WORD_DATA["coca_l1"] = {
  name: "COCA L1",
  color: "#22c55e",
  words: [
    {word:"the",definition:"used before a naming word to show which one you mean",chinese:"這個/那個（定冠詞）",sentence:"<strong>The</strong> cat is on the table.",tip:"THE 是英文最常見的字！",emoji:"👆",roots:["the"]},
    {word:"a",definition:"one; used before a word to mean just one thing",chinese:"一個（不定冠詞）",sentence:"I have <strong>a</strong> new toy.",tip:"A 用在子音開頭的字前面",emoji:"1️⃣",roots:["a"]},
    {word:"an",definition:"one; used before words starting with an a, e, i, o, or u sound",chinese:"一個（不定冠詞）",sentence:"She eats <strong>an</strong> egg every morning.",tip:"AN 用在母音開頭的字前面",emoji:"1️⃣",roots:["an"]},
    {word:"is",definition:"the form of 'be' used with he, she, or it",chinese:"是（第三人稱單數）",sentence:"He <strong>is</strong> my best friend.",tip:"IS 搭配 he/she/it 使用",emoji:"✅",roots:["is"]},
    {word:"are",definition:"the form of 'be' used with you, we, or they",chinese:"是（複數/第二人稱）",sentence:"They <strong>are</strong> very happy.",tip:"ARE 搭配 you/we/they 使用",emoji:"✅",roots:["are"]},
    {word:"was",definition:"the past form of 'is'; used for I, he, she, or it in the past",chinese:"是（過去式單數）",sentence:"She <strong>was</strong> at the store yesterday.",tip:"WAS 是 is 的過去式",emoji:"⏪",roots:["was"]},
    {word:"were",definition:"the past form of 'are'; used for you, we, or they in the past",chinese:"是（過去式複數）",sentence:"We <strong>were</strong> at the park.",tip:"WERE 是 are 的過去式",emoji:"⏪",roots:["were"]},
    {word:"be",definition:"to exist or to live; the base form of am, is, and are",chinese:"是/存在",sentence:"I want to <strong>be</strong> a pilot.",tip:"BE 是所有「是」的原形",emoji:"✨",roots:["be"]},
    {word:"been",definition:"the past form of 'be'; used after have or has",chinese:"已經是（過去分詞）",sentence:"I have <strong>been</strong> to Japan.",tip:"BEEN 用在 have 後面",emoji:"✈️",roots:["been"]},
    {word:"have",definition:"to own or hold something",chinese:"有/已經",sentence:"I <strong>have</strong> two cats at home.",tip:"HAVE 表示擁有或完成",emoji:"🤲",roots:["have"]},
    {word:"has",definition:"to own or hold something; the form of 'have' used with he, she, or it",chinese:"有（第三人稱）",sentence:"She <strong>has</strong> a beautiful smile.",tip:"HAS 是 have 的第三人稱",emoji:"🤲",roots:["has"]},
    {word:"had",definition:"the past form of 'have'; owned or held something before now",chinese:"有（過去式）",sentence:"He <strong>had</strong> a great idea.",tip:"HAD 是 have 的過去式",emoji:"⏪",roots:["had"]},
    {word:"do",definition:"to take an action or make something happen",chinese:"做/助動詞",sentence:"What do you <strong>do</strong> after school?",tip:"DO 也用來問問題",emoji:"💪",roots:["do"]},
    {word:"does",definition:"the form of 'do' used with he, she, or it",chinese:"做（第三人稱）",sentence:"She <strong>does</strong> her homework first.",tip:"DOES 搭配 he/she/it",emoji:"💪",roots:["does"]},
    {word:"did",definition:"the past form of 'do'",chinese:"做了（過去式）",sentence:"I <strong>did</strong> my best on the test.",tip:"DID 是 do 的過去式",emoji:"⏪",roots:["did"]},
    {word:"will",definition:"A word that shows something is going to happen in the future",chinese:"將要",sentence:"I <strong>will</strong> help you tomorrow.",tip:"WILL 表示未來要做的事",emoji:"🔮",roots:["will"]},
    {word:"would",definition:"A polite way to say 'will'; also used to imagine things",chinese:"會/將會",sentence:"I <strong>would</strong> like some juice.",tip:"WOULD 是比較有禮貌的說法",emoji:"🎩",roots:["would"]},
    {word:"can",definition:"to be able to do something",chinese:"能夠/會",sentence:"I <strong>can</strong> ride my bike fast.",tip:"CAN 表示有能力做某事",emoji:"💪",roots:["can"]},
    {word:"could",definition:"the past form of 'can'; also a polite way to ask",chinese:"能夠（過去式/禮貌）",sentence:"<strong>Could</strong> you help me, please?",tip:"COULD 比 CAN 更有禮貌",emoji:"🙏",roots:["could"]},
    {word:"should",definition:"used to say that something is a good idea to do",chinese:"應該",sentence:"You <strong>should</strong> eat your vegetables.",tip:"SHOULD 表示建議",emoji:"👍",roots:["should"]},
    {word:"may",definition:"to be allowed to do something; also shows something is possible",chinese:"可以/可能",sentence:"<strong>May</strong> I go outside?",tip:"MAY 用來請求許可",emoji:"🙋",roots:["may"]},
    {word:"might",definition:"used to say something is possible but not sure",chinese:"可能",sentence:"It <strong>might</strong> rain later.",tip:"MIGHT 表示不太確定",emoji:"🤔",roots:["might"]},
    {word:"must",definition:"used to say something has to be done",chinese:"必須",sentence:"You <strong>must</strong> brush your teeth.",tip:"MUST 表示一定要做",emoji:"❗",roots:["must"]},
    {word:"shall",definition:"used to talk about the future or to offer to do something",chinese:"將要/要不要",sentence:"<strong>Shall</strong> we go now?",tip:"SHALL 常用來提議",emoji:"🤝",roots:["shall"]},
    {word:"not",definition:"A word that says no or makes something mean the opposite",chinese:"不/沒有",sentence:"I am <strong>not</strong> afraid.",tip:"NOT 放在 be 動詞(am/is/are)或助動詞(do/can 等)後面表示否定，例：I am not…、I do not…",emoji:"🚫",roots:["not"]},
    {word:"no",definition:"A word that means 'not'; used to refuse or to say you disagree",chinese:"不/沒有",sentence:"<strong>No</strong>, thank you.",tip:"NO 是最直接的拒絕",emoji:"🙅",roots:["no"]},
    {word:"yes",definition:"A word you say to agree or to say something is true",chinese:"是/好",sentence:"<strong>Yes</strong>, I can do it!",tip:"YES 是最開心的回答",emoji:"👍",roots:["yes"]},
    {word:"and",definition:"A word used to join two things together",chinese:"和/而且",sentence:"I love cats <strong>and</strong> dogs.",tip:"AND 把兩個東西連在一起",emoji:"🤝",roots:["and"]},
    {word:"or",definition:"A word used to show a choice between two or more things",chinese:"或者",sentence:"Do you want cake <strong>or</strong> pie?",tip:"OR 表示二選一",emoji:"🔀",roots:["or"]},
    {word:"but",definition:"A word used to show a difference or a change of idea",chinese:"但是",sentence:"I want to go, <strong>but</strong> I am busy.",tip:"BUT 表示轉折",emoji:"↩️",roots:["but"]},
    {word:"if",definition:"A word used to talk about something that may or may not happen",chinese:"如果",sentence:"<strong>If</strong> it rains, we stay inside.",tip:"IF 表示條件",emoji:"❓",roots:["if"]},
    {word:"then",definition:"after that; used to tell what happens next",chinese:"然後/那麼",sentence:"First think, <strong>then</strong> speak.",tip:"THEN 表示接下來",emoji:"➡️",roots:["then"]},
    {word:"when",definition:"used to ask or tell at what time something happens",chinese:"什麼時候/當",sentence:"<strong>When</strong> is your birthday?",tip:"WHEN 問時間",emoji:"⏰",roots:["when"]},
    {word:"where",definition:"used to ask or tell in what place something is",chinese:"哪裡",sentence:"<strong>Where</strong> do you live?",tip:"WHERE 問地點",emoji:"📍",roots:["where"]},
    {word:"what",definition:"A word used to ask about a thing",chinese:"什麼",sentence:"<strong>What</strong> is your favorite color?",tip:"WHAT 問事物",emoji:"❓",roots:["what"]},
    {word:"who",definition:"A word used to ask which person",chinese:"誰",sentence:"<strong>Who</strong> is your best friend?",tip:"WHO 問人",emoji:"🧑",roots:["who"]},
    {word:"how",definition:"used to ask in what way something is or is done",chinese:"如何/怎麼",sentence:"<strong>How</strong> are you today?",tip:"HOW 問方式或程度",emoji:"🤷",roots:["how"]},
    {word:"why",definition:"A word used to ask the reason for something",chinese:"為什麼",sentence:"<strong>Why</strong> are you laughing?",tip:"WHY 問原因",emoji:"🤔",roots:["why"]},
    {word:"which",definition:"A word used to ask about a choice from a group",chinese:"哪一個",sentence:"<strong>Which</strong> one do you prefer?",tip:"WHICH 要從幾個中選一個",emoji:"👈",roots:["which"]},
    {word:"this",definition:"used to point to a thing that is near you",chinese:"這個",sentence:"<strong>This</strong> is my favorite song.",tip:"THIS 指近的東西",emoji:"👇",roots:["this"]},
    {word:"that",definition:"used to point to one thing away from you",chinese:"那個",sentence:"<strong>That</strong> mountain is very tall.",tip:"THAT 指遠的東西",emoji:"👉",roots:["that"]},
    {word:"these",definition:"used to point to more than one thing close to you",chinese:"這些",sentence:"<strong>These</strong> flowers are beautiful.",tip:"THESE 是 this 的複數",emoji:"👇",roots:["these"]},
    {word:"those",definition:"used to point to more than one thing away from you",chinese:"那些",sentence:"<strong>Those</strong> birds are singing.",tip:"THOSE 是 that 的複數",emoji:"👉",roots:["those"]},
    {word:"it",definition:"A word used for a thing or an animal you already talked about",chinese:"它",sentence:"<strong>It</strong> is a sunny day.",tip:"IT 代替事物或動物",emoji:"👆",roots:["it"]},
    {word:"he",definition:"A word used for a boy or a man",chinese:"他",sentence:"<strong>He</strong> is very smart.",tip:"HE 指男生",emoji:"👦",roots:["he"]},
    {word:"she",definition:"A word used for a girl or a woman",chinese:"她",sentence:"<strong>She</strong> is very kind.",tip:"SHE 指女生",emoji:"👧",roots:["she"]},
    {word:"we",definition:"A word for me and other people together",chinese:"我們",sentence:"<strong>We</strong> are a great team.",tip:"WE 包括說話的人",emoji:"👫",roots:["we"]},
    {word:"they",definition:"A word for a group of people, animals, or things",chinese:"他們/她們/它們",sentence:"<strong>They</strong> are playing outside.",tip:"THEY 指兩個以上的人或物",emoji:"👥",roots:["they"]},
    {word:"me",definition:"the word I use for myself when something is done to me",chinese:"我（受格）",sentence:"Please help <strong>me</strong>.",tip:"ME 在動詞後面用",emoji:"🙋",roots:["me"]},
    {word:"him",definition:"the word for a boy or man you do something to",chinese:"他（受格）",sentence:"I gave <strong>him</strong> a cookie.",tip:"HIM 是 he 的受格",emoji:"👦",roots:["him"]},
    {word:"her",definition:"the word for a girl or woman you do something to; also means belonging to her",chinese:"她（受格）/她的",sentence:"I see <strong>her</strong> every day.",tip:"HER 可以是受格也可以是所有格",emoji:"👧",roots:["her"]},
    {word:"us",definition:"A word for me and other people together",chinese:"我們（受格）",sentence:"Come with <strong>us</strong>!",tip:"US 是 we 的受格",emoji:"👫",roots:["us"]},
    {word:"them",definition:"A word for other people or things you do something to",chinese:"他們（受格）",sentence:"I helped <strong>them</strong> clean up.",tip:"THEM 是 they 的受格",emoji:"👥",roots:["them"]},
    {word:"my",definition:"belonging to me",chinese:"我的",sentence:"<strong>My</strong> dog is very cute.",tip:"MY 表示屬於我的",emoji:"🙋",roots:["my"]},
    {word:"your",definition:"belonging to you",chinese:"你的/你們的",sentence:"What is <strong>your</strong> name?",tip:"YOUR 表示屬於你的",emoji:"👉",roots:["your"]},
    {word:"his",definition:"belonging to him",chinese:"他的",sentence:"<strong>His</strong> room is very neat.",tip:"HIS 表示屬於他的",emoji:"👦",roots:["his"]},
    {word:"its",definition:"belonging to it",chinese:"它的",sentence:"The dog wags <strong>its</strong> tail.",tip:"ITS 沒有撇號！it's = it is",emoji:"🐕",roots:["its"]},
    {word:"our",definition:"belonging to us",chinese:"我們的",sentence:"This is <strong>our</strong> school.",tip:"OUR 表示屬於我們的",emoji:"👫",roots:["our"]},
    {word:"their",definition:"belonging to them",chinese:"他們的",sentence:"<strong>Their</strong> house is very big.",tip:"THEIR 不要和 there 搞混",emoji:"👥",roots:["their"]},
    {word:"mine",definition:"A thing that belongs to me",chinese:"我的（名詞性）",sentence:"This pencil is <strong>mine</strong>.",tip:"MINE 後面不加名詞",emoji:"🙋",roots:["mine"]},
    {word:"yours",definition:"A thing that belongs to you",chinese:"你的（名詞性）",sentence:"Is this bag <strong>yours</strong>?",tip:"YOURS 後面不加名詞",emoji:"👉",roots:["yours"]},
    {word:"I",definition:"the word a person uses to talk about themselves",chinese:"我",sentence:"<strong>I</strong> love my family.",tip:"I 永遠大寫！",emoji:"🙋",roots:["I"]},
    {word:"you",definition:"the word for the person being talked to",chinese:"你/你們",sentence:"<strong>You</strong> are amazing!",tip:"YOU 可以指一個人或多人",emoji:"👉",roots:["you"]},
    {word:"all",definition:"every one of them, with none left out",chinese:"全部/所有",sentence:"<strong>All</strong> the children are here.",tip:"ALL 表示全部都算在內",emoji:"💯",roots:["all"]},
    {word:"each",definition:"every one, taken one at a time",chinese:"每一個",sentence:"<strong>Each</strong> student got a prize.",tip:"EACH 強調一個一個",emoji:"☝️",roots:["each"]},
    {word:"every",definition:"all of them, one by one",chinese:"每一個",sentence:"I exercise <strong>every</strong> morning.",tip:"EVERY 強調全部無例外",emoji:"📅",roots:["every"]},
    {word:"both",definition:"the two of them together",chinese:"兩個都",sentence:"<strong>Both</strong> answers are correct.",tip:"BOTH 只能用在兩個",emoji:"✌️",roots:["both"]},
    {word:"few",definition:"A small number of things",chinese:"少數/幾個",sentence:"I have a <strong>few</strong> questions.",tip:"A FEW 表示有一些",emoji:"🤏",roots:["few"]},
    {word:"more",definition:"A bigger amount than before",chinese:"更多",sentence:"I want <strong>more</strong> time to finish.",tip:"MORE 是 many/much 的比較級",emoji:"➕",roots:["more"]},
    {word:"most",definition:"almost all of them",chinese:"最多/大部分",sentence:"<strong>Most</strong> people love music.",tip:"MOST 表示最高程度",emoji:"🏆",roots:["most"]},
    {word:"other",definition:"the different one, not this one",chinese:"其他的",sentence:"The <strong>other</strong> kids went home.",tip:"OTHER 表示剩下的",emoji:"👈",roots:["other"]},
    {word:"another",definition:"one more of the same kind",chinese:"另一個",sentence:"Can I have <strong>another</strong> chance?",tip:"ANOTHER = AN + OTHER",emoji:"➕",roots:["another"]},
    {word:"such",definition:"used to make a word stronger, like 'so'",chinese:"如此/這樣的",sentence:"It is <strong>such</strong> a nice day!",tip:"SUCH 加強語氣",emoji:"😮",roots:["such"]},
    {word:"any",definition:"some, even just one",chinese:"任何/一些",sentence:"Do you have <strong>any</strong> questions?",tip:"ANY 用在問句和否定句",emoji:"❓",roots:["any"]},
    {word:"same",definition:"just alike, not different",chinese:"相同的",sentence:"We wear the <strong>same</strong> shirt.",tip:"SAME 前面常加 the",emoji:"👯",roots:["same"]},
    {word:"different",definition:"not the same as another",chinese:"不同的",sentence:"We have <strong>different</strong> ideas.",tip:"DIFFERENT = dif(分開)＋fer(帶)＋ent(形容詞字尾)，帶往不同方向 → 不同的",emoji:"🔀",roots:["dif","fer","ent"]},
    {word:"new",definition:"just made or just bought, not old",chinese:"新的",sentence:"I got a <strong>new</strong> backpack!",tip:"NEW 和 KNEW 發音一樣",emoji:"✨",roots:["new"]},
    {word:"first",definition:"coming before all the others",chinese:"第一/首先",sentence:"I am <strong>first</strong> in line.",tip:"FIRST 與 FORE(前面)同源，原意是「最前面的」→ 第一",emoji:"🥇",roots:["first"]},
    {word:"last",definition:"coming after all the others",chinese:"最後的/上一個",sentence:"This is the <strong>last</strong> question.",tip:"LAST 可以指最後或上次",emoji:"🔚",roots:["last"]},
    {word:"next",definition:"coming right after this one",chinese:"下一個",sentence:"See you <strong>next</strong> time!",tip:"NEXT 表示接下來的",emoji:"⏭️",roots:["next"]},
    {word:"own",definition:"belonging to you and no one else",chinese:"自己的/擁有",sentence:"I clean my <strong>own</strong> room.",tip:"OWN 強調是自己的",emoji:"🏠",roots:["own"]},
    {word:"only",definition:"being the single one, with no others",chinese:"只有/唯一的",sentence:"She is the <strong>only</strong> one here.",tip:"ONLY 真的來自 ONE(一)＋-LY，本意是「只有一個」→ 唯一",emoji:"☝️",roots:["only"]},
    {word:"just",definition:"a very short time ago; also only or simply",chinese:"剛剛/只是",sentence:"I <strong>just</strong> finished eating.",tip:"JUST 有「剛剛」「只是」的意思",emoji:"👌",roots:["just"]},
    {word:"also",definition:"too; in addition to something else",chinese:"也/還",sentence:"I <strong>also</strong> enjoy painting.",tip:"ALSO 放在動詞前面",emoji:"➕",roots:["also"]},
    {word:"very",definition:"to a great degree; a lot",chinese:"非常",sentence:"The movie is <strong>very</strong> funny.",tip:"VERY 加強形容詞",emoji:"💪",roots:["very"]},
    {word:"too",definition:"also; as well",chinese:"也/太",sentence:"I like ice cream <strong>too</strong>!",tip:"TOO 放句尾表示「也」",emoji:"➕",roots:["too"]},
    {word:"so",definition:"very much; to a great amount",chinese:"這麼/所以",sentence:"I am <strong>so</strong> happy today!",tip:"SO 加強語氣或表示因果",emoji:"😊",roots:["so"]},
    {word:"really",definition:"truly; very much",chinese:"真的/非常",sentence:"I <strong>really</strong> love pizza.",tip:"REALLY = REAL + LY",emoji:"❗",roots:["real","ly"]},
    {word:"still",definition:"continuing up to now",chinese:"仍然/還是",sentence:"Are you <strong>still</strong> hungry?",tip:"STILL 表示狀態持續",emoji:"⏳",roots:["still"]},
    {word:"even",definition:"used to show something is surprising",chinese:"甚至/即使",sentence:"<strong>Even</strong> the teacher laughed!",tip:"EVEN 加強意外的感覺",emoji:"😲",roots:["even"]},
    {word:"again",definition:"one more time; once more",chinese:"再一次",sentence:"Can we do it <strong>again</strong>?",tip:"AGAIN 的 AI 常發 /ɛ/ 的音（唸成 a-gen）",emoji:"🔄",roots:["again"]},
    {word:"already",definition:"before now; by this time",chinese:"已經",sentence:"I <strong>already</strong> ate dinner.",tip:"ALREADY = ALL + READY",emoji:"✅",roots:["already"]},
    {word:"always",definition:"at all times; every time",chinese:"總是/一直",sentence:"She <strong>always</strong> smiles at me.",tip:"ALWAYS = ALL + WAYS",emoji:"♾️",roots:["always"]},
    {word:"never",definition:"at no time; not ever",chinese:"從不",sentence:"I <strong>never</strong> give up.",tip:"NEVER 真的來自 ne(不)＋ever(曾經) → 從不",emoji:"🙅",roots:["never"]},
    {word:"often",definition:"many times; again and again",chinese:"經常",sentence:"We <strong>often</strong> play after school.",tip:"OFTEN 的 T 可以不發音；來自 oft(常)＋-en",emoji:"🔁",roots:["often"]},
    {word:"sometimes",definition:"now and then; not all the time",chinese:"有時候",sentence:"I <strong>sometimes</strong> stay up late.",tip:"SOMETIMES = SOME + TIMES",emoji:"🎲",roots:["sometimes"]},
    {word:"usually",definition:"most of the time",chinese:"通常",sentence:"I <strong>usually</strong> wake up at seven.",tip:"USUALLY = USUAL + LY",emoji:"📅",roots:["usual","ly"]},
    {word:"about",definition:"having to do with a subject",chinese:"關於/大約",sentence:"Tell me <strong>about</strong> your weekend.",tip:"ABOUT 有「關於」和「大約」兩個意思要記",emoji:"💬",roots:["about"]},
    {word:"after",definition:"following in time; later than something",chinese:"在...之後",sentence:"We rest <strong>after</strong> lunch.",tip:"AFTER（之後）和 BEFORE（之前）意思相反",emoji:"⏩",roots:["after"]},
    {word:"before",definition:"earlier than; ahead of in time",chinese:"在...之前",sentence:"Wash hands <strong>before</strong> eating.",tip:"BEFORE = BE + FORE",emoji:"⏪",roots:["before"]},
    {word:"between",definition:"in the space that separates two things",chinese:"在...之間",sentence:"The park is <strong>between</strong> two buildings.",tip:"BETWEEN 用在兩者之間",emoji:"↔️",roots:["between"]},
    {word:"from",definition:"showing where something starts or comes from",chinese:"從/來自",sentence:"I am <strong>from</strong> Taipei.",tip:"FROM 表示起點",emoji:"📍",roots:["from"]},
    {word:"into",definition:"to the inside of something",chinese:"進入",sentence:"The frog jumped <strong>into</strong> the pond.",tip:"INTO = IN + TO",emoji:"➡️",roots:["into"]},
    {word:"over",definition:"above or higher than something",chinese:"在...上方/超過",sentence:"The rainbow is <strong>over</strong> the hill.",tip:"OVER 表示上方經過",emoji:"🌈",roots:["over"]},
    {word:"under",definition:"below or beneath something",chinese:"在...下面",sentence:"The cat hid <strong>under</strong> the bed.",tip:"UNDER（下面）和 OVER（上面）意思相反",emoji:"⬇️",roots:["under"]},
    {word:"up",definition:"toward a higher place",chinese:"向上",sentence:"Look <strong>up</strong> at the sky!",tip:"UP 只有兩個字母",emoji:"⬆️",roots:["up"]},
    {word:"down",definition:"toward a lower place",chinese:"向下",sentence:"The ball rolled <strong>down</strong> the hill.",tip:"DOWN 和 UP 相反",emoji:"⬇️",roots:["down"]},
    {word:"out",definition:"away from the inside; not inside",chinese:"出去/外面",sentence:"Let's go <strong>out</strong> and play.",tip:"OUT 和 IN 相反",emoji:"🚪",roots:["out"]},
    {word:"off",definition:"so that something stops working; also away from a place",chinese:"關掉/離開",sentence:"Turn <strong>off</strong> the TV.",tip:"OFF 和 ON 相反",emoji:"📴",roots:["off"]},
    {word:"away",definition:"to or at another place; far from here",chinese:"離開/遠處",sentence:"The bird flew <strong>away</strong>.",tip:"AWAY = A + WAY",emoji:"🐦",roots:["away"]},
    {word:"back",definition:"to the place you came from",chinese:"回來/背部",sentence:"Come <strong>back</strong> soon!",tip:"BACK 表示回到原處",emoji:"↩️",roots:["back"]},
    {word:"through",definition:"in one side and out the other",chinese:"穿過/通過",sentence:"We walked <strong>through</strong> the forest.",tip:"THROUGH 的 GH 不發音，OU 拼出 /oo/ 母音",emoji:"🌲",roots:["through"]},
    {word:"around",definition:"on every side of you",chinese:"周圍/到處",sentence:"Look <strong>around</strong> you.",tip:"AROUND = A + ROUND",emoji:"🔄",roots:["around"]},
    {word:"along",definition:"following the length of something",chinese:"沿著",sentence:"Walk <strong>along</strong> the river.",tip:"ALONG = A + LONG",emoji:"🏞️",roots:["along"]},
    {word:"across",definition:"on or to the other side of something",chinese:"橫過/對面",sentence:"The store is <strong>across</strong> the street.",tip:"ACROSS = A + CROSS",emoji:"↔️",roots:["across"]},
    {word:"against",definition:"in opposition to something; or touching and pressing on something",chinese:"反對/靠著",sentence:"Don't lean <strong>against</strong> the wall.",tip:"AGAINST 來自 again(再/相對)＋-st，有「對抗、相對」的意思",emoji:"🤼",roots:["against"]},
    {word:"until",definition:"up to the time when something happens",chinese:"直到",sentence:"Wait <strong>until</strong> I come back.",tip:"UNTIL 的 UN 不是「不」的意思，這裡＝「直到」，＋til(till 到)",emoji:"⏳",roots:["until"]},
    {word:"since",definition:"from a past time up to now",chinese:"自從/因為",sentence:"I have been here <strong>since</strong> morning.",tip:"SINCE 後面接時間點",emoji:"📅",roots:["since"]},
    {word:"during",definition:"all through a period of time",chinese:"在...期間",sentence:"Be quiet <strong>during</strong> class.",tip:"DURING = DUR(持續) + ING",emoji:"⏱️",roots:["during"]},
    {word:"while",definition:"at the same time as something else",chinese:"當...的時候/一會兒",sentence:"I listen to music <strong>while</strong> I study.",tip:"WHILE 表示同時進行",emoji:"⏱️",roots:["while"]},
    {word:"because",definition:"used to tell the reason why something happens",chinese:"因為",sentence:"I am happy <strong>because</strong> you came.",tip:"BECAUSE = BE + CAUSE（原因）",emoji:"💡",roots:["because"]},
    {word:"although",definition:"even though something else is true",chinese:"雖然",sentence:"<strong>Although</strong> it rained, we had fun.",tip:"ALTHOUGH = AL（源自 all，全然）+ THOUGH（雖然）",emoji:"🌧️",roots:["al","though"]},
    {word:"though",definition:"used to add a fact that seems surprising",chinese:"雖然/不過",sentence:"The test was hard, <strong>though</strong> I passed.",tip:"THOUGH 可放句尾",emoji:"💪",roots:["though"]},
    {word:"however",definition:"used to add something that seems the opposite",chinese:"然而/不過",sentence:"I tried hard; <strong>however</strong>, I lost.",tip:"HOWEVER = HOW + EVER",emoji:"↩️",roots:["how","ever"]},
    {word:"therefore",definition:"for that reason; because of that",chinese:"因此/所以",sentence:"He was sick, <strong>therefore</strong> he stayed home.",tip:"THEREFORE = THERE + FORE",emoji:"➡️",roots:["there","fore"]},
    {word:"instead",definition:"in the place of something else",chinese:"代替/反而",sentence:"I had fruit <strong>instead</strong> of candy.",tip:"INSTEAD = IN + STEAD（地方）",emoji:"🔀",roots:["instead"]},
    {word:"without",definition:"not having or not with someone or something",chinese:"沒有/不帶",sentence:"Don't leave <strong>without</strong> me!",tip:"WITHOUT = WITH + OUT",emoji:"🚫",roots:["with","out"]},
    {word:"within",definition:"inside something; not going past it",chinese:"在...之內",sentence:"Stay <strong>within</strong> the lines.",tip:"WITHIN = WITH + IN",emoji:"⭕",roots:["with","in"]},
    {word:"toward",definition:"in the direction of something",chinese:"朝向",sentence:"He walked <strong>toward</strong> the door.",tip:"TOWARD = TO + WARD（方向）",emoji:"➡️",roots:["toward"]},
    {word:"among",definition:"in the middle of a group of people or things",chinese:"在...之中",sentence:"She sat <strong>among</strong> her friends.",tip:"AMONG 用在三個以上的人事物之間（兩者之間用 between）",emoji:"👥",roots:["among"]},
    {word:"above",definition:"in a higher place than something",chinese:"在...上方",sentence:"The plane flew <strong>above</strong> the clouds.",tip:"ABOVE（上方）和 BELOW（下方）意思相反",emoji:"⬆️",roots:["above"]},
    {word:"below",definition:"in a lower place than something",chinese:"在...下方",sentence:"Fish swim <strong>below</strong> the surface.",tip:"BELOW = BE + LOW",emoji:"⬇️",roots:["below"]},
    {word:"behind",definition:"at the back of something",chinese:"在...後面",sentence:"The cat hid <strong>behind</strong> the sofa.",tip:"BEHIND = BE + HIND（後面）",emoji:"🔙",roots:["behind"]},
    {word:"beside",definition:"right next to someone or something",chinese:"在...旁邊",sentence:"Sit <strong>beside</strong> me.",tip:"BESIDE = BE + SIDE",emoji:"↔️",roots:["beside"]},
    {word:"beyond",definition:"going past a limit or more than something; also on the far side of something",chinese:"超越/在...之外",sentence:"The view <strong>beyond</strong> the hill is amazing.",tip:"BEYOND = be + yond(yonder 那邊)，指「越過那一邊」",emoji:"🌄",roots:["beyond"]},
    {word:"near",definition:"close to something; not far away",chinese:"靠近",sentence:"The store is <strong>near</strong> my house.",tip:"NEAR 和 FAR 相反",emoji:"📍",roots:["near"]},
    {word:"far",definition:"A long way away",chinese:"遠的",sentence:"The airport is very <strong>far</strong>.",tip:"FAR 和 NEAR 相反",emoji:"🌙",roots:["far"]},
    {word:"well",definition:"in a good or nice way",chinese:"好地/健康的",sentence:"She sings very <strong>well</strong>.",tip:"WELL 是 good 的副詞形式",emoji:"👏",roots:["well"]},
    {word:"better",definition:"more good than something else",chinese:"更好的",sentence:"Today is <strong>better</strong> than yesterday.",tip:"BETTER 是 good 的比較級（不規則變化：good→better→best）",emoji:"📈",roots:["better"]},
    {word:"best",definition:"more good than all the others",chinese:"最好的",sentence:"You are the <strong>best</strong>!",tip:"BEST 是 good 的最高級",emoji:"🏆",roots:["best"]},
    {word:"less",definition:"A smaller amount of something",chinese:"更少的",sentence:"I eat <strong>less</strong> sugar now.",tip:"LESS 和 MORE 相反",emoji:"➖",roots:["less"]},
    {word:"least",definition:"the smallest amount of all",chinese:"最少的",sentence:"This costs the <strong>least</strong>.",tip:"LEAST 是 little 的最高級",emoji:"🤏",roots:["least"]},
    {word:"enough",definition:"as much as you need",chinese:"足夠的",sentence:"Do you have <strong>enough</strong> time?",tip:"ENOUGH 的 GH 發 /f/ 音（與 laugh/rough/tough 同）",emoji:"👌",roots:["enough"]},
    {word:"quite",definition:"very; a lot",chinese:"相當/蠻",sentence:"It is <strong>quite</strong> cold today.",tip:"QUITE 和 QUIET 很像但不同",emoji:"😮",roots:["quite"]},
    {word:"rather",definition:"fairly or to some degree; also used to say what you would like more",chinese:"相當/寧可",sentence:"I would <strong>rather</strong> stay home.",tip:"RATHER 表示偏好",emoji:"🤔",roots:["rather"]},
    {word:"pretty",definition:"nice to look at; also means quite/fairly",chinese:"漂亮的/相當",sentence:"She is <strong>pretty</strong> smart.",tip:"PRETTY 當形容詞是「漂亮的」，當副詞是「相當」",emoji:"🌸",roots:["pretty"]},
    {word:"almost",definition:"very nearly but not quite",chinese:"幾乎",sentence:"I <strong>almost</strong> forgot!",tip:"ALMOST 由 all（全部）+ most（大部分）演變而來，意為「幾乎、差不多」",emoji:"😅",roots:["almost"]},
    {word:"together",definition:"with each other; as a group",chinese:"一起",sentence:"Let's work <strong>together</strong>.",tip:"記憶法(非字源)：拆成 TO-GET-HER 好記拼字；真正與 gather(聚集)同源",emoji:"🤝",roots:["together"]},
    {word:"alone",definition:"with no one else around",chinese:"獨自/孤單的",sentence:"I don't want to be <strong>alone</strong>.",tip:"ALONE 源自 all（完全）+ one（一個人），意為「獨自」；lone 其實是後來從 alone 去掉 a- 才產生的",emoji:"🧍",roots:["alone"]},
    {word:"else",definition:"other; besides this",chinese:"其他的/另外",sentence:"What <strong>else</strong> do you need?",tip:"ELSE 常跟疑問詞一起用",emoji:"❓",roots:["else"]},
    {word:"ago",definition:"in the past, before now",chinese:"...之前",sentence:"Two years <strong>ago</strong>, I moved here.",tip:"AGO 放在時間後面",emoji:"⏪",roots:["ago"]},
    {word:"yet",definition:"up to now; until this time",chinese:"還/尚未",sentence:"I have not finished <strong>yet</strong>.",tip:"YET 用在否定句和問句",emoji:"⏳",roots:["yet"]},
    {word:"soon",definition:"in a short time from now",chinese:"很快/不久",sentence:"I will be there <strong>soon</strong>.",tip:"SOON 有兩個 O",emoji:"⏰",roots:["soon"]},
    {word:"later",definition:"at a time after now",chinese:"稍後/之後",sentence:"See you <strong>later</strong>!",tip:"LATER = LAT（晚，來自 late）+ ER（比較級字尾，更…）：更晚",emoji:"👋",roots:["lat","er"]},
    {word:"early",definition:"near the start of the day or a time",chinese:"早的/提早",sentence:"I wake up <strong>early</strong>.",tip:"記憶法：EARLY 開頭的 EAR 剛好長得像 ear（耳朵），只是幫記拼字，並不是字根",emoji:"🌅",roots:["early"]},
    {word:"late",definition:"after the right or usual time",chinese:"晚的/遲到",sentence:"Don't be <strong>late</strong> for class.",tip:"LATE 和 EARLY 相反",emoji:"⏰",roots:["late"]},
    {word:"high",definition:"going up a long way from the ground",chinese:"高的",sentence:"The mountain is very <strong>high</strong>.",tip:"HIGH 的 GH 不發音",emoji:"🏔️",roots:["high"]},
    {word:"low",definition:"not high; also used for a soft, quiet sound",chinese:"低的；(聲音)小聲的、輕柔的",sentence:"Speak in a <strong>low</strong> voice.",tip:"LOW 和 HIGH 相反",emoji:"🔉",roots:["low"]},
    {word:"large",definition:"big in size",chinese:"大的",sentence:"We need a <strong>large</strong> box.",tip:"LARGE 比 BIG 正式",emoji:"📦",roots:["large"]},
    {word:"great",definition:"very good; wonderful",chinese:"很棒的/偉大的",sentence:"You did a <strong>great</strong> job!",tip:"GREAT 的 EA 發 /eɪ/",emoji:"🌟",roots:["great"]},
    {word:"little",definition:"small in size",chinese:"小的/一點點",sentence:"The <strong>little</strong> puppy is so cute.",tip:"LITTLE 有兩個 T，字尾 -tle 常見（如 bottle、gentle）",emoji:"🤏",roots:["little"]},
    {word:"whole",definition:"all of something, with no part left out",chinese:"整個的/全部",sentence:"I read the <strong>whole</strong> story.",tip:"WHOLE 的 W 不發音",emoji:"⭕",roots:["whole"]},
    {word:"real",definition:"actually there, not fake or pretend",chinese:"真實的",sentence:"Is that a <strong>real</strong> dinosaur?",tip:"REAL 和 REALLY 是一家人",emoji:"💎",roots:["real"]},
    {word:"true",definition:"matching what really happened; not made up",chinese:"真的/正確的",sentence:"Is the story <strong>true</strong>?",tip:"TRUE 和 REAL 意思接近",emoji:"✅",roots:["true"]},
    {word:"clear",definition:"easy to see or understand; also (of the sky) with no clouds",chinese:"清楚的/晴朗的",sentence:"The sky is <strong>clear</strong> tonight.",tip:"CLEAR 想到透明乾淨",emoji:"💧",roots:["clear"]},
    {word:"dark",definition:"with little or no light",chinese:"黑暗的",sentence:"It gets <strong>dark</strong> at night.",tip:"DARK 和 LIGHT 相反",emoji:"🌑",roots:["dark"]},
    {word:"light",definition:"the brightness that lets you see things",chinese:"光/輕的/亮的",sentence:"Turn on the <strong>light</strong>, please.",tip:"LIGHT 有三個意思",emoji:"💡",roots:["light"]},
    {word:"hot",definition:"very warm, so it can burn you",chinese:"熱的",sentence:"Be careful, the soup is <strong>hot</strong>!",tip:"HOT 和 COLD 相反",emoji:"🔥",roots:["hot"]},
    {word:"nice",definition:"good and pleasant",chinese:"好的/友善的",sentence:"Have a <strong>nice</strong> day!",tip:"NICE 和 ICE 押韻",emoji:"😊",roots:["nice"]},
    {word:"fine",definition:"feeling well and okay",chinese:"好的/很好",sentence:"I feel <strong>fine</strong>, thanks.",tip:"FINE 的意思很多",emoji:"👌",roots:["fine"]},
    {word:"beautiful",definition:"very pretty to look at",chinese:"美麗的",sentence:"The sunset is <strong>beautiful</strong>.",tip:"BEAUTIFUL = BEAUTI（美，來自 beauty）+ FUL（充滿…的，形容詞字尾）：充滿美的",emoji:"🌅",roots:["beauti","ful"]},
    {word:"wonderful",definition:"very good and makes you happy",chinese:"很棒的/美妙的",sentence:"We had a <strong>wonderful</strong> vacation.",tip:"WONDERFUL = WONDER（驚奇、奇妙）+ FUL（充滿…的，形容詞字尾）：充滿驚奇的",emoji:"🎉",roots:["wonder","ful"]},
    {word:"terrible",definition:"very bad or scary",chinese:"糟糕的/可怕的",sentence:"I had a <strong>terrible</strong> dream.",tip:"TERRIBLE = TERR（使驚恐，來自拉丁 terrere）+ IBLE（可…的，形容詞字尾）：令人恐懼的",emoji:"😱",roots:["terr","ible"]},
    {word:"sorry",definition:"feeling bad about something you did",chinese:"抱歉的",sentence:"I am <strong>sorry</strong> I broke it.",tip:"SORRY 有兩個 R；與 sore(痛)同源，指「心裡難過」",emoji:"🙏",roots:["sorry"]},
    {word:"afraid",definition:"scared that something bad may happen",chinese:"害怕的",sentence:"Don't be <strong>afraid</strong> of the dark.",tip:"AFRAID 來自古字 affray(使驚嚇)；常用 be afraid of…",emoji:"😨",roots:["afraid"]},
    {word:"certain",definition:"very sure that something is true",chinese:"確定的/某些",sentence:"I am <strong>certain</strong> he will come.",tip:"CERTAIN 的 CERT＝「確定、確實」(如 certificate 證書)，-ain 是字尾",emoji:"✅",roots:["certain"]},
    {word:"simple",definition:"easy to do or understand",chinese:"簡單的",sentence:"The recipe is very <strong>simple</strong>.",tip:"SIMPLE 和 EASY 意思相近",emoji:"👌",roots:["simple"]},
    {word:"special",definition:"not like the usual ones; extra important",chinese:"特別的",sentence:"Today is a <strong>special</strong> day.",tip:"SPECIAL＝spec（看／種類，如 species 種類）＋-ial（形容詞字尾）＝特別的",emoji:"⭐",roots:["spec","ial"]},
    {word:"poor",definition:"having very little money",chinese:"貧窮的/可憐的",sentence:"The <strong>poor</strong> family had very little money.",tip:"POOR 和 RICH 相反",emoji:"😢",roots:["poor"]},
    {word:"rich",definition:"having a lot of money",chinese:"富有的",sentence:"The <strong>rich</strong> man owns three cars.",tip:"RICH 和 POOR 相反",emoji:"💰",roots:["rich"]},
    {word:"strong",definition:"having great force or power",chinese:"強壯的",sentence:"The wind is very <strong>strong</strong>.",tip:"STRONG 和 WEAK 相反",emoji:"💪",roots:["strong"]},
    {word:"weak",definition:"not strong; having little power",chinese:"弱的",sentence:"I feel <strong>weak</strong> when I am sick.",tip:"WEAK 和 STRONG 相反",emoji:"🤒",roots:["weak"]},
    {word:"deep",definition:"going far down from the top",chinese:"深的",sentence:"The ocean is very <strong>deep</strong>.",tip:"DEEP 有兩個 E",emoji:"🌊",roots:["deep"]},
    {word:"wide",definition:"big from one side to the other side",chinese:"寬的",sentence:"Open your eyes <strong>wide</strong>.",tip:"WIDE 和 NARROW 相反",emoji:"↔️",roots:["wide"]},
    {word:"heavy",definition:"weighing a lot; hard to lift",chinese:"重的",sentence:"This box is too <strong>heavy</strong> for me.",tip:"HEAVY 和 LIGHT 相反",emoji:"🏋️",roots:["heavy"]},
    {word:"kind",definition:"nice and caring toward other people",chinese:"善良的/種類",sentence:"Be <strong>kind</strong> to others.",tip:"KIND 有兩個意思",emoji:"💖",roots:["kind"]},
    {word:"dear",definition:"A loving word used to greet someone you care about",chinese:"親愛的/昂貴的",sentence:"<strong>Dear</strong> Mom, I love you.",tip:"DEAR 寫信時用",emoji:"💌",roots:["dear"]},
    {word:"in",definition:"inside something",chinese:"在...裡面",sentence:"The toy is <strong>in</strong> the box.",tip:"IN 和 OUT 相反",emoji:"📦",roots:["in"]},
    {word:"on",definition:"resting on top of something",chinese:"在...上面",sentence:"The cup is <strong>on</strong> the shelf.",tip:"ON 表示接觸在上面",emoji:"📚",roots:["on"]},
    {word:"at",definition:"used to point to a time or place",chinese:"在（地點/時間）",sentence:"I wake up <strong>at</strong> seven.",tip:"AT 用在具體地點和時間",emoji:"📍",roots:["at"]},
    {word:"to",definition:"showing the direction you move toward",chinese:"到/向",sentence:"I walk <strong>to</strong> the park.",tip:"TO 表示方向或目的",emoji:"➡️",roots:["to"]},
    {word:"for",definition:"showing who something is meant for",chinese:"為了/給",sentence:"This gift is <strong>for</strong> you.",tip:"FOR 表示目的或對象",emoji:"🎁",roots:["for"]},
    {word:"with",definition:"used to show people or things are together",chinese:"和/跟/帶著",sentence:"I play <strong>with</strong> my friends.",tip:"WITH 表示一起或使用",emoji:"🤝",roots:["with"]},
    {word:"of",definition:"used to show what something holds or belongs to",chinese:"...的/屬於",sentence:"A glass <strong>of</strong> milk, please.",tip:"OF 是英文第二常見的字",emoji:"📎",roots:["of"]},
    {word:"by",definition:"used to show who did something",chinese:"被/在旁邊/搭乘",sentence:"The story was written <strong>by</strong> him.",tip:"BY 有很多意思",emoji:"📖",roots:["by"]},
    {word:"as",definition:"used to show a job or role someone has",chinese:"作為/像...一樣",sentence:"She works <strong>as</strong> a teacher.",tip:"AS 用來比較或表身份",emoji:"🔄",roots:["as"]},
    {word:"thing",definition:"an object you can see, hold, or talk about",chinese:"東西/事情",sentence:"What is that <strong>thing</strong>?",tip:"THING 可以指任何東西",emoji:"🔮",roots:["thing"]},
    {word:"people",definition:"more than one person; men, women, and kids",chinese:"人們",sentence:"Many <strong>people</strong> love this park.",tip:"PEOPLE 的複數不加 S",emoji:"👥",roots:["people"]},
    {word:"man",definition:"A grown-up male person",chinese:"男人",sentence:"That <strong>man</strong> is very tall.",tip:"MAN 的複數是 MEN",emoji:"👨",roots:["man"]},
    {word:"woman",definition:"A grown-up female person",chinese:"女人",sentence:"The <strong>woman</strong> is a pilot.",tip:"WOMAN 的複數是 WOMEN",emoji:"👩",roots:["woman"]},
    {word:"child",definition:"A young boy or girl",chinese:"小孩",sentence:"Every <strong>child</strong> needs love.",tip:"CHILD 的複數是 CHILDREN",emoji:"🧒",roots:["child"]},
    {word:"children",definition:"young boys and girls, more than one",chinese:"小孩們",sentence:"The <strong>children</strong> are laughing.",tip:"CHILDREN 是 CHILD 的複數",emoji:"👦👧",roots:["children"]},
    {word:"world",definition:"the Earth and all the people and places on it",chinese:"世界",sentence:"The <strong>world</strong> is full of wonder.",tip:"WORLD 裡面有 OR",emoji:"🌍",roots:["world"]},
    {word:"life",definition:"the time when a person is alive",chinese:"生活/生命",sentence:"I love my <strong>life</strong>!",tip:"LIFE 的複數是 LIVES",emoji:"❤️",roots:["life"]},
    {word:"house",definition:"A building where a family lives",chinese:"房子",sentence:"We painted our <strong>house</strong> blue.",tip:"HOUSE 和 MOUSE 押韻（都以 -OUSE 結尾）",emoji:"🏠",roots:["house"]},
    {word:"place",definition:"A spot or area where something is",chinese:"地方",sentence:"This is a nice <strong>place</strong> to rest.",tip:"PLACE 和 SPACE 押韻",emoji:"📍",roots:["place"]},
    {word:"room",definition:"A space inside a house with walls, like a bedroom",chinese:"房間",sentence:"My <strong>room</strong> is very tidy.",tip:"ROOM 有兩個 O",emoji:"🛏️",roots:["room"]},
    {word:"night",definition:"the dark time when the sun is down",chinese:"夜晚",sentence:"Good <strong>night</strong>! Sweet dreams.",tip:"NIGHT 的 GH 不發音",emoji:"🌙",roots:["night"]},
    {word:"morning",definition:"the early part of the day, after you wake up",chinese:"早上",sentence:"Good <strong>morning</strong>, everyone!",tip:"MORNING = MORN + ING",emoji:"🌅",roots:["morning"]},
    {word:"way",definition:"a road or path from one place to another; also how you do something",chinese:"路/方式",sentence:"This is the best <strong>way</strong> to learn.",tip:"WAY 可以指路或方法",emoji:"🛤️",roots:["way"]},
    {word:"end",definition:"the last part, where something stops",chinese:"結束/結尾",sentence:"The <strong>end</strong> of the movie was great.",tip:"END 只有三個字母",emoji:"🔚",roots:["end"]},
    {word:"part",definition:"one piece of a bigger thing",chinese:"部分",sentence:"This is the fun <strong>part</strong>.",tip:"PART 和 WHOLE 相反",emoji:"🧩",roots:["part"]},
    {word:"number",definition:"A word or sign like 1, 2, or 3 that tells how many",chinese:"數字/號碼",sentence:"Pick a <strong>number</strong> from one to ten.",tip:"NUMBER 源自拉丁文 numerus（數），和 numeral（數字）、numerous（許多的）同源",emoji:"🔢",roots:["number"]},
    {word:"word",definition:"A sound or group of letters that means something",chinese:"字/單字",sentence:"Can you spell this <strong>word</strong>?",tip:"WORD 和 WORLD 很像",emoji:"📝",roots:["word"]},
    {word:"story",definition:"A telling of things that happen, real or made-up",chinese:"故事",sentence:"Read me a <strong>story</strong>, please.",tip:"STORY 的複數是 STORIES",emoji:"📖",roots:["story"]},
    {word:"nothing",definition:"not a single thing",chinese:"什麼都沒有",sentence:"There is <strong>nothing</strong> to worry about.",tip:"NOTHING = NO + THING",emoji:"0️⃣",roots:["nothing"]},
    {word:"something",definition:"A thing you do not name",chinese:"某個東西",sentence:"I want <strong>something</strong> to drink.",tip:"SOMETHING = SOME + THING",emoji:"🤔",roots:["some","thing"]},
    {word:"everything",definition:"all of the things",chinese:"每樣東西",sentence:"<strong>Everything</strong> will be okay.",tip:"EVERYTHING = EVERY + THING",emoji:"💯",roots:["every","thing"]},
    {word:"everyone",definition:"every person; all the people",chinese:"每個人",sentence:"<strong>Everyone</strong> likes her.",tip:"EVERYONE = EVERY + ONE",emoji:"👥",roots:["every","one"]},
    {word:"someone",definition:"A person you do not name",chinese:"某個人",sentence:"<strong>Someone</strong> left a message.",tip:"SOMEONE = SOME + ONE",emoji:"🧑",roots:["some","one"]},
    {word:"anyone",definition:"any person at all",chinese:"任何人",sentence:"Does <strong>anyone</strong> know the answer?",tip:"ANYONE = ANY + ONE",emoji:"❓",roots:["any","one"]},
    {word:"nobody",definition:"no person; not anyone",chinese:"沒有人",sentence:"<strong>Nobody</strong> is perfect.",tip:"NOBODY = NO + BODY",emoji:"🚫",roots:["nobody"]},
    {word:"anything",definition:"A thing of any kind",chinese:"任何東西",sentence:"Is there <strong>anything</strong> I can help with?",tip:"ANYTHING = ANY + THING",emoji:"❓",roots:["any","thing"]},
    {word:"right",definition:"correct, with no mistakes; also the side opposite your left hand",chinese:"對的/右邊",sentence:"Turn <strong>right</strong> at the corner.",tip:"RIGHT 有兩個意思：對的和右邊",emoji:"✅",roots:["right"]},
    {word:"wrong",definition:"not right or not correct",chinese:"錯的",sentence:"That answer is <strong>wrong</strong>.",tip:"WRONG 的 W 不發音",emoji:"❌",roots:["wrong"]},
    {word:"sure",definition:"knowing something is true, with no doubt",chinese:"確定的/當然",sentence:"Are you <strong>sure</strong> about that?",tip:"SURE 聽起來像 SHORE",emoji:"👍",roots:["sure"]},
    {word:"able",definition:"having the power to do something",chinese:"能夠的",sentence:"I am <strong>able</strong> to finish on time.",tip:"ABLE 常加在字後面變形容詞",emoji:"💪",roots:["able"]},
    {word:"ready",definition:"all set to do something now",chinese:"準備好的",sentence:"Are you <strong>ready</strong> for the test?",tip:"READY（準備好）和 READ 長得像，但兩字意思無關，別拆成 READ+Y",emoji:"✅",roots:["ready"]},
    {word:"free",definition:"not controlled or held back; able to do what you want; also costing no money",chinese:"自由的/免費的",sentence:"This app is <strong>free</strong> to download.",tip:"FREE 有「自由」和「免費」兩個意思",emoji:"🆓",roots:["free"]},
    {word:"full",definition:"filled up, with no more room inside",chinese:"滿的/飽的",sentence:"My stomach is <strong>full</strong>.",tip:"FULL 和 EMPTY 相反",emoji:"🍽️",roots:["full"]},
    {word:"empty",definition:"having nothing inside",chinese:"空的",sentence:"The bottle is <strong>empty</strong>.",tip:"EMPTY 和 FULL 相反",emoji:"🫙",roots:["empty"]},
    {word:"young",definition:"not old; born not long ago",chinese:"年輕的",sentence:"She looks very <strong>young</strong>.",tip:"YOUNG 和 OLD 相反",emoji:"👶",roots:["young"]},
    {word:"fast",definition:"moving very quickly",chinese:"快的",sentence:"Cheetahs are very <strong>fast</strong>.",tip:"FAST 和 SLOW 相反",emoji:"🏎️",roots:["fast"]},
    {word:"slow",definition:"moving without much speed; not fast",chinese:"慢的",sentence:"The turtle is very <strong>slow</strong>.",tip:"SLOW 和 FAST 相反",emoji:"🐢",roots:["slow"]},
    {word:"hard",definition:"not easy to do; firm and solid; also needing a lot of effort",chinese:"困難的/硬的/努力",sentence:"I study <strong>hard</strong> for the exam.",tip:"HARD 有多個意思",emoji:"💎",roots:["hard"]},
    {word:"easy",definition:"not hard to do",chinese:"容易的",sentence:"This puzzle is <strong>easy</strong>.",tip:"EASY = EAS（源自 ease，輕鬆、容易）+ -Y（形容詞字尾）；和 HARD 相反",emoji:"😎",roots:["easy"]},
    {word:"possible",definition:"able to happen or be done",chinese:"可能的",sentence:"Anything is <strong>possible</strong>!",tip:"POSSIBLE 結尾是 -IBLE，不是 -ABLE（注意拼字）",emoji:"🌟",roots:["possible"]},
    {word:"important",definition:"mattering very much",chinese:"重要的",sentence:"Exercise is <strong>important</strong>.",tip:"IMPORTANT = IM-（此處同 in-，向內）+ PORT（攜帶、運送）+ -ANT（形容詞字尾）；原意「被帶進來、有分量的」",emoji:"⭐",roots:["im","port","ant"]},
    {word:"make",definition:"to build or create something",chinese:"製作/使得",sentence:"Let's <strong>make</strong> a paper airplane.",tip:"MAKE 的過去式是 MADE",emoji:"🎨",roots:["make"]},
    {word:"think",definition:"to believe something in your mind",chinese:"想/認為",sentence:"I <strong>think</strong> you are right.",tip:"THINK 的過去式是 THOUGHT",emoji:"🤔",roots:["think"]},
    {word:"know",definition:"to have facts or information in your mind",chinese:"知道",sentence:"I <strong>know</strong> the answer!",tip:"KNOW 的 K 不發音",emoji:"💡",roots:["know"]},
    {word:"look",definition:"to turn your eyes toward something to see it",chinese:"看",sentence:"<strong>Look</strong> at the stars!",tip:"LOOK 有兩個 O",emoji:"👀",roots:["look"]},
    {word:"find",definition:"to get or see something you were looking for",chinese:"找到",sentence:"Can you <strong>find</strong> your shoes?",tip:"FIND 的過去式是 FOUND",emoji:"🔍",roots:["find"]},
    {word:"put",definition:"to place something in a spot",chinese:"放",sentence:"<strong>Put</strong> your toys away.",tip:"PUT 三態同形：put-put-put",emoji:"👇",roots:["put"]},
    {word:"try",definition:"to make an effort to do something",chinese:"嘗試",sentence:"<strong>Try</strong> your best!",tip:"TRY 的過去式是 TRIED",emoji:"💪",roots:["try"]},
    {word:"ask",definition:"to speak to someone to get an answer or help",chinese:"問/要求",sentence:"Can I <strong>ask</strong> a question?",tip:"ASK 只有三個字母",emoji:"❓",roots:["ask"]},
    {word:"need",definition:"to have to have something you cannot do without",chinese:"需要",sentence:"I <strong>need</strong> a glass of water.",tip:"NEED 有兩個 E",emoji:"🆘",roots:["need"]},
    {word:"turn",definition:"to move so you face a new way; also the time when it is your chance to do something",chinese:"轉/輪到",sentence:"It is your <strong>turn</strong> now.",tip:"TURN 可以是轉或輪流",emoji:"↩️",roots:["turn"]},
    {word:"call",definition:"to say something loudly to get attention; also to talk to someone on the phone",chinese:"叫/打電話",sentence:"I will <strong>call</strong> you tonight.",tip:"CALL 有兩個 L",emoji:"📞",roots:["call"]},
    {word:"keep",definition:"to go on doing something",chinese:"保持/繼續",sentence:"<strong>Keep</strong> going! You are doing great.",tip:"KEEP 有兩個 E",emoji:"💪",roots:["keep"]},
    {word:"let",definition:"to allow someone to do something",chinese:"讓/允許",sentence:"<strong>Let</strong> me try again.",tip:"LET 只有三個字母",emoji:"👍",roots:["let"]},
    {word:"begin",definition:"to start doing something",chinese:"開始",sentence:"Let's <strong>begin</strong> our adventure!",tip:"BEGIN 的過去式是 BEGAN",emoji:"▶️",roots:["begin"]},
    {word:"seem",definition:"to look like something is true",chinese:"似乎/看起來",sentence:"You <strong>seem</strong> happy today!",tip:"SEEM 有兩個 E",emoji:"🤔",roots:["seem"]},
    {word:"help",definition:"to do something to make things easier for someone",chinese:"幫助",sentence:"Can you <strong>help</strong> me carry this?",tip:"HELP 是很常用的求助語",emoji:"🆘",roots:["help"]},
    {word:"show",definition:"to let someone see something",chinese:"展示/表演",sentence:"<strong>Show</strong> me your painting.",tip:"SHOW 的過去式是 SHOWED",emoji:"👀",roots:["show"]},
    {word:"hear",definition:"to take in sounds with your ears",chinese:"聽到",sentence:"I can <strong>hear</strong> birds singing.",tip:"HEAR 裡面有 EAR（耳朵）",emoji:"👂",roots:["hear"]},
    {word:"move",definition:"to go from one spot to another",chinese:"移動/搬家",sentence:"Please don't <strong>move</strong>.",tip:"MOVE 和 MOVIE 是一家人",emoji:"🏃",roots:["move"]},
    {word:"change",definition:"to become different",chinese:"改變/零錢",sentence:"People can <strong>change</strong> for the better.",tip:"CHANGE 裡面有 HANG",emoji:"🔄",roots:["change"]},
    {word:"bring",definition:"to carry something to a place or person",chinese:"帶來",sentence:"Please <strong>bring</strong> your homework.",tip:"BRING 的過去式是 BROUGHT",emoji:"🤲",roots:["bring"]},
    {word:"pay",definition:"to give money to buy something",chinese:"付錢",sentence:"I will <strong>pay</strong> for the ticket.",tip:"PAY 的過去式是 PAID",emoji:"💵",roots:["pay"]},
    {word:"meet",definition:"to come together with someone",chinese:"遇見/認識",sentence:"Nice to <strong>meet</strong> you!",tip:"MEET 有兩個 E",emoji:"🤝",roots:["meet"]},
    {word:"mean",definition:"to stand for an idea or thing",chinese:"意思是/壞心的",sentence:"What does this <strong>mean</strong>?",tip:"MEAN 有「意思是」和「壞心的」兩個意思",emoji:"🤔",roots:["mean"]},
    {word:"become",definition:"to grow or turn into something",chinese:"變成",sentence:"I want to <strong>become</strong> a scientist.",tip:"BECOME = BE + COME",emoji:"🦋",roots:["become"]},
    {word:"leave",definition:"to go away from a place",chinese:"離開/留下",sentence:"I <strong>leave</strong> for school at eight.",tip:"LEAVE 的過去式是 LEFT",emoji:"🚪",roots:["leave"]},
    {word:"happen",definition:"to take place",chinese:"發生",sentence:"What <strong>happen</strong>ed here?",tip:"HAPPEN 來自 hap(運氣、機緣)＋-en，本意「碰巧發生」→ 發生（同源字 happy、perhaps）",emoji:"❗",roots:["happen"]},
    {word:"love",definition:"to like something very, very much",chinese:"愛/喜愛",sentence:"I <strong>love</strong> reading stories.",tip:"LOVE 裡面藏著一顆心",emoji:"❤️",roots:["love"]},
    {word:"country",definition:"A land with its own people and name, like Japan",chinese:"國家/鄉下",sentence:"Japan is a beautiful <strong>country</strong>.",tip:"COUNTRY 的複數是 COUNTRIES（字尾 y 要變成 ies）",emoji:"🌏",roots:["country"]},
    {word:"city",definition:"A big town where many people live",chinese:"城市",sentence:"This <strong>city</strong> has many tall buildings.",tip:"CITY 的複數是 CITIES",emoji:"🏙️",roots:["city"]},
    {word:"family",definition:"your parents, children, and others close to you",chinese:"家庭/家人",sentence:"I enjoy spending time with my <strong>family</strong>.",tip:"FAMILY 的複數是 FAMILIES（字尾 y 要變成 ies）",emoji:"👨‍👩‍👧‍👦",roots:["family"]},
    {word:"body",definition:"the whole of a person from head to toe",chinese:"身體",sentence:"Stretching is good for your <strong>body</strong>.",tip:"BODY 的複數是 BODIES",emoji:"🧍",roots:["body"]},
    {word:"side",definition:"the left or right part of something",chinese:"邊/旁邊",sentence:"Walk on the right <strong>side</strong>.",tip:"SIDE 和 HIDE 押韻",emoji:"↔️",roots:["side"]},
    {word:"point",definition:"a spot, idea, or moment; also to show where something is with your finger; also a mark that counts toward a score",chinese:"點/指/分數",sentence:"You got the highest <strong>point</strong>s!",tip:"POINT 用手指 👉 指出某一「點」",emoji:"👉",roots:["point"]},
    {word:"fact",definition:"something that is true and real",chinese:"事實",sentence:"That is a known <strong>fact</strong>.",tip:"FACT 指真正發生、能被證明的事實",emoji:"📋",roots:["fact"]},
    {word:"power",definition:"the strength or ability to do things",chinese:"力量/電力",sentence:"Knowledge is <strong>power</strong>.",tip:"POWER 源自古法文 poeir(能夠)，與 possible(可能的)同源；本意是「能做事的力量」",emoji:"⚡",roots:["power"]},
    {word:"lot",definition:"A big amount of something",chinese:"很多",sentence:"I have a <strong>lot</strong> of homework.",tip:"A LOT OF 表示很多",emoji:"📚",roots:["lot"]},
    {word:"believe",definition:"to feel sure something is true",chinese:"相信",sentence:"I <strong>believe</strong> in you!",tip:"記憶法(非字源)：BELIEVE 裡面剛好看得到 lie 這幾個字母，只是幫記拼字，不代表字義",emoji:"🙏",roots:["believe"]},
    {word:"remember",definition:"to keep something in your mind and not forget",chinese:"記得",sentence:"<strong>Remember</strong> to lock the door.",tip:"REMEMBER 來自 re-(再)＋拉丁 memor(記得的)，和 memory(記憶)同源；與英文 member(成員)無關",emoji:"🧠",roots:["remember"]},
    {word:"use",definition:"to do something with an object or tool",chinese:"使用",sentence:"Can I <strong>use</strong> your eraser?",tip:"USE 當動詞 S 發 /z/",emoji:"✍️",roots:["use"]},
    {word:"tell",definition:"to say something to someone",chinese:"告訴",sentence:"<strong>Tell</strong> me what happened.",tip:"TELL 有兩個 L",emoji:"🗣️",roots:["tell"]},
    {word:"wait",definition:"to stay until something happens or someone comes",chinese:"等待",sentence:"Please <strong>wait</strong> for me.",tip:"WAIT 的 AI 發長音",emoji:"⏳",roots:["wait"]},
    {word:"follow",definition:"to go behind someone and go where they go",chinese:"跟隨",sentence:"<strong>Follow</strong> the leader!",tip:"FOLLOW 有兩個 L；加 -ER 變成 FOLLOWER（跟隨者）",emoji:"🚶",roots:["follow"]},
    {word:"stop",definition:"to no longer move or do something",chinese:"停止",sentence:"<strong>Stop</strong> at the red light.",tip:"STOP 是八角形紅色標誌",emoji:"🛑",roots:["stop"]},
    {word:"start",definition:"to begin doing something",chinese:"開始",sentence:"Let's <strong>start</strong> the game!",tip:"START 和 STOP 相反",emoji:"▶️",roots:["start"]},
    {word:"hour",definition:"A length of time equal to 60 minutes",chinese:"小時",sentence:"The movie is two <strong>hour</strong>s long.",tip:"HOUR 的 H 不發音",emoji:"🕐",roots:["hour"]},
    {word:"minute",definition:"A short time equal to 60 seconds",chinese:"分鐘",sentence:"Wait one <strong>minute</strong>, please.",tip:"MINUTE 的 min＝「小」(如 minimum、minus)；一分鐘就是把一小時切成的小段。當形容詞「微小」時重音在後",emoji:"⏱️",roots:["minute"]},
    {word:"second",definition:"the one right after the first; also a very short bit of time (60 seconds make a minute)",chinese:"第二/秒",sentence:"I will be back in a <strong>second</strong>.",tip:"SECOND 有「第二」和「秒」兩個意思，這裡指「一下下、片刻」",emoji:"⏱️",roots:["second"]},
    {word:"half",definition:"one of two equal parts of something",chinese:"一半",sentence:"I ate <strong>half</strong> of the pie.",tip:"HALF 的 L 不發音",emoji:"🍕",roots:["half"]},
    {word:"problem",definition:"something hard that you need to fix or solve",chinese:"問題/麻煩",sentence:"No <strong>problem</strong>! I can do it.",tip:"PROBLEM 源自希臘文：pro-(向前)＋blem(來自 ballein 丟)＝「擺在面前的難題」→ 問題",emoji:"🤔",roots:["problem"]},
    {word:"question",definition:"something you ask to find out an answer",chinese:"問題（提問）",sentence:"I have a <strong>question</strong> for you.",tip:"QUESTION = QUEST(探求／尋找) + -ION(名詞字尾)；源自拉丁 quaerere(詢問、尋找)，和 QUEST(探索)同源",emoji:"❓",roots:["quest","ion"]},
    {word:"answer",definition:"what you say back to a question",chinese:"答案/回答",sentence:"Do you know the <strong>answer</strong>?",tip:"ANSWER 的 W 不發音",emoji:"💡",roots:["answer"]},
    {word:"idea",definition:"A thought or plan in your mind",chinese:"主意/想法",sentence:"I have a great <strong>idea</strong>!",tip:"IDEA 有三個音節",emoji:"💡",roots:["idea"]},
    {word:"reason",definition:"why something happens or is done",chinese:"原因/理由",sentence:"There is a good <strong>reason</strong> for it.",tip:"REASON 和 REASONABLE（合理的）是一家人",emoji:"🤔",roots:["reason"]},
    {word:"example",definition:"one thing that shows what others are like",chinese:"例子",sentence:"Can you give me an <strong>example</strong>?",tip:"EXAMPLE 源自拉丁 exemplum：ex-(拿出)＋來自 emere(取)＝「取出來給人看的樣本」→ 例子；與英文 ample(充足的)無關",emoji:"📋",roots:["example"]},
    {word:"understand",definition:"to know what something means",chinese:"了解/明白",sentence:"I <strong>understand</strong> now!",tip:"記憶法(非字源)：UNDERSTAND 裡看得到 UNDER 和 STAND 兩個熟字，可幫記拼法；並不是「站在下面」的意思",emoji:"💡",roots:["understand"]},
    {word:"game",definition:"A fun activity you play, often with rules",chinese:"遊戲/比賽",sentence:"Let's play a board <strong>game</strong>.",tip:"GAME 和 NAME 押韻",emoji:"🎮",roots:["game"]},
    {word:"picture",definition:"A drawing or photo you can look at",chinese:"圖片/照片",sentence:"I took a <strong>picture</strong> of the sunset.",tip:"PICTURE 源自拉丁 pingere(繪畫)的 pict-(畫過的)，和 PAINT 意義相關；字尾 -URE 使它成為名詞",emoji:"🖼️",roots:["picture"]},
    {word:"movie",definition:"A story you watch on a screen with moving pictures",chinese:"電影",sentence:"We watched a funny <strong>movie</strong>.",tip:"MOVIE 和 MOVE 是一家人",emoji:"🎬",roots:["movie"]},
    {word:"letter",definition:"A message you write and send to someone",chinese:"信/字母",sentence:"I wrote a <strong>letter</strong> to my friend.",tip:"LETTER 有兩個 T",emoji:"✉️",roots:["letter"]},
    {word:"age",definition:"how many years old someone is",chinese:"年齡",sentence:"What <strong>age</strong> did you start school?",tip:"AGE 只有三個字母",emoji:"🎂",roots:["age"]},
    {word:"air",definition:"the gas all around us that we breathe",chinese:"空氣",sentence:"Fresh <strong>air</strong> feels wonderful.",tip:"AIR 只有三個字母",emoji:"💨",roots:["air"]},
    {word:"line",definition:"a long thin mark, like one you draw; also a row of people waiting one behind another",chinese:"線/排隊",sentence:"Stand in <strong>line</strong>, please.",tip:"LINE 和 FINE 押韻",emoji:"➖",roots:["line"]},
    {word:"class",definition:"A time when students learn a subject together",chinese:"課/班級",sentence:"We have art <strong>class</strong> today.",tip:"CLASS 有兩個 S",emoji:"🏫",roots:["class"]},
    {word:"heart",definition:"the part in your chest that pumps blood",chinese:"心/心臟",sentence:"I love you with all my <strong>heart</strong>.",tip:"HEART 裡面有 EAR 和 ART",emoji:"❤️",roots:["heart"]},
    {word:"river",definition:"A long stream of water flowing across the land",chinese:"河流",sentence:"We played by the <strong>river</strong>.",tip:"RIVER 和 LIVER 押韻（記憶法）",emoji:"🏞️",roots:["river"]},
    {word:"sea",definition:"A very large body of salty water",chinese:"海",sentence:"The <strong>sea</strong> is so blue and calm.",tip:"SEA 和 SEE 發音一樣",emoji:"🌊",roots:["sea"]},
    {word:"land",definition:"the dry part of Earth, not the water",chinese:"陸地/土地",sentence:"The bird landed on <strong>land</strong>.",tip:"LAND 和 SAND 押韻",emoji:"🏝️",roots:["land"]},
    {word:"mountain",definition:"A very tall, rocky hill",chinese:"山",sentence:"We climbed a <strong>mountain</strong>.",tip:"MOUNTAIN 源自拉丁 mont-（山），和 MOUNT（登上）同源",emoji:"🏔️",roots:["mountain"]},
    {word:"town",definition:"A place with homes and shops, smaller than a city",chinese:"小鎮",sentence:"Our <strong>town</strong> is very quiet.",tip:"TOWN 和 DOWN 押韻",emoji:"🏘️",roots:["town"]},
    {word:"street",definition:"A road in a town with houses along it",chinese:"街道",sentence:"Look both ways before crossing the <strong>street</strong>.",tip:"STREET 有兩個 E",emoji:"🛣️",roots:["street"]},
    {word:"road",definition:"A wide path that cars travel on between places",chinese:"路/道路",sentence:"The <strong>road</strong> goes through the forest.",tip:"ROAD 和 TOAD（蟾蜍）押韻",emoji:"🛣️",roots:["road"]},
    {word:"garden",definition:"A place outside where plants and flowers grow",chinese:"花園",sentence:"We grow tomatoes in our <strong>garden</strong>.",tip:"GARDEN 和 PARDON 押韻（記憶法）",emoji:"🌷",roots:["garden"]},
    {word:"snow",definition:"soft white flakes of frozen water that fall from the sky",chinese:"雪",sentence:"Let's play in the <strong>snow</strong>!",tip:"SNOW 和 KNOW 押韻",emoji:"❄️",roots:["snow"]},
    {word:"rain",definition:"drops of water that fall from clouds",chinese:"雨/下雨",sentence:"I love the sound of <strong>rain</strong>.",tip:"RAIN 和 TRAIN 押韻",emoji:"🌧️",roots:["rain"]},
    {word:"wind",definition:"air that moves across the ground",chinese:"風",sentence:"The <strong>wind</strong> blows leaves around.",tip:"WIND 也可以是「繞」(發音不同)",emoji:"🌬️",roots:["wind"]},
    {word:"animal",definition:"A living thing that can move, like a dog or a bird",chinese:"動物",sentence:"What <strong>animal</strong> do you like best?",tip:"ANIMAL 源自拉丁 anima（生命、氣息）→ 有生命的東西",emoji:"🐾",roots:["animal"]},
    {word:"horse",definition:"A large animal that people ride and that can run fast",chinese:"馬",sentence:"The <strong>horse</strong> galloped across the field.",tip:"HORSE 裡面有 OR",emoji:"🐴",roots:["horse"]},
    {word:"paper",definition:"A thin flat sheet you write or draw on",chinese:"紙",sentence:"Write your name on the <strong>paper</strong>.",tip:"PAPER 源自 PAPYRUS（古埃及莎草紙）",emoji:"📄",roots:["paper"]},
    {word:"son",definition:"someone's male child, a boy",chinese:"兒子",sentence:"He is a kind <strong>son</strong>.",tip:"SON 和 SUN 發音一樣",emoji:"👦",roots:["son"]},
    {word:"daughter",definition:"someone's female child, a girl",chinese:"女兒",sentence:"His <strong>daughter</strong> loves to paint.",tip:"DAUGHTER 的 GH 不發音",emoji:"👧",roots:["daughter"]},
    {word:"baby",definition:"A very young child who cannot walk or talk yet",chinese:"嬰兒",sentence:"The <strong>baby</strong> is smiling.",tip:"BABY 的複數是 BABIES",emoji:"👶",roots:["baby"]},
    {word:"king",definition:"A man who rules a country, like in old stories",chinese:"國王",sentence:"The <strong>king</strong> sits on a golden throne.",tip:"KING 和 SING 押韻",emoji:"👑",roots:["king"]},
    {word:"voice",definition:"the sound a person makes to talk or sing",chinese:"聲音/嗓音",sentence:"She has a lovely <strong>voice</strong>.",tip:"VOICE 裡面有 ICE",emoji:"🗣️",roots:["voice"]},
    {word:"sense",definition:"A clear meaning or good reason that makes something easy to understand",chinese:"道理；意義",sentence:"That makes <strong>sense</strong>!",tip:"make sense = 說得通、有道理",emoji:"🧠",roots:["sense"]},
    {word:"matter",definition:"to be important or worth caring about",chinese:"重要；要緊",sentence:"It doesn't <strong>matter</strong>.",tip:"MATTER 有兩個 T",emoji:"❗",roots:["matter"]},
    {word:"care",definition:"to feel that someone or something is important to you",chinese:"關心/照顧",sentence:"I <strong>care</strong> about my friends.",tip:"CARE 和 SHARE 押韻",emoji:"💕",roots:["care"]},
    {word:"stand",definition:"to be up on your feet, not sitting",chinese:"站立",sentence:"Please <strong>stand</strong> up.",tip:"STAND 裡面有 AND",emoji:"🧍",roots:["stand"]},
    {word:"catch",definition:"to grab something moving with your hands",chinese:"抓住/接住",sentence:"<strong>Catch</strong> the ball!",tip:"CATCH 的 TCH 發 /tʃ/",emoji:"🤾",roots:["catch"]},
    {word:"carry",definition:"to hold something and take it with you",chinese:"攜帶/搬運",sentence:"I <strong>carry</strong> my lunch to school.",tip:"CARRY 有兩個 R",emoji:"🎒",roots:["carry"]},
    {word:"cut",definition:"to split something with scissors or a knife",chinese:"切/剪",sentence:"<strong>Cut</strong> the paper along the line.",tip:"CUT 三態同形：cut-cut-cut",emoji:"✂️",roots:["cut"]},
    {word:"pick",definition:"to choose the one you want",chinese:"挑選/撿起",sentence:"<strong>Pick</strong> your favorite color.",tip:"PICK 和 KICK 押韻",emoji:"👆",roots:["pick"]},
    {word:"break",definition:"to make something come apart in pieces",chinese:"打破/休息",sentence:"Be careful not to <strong>break</strong> it!",tip:"BREAK 的 EA 發 /eɪ/",emoji:"💔",roots:["break"]},
    {word:"grow",definition:"to get bigger over time",chinese:"成長/種植",sentence:"Plants <strong>grow</strong> toward the sun.",tip:"GROW 的過去式是 GREW",emoji:"🌱",roots:["grow"]},
    {word:"hold",definition:"to keep something in your hand",chinese:"握住/抱著",sentence:"<strong>Hold</strong> my hand when crossing.",tip:"HOLD 的過去式是 HELD",emoji:"🤝",roots:["hold"]},
    {word:"spend",definition:"to use your time or money on something",chinese:"花費（時間/金錢）",sentence:"I <strong>spend</strong> time reading every day.",tip:"SPEND 的過去式是 SPENT",emoji:"⏰",roots:["spend"]},
    {word:"win",definition:"to come in first in a game or contest",chinese:"贏",sentence:"I hope our team will <strong>win</strong>!",tip:"WIN 的過去式是 WON",emoji:"🏆",roots:["win"]},
    {word:"lose",definition:"to not win a game or contest; also, to not be able to find something you had",chinese:"輸/丟失",sentence:"Don't <strong>lose</strong> your ticket!",tip:"LOSE 有「輸」和「丟失」兩個意思；和 CHOOSE 押韻",emoji:"😢",roots:["lose"]},
    {word:"send",definition:"to make something go to another person or place",chinese:"寄/送",sentence:"I will <strong>send</strong> you an email.",tip:"SEND 的過去式是 SENT",emoji:"📨",roots:["send"]},
    {word:"build",definition:"to make something by putting parts together",chinese:"建造",sentence:"Let's <strong>build</strong> a sandcastle!",tip:"BUILD 的 UI 發 /ɪ/",emoji:"🏗️",roots:["build"]},
    {word:"set",definition:"to decide or fix something, like a time or a rule; also to put things in their right place",chinese:"設定/放置",sentence:"<strong>Set</strong> the table for dinner.",tip:"SET 三態同形：set-set-set",emoji:"⚙️",roots:["set"]},
    {word:"miss",definition:"to feel sad that someone is not with you",chinese:"想念/錯過",sentence:"I <strong>miss</strong> my grandparents.",tip:"MISS 有「想念」和「錯過」兩個意思",emoji:"😢",roots:["miss"]},
    {word:"enjoy",definition:"to like doing something and have fun",chinese:"享受",sentence:"I <strong>enjoy</strong> playing with my friends.",tip:"ENJOY = EN（使、進入）+ JOY（喜悅）：讓自己進入喜悅 → 享受",emoji:"😊",roots:["en","joy"]},
    {word:"wish",definition:"to hope for something you want",chinese:"希望/祝福",sentence:"I <strong>wish</strong> upon a star.",tip:"WISH 和 FISH 押韻",emoji:"🌠",roots:["wish"]},
    {word:"wonder",definition:"to want to know or think about something",chinese:"想知道/驚嘆",sentence:"I <strong>wonder</strong> what is inside.",tip:"WONDER 和 THUNDER 押韻（記憶法）",emoji:"🤔",roots:["wonder"]},
    {word:"hope",definition:"to want something good to happen",chinese:"希望",sentence:"I <strong>hope</strong> you feel better.",tip:"HOPE 和 ROPE 押韻",emoji:"🙏",roots:["hope"]},
    {word:"thank",definition:"to tell someone you are happy for their help or gift",chinese:"感謝",sentence:"<strong>Thank</strong> you for the gift!",tip:"THANK 和 THINK 很像",emoji:"🙏",roots:["thank"]},
    {word:"add",definition:"to put numbers together to get more",chinese:"加/增加",sentence:"<strong>Add</strong> two plus three.",tip:"ADD 有兩個 D",emoji:"➕",roots:["add"]},
    {word:"smile",definition:"A happy look with the ends of your mouth turned up",chinese:"微笑",sentence:"Her <strong>smile</strong> lights up the room.",tip:"SMILE 讓人開心",emoji:"😊",roots:["smile"]},
    {word:"laugh",definition:"to make happy sounds when something is funny",chinese:"笑",sentence:"That joke makes me <strong>laugh</strong>.",tip:"LAUGH 的 GH 發 /f/",emoji:"😂",roots:["laugh"]},
    {word:"wake",definition:"to stop sleeping and open your eyes",chinese:"醒來",sentence:"I <strong>wake</strong> up when the sun rises.",tip:"WAKE 和 CAKE 押韻",emoji:"⏰",roots:["wake"]},
    {word:"die",definition:"to stop living",chinese:"死/去世",sentence:"The plant will <strong>die</strong> without water.",tip:"DIE 的現在分詞是 DYING",emoji:"🥀",roots:["die"]},
    {word:"stay",definition:"to keep being in one place or way",chinese:"停留/待",sentence:"Can I <strong>stay</strong> up late tonight?",tip:"STAY 和 DAY 押韻",emoji:"🏠",roots:["stay"]},
    {word:"bit",definition:"A small amount",chinese:"一點點",sentence:"I am a <strong>bit</strong> nervous.",tip:"A BIT 表示一點點",emoji:"🤏",roots:["bit"]},
    {word:"piece",definition:"A part cut from something bigger",chinese:"片/塊",sentence:"May I have a <strong>piece</strong> of cake?",tip:"PIECE 和 PEACE 發音一樣",emoji:"🍰",roots:["piece"]},
    {word:"top",definition:"the highest part of something",chinese:"頂端/上面",sentence:"The cat sat on <strong>top</strong> of the roof.",tip:"TOP 和 BOTTOM 相反",emoji:"🔝",roots:["top"]},
    {word:"bottom",definition:"the lowest part of something",chinese:"底部/下面",sentence:"Look at the <strong>bottom</strong> of the page.",tip:"BOTTOM 有兩個 T",emoji:"⬇️",roots:["bottom"]},
    {word:"middle",definition:"the center, halfway between the ends",chinese:"中間",sentence:"Sit in the <strong>middle</strong> of the row.",tip:"MIDDLE 有兩個 D；mid＝中(如 midday 正午、midnight 午夜)",emoji:"⏺️",roots:["middle"]},
    {word:"sound",definition:"something you hear with your ears",chinese:"聲音/聽起來",sentence:"What is that <strong>sound</strong>?",tip:"SOUND 和 ROUND 押韻",emoji:"🔊",roots:["sound"]},
    {word:"war",definition:"A big fight between countries using armies",chinese:"戰爭",sentence:"We want peace, not <strong>war</strong>.",tip:"WAR 和 PEACE 相反",emoji:"⚔️",roots:["war"]},
    {word:"peace",definition:"A calm time with no fighting",chinese:"和平",sentence:"Let there be <strong>peace</strong> on Earth.",tip:"PEACE 和 PIECE 發音一樣",emoji:"☮️",roots:["peace"]},
    {word:"group",definition:"A number of people or things together",chinese:"群/組",sentence:"Our <strong>group</strong> won the contest.",tip:"GROUP 的 OU 發 /u:/",emoji:"👥",roots:["group"]},
    {word:"teach",definition:"to help someone learn something",chinese:"教",sentence:"She loves to <strong>teach</strong> kids.",tip:"TEACH 的過去式是 TAUGHT",emoji:"👩‍🏫",roots:["teach"]},
    {word:"type",definition:"A kind or sort of something",chinese:"種類/打字",sentence:"What <strong>type</strong> of music do you like?",tip:"TYPE 有「種類」和「打字」兩個意思",emoji:"⌨️",roots:["type"]},
    {word:"song",definition:"words and music you sing",chinese:"歌曲",sentence:"That is my favorite <strong>song</strong>.",tip:"SONG 和 LONG 押韻",emoji:"🎵",roots:["song"]},
    {word:"language",definition:"the words people use to talk and write",chinese:"語言",sentence:"I want to learn a new <strong>language</strong>.",tip:"LANGUAGE 來自拉丁 lingua(舌頭)＋字尾 -age；用舌頭說出來的就是語言",emoji:"🗣️",roots:["language"]},
    {word:"maybe",definition:"it could happen, but you are not sure",chinese:"也許/可能",sentence:"<strong>Maybe</strong> we can go swimming.",tip:"MAYBE = MAY + BE",emoji:"🤔",roots:["maybe"]},
    {word:"plan",definition:"the things you decide to do ahead of time",chinese:"計劃",sentence:"What is your <strong>plan</strong> for today?",tip:"PLAN 和 CAN 押韻",emoji:"📋",roots:["plan"]},
    {word:"finish",definition:"to do the last part and be done",chinese:"完成",sentence:"I need to <strong>finish</strong> my project.",tip:"FINISH = FIN(結束) + ISH",emoji:"🏁",roots:["finish"]},
    {word:"pass",definition:"to hand something to another person",chinese:"傳遞；遞給",sentence:"Please <strong>pass</strong> me the salt.",tip:"PASS 有兩個 S",emoji:"🤲",roots:["pass"]},
    {word:"decide",definition:"to make up your mind about something",chinese:"決定",sentence:"I can't <strong>decide</strong> which book to read.",tip:"DECIDE = DE(去除) + CIDE(切)：切掉其他選項，就是做「決定」",emoji:"🤔",roots:["de","cide"]},
    {word:"once",definition:"one time",chinese:"一次/曾經",sentence:"I brush my teeth <strong>once</strong> in the morning.",tip:"ONCE 的發音特殊：/wʌns/",emoji:"1️⃣",roots:["once"]},
    {word:"ever",definition:"at any time",chinese:"曾經/到底",sentence:"Have you <strong>ever</strong> seen a whale?",tip:"EVER 常和 HAVE 一起用",emoji:"🐋",roots:["ever"]},
    {word:"upon",definition:"on or on top of something",chinese:"在...上面",sentence:"Once <strong>upon</strong> a time, there was a princess.",tip:"UPON = UP + ON",emoji:"📖",roots:["upon"]},
    {word:"either",definition:"also, used after saying 'not'",chinese:"也（否定）/兩者之一",sentence:"I don't like it <strong>either</strong>.",tip:"EITHER 可唸 /iːðər/ 或 /aɪðər/",emoji:"🔀",roots:["either"]},
    {word:"neither",definition:"not one and not the other",chinese:"兩者都不",sentence:"<strong>Neither</strong> answer is correct.",tip:"NEITHER 來自 ne(不)＋either(兩者之一) → 兩者都不",emoji:"🚫",roots:["neither"]},
    {word:"perhaps",definition:"maybe; it could be true",chinese:"也許/可能",sentence:"<strong>Perhaps</strong> it will be sunny tomorrow.",tip:"PERHAPS = PER + HAPS",emoji:"🤔",roots:["perhaps"]},
    {word:"several",definition:"more than two, but not many",chinese:"幾個/一些",sentence:"I have <strong>several</strong> pets.",tip:"SEVERAL 與 separate(分開)同源，本意是「各自分開的幾個」→ 幾個",emoji:"👥",roots:["several"]},
    {word:"whether",definition:"used when you pick between two things",chinese:"是否",sentence:"I don't know <strong>whether</strong> to go or stay.",tip:"WHETHER 和 WEATHER 發音一樣",emoji:"🤔",roots:["whether"]},
    {word:"nor",definition:"and not; used after 'neither'",chinese:"也不",sentence:"I have neither time <strong>nor</strong> energy.",tip:"NOR 和 NEITHER 搭配",emoji:"🚫",roots:["nor"]},
    {word:"thus",definition:"for that reason; so",chinese:"因此/如此",sentence:"He practiced hard, <strong>thus</strong> he improved.",tip:"THUS 比較正式",emoji:"➡️",roots:["thus"]},
    {word:"okay",definition:"fine; all right",chinese:"好的/沒問題",sentence:"Are you <strong>okay</strong>?",tip:"OKAY 也寫成 OK",emoji:"👌",roots:["okay"]},
    {word:"please",definition:"A kind word used to ask for something",chinese:"請",sentence:"<strong>Please</strong> pass me the butter.",tip:"PLEASE 是禮貌用語",emoji:"🙏",roots:["please"]},
    {word:"welcome",definition:"glad to have someone come; also what you say back when someone thanks you",chinese:"歡迎/不客氣",sentence:"You are <strong>welcome</strong>!",tip:"WELCOME 源自古英語 wilcuma（受歡迎的客人）；記憶時可想成 well(好)＋come(來)，好好地來 → 歡迎",emoji:"🤗",roots:["welcome"]},
    {word:"hello",definition:"A word you say to greet someone",chinese:"你好",sentence:"<strong>Hello</strong>, nice to meet you!",tip:"HELLO 是最基本的打招呼",emoji:"👋",roots:["hello"]},
    {word:"bye",definition:"A short word you say when you leave",chinese:"再見",sentence:"<strong>Bye</strong>! See you tomorrow!",tip:"BYE 是 GOODBYE 的縮寫",emoji:"👋",roots:["bye"]},
    {word:"myself",definition:"my own self; me",chinese:"我自己",sentence:"I made it <strong>myself</strong>!",tip:"MYSELF = my(我的)＋self(自己、本身) → 我自己",emoji:"🙋",roots:["myself"]},
    {word:"yourself",definition:"your own self",chinese:"你自己",sentence:"Believe in <strong>yourself</strong>!",tip:"YOURSELF = your(你的)＋self(自己、本身) → 你自己",emoji:"👉",roots:["your","self"]},
    {word:"himself",definition:"his own self",chinese:"他自己",sentence:"He cooked dinner <strong>himself</strong>.",tip:"HIMSELF = him(他)＋self(自己、本身) → 他自己",emoji:"👦",roots:["him","self"]},
    {word:"herself",definition:"her own self",chinese:"她自己",sentence:"She did the project <strong>herself</strong>.",tip:"HERSELF = her(她)＋self(自己、本身) → 她自己",emoji:"👧",roots:["her","self"]},
    {word:"itself",definition:"the thing's own self",chinese:"它自己",sentence:"The door opened by <strong>itself</strong>.",tip:"ITSELF = it(它)＋self(自己、本身) → 它自己",emoji:"🚪",roots:["itself"]},
    {word:"themselves",definition:"their own selves",chinese:"他們自己",sentence:"They cleaned the room <strong>themselves</strong>.",tip:"THEMSELVES 是 they／them 的反身代名詞（他們自己）；注意字尾是 -selves 不是 -selfs",emoji:"👥",roots:["themselves"]},
    {word:"common",definition:"seen or found very often",chinese:"常見的/共同的",sentence:"Cats are <strong>common</strong> pets.",tip:"COMMON 來自拉丁 communis：com-(共同)＋mun-(來自 munus 職責/公共)，大家共有的 → 共同的、常見的",emoji:"🐱",roots:["common"]},
    {word:"public",definition:"open for everyone to use",chinese:"公共的/公眾",sentence:"This is a <strong>public</strong> library.",tip:"PUBLIC＝公共，源自拉丁文 populus（人民）；別和 PUB（酒吧）搞混",emoji:"🏛️",roots:["public"]},
    {word:"natural",definition:"coming from nature, not made by people",chinese:"自然的",sentence:"This soap is all <strong>natural</strong>.",tip:"NATURAL = natur(天生、本性，如 nature)＋-al(形容詞字尾) → 天生如此的 → 自然的",emoji:"🌿",roots:["natur","al"]},
    {word:"private",definition:"only for you, not for other people",chinese:"私人的",sentence:"That is my <strong>private</strong> diary.",tip:"PRIVATE＝私人的，源自拉丁文 privatus（個人的）；字尾 ATE 不是「吃」",emoji:"🔒",roots:["private"]},
    {word:"market",definition:"A place where people buy and sell food and things",chinese:"市場",sentence:"We buy fruit at the <strong>market</strong>.",tip:"MARKET＝市場，源自拉丁文「買賣」；別誤以為和 MARK（記號）有關",emoji:"🏪",roots:["market"]},
    {word:"parent",definition:"A mother or father",chinese:"父母",sentence:"My <strong>parent</strong>s support me.",tip:"PARENT = par(生育，源自拉丁 parere「生出」)＋-ent(名詞字尾，做…的人) → 生育者、父母",emoji:"👨‍👩‍👧",roots:["par","ent"]},
    {word:"present",definition:"A gift you give someone",chinese:"禮物/現在/出席",sentence:"I got a <strong>present</strong> for my birthday!",tip:"PRESENT = pre-(在前)＋-sent(源自拉丁 esse「存在、在」) → 在眼前的；有現在、出席、禮物三個意思",emoji:"🎁",roots:["pre","sent"]},
    {word:"practice",definition:"doing something again and again to get better",chinese:"練習",sentence:"<strong>Practice</strong> makes perfect!",tip:"PRACTICE = pract(做、實行，源自希臘 praktikos)＋-ice(名詞字尾) → 練習；字尾 ICE 不是「冰」",emoji:"🎯",roots:["practice"]},
    {word:"page",definition:"one side of a sheet of paper in a book",chinese:"頁",sentence:"Turn to <strong>page</strong> five.",tip:"PAGE 和 AGE 押韻",emoji:"📄",roots:["page"]},
    {word:"glass",definition:"a hard, clear material used to make windows and bottles; also a cup you drink from, made of this material",chinese:"玻璃/杯子",sentence:"Handle the <strong>glass</strong> carefully.",tip:"GLASS 有兩個 S",emoji:"🥛",roots:["glass"]},
    {word:"difficult",definition:"hard to do or understand",chinese:"困難的",sentence:"The math test was <strong>difficult</strong>.",tip:"DIFFICULT 源自拉丁 difficilis：dif-（=dis 不）＋ facil（來自 facilis 容易）＝「不容易」→ 困難；別把字尾看成英文的 CULT",emoji:"😰",roots:["difficult"]},
    {word:"perfect",definition:"so good that nothing is wrong with it",chinese:"完美的",sentence:"Your drawing is <strong>perfect</strong>!",tip:"PERFECT = PER（徹底、完全）＋ FECT（來自拉丁 facere「做」）：徹底做好 → 完美",emoji:"💯",roots:["per","fect"]},
    {word:"subject",definition:"A topic you study in school, like math",chinese:"科目/主題",sentence:"What is your favorite <strong>subject</strong>?",tip:"SUBJECT = SUB（在下面）＋ JECT（來自拉丁 jacere「投、丟」）：放在其下 → 科目／主題",emoji:"📚",roots:["sub","ject"]},
    {word:"effort",definition:"the hard work you put into doing something",chinese:"努力",sentence:"Good <strong>effort</strong>, keep trying!",tip:"EFFORT 源自拉丁 ex-（使出、向外）＋ fortis（強壯）：使出力氣 → 努力（FORT 這裡不是英文的「堡壘」）",emoji:"💪",roots:["effort"]},
    {word:"news",definition:"new information about things that just happened",chinese:"新聞",sentence:"Did you hear the <strong>news</strong>?",tip:"NEWS 用單數動詞",emoji:"📰",roots:["news"]},
    {word:"test",definition:"A set of questions to show what you know",chinese:"測驗/考試",sentence:"We have a spelling <strong>test</strong> Friday.",tip:"TEST 和 BEST 押韻",emoji:"📝",roots:["test"]},
    {word:"mind",definition:"the part of you that thinks, feels, and remembers; it can also mean to feel bothered by something",chinese:"心智/介意",sentence:"I don't <strong>mind</strong> waiting.",tip:"MIND 有「心」和「介意」的意思",emoji:"🧠",roots:["mind"]},
    {word:"cause",definition:"to make something happen",chinese:"原因/引起",sentence:"What <strong>cause</strong>d the noise?",tip:"CAUSE = 原因，BECAUSE = 因為",emoji:"💡",roots:["cause"]},
    {word:"serve",definition:"to bring food or drink to someone",chinese:"服務/上菜",sentence:"May I <strong>serve</strong> you some tea?",tip:"SERVE 源自拉丁 servire（服侍）；同家族字：SERVICE(服務)、SERVANT(僕人)",emoji:"🍽️",roots:["serve"]},
    {word:"human",definition:"A person, like a man, woman, or child",chinese:"人類/人的",sentence:"Every <strong>human</strong> being is unique.",tip:"HUMAN 源自拉丁 humanus（人的），與 homo（人）同源；拆成 HU＋MAN 只是巧合，英文的 MAN 不是這裡的字根",emoji:"🧑",roots:["human"]},
    {word:"interest",definition:"A feeling of wanting to know more about something",chinese:"興趣/利息",sentence:"I have great <strong>interest</strong> in space.",tip:"INTEREST 來自拉丁 inter-(在...之間)＋est(來自 esse「是、存在」)，介於其中、與我有關 → 興趣",emoji:"🔍",roots:["interest"]},
    {word:"form",definition:"the shape, type, or way something exists; also a paper with blanks you fill in",chinese:"形式／種類；表格",sentence:"Please fill out this <strong>form</strong>.",tip:"FORM 和 STORM 押韻",emoji:"📋",roots:["form"]},
    {word:"system",definition:"A group of parts that work together",chinese:"系統",sentence:"The solar <strong>system</strong> has eight planets.",tip:"SYSTEM 來自希臘文：sys-(=syn 一起)＋-stem(來自「站立、組合」)，組合在一起 → 系統",emoji:"⚙️",roots:["system"]},
    {word:"area",definition:"A part of a place or space",chinese:"地區/面積",sentence:"This <strong>area</strong> has many parks.",tip:"AREA 有三個音節",emoji:"🗺️",roots:["area"]},
    {word:"result",definition:"what happens because of something else",chinese:"結果",sentence:"The <strong>result</strong> was amazing!",tip:"RESULT = RE（回）＋ SULT（來自拉丁 salire「跳」）：跳回來的東西 → 結果",emoji:"📊",roots:["re","sult"]},
    {word:"note",definition:"A short message you write down",chinese:"筆記/備註",sentence:"I wrote a <strong>note</strong> to remind myself.",tip:"NOTE 和 VOTE 押韻",emoji:"📝",roots:["note"]},
    {word:"report",definition:"A talk or writing that tells about something",chinese:"報告",sentence:"I gave a <strong>report</strong> on dolphins.",tip:"REPORT = RE（回）＋ PORT（來自拉丁 portare「攜帶」）：把消息帶回來 → 報告",emoji:"📄",roots:["re","port"]},
    {word:"level",definition:"A step or stage, like in a game",chinese:"等級/程度",sentence:"I reached the next <strong>level</strong>!",tip:"LEVEL 正著反著都一樣！",emoji:"📶",roots:["level"]},
    {word:"order",definition:"the way things are placed, one after another",chinese:"順序/點菜/命令",sentence:"Put these numbers in <strong>order</strong>.",tip:"ORDER 有多個意思：順序、命令、點餐；記憶法(非字源)：唸成 or-der 兩個音節",emoji:"📋",roots:["order"]},
    {word:"chance",definition:"A time when you get to try something",chinese:"機會",sentence:"Give me one more <strong>chance</strong>!",tip:"CHANCE 和 DANCE 押韻",emoji:"🎲",roots:["chance"]},
    {word:"act",definition:"to do something",chinese:"行為/演戲",sentence:"Think before you <strong>act</strong>.",tip:"ACT 只有三個字母",emoji:"🎭",roots:["act"]},
    {word:"ground",definition:"the land you walk on",chinese:"地面/地上",sentence:"The ball rolled on the <strong>ground</strong>.",tip:"GROUND 和 ROUND 押韻",emoji:"🌍",roots:["ground"]},
    {word:"experience",definition:"something that happens to you",chinese:"經驗/體驗",sentence:"It was an amazing <strong>experience</strong>!",tip:"EXPERIENCE 源自拉丁 experiri（嘗試、親歷）；注意這裡的 PERI 不是希臘文的 peri-（周圍）",emoji:"🌟",roots:["experience"]},
    {word:"share",definition:"to give part of what you have to others",chinese:"分享",sentence:"Let's <strong>share</strong> these snacks.",tip:"SHARE 和 CARE 押韻",emoji:"🤝",roots:["share"]},
    {word:"surprise",definition:"something you did not expect to happen",chinese:"驚喜/驚訝",sentence:"What a wonderful <strong>surprise</strong>!",tip:"surprise 源自古法語 surprendre：sur-（拉丁 super「在上、超過」）＋ prise（拉丁 prehendere「抓取」）＝出其不意地抓住你 → 驚喜／驚訝",emoji:"🎉",roots:["surprise"]},
    {word:"agree",definition:"to think the same as someone else",chinese:"同意",sentence:"I <strong>agree</strong> with your idea.",tip:"AGREE 字尾有兩個 E；同意某人用 agree with somebody",emoji:"🤝",roots:["agree"]},
    {word:"receive",definition:"to get something given or sent to you",chinese:"收到",sentence:"I <strong>receive</strong>d a letter today.",tip:"RE(回)+CEIVE(拿取)＝把東西拿回來＝收到、接收",emoji:"📬",roots:["re","ceive"]},
    {word:"suppose",definition:"to think something is probably true",chinese:"假設/認為",sentence:"I <strong>suppose</strong> that is fair.",tip:"SUPPOSE 有兩個 P；I suppose so＝我想是吧",emoji:"🤔",roots:["suppose"]},
    {word:"include",definition:"to have something as a part",chinese:"包括",sentence:"Does the price <strong>include</strong> tax?",tip:"IN(向內)+CLUDE(關)＝關進裡面＝包含、包括",emoji:"📦",roots:["in","clude"]},
    {word:"continue",definition:"to keep doing something",chinese:"繼續",sentence:"Please <strong>continue</strong> reading aloud.",tip:"字源：con-＝一起，-tin-＝握住(源自拉丁 tenere，如 retain、contain)；continue＝持續握著→繼續",emoji:"▶️",roots:["continue"]},
    {word:"appear",definition:"to come into sight",chinese:"出現/看起來",sentence:"A rainbow <strong>appear</strong>ed in the sky!",tip:"APPEAR 有兩個 P；加 dis- 變 disappear（消失）",emoji:"🌈",roots:["appear"]},
    {word:"create",definition:"to make something new",chinese:"創造",sentence:"Let's <strong>create</strong> a new game!",tip:"CREATE 重音在第二音節；名詞形是 creation（創造）",emoji:"🎨",roots:["create"]},
    {word:"record",definition:"the best that has ever been done",chinese:"紀錄/唱片",sentence:"She broke the school <strong>record</strong>.",tip:"RECORD 當名詞和動詞重音不同",emoji:"📊",roots:["record"]},
    {word:"consider",definition:"to think about something carefully",chinese:"考慮",sentence:"Let me <strong>consider</strong> your offer.",tip:"CONSIDER 重音在第二音節；名詞形是 consideration（考量）",emoji:"🤔",roots:["consider"]},
    {word:"expect",definition:"to think something will happen",chinese:"期望/預期",sentence:"I <strong>expect</strong> it will be fun!",tip:"EXPECT = EX(向外) + SPECT(看)＝向外望著等＝期待（字根是 spect／spec「看」，同 inspect、respect；expect 拼寫時省去了 s）",emoji:"🔮",roots:["expect"]},
    {word:"suggest",definition:"to share an idea for others to think about",chinese:"建議",sentence:"I <strong>suggest</strong> we leave early.",tip:"SUG(從下)+GEST(帶出)＝把想法帶出來＝建議、提議",emoji:"💡",roots:["sug","gest"]},
    {word:"raise",definition:"to lift something up higher",chinese:"舉起/提高/養育",sentence:"<strong>Raise</strong> your hand if you know.",tip:"RAISE 有受詞，RISE 沒有",emoji:"🙋",roots:["raise"]},
    {word:"develop",definition:"to grow and change over time",chinese:"發展/開發",sentence:"Children <strong>develop</strong> quickly.",tip:"字源：de-＝解開/相反，velop＝包裹(同 envelop)；develop 原意「把包裹解開展開」→發展、開發",emoji:"📈",roots:["develop"]},
    {word:"reach",definition:"to stretch out and touch something",chinese:"到達/伸手拿",sentence:"I can <strong>reach</strong> the top shelf now!",tip:"REACH 和 TEACH 押韻",emoji:"🤚",roots:["reach"]},
    {word:"remain",definition:"to stay in the same place",chinese:"保持/剩餘",sentence:"Please <strong>remain</strong> seated.",tip:"REMAIN＝留下、依然是；複數名詞 remains 指殘餘、遺跡",emoji:"🪑",roots:["remain"]},
    {word:"offer",definition:"to say you will give or do something for someone",chinese:"提供/提議",sentence:"She <strong>offer</strong>ed to help me.",tip:"OFFER 有兩個 F",emoji:"🤲",roots:["offer"]},
    {word:"force",definition:"the strong push or power of something",chinese:"力量/強迫",sentence:"The <strong>force</strong> of the wind is strong.",tip:"FORCE 想到星際大戰",emoji:"💪",roots:["force"]},
    {word:"information",definition:"facts that tell you about something",chinese:"資訊",sentence:"I need more <strong>information</strong>.",tip:"IN(向內)+FORM(形塑)+ATION(名詞字尾)＝形塑進腦中的內容＝資訊、消息",emoji:"ℹ️",roots:["in","form","ation"]},
    {word:"produce",definition:"to make something",chinese:"生產/農產品",sentence:"Trees <strong>produce</strong> oxygen for us.",tip:"PRO(向前)+DUCE(引導)＝向前引出來＝生產、製造",emoji:"🌳",roots:["pro","duce"]},
    {word:"company",definition:"A place where people work to make or sell things",chinese:"公司/陪伴",sentence:"My mom works at a big <strong>company</strong>.",tip:"字源：compan-＝同伴(拉丁 com-一起＋panis麵包，原意「一起吃麵包的人」)，-y＝名詞字尾 → 同伴、公司",emoji:"🏢",roots:["company"]},
    {word:"money",definition:"coins and paper bills you use to buy things",chinese:"錢",sentence:"I save my <strong>money</strong> in a piggy bank.",tip:"字源：money 源自拉丁 moneta（鑄造錢幣的地方）；指硬幣和鈔票",emoji:"💰",roots:["money"]},
    {word:"further",definition:"more, or beyond where you are now",chinese:"更遠/進一步",sentence:"Let's look <strong>further</strong> into this.",tip:"字源：-er＝比較級字尾「更…」，furth- 源自 forth（向前）；further＝更遠、進一步",emoji:"➡️",roots:["further"]},
    {word:"per",definition:"for each one",chinese:"每/每一",sentence:"It costs ten dollars <strong>per</strong> ticket.",tip:"PER 表示「每一個」",emoji:"👤",roots:["per"]},
    {word:"job",definition:"the work a person does to earn money",chinese:"工作/職業",sentence:"He has a great <strong>job</strong>.",tip:"JOB 只有三個字母",emoji:"💼",roots:["job"]},
    {word:"head",definition:"the top part of your body, above your neck; also the person in charge of a group",chinese:"頭；領導/負責人",sentence:"I wear a hat on my <strong>head</strong>.",tip:"HEAD 的 EA 發短音 /ɛ/；也可指「領導」",emoji:"🧑",roots:["head"]},
    {word:"door",definition:"A flat part you open to go in or out of a room",chinese:"門",sentence:"Please close the <strong>door</strong> quietly.",tip:"DOOR 有兩個 O",emoji:"🚪",roots:["door"]},
    {word:"face",definition:"the front of your head with your eyes, nose, and mouth",chinese:"臉/面對",sentence:"Wash your <strong>face</strong> before bed.",tip:"FACE 也是動詞「面對」",emoji:"😊",roots:["face"]},
    {word:"eye",definition:"the part of your body you use to see",chinese:"眼睛",sentence:"Close your <strong>eye</strong>s and make a wish.",tip:"EYE 正著看反著看都一樣",emoji:"👁️",roots:["eye"]},
    {word:"hand",definition:"the part of your body at the end of your arm",chinese:"手/遞給",sentence:"Raise your <strong>hand</strong> to answer.",tip:"HAND 和 SAND 押韻",emoji:"✋",roots:["hand"]},
    {word:"book",definition:"sheets of paper joined together for reading",chinese:"書/預訂",sentence:"I finished reading this <strong>book</strong>.",tip:"BOOK 也可以當動詞「預訂」",emoji:"📖",roots:["book"]},
    {word:"home",definition:"the place where you live",chinese:"家",sentence:"There is no place like <strong>home</strong>.",tip:"HOME SWEET HOME!",emoji:"🏠",roots:["home"]},
    {word:"school",definition:"A place where children go to learn",chinese:"學校",sentence:"I love going to <strong>school</strong>.",tip:"SCHOOL 的 CH 發 /k/ 的音",emoji:"🏫",roots:["school"]},
    {word:"food",definition:"things you eat to live and grow",chinese:"食物",sentence:"Healthy <strong>food</strong> gives you energy.",tip:"FOOD 有兩個 O",emoji:"🍽️",roots:["food"]},
    {word:"water",definition:"the clear liquid we drink and find in rivers",chinese:"水/澆水",sentence:"Plants need <strong>water</strong> to grow.",tip:"WATER 是生命之源",emoji:"💧",roots:["water"]},
    {word:"car",definition:"A machine with wheels that people drive to go places",chinese:"汽車",sentence:"We drove the <strong>car</strong> to the beach.",tip:"CAR 只有三個字母",emoji:"🚗",roots:["car"]},
    {word:"table",definition:"furniture with a flat top and legs to hold things",chinese:"桌子/表格",sentence:"Set the plates on the <strong>table</strong>.",tip:"TABLE 的 A 發長音",emoji:"🍽️",roots:["table"]},
    {word:"today",definition:"this day, the one happening now",chinese:"今天",sentence:"<strong>Today</strong> is going to be great!",tip:"TODAY = TO（在、當）+ DAY（日），就是「當這一日」＝今天",emoji:"📅",roots:["today"]},
    {word:"year",definition:"A time of twelve months",chinese:"年/歲",sentence:"I am eight <strong>year</strong>s old.",tip:"YEAR 和 EAR 押韻",emoji:"📅",roots:["year"]},
    {word:"day",definition:"the bright time when the sun is out",chinese:"天/白天",sentence:"What a beautiful <strong>day</strong>!",tip:"DAY 和 PLAY 押韻",emoji:"☀️",roots:["day"]},
    {word:"name",definition:"what you call a person, animal, or thing",chinese:"名字/命名",sentence:"What is your puppy's <strong>name</strong>?",tip:"NAME 的 A 發長音",emoji:"📛",roots:["name"]},
    {word:"friend",definition:"someone you like and enjoy being with",chinese:"朋友",sentence:"You are my best <strong>friend</strong>.",tip:"FRIEND 裡面藏著 END",emoji:"🤝",roots:["friend"]},
    {word:"work",definition:"the effort you use to get something done",chinese:"工作/運作",sentence:"Hard <strong>work</strong> pays off.",tip:"WORK 和 WORD 很像",emoji:"💼",roots:["work"]},
    {word:"play",definition:"to have fun doing games or activities",chinese:"玩/演奏",sentence:"Let's go <strong>play</strong> in the yard!",tip:"PLAY 可以是玩或演奏",emoji:"🎮",roots:["play"]},
    {word:"run",definition:"to move fast on your feet",chinese:"跑",sentence:"I love to <strong>run</strong> in the park.",tip:"RUN 的過去式是 RAN",emoji:"🏃",roots:["run"]},
    {word:"read",definition:"to look at words and understand them",chinese:"讀/閱讀",sentence:"I <strong>read</strong> before bedtime.",tip:"READ 現在式和過去式拼法相同但發音不同",emoji:"📖",roots:["read"]},
    {word:"walk",definition:"to move on your feet step by step",chinese:"走路/散步",sentence:"Let's <strong>walk</strong> to the store.",tip:"WALK 的 L 不發音",emoji:"🚶",roots:["walk"]},
    {word:"eat",definition:"to put food in your mouth and swallow it",chinese:"吃",sentence:"Let's <strong>eat</strong> lunch together.",tip:"EAT 的過去式是 ATE",emoji:"🍽️",roots:["eat"]},
    {word:"drink",definition:"to swallow a liquid",chinese:"喝/飲料",sentence:"I <strong>drink</strong> juice every morning.",tip:"DRINK 的過去式是 DRANK",emoji:"🥤",roots:["drink"]},
    {word:"sleep",definition:"to rest with your eyes closed at night",chinese:"睡覺",sentence:"I <strong>sleep</strong> eight hours every night.",tip:"SLEEP 有兩個 E",emoji:"😴",roots:["sleep"]},
    {word:"speak",definition:"to say words out loud",chinese:"說/講話",sentence:"She can <strong>speak</strong> three languages.",tip:"SPEAK 的過去式是 SPOKE",emoji:"🗣️",roots:["speak"]},
    {word:"write",definition:"to make letters or words with a pen",chinese:"寫",sentence:"I <strong>write</strong> in my journal daily.",tip:"WRITE 的 W 不發音",emoji:"✍️",roots:["write"]},
    {word:"give",definition:"to hand something to someone to keep",chinese:"給",sentence:"I will <strong>give</strong> you my extra pencil.",tip:"GIVE 的過去式是 GAVE",emoji:"🎁",roots:["give"]},
    {word:"take",definition:"to pick up and carry something with you",chinese:"拿/帶走",sentence:"<strong>Take</strong> an umbrella with you.",tip:"TAKE 的過去式是 TOOK",emoji:"🤲",roots:["take"]},
    {word:"come",definition:"to move toward a place or person",chinese:"來",sentence:"<strong>Come</strong> here, please!",tip:"COME 的過去式是 CAME",emoji:"🏃",roots:["come"]},
    {word:"go",definition:"to move from one place to another",chinese:"去",sentence:"Let's <strong>go</strong> to the playground!",tip:"GO 的過去式是 WENT",emoji:"🚶",roots:["go"]},
    {word:"see",definition:"to notice something with your eyes",chinese:"看見",sentence:"I can <strong>see</strong> the ocean from here.",tip:"SEE 和 SEA 發音一樣",emoji:"👀",roots:["see"]},
    {word:"say",definition:"to speak words out loud",chinese:"說",sentence:"What did you <strong>say</strong>?",tip:"SAY 的過去式是 SAID",emoji:"💬",roots:["say"]},
    {word:"get",definition:"to receive or come to have something",chinese:"得到/變得",sentence:"I <strong>get</strong> a gift on my birthday.",tip:"GET 有很多用法",emoji:"🤲",roots:["get"]},
    {word:"like",definition:"to enjoy something or think it is nice",chinese:"喜歡/像",sentence:"I <strong>like</strong> chocolate ice cream.",tip:"LIKE 有「喜歡」和「像」兩個意思",emoji:"👍",roots:["like"]},
    {word:"time",definition:"the hour of the day, shown on a clock",chinese:"時間/次",sentence:"What <strong>time</strong> is it?",tip:"TIME 和 DIME 押韻",emoji:"⏰",roots:["time"]},
    {word:"long",definition:"measuring a lot from one end to the other",chinese:"長的/長久",sentence:"The snake is very <strong>long</strong>.",tip:"LONG 和 SHORT 相反",emoji:"📏",roots:["long"]},
    {word:"big",definition:"large in size and taking up a lot of space",chinese:"大的",sentence:"That is a <strong>big</strong> elephant!",tip:"BIG 只有三個字母",emoji:"🐘",roots:["big"]},
    {word:"good",definition:"kind, nice, or doing things the right way",chinese:"好的",sentence:"You are a <strong>good</strong> student.",tip:"GOOD 的比較級是 BETTER",emoji:"👍",roots:["good"]},
    {word:"bad",definition:"not good, or likely to cause problems",chinese:"壞的/糟糕的",sentence:"That was a <strong>bad</strong> idea.",tip:"BAD 的比較級是 WORSE",emoji:"👎",roots:["bad"]},
    {word:"happy",definition:"feeling glad and cheerful",chinese:"開心的",sentence:"I am so <strong>happy</strong> to see you!",tip:"字源：hap＝運氣(happen、mishap 同源)，-y＝形容詞字尾；happy＝有好運的→開心",emoji:"😊",roots:["happy"]},
    {word:"sad",definition:"feeling unhappy and wanting to cry",chinese:"難過的",sentence:"Don't be <strong>sad</strong>, things will get better.",tip:"SAD 只有三個字母",emoji:"😢",roots:["sad"]},
    {word:"old",definition:"having been around for a long time",chinese:"老的/舊的",sentence:"That is an <strong>old</strong> castle.",tip:"OLD 和 GOLD 押韻",emoji:"🏰",roots:["old"]},
    {word:"learn",definition:"to find out how to do something new",chinese:"學習",sentence:"I want to <strong>learn</strong> to cook.",tip:"LEARN 和 EARN 押韻",emoji:"🎓",roots:["learn"]},
    {word:"live",definition:"to have your home in a place",chinese:"住/活/現場的",sentence:"I <strong>live</strong> near the river.",tip:"LIVE 當動詞和形容詞發音不同",emoji:"🏠",roots:["live"]},
    {word:"feel",definition:"to notice an emotion or how your body is, like happy or tired",chinese:"感覺",sentence:"I <strong>feel</strong> great after exercising.",tip:"FEEL 有兩個 E",emoji:"😊",roots:["feel"]},
    {word:"fly",definition:"to move through the air using wings",chinese:"飛",sentence:"Birds <strong>fly</strong> south in winter.",tip:"FLY 的過去式是 FLEW",emoji:"🦅",roots:["fly"]},
    {word:"open",definition:"to move something so it is not shut",chinese:"打開/開放的",sentence:"<strong>Open</strong> the window for fresh air.",tip:"OPEN 和 CLOSE 相反",emoji:"📖",roots:["open"]},
    {word:"close",definition:"to shut something so it is not open",chinese:"關閉/靠近",sentence:"Please <strong>close</strong> your textbook.",tip:"CLOSE 當動詞和形容詞發音不同",emoji:"📕",roots:["close"]},
    {word:"listen",definition:"to pay attention to sounds with your ears",chinese:"聽",sentence:"<strong>Listen</strong> to the teacher carefully.",tip:"LISTEN 的 T 不發音",emoji:"👂",roots:["listen"]},
    {word:"sit",definition:"to rest with your bottom on a seat",chinese:"坐",sentence:"Please <strong>sit</strong> down and relax.",tip:"SIT 的過去式是 SAT",emoji:"🪑",roots:["sit"]}
  ]
};
