WORD_DATA["coca_l3"] = {
  name: "COCA L3",
  color: "#06b6d4",
  words: [
    {word:"abandon",chinese:"放棄/拋棄",sentence:"Don't <strong>abandon</strong> your dreams.",tip:"A+BANDON — 把東西ban(禁止)掉就是放棄",emoji:"🚪",roots:["a","ban","don"]},
    {word:"absorb",chinese:"吸收",sentence:"Plants <strong>absorb</strong> water from the soil.",tip:"ABSORB = AB + SORB（吸進去）",emoji:"🧽",roots:["ab","sorb"]},
    {word:"abstract",chinese:"抽象的",sentence:"Art can be <strong>abstract</strong> and colorful.",tip:"ABSTRACT = ABS + TRACT（從具體中拉出來）",emoji:"🎨",roots:["abs","tract"]},
    {word:"accompany",chinese:"陪伴/伴隨",sentence:"My mom will <strong>accompany</strong> me to school.",tip:"ACCOMPANY = AC + COMPANY（一起作伴）",emoji:"👫",roots:["ac","com","pa","ny"]},
    {word:"accomplish",chinese:"完成/達成",sentence:"We can <strong>accomplish</strong> anything together.",tip:"ACCOMPLISH = AC + COMP + LISH（徹底完成）",emoji:"🏆",roots:["ac","com","plish"]},
    {word:"accurate",chinese:"準確的",sentence:"Make sure your answer is <strong>accurate</strong>.",tip:"ACCURATE = AC + CUR + ATE（用心做到精準）",emoji:"🎯",roots:["ac","cur","ate"]},
    {word:"accuse",chinese:"指控/控告",sentence:"Don't <strong>accuse</strong> someone without proof.",tip:"ACCUSE = AC + CUSE（對著某人叫）",emoji:"👉",roots:["ac","cuse"]},
    {word:"achieve",chinese:"達成/實現",sentence:"Study hard to <strong>achieve</strong> your goals.",tip:"ACHIEVE 裡有 CHIEF（首領達到目標）",emoji:"⭐",roots:["a","chieve"]},
    {word:"acquire",chinese:"獲得",sentence:"He <strong>acquire</strong>d a new skill this summer.",tip:"ACQUIRE = AC + QUIRE（追求取得）",emoji:"🎁",roots:["ac","quire"]},
    {word:"adapt",chinese:"適應/改編",sentence:"Animals <strong>adapt</strong> to their environment.",tip:"ADAPT = AD + APT（使適合）",emoji:"🦎",roots:["ad","apt"]},
    {word:"adjust",chinese:"調整",sentence:"Please <strong>adjust</strong> the volume.",tip:"ADJUST = AD + JUST（使其剛好）",emoji:"🎚️",roots:["ad","just"]},
    {word:"admire",chinese:"欽佩/讚賞",sentence:"I <strong>admire</strong> your courage.",tip:"ADMIRE = AD + MIRE（看著驚嘆）",emoji:"😍",roots:["ad","mire"]},
    {word:"admit",chinese:"承認/准許進入",sentence:"He <strong>admit</strong>ted his mistake.",tip:"ADMIT = AD + MIT（送進去＝承認）",emoji:"🙋",roots:["ad","mit"]},
    {word:"adopt",chinese:"領養/採用",sentence:"We decided to <strong>adopt</strong> a puppy.",tip:"ADOPT = AD + OPT（選擇接納）",emoji:"🐶",roots:["ad","opt"]},
    {word:"advance",chinese:"前進/進步",sentence:"Technology continues to <strong>advance</strong>.",tip:"ADVANCE = AD + VANCE（往前走）",emoji:"🚀",roots:["ad","vance"]},
    {word:"advertise",chinese:"廣告/宣傳",sentence:"They <strong>advertise</strong> on TV.",tip:"ADVERTISE = AD + VERT + ISE（轉向注意）",emoji:"📺",roots:["ad","ver","tise"]},
    {word:"affect",chinese:"影響",sentence:"Rain can <strong>affect</strong> our plans.",tip:"AFFECT（動詞影響）vs EFFECT（名詞效果）",emoji:"🌊",roots:["af","fect"]},
    {word:"afford",chinese:"負擔得起",sentence:"Can we <strong>afford</strong> this toy?",tip:"AFFORD = AF + FORD（往前到達＝夠得到）",emoji:"💰",roots:["af","ford"]},
    {word:"agency",chinese:"機構/代理",sentence:"The travel <strong>agency</strong> booked our trip.",tip:"AGENCY = AGENT + CY（代理的地方）",emoji:"🏢",roots:["a","gen","cy"]},
    {word:"agent",chinese:"代理人/特工",sentence:"A secret <strong>agent</strong> has many skills.",tip:"AGENT = AG + ENT（行動的人）",emoji:"🕵️",roots:["a","gent"]},
    {word:"agree",chinese:"同意",sentence:"I <strong>agree</strong> with your idea.",tip:"AGREE = A + GREE（想法合在一起）",emoji:"🤝",roots:["a","gree"]},
    {word:"ahead",chinese:"在前方",sentence:"Go <strong>ahead</strong> and start eating.",tip:"AHEAD = A + HEAD（在頭的方向）",emoji:"➡️",roots:["a","head"]},
    {word:"aim",chinese:"目標/瞄準",sentence:"My <strong>aim</strong> is to get an A+.",tip:"AIM 只有三個字母，像瞄準一樣精簡",emoji:"🎯",roots:["aim"]},
    {word:"alarm",chinese:"警報/鬧鐘",sentence:"The fire <strong>alarm</strong> rang loudly.",tip:"ALARM 有兩個 A，想像響亮的警報聲",emoji:"🚨",roots:["a","larm"]},
    {word:"allow",chinese:"允許",sentence:"Mom will <strong>allow</strong> me to stay up late.",tip:"ALLOW = AL + LOW（讓某事通過）",emoji:"✅",roots:["al","low"]},
    {word:"amount",chinese:"數量/金額",sentence:"A large <strong>amount</strong> of rain fell today.",tip:"AMOUNT = A + MOUNT（往上累積的量）",emoji:"📊",roots:["a","mount"]},
    {word:"amuse",chinese:"逗樂/使娛樂",sentence:"The clown <strong>amuse</strong>d the children.",tip:"AMUSE = A + MUSE（像繆斯女神帶來歡樂）",emoji:"🤡",roots:["a","muse"]},
    {word:"ancient",chinese:"古代的",sentence:"The <strong>ancient</strong> pyramids are amazing.",tip:"ANCIENT = ANCI + ENT（很久以前的）",emoji:"🏛️",roots:["an","cient"]},
    {word:"announce",chinese:"宣布",sentence:"The principal will <strong>announce</strong> the winner.",tip:"ANNOUNCE = AN + NOUNCE（發出通知）",emoji:"📢",roots:["an","nounce"]},
    {word:"annual",chinese:"每年的",sentence:"We have an <strong>annual</strong> school fair.",tip:"ANNUAL = ANNU + AL（年的，像anniversary）",emoji:"📅",roots:["an","nu","al"]},
    {word:"anxiety",chinese:"焦慮",sentence:"She felt <strong>anxiety</strong> before the test.",tip:"ANXIETY = ANXI + ETY（心裡著急）",emoji:"😰",roots:["anx","i","ety"]},
    {word:"apart",chinese:"分開",sentence:"The two towns are far <strong>apart</strong>.",tip:"APART = A + PART（成為部分＝分開）",emoji:"↔️",roots:["a","part"]},
    {word:"appeal",chinese:"吸引力/呼籲",sentence:"The colorful toy has great <strong>appeal</strong>.",tip:"APPEAL = AP + PEAL（呼喊吸引）",emoji:"✨",roots:["ap","peal"]},
    {word:"appear",chinese:"出現/看起來",sentence:"Stars <strong>appear</strong> at night.",tip:"APPEAR = AP + PEAR（來到眼前）",emoji:"⭐",roots:["ap","pear"]},
    {word:"apply",chinese:"申請/應用",sentence:"I will <strong>apply</strong> for the school contest.",tip:"APPLY = AP + PLY（折疊放上去）",emoji:"📝",roots:["ap","ply"]},
    {word:"appoint",chinese:"任命/指定",sentence:"They <strong>appoint</strong>ed her as class leader.",tip:"APPOINT = AP + POINT（指向某人）",emoji:"👆",roots:["ap","point"]},
    {word:"appreciate",chinese:"感謝/欣賞",sentence:"I <strong>appreciate</strong> your kindness.",tip:"APPRECIATE = AP + PRECI + ATE（看到價值）",emoji:"🙏",roots:["ap","preci","ate"]},
    {word:"approach",chinese:"接近/方法",sentence:"We <strong>approach</strong>ed the castle slowly.",tip:"APPROACH = AP + PROACH（靠近）",emoji:"🚶",roots:["ap","proach"]},
    {word:"approve",chinese:"批准/贊成",sentence:"Dad <strong>approve</strong>d my plan.",tip:"APPROVE = AP + PROVE（證明是好的）",emoji:"👍",roots:["ap","prove"]},
    {word:"argue",chinese:"爭論",sentence:"Don't <strong>argue</strong> with your sister.",tip:"ARGUE 結尾不加 E 也不省 E",emoji:"🗣️",roots:["ar","gue"]},
    {word:"arrange",chinese:"安排/整理",sentence:"Let me <strong>arrange</strong> the flowers.",tip:"ARRANGE = AR + RANGE（排列好）",emoji:"💐",roots:["ar","range"]},
    {word:"arrest",chinese:"逮捕",sentence:"The police <strong>arrest</strong>ed the thief.",tip:"ARREST = AR + REST（使其停下來）",emoji:"🚔",roots:["ar","rest"]},
    {word:"arrive",chinese:"到達",sentence:"We will <strong>arrive</strong> at 5 PM.",tip:"ARRIVE = AR + RIVE（到達河岸＝目的地）",emoji:"🏁",roots:["ar","rive"]},
    {word:"assist",chinese:"協助",sentence:"The nurse <strong>assist</strong>ed the doctor.",tip:"ASSIST = AS + SIST（站在旁邊幫忙）",emoji:"🤝",roots:["as","sist"]},
    {word:"associate",chinese:"聯想/夥伴",sentence:"I <strong>associate</strong> summer with ice cream.",tip:"ASSOCIATE = AS + SOCI + ATE（和社團在一起）",emoji:"🔗",roots:["as","so","ci","ate"]},
    {word:"assume",chinese:"假設/認為",sentence:"Don't <strong>assume</strong> without asking.",tip:"ASSUME = AS + SUME（把東西拿給自己）",emoji:"🤔",roots:["as","sume"]},
    {word:"attach",chinese:"附加/貼上",sentence:"Please <strong>attach</strong> your photo to the form.",tip:"ATTACH = AT + TACH（釘上去）",emoji:"📎",roots:["at","tach"]},
    {word:"attack",chinese:"攻擊",sentence:"The cat will <strong>attack</strong> the toy mouse.",tip:"ATTACK = AT + TACK（釘上去打）",emoji:"⚔️",roots:["at","tack"]},
    {word:"attempt",chinese:"嘗試",sentence:"She <strong>attempt</strong>ed to climb the tree.",tip:"ATTEMPT = AT + TEMPT（試著去做）",emoji:"🧗",roots:["at","tempt"]},
    {word:"attend",chinese:"參加/出席",sentence:"I will <strong>attend</strong> the meeting.",tip:"ATTEND = AT + TEND（朝向某處伸展）",emoji:"🙋",roots:["at","tend"]},
    {word:"attract",chinese:"吸引",sentence:"Flowers <strong>attract</strong> butterflies.",tip:"ATTRACT = AT + TRACT（拉向自己）",emoji:"🧲",roots:["at","tract"]},
    {word:"authority",chinese:"權威/當局",sentence:"The teacher has <strong>authority</strong> in class.",tip:"AUTHORITY = AUTHOR + ITY（作者般的權力）",emoji:"👮",roots:["au","thor","ity"]},
    {word:"avoid",chinese:"避免",sentence:"<strong>Avoid</strong> eating too much candy.",tip:"AVOID = A + VOID（使空掉＝避開）",emoji:"🚫",roots:["a","void"]},
    {word:"awake",chinese:"醒著的",sentence:"I was <strong>awake</strong> all night.",tip:"AWAKE = A + WAKE（醒來的狀態）",emoji:"👀",roots:["a","wake"]},
    {word:"awful",chinese:"糟糕的",sentence:"The weather is <strong>awful</strong> today.",tip:"AWFUL = AWE + FUL（充滿敬畏→變成糟糕）",emoji:"😖",roots:["aw","ful"]},
    {word:"balance",chinese:"平衡",sentence:"Try to keep your <strong>balance</strong> on one foot.",tip:"BALANCE = BAL + ANCE（兩邊盤子一樣重）",emoji:"⚖️",roots:["bal","ance"]},
    {word:"ban",chinese:"禁止",sentence:"They <strong>ban</strong>ned plastic bags.",tip:"BAN 只有三個字母，簡短有力像禁令一樣",emoji:"🚫",roots:["ban"]},
    {word:"bargain",chinese:"便宜貨/討價還價",sentence:"This toy is a real <strong>bargain</strong>!",tip:"BARGAIN = BAR + GAIN（爭取好處）",emoji:"🏷️",roots:["bar","gain"]},
    {word:"base",chinese:"基礎/基地",sentence:"The lamp has a heavy <strong>base</strong>.",tip:"BASE 和 BASIC 同家族（底部的）",emoji:"🏠",roots:["base"]},
    {word:"basis",chinese:"基礎/根據",sentence:"We meet on a weekly <strong>basis</strong>.",tip:"BASIS 是 BASE 的名詞形式",emoji:"🧱",roots:["ba","sis"]},
    {word:"battle",chinese:"戰鬥",sentence:"The knights prepared for <strong>battle</strong>.",tip:"BATTLE 有兩個 T，像打鬥的激烈",emoji:"⚔️",roots:["bat","tle"]},
    {word:"beat",chinese:"打敗/節拍",sentence:"We <strong>beat</strong> the other team 3 to 1.",tip:"BEAT 和 HEAT 押韻",emoji:"🥁",roots:["beat"]},
    {word:"behave",chinese:"表現/行為端正",sentence:"Please <strong>behave</strong> well in class.",tip:"BEHAVE = BE + HAVE（要好好有禮貌）",emoji:"😇",roots:["be","have"]},
    {word:"belief",chinese:"信念/相信",sentence:"I have a strong <strong>belief</strong> in kindness.",tip:"BELIEF 是 BELIEVE 的名詞",emoji:"💫",roots:["be","lief"]},
    {word:"belong",chinese:"屬於",sentence:"This book <strong>belong</strong>s to me.",tip:"BELONG = BE + LONG（在旁邊很久＝屬於）",emoji:"🏷️",roots:["be","long"]},
    {word:"bend",chinese:"彎曲",sentence:"<strong>Bend</strong> your knees when you jump.",tip:"BEND 和 SEND 押韻",emoji:"🔄",roots:["bend"]},
    {word:"benefit",chinese:"好處/受益",sentence:"Reading has many <strong>benefit</strong>s.",tip:"BENEFIT = BENE（好）+ FIT（做）",emoji:"💪",roots:["bene","fit"]},
    {word:"beyond",chinese:"超越/在...之外",sentence:"The view <strong>beyond</strong> the hill is beautiful.",tip:"BEYOND = BE + YOND（在那邊更遠處）",emoji:"🌄",roots:["be","yond"]},
    {word:"bind",chinese:"綁/約束",sentence:"Use rope to <strong>bind</strong> the box shut.",tip:"BIND 和 FIND 押韻（找到就綁住）",emoji:"🪢",roots:["bind"]},
    {word:"bite",chinese:"咬",sentence:"Don't let the dog <strong>bite</strong> you!",tip:"BITE 和 KITE 押韻",emoji:"🦷",roots:["bite"]},
    {word:"blame",chinese:"責怪",sentence:"Don't <strong>blame</strong> others for your mistakes.",tip:"BLAME 和 FLAME 押韻",emoji:"👉",roots:["blame"]},
    {word:"blank",chinese:"空白的",sentence:"Write your name on the <strong>blank</strong> line.",tip:"BLANK 想像一張空白的紙",emoji:"📄",roots:["blank"]},
    {word:"blast",chinese:"爆炸/一陣",sentence:"A <strong>blast</strong> of wind blew my hat away.",tip:"BLAST 和 FAST 押韻（爆炸很快）",emoji:"💥",roots:["blast"]},
    {word:"bleed",chinese:"流血",sentence:"My finger started to <strong>bleed</strong>.",tip:"BLEED 有兩個 E（像血流不止）",emoji:"🩸",roots:["bleed"]},
    {word:"bless",chinese:"祝福",sentence:"May God <strong>bless</strong> you.",tip:"BLESS 和 LESS 押韻",emoji:"🙏",roots:["bless"]},
    {word:"blind",chinese:"瞎的/盲目的",sentence:"The <strong>blind</strong> man uses a white cane.",tip:"BLIND 和 FIND 押韻",emoji:"🦯",roots:["blind"]},
    {word:"block",chinese:"阻擋/街區",sentence:"A big rock <strong>block</strong>ed the road.",tip:"BLOCK 和 CLOCK 押韻",emoji:"🧱",roots:["block"]},
    {word:"blow",chinese:"吹",sentence:"<strong>Blow</strong> out the birthday candles!",tip:"BLOW 和 SNOW 押韻",emoji:"🌬️",roots:["blow"]},
    {word:"board",chinese:"板子/上車",sentence:"Write on the white <strong>board</strong>.",tip:"BOARD 可以是木板也可以是上船",emoji:"📋",roots:["board"]},
    {word:"boil",chinese:"煮沸",sentence:"<strong>Boil</strong> water to make tea.",tip:"BOIL 和 OIL 押韻",emoji:"🫕",roots:["boil"]},
    {word:"bomb",chinese:"炸彈",sentence:"The <strong>bomb</strong> exploded far away.",tip:"BOMB 的 B 在結尾不發音",emoji:"💣",roots:["bomb"]},
    {word:"bond",chinese:"紐帶/連結",sentence:"The <strong>bond</strong> between friends is strong.",tip:"BOND 和 POND 押韻",emoji:"🔗",roots:["bond"]},
    {word:"border",chinese:"邊界/邊緣",sentence:"We crossed the <strong>border</strong> into Canada.",tip:"BORDER = BORD + ER（邊的地方）",emoji:"🗺️",roots:["bor","der"]},
    {word:"bore",chinese:"使無聊/鑽孔",sentence:"The long speech <strong>bore</strong>d everyone.",tip:"BORE 和 MORE 押韻",emoji:"😴",roots:["bore"]},
    {word:"bother",chinese:"打擾/煩惱",sentence:"Sorry to <strong>bother</strong> you.",tip:"BOTHER 和 BROTHER 差一個字母",emoji:"😣",roots:["both","er"]},
    {word:"bottom",chinese:"底部",sentence:"The treasure is at the <strong>bottom</strong> of the sea.",tip:"BOTTOM 有兩個 T",emoji:"⬇️",roots:["bot","tom"]},
    {word:"bound",chinese:"一定會/跳躍",sentence:"The ball <strong>bound</strong>ed across the yard.",tip:"BOUND 和 FOUND 押韻",emoji:"🏀",roots:["bound"]},
    {word:"bow",chinese:"鞠躬/弓",sentence:"The actor took a <strong>bow</strong> on stage.",tip:"BOW 有兩個發音：鞠躬/弓",emoji:"🎀",roots:["bow"]},
    {word:"brain",chinese:"大腦",sentence:"Use your <strong>brain</strong> to solve the puzzle.",tip:"BRAIN 和 TRAIN 押韻",emoji:"🧠",roots:["brain"]},
    {word:"branch",chinese:"樹枝/分支",sentence:"The bird sat on a <strong>branch</strong>.",tip:"BRANCH 像樹枝分叉出去",emoji:"🌿",roots:["branch"]},
    {word:"brave",chinese:"勇敢的",sentence:"The firefighter is very <strong>brave</strong>.",tip:"BRAVE 和 WAVE 押韻",emoji:"🦸",roots:["brave"]},
    {word:"breathe",chinese:"呼吸",sentence:"Take a moment to <strong>breathe</strong> deeply.",tip:"BREATHE 結尾有E（動詞），BREATH沒有（名詞）",emoji:"🌬️",roots:["breathe"]},
    {word:"breed",chinese:"繁殖/品種",sentence:"What <strong>breed</strong> is your dog?",tip:"BREED 有兩個 E",emoji:"🐕",roots:["breed"]},
    {word:"brick",chinese:"磚塊",sentence:"The house is made of <strong>brick</strong>.",tip:"BRICK 和 STICK 押韻",emoji:"🧱",roots:["brick"]},
    {word:"brief",chinese:"簡短的",sentence:"Please give a <strong>brief</strong> answer.",tip:"BRIEF 裡有 I before E",emoji:"📝",roots:["brief"]},
    {word:"broad",chinese:"寬闘的",sentence:"The river is very <strong>broad</strong>.",tip:"BROAD 和 ROAD 押韻（寬闘的路）",emoji:"↔️",roots:["broad"]},
    {word:"broadcast",chinese:"廣播",sentence:"They <strong>broadcast</strong> news every morning.",tip:"BROADCAST = BROAD + CAST（廣泛投射）",emoji:"📡",roots:["broad","cast"]},
    {word:"budget",chinese:"預算",sentence:"We planned our vacation <strong>budget</strong>.",tip:"BUDGET 原意是小錢包",emoji:"💰",roots:["bud","get"]},
    {word:"bunch",chinese:"一串/一群",sentence:"I bought a <strong>bunch</strong> of bananas.",tip:"BUNCH 和 LUNCH 押韻",emoji:"🍌",roots:["bunch"]},
    {word:"burden",chinese:"負擔",sentence:"Don't carry such a heavy <strong>burden</strong>.",tip:"BURDEN = BURD + EN（沉重的東西）",emoji:"🎒",roots:["bur","den"]},
    {word:"burn",chinese:"燃燒",sentence:"Be careful not to <strong>burn</strong> yourself.",tip:"BURN 和 TURN 押韻",emoji:"🔥",roots:["burn"]},
    {word:"burst",chinese:"爆裂",sentence:"The balloon <strong>burst</strong> with a pop.",tip:"BURST 和 FIRST 押韻",emoji:"🎈",roots:["burst"]},
    {word:"bury",chinese:"埋葬/埋藏",sentence:"The dog likes to <strong>bury</strong> bones.",tip:"BURY 發音像 BERRY（莓果）",emoji:"⚰️",roots:["bu","ry"]},
    {word:"bush",chinese:"灌木叢",sentence:"The rabbit hid behind the <strong>bush</strong>.",tip:"BUSH 和 PUSH 押韻",emoji:"🌳",roots:["bush"]},
    {word:"butter",chinese:"奶油",sentence:"Spread <strong>butter</strong> on the toast.",tip:"BUTTER 有兩個 T",emoji:"🧈",roots:["but","ter"]},
    {word:"cabin",chinese:"小屋/機艙",sentence:"We stayed in a <strong>cabin</strong> in the woods.",tip:"CABIN 和 CAPTAIN 的 CAB 相同",emoji:"🏡",roots:["cab","in"]},
    {word:"calculate",chinese:"計算",sentence:"Can you <strong>calculate</strong> the total?",tip:"CALCULATE = CALC + UL + ATE（用石頭算）",emoji:"🧮",roots:["cal","cu","late"]},
    {word:"campaign",chinese:"活動/運動",sentence:"The school ran a recycling <strong>campaign</strong>.",tip:"CAMPAIGN = CAMP + AIGN（在營地行動）",emoji:"📣",roots:["cam","paign"]},
    {word:"capable",chinese:"有能力的",sentence:"She is <strong>capable</strong> of great things.",tip:"CAPABLE = CAP + ABLE（能抓住的）",emoji:"💪",roots:["cap","able"]},
    {word:"capture",chinese:"捕捉",sentence:"The photographer <strong>capture</strong>d a sunset.",tip:"CAPTURE = CAPT + URE（抓住）",emoji:"📸",roots:["cap","ture"]},
    {word:"career",chinese:"職業/生涯",sentence:"She wants a <strong>career</strong> in medicine.",tip:"CAREER 有兩個 E（長長的人生道路）",emoji:"💼",roots:["ca","reer"]},
    {word:"castle",chinese:"城堡",sentence:"The princess lived in a <strong>castle</strong>.",tip:"CASTLE 的 T 不發音",emoji:"🏰",roots:["cas","tle"]},
    {word:"category",chinese:"類別",sentence:"Sort these books by <strong>category</strong>.",tip:"CATEGORY = CATE + GORY（歸類的框架）",emoji:"📁",roots:["cat","e","go","ry"]},
    {word:"cause",chinese:"原因/引起",sentence:"What <strong>cause</strong>d the fire?",tip:"CAUSE 和 BECAUSE 有關聯",emoji:"💡",roots:["cause"]},
    {word:"celebrate",chinese:"慶祝",sentence:"Let's <strong>celebrate</strong> your birthday!",tip:"CELEBRATE = CELEB + RATE（讓名人來慶祝）",emoji:"🎉",roots:["cel","e","brate"]},
    {word:"ceremony",chinese:"典禮/儀式",sentence:"The graduation <strong>ceremony</strong> was beautiful.",tip:"CEREMONY = CERE + MONY（莊嚴的儀式）",emoji:"🎓",roots:["cer","e","mo","ny"]},
    {word:"chain",chinese:"鏈條/連鎖",sentence:"The dog is on a <strong>chain</strong>.",tip:"CHAIN 和 TRAIN 押韻",emoji:"⛓️",roots:["chain"]},
    {word:"challenge",chinese:"挑戰",sentence:"This puzzle is a fun <strong>challenge</strong>.",tip:"CHALLENGE = CHALL + ENGE（叫人出來比）",emoji:"🏋️",roots:["chal","lenge"]},
    {word:"champion",chinese:"冠軍",sentence:"She is the spelling bee <strong>champion</strong>.",tip:"CHAMPION = CHAMP + ION（戰場上的贏家）",emoji:"🏆",roots:["cham","pi","on"]},
    {word:"chapter",chinese:"章節",sentence:"Read <strong>chapter</strong> three tonight.",tip:"CHAPTER = CHAPT + ER（書的一段）",emoji:"📖",roots:["chap","ter"]},
    {word:"charge",chinese:"充電/收費/指控",sentence:"I need to <strong>charge</strong> my phone.",tip:"CHARGE 一詞多義：收費、充電、衝鋒",emoji:"🔌",roots:["charge"]},
    {word:"charity",chinese:"慈善",sentence:"We donated money to <strong>charity</strong>.",tip:"CHARITY = CHAR + ITY（關愛的行為）",emoji:"💝",roots:["char","i","ty"]},
    {word:"charm",chinese:"魅力/吸引",sentence:"The small town has a lot of <strong>charm</strong>.",tip:"CHARM 和 FARM 押韻",emoji:"✨",roots:["charm"]},
    {word:"chase",chinese:"追趕",sentence:"The dog likes to <strong>chase</strong> cats.",tip:"CHASE 和 RACE 押韻",emoji:"🏃",roots:["chase"]},
    {word:"cheat",chinese:"作弊/欺騙",sentence:"Never <strong>cheat</strong> on a test.",tip:"CHEAT 和 BEAT 押韻",emoji:"🃏",roots:["cheat"]},
    {word:"check",chinese:"檢查/支票",sentence:"<strong>Check</strong> your work before you submit.",tip:"CHECK 和 DECK 押韻",emoji:"✅",roots:["check"]},
    {word:"chief",chinese:"首領/主要的",sentence:"The <strong>chief</strong> made an important decision.",tip:"CHIEF 裡有 I before E",emoji:"👑",roots:["chief"]},
    {word:"choice",chinese:"選擇",sentence:"You have three <strong>choice</strong>s.",tip:"CHOICE = CHOI + CE（選出來的）",emoji:"🔀",roots:["choice"]},
    {word:"civil",chinese:"公民的/文明的",sentence:"We should be <strong>civil</strong> to each other.",tip:"CIVIL = CIV + IL（城市市民的）",emoji:"🏛️",roots:["civ","il"]},
    {word:"claim",chinese:"聲稱/索賠",sentence:"He <strong>claim</strong>s to be the fastest runner.",tip:"CLAIM 和 FAME 有點像",emoji:"📢",roots:["claim"]},
    {word:"classic",chinese:"經典的",sentence:"This is a <strong>classic</strong> fairy tale.",tip:"CLASSIC = CLASS + IC（一等的）",emoji:"📚",roots:["clas","sic"]},
    {word:"clay",chinese:"黏土",sentence:"We made pots with <strong>clay</strong>.",tip:"CLAY 和 PLAY 押韻",emoji:"🏺",roots:["clay"]},
    {word:"cliff",chinese:"懸崖",sentence:"Don't stand near the <strong>cliff</strong> edge!",tip:"CLIFF 有兩個 F",emoji:"🏔️",roots:["cliff"]},
    {word:"climb",chinese:"攀爬",sentence:"Let's <strong>climb</strong> the mountain!",tip:"CLIMB 的 B 不發音",emoji:"🧗",roots:["climb"]},
    {word:"club",chinese:"社團/俱樂部",sentence:"I joined the science <strong>club</strong>.",tip:"CLUB 和 TUB 押韻",emoji:"🎭",roots:["club"]},
    {word:"coach",chinese:"教練",sentence:"The <strong>coach</strong> taught us new moves.",tip:"COACH 和 APPROACH 有相同結尾",emoji:"🏈",roots:["coach"]},
    {word:"coal",chinese:"煤炭",sentence:"Santa gives <strong>coal</strong> to naughty kids.",tip:"COAL 和 GOAL 押韻",emoji:"⚫",roots:["coal"]},
    {word:"coast",chinese:"海岸",sentence:"We drove along the <strong>coast</strong>.",tip:"COAST 和 TOAST 押韻",emoji:"🏖️",roots:["coast"]},
    {word:"code",chinese:"密碼/代碼",sentence:"Enter the secret <strong>code</strong>.",tip:"CODE 和 ROAD 有類似的長 O 音",emoji:"🔐",roots:["code"]},
    {word:"collect",chinese:"收集",sentence:"I <strong>collect</strong> stamps from many countries.",tip:"COLLECT = COL + LECT（一起挑選）",emoji:"📮",roots:["col","lect"]},
    {word:"colony",chinese:"殖民地/群體",sentence:"The ants built a large <strong>colony</strong>.",tip:"COLONY = COL + ONY（一群住在一起）",emoji:"🐜",roots:["col","o","ny"]},
    {word:"combine",chinese:"結合",sentence:"<strong>Combine</strong> flour and eggs to make dough.",tip:"COMBINE = COM + BINE（兩個放一起）",emoji:"🔀",roots:["com","bine"]},
    {word:"comfort",chinese:"安慰/舒適",sentence:"Mom gave me <strong>comfort</strong> when I was sad.",tip:"COMFORT = COM + FORT（一起強壯＝安慰）",emoji:"🤗",roots:["com","fort"]},
    {word:"command",chinese:"命令/指揮",sentence:"The captain gave a <strong>command</strong>.",tip:"COMMAND = COM + MAND（交給手中）",emoji:"📣",roots:["com","mand"]},
    {word:"comment",chinese:"評論",sentence:"Please leave a <strong>comment</strong> below.",tip:"COMMENT = COM + MENT（一起想的話）",emoji:"💬",roots:["com","ment"]},
    {word:"commit",chinese:"承諾/犯(罪)",sentence:"I <strong>commit</strong> to studying every day.",tip:"COMMIT = COM + MIT（完全投入送出）",emoji:"🤝",roots:["com","mit"]},
    {word:"committee",chinese:"委員會",sentence:"The <strong>committee</strong> made the decision.",tip:"COMMITTEE 有兩個 M、兩個 T、兩個 E",emoji:"👥",roots:["com","mit","tee"]},
    {word:"communicate",chinese:"溝通",sentence:"Animals <strong>communicate</strong> in many ways.",tip:"COMMUNICATE = COM + MUNIC + ATE（共同分享）",emoji:"💬",roots:["com","mu","ni","cate"]},
    {word:"community",chinese:"社區",sentence:"Our <strong>community</strong> is very friendly.",tip:"COMMUNITY = COM + MUNI + TY（共同的團體）",emoji:"🏘️",roots:["com","mu","ni","ty"]},
    {word:"companion",chinese:"同伴",sentence:"My dog is my best <strong>companion</strong>.",tip:"COMPANION = COM + PAN + ION（一起吃麵包的人）",emoji:"🐕",roots:["com","pan","ion"]},
    {word:"compare",chinese:"比較",sentence:"Let's <strong>compare</strong> the two pictures.",tip:"COMPARE = COM + PARE（放在一起配對）",emoji:"⚖️",roots:["com","pare"]},
    {word:"compete",chinese:"競爭",sentence:"We <strong>compete</strong> in a swimming race.",tip:"COMPETE = COM + PETE（一起追求）",emoji:"🏊",roots:["com","pete"]},
    {word:"complain",chinese:"抱怨",sentence:"Don't <strong>complain</strong> about the food.",tip:"COMPLAIN = COM + PLAIN（大聲說出不滿）",emoji:"😤",roots:["com","plain"]},
    {word:"complex",chinese:"複雜的",sentence:"The puzzle is very <strong>complex</strong>.",tip:"COMPLEX = COM + PLEX（纏在一起的）",emoji:"🧩",roots:["com","plex"]},
    {word:"concentrate",chinese:"專注",sentence:"Please <strong>concentrate</strong> on your work.",tip:"CONCENTRATE = CON + CENTR + ATE（集中到中心）",emoji:"🎯",roots:["con","cen","trate"]},
    {word:"concern",chinese:"擔心/關心",sentence:"I am <strong>concern</strong>ed about your health.",tip:"CONCERN = CON + CERN（一起篩選在意的事）",emoji:"😟",roots:["con","cern"]},
    {word:"condition",chinese:"條件/狀況",sentence:"The car is in good <strong>condition</strong>.",tip:"CONDITION = CON + DIT + ION（一起說好的事）",emoji:"📋",roots:["con","di","tion"]},
    {word:"conduct",chinese:"行為/指揮",sentence:"He <strong>conduct</strong>s the orchestra.",tip:"CONDUCT = CON + DUCT（一起引導）",emoji:"🎵",roots:["con","duct"]},
    {word:"confess",chinese:"承認/坦白",sentence:"He <strong>confess</strong>ed that he ate the cake.",tip:"CONFESS = CON + FESS（完全說出來）",emoji:"😳",roots:["con","fess"]},
    {word:"confidence",chinese:"信心",sentence:"She speaks with <strong>confidence</strong>.",tip:"CONFIDENCE = CON + FID + ENCE（完全相信）",emoji:"💪",roots:["con","fi","dence"]},
    {word:"confirm",chinese:"確認",sentence:"Please <strong>confirm</strong> your booking.",tip:"CONFIRM = CON + FIRM（使堅固確定）",emoji:"✅",roots:["con","firm"]},
    {word:"conflict",chinese:"衝突",sentence:"They resolved the <strong>conflict</strong> peacefully.",tip:"CONFLICT = CON + FLICT（一起打擊）",emoji:"⚔️",roots:["con","flict"]},
    {word:"confuse",chinese:"使困惑",sentence:"The directions <strong>confuse</strong>d me.",tip:"CONFUSE = CON + FUSE（混在一起分不清）",emoji:"😵",roots:["con","fuse"]},
    {word:"connect",chinese:"連接",sentence:"<strong>Connect</strong> the dots to make a picture.",tip:"CONNECT = CON + NECT（綁在一起）",emoji:"🔗",roots:["con","nect"]},
    {word:"conscious",chinese:"有意識的/察覺的",sentence:"Be <strong>conscious</strong> of your surroundings.",tip:"CONSCIOUS = CON + SCI + OUS（一起知道的）",emoji:"👁️",roots:["con","sci","ous"]},
    {word:"consider",chinese:"考慮",sentence:"<strong>Consider</strong> all the options carefully.",tip:"CONSIDER = CON + SIDER（和星星一起看＝仔細想）",emoji:"🤔",roots:["con","sid","er"]},
    {word:"consist",chinese:"由...組成",sentence:"The team <strong>consist</strong>s of five players.",tip:"CONSIST = CON + SIST（站在一起組成）",emoji:"🧩",roots:["con","sist"]},
    {word:"constant",chinese:"不斷的/恆定的",sentence:"The <strong>constant</strong> noise kept me awake.",tip:"CONSTANT = CON + STANT（一直站著不變）",emoji:"♾️",roots:["con","stant"]},
    {word:"construct",chinese:"建造",sentence:"Workers <strong>construct</strong> a new bridge.",tip:"CONSTRUCT = CON + STRUCT（一起堆疊建造）",emoji:"🏗️",roots:["con","struct"]},
    {word:"consult",chinese:"諮詢",sentence:"I need to <strong>consult</strong> a doctor.",tip:"CONSULT = CON + SULT（一起商量）",emoji:"👨‍⚕️",roots:["con","sult"]},
    {word:"contact",chinese:"聯繫/接觸",sentence:"Please <strong>contact</strong> me by phone.",tip:"CONTACT = CON + TACT（觸碰在一起）",emoji:"📞",roots:["con","tact"]},
    {word:"contain",chinese:"包含/容納",sentence:"This box <strong>contain</strong>s chocolates.",tip:"CONTAIN = CON + TAIN（一起持有）",emoji:"📦",roots:["con","tain"]},
    {word:"content",chinese:"內容/滿足的",sentence:"I am <strong>content</strong> with my grades.",tip:"CONTENT 重音不同意思不同（內容/滿足）",emoji:"😊",roots:["con","tent"]},
    {word:"contest",chinese:"比賽/競賽",sentence:"She won the art <strong>contest</strong>.",tip:"CONTEST = CON + TEST（一起測試）",emoji:"🏅",roots:["con","test"]},
    {word:"continue",chinese:"繼續",sentence:"Please <strong>continue</strong> reading.",tip:"CONTINUE = CON + TINUE（保持不斷）",emoji:"▶️",roots:["con","tin","ue"]},
    {word:"contract",chinese:"合約/收縮",sentence:"We signed a <strong>contract</strong>.",tip:"CONTRACT = CON + TRACT（一起拉扯＝協議）",emoji:"📄",roots:["con","tract"]},
    {word:"contrast",chinese:"對比",sentence:"There is a big <strong>contrast</strong> between them.",tip:"CONTRAST = CONTRA + ST（反向站立）",emoji:"⬛",roots:["con","trast"]},
    {word:"contribute",chinese:"貢獻",sentence:"Everyone should <strong>contribute</strong> to the team.",tip:"CONTRIBUTE = CON + TRIBUTE（一起給予）",emoji:"🤲",roots:["con","trib","ute"]},
    {word:"control",chinese:"控制",sentence:"He can <strong>control</strong> the robot.",tip:"CONTROL = CON + TROL（按照名冊管理）",emoji:"🎮",roots:["con","trol"]},
    {word:"conversation",chinese:"對話",sentence:"We had a long <strong>conversation</strong>.",tip:"CONVERSATION = CON + VERS + ATION（一起轉話題）",emoji:"💬",roots:["con","ver","sa","tion"]},
    {word:"convince",chinese:"說服",sentence:"She <strong>convince</strong>d me to try it.",tip:"CONVINCE = CON + VINCE（完全征服）",emoji:"🗣️",roots:["con","vince"]},
    {word:"copy",chinese:"複製/副本",sentence:"Make a <strong>copy</strong> of the homework.",tip:"COPY 和 PUPPY 有類似結尾音",emoji:"📋",roots:["co","py"]},
    {word:"core",chinese:"核心",sentence:"Math is a <strong>core</strong> subject.",tip:"CORE 和 MORE 押韻",emoji:"🍎",roots:["core"]},
    {word:"corner",chinese:"角落",sentence:"The cat hid in the <strong>corner</strong>.",tip:"CORNER = CORN + ER（角的地方）",emoji:"📐",roots:["cor","ner"]},
    {word:"correct",chinese:"正確的/糾正",sentence:"Your answer is <strong>correct</strong>!",tip:"CORRECT = COR + RECT（一起使直＝正確）",emoji:"✅",roots:["cor","rect"]},
    {word:"council",chinese:"議會/委員會",sentence:"The city <strong>council</strong> held a meeting.",tip:"COUNCIL 和 COUNSEL 發音相同但意思不同",emoji:"🏛️",roots:["coun","cil"]},
    {word:"count",chinese:"計算/重要",sentence:"Can you <strong>count</strong> to one hundred?",tip:"COUNT 和 MOUNT 押韻",emoji:"🔢",roots:["count"]},
    {word:"courage",chinese:"勇氣",sentence:"It takes <strong>courage</strong> to speak up.",tip:"COURAGE = COUR（心）+ AGE",emoji:"🦁",roots:["cour","age"]},
    {word:"court",chinese:"法庭/球場",sentence:"The tennis <strong>court</strong> is over there.",tip:"COURT 和 SPORT 有類似結尾",emoji:"🎾",roots:["court"]},
    {word:"cover",chinese:"覆蓋/封面",sentence:"<strong>Cover</strong> your mouth when you cough.",tip:"COVER 和 DISCOVER 有關聯",emoji:"🫳",roots:["cov","er"]},
    {word:"crack",chinese:"裂縫/破裂",sentence:"There is a <strong>crack</strong> in the wall.",tip:"CRACK 和 BACK 押韻",emoji:"💔",roots:["crack"]},
    {word:"crash",chinese:"碰撞/墜毀",sentence:"The car <strong>crash</strong>ed into a tree.",tip:"CRASH 和 TRASH 押韻",emoji:"💥",roots:["crash"]},
    {word:"create",chinese:"創造",sentence:"Let's <strong>create</strong> something amazing!",tip:"CREATE = CRE + ATE（使成長出來）",emoji:"🎨",roots:["cre","ate"]},
    {word:"creature",chinese:"生物",sentence:"A whale is the largest <strong>creature</strong> on Earth.",tip:"CREATURE = CREATE + URE（被創造的東西）",emoji:"🐋",roots:["crea","ture"]},
    {word:"crew",chinese:"機組人員/團隊",sentence:"The ship's <strong>crew</strong> worked together.",tip:"CREW 和 NEW 押韻",emoji:"👷",roots:["crew"]},
    {word:"crime",chinese:"犯罪",sentence:"The detective solved the <strong>crime</strong>.",tip:"CRIME 和 TIME 押韻",emoji:"🔍",roots:["crime"]},
    {word:"critic",chinese:"評論家/批評者",sentence:"The movie <strong>critic</strong> gave it five stars.",tip:"CRITIC = CRIT + IC（判斷的人）",emoji:"📝",roots:["crit","ic"]},
    {word:"crop",chinese:"農作物",sentence:"The farmer grows many <strong>crop</strong>s.",tip:"CROP 和 DROP 押韻",emoji:"🌾",roots:["crop"]},
    {word:"cross",chinese:"穿越/十字",sentence:"Look both ways before you <strong>cross</strong> the street.",tip:"CROSS 有兩個 S",emoji:"🚶",roots:["cross"]},
    {word:"crowd",chinese:"人群",sentence:"A large <strong>crowd</strong> gathered at the park.",tip:"CROWD 和 LOUD 押韻",emoji:"👥",roots:["crowd"]},
    {word:"cruel",chinese:"殘忍的",sentence:"It's <strong>cruel</strong> to hurt animals.",tip:"CRUEL = CRU + EL（像十字架上受苦的）",emoji:"😢",roots:["cru","el"]},
    {word:"crush",chinese:"壓碎/迷戀",sentence:"Don't <strong>crush</strong> the flowers.",tip:"CRUSH 和 BRUSH 押韻",emoji:"💔",roots:["crush"]},
    {word:"culture",chinese:"文化",sentence:"Every country has its own <strong>culture</strong>.",tip:"CULTURE = CULT + URE（培養出來的）",emoji:"🌍",roots:["cul","ture"]},
    {word:"cure",chinese:"治療/治癒",sentence:"Scientists are working to find a <strong>cure</strong>.",tip:"CURE 和 PURE 押韻",emoji:"💊",roots:["cure"]},
    {word:"curious",chinese:"好奇的",sentence:"The <strong>curious</strong> cat explored the garden.",tip:"CURIOUS = CUR + I + OUS（想要照顧了解的）",emoji:"🔍",roots:["cur","i","ous"]},
    {word:"current",chinese:"目前的/水流",sentence:"The <strong>current</strong> situation is good.",tip:"CURRENT = CUR + RENT（正在跑的）",emoji:"🌊",roots:["cur","rent"]},
    {word:"curve",chinese:"曲線/彎曲",sentence:"The road has a sharp <strong>curve</strong>.",tip:"CURVE 和 SERVE 押韻",emoji:"〰️",roots:["curve"]},
    {word:"custom",chinese:"習俗/自訂的",sentence:"It is a <strong>custom</strong> to eat cake on birthdays.",tip:"CUSTOM = CUST + OM（習慣的做法）",emoji:"🎂",roots:["cus","tom"]},
    {word:"cycle",chinese:"循環/腳踏車",sentence:"The water <strong>cycle</strong> starts with evaporation.",tip:"CYCLE = CYC + LE（圓圈轉動）",emoji:"🔄",roots:["cy","cle"]},
    {word:"damage",chinese:"損害",sentence:"The storm caused a lot of <strong>damage</strong>.",tip:"DAMAGE = DAM + AGE（損壞的程度）",emoji:"🌪️",roots:["dam","age"]},
    {word:"dare",chinese:"敢/膽敢",sentence:"I <strong>dare</strong> you to jump!",tip:"DARE 和 CARE 押韻",emoji:"😎",roots:["dare"]},
    {word:"data",chinese:"數據/資料",sentence:"We collected <strong>data</strong> for our project.",tip:"DATA 是 DATUM 的複數",emoji:"📊",roots:["da","ta"]},
    {word:"debate",chinese:"辯論",sentence:"The students had a <strong>debate</strong> about homework.",tip:"DEBATE = DE + BATE（打來打去討論）",emoji:"🗣️",roots:["de","bate"]},
    {word:"debt",chinese:"債務",sentence:"He paid off all his <strong>debt</strong>.",tip:"DEBT 的 B 不發音",emoji:"💸",roots:["debt"]},
    {word:"decent",chinese:"體面的/不錯的",sentence:"She wore a <strong>decent</strong> dress to the party.",tip:"DECENT = DEC + ENT（合適得體的）",emoji:"👔",roots:["de","cent"]},
    {word:"declare",chinese:"宣布/聲明",sentence:"The mayor <strong>declare</strong>d a holiday.",tip:"DECLARE = DE + CLARE（使清楚明白）",emoji:"📢",roots:["de","clare"]},
    {word:"decline",chinese:"下降/拒絕",sentence:"Sales <strong>decline</strong>d this month.",tip:"DECLINE = DE + CLINE（向下傾斜）",emoji:"📉",roots:["de","cline"]},
    {word:"decorate",chinese:"裝飾",sentence:"Let's <strong>decorate</strong> the room for Christmas!",tip:"DECORATE = DECOR + ATE（使美麗）",emoji:"🎄",roots:["dec","o","rate"]},
    {word:"decrease",chinese:"減少",sentence:"The temperature will <strong>decrease</strong> tonight.",tip:"DECREASE = DE + CREASE（向下成長＝減少）",emoji:"⬇️",roots:["de","crease"]},
    {word:"defeat",chinese:"打敗",sentence:"We <strong>defeat</strong>ed the other team.",tip:"DEFEAT = DE + FEAT（取消成就）",emoji:"🏆",roots:["de","feat"]},
    {word:"defend",chinese:"防禦/辯護",sentence:"The goalkeeper must <strong>defend</strong> the goal.",tip:"DEFEND = DE + FEND（擋開攻擊）",emoji:"🛡️",roots:["de","fend"]},
    {word:"define",chinese:"定義",sentence:"Can you <strong>define</strong> this word?",tip:"DEFINE = DE + FINE（劃出界線）",emoji:"📖",roots:["de","fine"]},
    {word:"definite",chinese:"確定的/明確的",sentence:"We need a <strong>definite</strong> answer.",tip:"DEFINITE = DE + FIN + ITE（有明確邊界的）",emoji:"✅",roots:["def","i","nite"]},
    {word:"degree",chinese:"程度/學位/度",sentence:"It's 30 <strong>degree</strong>s today.",tip:"DEGREE = DE + GREE（向下的級別）",emoji:"🌡️",roots:["de","gree"]},
    {word:"delay",chinese:"延遲",sentence:"The flight was <strong>delay</strong>ed by an hour.",tip:"DELAY = DE + LAY（放下來等一等）",emoji:"⏰",roots:["de","lay"]},
    {word:"deliberate",chinese:"故意的/深思熟慮的",sentence:"It was a <strong>deliberate</strong> choice.",tip:"DELIBERATE = DE + LIBER + ATE（仔細稱量的）",emoji:"🤔",roots:["de","lib","er","ate"]},
    {word:"delicate",chinese:"精緻的/脆弱的",sentence:"The flower is very <strong>delicate</strong>.",tip:"DELICATE = DELIC + ATE（令人愉悅但易碎的）",emoji:"🌸",roots:["del","i","cate"]},
    {word:"deliver",chinese:"遞送",sentence:"The mailman <strong>deliver</strong>s packages.",tip:"DELIVER = DE + LIVER（從...釋放出來）",emoji:"📦",roots:["de","liv","er"]},
    {word:"demand",chinese:"要求/需求",sentence:"The <strong>demand</strong> for water is high in summer.",tip:"DEMAND = DE + MAND（完全交到手中）",emoji:"📣",roots:["de","mand"]},
    {word:"demonstrate",chinese:"展示/示範",sentence:"Let me <strong>demonstrate</strong> how it works.",tip:"DEMONSTRATE = DE + MONSTR + ATE（指出來給人看）",emoji:"🎬",roots:["dem","on","strate"]},
    {word:"deny",chinese:"否認",sentence:"He <strong>denied</strong> eating the cookie.",tip:"DENY = DE + NY（說不是）",emoji:"🙅",roots:["de","ny"]},
    {word:"depend",chinese:"依賴/取決於",sentence:"The answer <strong>depend</strong>s on you.",tip:"DEPEND = DE + PEND（掛在...上面）",emoji:"🔗",roots:["de","pend"]},
    {word:"deposit",chinese:"存款/押金",sentence:"I made a <strong>deposit</strong> at the bank.",tip:"DEPOSIT = DE + POSIT（放下來）",emoji:"🏦",roots:["de","pos","it"]},
    {word:"depress",chinese:"使沮喪/壓低",sentence:"The rainy weather <strong>depress</strong>ed him.",tip:"DEPRESS = DE + PRESS（壓下去）",emoji:"😔",roots:["de","press"]},
    {word:"derive",chinese:"源自/得出",sentence:"This word is <strong>derive</strong>d from Latin.",tip:"DERIVE = DE + RIVE（從河流中引出）",emoji:"🌊",roots:["de","rive"]},
    {word:"describe",chinese:"描述",sentence:"<strong>Describe</strong> what you see in the picture.",tip:"DESCRIBE = DE + SCRIBE（寫下來）",emoji:"✍️",roots:["de","scribe"]},
    {word:"desert",chinese:"沙漠/拋棄",sentence:"The <strong>desert</strong> is hot and dry.",tip:"DESERT（沙漠重音在前）vs DESSERT（甜點兩個S）",emoji:"🏜️",roots:["des","ert"]},
    {word:"deserve",chinese:"值得",sentence:"You <strong>deserve</strong> a reward for your hard work.",tip:"DESERVE = DE + SERVE（服務得來的回報）",emoji:"🌟",roots:["de","serve"]},
    {word:"design",chinese:"設計",sentence:"She likes to <strong>design</strong> clothes.",tip:"DESIGN = DE + SIGN（畫出記號）",emoji:"🎨",roots:["de","sign"]},
    {word:"desire",chinese:"渴望/慾望",sentence:"His <strong>desire</strong> is to travel the world.",tip:"DESIRE = DE + SIRE（從星星上渴求）",emoji:"⭐",roots:["de","sire"]},
    {word:"desperate",chinese:"絕望的/拼命的",sentence:"The lost hiker felt <strong>desperate</strong>.",tip:"DESPERATE = DE + SPER + ATE（失去希望的）",emoji:"😱",roots:["des","per","ate"]},
    {word:"destroy",chinese:"摧毀",sentence:"The earthquake <strong>destroy</strong>ed many buildings.",tip:"DESTROY = DE + STROY（拆掉建造的）",emoji:"💥",roots:["de","stroy"]},
    {word:"detail",chinese:"細節",sentence:"Pay attention to every <strong>detail</strong>.",tip:"DETAIL = DE + TAIL（切到最小片）",emoji:"🔍",roots:["de","tail"]},
    {word:"detect",chinese:"偵測/發現",sentence:"Dogs can <strong>detect</strong> hidden objects.",tip:"DETECT = DE + TECT（揭開蓋子）",emoji:"🔎",roots:["de","tect"]},
    {word:"determine",chinese:"決定/確定",sentence:"Hard work will <strong>determine</strong> your success.",tip:"DETERMINE = DE + TERMINE（設定界限）",emoji:"🎯",roots:["de","ter","mine"]},
    {word:"develop",chinese:"發展/開發",sentence:"We need to <strong>develop</strong> new ideas.",tip:"DEVELOP = DE + VELOP（展開）",emoji:"🌱",roots:["de","vel","op"]},
    {word:"device",chinese:"裝置/設備",sentence:"A smartphone is a useful <strong>device</strong>.",tip:"DEVICE（名詞）和 DEVISE（動詞）不同",emoji:"📱",roots:["de","vice"]},
    {word:"devote",chinese:"奉獻/致力於",sentence:"She <strong>devote</strong>s time to helping others.",tip:"DEVOTE = DE + VOTE（鄭重發誓投入）",emoji:"❤️",roots:["de","vote"]},
    {word:"dial",chinese:"撥號/錶盤",sentence:"<strong>Dial</strong> 911 in an emergency.",tip:"DIAL 和 TRIAL 有相同結尾",emoji:"📞",roots:["di","al"]},
    {word:"diamond",chinese:"鑽石",sentence:"A <strong>diamond</strong> is very hard.",tip:"DIAMOND = DIA + MOND（閃亮的石頭）",emoji:"💎",roots:["dia","mond"]},
    {word:"dig",chinese:"挖",sentence:"The dog likes to <strong>dig</strong> in the garden.",tip:"DIG 和 BIG 押韻",emoji:"🕳️",roots:["dig"]},
    {word:"digital",chinese:"數位的",sentence:"We live in a <strong>digital</strong> world.",tip:"DIGITAL = DIGIT + AL（手指計算的）",emoji:"💻",roots:["dig","i","tal"]},
    {word:"direct",chinese:"直接的/指導",sentence:"Follow the <strong>direct</strong> path to school.",tip:"DIRECT = DI + RECT（使直的）",emoji:"➡️",roots:["di","rect"]},
    {word:"disappear",chinese:"消失",sentence:"The magician made the rabbit <strong>disappear</strong>.",tip:"DISAPPEAR = DIS + APPEAR（不出現了）",emoji:"🪄",roots:["dis","ap","pear"]},
    {word:"disappoint",chinese:"使失望",sentence:"Don't <strong>disappoint</strong> your parents.",tip:"DISAPPOINT = DIS + APPOINT（取消指定的期望）",emoji:"😞",roots:["dis","ap","point"]},
    {word:"discipline",chinese:"紀律/學科",sentence:"Good <strong>discipline</strong> helps you succeed.",tip:"DISCIPLINE = DISC + I + PLINE（學習的過程）",emoji:"📏",roots:["dis","ci","pline"]},
    {word:"discount",chinese:"折扣",sentence:"The store gives a 20% <strong>discount</strong>.",tip:"DISCOUNT = DIS + COUNT（扣掉一些不算）",emoji:"🏷️",roots:["dis","count"]},
    {word:"discover",chinese:"發現",sentence:"Columbus <strong>discover</strong>ed America.",tip:"DISCOVER = DIS + COVER（揭開覆蓋物）",emoji:"🔭",roots:["dis","cov","er"]},
    {word:"discuss",chinese:"討論",sentence:"Let's <strong>discuss</strong> the plan together.",tip:"DISCUSS = DIS + CUSS（分開來講）",emoji:"💬",roots:["dis","cuss"]},
    {word:"disease",chinese:"疾病",sentence:"Washing hands prevents <strong>disease</strong>.",tip:"DISEASE = DIS + EASE（不舒服）",emoji:"🤒",roots:["dis","ease"]},
    {word:"disguise",chinese:"偽裝",sentence:"The spy wore a <strong>disguise</strong>.",tip:"DISGUISE = DIS + GUISE（改變外表）",emoji:"🥸",roots:["dis","guise"]},
    {word:"dish",chinese:"盤子/菜餚",sentence:"This <strong>dish</strong> is my favorite.",tip:"DISH 和 FISH 押韻",emoji:"🍽️",roots:["dish"]},
    {word:"dismiss",chinese:"解散/忽略",sentence:"The teacher <strong>dismiss</strong>ed the class.",tip:"DISMISS = DIS + MISS（送走）",emoji:"👋",roots:["dis","miss"]},
    {word:"display",chinese:"展示/顯示",sentence:"The museum <strong>display</strong>s ancient art.",tip:"DISPLAY = DIS + PLAY（展開來看）",emoji:"🖼️",roots:["dis","play"]},
    {word:"distance",chinese:"距離",sentence:"The <strong>distance</strong> between the two cities is 100 km.",tip:"DISTANCE = DIS + TANCE（站開的程度）",emoji:"📏",roots:["dis","tance"]},
    {word:"distinguish",chinese:"區分/辨別",sentence:"Can you <strong>distinguish</strong> between the twins?",tip:"DISTINGUISH = DIS + TINGUISH（分開標記）",emoji:"🔍",roots:["dis","tin","guish"]},
    {word:"distribute",chinese:"分配/分發",sentence:"We <strong>distribute</strong>d flyers to everyone.",tip:"DISTRIBUTE = DIS + TRIBUTE（分開給予）",emoji:"📤",roots:["dis","trib","ute"]},
    {word:"district",chinese:"區域/地區",sentence:"I live in the east <strong>district</strong>.",tip:"DISTRICT = DIS + TRICT（分開的地方）",emoji:"🗺️",roots:["dis","trict"]},
    {word:"disturb",chinese:"打擾/干擾",sentence:"Please don't <strong>disturb</strong> me while I study.",tip:"DISTURB = DIS + TURB（使不安寧）",emoji:"🤫",roots:["dis","turb"]},
    {word:"divide",chinese:"分開/除以",sentence:"<strong>Divide</strong> the pizza into eight slices.",tip:"DIVIDE = DI + VIDE（分成兩半看）",emoji:"✂️",roots:["di","vide"]},
    {word:"document",chinese:"文件/記錄",sentence:"Save the <strong>document</strong> on the computer.",tip:"DOCUMENT = DOC + U + MENT（教導的記錄）",emoji:"📄",roots:["doc","u","ment"]},
    {word:"domestic",chinese:"國內的/家庭的",sentence:"A cat is a <strong>domestic</strong> animal.",tip:"DOMESTIC = DOMEST + IC（家裡的）",emoji:"🏠",roots:["do","mes","tic"]},
    {word:"dominate",chinese:"主導/支配",sentence:"The tall player <strong>dominate</strong>d the game.",tip:"DOMINATE = DOMIN + ATE（當主人）",emoji:"👑",roots:["dom","i","nate"]},
    {word:"donate",chinese:"捐贈",sentence:"We <strong>donate</strong>d books to the library.",tip:"DONATE = DON + ATE（給予禮物）",emoji:"🎁",roots:["do","nate"]},
    {word:"doubt",chinese:"懷疑",sentence:"I have no <strong>doubt</strong> you will win.",tip:"DOUBT 的 B 不發音",emoji:"🤨",roots:["doubt"]},
    {word:"draft",chinese:"草稿/草案",sentence:"Write a rough <strong>draft</strong> first.",tip:"DRAFT 和 CRAFT 押韻",emoji:"📝",roots:["draft"]},
    {word:"drag",chinese:"拖/拉",sentence:"The child <strong>drag</strong>ged the toy behind her.",tip:"DRAG 和 BAG 押韻",emoji:"🧲",roots:["drag"]},
    {word:"drama",chinese:"戲劇",sentence:"We watched a <strong>drama</strong> at the theater.",tip:"DRAMA 有兩個 A",emoji:"🎭",roots:["dra","ma"]},
    {word:"drastic",chinese:"劇烈的/激烈的",sentence:"We need to take <strong>drastic</strong> action.",tip:"DRASTIC = DRAST + IC（做出來的激烈改變）",emoji:"⚡",roots:["dras","tic"]},
    {word:"drift",chinese:"漂流/漂移",sentence:"The boat <strong>drift</strong>ed down the river.",tip:"DRIFT 和 GIFT 押韻",emoji:"🚣",roots:["drift"]},
    {word:"drill",chinese:"鑽孔/操練",sentence:"The dentist used a <strong>drill</strong>.",tip:"DRILL 有兩個 L",emoji:"🔩",roots:["drill"]},
    {word:"drop",chinese:"掉落/滴",sentence:"Don't <strong>drop</strong> the glass!",tip:"DROP 和 STOP 押韻",emoji:"💧",roots:["drop"]},
    {word:"drug",chinese:"藥物/毒品",sentence:"The doctor prescribed a new <strong>drug</strong>.",tip:"DRUG 和 BUG 押韻",emoji:"💊",roots:["drug"]},
    {word:"due",chinese:"到期的/應付的",sentence:"The homework is <strong>due</strong> tomorrow.",tip:"DUE 和 DO 發音一樣",emoji:"📅",roots:["due"]},
    {word:"dump",chinese:"傾倒/垃圾場",sentence:"Don't <strong>dump</strong> trash on the ground.",tip:"DUMP 和 JUMP 押韻",emoji:"🗑️",roots:["dump"]},
    {word:"dust",chinese:"灰塵",sentence:"There is <strong>dust</strong> on the shelf.",tip:"DUST 和 MUST 押韻",emoji:"🧹",roots:["dust"]},
    {word:"duty",chinese:"責任/義務",sentence:"It is my <strong>duty</strong> to help my family.",tip:"DUTY = DU + TY（欠的東西）",emoji:"⚖️",roots:["du","ty"]},
    {word:"eager",chinese:"渴望的/急切的",sentence:"She is <strong>eager</strong> to learn new things.",tip:"EAGER 和 BEAVER 有關（eager beaver＝勤勞的人）",emoji:"🙋",roots:["ea","ger"]},
    {word:"earn",chinese:"賺取",sentence:"She <strong>earn</strong>s money by selling lemonade.",tip:"EARN 和 LEARN 押韻",emoji:"💵",roots:["earn"]},
    {word:"ease",chinese:"容易/放鬆",sentence:"He solved the puzzle with <strong>ease</strong>.",tip:"EASE 和 PLEASE 有相同結尾",emoji:"😌",roots:["ease"]},
    {word:"edge",chinese:"邊緣",sentence:"Don't sit on the <strong>edge</strong> of the table.",tip:"EDGE 和 HEDGE 押韻",emoji:"📐",roots:["edge"]},
    {word:"educate",chinese:"教育",sentence:"Teachers <strong>educate</strong> children.",tip:"EDUCATE = E + DUC + ATE（引導出來）",emoji:"🎓",roots:["ed","u","cate"]},
    {word:"effect",chinese:"效果/影響",sentence:"The medicine had a positive <strong>effect</strong>.",tip:"EFFECT（名詞效果）vs AFFECT（動詞影響）",emoji:"💫",roots:["ef","fect"]},
    {word:"effort",chinese:"努力",sentence:"Put more <strong>effort</strong> into your work.",tip:"EFFORT = EF + FORT（用力把東西拿出來）",emoji:"💪",roots:["ef","fort"]},
    {word:"elder",chinese:"年長的/長輩",sentence:"Respect your <strong>elder</strong>s.",tip:"ELDER 是 OLD 的比較級形式",emoji:"👴",roots:["eld","er"]},
    {word:"elect",chinese:"選舉",sentence:"We <strong>elect</strong> a class president every year.",tip:"ELECT = E + LECT（選出來）",emoji:"🗳️",roots:["e","lect"]},
    {word:"element",chinese:"元素/要素",sentence:"Water is made of two <strong>element</strong>s.",tip:"ELEMENT = ELE + MENT（基本的東西）",emoji:"⚗️",roots:["el","e","ment"]},
    {word:"eliminate",chinese:"消除/淘汰",sentence:"We must <strong>eliminate</strong> all errors.",tip:"ELIMINATE = E + LIMIN + ATE（趕出門檻外）",emoji:"❌",roots:["e","lim","i","nate"]},
    {word:"emerge",chinese:"出現/浮現",sentence:"The butterfly <strong>emerge</strong>d from the cocoon.",tip:"EMERGE = E + MERGE（從裡面冒出來）",emoji:"🦋",roots:["e","merge"]},
    {word:"emotion",chinese:"情緒/感情",sentence:"Music can express strong <strong>emotion</strong>.",tip:"EMOTION = E + MOTION（從內心動出來的）",emoji:"😢",roots:["e","mo","tion"]},
    {word:"emphasize",chinese:"強調",sentence:"I want to <strong>emphasize</strong> the importance of sleep.",tip:"EMPHASIZE = EM + PHAS + IZE（放進去顯示）",emoji:"❗",roots:["em","pha","size"]},
    {word:"employ",chinese:"雇用",sentence:"The company <strong>employ</strong>s 100 people.",tip:"EMPLOY = EM + PLOY（在裡面使用）",emoji:"👷",roots:["em","ploy"]},
    {word:"enable",chinese:"使能夠",sentence:"Practice <strong>enable</strong>s you to improve.",tip:"ENABLE = EN + ABLE（使有能力）",emoji:"🔓",roots:["en","able"]},
    {word:"encounter",chinese:"遇到/遭遇",sentence:"We <strong>encounter</strong>ed a deer in the forest.",tip:"ENCOUNTER = EN + COUNTER（面對面碰到）",emoji:"🦌",roots:["en","coun","ter"]},
    {word:"encourage",chinese:"鼓勵",sentence:"My parents <strong>encourage</strong> me to try new things.",tip:"ENCOURAGE = EN + COURAGE（給予勇氣）",emoji:"💪",roots:["en","cour","age"]},
    {word:"energy",chinese:"能量/精力",sentence:"Kids have a lot of <strong>energy</strong>.",tip:"ENERGY = EN + ERG + Y（裡面的工作力）",emoji:"⚡",roots:["en","er","gy"]},
    {word:"engage",chinese:"參與/訂婚",sentence:"The game <strong>engage</strong>s students in learning.",tip:"ENGAGE = EN + GAGE（投入承諾）",emoji:"🤝",roots:["en","gage"]},
    {word:"engine",chinese:"引擎/發動機",sentence:"The car <strong>engine</strong> makes a loud noise.",tip:"ENGINE = EN + GINE（裡面產生力量的）",emoji:"🚗",roots:["en","gine"]},
    {word:"enormous",chinese:"巨大的",sentence:"The elephant is <strong>enormous</strong>.",tip:"ENORMOUS = E + NORM + OUS（超出正常的）",emoji:"🐘",roots:["e","nor","mous"]},
    {word:"ensure",chinese:"確保",sentence:"Please <strong>ensure</strong> the door is locked.",tip:"ENSURE = EN + SURE（使確定）",emoji:"🔒",roots:["en","sure"]},
    {word:"enter",chinese:"進入",sentence:"Please <strong>enter</strong> the room quietly.",tip:"ENTER = EN + TER（進到裡面）",emoji:"🚪",roots:["en","ter"]},
    {word:"entire",chinese:"整個的",sentence:"I ate the <strong>entire</strong> cake!",tip:"ENTIRE = EN + TIRE（完整不碎的）",emoji:"🎂",roots:["en","tire"]},
    {word:"entry",chinese:"入口/條目",sentence:"The <strong>entry</strong> to the park is free.",tip:"ENTRY = ENTER 的名詞形式",emoji:"🚪",roots:["en","try"]},
    {word:"environment",chinese:"環境",sentence:"We must protect the <strong>environment</strong>.",tip:"ENVIRONMENT = EN + VIRON + MENT（圍繞我們的東西）",emoji:"🌍",roots:["en","vi","ron","ment"]},
    {word:"episode",chinese:"集/插曲",sentence:"I watched three <strong>episode</strong>s of my favorite show.",tip:"EPISODE = EPI + SODE（插入的事件）",emoji:"📺",roots:["ep","i","sode"]},
    {word:"equal",chinese:"相等的",sentence:"All students deserve <strong>equal</strong> treatment.",tip:"EQUAL = EQU + AL（平的一樣的）",emoji:"⚖️",roots:["e","qual"]},
    {word:"equip",chinese:"裝備",sentence:"The school <strong>equip</strong>ped us with laptops.",tip:"EQUIP = E + QUIP（配備好裝備）",emoji:"🎒",roots:["e","quip"]},
    {word:"escape",chinese:"逃跑/逃脫",sentence:"The cat <strong>escape</strong>d from the box.",tip:"ESCAPE = ES + CAPE（脫掉披風跑掉）",emoji:"🏃",roots:["es","cape"]},
    {word:"especially",chinese:"尤其/特別",sentence:"I love fruits, <strong>especially</strong> strawberries.",tip:"ESPECIALLY = ESPECIAL + LY",emoji:"⭐",roots:["es","pe","cial","ly"]},
    {word:"essential",chinese:"必要的/本質的",sentence:"Water is <strong>essential</strong> for life.",tip:"ESSENTIAL = ESSENT + IAL（存在必需的）",emoji:"💧",roots:["es","sen","tial"]},
    {word:"establish",chinese:"建立",sentence:"They <strong>establish</strong>ed a new school.",tip:"ESTABLISH = E + STAB + LISH（穩固地放置）",emoji:"🏛️",roots:["es","tab","lish"]},
    {word:"estate",chinese:"房地產/莊園",sentence:"The <strong>estate</strong> has a big garden.",tip:"ESTATE = E + STATE（有狀態的東西＝財產）",emoji:"🏘️",roots:["es","tate"]},
    {word:"estimate",chinese:"估計",sentence:"Can you <strong>estimate</strong> how many candies are in the jar?",tip:"ESTIMATE = ESTIM + ATE（評定價值）",emoji:"📊",roots:["es","ti","mate"]},
    {word:"evaluate",chinese:"評估",sentence:"The teacher will <strong>evaluate</strong> our projects.",tip:"EVALUATE = E + VALU + ATE（定出價值）",emoji:"📋",roots:["e","val","u","ate"]},
    {word:"evidence",chinese:"證據",sentence:"There is <strong>evidence</strong> that exercise is good for you.",tip:"EVIDENCE = EVI + DENCE（看得見的東西）",emoji:"🔎",roots:["ev","i","dence"]},
    {word:"evil",chinese:"邪惡的",sentence:"The villain in the story is <strong>evil</strong>.",tip:"EVIL 反過來是 LIVE（邪惡是活著的反面）",emoji:"😈",roots:["e","vil"]},
    {word:"evolve",chinese:"進化/演變",sentence:"Animals <strong>evolve</strong> over millions of years.",tip:"EVOLVE = E + VOLVE（向外展開變化）",emoji:"🧬",roots:["e","volve"]},
    {word:"exact",chinese:"確切的",sentence:"I need the <strong>exact</strong> answer.",tip:"EXACT = EX + ACT（做到精確）",emoji:"🎯",roots:["ex","act"]},
    {word:"examine",chinese:"檢查/考試",sentence:"The doctor will <strong>examine</strong> your eyes.",tip:"EXAMINE = EX + AMINE（仔細看出來）",emoji:"🔬",roots:["ex","am","ine"]},
    {word:"exceed",chinese:"超越",sentence:"Don't <strong>exceed</strong> the speed limit.",tip:"EXCEED = EX + CEED（走到外面去＝超過）",emoji:"🚀",roots:["ex","ceed"]},
    {word:"exchange",chinese:"交換",sentence:"Let's <strong>exchange</strong> gifts.",tip:"EXCHANGE = EX + CHANGE（互相改變）",emoji:"🔄",roots:["ex","change"]},
    {word:"excite",chinese:"使興奮",sentence:"The news <strong>excite</strong>d everyone.",tip:"EXCITE = EX + CITE（激動出來）",emoji:"🎉",roots:["ex","cite"]},
    {word:"exclude",chinese:"排除",sentence:"Don't <strong>exclude</strong> anyone from the game.",tip:"EXCLUDE = EX + CLUDE（關在外面）",emoji:"🚫",roots:["ex","clude"]},
    {word:"excuse",chinese:"藉口/原諒",sentence:"That is not a valid <strong>excuse</strong>.",tip:"EXCUSE = EX + CUSE（使脫離指控）",emoji:"🙄",roots:["ex","cuse"]},
    {word:"execute",chinese:"執行/處決",sentence:"We need to <strong>execute</strong> the plan.",tip:"EXECUTE = EX + ECUTE（從追逐中完成）",emoji:"⚡",roots:["ex","e","cute"]},
    {word:"exhibit",chinese:"展覽/展示",sentence:"The museum has a new dinosaur <strong>exhibit</strong>.",tip:"EXHIBIT = EX + HIBIT（拿出來展示）",emoji:"🦕",roots:["ex","hib","it"]},
    {word:"exist",chinese:"存在",sentence:"Dinosaurs no longer <strong>exist</strong>.",tip:"EXIST = EX + IST（站出來＝存在）",emoji:"🌍",roots:["ex","ist"]},
    {word:"expand",chinese:"擴展",sentence:"The city continues to <strong>expand</strong>.",tip:"EXPAND = EX + PAND（向外展開）",emoji:"📈",roots:["ex","pand"]},
    {word:"expect",chinese:"期望/預料",sentence:"I <strong>expect</strong> you to do your best.",tip:"EXPECT = EX + PECT（向外看＝期望）",emoji:"🤞",roots:["ex","pect"]},
    {word:"expense",chinese:"費用/開銷",sentence:"Food is a daily <strong>expense</strong>.",tip:"EXPENSE = EX + PENSE（花出去的錢）",emoji:"💸",roots:["ex","pense"]},
    {word:"experiment",chinese:"實驗",sentence:"We did a fun science <strong>experiment</strong>.",tip:"EXPERIMENT = EX + PERI + MENT（嘗試出來的）",emoji:"🧪",roots:["ex","per","i","ment"]},
    {word:"expert",chinese:"專家",sentence:"She is an <strong>expert</strong> in cooking.",tip:"EXPERT = EX + PERT（經驗豐富的人）",emoji:"🧑‍🔬",roots:["ex","pert"]},
    {word:"explain",chinese:"解釋",sentence:"Can you <strong>explain</strong> this to me?",tip:"EXPLAIN = EX + PLAIN（使平坦清楚）",emoji:"💡",roots:["ex","plain"]},
    {word:"explode",chinese:"爆炸",sentence:"The fireworks <strong>explode</strong>d in the sky.",tip:"EXPLODE = EX + PLODE（拍手趕出來＝爆）",emoji:"💥",roots:["ex","plode"]},
    {word:"explore",chinese:"探索",sentence:"Let's <strong>explore</strong> the forest!",tip:"EXPLORE = EX + PLORE（向外搜尋）",emoji:"🗺️",roots:["ex","plore"]},
    {word:"export",chinese:"出口/輸出",sentence:"Japan <strong>export</strong>s cars to many countries.",tip:"EXPORT = EX + PORT（從港口送出去）",emoji:"🚢",roots:["ex","port"]},
    {word:"expose",chinese:"暴露/揭露",sentence:"Don't <strong>expose</strong> your skin to too much sun.",tip:"EXPOSE = EX + POSE（放到外面）",emoji:"☀️",roots:["ex","pose"]},
    {word:"express",chinese:"表達/快速的",sentence:"She <strong>express</strong>ed her feelings clearly.",tip:"EXPRESS = EX + PRESS（壓出來＝表達）",emoji:"🗣️",roots:["ex","press"]},
    {word:"extend",chinese:"延伸/延長",sentence:"We <strong>extend</strong>ed the deadline by one week.",tip:"EXTEND = EX + TEND（往外伸展）",emoji:"📏",roots:["ex","tend"]},
    {word:"extent",chinese:"程度/範圍",sentence:"To what <strong>extent</strong> do you agree?",tip:"EXTENT = EX + TENT（伸展的程度）",emoji:"📊",roots:["ex","tent"]},
    {word:"external",chinese:"外部的",sentence:"The <strong>external</strong> walls are painted white.",tip:"EXTERNAL = EXTERN + AL（外面的）",emoji:"🔲",roots:["ex","ter","nal"]},
    {word:"extra",chinese:"額外的",sentence:"I need <strong>extra</strong> time to finish.",tip:"EXTRA 和 EXTRAORDINARY 同源",emoji:"➕",roots:["ex","tra"]},
    {word:"extreme",chinese:"極端的",sentence:"The weather is <strong>extreme</strong>ly hot today.",tip:"EXTREME = EX + TREME（在最外面的）",emoji:"🌡️",roots:["ex","treme"]},
    {word:"fade",chinese:"褪色/消退",sentence:"The color will <strong>fade</strong> in the sun.",tip:"FADE 和 MADE 押韻",emoji:"🌅",roots:["fade"]},
    {word:"fail",chinese:"失敗",sentence:"If you <strong>fail</strong>, try again.",tip:"FAIL 和 TAIL 押韻",emoji:"❌",roots:["fail"]},
    {word:"faith",chinese:"信仰/信念",sentence:"Have <strong>faith</strong> in yourself.",tip:"FAITH 裡有 AI（人工智慧也需要信念）",emoji:"🙏",roots:["faith"]},
    {word:"false",chinese:"假的/錯誤的",sentence:"The answer is <strong>false</strong>.",tip:"FALSE 和 TRUE 是相反詞",emoji:"❌",roots:["false"]},
    {word:"fame",chinese:"名聲",sentence:"The singer gained <strong>fame</strong> quickly.",tip:"FAME 和 GAME 押韻",emoji:"🌟",roots:["fame"]},
    {word:"fancy",chinese:"花俏的/想像",sentence:"She wore a <strong>fancy</strong> dress to the party.",tip:"FANCY = FAN + CY（幻想出來的美）",emoji:"👗",roots:["fan","cy"]},
    {word:"fare",chinese:"費用/車費",sentence:"The bus <strong>fare</strong> is two dollars.",tip:"FARE 和 CARE 押韻",emoji:"🎫",roots:["fare"]},
    {word:"fascinate",chinese:"迷住/使著迷",sentence:"Dinosaurs <strong>fascinate</strong> many children.",tip:"FASCINATE = FASCIN + ATE（像被施了魔法）",emoji:"🤩",roots:["fas","ci","nate"]},
    {word:"fate",chinese:"命運",sentence:"<strong>Fate</strong> brought them together.",tip:"FATE 和 LATE 押韻",emoji:"🔮",roots:["fate"]},
    {word:"fault",chinese:"錯誤/過失",sentence:"It's not your <strong>fault</strong>.",tip:"FAULT 的 L 不太發音",emoji:"⚠️",roots:["fault"]},
    {word:"favor",chinese:"幫忙/偏愛",sentence:"Can you do me a <strong>favor</strong>?",tip:"FAVOR = FAV + OR（偏向某一方）",emoji:"🙏",roots:["fa","vor"]},
    {word:"feature",chinese:"特徵/特色",sentence:"The phone has many useful <strong>feature</strong>s.",tip:"FEATURE = FEAT + URE（做出來的特點）",emoji:"✨",roots:["fea","ture"]},
    {word:"feed",chinese:"餵食",sentence:"Don't <strong>feed</strong> the animals at the zoo.",tip:"FEED 有兩個 E",emoji:"🍼",roots:["feed"]},
    {word:"fiction",chinese:"小說/虛構",sentence:"I love reading <strong>fiction</strong>.",tip:"FICTION = FICT + ION（編造出來的）",emoji:"📚",roots:["fic","tion"]},
    {word:"fierce",chinese:"兇猛的",sentence:"The <strong>fierce</strong> dragon breathed fire.",tip:"FIERCE 裡面有 FIRE 的感覺",emoji:"🐉",roots:["fierce"]},
    {word:"figure",chinese:"數字/人物/身材",sentence:"Draw a stick <strong>figure</strong>.",tip:"FIGURE = FIG + URE（形狀）",emoji:"🧍",roots:["fig","ure"]},
    {word:"file",chinese:"檔案/文件夾",sentence:"Save the <strong>file</strong> on your computer.",tip:"FILE 和 SMILE 有相同結尾",emoji:"📁",roots:["file"]},
    {word:"firm",chinese:"公司/堅定的",sentence:"She gave a <strong>firm</strong> handshake.",tip:"FIRM 和 CONFIRM 有相同字根",emoji:"🤝",roots:["firm"]},
    {word:"fit",chinese:"適合/健康的",sentence:"These shoes <strong>fit</strong> perfectly.",tip:"FIT 和 SIT 押韻",emoji:"👟",roots:["fit"]},
    {word:"fix",chinese:"修理/固定",sentence:"Dad can <strong>fix</strong> anything!",tip:"FIX 和 MIX 押韻",emoji:"🔧",roots:["fix"]},
    {word:"flame",chinese:"火焰",sentence:"The candle <strong>flame</strong> flickered.",tip:"FLAME 和 BLAME 押韻",emoji:"🔥",roots:["flame"]},
    {word:"flash",chinese:"閃光",sentence:"A <strong>flash</strong> of lightning lit the sky.",tip:"FLASH 和 CRASH 押韻",emoji:"⚡",roots:["flash"]},
    {word:"flat",chinese:"平坦的/公寓",sentence:"The road is very <strong>flat</strong>.",tip:"FLAT 和 CAT 押韻",emoji:"🏠",roots:["flat"]},
    {word:"flee",chinese:"逃跑",sentence:"The deer <strong>fled</strong> from the wolf.",tip:"FLEE 和 FREE 押韻",emoji:"🏃",roots:["flee"]},
    {word:"flexible",chinese:"靈活的/彈性的",sentence:"Be <strong>flexible</strong> with your plans.",tip:"FLEXIBLE = FLEX + IBLE（能彎曲的）",emoji:"🧘",roots:["flex","i","ble"]},
    {word:"float",chinese:"漂浮",sentence:"The duck <strong>float</strong>s on the pond.",tip:"FLOAT 和 BOAT 押韻",emoji:"🦆",roots:["float"]},
    {word:"flood",chinese:"洪水",sentence:"The heavy rain caused a <strong>flood</strong>.",tip:"FLOOD 雖然有 OO 但發短音",emoji:"🌊",roots:["flood"]},
    {word:"flow",chinese:"流動",sentence:"Water <strong>flow</strong>s downhill.",tip:"FLOW 和 GROW 押韻",emoji:"🌊",roots:["flow"]},
    {word:"focus",chinese:"焦點/專注",sentence:"<strong>Focus</strong> on your homework.",tip:"FOCUS = FOC + US（火的中心點）",emoji:"🔍",roots:["fo","cus"]},
    {word:"fold",chinese:"折疊",sentence:"<strong>Fold</strong> the paper in half.",tip:"FOLD 和 GOLD 押韻",emoji:"📃",roots:["fold"]},
    {word:"forbid",chinese:"禁止",sentence:"Smoking is <strong>forbid</strong>den here.",tip:"FORBID = FOR + BID（在前面阻止）",emoji:"🚫",roots:["for","bid"]},
    {word:"force",chinese:"力量/強迫",sentence:"The wind blew with great <strong>force</strong>.",tip:"FORCE 和 COURSE 有類似結尾",emoji:"💨",roots:["force"]},
    {word:"forecast",chinese:"預測/預報",sentence:"The weather <strong>forecast</strong> says it will rain.",tip:"FORECAST = FORE + CAST（向前投射）",emoji:"🌤️",roots:["fore","cast"]},
    {word:"forgive",chinese:"原諒",sentence:"I <strong>forgive</strong> you for being late.",tip:"FORGIVE = FOR + GIVE（給予寬恕）",emoji:"🕊️",roots:["for","give"]},
    {word:"formal",chinese:"正式的",sentence:"Wear <strong>formal</strong> clothes to the event.",tip:"FORMAL = FORM + AL（有形式的）",emoji:"👔",roots:["for","mal"]},
    {word:"former",chinese:"以前的/前者",sentence:"The <strong>former</strong> president visited our school.",tip:"FORMER = FORM + ER（之前形成的）",emoji:"⏮️",roots:["for","mer"]},
    {word:"formula",chinese:"公式/配方",sentence:"We learned a math <strong>formula</strong> today.",tip:"FORMULA = FORM + ULA（小小的形式）",emoji:"📐",roots:["for","mu","la"]},
    {word:"fortune",chinese:"財富/運氣",sentence:"She made a <strong>fortune</strong> selling toys.",tip:"FORTUNE = FORT + UNE（好運帶來的）",emoji:"💰",roots:["for","tune"]},
    {word:"fossil",chinese:"化石",sentence:"We found a <strong>fossil</strong> in the rock.",tip:"FOSSIL = FOSS + IL（挖出來的東西）",emoji:"🦴",roots:["fos","sil"]},
    {word:"foundation",chinese:"基礎/基金會",sentence:"Trust is the <strong>foundation</strong> of friendship.",tip:"FOUNDATION = FOUND + ATION（建立的基底）",emoji:"🧱",roots:["foun","da","tion"]},
    {word:"frame",chinese:"框架/相框",sentence:"Put the photo in a <strong>frame</strong>.",tip:"FRAME 和 GAME 押韻",emoji:"🖼️",roots:["frame"]},
    {word:"freeze",chinese:"結冰/凍結",sentence:"Water will <strong>freeze</strong> at zero degrees.",tip:"FREEZE 有兩個 E",emoji:"🧊",roots:["freeze"]},
    {word:"frequent",chinese:"頻繁的",sentence:"She is a <strong>frequent</strong> visitor to the library.",tip:"FREQUENT = FREQU + ENT（經常發生的）",emoji:"🔄",roots:["fre","quent"]},
    {word:"frighten",chinese:"使害怕",sentence:"The loud noise <strong>frighten</strong>ed the cat.",tip:"FRIGHTEN = FRIGHT + EN（使驚嚇）",emoji:"😱",roots:["fright","en"]},
    {word:"frost",chinese:"霜",sentence:"There was <strong>frost</strong> on the window this morning.",tip:"FROST 和 LOST 押韻",emoji:"❄️",roots:["frost"]},
    {word:"frustrate",chinese:"使沮喪",sentence:"Difficult homework can <strong>frustrate</strong> students.",tip:"FRUSTRATE = FRUSTR + ATE（白費力氣的感覺）",emoji:"😤",roots:["frus","trate"]},
    {word:"fuel",chinese:"燃料",sentence:"Cars need <strong>fuel</strong> to run.",tip:"FUEL = FU + EL（餵給火的東西）",emoji:"⛽",roots:["fu","el"]},
    {word:"fulfill",chinese:"實現/完成",sentence:"She <strong>fulfill</strong>ed her dream.",tip:"FULFILL = FUL + FILL（完全填滿）",emoji:"🎯",roots:["ful","fill"]},
    {word:"function",chinese:"功能/函數",sentence:"What is the <strong>function</strong> of this button?",tip:"FUNCTION = FUNCT + ION（執行的事）",emoji:"⚙️",roots:["func","tion"]},
    {word:"fund",chinese:"基金/資助",sentence:"They <strong>fund</strong>ed the science project.",tip:"FUND 和 FOUND 有關聯（基礎資金）",emoji:"💰",roots:["fund"]},
    {word:"fundamental",chinese:"基本的",sentence:"Reading is a <strong>fundamental</strong> skill.",tip:"FUNDAMENTAL = FUND + A + MENTAL（基礎的）",emoji:"🧱",roots:["fun","da","men","tal"]},
    {word:"furniture",chinese:"家具",sentence:"We bought new <strong>furniture</strong> for the house.",tip:"FURNITURE = FURN + ITURE（提供的東西）",emoji:"🛋️",roots:["fur","ni","ture"]},
    {word:"gain",chinese:"獲得/增加",sentence:"She <strong>gain</strong>ed confidence from practice.",tip:"GAIN 和 TRAIN 押韻",emoji:"📈",roots:["gain"]},
    {word:"gap",chinese:"間隙/差距",sentence:"There is a <strong>gap</strong> in the fence.",tip:"GAP 和 MAP 押韻",emoji:"🕳️",roots:["gap"]},
    {word:"gather",chinese:"聚集/收集",sentence:"We <strong>gather</strong>ed around the campfire.",tip:"GATHER = GATH + ER（在一起的人）",emoji:"👥",roots:["gath","er"]},
    {word:"gender",chinese:"性別",sentence:"People of all <strong>gender</strong>s are welcome.",tip:"GENDER = GEND + ER（種類）",emoji:"👫",roots:["gen","der"]},
    {word:"generate",chinese:"產生/發電",sentence:"The machine <strong>generate</strong>s electricity.",tip:"GENERATE = GENER + ATE（使產生）",emoji:"⚡",roots:["gen","er","ate"]},
    {word:"generous",chinese:"慷慨的",sentence:"She is very <strong>generous</strong> with her time.",tip:"GENEROUS = GENER + OUS（大量給予的）",emoji:"🎁",roots:["gen","er","ous"]},
    {word:"genius",chinese:"天才",sentence:"Einstein was a <strong>genius</strong>.",tip:"GENIUS = GEN + IUS（天生的才能）",emoji:"🧠",roots:["gen","ius"]},
    {word:"genuine",chinese:"真正的",sentence:"This is a <strong>genuine</strong> diamond.",tip:"GENUINE = GEN + U + INE（天生真實的）",emoji:"💎",roots:["gen","u","ine"]},
    {word:"giant",chinese:"巨人/巨大的",sentence:"The <strong>giant</strong> panda is very cute.",tip:"GIANT = GI + ANT（超大的螞蟻般）",emoji:"🐼",roots:["gi","ant"]},
    {word:"globe",chinese:"地球儀/全球",sentence:"We have a <strong>globe</strong> in our classroom.",tip:"GLOBE 和 ROBE 押韻",emoji:"🌍",roots:["globe"]},
    {word:"glory",chinese:"榮耀",sentence:"The team won <strong>glory</strong> for our school.",tip:"GLORY = GLOR + Y（光榮閃耀的）",emoji:"🏆",roots:["glo","ry"]},
    {word:"grab",chinese:"抓住",sentence:"<strong>Grab</strong> your coat — it's cold outside!",tip:"GRAB 和 CAB 押韻",emoji:"✊",roots:["grab"]},
    {word:"gradual",chinese:"漸進的",sentence:"The hill has a <strong>gradual</strong> slope.",tip:"GRADUAL = GRAD + UAL（一步一步的）",emoji:"📈",roots:["grad","u","al"]},
    {word:"grant",chinese:"授予/補助金",sentence:"The school <strong>grant</strong>ed her a scholarship.",tip:"GRANT 和 PLANT 押韻",emoji:"🎓",roots:["grant"]},
    {word:"grateful",chinese:"感恩的",sentence:"I am <strong>grateful</strong> for your help.",tip:"GRATEFUL = GRATE + FUL（充滿感謝）",emoji:"🙏",roots:["grate","ful"]},
    {word:"grave",chinese:"嚴重的/墳墓",sentence:"This is a <strong>grave</strong> situation.",tip:"GRAVE 和 BRAVE 押韻",emoji:"⚰️",roots:["grave"]},
    {word:"grip",chinese:"緊握",sentence:"<strong>Grip</strong> the handle tightly.",tip:"GRIP 和 TRIP 押韻",emoji:"✊",roots:["grip"]},
    {word:"grocery",chinese:"雜貨店",sentence:"Mom went to the <strong>grocery</strong> store.",tip:"GROCERY = GROCE + RY（批發的東西）",emoji:"🛒",roots:["gro","ce","ry"]},
    {word:"guarantee",chinese:"保證",sentence:"I <strong>guarantee</strong> you will love it!",tip:"GUARANTEE 有兩個 A 和兩個 E",emoji:"🤞",roots:["guar","an","tee"]},
    {word:"guard",chinese:"守衛/保護",sentence:"The dog <strong>guard</strong>s the house.",tip:"GUARD 的 U 不發音",emoji:"💂",roots:["guard"]},
    {word:"guide",chinese:"指導/導遊",sentence:"The tour <strong>guide</strong> showed us around.",tip:"GUIDE 的 U 不發音",emoji:"🗺️",roots:["guide"]},
    {word:"guilty",chinese:"有罪的/內疚的",sentence:"He felt <strong>guilty</strong> about lying.",tip:"GUILTY = GUILT + Y（有罪的感覺）",emoji:"😔",roots:["guilt","y"]},
    {word:"halt",chinese:"停止",sentence:"The car came to a <strong>halt</strong>.",tip:"HALT 和 SALT 押韻",emoji:"🛑",roots:["halt"]},
    {word:"handle",chinese:"把手/處理",sentence:"I can <strong>handle</strong> this problem.",tip:"HANDLE = HAND + LE（用手處理）",emoji:"🤲",roots:["hand","le"]},
    {word:"hang",chinese:"懸掛",sentence:"<strong>Hang</strong> your coat on the hook.",tip:"HANG 和 BANG 押韻",emoji:"🧥",roots:["hang"]},
    {word:"harbor",chinese:"港口",sentence:"The ships rest in the <strong>harbor</strong>.",tip:"HARBOR = HAR + BOR（軍隊的庇護所）",emoji:"⚓",roots:["har","bor"]},
    {word:"harm",chinese:"傷害",sentence:"Don't <strong>harm</strong> any animals.",tip:"HARM 和 FARM 押韻",emoji:"⚠️",roots:["harm"]},
    {word:"harmony",chinese:"和諧",sentence:"The choir sang in <strong>harmony</strong>.",tip:"HARMONY = HARMON + Y（配合在一起的）",emoji:"🎵",roots:["har","mo","ny"]},
    {word:"harsh",chinese:"嚴厲的/粗糙的",sentence:"The teacher's words were <strong>harsh</strong>.",tip:"HARSH 和 MARSH 押韻",emoji:"😠",roots:["harsh"]},
    {word:"harvest",chinese:"收穫",sentence:"Farmers <strong>harvest</strong> crops in autumn.",tip:"HARVEST = HARV + EST（秋天的收穫）",emoji:"🌾",roots:["har","vest"]},
    {word:"haunt",chinese:"困擾/鬧鬼",sentence:"The old house is said to be <strong>haunt</strong>ed.",tip:"HAUNT 和 WANT 有類似發音",emoji:"👻",roots:["haunt"]},
    {word:"heal",chinese:"治癒",sentence:"The wound will <strong>heal</strong> in a week.",tip:"HEAL 和 DEAL 押韻",emoji:"💚",roots:["heal"]},
    {word:"headline",chinese:"標題/頭條",sentence:"The <strong>headline</strong> caught my attention.",tip:"HEADLINE = HEAD + LINE（頭等的一行）",emoji:"📰",roots:["head","line"]},
    {word:"heap",chinese:"堆",sentence:"There is a <strong>heap</strong> of laundry to wash.",tip:"HEAP 和 CHEAP 押韻",emoji:"🗻",roots:["heap"]},
    {word:"heritage",chinese:"遺產/傳統",sentence:"We should protect our cultural <strong>heritage</strong>.",tip:"HERITAGE = HERIT + AGE（繼承下來的東西）",emoji:"🏛️",roots:["her","it","age"]},
    {word:"hero",chinese:"英雄",sentence:"The firefighter is a real <strong>hero</strong>.",tip:"HERO 和 ZERO 押韻",emoji:"🦸",roots:["he","ro"]},
    {word:"hesitate",chinese:"猶豫",sentence:"Don't <strong>hesitate</strong> to ask for help.",tip:"HESITATE = HESIT + ATE（卡住不動）",emoji:"🤔",roots:["hes","i","tate"]},
    {word:"hide",chinese:"躲藏/隱藏",sentence:"The cat likes to <strong>hide</strong> under the bed.",tip:"HIDE 和 RIDE 押韻",emoji:"🙈",roots:["hide"]},
    {word:"highlight",chinese:"強調/亮點",sentence:"The <strong>highlight</strong> of the trip was the beach.",tip:"HIGHLIGHT = HIGH + LIGHT（高亮的部分）",emoji:"🌟",roots:["high","light"]},
    {word:"hint",chinese:"提示/暗示",sentence:"Can you give me a <strong>hint</strong>?",tip:"HINT 和 PRINT 有相同結尾",emoji:"💡",roots:["hint"]},
    {word:"hire",chinese:"雇用",sentence:"The company will <strong>hire</strong> new workers.",tip:"HIRE 和 FIRE 押韻",emoji:"💼",roots:["hire"]},
    {word:"hollow",chinese:"空心的/中空的",sentence:"The tree trunk is <strong>hollow</strong>.",tip:"HOLLOW 有兩個 L（像中間挖空了）",emoji:"🌳",roots:["hol","low"]},
    {word:"honor",chinese:"榮譽/尊敬",sentence:"It's an <strong>honor</strong> to meet you.",tip:"HONOR 的 H 不發音",emoji:"🎖️",roots:["hon","or"]},
    {word:"hook",chinese:"鉤子",sentence:"Hang your bag on the <strong>hook</strong>.",tip:"HOOK 和 BOOK 押韻",emoji:"🪝",roots:["hook"]},
    {word:"horizon",chinese:"地平線",sentence:"The sun set below the <strong>horizon</strong>.",tip:"HORIZON = HORI + ZON（界線的區域）",emoji:"🌅",roots:["ho","ri","zon"]},
    {word:"horror",chinese:"恐怖",sentence:"I don't like <strong>horror</strong> movies.",tip:"HORROR 有兩個 R",emoji:"😱",roots:["hor","ror"]},
    {word:"host",chinese:"主人/主持",sentence:"She was the <strong>host</strong> of the party.",tip:"HOST 和 MOST 押韻",emoji:"🎤",roots:["host"]},
    {word:"household",chinese:"家庭/家用的",sentence:"We share <strong>household</strong> chores.",tip:"HOUSEHOLD = HOUSE + HOLD（持有的家）",emoji:"🏠",roots:["house","hold"]},
    {word:"humble",chinese:"謙虛的",sentence:"Stay <strong>humble</strong> even when you succeed.",tip:"HUMBLE = HUMB + LE（低下的）",emoji:"🙇",roots:["hum","ble"]},
    {word:"humor",chinese:"幽默",sentence:"He has a great sense of <strong>humor</strong>.",tip:"HUMOR 和 RUMOR 有相同結尾",emoji:"😂",roots:["hu","mor"]},
    {word:"hunger",chinese:"飢餓",sentence:"<strong>Hunger</strong> is a big problem in some countries.",tip:"HUNGER = HUNG + ER（餓的狀態）",emoji:"🍽️",roots:["hun","ger"]},
    {word:"hunt",chinese:"打獵/搜尋",sentence:"The owl <strong>hunt</strong>s at night.",tip:"HUNT 和 FRONT 有相同結尾",emoji:"🦉",roots:["hunt"]},
    {word:"ignore",chinese:"忽略",sentence:"Don't <strong>ignore</strong> your teacher's advice.",tip:"IGNORE = IG + NORE（不去知道）",emoji:"🙈",roots:["ig","nore"]},
    {word:"illustrate",chinese:"說明/畫插圖",sentence:"Let me <strong>illustrate</strong> with a picture.",tip:"ILLUSTRATE = IL + LUSTR + ATE（照亮說明）",emoji:"🎨",roots:["il","lus","trate"]},
    {word:"imagine",chinese:"想像",sentence:"<strong>Imagine</strong> you can fly!",tip:"IMAGINE = IMAG + INE（在心中成像）",emoji:"💭",roots:["i","mag","ine"]},
    {word:"immediate",chinese:"立即的",sentence:"We need an <strong>immediate</strong> response.",tip:"IMMEDIATE = IM + MEDI + ATE（沒有中間的）",emoji:"⚡",roots:["im","me","di","ate"]},
    {word:"impact",chinese:"影響/衝擊",sentence:"The book had a big <strong>impact</strong> on me.",tip:"IMPACT = IM + PACT（撞進去的力）",emoji:"💥",roots:["im","pact"]},
    {word:"import",chinese:"進口/重要性",sentence:"We <strong>import</strong> fruits from other countries.",tip:"IMPORT = IM + PORT（從港口帶進來）",emoji:"📥",roots:["im","port"]},
    {word:"impose",chinese:"強加/施加",sentence:"Don't <strong>impose</strong> your ideas on others.",tip:"IMPOSE = IM + POSE（放到上面）",emoji:"⚠️",roots:["im","pose"]},
    {word:"impress",chinese:"留下深刻印象",sentence:"Her singing <strong>impress</strong>ed the judges.",tip:"IMPRESS = IM + PRESS（壓進心裡）",emoji:"😲",roots:["im","press"]},
    {word:"improve",chinese:"改善/進步",sentence:"Practice will <strong>improve</strong> your skills.",tip:"IMPROVE = IM + PROVE（使變得更好）",emoji:"📈",roots:["im","prove"]},
    {word:"include",chinese:"包含",sentence:"The price <strong>include</strong>s delivery.",tip:"INCLUDE = IN + CLUDE（關在裡面）",emoji:"📦",roots:["in","clude"]},
    {word:"income",chinese:"收入",sentence:"Her <strong>income</strong> comes from teaching.",tip:"INCOME = IN + COME（進來的錢）",emoji:"💵",roots:["in","come"]},
    {word:"indicate",chinese:"指出/顯示",sentence:"The arrow <strong>indicate</strong>s the direction.",tip:"INDICATE = IN + DIC + ATE（說出來指向）",emoji:"👉",roots:["in","di","cate"]},
    {word:"individual",chinese:"個人/個別的",sentence:"Every <strong>individual</strong> is unique.",tip:"INDIVIDUAL = IN + DIVID + UAL（不可分割的）",emoji:"🧍",roots:["in","di","vid","u","al"]},
    {word:"influence",chinese:"影響/影響力",sentence:"Friends <strong>influence</strong> our choices.",tip:"INFLUENCE = IN + FLU + ENCE（流進去的力量）",emoji:"🌊",roots:["in","flu","ence"]},
    {word:"inform",chinese:"通知/告知",sentence:"Please <strong>inform</strong> me of any changes.",tip:"INFORM = IN + FORM（把形式放進去＝告知）",emoji:"📢",roots:["in","form"]},
    {word:"initial",chinese:"最初的/首字母",sentence:"What is your <strong>initial</strong> impression?",tip:"INITIAL = INIT + IAL（開始的）",emoji:"🔤",roots:["in","i","tial"]},
    {word:"injure",chinese:"傷害/受傷",sentence:"He <strong>injure</strong>d his knee playing soccer.",tip:"INJURE = IN + JURE（不正義＝傷害）",emoji:"🩹",roots:["in","jure"]},
    {word:"innocent",chinese:"無辜的/天真的",sentence:"The child has an <strong>innocent</strong> smile.",tip:"INNOCENT = IN + NOC + ENT（不傷害的）",emoji:"😇",roots:["in","no","cent"]},
    {word:"inspire",chinese:"啟發/激勵",sentence:"Great leaders <strong>inspire</strong> people.",tip:"INSPIRE = IN + SPIRE（吹入靈感）",emoji:"💡",roots:["in","spire"]},
    {word:"install",chinese:"安裝",sentence:"Dad <strong>install</strong>ed a new shelf.",tip:"INSTALL = IN + STALL（放到位子上）",emoji:"🔧",roots:["in","stall"]},
    {word:"instance",chinese:"例子/實例",sentence:"For <strong>instance</strong>, cats can swim.",tip:"INSTANCE = IN + STANCE（站在裡面的例子）",emoji:"📌",roots:["in","stance"]},
    {word:"instant",chinese:"立即的/瞬間",sentence:"I want <strong>instant</strong> noodles!",tip:"INSTANT = IN + STANT（站在裡面不動＝當下）",emoji:"⚡",roots:["in","stant"]},
    {word:"instinct",chinese:"本能/直覺",sentence:"Animals act on <strong>instinct</strong>.",tip:"INSTINCT = IN + STINCT（內在的刺激）",emoji:"🐾",roots:["in","stinct"]},
    {word:"institution",chinese:"機構/制度",sentence:"A school is an educational <strong>institution</strong>.",tip:"INSTITUTION = IN + STITUT + ION（設立的東西）",emoji:"🏫",roots:["in","sti","tu","tion"]},
    {word:"instruct",chinese:"指導/教導",sentence:"The coach <strong>instruct</strong>ed the players.",tip:"INSTRUCT = IN + STRUCT（在裡面建構知識）",emoji:"👩‍🏫",roots:["in","struct"]},
    {word:"insult",chinese:"侮辱",sentence:"It's wrong to <strong>insult</strong> others.",tip:"INSULT = IN + SULT（跳到人身上）",emoji:"😡",roots:["in","sult"]},
    {word:"intend",chinese:"打算",sentence:"I <strong>intend</strong> to finish early.",tip:"INTEND = IN + TEND（心向內伸展）",emoji:"🎯",roots:["in","tend"]},
    {word:"intense",chinese:"強烈的",sentence:"The heat is very <strong>intense</strong> today.",tip:"INTENSE = IN + TENSE（拉緊到裡面）",emoji:"🔥",roots:["in","tense"]},
    {word:"interact",chinese:"互動",sentence:"Students <strong>interact</strong> during group work.",tip:"INTERACT = INTER + ACT（之間行動）",emoji:"👥",roots:["inter","act"]},
    {word:"interest",chinese:"興趣/利息",sentence:"I have an <strong>interest</strong> in science.",tip:"INTEREST = INTER + EST（在其中存在的）",emoji:"🔍",roots:["in","ter","est"]},
    {word:"interpret",chinese:"解釋/翻譯",sentence:"How do you <strong>interpret</strong> this poem?",tip:"INTERPRET = INTER + PRET（在中間解釋）",emoji:"🗣️",roots:["in","ter","pret"]},
    {word:"interrupt",chinese:"打斷",sentence:"Please don't <strong>interrupt</strong> me.",tip:"INTERRUPT = INTER + RUPT（在中間斷裂）",emoji:"✋",roots:["inter","rupt"]},
    {word:"introduce",chinese:"介紹/引進",sentence:"Let me <strong>introduce</strong> my friend.",tip:"INTRODUCE = INTRO + DUCE（帶進去）",emoji:"🤝",roots:["intro","duce"]},
    {word:"invade",chinese:"入侵",sentence:"The army <strong>invade</strong>d the country.",tip:"INVADE = IN + VADE（走進去）",emoji:"⚔️",roots:["in","vade"]},
    {word:"invent",chinese:"發明",sentence:"Edison <strong>invent</strong>ed the light bulb.",tip:"INVENT = IN + VENT（進來找到的）",emoji:"💡",roots:["in","vent"]},
    {word:"invest",chinese:"投資",sentence:"He <strong>invest</strong>ed money in the project.",tip:"INVEST = IN + VEST（穿上＝投入）",emoji:"📈",roots:["in","vest"]},
    {word:"investigate",chinese:"調查",sentence:"Police <strong>investigate</strong>d the case.",tip:"INVESTIGATE = IN + VESTIG + ATE（追蹤腳印）",emoji:"🕵️",roots:["in","ves","ti","gate"]},
    {word:"involve",chinese:"涉及/包含",sentence:"The project <strong>involve</strong>s teamwork.",tip:"INVOLVE = IN + VOLVE（捲進去）",emoji:"🔄",roots:["in","volve"]},
    {word:"irritate",chinese:"激怒/刺激",sentence:"Loud noise <strong>irritate</strong>s me.",tip:"IRRITATE = IR + RIT + ATE（使不安）",emoji:"😠",roots:["ir","ri","tate"]},
    {word:"isolate",chinese:"隔離",sentence:"The sick person was <strong>isolate</strong>d.",tip:"ISOLATE = ISOL + ATE（使成為島嶼般孤立）",emoji:"🏝️",roots:["i","so","late"]},
    {word:"issue",chinese:"問題/議題",sentence:"Pollution is a serious <strong>issue</strong>.",tip:"ISSUE = IS + SUE（出來的事情）",emoji:"❗",roots:["is","sue"]},
    {word:"item",chinese:"項目/物品",sentence:"I need to buy several <strong>item</strong>s.",tip:"ITEM = I + TEM（一個一個的東西）",emoji:"📋",roots:["i","tem"]},
    {word:"joint",chinese:"聯合的/關節",sentence:"They made a <strong>joint</strong> effort.",tip:"JOINT = JOIN + T（連接在一起的）",emoji:"🤝",roots:["joint"]}
  ]
};
