WORD_DATA["competition_mid"] = {

    name: "公館中年級",
    color: "#7c3aed",
    words: [
      {word:"boy",chinese:"男孩",sentence:"The <strong>boy</strong> is playing in the park.",tip:"BOY 只有三個字母，很好記！",emoji:"👦",roots:["boy"]},
      {word:"girl",chinese:"女孩",sentence:"The <strong>girl</strong> has a red dress.",tip:"GIRL 像 GI（美國兵）加上 RL",emoji:"👧",roots:["girl"]},
      {word:"dad",chinese:"爸爸",sentence:"My <strong>dad</strong> cooks dinner.",tip:"DAD 正著讀反著讀都一樣！",emoji:"👨",roots:["dad"]},
      {word:"mom",chinese:"媽媽",sentence:"My <strong>mom</strong> gives me a hug.",tip:"MOM 正著讀反著讀都一樣！",emoji:"👩",roots:["mom"]},
      {word:"apple",chinese:"蘋果",sentence:"I eat an <strong>apple</strong> every day.",tip:"APPLE 有兩個 P！",emoji:"🍎",roots:["app","le"]},
      {word:"cake",chinese:"蛋糕",sentence:"We have <strong>cake</strong> for my birthday.",tip:"CAKE 結尾的 E 不發音",emoji:"🎂",roots:["cake"]},
      {word:"egg",chinese:"蛋",sentence:"I eat one <strong>egg</strong> for breakfast.",tip:"EGG 有兩個 G",emoji:"🥚",roots:["egg"]},
      {word:"zoo",chinese:"動物園",sentence:"We go to the <strong>zoo</strong> on Sunday.",tip:"ZOO 有兩個 O",emoji:"🦁",roots:["zoo"]},
      {word:"blue",chinese:"藍色",sentence:"The sky is <strong>blue</strong> today.",tip:"BLUE 想到天空和大海",emoji:"🔵",roots:["blue"]},
      {word:"green",chinese:"綠色",sentence:"The <strong>green</strong> leaves are beautiful.",tip:"GREEN 有兩個 E",emoji:"🟢",roots:["green"]},
      {word:"red",chinese:"紅色",sentence:"I have a <strong>red</strong> ball.",tip:"RED 只有三個字母",emoji:"🔴",roots:["red"]},
      {word:"yellow",chinese:"黃色",sentence:"The sun is <strong>yellow</strong>.",tip:"YELLOW 有兩個 L",emoji:"🟡",roots:["yell","ow"]},
      {word:"color",chinese:"顏色",sentence:"What <strong>color</strong> do you like?",tip:"COLOR 美式拼法，英式是 colour",emoji:"🎨",roots:["col","or"]},
      {word:"ball",chinese:"球",sentence:"Let's play with the <strong>ball</strong>.",tip:"BALL 有兩個 L",emoji:"⚽",roots:["ball"]},
      {word:"bag",chinese:"袋子/書包",sentence:"Put the book in your <strong>bag</strong>.",tip:"BAG 和 BIG 只差一個字母",emoji:"🎒",roots:["bag"]},
      {word:"book",chinese:"書",sentence:"I read a <strong>book</strong> every night.",tip:"BOOK 有兩個 O",emoji:"📖",roots:["book"]},
      {word:"box",chinese:"箱子",sentence:"The toy is in the <strong>box</strong>.",tip:"BOX 結尾的 X 發 /ks/ 的音",emoji:"📦",roots:["box"]},
      {word:"pencil",chinese:"鉛筆",sentence:"Write your name with a <strong>pencil</strong>.",tip:"PENCIL = PEN + CIL",emoji:"✏️",roots:["pen","cil"]},
      {word:"bird",chinese:"鳥",sentence:"The <strong>bird</strong> sings in the tree.",tip:"BIRD 和 BIRTHDAY 開頭一樣",emoji:"🐦",roots:["bird"]},
      {word:"cat",chinese:"貓",sentence:"My <strong>cat</strong> sleeps all day.",tip:"CAT 只有三個字母",emoji:"🐱",roots:["cat"]},
      {word:"cow",chinese:"牛",sentence:"The <strong>cow</strong> gives us milk.",tip:"COW 和 HOW 押韻",emoji:"🐄",roots:["cow"]},
      {word:"dog",chinese:"狗",sentence:"I walk my <strong>dog</strong> after school.",tip:"DOG 反過來是 GOD",emoji:"🐕",roots:["dog"]},
      {word:"fish",chinese:"魚",sentence:"There are many <strong>fish</strong> in the sea.",tip:"FISH 的複數也是 FISH",emoji:"🐟",roots:["fish"]},
      {word:"pig",chinese:"豬",sentence:"The <strong>pig</strong> is pink and cute.",tip:"PIG 和 BIG 押韻",emoji:"🐷",roots:["pig"]},
      {word:"cup",chinese:"杯子",sentence:"I drink water from a <strong>cup</strong>.",tip:"CUP 和 UP 押韻",emoji:"☕",roots:["cup"]},
      {word:"yo-yo",chinese:"溜溜球",sentence:"I can play with my <strong>yo-yo</strong>.",tip:"YO-YO 上上下下的玩具",emoji:"🪀",roots:["yo","-","yo"]},
      {word:"kid",chinese:"小孩",sentence:"Every <strong>kid</strong> loves ice cream.",tip:"KID 和 BIG 押韻",emoji:"🧒",roots:["kid"]},
      {word:"student",chinese:"學生",sentence:"I am a good <strong>student</strong>.",tip:"STUDENT = STUD + ENT",emoji:"🧑‍🎓",roots:["stu","dent"]},
      {word:"teacher",chinese:"老師",sentence:"Our <strong>teacher</strong> is very kind.",tip:"TEACHER = TEACH + ER（教的人）",emoji:"👩‍🏫",roots:["teach","er"]},
      {word:"doctor",chinese:"醫生",sentence:"The <strong>doctor</strong> helps sick people.",tip:"DOCTOR = DOCT + OR",emoji:"👨‍⚕️",roots:["doc","tor"]},
      {word:"friend",chinese:"朋友",sentence:"She is my best <strong>friend</strong>.",tip:"FRIEND 裡面有 END（到最後都是朋友）",emoji:"🤝",roots:["fri","end"]},
      {word:"father",chinese:"父親",sentence:"My <strong>father</strong> works hard.",tip:"FATHER = FAT + HER（比 dad 正式）",emoji:"👨",roots:["fa","ther"]},
      {word:"mother",chinese:"母親",sentence:"My <strong>mother</strong> loves me.",tip:"MOTHER = MOT + HER（比 mom 正式）",emoji:"👩",roots:["mo","ther"]},
      {word:"brother",chinese:"兄弟",sentence:"My <strong>brother</strong> is older than me.",tip:"BROTHER = BRO + THER",emoji:"👦",roots:["bro","ther"]},
      {word:"sister",chinese:"姊妹",sentence:"My <strong>sister</strong> helps me study.",tip:"SISTER = SIS + TER",emoji:"👧",roots:["sis","ter"]},
      {word:"grandpa",chinese:"爺爺/外公",sentence:"My <strong>grandpa</strong> tells me stories.",tip:"GRANDPA = GRAND + PA",emoji:"👴",roots:["grand","pa"]},
      {word:"grandma",chinese:"奶奶/外婆",sentence:"My <strong>grandma</strong> makes cookies.",tip:"GRANDMA = GRAND + MA",emoji:"👵",roots:["grand","ma"]},
      {word:"banana",chinese:"香蕉",sentence:"The monkey eats a <strong>banana</strong>.",tip:"BANANA 有三個 A！",emoji:"🍌",roots:["ba","na","na"]},
      {word:"milk",chinese:"牛奶",sentence:"I drink <strong>milk</strong> every morning.",tip:"MILK 想到白色的液體",emoji:"🥛",roots:["milk"]},
      {word:"rice",chinese:"米飯",sentence:"We eat <strong>rice</strong> for lunch.",tip:"RICE 和 NICE 押韻",emoji:"🍚",roots:["rice"]},
      {word:"tea",chinese:"茶",sentence:"Mom drinks hot <strong>tea</strong>.",tip:"TEA 只有三個字母",emoji:"🍵",roots:["tea"]},
      {word:"water",chinese:"水",sentence:"Please drink more <strong>water</strong>.",tip:"WATER = WAT + ER",emoji:"💧",roots:["wa","ter"]},
      {word:"cook",chinese:"煮/廚師",sentence:"Dad can <strong>cook</strong> very well.",tip:"COOK 有兩個 O",emoji:"👨‍🍳",roots:["cook"]},
      {word:"orange",chinese:"橘子/橘色",sentence:"I like <strong>orange</strong> juice.",tip:"ORANGE 又是水果又是顏色",emoji:"🍊",roots:["or","ange"]},
      {word:"juice",chinese:"果汁",sentence:"I want apple <strong>juice</strong>.",tip:"JUICE 的 UI 發 /u:/ 的音",emoji:"🧃",roots:["juice"]},
      {word:"hamburger",chinese:"漢堡",sentence:"I eat a <strong>hamburger</strong> for lunch.",tip:"HAMBURGER = HAM + BURGER",emoji:"🍔",roots:["ham","bur","ger"]},
      {word:"ice cream",chinese:"冰淇淋",sentence:"I love chocolate <strong>ice cream</strong>.",tip:"ICE CREAM = 冰 + 奶油",emoji:"🍦",roots:["ice"," ","cream"]},
      {word:"pizza",chinese:"披薩",sentence:"We order <strong>pizza</strong> on Friday.",tip:"PIZZA 有兩個 Z！",emoji:"🍕",roots:["piz","za"]},
      {word:"black",chinese:"黑色",sentence:"My shoes are <strong>black</strong>.",tip:"BLACK 和 BACK 只差一個 L",emoji:"⚫",roots:["black"]},
      {word:"white",chinese:"白色",sentence:"Snow is <strong>white</strong>.",tip:"WHITE 的 WH 發 /w/ 的音",emoji:"⚪",roots:["white"]},
      {word:"desk",chinese:"書桌",sentence:"Put your book on the <strong>desk</strong>.",tip:"DESK 和 DISK 很像",emoji:"🪑",roots:["desk"]},
      {word:"door",chinese:"門",sentence:"Please close the <strong>door</strong>.",tip:"DOOR 有兩個 O",emoji:"🚪",roots:["door"]},
      {word:"marker",chinese:"麥克筆",sentence:"I draw with a <strong>marker</strong>.",tip:"MARKER = MARK + ER",emoji:"🖊️",roots:["mark","er"]},
      {word:"pen",chinese:"筆",sentence:"Write with a <strong>pen</strong>, please.",tip:"PEN 只有三個字母",emoji:"🖊️",roots:["pen"]},
      {word:"table",chinese:"桌子",sentence:"We eat at the <strong>table</strong>.",tip:"TABLE 和 ABLE 押韻",emoji:"🪑",roots:["ta","ble"]},
      {word:"chair",chinese:"椅子",sentence:"Sit on the <strong>chair</strong>.",tip:"CHAIR 裡有 AIR（空氣）",emoji:"💺",roots:["chair"]},
      {word:"eraser",chinese:"橡皮擦",sentence:"I need an <strong>eraser</strong> for my mistake.",tip:"ERASER = ERASE（擦掉）+ R",emoji:"🧹",roots:["eras","er"]},
      {word:"ruler",chinese:"尺",sentence:"Use a <strong>ruler</strong> to draw a line.",tip:"RULER = RULE + R（統治者/尺）",emoji:"📏",roots:["rul","er"]},
      {word:"window",chinese:"窗戶",sentence:"Open the <strong>window</strong>, please.",tip:"WINDOW = WIND + OW（風吹進來）",emoji:"🪟",roots:["win","dow"]},
      {word:"bear",chinese:"熊",sentence:"The <strong>bear</strong> lives in the forest.",tip:"BEAR 和 PEAR（梨子）押韻",emoji:"🐻",roots:["bear"]},
      {word:"monkey",chinese:"猴子",sentence:"The <strong>monkey</strong> climbs the tree.",tip:"MONKEY 裡有 KEY（鑰匙）",emoji:"🐒",roots:["mon","key"]},
      {word:"lion",chinese:"獅子",sentence:"The <strong>lion</strong> is the king of animals.",tip:"LION 聽起來像「賴恩」",emoji:"🦁",roots:["li","on"]},
      {word:"rabbit",chinese:"兔子",sentence:"The <strong>rabbit</strong> eats carrots.",tip:"RABBIT 有兩個 B",emoji:"🐰",roots:["rab","bit"]},
      {word:"tiger",chinese:"老虎",sentence:"The <strong>tiger</strong> has orange stripes.",tip:"TIGER 想到 Tiger Woods",emoji:"🐯",roots:["ti","ger"]},
      {word:"home",chinese:"家",sentence:"I go <strong>home</strong> after school.",tip:"HOME 和 COME 都有 OME",emoji:"🏠",roots:["home"]},
      {word:"park",chinese:"公園",sentence:"We play in the <strong>park</strong>.",tip:"PARK 也有停車的意思",emoji:"🏞️",roots:["park"]},
      {word:"school",chinese:"學校",sentence:"I go to <strong>school</strong> by bus.",tip:"SCHOOL 的 SCH 發 /sk/ 的音",emoji:"🏫",roots:["school"]},
      {word:"bookstore",chinese:"書店",sentence:"I buy books at the <strong>bookstore</strong>.",tip:"BOOKSTORE = BOOK + STORE",emoji:"📚",roots:["book","store"]},
      {word:"fan",chinese:"風扇/粉絲",sentence:"Turn on the <strong>fan</strong>. It is hot.",tip:"FAN 也有粉絲的意思",emoji:"🪭",roots:["fan"]},
      {word:"key",chinese:"鑰匙",sentence:"I lost my <strong>key</strong>.",tip:"KEY 和 FREE 押韻",emoji:"🔑",roots:["key"]},
      {word:"head",chinese:"頭",sentence:"I wear a hat on my <strong>head</strong>.",tip:"HEAD 裡的 EA 發短音 /e/",emoji:"🗣️",roots:["head"]},
      {word:"eye",chinese:"眼睛",sentence:"She has big <strong>eye</strong>s.",tip:"EYE 正著反著都一樣",emoji:"👁️",roots:["eye"]},
      {word:"nose",chinese:"鼻子",sentence:"My <strong>nose</strong> is cold.",tip:"NOSE 和 ROSE 押韻",emoji:"👃",roots:["nose"]},
      {word:"hand",chinese:"手",sentence:"Raise your <strong>hand</strong>, please.",tip:"HAND 和 SAND 押韻",emoji:"✋",roots:["hand"]},
      {word:"arm",chinese:"手臂",sentence:"I hurt my <strong>arm</strong>.",tip:"ARM 和 FARM 押韻",emoji:"💪",roots:["arm"]},
      {word:"leg",chinese:"腿",sentence:"My <strong>leg</strong> is tired from running.",tip:"LEG 和 EGG 押韻",emoji:"🦵",roots:["leg"]},
      {word:"foot",chinese:"腳",sentence:"I step on the ball with my <strong>foot</strong>.",tip:"FOOT 的複數是 FEET（不規則）",emoji:"🦶",roots:["foot"]},
      {word:"face",chinese:"臉",sentence:"Wash your <strong>face</strong> every morning.",tip:"FACE 和 PLACE 押韻",emoji:"😊",roots:["face"]},
      {word:"mouth",chinese:"嘴巴",sentence:"Open your <strong>mouth</strong> wide.",tip:"MOUTH 裡有 OUT",emoji:"👄",roots:["mouth"]},
      {word:"one",chinese:"一",sentence:"I have <strong>one</strong> sister.",tip:"ONE 的發音很特別 /wʌn/",emoji:"1️⃣",roots:["one"]},
      {word:"two",chinese:"二",sentence:"I have <strong>two</strong> eyes.",tip:"TWO 的 W 不發音",emoji:"2️⃣",roots:["two"]},
      {word:"three",chinese:"三",sentence:"There are <strong>three</strong> cats.",tip:"THREE 的 TH 要咬舌頭",emoji:"3️⃣",roots:["three"]},
      {word:"four",chinese:"四",sentence:"A table has <strong>four</strong> legs.",tip:"FOUR 和 DOOR 押韻",emoji:"4️⃣",roots:["four"]},
      {word:"five",chinese:"五",sentence:"I have <strong>five</strong> fingers on one hand.",tip:"FIVE 和 DIVE 押韻",emoji:"5️⃣",roots:["five"]},
      {word:"six",chinese:"六",sentence:"There are <strong>six</strong> eggs in the box.",tip:"SIX 和 MIX 押韻",emoji:"6️⃣",roots:["six"]},
      {word:"seven",chinese:"七",sentence:"There are <strong>seven</strong> days in a week.",tip:"SEVEN = SE + VEN",emoji:"7️⃣",roots:["sev","en"]},
      {word:"eight",chinese:"八",sentence:"I go to bed at <strong>eight</strong>.",tip:"EIGHT 有很多不發音的字母",emoji:"8️⃣",roots:["eight"]},
      {word:"nine",chinese:"九",sentence:"My cat has <strong>nine</strong> lives.",tip:"NINE 和 FINE 押韻",emoji:"9️⃣",roots:["nine"]},
      {word:"ten",chinese:"十",sentence:"I can count to <strong>ten</strong>.",tip:"TEN 和 PEN 押韻",emoji:"🔟",roots:["ten"]},
      {word:"eleven",chinese:"十一",sentence:"There are <strong>eleven</strong> players on a soccer team.",tip:"ELEVEN 有三個 E",emoji:"1️⃣",roots:["e","lev","en"]},
      {word:"twelve",chinese:"十二",sentence:"There are <strong>twelve</strong> months in a year.",tip:"TWELVE 和 SHELF 有點像",emoji:"1️⃣",roots:["twelve"]},
      {word:"old",chinese:"老的/舊的",sentence:"My grandpa is very <strong>old</strong>.",tip:"OLD 和 GOLD 押韻",emoji:"👴",roots:["old"]},
      {word:"short",chinese:"矮的/短的",sentence:"The pencil is very <strong>short</strong>.",tip:"SHORT 裡有 ORT",emoji:"📏",roots:["short"]},
      {word:"tall",chinese:"高的",sentence:"The tree is very <strong>tall</strong>.",tip:"TALL 有兩個 L",emoji:"🌲",roots:["tall"]},
      {word:"thin",chinese:"瘦的",sentence:"The cat is very <strong>thin</strong>.",tip:"THIN 的 TH 要咬舌頭",emoji:"🧍",roots:["thin"]},
      {word:"cold",chinese:"冷的",sentence:"It is very <strong>cold</strong> in winter.",tip:"COLD 和 OLD 押韻",emoji:"🥶",roots:["cold"]},
      {word:"cool",chinese:"涼爽的/酷",sentence:"The weather is <strong>cool</strong> today.",tip:"COOL 有兩個 O，也有「酷」的意思",emoji:"😎",roots:["cool"]},
      {word:"hat",chinese:"帽子",sentence:"I wear a <strong>hat</strong> in summer.",tip:"HAT 和 CAT 押韻",emoji:"🎩",roots:["hat"]},
      {word:"warm",chinese:"溫暖的",sentence:"Spring is <strong>warm</strong>.",tip:"WARM 和 ARM 有關",emoji:"🌤️",roots:["warm"]},
      {word:"cloudy",chinese:"多雲的",sentence:"It is <strong>cloudy</strong> today.",tip:"CLOUDY = CLOUD + Y",emoji:"☁️",roots:["cloud","y"]},
      {word:"rainy",chinese:"下雨的",sentence:"It is <strong>rainy</strong> today. Bring an umbrella.",tip:"RAINY = RAIN + Y",emoji:"🌧️",roots:["rain","y"]},
      {word:"sunny",chinese:"晴朗的",sentence:"It is <strong>sunny</strong> today. Let's go outside.",tip:"SUNNY = SUN + NY（兩個N）",emoji:"☀️",roots:["sun","ny"]},
      {word:"windy",chinese:"有風的",sentence:"It is <strong>windy</strong>. Hold your hat!",tip:"WINDY = WIND + Y",emoji:"💨",roots:["wind","y"]},
      {word:"Sunday",chinese:"星期日",sentence:"We rest on <strong>Sunday</strong>.",tip:"SUNDAY = SUN + DAY（太陽日）",emoji:"☀️",roots:["Sun","day"]},
      {word:"Monday",chinese:"星期一",sentence:"School starts on <strong>Monday</strong>.",tip:"MONDAY = MOON + DAY（月亮日）",emoji:"🌙",roots:["Mon","day"]},
      {word:"Tuesday",chinese:"星期二",sentence:"We have art on <strong>Tuesday</strong>.",tip:"TUESDAY 的 TUE 發 /tju:/ 的音",emoji:"📅",roots:["Tues","day"]},
      {word:"Wednesday",chinese:"星期三",sentence:"<strong>Wednesday</strong> is the middle of the week.",tip:"WEDNESDAY 的 D 不發音！",emoji:"📅",roots:["Wednes","day"]},
      {word:"Thursday",chinese:"星期四",sentence:"We have PE on <strong>Thursday</strong>.",tip:"THURSDAY = THURS + DAY",emoji:"📅",roots:["Thurs","day"]},
      {word:"Friday",chinese:"星期五",sentence:"<strong>Friday</strong> is my favorite day!",tip:"FRIDAY = FRI + DAY（自由日）",emoji:"🎉",roots:["Fri","day"]},
      {word:"Saturday",chinese:"星期六",sentence:"I play games on <strong>Saturday</strong>.",tip:"SATURDAY = SATUR + DAY",emoji:"🎮",roots:["Satur","day"]},
      {word:"time",chinese:"時間",sentence:"What <strong>time</strong> is it?",tip:"TIME 和 DIME 押韻",emoji:"⏰",roots:["time"]},
      {word:"day",chinese:"天/日子",sentence:"Today is a beautiful <strong>day</strong>.",tip:"DAY 和 PLAY 押韻",emoji:"🌅",roots:["day"]},
      {word:"week",chinese:"週",sentence:"There are seven days in a <strong>week</strong>.",tip:"WEEK 有兩個 E",emoji:"📅",roots:["week"]},
      {word:"year",chinese:"年",sentence:"There are twelve months in a <strong>year</strong>.",tip:"YEAR 和 EAR（耳朵）押韻",emoji:"📆",roots:["year"]},
      {word:"now",chinese:"現在",sentence:"I am hungry <strong>now</strong>.",tip:"NOW 和 COW 押韻",emoji:"⏱️",roots:["now"]},
      {word:"today",chinese:"今天",sentence:"<strong>Today</strong> is Monday.",tip:"TODAY = TO + DAY",emoji:"📅",roots:["to","day"]},
      {word:"cry",chinese:"哭",sentence:"Don't <strong>cry</strong>. It's okay.",tip:"CRY 和 FLY 押韻",emoji:"😢",roots:["cry"]},
      {word:"dance",chinese:"跳舞",sentence:"I love to <strong>dance</strong>.",tip:"DANCE 和 CHANCE 押韻",emoji:"💃",roots:["dance"]},
      {word:"jump",chinese:"跳",sentence:"The frog can <strong>jump</strong> high.",tip:"JUMP 和 BUMP 押韻",emoji:"🦘",roots:["jump"]},
      {word:"like",chinese:"喜歡",sentence:"I <strong>like</strong> ice cream.",tip:"LIKE 和 BIKE 押韻",emoji:"❤️",roots:["like"]},
      {word:"read",chinese:"閱讀",sentence:"I <strong>read</strong> a book before bed.",tip:"READ 現在式和過去式拼法一樣！",emoji:"📖",roots:["read"]},
      {word:"sing",chinese:"唱歌",sentence:"Birds <strong>sing</strong> in the morning.",tip:"SING 和 RING 押韻",emoji:"🎤",roots:["sing"]},
      {word:"draw",chinese:"畫畫",sentence:"I <strong>draw</strong> a picture of my family.",tip:"DRAW 過去式是 DREW",emoji:"🎨",roots:["draw"]},
      {word:"sleep",chinese:"睡覺",sentence:"I <strong>sleep</strong> at nine o'clock.",tip:"SLEEP 有兩個 E",emoji:"😴",roots:["sleep"]},
      {word:"swim",chinese:"游泳",sentence:"I can <strong>swim</strong> in the pool.",tip:"SWIM 和 HIM 押韻",emoji:"🏊",roots:["swim"]},
      {word:"want",chinese:"想要",sentence:"I <strong>want</strong> a new toy.",tip:"WANT 的 A 發 /ɒ/ 的音",emoji:"🙏",roots:["want"]},
      {word:"write",chinese:"寫",sentence:"I <strong>write</strong> my name on the paper.",tip:"WRITE 的 W 不發音",emoji:"✍️",roots:["write"]},
      {word:"kite",chinese:"風箏",sentence:"I fly a <strong>kite</strong> in the park.",tip:"KITE 和 BITE 押韻",emoji:"🪁",roots:["kite"]},
      {word:"name",chinese:"名字",sentence:"My <strong>name</strong> is Tom.",tip:"NAME 和 GAME 押韻",emoji:"📛",roots:["name"]},
      {word:"o'clock",chinese:"...點鐘",sentence:"It is three <strong>o'clock</strong>.",tip:"O'CLOCK = OF THE CLOCK 的縮寫",emoji:"🕐",roots:["o'","clock"]},
      {word:"weather",chinese:"天氣",sentence:"The <strong>weather</strong> is nice today.",tip:"WEATHER 和 WHETHER 發音一樣",emoji:"🌤️",roots:["wea","ther"]},
      {word:"big",chinese:"大的",sentence:"The elephant is very <strong>big</strong>.",tip:"BIG 和 PIG 押韻",emoji:"🐘",roots:["big"]},
      {word:"small",chinese:"小的",sentence:"The ant is very <strong>small</strong>.",tip:"SMALL 有兩個 L",emoji:"🐜",roots:["small"]},
      {word:"long",chinese:"長的",sentence:"The snake is very <strong>long</strong>.",tip:"LONG 和 SONG 押韻",emoji:"📏",roots:["long"]},
      {word:"many",chinese:"很多（可數）",sentence:"There are <strong>many</strong> stars in the sky.",tip:"MANY 用在可以數的東西",emoji:"✨",roots:["ma","ny"]},
      {word:"much",chinese:"很多（不可數）",sentence:"I don't have <strong>much</strong> time.",tip:"MUCH 用在不能數的東西",emoji:"📊",roots:["much"]}
    ]
};
