WORD_DATA["coca_l2"] = {
  name: "COCA L2",
  color: "#3b82f6",
  words: [
    {word:"abandon",chinese:"放棄/遺棄",sentence:"Never <strong>abandon</strong> your dreams.",tip:"ABANDON = A + BAND + ON",emoji:"🚫",roots:["a","ban","don"]},
    {word:"discover",chinese:"發現",sentence:"We <strong>discover</strong>ed a hidden path.",tip:"DISCOVER = DIS + COVER(揭開蓋子)",emoji:"🔍",roots:["dis","cov","er"]},
    {word:"absorb",chinese:"吸收/全神貫注",sentence:"Sponges <strong>absorb</strong> water easily.",tip:"ABSORB = AB + SORB(吸)",emoji:"🧽",roots:["ab","sorb"]},
    {word:"explain",chinese:"解釋",sentence:"Can you <strong>explain</strong> this to me?",tip:"EXPLAIN = EX + PLAIN(清楚)",emoji:"💬",roots:["ex","plain"]},
    {word:"accomplish",chinese:"完成/達成",sentence:"She <strong>accomplish</strong>ed her goal.",tip:"ACCOMPLISH = AC + COMPLISH",emoji:"🏆",roots:["ac","com","plish"]},
    {word:"accompany",chinese:"陪伴/伴隨",sentence:"May I <strong>accompany</strong> you home?",tip:"ACCOMPANY = AC + COMPANY(同伴)",emoji:"🚶‍♂️",roots:["ac","com","pa","ny"]},
    {word:"forget",chinese:"忘記",sentence:"Don't <strong>forget</strong> your lunch box!",tip:"FORGET = FOR + GET",emoji:"😅",roots:["for","get"]},
    {word:"acquire",chinese:"獲得/學到",sentence:"She <strong>acquire</strong>d new skills quickly.",tip:"ACQUIRE = AC + QUIRE(尋求)",emoji:"📚",roots:["ac","quire"]},
    {word:"imagine",chinese:"想像",sentence:"<strong>Imagine</strong> you could fly!",tip:"IMAGINE = IMAGE + INE",emoji:"💭",roots:["i","mag","ine"]},
    {word:"notice",chinese:"注意到",sentence:"Did you <strong>notice</strong> the rainbow?",tip:"NOTICE = NOT + ICE",emoji:"👀",roots:["no","tice"]},
    {word:"prepare",chinese:"準備",sentence:"I need to <strong>prepare</strong> for the show.",tip:"PREPARE = PRE(預先) + PARE",emoji:"📝",roots:["pre","pare"]},
    {word:"promise",chinese:"承諾/答應",sentence:"I <strong>promise</strong> I will be careful.",tip:"PROMISE = PRO + MISE",emoji:"🤝",roots:["prom","ise"]},
    {word:"protect",chinese:"保護",sentence:"We must <strong>protect</strong> the environment.",tip:"PROTECT = PRO(向前) + TECT(遮蓋)",emoji:"🛡️",roots:["pro","tect"]},
    {word:"provide",chinese:"提供",sentence:"Trees <strong>provide</strong> shade and oxygen.",tip:"PROVIDE = PRO + VIDE(看/準備)",emoji:"🌳",roots:["pro","vide"]},
    {word:"pull",chinese:"拉",sentence:"<strong>Pull</strong> the door to open it.",tip:"PULL 和 PUSH 相反",emoji:"🤚",roots:["pull"]},
    {word:"push",chinese:"推",sentence:"<strong>Push</strong> the button to start.",tip:"PUSH 和 PULL 相反",emoji:"👋",roots:["push"]},
    {word:"return",chinese:"回來/歸還",sentence:"Please <strong>return</strong> the library book.",tip:"RETURN = RE(回) + TURN",emoji:"↩️",roots:["re","turn"]},
    {word:"save",chinese:"救/存/節省",sentence:"I <strong>save</strong> money every week.",tip:"SAVE 有三個意思都很常用",emoji:"💰",roots:["save"]},
    {word:"throw",chinese:"丟/投",sentence:"<strong>Throw</strong> the ball to me!",tip:"THROW 的過去式是 THREW",emoji:"🤾",roots:["throw"]},
    {word:"touch",chinese:"觸摸/碰",sentence:"Don't <strong>touch</strong> the hot stove!",tip:"TOUCH 的 OU 發 /ʌ/ 的音",emoji:"👆",roots:["touch"]},
    {word:"adapt",chinese:"適應/改編",sentence:"Animals <strong>adapt</strong> to their environment.",tip:"ADAPT = AD + APT(適合)",emoji:"🦎",roots:["ad","apt"]},
    {word:"adjust",chinese:"調整/適應",sentence:"<strong>Adjust</strong> the volume on the speaker.",tip:"ADJUST = AD + JUST(正確)",emoji:"🎚️",roots:["ad","just"]},
    {word:"worry",chinese:"擔心",sentence:"Don't <strong>worry</strong>, everything will be fine.",tip:"WORRY 有兩個 R",emoji:"😟",roots:["wor","ry"]},
    {word:"bright",chinese:"明亮的/聰明的",sentence:"The stars are very <strong>bright</strong> tonight.",tip:"BRIGHT 的 GH 不發音",emoji:"✨",roots:["bright"]},
    {word:"busy",chinese:"忙碌的",sentence:"Mom is very <strong>busy</strong> today.",tip:"BUSY 的 U 發 /ɪ/ 特殊音",emoji:"🏃",roots:["bus","y"]},
    {word:"calm",chinese:"平靜的/冷靜",sentence:"Stay <strong>calm</strong> and take a deep breath.",tip:"CALM 的 L 不發音",emoji:"😌",roots:["calm"]},
    {word:"careful",chinese:"小心的",sentence:"Be <strong>careful</strong> crossing the street.",tip:"CAREFUL = CARE + FUL",emoji:"⚠️",roots:["care","ful"]},
    {word:"cheap",chinese:"便宜的",sentence:"These shoes are very <strong>cheap</strong>.",tip:"CHEAP 和 EXPENSIVE 相反",emoji:"🏷️",roots:["cheap"]},
    {word:"clever",chinese:"聰明的",sentence:"That was a <strong>clever</strong> trick!",tip:"CLEVER = CLEV + ER",emoji:"🧠",roots:["clev","er"]},
    {word:"comfortable",chinese:"舒適的",sentence:"This chair is very <strong>comfortable</strong>.",tip:"COMFORTABLE = COMFORT + ABLE",emoji:"🛋️",roots:["com","fort","able"]},
    {word:"complete",chinese:"完成的/完整的",sentence:"The puzzle is <strong>complete</strong>!",tip:"COMPLETE = COM + PLETE",emoji:"✅",roots:["com","plete"]},
    {word:"correct",chinese:"正確的",sentence:"Your answer is <strong>correct</strong>!",tip:"CORRECT = COR + RECT(直)",emoji:"✅",roots:["cor","rect"]},
    {word:"dangerous",chinese:"危險的",sentence:"Swimming alone is <strong>dangerous</strong>.",tip:"DANGEROUS = DANGER + OUS",emoji:"⚠️",roots:["dan","ger","ous"]},
    {word:"dry",chinese:"乾的/乾燥",sentence:"The towel is <strong>dry</strong> now.",tip:"DRY 和 WET 相反",emoji:"☀️",roots:["dry"]},
    {word:"equal",chinese:"相等的/平等的",sentence:"All people are <strong>equal</strong>.",tip:"EQUAL = E + QUAL",emoji:"⚖️",roots:["e","qual"]},
    {word:"exact",chinese:"確切的/精確的",sentence:"What is the <strong>exact</strong> time?",tip:"EXACT = EX + ACT",emoji:"🎯",roots:["ex","act"]},
    {word:"fair",chinese:"公平的/展覽會",sentence:"That is not <strong>fair</strong>!",tip:"FAIR 有「公平」和「博覽會」的意思",emoji:"⚖️",roots:["fair"]},
    {word:"familiar",chinese:"熟悉的",sentence:"That song sounds <strong>familiar</strong>.",tip:"FAMILIAR = FAMIL(家) + IAR",emoji:"🤔",roots:["fa","mil","iar"]},
    {word:"famous",chinese:"有名的",sentence:"She is a <strong>famous</strong> singer.",tip:"FAMOUS = FAM(名聲) + OUS",emoji:"⭐",roots:["fam","ous"]},
    {word:"flat",chinese:"平的/公寓",sentence:"The road is very <strong>flat</strong> here.",tip:"FLAT 和 FAT 只差一個字母",emoji:"➖",roots:["flat"]},
    {word:"fresh",chinese:"新鮮的",sentence:"I love <strong>fresh</strong> fruit.",tip:"FRESH 想到剛摘的蔬果",emoji:"🍎",roots:["fresh"]},
    {word:"funny",chinese:"有趣的/好笑的",sentence:"That joke is so <strong>funny</strong>!",tip:"FUNNY = FUN + NY",emoji:"😂",roots:["fun","ny"]},
    {word:"gentle",chinese:"溫柔的/輕柔的",sentence:"Be <strong>gentle</strong> with the kitten.",tip:"GENTLE = GENT + LE",emoji:"🤗",roots:["gen","tle"]},
    {word:"glad",chinese:"高興的",sentence:"I am <strong>glad</strong> you came!",tip:"GLAD 和 HAPPY 意思相近",emoji:"😊",roots:["glad"]},
    {word:"guilty",chinese:"有罪的/內疚的",sentence:"I feel <strong>guilty</strong> for eating the last cookie.",tip:"GUILTY = GUILT + Y",emoji:"😔",roots:["guilt","y"]},
    {word:"helpful",chinese:"有幫助的",sentence:"You are always so <strong>helpful</strong>!",tip:"HELPFUL = HELP + FUL",emoji:"🤝",roots:["help","ful"]},
    {word:"honest",chinese:"誠實的",sentence:"An <strong>honest</strong> person tells the truth.",tip:"HONEST 的 H 不發音",emoji:"🤞",roots:["hon","est"]},
    {word:"huge",chinese:"巨大的",sentence:"The whale is <strong>huge</strong>!",tip:"HUGE 比 BIG 大很多！",emoji:"🐋",roots:["huge"]},
    {word:"impossible",chinese:"不可能的",sentence:"Nothing is <strong>impossible</strong> if you try.",tip:"IMPOSSIBLE = IM(不) + POSSIBLE",emoji:"🚫",roots:["im","poss","ible"]},
    {word:"interesting",chinese:"有趣的",sentence:"This book is very <strong>interesting</strong>.",tip:"INTERESTING = INTEREST + ING",emoji:"📚",roots:["in","ter","est","ing"]},
    {word:"lazy",chinese:"懶惰的",sentence:"The <strong>lazy</strong> cat sleeps all day.",tip:"LAZY 和 HARDWORKING 相反",emoji:"😴",roots:["laz","y"]},
    {word:"likely",chinese:"可能的",sentence:"It is <strong>likely</strong> to rain tomorrow.",tip:"LIKELY = LIKE + LY",emoji:"🌧️",roots:["like","ly"]},
    {word:"lonely",chinese:"孤獨的/寂寞的",sentence:"The <strong>lonely</strong> boy needed a friend.",tip:"LONELY = LONE + LY",emoji:"😢",roots:["lone","ly"]},
    {word:"loud",chinese:"大聲的",sentence:"The music is too <strong>loud</strong>!",tip:"LOUD 和 QUIET 相反",emoji:"🔊",roots:["loud"]},
    {word:"lucky",chinese:"幸運的",sentence:"I feel very <strong>lucky</strong> today!",tip:"LUCKY = LUCK + Y",emoji:"🍀",roots:["luck","y"]},
    {word:"main",chinese:"主要的",sentence:"The <strong>main</strong> idea is teamwork.",tip:"MAIN 和 RAIN 押韻",emoji:"⭐",roots:["main"]},
    {word:"narrow",chinese:"狹窄的",sentence:"The path is too <strong>narrow</strong> for cars.",tip:"NARROW 和 WIDE 相反",emoji:"↔️",roots:["nar","row"]},
    {word:"neat",chinese:"整潔的",sentence:"Keep your room <strong>neat</strong> and tidy.",tip:"NEAT 和 MESSY 相反",emoji:"✨",roots:["neat"]},
    {word:"necessary",chinese:"必要的",sentence:"Sleep is <strong>necessary</strong> for health.",tip:"NECESSARY 有一個 C 兩個 S",emoji:"❗",roots:["nec","es","sary"]},
    {word:"nervous",chinese:"緊張的",sentence:"I am <strong>nervous</strong> about the test.",tip:"NERVOUS = NERV(神經) + OUS",emoji:"😰",roots:["nerv","ous"]},
    {word:"normal",chinese:"正常的",sentence:"It is <strong>normal</strong> to feel scared.",tip:"NORMAL = NORM(標準) + AL",emoji:"👌",roots:["norm","al"]},
    {word:"obvious",chinese:"明顯的",sentence:"The answer is <strong>obvious</strong>!",tip:"OBVIOUS = OB + VIOUS",emoji:"💡",roots:["ob","vi","ous"]},
    {word:"pleasant",chinese:"令人愉快的",sentence:"What a <strong>pleasant</strong> surprise!",tip:"PLEASANT = PLEAS + ANT",emoji:"😊",roots:["pleas","ant"]},
    {word:"polite",chinese:"有禮貌的",sentence:"Always be <strong>polite</strong> to others.",tip:"POLITE 和 RUDE 相反",emoji:"🙏",roots:["po","lite"]},
    {word:"popular",chinese:"受歡迎的",sentence:"She is very <strong>popular</strong> at school.",tip:"POPULAR = POP + U + LAR",emoji:"🌟",roots:["pop","u","lar"]},
    {word:"powerful",chinese:"強大的",sentence:"The engine is very <strong>powerful</strong>.",tip:"POWERFUL = POWER + FUL",emoji:"💪",roots:["pow","er","ful"]},
    {word:"proper",chinese:"適當的/正確的",sentence:"Use the <strong>proper</strong> tool for the job.",tip:"PROPER = PROP + ER",emoji:"✅",roots:["prop","er"]},
    {word:"proud",chinese:"驕傲的/自豪的",sentence:"I am <strong>proud</strong> of you!",tip:"PROUD 和 LOUD 押韻",emoji:"🏆",roots:["proud"]},
    {word:"quick",chinese:"快的/迅速的",sentence:"Give me a <strong>quick</strong> answer.",tip:"QUICK 和 FAST 意思相近",emoji:"⚡",roots:["quick"]},
    {word:"quiet",chinese:"安靜的",sentence:"Please be <strong>quiet</strong> in the library.",tip:"QUIET 不要和 QUITE 搞混！",emoji:"🤫",roots:["qui","et"]},
    {word:"rare",chinese:"罕見的/稀有的",sentence:"That bird is very <strong>rare</strong>.",tip:"RARE 和 CARE 押韻",emoji:"💎",roots:["rare"]},
    {word:"raw",chinese:"生的/未煮的",sentence:"Don't eat <strong>raw</strong> meat.",tip:"RAW 和 LAW 押韻",emoji:"🥩",roots:["raw"]},
    {word:"reasonable",chinese:"合理的",sentence:"The price is <strong>reasonable</strong>.",tip:"REASONABLE = REASON + ABLE",emoji:"👌",roots:["rea","son","able"]},
    {word:"regular",chinese:"規律的/正常的",sentence:"I take <strong>regular</strong> exercise.",tip:"REGULAR = REG + U + LAR",emoji:"🔁",roots:["reg","u","lar"]},
    {word:"responsible",chinese:"負責任的",sentence:"She is very <strong>responsible</strong>.",tip:"RESPONSIBLE = RESPONSE + IBLE",emoji:"✊",roots:["re","spon","sible"]},
    {word:"rough",chinese:"粗糙的/大約的",sentence:"The rock has a <strong>rough</strong> surface.",tip:"ROUGH 的 GH 發 /f/",emoji:"🪨",roots:["rough"]},
    {word:"round",chinese:"圓的",sentence:"The ball is <strong>round</strong>.",tip:"ROUND 和 GROUND 押韻",emoji:"⭕",roots:["round"]},
    {word:"rude",chinese:"粗魯的/無禮的",sentence:"It is <strong>rude</strong> to interrupt.",tip:"RUDE 和 POLITE 相反",emoji:"😤",roots:["rude"]},
    {word:"safe",chinese:"安全的",sentence:"Make sure everyone is <strong>safe</strong>.",tip:"SAFE 和 DANGEROUS 相反",emoji:"🔒",roots:["safe"]},
    {word:"secret",chinese:"秘密/祕密的",sentence:"Can you keep a <strong>secret</strong>?",tip:"SECRET = SE + CRET",emoji:"🤫",roots:["se","cret"]},
    {word:"serious",chinese:"嚴肅的/認真的",sentence:"This is a <strong>serious</strong> matter.",tip:"SERIOUS = SERI + OUS",emoji:"😐",roots:["ser","i","ous"]},
    {word:"sharp",chinese:"鋒利的/尖的",sentence:"The knife is very <strong>sharp</strong>.",tip:"SHARP 和 DULL 相反",emoji:"🔪",roots:["sharp"]},
    {word:"shy",chinese:"害羞的",sentence:"The new student is very <strong>shy</strong>.",tip:"SHY 只有三個字母",emoji:"😊",roots:["shy"]},
    {word:"silly",chinese:"傻的/愚蠢的",sentence:"That was a <strong>silly</strong> mistake.",tip:"SILLY 有兩個 L",emoji:"🤪",roots:["sil","ly"]},
    {word:"slight",chinese:"輕微的",sentence:"There is a <strong>slight</strong> breeze.",tip:"SLIGHT 的 GH 不發音",emoji:"🌬️",roots:["slight"]},
    {word:"smart",chinese:"聰明的/漂亮的",sentence:"You are a <strong>smart</strong> kid!",tip:"SMART 和 CLEVER 意思相近",emoji:"🧠",roots:["smart"]},
    {word:"smooth",chinese:"光滑的/順暢的",sentence:"The ice is very <strong>smooth</strong>.",tip:"SMOOTH 和 ROUGH 相反",emoji:"✨",roots:["smooth"]},
    {word:"soft",chinese:"柔軟的",sentence:"The pillow is very <strong>soft</strong>.",tip:"SOFT 和 HARD 相反",emoji:"🧸",roots:["soft"]},
    {word:"solid",chinese:"固體的/堅固的",sentence:"Ice is <strong>solid</strong> water.",tip:"SOLID = SOL + ID",emoji:"🧊",roots:["sol","id"]},
    {word:"strange",chinese:"奇怪的/陌生的",sentence:"I heard a <strong>strange</strong> noise.",tip:"STRANGE = STRANG + E",emoji:"🤨",roots:["strange"]},
    {word:"strict",chinese:"嚴格的",sentence:"Our teacher is very <strong>strict</strong>.",tip:"STRICT 和 LENIENT 相反",emoji:"😠",roots:["strict"]},
    {word:"stupid",chinese:"愚蠢的",sentence:"That was a <strong>stupid</strong> mistake.",tip:"STUPID = STU + PID",emoji:"😤",roots:["stu","pid"]},
    {word:"sudden",chinese:"突然的",sentence:"There was a <strong>sudden</strong> noise.",tip:"SUDDEN 有兩個 D",emoji:"⚡",roots:["sud","den"]},
    {word:"suitable",chinese:"合適的",sentence:"This movie is <strong>suitable</strong> for children.",tip:"SUITABLE = SUIT + ABLE",emoji:"👌",roots:["suit","able"]},
    {word:"surprised",chinese:"驚訝的",sentence:"I was <strong>surprised</strong> by the gift!",tip:"SURPRISED = SURPRISE + D",emoji:"😲",roots:["sur","prise","d"]},
    {word:"sweet",chinese:"甜的/甜蜜的",sentence:"The fruit is very <strong>sweet</strong>.",tip:"SWEET 有兩個 E",emoji:"🍬",roots:["sweet"]},
    {word:"thick",chinese:"厚的/濃的",sentence:"The book is very <strong>thick</strong>.",tip:"THICK 和 THIN 相反",emoji:"📗",roots:["thick"]},
    {word:"tight",chinese:"緊的",sentence:"These shoes are too <strong>tight</strong>.",tip:"TIGHT 和 LOOSE 相反",emoji:"👟",roots:["tight"]},
    {word:"tiny",chinese:"極小的",sentence:"The ant is <strong>tiny</strong>.",tip:"TINY 比 SMALL 更小",emoji:"🐜",roots:["ti","ny"]},
    {word:"tough",chinese:"堅韌的/困難的",sentence:"The test was really <strong>tough</strong>.",tip:"TOUGH 的 GH 發 /f/",emoji:"💪",roots:["tough"]},
    {word:"ugly",chinese:"醜的",sentence:"The monster in the story is <strong>ugly</strong>.",tip:"UGLY 和 BEAUTIFUL 相反",emoji:"👹",roots:["ug","ly"]},
    {word:"unusual",chinese:"不尋常的",sentence:"That is an <strong>unusual</strong> plant.",tip:"UNUSUAL = UN + USUAL",emoji:"🤨",roots:["un","usu","al"]},
    {word:"useful",chinese:"有用的",sentence:"This tool is very <strong>useful</strong>.",tip:"USEFUL = USE + FUL",emoji:"🔧",roots:["use","ful"]},
    {word:"usual",chinese:"通常的/平常的",sentence:"I took my <strong>usual</strong> seat.",tip:"USUAL 的反義是 UNUSUAL",emoji:"📅",roots:["usu","al"]},
    {word:"valuable",chinese:"有價值的/貴重的",sentence:"Time is <strong>valuable</strong>.",tip:"VALUABLE = VALUE + ABLE",emoji:"💎",roots:["valu","able"]},
    {word:"violent",chinese:"暴力的/猛烈的",sentence:"The storm was very <strong>violent</strong>.",tip:"VIOLENT = VIOL + ENT",emoji:"🌪️",roots:["vi","o","lent"]},
    {word:"wet",chinese:"濕的",sentence:"My shoes are <strong>wet</strong> from the rain.",tip:"WET 和 DRY 相反",emoji:"💦",roots:["wet"]},
    {word:"wild",chinese:"野生的/瘋狂的",sentence:"We saw <strong>wild</strong> deer in the forest.",tip:"WILD 和 TAME 相反",emoji:"🦌",roots:["wild"]},
    {word:"wise",chinese:"有智慧的",sentence:"The owl is a <strong>wise</strong> bird.",tip:"WISE 和 FOOLISH 相反",emoji:"🦉",roots:["wise"]},
    {word:"worried",chinese:"擔心的",sentence:"She looks <strong>worried</strong> about the test.",tip:"WORRIED = WORRY 去 Y + IED",emoji:"😟",roots:["worr","ied"]},
    {word:"worth",chinese:"值得的",sentence:"This movie is <strong>worth</strong> watching.",tip:"WORTH 表示有...價值",emoji:"💰",roots:["worth"]},
    {word:"accept",chinese:"接受",sentence:"I <strong>accept</strong> your invitation.",tip:"ACCEPT = AC + CEPT(拿取)",emoji:"🤝",roots:["ac","cept"]},
    {word:"achieve",chinese:"達成/實現",sentence:"You can <strong>achieve</strong> your dreams!",tip:"ACHIEVE = A + CHIEVE",emoji:"🏆",roots:["a","chieve"]},
    {word:"admire",chinese:"欽佩/讚賞",sentence:"I <strong>admire</strong> her courage.",tip:"ADMIRE = AD + MIRE(看)",emoji:"🌟",roots:["ad","mire"]},
    {word:"admit",chinese:"承認",sentence:"He <strong>admit</strong>ted his mistake.",tip:"ADMIT = AD + MIT(送)",emoji:"🙋",roots:["ad","mit"]},
    {word:"advise",chinese:"建議/勸告",sentence:"I <strong>advise</strong> you to study harder.",tip:"ADVISE = AD + VISE(看)",emoji:"💡",roots:["ad","vise"]},
    {word:"afford",chinese:"負擔得起",sentence:"I can't <strong>afford</strong> that bike.",tip:"AFFORD = AF + FORD",emoji:"💰",roots:["af","ford"]},
    {word:"allow",chinese:"允許",sentence:"Mom <strong>allow</strong>ed me to stay up late.",tip:"ALLOW = AL + LOW",emoji:"✅",roots:["al","low"]},
    {word:"announce",chinese:"宣布",sentence:"The teacher <strong>announce</strong>d the winners.",tip:"ANNOUNCE = AN + NOUNCE",emoji:"📢",roots:["an","nounce"]},
    {word:"apologize",chinese:"道歉",sentence:"I want to <strong>apologize</strong> for being late.",tip:"APOLOGIZE = APOLOGY + IZE",emoji:"🙏",roots:["a","pol","o","gize"]},
    {word:"apply",chinese:"申請/應用",sentence:"I will <strong>apply</strong> for the scholarship.",tip:"APPLY = AP + PLY",emoji:"📝",roots:["ap","ply"]},
    {word:"arrange",chinese:"安排/整理",sentence:"Let me <strong>arrange</strong> the flowers.",tip:"ARRANGE = AR + RANGE",emoji:"🌹",roots:["ar","range"]},
    {word:"attach",chinese:"附上/黏貼",sentence:"<strong>Attach</strong> the photo to the email.",tip:"ATTACH = AT + TACH",emoji:"📎",roots:["at","tach"]},
    {word:"attempt",chinese:"嘗試/企圖",sentence:"I will <strong>attempt</strong> to climb the wall.",tip:"ATTEMPT = AT + TEMPT",emoji:"🧗",roots:["at","tempt"]},
    {word:"attend",chinese:"參加/出席",sentence:"I will <strong>attend</strong> the meeting.",tip:"ATTEND = AT + TEND",emoji:"🏛️",roots:["at","tend"]},
    {word:"avoid",chinese:"避免",sentence:"Try to <strong>avoid</strong> sugar.",tip:"AVOID = A + VOID(空)",emoji:"🚫",roots:["a","void"]},
    {word:"bake",chinese:"烘烤",sentence:"Let's <strong>bake</strong> some cookies!",tip:"BAKE 和 CAKE 押韻",emoji:"🍪",roots:["bake"]},
    {word:"blame",chinese:"責怪",sentence:"Don't <strong>blame</strong> others for your mistakes.",tip:"BLAME 和 GAME 押韻",emoji:"👉",roots:["blame"]},
    {word:"borrow",chinese:"借（入）",sentence:"May I <strong>borrow</strong> your pencil?",tip:"BORROW 是借入，LEND 是借出",emoji:"🤲",roots:["bor","row"]},
    {word:"breathe",chinese:"呼吸",sentence:"Take a deep breath and <strong>breathe</strong> slowly.",tip:"BREATHE 有 E 結尾和 BREATH 不同",emoji:"🌬️",roots:["breathe"]},
    {word:"celebrate",chinese:"慶祝",sentence:"Let's <strong>celebrate</strong> your birthday!",tip:"CELEBRATE = CELE + BRATE",emoji:"🎉",roots:["cel","e","brate"]},
    {word:"chase",chinese:"追趕",sentence:"The dog <strong>chase</strong>d the cat.",tip:"CHASE 和 RACE 押韻",emoji:"🏃",roots:["chase"]},
    {word:"cheat",chinese:"作弊/欺騙",sentence:"Never <strong>cheat</strong> on a test.",tip:"CHEAT 和 EAT 押韻",emoji:"🚫",roots:["cheat"]},
    {word:"check",chinese:"檢查/確認",sentence:"<strong>Check</strong> your answer before submitting.",tip:"CHECK 和 DECK 押韻",emoji:"✅",roots:["check"]},
    {word:"choose",chinese:"選擇",sentence:"<strong>Choose</strong> your favorite color.",tip:"CHOOSE 的過去式是 CHOSE",emoji:"👆",roots:["choose"]},
    {word:"climb",chinese:"爬/攀登",sentence:"We <strong>climb</strong>ed the mountain.",tip:"CLIMB 的 B 不發音",emoji:"🧗",roots:["climb"]},
    {word:"collect",chinese:"收集",sentence:"I <strong>collect</strong> stamps as a hobby.",tip:"COLLECT = COL + LECT(選/集)",emoji:"📫",roots:["col","lect"]},
    {word:"compare",chinese:"比較",sentence:"<strong>Compare</strong> the two pictures.",tip:"COMPARE = COM + PARE",emoji:"🔄",roots:["com","pare"]},
    {word:"complain",chinese:"抱怨",sentence:"Stop <strong>complain</strong>ing and start working.",tip:"COMPLAIN = COM + PLAIN",emoji:"😤",roots:["com","plain"]},
    {word:"connect",chinese:"連接",sentence:"<strong>Connect</strong> the dots to form a picture.",tip:"CONNECT = CON + NECT(綁)",emoji:"🔗",roots:["con","nect"]},
    {word:"contain",chinese:"包含/容納",sentence:"This box <strong>contain</strong>s my toys.",tip:"CONTAIN = CON + TAIN(持有)",emoji:"📦",roots:["con","tain"]},
    {word:"copy",chinese:"抄寫/複製",sentence:"Please <strong>copy</strong> the sentences into your notebook.",tip:"COPY 的複數是 COPIES",emoji:"📝",roots:["cop","y"]},
    {word:"count",chinese:"數/計算",sentence:"Can you <strong>count</strong> to one hundred?",tip:"COUNT 和 MOUNT 押韻",emoji:"🔢",roots:["count"]},
    {word:"cross",chinese:"穿越/交叉",sentence:"<strong>Cross</strong> the street at the crosswalk.",tip:"CROSS 有兩個 S",emoji:"🚸",roots:["cross"]},
    {word:"cure",chinese:"治癒/療法",sentence:"Scientists are looking for a <strong>cure</strong>.",tip:"CURE 和 PURE 押韻",emoji:"💊",roots:["cure"]},
    {word:"damage",chinese:"損壞/傷害",sentence:"The storm <strong>damage</strong>d many houses.",tip:"DAMAGE = DAM + AGE",emoji:"🌪️",roots:["dam","age"]},
    {word:"deliver",chinese:"遞送/發表",sentence:"The mailman <strong>deliver</strong>s packages.",tip:"DELIVER = DE + LIVER",emoji:"📦",roots:["de","liv","er"]},
    {word:"demand",chinese:"要求/需求",sentence:"The customers <strong>demand</strong> better service.",tip:"DEMAND = DE + MAND(命令)",emoji:"❗",roots:["de","mand"]},
    {word:"depend",chinese:"依賴/取決於",sentence:"It <strong>depend</strong>s on the weather.",tip:"DEPEND = DE + PEND(掛)",emoji:"🤝",roots:["de","pend"]},
    {word:"describe",chinese:"描述",sentence:"<strong>Describe</strong> what you see.",tip:"DESCRIBE = DE + SCRIBE(寫)",emoji:"📝",roots:["de","scribe"]},
    {word:"design",chinese:"設計",sentence:"She <strong>design</strong>ed a beautiful dress.",tip:"DESIGN = DE + SIGN",emoji:"🎨",roots:["de","sign"]},
    {word:"destroy",chinese:"摧毀",sentence:"The fire <strong>destroy</strong>ed the building.",tip:"DESTROY = DE + STROY",emoji:"🔥",roots:["de","stroy"]},
    {word:"direct",chinese:"直接的/指導",sentence:"Can you <strong>direct</strong> me to the station?",tip:"DIRECT = DI + RECT(直)",emoji:"➡️",roots:["di","rect"]},
    {word:"disappear",chinese:"消失",sentence:"The magician made the rabbit <strong>disappear</strong>.",tip:"DISAPPEAR = DIS + APPEAR",emoji:"🎩",roots:["dis","ap","pear"]},
    {word:"divide",chinese:"分開/除",sentence:"<strong>Divide</strong> the cake into eight pieces.",tip:"DIVIDE = DI + VIDE",emoji:"🍰",roots:["di","vide"]},
    {word:"double",chinese:"兩倍的/加倍",sentence:"I got <strong>double</strong> the amount!",tip:"DOUBLE = DOUB + LE",emoji:"✌️",roots:["doub","le"]},
    {word:"doubt",chinese:"懷疑",sentence:"I <strong>doubt</strong> he will come.",tip:"DOUBT 的 B 不發音",emoji:"🤨",roots:["doubt"]},
    {word:"earn",chinese:"賺/獲得",sentence:"She <strong>earn</strong>s money by tutoring.",tip:"EARN 和 LEARN 押韻",emoji:"💰",roots:["earn"]},
    {word:"encourage",chinese:"鼓勵",sentence:"My parents <strong>encourage</strong> me to read.",tip:"ENCOURAGE = EN + COURAGE",emoji:"💪",roots:["en","cour","age"]},
    {word:"enter",chinese:"進入",sentence:"Please <strong>enter</strong> the room quietly.",tip:"ENTER = EN + TER",emoji:"🚪",roots:["en","ter"]},
    {word:"escape",chinese:"逃跑/逃脫",sentence:"The bird <strong>escape</strong>d from the cage.",tip:"ESCAPE = ES + CAPE",emoji:"🏃",roots:["es","cape"]},
    {word:"examine",chinese:"檢查/考試",sentence:"The doctor <strong>examine</strong>d my eyes.",tip:"EXAMINE = EX + AMINE",emoji:"🔍",roots:["ex","am","ine"]},
    {word:"exchange",chinese:"交換",sentence:"Let's <strong>exchange</strong> phone numbers.",tip:"EXCHANGE = EX + CHANGE",emoji:"🔄",roots:["ex","change"]},
    {word:"exist",chinese:"存在",sentence:"Do ghosts really <strong>exist</strong>?",tip:"EXIST = EX + IST",emoji:"👻",roots:["ex","ist"]},
    {word:"express",chinese:"表達/快速的",sentence:"I want to <strong>express</strong> my thanks.",tip:"EXPRESS = EX + PRESS",emoji:"💬",roots:["ex","press"]},
    {word:"fail",chinese:"失敗",sentence:"If you <strong>fail</strong>, try again!",tip:"FAIL 和 SUCCEED 相反",emoji:"📉",roots:["fail"]},
    {word:"feed",chinese:"餵食",sentence:"Don't forget to <strong>feed</strong> the fish.",tip:"FEED 有兩個 E",emoji:"🐟",roots:["feed"]},
    {word:"fight",chinese:"打架/戰鬥",sentence:"Don't <strong>fight</strong> with your brother.",tip:"FIGHT 的 GH 不發音",emoji:"🥊",roots:["fight"]},
    {word:"fill",chinese:"填滿",sentence:"<strong>Fill</strong> the cup with water.",tip:"FILL 有兩個 L",emoji:"🥛",roots:["fill"]},
    {word:"fix",chinese:"修理/固定",sentence:"Dad can <strong>fix</strong> anything.",tip:"FIX 只有三個字母",emoji:"🔧",roots:["fix"]},
    {word:"flow",chinese:"流動",sentence:"The river <strong>flow</strong>s to the sea.",tip:"FLOW 和 SHOW 押韻",emoji:"🌊",roots:["flow"]},
    {word:"fold",chinese:"折疊",sentence:"<strong>Fold</strong> the paper in half.",tip:"FOLD 和 GOLD 押韻",emoji:"📄",roots:["fold"]},
    {word:"gain",chinese:"獲得/增加",sentence:"I <strong>gain</strong>ed confidence from practice.",tip:"GAIN 和 RAIN 押韻",emoji:"📈",roots:["gain"]},
    {word:"gather",chinese:"聚集/收集",sentence:"We <strong>gather</strong>ed flowers in the garden.",tip:"GATHER = GATH + ER",emoji:"💐",roots:["gath","er"]},
    {word:"grab",chinese:"抓取",sentence:"<strong>Grab</strong> your coat, we are leaving!",tip:"GRAB 和 CATCH 意思相近",emoji:"🤏",roots:["grab"]},
    {word:"greet",chinese:"問候/打招呼",sentence:"She <strong>greet</strong>ed us with a big smile.",tip:"GREET 有兩個 E",emoji:"👋",roots:["greet"]},
    {word:"guess",chinese:"猜",sentence:"Can you <strong>guess</strong> what I am thinking?",tip:"GUESS 的 U 不發音",emoji:"🤔",roots:["guess"]},
    {word:"guide",chinese:"引導/指南",sentence:"The map will <strong>guide</strong> us.",tip:"GUIDE 的 U 不發音",emoji:"🗺️",roots:["guide"]},
    {word:"hang",chinese:"掛/懸掛",sentence:"<strong>Hang</strong> your coat on the hook.",tip:"HANG 的過去式是 HUNG",emoji:"🧥",roots:["hang"]},
    {word:"hate",chinese:"討厭/恨",sentence:"I <strong>hate</strong> getting up early.",tip:"HATE 和 LOVE 相反",emoji:"😡",roots:["hate"]},
    {word:"hide",chinese:"躲藏/隱藏",sentence:"Let's play <strong>hide</strong> and seek!",tip:"HIDE 的過去式是 HID",emoji:"🙈",roots:["hide"]},
    {word:"hit",chinese:"打/擊中",sentence:"He <strong>hit</strong> the ball over the fence.",tip:"HIT 三態同形：hit-hit-hit",emoji:"🏏",roots:["hit"]},
    {word:"hunt",chinese:"打獵/搜尋",sentence:"The cat <strong>hunt</strong>s mice at night.",tip:"HUNT 和 FRONT 押韻",emoji:"🐱",roots:["hunt"]},
    {word:"hurry",chinese:"趕快/匆忙",sentence:"<strong>Hurry</strong> up or we will be late!",tip:"HURRY 有兩個 R",emoji:"🏃",roots:["hur","ry"]},
    {word:"hurt",chinese:"傷害/受傷",sentence:"Did you <strong>hurt</strong> yourself?",tip:"HURT 三態同形：hurt-hurt-hurt",emoji:"🤕",roots:["hurt"]},
    {word:"improve",chinese:"改善/進步",sentence:"I want to <strong>improve</strong> my English.",tip:"IMPROVE = IM + PROVE",emoji:"📈",roots:["im","prove"]},
    {word:"insist",chinese:"堅持",sentence:"She <strong>insist</strong>ed on paying.",tip:"INSIST = IN + SIST(站)",emoji:"✊",roots:["in","sist"]},
    {word:"intend",chinese:"打算/意圖",sentence:"I <strong>intend</strong> to finish today.",tip:"INTEND = IN + TEND",emoji:"🎯",roots:["in","tend"]},
    {word:"introduce",chinese:"介紹",sentence:"Let me <strong>introduce</strong> myself.",tip:"INTRODUCE = INTRO + DUCE(帶領)",emoji:"🤝",roots:["intro","duce"]},
    {word:"invent",chinese:"發明",sentence:"Who <strong>invent</strong>ed the light bulb?",tip:"INVENT = IN + VENT(來)",emoji:"💡",roots:["in","vent"]},
    {word:"invite",chinese:"邀請",sentence:"I want to <strong>invite</strong> you to my party.",tip:"INVITE = IN + VITE",emoji:"💌",roots:["in","vite"]},
    {word:"involve",chinese:"涉及/包含",sentence:"The project <strong>involve</strong>s teamwork.",tip:"INVOLVE = IN + VOLVE(轉)",emoji:"🤝",roots:["in","volve"]},
    {word:"joke",chinese:"笑話/開玩笑",sentence:"He told a funny <strong>joke</strong>.",tip:"JOKE 和 POKE 押韻",emoji:"😂",roots:["joke"]},
    {word:"knock",chinese:"敲",sentence:"<strong>Knock</strong> on the door before entering.",tip:"KNOCK 的 K 不發音",emoji:"🚪",roots:["knock"]},
    {word:"lack",chinese:"缺乏",sentence:"I <strong>lack</strong> confidence in math.",tip:"LACK 和 BACK 押韻",emoji:"😔",roots:["lack"]},
    {word:"lend",chinese:"借（出）",sentence:"Can you <strong>lend</strong> me a pen?",tip:"LEND 是借出，BORROW 是借入",emoji:"🤲",roots:["lend"]},
    {word:"limit",chinese:"限制/限度",sentence:"There is a speed <strong>limit</strong> here.",tip:"LIMIT = LIM + IT",emoji:"🚫",roots:["lim","it"]},
    {word:"locate",chinese:"找到位置/位於",sentence:"Can you <strong>locate</strong> it on the map?",tip:"LOCATE = LOC(地方) + ATE",emoji:"📍",roots:["lo","cate"]},
    {word:"manage",chinese:"管理/設法",sentence:"She <strong>manage</strong>s the whole team.",tip:"MANAGE = MAN + AGE",emoji:"👩‍💼",roots:["man","age"]},
    {word:"mark",chinese:"記號/標記/分數",sentence:"Put a <strong>mark</strong> next to the answer.",tip:"MARK 和 PARK 押韻",emoji:"✅",roots:["mark"]},
    {word:"match",chinese:"比賽/配對/火柴",sentence:"The socks don't <strong>match</strong>.",tip:"MATCH 有三個意思",emoji:"🧦",roots:["match"]},
    {word:"measure",chinese:"測量",sentence:"<strong>Measure</strong> the length of the table.",tip:"MEASURE = MEAS + URE",emoji:"📏",roots:["meas","ure"]},
    {word:"mention",chinese:"提到/提及",sentence:"She <strong>mention</strong>ed your name.",tip:"MENTION = MENT + ION",emoji:"💬",roots:["men","tion"]},
    {word:"mix",chinese:"混合",sentence:"<strong>Mix</strong> the flour and eggs together.",tip:"MIX 只有三個字母",emoji:"🥣",roots:["mix"]},
    {word:"nod",chinese:"點頭",sentence:"He <strong>nod</strong>ded in agreement.",tip:"NOD 只有三個字母",emoji:"🙂",roots:["nod"]},
    {word:"obey",chinese:"服從/遵守",sentence:"You must <strong>obey</strong> the rules.",tip:"OBEY = O + BEY",emoji:"✅",roots:["o","bey"]},
    {word:"obtain",chinese:"獲得",sentence:"He <strong>obtain</strong>ed a perfect score!",tip:"OBTAIN = OB + TAIN(拿)",emoji:"🏆",roots:["ob","tain"]},
    {word:"occur",chinese:"發生",sentence:"Earthquakes <strong>occur</strong> without warning.",tip:"OCCUR 有兩個 C",emoji:"🌋",roots:["oc","cur"]},
    {word:"operate",chinese:"操作/手術",sentence:"Can you <strong>operate</strong> this machine?",tip:"OPERATE = OPER + ATE",emoji:"⚙️",roots:["op","er","ate"]},
    {word:"organize",chinese:"組織/整理",sentence:"Let me <strong>organize</strong> my desk.",tip:"ORGANIZE = ORGAN + IZE",emoji:"📋",roots:["or","gan","ize"]},
    {word:"pack",chinese:"打包/裝",sentence:"I need to <strong>pack</strong> my suitcase.",tip:"PACK 和 BACK 押韻",emoji:"🧳",roots:["pack"]},
    {word:"perform",chinese:"表演/執行",sentence:"She <strong>perform</strong>ed a beautiful dance.",tip:"PERFORM = PER + FORM",emoji:"💃",roots:["per","form"]},
    {word:"permit",chinese:"允許/許可",sentence:"Pets are not <strong>permit</strong>ted here.",tip:"PERMIT = PER + MIT(送)",emoji:"🚫",roots:["per","mit"]},
    {word:"persuade",chinese:"說服",sentence:"I <strong>persuade</strong>d her to come.",tip:"PERSUADE = PER + SUADE",emoji:"🗣️",roots:["per","suade"]},
    {word:"plant",chinese:"植物/種植",sentence:"I <strong>plant</strong>ed seeds in my garden.",tip:"PLANT 可以是名詞或動詞",emoji:"🌱",roots:["plant"]},
    {word:"plug",chinese:"插頭/插入",sentence:"<strong>Plug</strong> in the charger.",tip:"PLUG 和 MUG 押韻",emoji:"🔌",roots:["plug"]},
    {word:"pour",chinese:"倒/灌",sentence:"<strong>Pour</strong> the juice into the glass.",tip:"POUR 和 MORE 押韻",emoji:"🫗",roots:["pour"]},
    {word:"prefer",chinese:"偏好/更喜歡",sentence:"I <strong>prefer</strong> tea over coffee.",tip:"PREFER = PRE + FER(帶)",emoji:"☕",roots:["pre","fer"]},
    {word:"pretend",chinese:"假裝",sentence:"Let's <strong>pretend</strong> we are pirates!",tip:"PRETEND = PRE + TEND",emoji:"🏴‍☠️",roots:["pre","tend"]},
    {word:"prevent",chinese:"防止/預防",sentence:"Washing hands <strong>prevent</strong>s illness.",tip:"PREVENT = PRE + VENT",emoji:"🛡️",roots:["pre","vent"]},
    {word:"print",chinese:"印刷/列印",sentence:"I need to <strong>print</strong> my report.",tip:"PRINT 和 SPRINT 押韻",emoji:"🖨️",roots:["print"]},
    {word:"prove",chinese:"證明",sentence:"Can you <strong>prove</strong> it is true?",tip:"PROVE 和 MOVE 押韻",emoji:"📊",roots:["prove"]},
    {word:"publish",chinese:"出版/發表",sentence:"She <strong>publish</strong>ed her first book.",tip:"PUBLISH = PUB + LISH",emoji:"📚",roots:["pub","lish"]},
    {word:"punish",chinese:"處罰",sentence:"The teacher <strong>punish</strong>ed the cheater.",tip:"PUNISH = PUN + ISH",emoji:"😠",roots:["pun","ish"]},
    {word:"realize",chinese:"意識到/實現",sentence:"I <strong>realize</strong>d I forgot my keys.",tip:"REALIZE = REAL + IZE",emoji:"💡",roots:["re","al","ize"]},
    {word:"recognize",chinese:"認出/認識",sentence:"I <strong>recognize</strong>d her from the photo.",tip:"RECOGNIZE = RE + COGNIZE(知道)",emoji:"👀",roots:["rec","og","nize"]},
    {word:"recommend",chinese:"推薦",sentence:"I <strong>recommend</strong> this restaurant.",tip:"RECOMMEND = RE + COMMEND",emoji:"👍",roots:["rec","om","mend"]},
    {word:"reduce",chinese:"減少",sentence:"We should <strong>reduce</strong> waste.",tip:"REDUCE = RE + DUCE(帶)",emoji:"📉",roots:["re","duce"]},
    {word:"refuse",chinese:"拒絕",sentence:"She <strong>refuse</strong>d to give up.",tip:"REFUSE = RE + FUSE",emoji:"🙅",roots:["re","fuse"]},
    {word:"regret",chinese:"後悔/遺憾",sentence:"I <strong>regret</strong> not studying harder.",tip:"REGRET = RE + GRET",emoji:"😔",roots:["re","gret"]},
    {word:"reject",chinese:"拒絕/排斥",sentence:"They <strong>reject</strong>ed my proposal.",tip:"REJECT = RE + JECT(丟)",emoji:"🚫",roots:["re","ject"]},
    {word:"relate",chinese:"相關/連結",sentence:"These two stories <strong>relate</strong> to each other.",tip:"RELATE = RE + LATE",emoji:"🔗",roots:["re","late"]},
    {word:"relax",chinese:"放鬆",sentence:"<strong>Relax</strong> and enjoy the music.",tip:"RELAX = RE + LAX(鬆)",emoji:"😌",roots:["re","lax"]},
    {word:"release",chinese:"釋放/發行",sentence:"They <strong>release</strong>d the bird.",tip:"RELEASE = RE + LEASE",emoji:"🕊️",roots:["re","lease"]},
    {word:"rely",chinese:"依賴/信賴",sentence:"I <strong>rely</strong> on my parents.",tip:"RELY = RE + LY",emoji:"🤝",roots:["re","ly"]},
    {word:"remove",chinese:"移除/去除",sentence:"Please <strong>remove</strong> your shoes.",tip:"REMOVE = RE + MOVE",emoji:"🗑️",roots:["re","move"]},
    {word:"repair",chinese:"修理/修復",sentence:"He <strong>repair</strong>ed the broken chair.",tip:"REPAIR = RE + PAIR",emoji:"🔧",roots:["re","pair"]},
    {word:"repeat",chinese:"重複",sentence:"<strong>Repeat</strong> after me.",tip:"REPEAT = RE + PEAT",emoji:"🔄",roots:["re","peat"]},
    {word:"replace",chinese:"取代/更換",sentence:"I need to <strong>replace</strong> the battery.",tip:"REPLACE = RE + PLACE",emoji:"🔄",roots:["re","place"]},
    {word:"reply",chinese:"回答/回覆",sentence:"Please <strong>reply</strong> to my message.",tip:"REPLY = RE + PLY",emoji:"💬",roots:["re","ply"]},
    {word:"represent",chinese:"代表",sentence:"She <strong>represent</strong>s our class.",tip:"REPRESENT = RE + PRESENT",emoji:"🏅",roots:["rep","re","sent"]},
    {word:"request",chinese:"請求/要求",sentence:"I <strong>request</strong> a meeting.",tip:"REQUEST = RE + QUEST(尋求)",emoji:"🙏",roots:["re","quest"]},
    {word:"require",chinese:"需要/要求",sentence:"This job <strong>require</strong>s patience.",tip:"REQUIRE = RE + QUIRE(尋求)",emoji:"📋",roots:["re","quire"]},
    {word:"respect",chinese:"尊重/尊敬",sentence:"We must <strong>respect</strong> our elders.",tip:"RESPECT = RE + SPECT(看)",emoji:"🙏",roots:["re","spect"]},
    {word:"respond",chinese:"回應",sentence:"He didn't <strong>respond</strong> to my text.",tip:"RESPOND = RE + SPOND(承諾)",emoji:"💬",roots:["re","spond"]},
    {word:"rest",chinese:"休息/剩餘",sentence:"Let's <strong>rest</strong> for a while.",tip:"REST 和 BEST 押韻",emoji:"😴",roots:["rest"]},
    {word:"rob",chinese:"搶劫",sentence:"Someone tried to <strong>rob</strong> the bank.",tip:"ROB 和 JOB 押韻",emoji:"🚨",roots:["rob"]},
    {word:"roll",chinese:"滾/捲",sentence:"The ball <strong>roll</strong>ed down the hill.",tip:"ROLL 有兩個 L",emoji:"⚽",roots:["roll"]},
    {word:"rush",chinese:"衝/趕",sentence:"Don't <strong>rush</strong>, take your time.",tip:"RUSH 和 BRUSH 押韻",emoji:"🏃",roots:["rush"]},
    {word:"satisfy",chinese:"使滿足",sentence:"This meal <strong>satisfi</strong>es my hunger.",tip:"SATISFY = SAT + IS + FY",emoji:"😊",roots:["sat","is","fy"]},
    {word:"scare",chinese:"嚇/驚嚇",sentence:"The loud noise <strong>scare</strong>d me.",tip:"SCARE 和 CARE 押韻",emoji:"😱",roots:["scare"]},
    {word:"search",chinese:"搜尋/尋找",sentence:"I <strong>search</strong>ed everywhere for my keys.",tip:"SEARCH 和 RESEARCH 是一家人",emoji:"🔍",roots:["search"]},
    {word:"select",chinese:"選擇/挑選",sentence:"<strong>Select</strong> the best answer.",tip:"SELECT = SE + LECT(選)",emoji:"👆",roots:["se","lect"]},
    {word:"separate",chinese:"分開/分離",sentence:"<strong>Separate</strong> the colors from the whites.",tip:"SEPARATE 有三個 E（拼寫注意 A）",emoji:"↔️",roots:["sep","a","rate"]},
    {word:"settle",chinese:"定居/解決",sentence:"They <strong>settle</strong>d the argument calmly.",tip:"SETTLE = SET + TLE",emoji:"🏠",roots:["set","tle"]},
    {word:"shake",chinese:"搖/握手",sentence:"<strong>Shake</strong> the bottle before opening.",tip:"SHAKE 的過去式是 SHOOK",emoji:"🤝",roots:["shake"]},
    {word:"shape",chinese:"形狀/塑造",sentence:"What <strong>shape</strong> is the box?",tip:"SHAPE 和 TAPE 押韻",emoji:"🔶",roots:["shape"]},
    {word:"shout",chinese:"大喊",sentence:"Don't <strong>shout</strong> in the library!",tip:"SHOUT 和 OUT 押韻",emoji:"📢",roots:["shout"]},
    {word:"shut",chinese:"關閉",sentence:"<strong>Shut</strong> the window, it is cold.",tip:"SHUT 和 CUT 押韻",emoji:"🚪",roots:["shut"]},
    {word:"sign",chinese:"簽名/標誌",sentence:"<strong>Sign</strong> your name here.",tip:"SIGN 的 G 不發音",emoji:"✍️",roots:["sign"]},
    {word:"slip",chinese:"滑倒/溜走",sentence:"Be careful not to <strong>slip</strong> on the ice.",tip:"SLIP 和 TRIP 押韻",emoji:"🧊",roots:["slip"]},
    {word:"solve",chinese:"解決/解答",sentence:"Can you <strong>solve</strong> this puzzle?",tip:"SOLVE 和 PROBLEM 常搭配",emoji:"🧩",roots:["solve"]},
    {word:"sort",chinese:"分類/種類",sentence:"<strong>Sort</strong> the cards by color.",tip:"SORT 和 SHORT 押韻",emoji:"📊",roots:["sort"]},
    {word:"spread",chinese:"散布/塗抹",sentence:"<strong>Spread</strong> butter on the bread.",tip:"SPREAD 的過去式也是 SPREAD",emoji:"🧈",roots:["spread"]},
    {word:"steal",chinese:"偷",sentence:"It is wrong to <strong>steal</strong>.",tip:"STEAL 的過去式是 STOLE",emoji:"🚫",roots:["steal"]},
    {word:"stick",chinese:"棍子/黏貼/伸出",sentence:"<strong>Stick</strong> the poster on the wall.",tip:"STICK 和 KICK 押韻",emoji:"📌",roots:["stick"]},
    {word:"stretch",chinese:"伸展",sentence:"<strong>Stretch</strong> your arms above your head.",tip:"STRETCH = STR + ETCH",emoji:"🧘",roots:["stretch"]},
    {word:"strike",chinese:"打/罷工/擊中",sentence:"Lightning <strong>struck</strong> the tree.",tip:"STRIKE 的過去式是 STRUCK",emoji:"⚡",roots:["strike"]},
    {word:"struggle",chinese:"掙扎/奮鬥",sentence:"I <strong>struggle</strong> with math sometimes.",tip:"STRUGGLE = STRUGG + LE",emoji:"💪",roots:["strug","gle"]},
    {word:"succeed",chinese:"成功",sentence:"If you try hard, you will <strong>succeed</strong>.",tip:"SUCCEED = SUC + CEED(走)",emoji:"🏆",roots:["suc","ceed"]},
    {word:"suffer",chinese:"受苦/遭受",sentence:"Many people <strong>suffer</strong> from allergies.",tip:"SUFFER = SUF + FER",emoji:"😣",roots:["suf","fer"]},
    {word:"supply",chinese:"供應/供給",sentence:"The store <strong>suppli</strong>es fresh vegetables.",tip:"SUPPLY = SUP + PLY",emoji:"📦",roots:["sup","ply"]},
    {word:"support",chinese:"支持/支撐",sentence:"I <strong>support</strong> your decision.",tip:"SUPPORT = SUP + PORT",emoji:"💪",roots:["sup","port"]},
    {word:"survive",chinese:"生存/存活",sentence:"Plants cannot <strong>survive</strong> without water.",tip:"SURVIVE = SUR + VIVE(活)",emoji:"🌱",roots:["sur","vive"]},
    {word:"suspect",chinese:"懷疑/嫌疑犯",sentence:"I <strong>suspect</strong> he is hiding something.",tip:"SUSPECT = SUS + PECT(看)",emoji:"🤨",roots:["sus","pect"]},
    {word:"swap",chinese:"交換",sentence:"Let's <strong>swap</strong> stickers!",tip:"SWAP 和 STOP 押韻",emoji:"🔄",roots:["swap"]},
    {word:"tear",chinese:"撕/眼淚",sentence:"Don't <strong>tear</strong> the paper!",tip:"TEAR 有兩個意思和兩個發音",emoji:"📃",roots:["tear"]},
    {word:"threaten",chinese:"威脅",sentence:"The bully <strong>threaten</strong>ed the younger kids.",tip:"THREATEN = THREAT + EN",emoji:"😠",roots:["threat","en"]},
    {word:"trade",chinese:"交易/貿易",sentence:"Let's <strong>trade</strong> cards.",tip:"TRADE 和 MADE 押韻",emoji:"🤝",roots:["trade"]},
    {word:"trap",chinese:"陷阱/困住",sentence:"The mouse got caught in a <strong>trap</strong>.",tip:"TRAP 和 MAP 押韻",emoji:"🪤",roots:["trap"]},
    {word:"treat",chinese:"對待/款待/治療",sentence:"<strong>Treat</strong> others kindly.",tip:"TREAT 有好幾個意思",emoji:"🍭",roots:["treat"]},
    {word:"trust",chinese:"信任",sentence:"I <strong>trust</strong> my best friend.",tip:"TRUST 和 MUST 押韻",emoji:"🤝",roots:["trust"]},
    {word:"vary",chinese:"變化/不同",sentence:"Prices <strong>vary</strong> from store to store.",tip:"VARY 的名詞是 VARIETY",emoji:"🔀",roots:["var","y"]},
    {word:"warn",chinese:"警告",sentence:"I <strong>warn</strong>ed you to be careful.",tip:"WARN 和 WARM 很像",emoji:"⚠️",roots:["warn"]},
    {word:"waste",chinese:"浪費/廢物",sentence:"Don't <strong>waste</strong> food.",tip:"WASTE 和 TASTE 押韻",emoji:"🗑️",roots:["waste"]},
    {word:"weigh",chinese:"稱重/重量",sentence:"How much do you <strong>weigh</strong>?",tip:"WEIGH 的 GH 不發音",emoji:"⚖️",roots:["weigh"]},
    {word:"wrap",chinese:"包裝",sentence:"<strong>Wrap</strong> the gift with nice paper.",tip:"WRAP 的 W 不發音",emoji:"🎁",roots:["wrap"]},
    {word:"advantage",chinese:"優勢/好處",sentence:"Being tall is an <strong>advantage</strong> in basketball.",tip:"ADVANTAGE = AD + VANT + AGE",emoji:"💪",roots:["ad","vant","age"]},
    {word:"adventure",chinese:"冒險",sentence:"We went on a great <strong>adventure</strong>.",tip:"ADVENTURE = AD + VENTURE",emoji:"🗺️",roots:["ad","ven","ture"]},
    {word:"amount",chinese:"數量/金額",sentence:"A large <strong>amount</strong> of water fell.",tip:"AMOUNT = A + MOUNT",emoji:"📊",roots:["a","mount"]},
    {word:"audience",chinese:"觀眾/聽眾",sentence:"The <strong>audience</strong> clapped loudly.",tip:"AUDIENCE = AUDI(聽) + ENCE",emoji:"👏",roots:["au","di","ence"]},
    {word:"battle",chinese:"戰鬥/戰役",sentence:"The chess <strong>battle</strong> was exciting.",tip:"BATTLE = BAT + TLE",emoji:"⚔️",roots:["bat","tle"]},
    {word:"benefit",chinese:"利益/好處",sentence:"Exercise has many <strong>benefit</strong>s.",tip:"BENEFIT = BENE(好) + FIT",emoji:"💪",roots:["ben","e","fit"]},
    {word:"brain",chinese:"大腦",sentence:"Use your <strong>brain</strong> to solve this!",tip:"BRAIN 和 TRAIN 押韻",emoji:"🧠",roots:["brain"]},
    {word:"budget",chinese:"預算",sentence:"We have a limited <strong>budget</strong>.",tip:"BUDGET = BUDG + ET",emoji:"💰",roots:["budg","et"]},
    {word:"captain",chinese:"隊長/船長",sentence:"She is the <strong>captain</strong> of the team.",tip:"CAPTAIN = CAPT + AIN",emoji:"👩‍✈️",roots:["cap","tain"]},
    {word:"career",chinese:"職業/事業",sentence:"What <strong>career</strong> do you want?",tip:"CAREER 有兩個 E",emoji:"💼",roots:["ca","reer"]},
    {word:"century",chinese:"世紀",sentence:"We live in the 21st <strong>century</strong>.",tip:"CENTURY = CENT(百) + URY",emoji:"📅",roots:["cen","tu","ry"]},
    {word:"challenge",chinese:"挑戰",sentence:"I accept the <strong>challenge</strong>!",tip:"CHALLENGE = CHALL + ENGE",emoji:"🏆",roots:["chal","lenge"]},
    {word:"chapter",chinese:"章節",sentence:"Read <strong>chapter</strong> three tonight.",tip:"CHAPTER = CHAPT + ER",emoji:"📖",roots:["chap","ter"]},
    {word:"character",chinese:"角色/性格",sentence:"Who is your favorite <strong>character</strong>?",tip:"CHARACTER = CHAR + ACT + ER",emoji:"🎭",roots:["char","ac","ter"]},
    {word:"climate",chinese:"氣候",sentence:"The <strong>climate</strong> here is warm.",tip:"CLIMATE = CLIM + ATE",emoji:"🌡️",roots:["cli","mate"]},
    {word:"coast",chinese:"海岸",sentence:"We live near the <strong>coast</strong>.",tip:"COAST 和 TOAST 押韻",emoji:"🏖️",roots:["coast"]},
    {word:"comment",chinese:"評論/留言",sentence:"Do you have any <strong>comment</strong>s?",tip:"COMMENT = COM + MENT",emoji:"💬",roots:["com","ment"]},
    {word:"communication",chinese:"溝通/通訊",sentence:"Good <strong>communication</strong> is important.",tip:"COMMUNICATION = COMMUN + IC + ATION",emoji:"📱",roots:["com","muni","cation"]},
    {word:"community",chinese:"社區/社群",sentence:"Our <strong>community</strong> helps each other.",tip:"COMMUNITY = COM + MUNITY",emoji:"🏘️",roots:["com","mu","ni","ty"]},
    {word:"competition",chinese:"競爭/比賽",sentence:"I joined a spelling <strong>competition</strong>.",tip:"COMPETITION = COMPET + ITION",emoji:"🏅",roots:["com","pe","ti","tion"]},
    {word:"condition",chinese:"條件/狀況",sentence:"The road is in bad <strong>condition</strong>.",tip:"CONDITION = CON + DITION",emoji:"📋",roots:["con","di","tion"]},
    {word:"conflict",chinese:"衝突",sentence:"We need to resolve this <strong>conflict</strong>.",tip:"CONFLICT = CON + FLICT(打)",emoji:"⚡",roots:["con","flict"]},
    {word:"contrast",chinese:"對比/相反",sentence:"The <strong>contrast</strong> is very clear.",tip:"CONTRAST = CON + TRAST",emoji:"↔️",roots:["con","trast"]},
    {word:"conversation",chinese:"對話/談話",sentence:"We had a nice <strong>conversation</strong>.",tip:"CONVERSATION = CON + VERS + ATION",emoji:"💬",roots:["con","ver","sa","tion"]},
    {word:"corner",chinese:"角落/轉角",sentence:"The store is around the <strong>corner</strong>.",tip:"CORNER = CORN + ER",emoji:"📐",roots:["cor","ner"]},
    {word:"courage",chinese:"勇氣",sentence:"It takes <strong>courage</strong> to try new things.",tip:"COURAGE = COUR(心) + AGE",emoji:"🦁",roots:["cour","age"]},
    {word:"creature",chinese:"生物",sentence:"We saw a strange <strong>creature</strong> in the pond.",tip:"CREATURE = CREAT(創造) + URE",emoji:"🦎",roots:["crea","ture"]},
    {word:"crime",chinese:"犯罪",sentence:"<strong>Crime</strong> does not pay.",tip:"CRIME 和 TIME 押韻",emoji:"🚨",roots:["crime"]},
    {word:"crowd",chinese:"人群",sentence:"A large <strong>crowd</strong> gathered in the park.",tip:"CROWD 和 LOUD 押韻",emoji:"👥",roots:["crowd"]},
    {word:"custom",chinese:"風俗/習慣",sentence:"It is a <strong>custom</strong> to shake hands.",tip:"CUSTOM = CUST + OM",emoji:"🤝",roots:["cust","om"]},
    {word:"debate",chinese:"辯論/討論",sentence:"We had a <strong>debate</strong> about the topic.",tip:"DEBATE = DE + BATE",emoji:"🗣️",roots:["de","bate"]},
    {word:"detail",chinese:"細節",sentence:"Pay attention to every <strong>detail</strong>.",tip:"DETAIL = DE + TAIL",emoji:"🔍",roots:["de","tail"]},
    {word:"device",chinese:"裝置/設備",sentence:"This <strong>device</strong> is very useful.",tip:"DEVICE = DE + VICE",emoji:"📱",roots:["de","vice"]},
    {word:"disaster",chinese:"災難",sentence:"The flood was a terrible <strong>disaster</strong>.",tip:"DISASTER = DIS + ASTER(星)",emoji:"🌊",roots:["dis","as","ter"]},
    {word:"distance",chinese:"距離",sentence:"The <strong>distance</strong> is about five miles.",tip:"DISTANCE = DIS + TANCE",emoji:"📏",roots:["dis","tance"]},
    {word:"education",chinese:"教育",sentence:"<strong>Education</strong> is very important.",tip:"EDUCATION = EDUC + ATION",emoji:"🎓",roots:["ed","u","ca","tion"]},
    {word:"effect",chinese:"效果/影響",sentence:"The medicine had a good <strong>effect</strong>.",tip:"EFFECT = EF + FECT",emoji:"✨",roots:["ef","fect"]},
    {word:"emotion",chinese:"情緒/情感",sentence:"She showed strong <strong>emotion</strong>.",tip:"EMOTION = E + MOTION",emoji:"😢",roots:["e","mo","tion"]},
    {word:"enemy",chinese:"敵人",sentence:"The hero defeated his <strong>enemy</strong>.",tip:"ENEMY = EN + E + MY",emoji:"😈",roots:["en","e","my"]},
    {word:"energy",chinese:"能量/精力",sentence:"I have a lot of <strong>energy</strong> today!",tip:"ENERGY = EN + ERG(工作) + Y",emoji:"⚡",roots:["en","er","gy"]},
    {word:"environment",chinese:"環境",sentence:"Protect the <strong>environment</strong>!",tip:"ENVIRONMENT = EN + VIRON + MENT",emoji:"🌍",roots:["en","viron","ment"]},
    {word:"equipment",chinese:"設備/器材",sentence:"We need sports <strong>equipment</strong>.",tip:"EQUIPMENT = EQUIP + MENT",emoji:"🏋️",roots:["e","quip","ment"]},
    {word:"event",chinese:"事件/活動",sentence:"The school <strong>event</strong> was fun!",tip:"EVENT = E + VENT",emoji:"🎪",roots:["e","vent"]},
    {word:"evidence",chinese:"證據",sentence:"There is no <strong>evidence</strong> of that.",tip:"EVIDENCE = EVI + DENCE",emoji:"🔍",roots:["ev","i","dence"]},
    {word:"feature",chinese:"特色/特徵",sentence:"What is the best <strong>feature</strong> of this phone?",tip:"FEATURE = FEAT + URE",emoji:"⭐",roots:["fea","ture"]},
    {word:"fee",chinese:"費用",sentence:"The entrance <strong>fee</strong> is five dollars.",tip:"FEE 有兩個 E",emoji:"💰",roots:["fee"]},
    {word:"figure",chinese:"數字/人物/身材",sentence:"She is a famous <strong>figure</strong> in science.",tip:"FIGURE = FIG + URE",emoji:"👤",roots:["fig","ure"]},
    {word:"fortune",chinese:"財富/運氣",sentence:"She made a <strong>fortune</strong> selling books.",tip:"FORTUNE = FORT + UNE",emoji:"💰",roots:["for","tune"]},
    {word:"furniture",chinese:"家具",sentence:"We bought new <strong>furniture</strong>.",tip:"FURNITURE = FURNIT + URE",emoji:"🛋️",roots:["fur","ni","ture"]},
    {word:"generation",chinese:"世代/一代",sentence:"Each <strong>generation</strong> is different.",tip:"GENERATION = GENER + ATION",emoji:"👶👧👩👵",roots:["gen","er","a","tion"]},
    {word:"goal",chinese:"目標/球門",sentence:"My <strong>goal</strong> is to read 50 books.",tip:"GOAL 和 ROLE 押韻",emoji:"🥅",roots:["goal"]},
    {word:"habit",chinese:"習慣",sentence:"Reading is a good <strong>habit</strong>.",tip:"HABIT = HAB + IT",emoji:"📅",roots:["hab","it"]},
    {word:"harm",chinese:"傷害/危害",sentence:"Pollution does <strong>harm</strong> to animals.",tip:"HARM 和 FARM 押韻",emoji:"⚠️",roots:["harm"]},
    {word:"health",chinese:"健康",sentence:"<strong>Health</strong> is the most important thing.",tip:"HEALTH = HEAL + TH",emoji:"❤️",roots:["heal","th"]},
    {word:"hero",chinese:"英雄",sentence:"She is my <strong>hero</strong>!",tip:"HERO 的複數是 HEROES",emoji:"🦸",roots:["he","ro"]},
    {word:"humor",chinese:"幽默",sentence:"He has a great sense of <strong>humor</strong>.",tip:"HUMOR = HUM + OR",emoji:"😂",roots:["hu","mor"]},
    {word:"income",chinese:"收入",sentence:"Their <strong>income</strong> increased this year.",tip:"INCOME = IN + COME",emoji:"💵",roots:["in","come"]},
    {word:"industry",chinese:"工業/產業",sentence:"The tech <strong>industry</strong> grows fast.",tip:"INDUSTRY = IN + DUST + RY",emoji:"🏭",roots:["in","dus","try"]},
    {word:"injury",chinese:"傷害/受傷",sentence:"The <strong>injury</strong> healed quickly.",tip:"INJURY = IN + JURY",emoji:"🤕",roots:["in","ju","ry"]},
    {word:"insect",chinese:"昆蟲",sentence:"A butterfly is a beautiful <strong>insect</strong>.",tip:"INSECT = IN + SECT(切)",emoji:"🦋",roots:["in","sect"]},
    {word:"island",chinese:"島嶼",sentence:"We took a boat to the <strong>island</strong>.",tip:"ISLAND 的 S 不發音",emoji:"🏝️",roots:["is","land"]},
    {word:"journey",chinese:"旅程",sentence:"The <strong>journey</strong> took three hours.",tip:"JOURNEY = JOURN(日) + EY",emoji:"🧳",roots:["jour","ney"]},
    {word:"justice",chinese:"正義/公正",sentence:"We must fight for <strong>justice</strong>.",tip:"JUSTICE = JUST + ICE",emoji:"⚖️",roots:["just","ice"]},
    {word:"knowledge",chinese:"知識",sentence:"<strong>Knowledge</strong> is power!",tip:"KNOWLEDGE = KNOW + LEDGE",emoji:"📚",roots:["know","ledge"]},
    {word:"labor",chinese:"勞動/努力",sentence:"Building a house takes hard <strong>labor</strong>.",tip:"LABOR = LAB + OR",emoji:"👷",roots:["la","bor"]},
    {word:"layer",chinese:"層",sentence:"Add another <strong>layer</strong> of paint.",tip:"LAYER = LAY + ER",emoji:"🎨",roots:["lay","er"]},
    {word:"leaf",chinese:"葉子",sentence:"A <strong>leaf</strong> fell from the tree.",tip:"LEAF 的複數是 LEAVES",emoji:"🍃",roots:["leaf"]},
    {word:"lesson",chinese:"課/教訓",sentence:"I learned an important <strong>lesson</strong>.",tip:"LESSON = LESS + ON",emoji:"📖",roots:["les","son"]},
    {word:"log",chinese:"木頭/記錄",sentence:"Sit on this <strong>log</strong>.",tip:"LOG 和 DOG 押韻",emoji:"🪵",roots:["log"]},
    {word:"manner",chinese:"方式/禮貌",sentence:"Always use good <strong>manner</strong>s.",tip:"MANNER 有兩個 N",emoji:"🙏",roots:["man","ner"]},
    {word:"mass",chinese:"大量/質量",sentence:"A <strong>mass</strong> of clouds covered the sky.",tip:"MASS 有兩個 S",emoji:"☁️",roots:["mass"]},
    {word:"material",chinese:"材料/物質",sentence:"What <strong>material</strong> is this made of?",tip:"MATERIAL = MATER + IAL",emoji:"🧱",roots:["ma","ter","i","al"]},
    {word:"medicine",chinese:"藥/醫學",sentence:"Take your <strong>medicine</strong> after meals.",tip:"MEDICINE = MEDI(治療) + CINE",emoji:"💊",roots:["med","i","cine"]},
    {word:"memory",chinese:"記憶/回憶",sentence:"I have a good <strong>memory</strong> of that day.",tip:"MEMORY = MEM + ORY",emoji:"🧠",roots:["mem","o","ry"]},
    {word:"message",chinese:"訊息/消息",sentence:"I got your <strong>message</strong>.",tip:"MESSAGE = MESS + AGE",emoji:"💬",roots:["mes","sage"]},
    {word:"method",chinese:"方法",sentence:"This <strong>method</strong> works best.",tip:"METHOD = METH + OD",emoji:"📋",roots:["meth","od"]},
    {word:"mood",chinese:"心情/情緒",sentence:"I am in a good <strong>mood</strong> today!",tip:"MOOD 有兩個 O",emoji:"😊",roots:["mood"]},
    {word:"mystery",chinese:"神秘/謎",sentence:"The disappearance is a <strong>mystery</strong>.",tip:"MYSTERY = MYST + ERY",emoji:"🔮",roots:["mys","ter","y"]},
    {word:"nation",chinese:"國家",sentence:"People across the <strong>nation</strong> celebrated.",tip:"NATION = NAT(出生) + ION",emoji:"🏳️",roots:["na","tion"]},
    {word:"neighbor",chinese:"鄰居",sentence:"Our <strong>neighbor</strong> is very friendly.",tip:"NEIGHBOR = NEIGH + BOR",emoji:"🏘️",roots:["neigh","bor"]},
    {word:"object",chinese:"物體/目標/反對",sentence:"What is that <strong>object</strong>?",tip:"OBJECT 當名詞和動詞重音不同",emoji:"🔮",roots:["ob","ject"]},
    {word:"ocean",chinese:"海洋",sentence:"The <strong>ocean</strong> is deep and wide.",tip:"OCEAN 有兩個音節",emoji:"🌊",roots:["o","cean"]},
    {word:"opinion",chinese:"意見/看法",sentence:"What is your <strong>opinion</strong>?",tip:"OPINION = O + PIN + ION",emoji:"💭",roots:["o","pin","ion"]},
    {word:"opportunity",chinese:"機會",sentence:"This is a great <strong>opportunity</strong>!",tip:"OPPORTUNITY = OP + PORT + UNITY",emoji:"🌟",roots:["op","por","tu","ni","ty"]},
    {word:"pain",chinese:"疼痛/痛苦",sentence:"I feel <strong>pain</strong> in my knee.",tip:"PAIN 和 RAIN 押韻",emoji:"😣",roots:["pain"]},
    {word:"partner",chinese:"夥伴/搭檔",sentence:"She is my lab <strong>partner</strong>.",tip:"PARTNER = PART + NER",emoji:"🤝",roots:["part","ner"]},
    {word:"passenger",chinese:"乘客",sentence:"All <strong>passenger</strong>s must wear seatbelts.",tip:"PASSENGER = PASS + ENGER",emoji:"✈️",roots:["pas","sen","ger"]},
    {word:"path",chinese:"小路/途徑",sentence:"Follow the <strong>path</strong> through the woods.",tip:"PATH 和 MATH 押韻",emoji:"🛤️",roots:["path"]},
    {word:"pattern",chinese:"圖案/模式",sentence:"I like the <strong>pattern</strong> on this dress.",tip:"PATTERN = PAT + TERN",emoji:"🎨",roots:["pat","tern"]},
    {word:"period",chinese:"期間/句號",sentence:"The class <strong>period</strong> is 45 minutes.",tip:"PERIOD = PERI(周圍) + OD",emoji:"⏰",roots:["per","i","od"]},
    {word:"permission",chinese:"許可/允許",sentence:"I got <strong>permission</strong> to go.",tip:"PERMISSION = PER + MISS + ION",emoji:"✅",roots:["per","mis","sion"]},
    {word:"planet",chinese:"行星",sentence:"Earth is our <strong>planet</strong>.",tip:"PLANET = PLAN + ET",emoji:"🌍",roots:["plan","et"]},
    {word:"pleasure",chinese:"快樂/樂事",sentence:"It is a <strong>pleasure</strong> to meet you.",tip:"PLEASURE = PLEAS + URE",emoji:"😊",roots:["pleas","ure"]},
    {word:"poem",chinese:"詩",sentence:"She wrote a beautiful <strong>poem</strong>.",tip:"POEM 有兩個音節",emoji:"📜",roots:["po","em"]},
    {word:"poison",chinese:"毒藥/毒素",sentence:"Some mushrooms contain <strong>poison</strong>.",tip:"POISON = POI + SON",emoji:"☠️",roots:["poi","son"]},
    {word:"population",chinese:"人口",sentence:"The city's <strong>population</strong> is growing.",tip:"POPULATION = POPUL + ATION",emoji:"👥",roots:["pop","u","la","tion"]},
    {word:"position",chinese:"位置/職位",sentence:"What <strong>position</strong> do you play?",tip:"POSITION = POS + ITION",emoji:"📍",roots:["po","si","tion"]},
    {word:"prize",chinese:"獎品/獎",sentence:"She won first <strong>prize</strong>!",tip:"PRIZE 和 SURPRISE 是一家人",emoji:"🏆",roots:["prize"]},
    {word:"process",chinese:"過程/流程",sentence:"Learning is a long <strong>process</strong>.",tip:"PROCESS = PRO + CESS(走)",emoji:"⚙️",roots:["pro","cess"]},
    {word:"profit",chinese:"利潤/獲利",sentence:"The store made a good <strong>profit</strong>.",tip:"PROFIT = PRO + FIT",emoji:"💰",roots:["prof","it"]},
    {word:"progress",chinese:"進步/進展",sentence:"You are making great <strong>progress</strong>!",tip:"PROGRESS = PRO + GRESS(走)",emoji:"📈",roots:["pro","gress"]},
    {word:"purpose",chinese:"目的/用途",sentence:"What is the <strong>purpose</strong> of this tool?",tip:"PURPOSE = PUR + POSE",emoji:"🎯",roots:["pur","pose"]},
    {word:"quality",chinese:"品質/質量",sentence:"This product has high <strong>quality</strong>.",tip:"QUALITY = QUAL + ITY",emoji:"⭐",roots:["qual","i","ty"]},
    {word:"quantity",chinese:"數量",sentence:"We need a large <strong>quantity</strong> of paper.",tip:"QUANTITY = QUANT + ITY",emoji:"📊",roots:["quan","ti","ty"]},
    {word:"recipe",chinese:"食譜",sentence:"Follow the <strong>recipe</strong> carefully.",tip:"RECIPE = REC + I + PE",emoji:"📖",roots:["rec","i","pe"]},
    {word:"region",chinese:"地區/區域",sentence:"This <strong>region</strong> has cold winters.",tip:"REGION = REG + ION",emoji:"🗺️",roots:["re","gion"]},
    {word:"reward",chinese:"獎勵/回報",sentence:"Hard work brings great <strong>reward</strong>s.",tip:"REWARD = RE + WARD",emoji:"🏆",roots:["re","ward"]},
    {word:"risk",chinese:"風險/冒險",sentence:"There is a <strong>risk</strong> of falling.",tip:"RISK 和 DISK 押韻",emoji:"⚠️",roots:["risk"]},
    {word:"role",chinese:"角色/作用",sentence:"What is your <strong>role</strong> in the play?",tip:"ROLE 和 GOAL 押韻",emoji:"🎭",roots:["role"]},
    {word:"rule",chinese:"規則",sentence:"Follow the <strong>rule</strong>s of the game.",tip:"RULE 和 COOL 押韻",emoji:"📋",roots:["rule"]},
    {word:"scene",chinese:"場景/現場",sentence:"The mountain <strong>scene</strong> is beautiful.",tip:"SCENE 的 C 不發音",emoji:"🏔️",roots:["scene"]},
    {word:"score",chinese:"分數/得分",sentence:"I got a high <strong>score</strong> on the test.",tip:"SCORE 和 MORE 押韻",emoji:"💯",roots:["score"]},
    {word:"season",chinese:"季節",sentence:"What is your favorite <strong>season</strong>?",tip:"SEASON = SEA + SON",emoji:"🌸",roots:["sea","son"]},
    {word:"section",chinese:"部分/區域",sentence:"Read the first <strong>section</strong>.",tip:"SECTION = SECT(切) + ION",emoji:"📄",roots:["sec","tion"]},
    {word:"seed",chinese:"種子",sentence:"Plant the <strong>seed</strong> in the soil.",tip:"SEED 有兩個 E",emoji:"🌱",roots:["seed"]},
    {word:"shadow",chinese:"影子/陰影",sentence:"My <strong>shadow</strong> follows me everywhere.",tip:"SHADOW = SHAD + OW",emoji:"👤",roots:["shad","ow"]},
    {word:"signal",chinese:"信號/暗號",sentence:"Wait for my <strong>signal</strong>.",tip:"SIGNAL = SIGN + AL",emoji:"🚦",roots:["sig","nal"]},
    {word:"skill",chinese:"技能/技巧",sentence:"Reading is an important <strong>skill</strong>.",tip:"SKILL 有兩個 L",emoji:"🎯",roots:["skill"]},
    {word:"society",chinese:"社會",sentence:"We live in a modern <strong>society</strong>.",tip:"SOCIETY = SOC + IETY",emoji:"🏙️",roots:["so","ci","ety"]},
    {word:"solution",chinese:"解決方法/溶液",sentence:"We found a <strong>solution</strong> to the problem.",tip:"SOLUTION = SOLUT + ION",emoji:"💡",roots:["so","lu","tion"]},
    {word:"source",chinese:"來源/源頭",sentence:"The sun is our main <strong>source</strong> of light.",tip:"SOURCE = SOUR + CE",emoji:"☀️",roots:["source"]},
    {word:"space",chinese:"空間/太空",sentence:"Astronauts travel to <strong>space</strong>.",tip:"SPACE 和 PLACE 押韻",emoji:"🚀",roots:["space"]},
    {word:"speech",chinese:"演講/說話",sentence:"She gave a wonderful <strong>speech</strong>.",tip:"SPEECH = SPEE + CH",emoji:"🎤",roots:["speech"]},
    {word:"spirit",chinese:"精神/靈魂",sentence:"Team <strong>spirit</strong> helps us win.",tip:"SPIRIT = SPIR(呼吸) + IT",emoji:"✨",roots:["spir","it"]},
    {word:"stage",chinese:"舞台/階段",sentence:"The singer walked onto the <strong>stage</strong>.",tip:"STAGE 和 AGE 押韻",emoji:"🎭",roots:["stage"]},
    {word:"standard",chinese:"標準",sentence:"We must meet high <strong>standard</strong>s.",tip:"STANDARD = STAND + ARD",emoji:"📏",roots:["stand","ard"]},
    {word:"stranger",chinese:"陌生人",sentence:"Never talk to a <strong>stranger</strong>.",tip:"STRANGER = STRANGE + R",emoji:"🚫",roots:["strang","er"]},
    {word:"strength",chinese:"力量/優點",sentence:"Teamwork is our <strong>strength</strong>.",tip:"STRENGTH = STRENG + TH",emoji:"💪",roots:["streng","th"]},
    {word:"structure",chinese:"結構/建築物",sentence:"The <strong>structure</strong> is made of wood.",tip:"STRUCTURE = STRUCT(建) + URE",emoji:"🏗️",roots:["struct","ure"]},
    {word:"surface",chinese:"表面",sentence:"The <strong>surface</strong> of the lake is smooth.",tip:"SURFACE = SUR + FACE",emoji:"🌊",roots:["sur","face"]},
    {word:"symbol",chinese:"符號/象徵",sentence:"The dove is a <strong>symbol</strong> of peace.",tip:"SYMBOL = SYM + BOL",emoji:"🕊️",roots:["sym","bol"]},
    {word:"talent",chinese:"才能/天賦",sentence:"She has a <strong>talent</strong> for singing.",tip:"TALENT = TAL + ENT",emoji:"🌟",roots:["tal","ent"]},
    {word:"task",chinese:"任務/工作",sentence:"I finished the <strong>task</strong> quickly.",tip:"TASK 和 ASK 押韻",emoji:"📋",roots:["task"]},
    {word:"technology",chinese:"科技",sentence:"<strong>Technology</strong> changes our lives.",tip:"TECHNOLOGY = TECHNO + LOGY(學)",emoji:"💻",roots:["tech","no","lo","gy"]},
    {word:"temperature",chinese:"溫度",sentence:"The <strong>temperature</strong> dropped at night.",tip:"TEMPERATURE = TEMPER + ATURE",emoji:"🌡️",roots:["tem","per","a","ture"]},
    {word:"theory",chinese:"理論",sentence:"That is just a <strong>theory</strong>.",tip:"THEORY = THE + ORY",emoji:"🧪",roots:["the","o","ry"]},
    {word:"title",chinese:"標題/頭銜",sentence:"What is the <strong>title</strong> of the book?",tip:"TITLE = TIT + LE",emoji:"📰",roots:["ti","tle"]},
    {word:"tool",chinese:"工具",sentence:"A hammer is a useful <strong>tool</strong>.",tip:"TOOL 有兩個 O",emoji:"🔧",roots:["tool"]},
    {word:"topic",chinese:"主題/話題",sentence:"What is today's <strong>topic</strong>?",tip:"TOPIC = TOP + IC",emoji:"📌",roots:["top","ic"]},
    {word:"tradition",chinese:"傳統",sentence:"It is a family <strong>tradition</strong>.",tip:"TRADITION = TRADIT + ION",emoji:"🎄",roots:["tra","di","tion"]},
    {word:"traffic",chinese:"交通",sentence:"The <strong>traffic</strong> is heavy today.",tip:"TRAFFIC 有兩個 F",emoji:"🚗",roots:["traf","fic"]},
    {word:"treasure",chinese:"寶藏/珍惜",sentence:"The pirate found the <strong>treasure</strong>.",tip:"TREASURE = TREAS + URE",emoji:"💎",roots:["treas","ure"]},
    {word:"trouble",chinese:"麻煩/問題",sentence:"I don't want any <strong>trouble</strong>.",tip:"TROUBLE = TROUB + LE",emoji:"😟",roots:["troub","le"]},
    {word:"variety",chinese:"多樣性/品種",sentence:"There is a <strong>variety</strong> of choices.",tip:"VARIETY = VARI + ETY",emoji:"🌈",roots:["va","ri","ety"]},
    {word:"version",chinese:"版本",sentence:"This is the newest <strong>version</strong>.",tip:"VERSION = VERS + ION",emoji:"📱",roots:["ver","sion"]},
    {word:"victory",chinese:"勝利",sentence:"We celebrated our <strong>victory</strong>!",tip:"VICTORY = VICT(贏) + ORY",emoji:"🏆",roots:["vic","to","ry"]},
    {word:"view",chinese:"風景/觀點",sentence:"The <strong>view</strong> from here is amazing.",tip:"VIEW 和 FEW 押韻",emoji:"🌄",roots:["view"]},
    {word:"village",chinese:"村莊",sentence:"I grew up in a small <strong>village</strong>.",tip:"VILLAGE = VILL + AGE",emoji:"🏘️",roots:["vill","age"]},
    {word:"wealth",chinese:"財富",sentence:"Health is more important than <strong>wealth</strong>.",tip:"WEALTH = WEAL + TH",emoji:"💰",roots:["weal","th"]},
    {word:"weapon",chinese:"武器",sentence:"Words can be a powerful <strong>weapon</strong>.",tip:"WEAPON = WEAP + ON",emoji:"⚔️",roots:["weap","on"]},
    {word:"wing",chinese:"翅膀",sentence:"The bird spread its <strong>wing</strong>s and flew.",tip:"WING 和 SING 押韻",emoji:"🦅",roots:["wing"]},
    {word:"wisdom",chinese:"智慧",sentence:"My grandmother shares her <strong>wisdom</strong>.",tip:"WISDOM = WIS + DOM",emoji:"🦉",roots:["wis","dom"]},
    {word:"anxiety",chinese:"焦慮/不安",sentence:"She felt <strong>anxiety</strong> before the speech.",tip:"ANXIETY = ANX + IETY",emoji:"😰",roots:["anx","i","ety"]},
    {word:"approach",chinese:"接近/方法",sentence:"We need a different <strong>approach</strong>.",tip:"APPROACH = AP + PROACH",emoji:"🚶",roots:["ap","proach"]},
    {word:"aspect",chinese:"方面/觀點",sentence:"Consider every <strong>aspect</strong> of the problem.",tip:"ASPECT = A + SPECT(看)",emoji:"🔍",roots:["a","spect"]},
    {word:"assign",chinese:"分配/指派",sentence:"The teacher <strong>assign</strong>ed homework.",tip:"ASSIGN = AS + SIGN",emoji:"📝",roots:["as","sign"]},
    {word:"atmosphere",chinese:"氣氛/大氣",sentence:"The <strong>atmosphere</strong> at the party was fun.",tip:"ATMOSPHERE = ATMO + SPHERE(球)",emoji:"🌍",roots:["at","mo","sphere"]},
    {word:"attitude",chinese:"態度",sentence:"A positive <strong>attitude</strong> helps you succeed.",tip:"ATTITUDE = ATT + ITUDE",emoji:"😊",roots:["at","ti","tude"]},
    {word:"bare",chinese:"赤裸的/光禿的",sentence:"He walked on the beach with <strong>bare</strong> feet.",tip:"BARE 和 CARE 押韻",emoji:"🦶",roots:["bare"]},
    {word:"basis",chinese:"基礎/根據",sentence:"On what <strong>basis</strong> did you decide?",tip:"BASIS = BAS + IS",emoji:"🧱",roots:["ba","sis"]},
    {word:"block",chinese:"街區/阻擋/積木",sentence:"Walk two <strong>block</strong>s to the right.",tip:"BLOCK 有多個意思",emoji:"🧱",roots:["block"]},
    {word:"bond",chinese:"紐帶/聯繫",sentence:"The <strong>bond</strong> between friends is strong.",tip:"BOND 和 FOND 押韻",emoji:"🤝",roots:["bond"]},
    {word:"border",chinese:"邊界/邊緣",sentence:"We crossed the <strong>border</strong> into Canada.",tip:"BORDER = BORD + ER",emoji:"🗺️",roots:["bor","der"]},
    {word:"breast",chinese:"胸部/胸膛",sentence:"She held the baby to her <strong>breast</strong>.",tip:"BREAST 和 BEST 押韻",emoji:"❤️",roots:["breast"]},
    {word:"broad",chinese:"寬闘的/廣泛的",sentence:"The river is very <strong>broad</strong> here.",tip:"BROAD 和 WIDE 意思相近",emoji:"↔️",roots:["broad"]},
    {word:"cable",chinese:"電纜/纜線",sentence:"Connect the <strong>cable</strong> to the TV.",tip:"CABLE = CAB + LE",emoji:"🔌",roots:["ca","ble"]},
    {word:"calculate",chinese:"計算",sentence:"Can you <strong>calculate</strong> the total?",tip:"CALCULATE = CALC + UL + ATE",emoji:"🔢",roots:["cal","cu","late"]},
    {word:"campaign",chinese:"運動/活動",sentence:"They started a recycling <strong>campaign</strong>.",tip:"CAMPAIGN = CAMP + AIGN",emoji:"📢",roots:["cam","paign"]},
    {word:"capable",chinese:"有能力的",sentence:"She is <strong>capable</strong> of great things.",tip:"CAPABLE = CAP + ABLE",emoji:"💪",roots:["cap","able"]},
    {word:"capture",chinese:"捕獲/抓住",sentence:"The photo <strong>capture</strong>d a beautiful moment.",tip:"CAPTURE = CAPT(拿) + URE",emoji:"📸",roots:["cap","ture"]},
    {word:"circle",chinese:"圓/圈子",sentence:"Draw a <strong>circle</strong> on the paper.",tip:"CIRCLE = CIRC(環) + LE",emoji:"⭕",roots:["cir","cle"]},
    {word:"citizen",chinese:"公民/市民",sentence:"Every <strong>citizen</strong> has rights.",tip:"CITIZEN = CIT(城市) + IZEN",emoji:"🧑",roots:["ci","ti","zen"]},
    {word:"claim",chinese:"聲稱/要求",sentence:"He <strong>claim</strong>ed he was innocent.",tip:"CLAIM 和 NAME 押韻",emoji:"🗣️",roots:["claim"]},
    {word:"colleague",chinese:"同事",sentence:"She invited her <strong>colleague</strong>s to lunch.",tip:"COLLEAGUE = COL + LEAGUE",emoji:"👥",roots:["col","league"]},
    {word:"combine",chinese:"結合/合併",sentence:"<strong>Combine</strong> the two colors to make green.",tip:"COMBINE = COM + BINE(兩個)",emoji:"🎨",roots:["com","bine"]},
    {word:"conclude",chinese:"結論/結束",sentence:"I <strong>conclude</strong> that you are right.",tip:"CONCLUDE = CON + CLUDE(關)",emoji:"🏁",roots:["con","clude"]},
    {word:"confident",chinese:"自信的",sentence:"Be <strong>confident</strong> in yourself!",tip:"CONFIDENT = CON + FID(信) + ENT",emoji:"💪",roots:["con","fi","dent"]},
    {word:"confuse",chinese:"使困惑",sentence:"The instructions <strong>confuse</strong> me.",tip:"CONFUSE = CON + FUSE(混)",emoji:"😵",roots:["con","fuse"]},
    {word:"consequence",chinese:"後果/結果",sentence:"Every action has a <strong>consequence</strong>.",tip:"CONSEQUENCE = CON + SEQU(跟隨) + ENCE",emoji:"⚠️",roots:["con","se","quence"]},
    {word:"constant",chinese:"持續的/不變的",sentence:"The noise is <strong>constant</strong>.",tip:"CONSTANT = CON + STANT(站)",emoji:"🔁",roots:["con","stant"]},
    {word:"construct",chinese:"建造/建設",sentence:"Workers <strong>construct</strong>ed a new bridge.",tip:"CONSTRUCT = CON + STRUCT(建)",emoji:"🏗️",roots:["con","struct"]},
    {word:"consumer",chinese:"消費者",sentence:"<strong>Consumer</strong>s want good products.",tip:"CONSUMER = CONSUME + R",emoji:"🛒",roots:["con","sum","er"]},
    {word:"context",chinese:"上下文/背景",sentence:"Read the sentence in <strong>context</strong>.",tip:"CONTEXT = CON + TEXT(編織)",emoji:"📖",roots:["con","text"]},
    {word:"contribute",chinese:"貢獻/捐獻",sentence:"Everyone can <strong>contribute</strong> to the project.",tip:"CONTRIBUTE = CON + TRIBUTE(給)",emoji:"🤝",roots:["con","trib","ute"]},
    {word:"convince",chinese:"說服/使相信",sentence:"I <strong>convince</strong>d her to join us.",tip:"CONVINCE = CON + VINCE(征服)",emoji:"🗣️",roots:["con","vince"]},
    {word:"creative",chinese:"有創意的",sentence:"She is very <strong>creative</strong>.",tip:"CREATIVE = CREATE + IVE",emoji:"🎨",roots:["cre","a","tive"]},
    {word:"crisis",chinese:"危機",sentence:"We must prepare for a <strong>crisis</strong>.",tip:"CRISIS 的複數是 CRISES",emoji:"🚨",roots:["cri","sis"]},
    {word:"critic",chinese:"評論家/批評者",sentence:"The food <strong>critic</strong> loved the restaurant.",tip:"CRITIC = CRIT(判斷) + IC",emoji:"📰",roots:["crit","ic"]},
    {word:"crucial",chinese:"關鍵的/重要的",sentence:"Timing is <strong>crucial</strong> in this game.",tip:"CRUCIAL = CRUC(十字) + IAL",emoji:"❗",roots:["cru","cial"]},
    {word:"definite",chinese:"明確的/確定的",sentence:"I have a <strong>definite</strong> plan.",tip:"DEFINITE = DE + FIN(限) + ITE",emoji:"✅",roots:["def","in","ite"]},
    {word:"delay",chinese:"延遲/耽擱",sentence:"Sorry for the <strong>delay</strong>.",tip:"DELAY = DE + LAY",emoji:"⏰",roots:["de","lay"]},
    {word:"demonstrate",chinese:"展示/證明",sentence:"Let me <strong>demonstrate</strong> how it works.",tip:"DEMONSTRATE = DE + MONSTER + ATE",emoji:"👀",roots:["dem","on","strate"]},
    {word:"deny",chinese:"否認/拒絕",sentence:"He <strong>deni</strong>ed eating the last cookie.",tip:"DENY = DE + NY",emoji:"🙅",roots:["de","ny"]},
    {word:"desire",chinese:"渴望/慾望",sentence:"I have a strong <strong>desire</strong> to travel.",tip:"DESIRE = DE + SIRE(星)",emoji:"✨",roots:["de","sire"]},
    {word:"determine",chinese:"決定/確定",sentence:"Hard work <strong>determine</strong>s success.",tip:"DETERMINE = DE + TERMINE(限)",emoji:"🎯",roots:["de","ter","mine"]},
    {word:"dismiss",chinese:"解散/駁回",sentence:"Class is <strong>dismiss</strong>ed!",tip:"DISMISS = DIS + MISS(送)",emoji:"🏫",roots:["dis","miss"]},
    {word:"display",chinese:"展示/顯示",sentence:"The store has a nice window <strong>display</strong>.",tip:"DISPLAY = DIS + PLAY",emoji:"🖥️",roots:["dis","play"]},
    {word:"domestic",chinese:"國內的/家庭的",sentence:"<strong>Domestic</strong> flights are cheaper.",tip:"DOMESTIC = DOMEST(家) + IC",emoji:"🏠",roots:["do","mes","tic"]},
    {word:"donate",chinese:"捐贈",sentence:"I <strong>donate</strong>d toys to charity.",tip:"DONATE = DON(給) + ATE",emoji:"🎁",roots:["do","nate"]},
    {word:"draft",chinese:"草稿/草案",sentence:"This is just the first <strong>draft</strong>.",tip:"DRAFT 和 CRAFT 押韻",emoji:"📝",roots:["draft"]},
    {word:"drama",chinese:"戲劇/戲",sentence:"She is in the school <strong>drama</strong> club.",tip:"DRAMA 來自希臘文「行動」",emoji:"🎭",roots:["dra","ma"]},
    {word:"duty",chinese:"責任/義務",sentence:"It is our <strong>duty</strong> to help.",tip:"DUTY = DUT + Y",emoji:"✊",roots:["du","ty"]},
    {word:"eager",chinese:"渴望的/熱切的",sentence:"I am <strong>eager</strong> to start the project.",tip:"EAGER = EAG + ER",emoji:"🤩",roots:["ea","ger"]},
    {word:"element",chinese:"元素/要素",sentence:"Water is an important <strong>element</strong>.",tip:"ELEMENT = ELE + MENT",emoji:"🧪",roots:["el","e","ment"]},
    {word:"eliminate",chinese:"消除/淘汰",sentence:"We must <strong>eliminate</strong> mistakes.",tip:"ELIMINATE = E + LIMIN(門檻) + ATE",emoji:"❌",roots:["e","lim","in","ate"]},
    {word:"embarrass",chinese:"使尷尬",sentence:"His joke <strong>embarrass</strong>ed her.",tip:"EMBARRASS 有兩個 R 兩個 S",emoji:"😳",roots:["em","bar","rass"]},
    {word:"emerge",chinese:"出現/浮現",sentence:"The sun <strong>emerge</strong>d from behind the clouds.",tip:"EMERGE = E + MERGE",emoji:"🌅",roots:["e","merge"]},
    {word:"enormous",chinese:"巨大的",sentence:"An <strong>enormous</strong> whale swam past us.",tip:"ENORMOUS = E + NORM + OUS",emoji:"🐋",roots:["e","norm","ous"]},
    {word:"entire",chinese:"整個的/全部的",sentence:"I read the <strong>entire</strong> book in one day.",tip:"ENTIRE = EN + TIRE",emoji:"📖",roots:["en","tire"]},
    {word:"essential",chinese:"必要的/本質的",sentence:"Water is <strong>essential</strong> for life.",tip:"ESSENTIAL = ESSENT + IAL",emoji:"💧",roots:["es","sen","tial"]},
    {word:"establish",chinese:"建立/創立",sentence:"They <strong>establish</strong>ed a new school.",tip:"ESTABLISH = ES + TAB + LISH",emoji:"🏫",roots:["es","tab","lish"]},
    {word:"estimate",chinese:"估計/評估",sentence:"I <strong>estimate</strong> it will take an hour.",tip:"ESTIMATE = ESTIM + ATE",emoji:"🤔",roots:["es","ti","mate"]},
    {word:"expand",chinese:"擴展/擴大",sentence:"The company wants to <strong>expand</strong> overseas.",tip:"EXPAND = EX + PAND(展開)",emoji:"📈",roots:["ex","pand"]}
  ]
};
