WORD_DATA["cefr_a1"] = {
  name: "CEFR A1",
  color: "#16a34a",
  words: [
    {word:"need",chinese:"",definition:"having to have something because it is necessary or you want it very much",sentence:"We <strong>need</strong> more people so that we can finish the project on time.",tip:"",emoji:"📖",roots:["need"]},
    {word:"new",chinese:"",definition:"recently created, purchased, or obtained",sentence:"I need a <strong>new</strong> computer. This one is too slow.",tip:"",emoji:"📖",roots:["new"]},
    {word:"page",chinese:"",definition:"a side of a piece of paper in a book or magazine, usually with a number on it",sentence:"We need our logo on every <strong>page</strong>.",tip:"",emoji:"📖",roots:["page"]},
    {word:"number",chinese:"",definition:"a symbol that represents an amount, such as 1, 2, etc.",sentence:"Can you tell me your phone <strong>number</strong>?",tip:"",emoji:"📖",roots:["number"]},
    {word:"night",chinese:"",definition:"the time of day when it is dark, between late afternoon and 12:00 am",sentence:"I'll stay there for two <strong>nights</strong>.",tip:"",emoji:"📖",roots:["night"]},
    {word:"now",chinese:"",definition:"at the moment or present",sentence:"I'm leaving <strong>now</strong>. Do you want to come with me?",tip:"",emoji:"📖",roots:["now"]},
    {word:"open",chinese:"",definition:"to let people enter a place and start to use it or do business there",sentence:"The coffee shop <strong>opens</strong> at 8:00 am on weekdays and 9:00 am on weekends.",tip:"",emoji:"📖",roots:["open"]},
    {word:"note",chinese:"",definition:"a short piece of writing such as a message or very short letter",sentence:"Did you see the <strong>note</strong> on your computer?",tip:"",emoji:"📖",roots:["note"]},
    {word:"people",chinese:"",definition:"human beings",sentence:"We interviewed six <strong>people</strong> yesterday.",tip:"",emoji:"📖",roots:["people"]},
    {word:"only",chinese:"",definition:"showing the amount is less than expected; just the number or group talked about and not others",sentence:"The sports watch is <strong>only</strong> US $20. It's a very good price.",tip:"",emoji:"📖",roots:["only"]},
    {word:"office",chinese:"",definition:"a room in a company or building where people work, usually at a desk",sentence:"My <strong>office</strong> is on the third floor.",tip:"",emoji:"📖",roots:["office"]},
    {word:"name",chinese:"",definition:"the word or group of words a person is known by",sentence:"Hi, I'm Tommy. What's your <strong>name</strong>?",tip:"",emoji:"📖",roots:["name"]},
    {word:"nationality",chinese:"",definition:"the status of belonging to a country",sentence:"There are students of many <strong>nationalities</strong> in our school.",tip:"",emoji:"📖",roots:["nationality"]},
    {word:"often",chinese:"",definition:"frequently or many times",sentence:"I <strong>often</strong> eat dinner by myself.",tip:"",emoji:"📖",roots:["often"]},
    {word:"other",chinese:"",definition:"an extra or additional thing of the same kind",sentence:"We have many <strong>other</strong> factories in Taiwan.",tip:"",emoji:"📖",roots:["other"]},
    {word:"old",chinese:"",definition:"having been alive for many years, or having existed a long time",sentence:"It's an <strong>old</strong> building, but it's in a nice area.",tip:"",emoji:"📖",roots:["old"]},
    {word:"never",chinese:"",definition:"not happening or being true ever",sentence:"We <strong>never</strong> work on weekends.",tip:"",emoji:"📖",roots:["never"]},
    {word:"pair",chinese:"",definition:"two things of the same kind that are used together",sentence:"I need to get a new <strong>pair</strong> of socks.",tip:"",emoji:"📖",roots:["pair"]},
    {word:"pay",chinese:"",definition:"give money to someone for goods or a service, or for their work",sentence:"The company will <strong>pay</strong> for the meals.",tip:"",emoji:"📖",roots:["pay"]},
    {word:"part",chinese:"",definition:"a piece or section of something",sentence:"My school is in the old <strong>part</strong> of the city.",tip:"",emoji:"📖",roots:["part"]},
    {word:"sit",chinese:"",definition:"rest your body on something with your upper body upright and your legs not holding the weight of your body",sentence:"You can <strong>sit</strong> here and drink coffee.",tip:"",emoji:"📖",roots:["sit"]},
    {word:"slim",chinese:"",definition:"thin in a way that looks good",sentence:"He's <strong>slim</strong> because he exercises almost every day.",tip:"",emoji:"📖",roots:["slim"]},
    {word:"start",chinese:"",definition:"begin something",sentence:"The game will <strong>start</strong> in fifteen minutes.",tip:"",emoji:"📖",roots:["start"]},
    {word:"stop",chinese:"",definition:"to be no longer doing something",sentence:"We need to <strong>stop</strong> talking and start working.",tip:"",emoji:"📖",roots:["stop"]},
    {word:"talk",chinese:"",definition:"to say words in order to discuss something with someone",sentence:"I want to <strong>talk</strong> about our plan for next year.",tip:"",emoji:"📖",roots:["talk"]},
    {word:"stuff",chinese:"",definition:"things or items, especially when you don't know what exactly it is",sentence:"There's a lot of <strong>stuff</strong> on your desk. You need to clean that first.",tip:"",emoji:"📖",roots:["stuff"]},
    {word:"soon",chinese:"",definition:"in or after a short amount of time",sentence:"She just went to get some lunch, but she will be here <strong>soon</strong>.",tip:"",emoji:"📖",roots:["soon"]},
    {word:"sleep",chinese:"",definition:"to rest in a way in which your eyes are closed and you are temporarily unconscious",sentence:"I usually <strong>sleep</strong> from 11:00 pm to 6:00 am.",tip:"",emoji:"📖",roots:["sleep"]},
    {word:"thing",chinese:"",definition:"used to talk about an idea, subject, event, and action in a general way",sentence:"We have three <strong>things</strong> to deal with this afternoon.",tip:"",emoji:"📖",roots:["thing"]},
    {word:"ticket",chinese:"",definition:"a piece of paper that shows you have paid to enter a place, used a service, or taken a kind of transportation",sentence:"How much is a <strong>ticket</strong> to Taichung?",tip:"",emoji:"📖",roots:["ticket"]},
    {word:"show",chinese:"",definition:"to let someone see something",sentence:"Come with me. I'll <strong>show</strong> you where your seat is.",tip:"",emoji:"📖",roots:["show"]},
    {word:"slow",chinese:"",definition:"not fast; moving or happening at a low speed",sentence:"This train is very <strong>slow</strong>, but the ticket is very cheap.",tip:"",emoji:"📖",roots:["slow"]},
    {word:"small",chinese:"",definition:"little",sentence:"There is a bedroom, a living room, and a <strong>small</strong> kitchen in the apartment.",tip:"",emoji:"📖",roots:["small"]},
    {word:"special",chinese:"",definition:"different from, or more than usual",sentence:"We offer a <strong>special</strong> discount to our new customers.",tip:"",emoji:"📖",roots:["special"]},
    {word:"bus stop",chinese:"",definition:"a place where people can get on or off a bus",sentence:"There's a <strong>bus stop</strong> just outside our office.",tip:"",emoji:"📖",roots:["bus","stop"]},
    {word:"speak",chinese:"",definition:"use your voice to say words",sentence:"She's here now. Would you like to <strong>speak</strong> with her?",tip:"",emoji:"📖",roots:["speak"]},
    {word:"stay",chinese:"",definition:"to remain in or not leave a place, or situation",sentence:"We will <strong>stay</strong> in Tokyo for three days.",tip:"",emoji:"📖",roots:["stay"]},
    {word:"tell",chinese:"",definition:"to use your voice to give information to someone",sentence:"Please <strong>tell</strong> him that I called.",tip:"",emoji:"📖",roots:["tell"]},
    {word:"take",chinese:"",definition:"to use or go by one kind of transportation",sentence:"I need to <strong>take</strong> the kids to school before I come to work.",tip:"",emoji:"📖",roots:["take"]},
    {word:"think",chinese:"",definition:"to have a certain opinion, belief, or idea",sentence:"I <strong>think</strong> it's a good idea.",tip:"",emoji:"📖",roots:["think"]},
    {word:"tired",chinese:"",definition:"needing rest or sleep",sentence:"I feel <strong>tired</strong>. I didn't sleep well last night.",tip:"",emoji:"📖",roots:["tired"]},
    {word:"week",chinese:"",definition:"a period of seven days",sentence:"I'm going to be in Tokyo for a <strong>week</strong> and in Taipei for four days.",tip:"",emoji:"📖",roots:["week"]},
    {word:"visit",chinese:"",definition:"to go somewhere to see a person or a place and spend time there",sentence:"I'm going to <strong>visit</strong> my grandmother on weekends.",tip:"",emoji:"📖",roots:["visit"]},
    {word:"together",chinese:"",definition:"with another thing or person",sentence:"Let's have dinner <strong>together</strong> tonight.",tip:"",emoji:"📖",roots:["together"]},
    {word:"water",chinese:"",definition:"H2O; a clear liquid that falls from the sky as rain",sentence:"Can I have a glass of <strong>water</strong>, please?",tip:"",emoji:"📖",roots:["water"]},
    {word:"work",chinese:"",definition:"to have a job or use your energy to do a task, usually for payment",sentence:"I <strong>work</strong> for an international company.",tip:"",emoji:"📖",roots:["work"]},
    {word:"website",chinese:"",definition:"a set of pages on the internet at the same address about the same topic or organization",sentence:"You can see pictures of our products on our <strong>website</strong>.",tip:"",emoji:"📖",roots:["website"]},
    {word:"travel",chinese:"",definition:"to go away to a place usually far from where you are now or where you live",sentence:"I enjoy <strong>traveling</strong> around the world because visiting different countries is interesting.",tip:"",emoji:"📖",roots:["travel"]},
    {word:"today",chinese:"",definition:"on this day",sentence:"It's a very busy day <strong>today</strong>.",tip:"",emoji:"📖",roots:["today"]},
    {word:"year",chinese:"",definition:"the period from 1 January to 31 December",sentence:"I want to work here for a <strong>year</strong>, and then I'll change jobs.",tip:"",emoji:"📖",roots:["year"]},
    {word:"young",chinese:"",definition:"to describe a person who has only lived a short time, or something that has not existed for a long time",sentence:"He's very <strong>young</strong>, but he learns fast.",tip:"",emoji:"📖",roots:["young"]},
    {word:"wait",chinese:"",definition:"stay in one place or delay doing something until something else happens",sentence:"You will need to <strong>wait</strong> for thirty minutes. Is that OK?",tip:"",emoji:"📖",roots:["wait"]},
    {word:"tomorrow",chinese:"",definition:"the day following today",sentence:"What time do you want to meet <strong>tomorrow</strong>?",tip:"",emoji:"📖",roots:["tomorrow"]},
    {word:"want",chinese:"",definition:"to feel that you would like something, or would like something to happen",sentence:"What do you <strong>want</strong> to do?",tip:"",emoji:"📖",roots:["want"]},
    {word:"understand",chinese:"",definition:"to know the meaning of something",sentence:"It's too difficult to <strong>understand</strong> the things that he said.",tip:"",emoji:"📖",roots:["understand"]},
    {word:"write",chinese:"",definition:"to use a pen or keyboard to put words on a piece of paper or a screen",sentence:"Please <strong>write</strong> your name here.",tip:"",emoji:"📖",roots:["write"]},
    {word:"wrong",chinese:"",definition:"not correct or true",sentence:"I can't send it to him. He gave us the <strong>wrong</strong> address.",tip:"",emoji:"📖",roots:["wrong"]},
    {word:"weekend",chinese:"",definition:"Saturday and Sunday",sentence:"What did you do last <strong>weekend</strong>?",tip:"",emoji:"📖",roots:["weekend"]},
    {word:"use",chinese:"",definition:"to do something with something else for a purpose or to get a result",sentence:"Can I <strong>use</strong> US dollars here?",tip:"",emoji:"📖",roots:["use"]},
    {word:"world",chinese:"",definition:"the planet we live on and everything on it",sentence:"You will have the chance to meet people from all over the <strong>world</strong>.",tip:"",emoji:"📖",roots:["world"]},
    {word:"always",chinese:"",definition:"every time; at any time",sentence:"I <strong>always</strong> check my email before I go to work.",tip:"",emoji:"📖",roots:["always"]},
    {word:"best",chinese:"",definition:"the most satisfactory, suitable, or of the highest quality",sentence:"The Tristar Hotel has the <strong>best</strong> service.",tip:"",emoji:"📖",roots:["best"]},
    {word:"also",chinese:"",definition:"together with; in addition to",sentence:"I speak English and Japanese, and <strong>also</strong> a little Korean.",tip:"",emoji:"📖",roots:["also"]},
    {word:"almost",chinese:"",definition:"nearly but not exactly",sentence:"Our new apartment is <strong>almost</strong> ready.",tip:"",emoji:"📖",roots:["almost"]},
    {word:"begin",chinese:"",definition:"to start",sentence:"The presentation will <strong>begin</strong> at 9:30 in the morning.",tip:"",emoji:"📖",roots:["begin"]},
    {word:"better",chinese:"",definition:"more satisfactory, suitable, or higher quality",sentence:"Business wasn't very good last month, but this month it is <strong>better</strong>.",tip:"",emoji:"📖",roots:["better"]},
    {word:"bad",chinese:"",definition:"not good; having negative effects",sentence:"We got some <strong>bad</strong> news yesterday.",tip:"",emoji:"📖",roots:["bad"]},
    {word:"again",chinese:"",definition:"happening after it has happened once; done another time after it has been done once",sentence:"I called him <strong>again</strong>, but there was still no answer.",tip:"",emoji:"📖",roots:["again"]},
    {word:"because",chinese:"",definition:"as a result; for the reason that",sentence:"I moved to this house <strong>because</strong> it's closer to my school.",tip:"",emoji:"📖",roots:["because"]},
    {word:"bag",chinese:"",definition:"a soft container you use to carry or keep things",sentence:"You can put the books in a <strong>bag</strong> and give them to me tomorrow.",tip:"",emoji:"📖",roots:["bag"]},
    {word:"away",chinese:"",definition:"to or in a different or further place; in a different direction or situation",sentence:"You can take it <strong>away</strong> with you if you want.",tip:"",emoji:"📖",roots:["away"]},
    {word:"baseball",chinese:"",definition:"a game played on a field between two teams where a ball is hit with a bat and runs are scored",sentence:"My sister plays <strong>baseball</strong> every Saturday afternoon.",tip:"",emoji:"📖",roots:["baseball"]},
    {word:"about",chinese:"",definition:"connected with; related to; on the topic of",sentence:"We need <strong>about</strong> three hours for the training.",tip:"",emoji:"📖",roots:["about"]},
    {word:"back",chinese:"",definition:"towards the original location, place, or situation",sentence:"I need to go <strong>back</strong> home soon.",tip:"",emoji:"📖",roots:["back"]},
    {word:"basketball",chinese:"",definition:"a game played on a court between two teams in which points are scored by throwing the ball through the opposite team's hoop",sentence:"Do you want to play <strong>basketball</strong> with us after school?",tip:"",emoji:"📖",roots:["basketball"]},
    {word:"age",chinese:"",definition:"the number of years months, days, etc. someone has been alive or something has existed",sentence:"I think he's quite young, but I didn't ask his <strong>age</strong>.",tip:"",emoji:"📖",roots:["age"]},
    {word:"ask",chinese:"",definition:"to request; to communicate with someone that you want them to do something or give you something",sentence:"Can you <strong>ask</strong> him for his phone number?",tip:"",emoji:"📖",roots:["ask"]},
    {word:"address",chinese:"",definition:"the street number and name of where someone lives or a company is located; the set of letters, numbers, or symbols used to find a page on the internet",sentence:"My email <strong>address</strong> is yuanyuan@gmail.com.",tip:"",emoji:"📖",roots:["address"]},
    {word:"already",chinese:"",definition:"to say that something has happened or been done before now, or before another particular time",sentence:"The company has <strong>already</strong> paid for the flight.",tip:"",emoji:"📖",roots:["already"]},
    {word:"bank",chinese:"",definition:"an organization that provides financial services such as looking after your money or providing loans",sentence:"I want to get a job in a <strong>bank</strong> after I graduate.",tip:"",emoji:"📖",roots:["bank"]},
    {word:"rich",chinese:"",definition:"having a lot of money or possessions",sentence:"Her family is quite <strong>rich</strong>, but she makes her own money.",tip:"",emoji:"📖",roots:["rich"]},
    {word:"say",chinese:"",definition:"use your voice to produce words to express information or an idea",sentence:"She <strong>says</strong> that she will come back tomorrow.",tip:"",emoji:"📖",roots:["say"]},
    {word:"short",chinese:"",definition:"a small amount or period of time, less than expected",sentence:"My workmate is the woman there with <strong>short</strong> hair.",tip:"",emoji:"📖",roots:["short"]},
    {word:"practice",chinese:"",definition:"to do an activity many times to make your skill better",sentence:"I need to <strong>practice</strong> my speech.",tip:"",emoji:"📖",roots:["practice"]},
    {word:"problem",chinese:"",definition:"a thing or situation that creates difficulty",sentence:"There's a <strong>problem</strong> with the printer.",tip:"",emoji:"📖",roots:["problem"]},
    {word:"sad",chinese:"",definition:"feeling unhappy or bad about something",sentence:"We are <strong>sad</strong> that you are leaving.",tip:"",emoji:"📖",roots:["sad"]},
    {word:"picture",chinese:"",definition:"a drawing, painting, photograph, etc.",sentence:"We need to post some good <strong>pictures</strong> on our website.",tip:"",emoji:"📖",roots:["picture"]},
    {word:"ride",chinese:"",definition:"sit on an animal such as a horse, or a vehicle such as a bicycle or a motorcycle and control it as it moves",sentence:"I <strong>ride</strong> my motorcycle to work every day.",tip:"",emoji:"📖",roots:["ride"]},
    {word:"sell",chinese:"",definition:"to give goods or services to someone in return for money",sentence:"We <strong>sell</strong> our products in twenty-five countries.",tip:"",emoji:"📖",roots:["sell"]},
    {word:"safe",chinese:"",definition:"not in danger of being hurt or damaged",sentence:"We need to make sure our workers are <strong>safe</strong>.",tip:"",emoji:"📖",roots:["safe"]},
    {word:"shopping",chinese:"",definition:"the activity of buying things from stores or online",sentence:"Online <strong>shopping</strong> is very popular these days.",tip:"",emoji:"📖",roots:["shopping"]},
    {word:"quick",chinese:"",definition:"done in a short time or fast",sentence:"Their service is very <strong>quick</strong>. We only ordered it yesterday and it's here already.",tip:"",emoji:"📖",roots:["quick"]},
    {word:"price",chinese:"",definition:"the amount of money you need to pay to get something",sentence:"The <strong>price</strong> is US $4,500, but we can give you a discount if you pay in cash right now.",tip:"",emoji:"📖",roots:["price"]},
    {word:"restaurant",chinese:"",definition:"a place with tables where customers pay to eat meals",sentence:"We can take our guests to the Thai <strong>restaurant</strong> in the hotel.",tip:"",emoji:"📖",roots:["restaurant"]},
    {word:"put",chinese:"",definition:"to use your hands to move something into a particular place",sentence:"I <strong>put</strong> your business cards on your desk.",tip:"",emoji:"📖",roots:["put"]},
    {word:"poor",chinese:"",definition:"having very little money or few possessions",sentence:"A lot of people in this area are quite <strong>poor</strong>.",tip:"",emoji:"📖",roots:["poor"]},
    {word:"shop",chinese:"",definition:"a place where items are displayed for sale",sentence:"I need to find a <strong>shop</strong> that sells gifts.",tip:"",emoji:"📖",roots:["shop"]},
    {word:"same",chinese:"",definition:"not different from the thing you are talking about",sentence:"We work in the <strong>same</strong> company but in different departments.",tip:"",emoji:"📖",roots:["same"]},
    {word:"restroom",chinese:"",definition:"a room with a toilet",sentence:"Excuse me. Where's the <strong>restroom</strong>?",tip:"",emoji:"📖",roots:["restroom"]},
    {word:"person",chinese:"",definition:"a human being",sentence:"I met a <strong>person</strong> from Brazil yesterday.",tip:"",emoji:"📖",roots:["person"]},
    {word:"building",chinese:"",definition:"a walled structure with a roof on top and rooms inside",sentence:"That big <strong>building</strong> there is the city library.",tip:"",emoji:"📖",roots:["building"]},
    {word:"carry",chinese:"",definition:"to have something with you, or to hold it in your hands and take it somewhere",sentence:"I'll <strong>carry</strong> your bags to the car.",tip:"",emoji:"📖",roots:["carry"]},
    {word:"cheap",chinese:"",definition:"costing less than usual or than you expected",sentence:"Fruit is <strong>cheap</strong> here, but other things are expensive.",tip:"",emoji:"📖",roots:["cheap"]},
    {word:"clean",chinese:"",definition:"having no dirt on or in it",sentence:"The hotel room was small, but at least it was <strong>clean</strong>.",tip:"",emoji:"📖",roots:["clean"]},
    {word:"close",chinese:"",definition:"to shut or to end",sentence:"I live quite <strong>close</strong> to my work, so it's very convenient.",tip:"",emoji:"📖",roots:["close"]},
    {word:"color",chinese:"",definition:"blue, yellow, red, etc.",sentence:"What <strong>color</strong> is the tie?",tip:"",emoji:"📖",roots:["color"]},
    {word:"change",chinese:"",definition:"to become different or make something different",sentence:"I want to <strong>change</strong> jobs as soon as possible.",tip:"",emoji:"📖",roots:["change"]},
    {word:"buy",chinese:"",definition:"pay money for something so that it becomes yours",sentence:"We will <strong>buy</strong> new computers next month.",tip:"",emoji:"📖",roots:["buy"]},
    {word:"bring",chinese:"",definition:"to take something or someone to a place",sentence:"Please remember to <strong>bring</strong> your laptop on Friday.",tip:"",emoji:"📖",roots:["bring"]},
    {word:"boring",chinese:"",definition:"making you feel not interested",sentence:"My job is <strong>boring</strong>, but the salary is good.",tip:"",emoji:"📖",roots:["boring"]},
    {word:"busy",chinese:"",definition:"having many things to do in a limited time",sentence:"I have three kids, so I am very <strong>busy</strong> every day.",tip:"",emoji:"📖",roots:["busy"]},
    {word:"box",chinese:"",definition:"a square or rectangular container",sentence:"My business cards are in that white <strong>box</strong> on the desk.",tip:"",emoji:"📖",roots:["box"]},
    {word:"choose",chinese:"",definition:"decide which you want from a set of two or more things",sentence:"We need to <strong>choose</strong> some good pictures for the website.",tip:"",emoji:"📖",roots:["choose"]},
    {word:"click",chinese:"",definition:"to push a button on a keyboard or mouse to make something happen on a computer",sentence:"Please <strong>click</strong> on the link below.",tip:"",emoji:"📖",roots:["click"]},
    {word:"cash",chinese:"",definition:"money you can hold such as bills and coins",sentence:"I don't have my credit card, so I'll pay in <strong>cash</strong>.",tip:"",emoji:"📖",roots:["cash"]},
    {word:"chat",chinese:"",definition:"to talk with someone informally",sentence:"I like to <strong>chat</strong> with my classmates at lunchtime.",tip:"",emoji:"📖",roots:["chat"]},
    {word:"business",chinese:"",definition:"buying and selling goods or services",sentence:"It's not easy to do <strong>business</strong> in this country.",tip:"",emoji:"📖",roots:["business"]},
    {word:"call",chinese:"",definition:"to use a phone or computer to talk to someone",sentence:"He's not at home now, but you can <strong>call</strong> him on his cell phone.",tip:"",emoji:"📖",roots:["call"]},
    {word:"check",chinese:"",definition:"to look at something to make sure it is right or what it should be",sentence:"I think the flight is four hours, but I need to <strong>check</strong>.",tip:"",emoji:"📖",roots:["check"]},
    {word:"comfortable",chinese:"",definition:"giving you a nice and relaxed feeling",sentence:"My company gave me a <strong>comfortable</strong> apartment and a car.",tip:"",emoji:"📖",roots:["comfortable"]},
    {word:"interesting",chinese:"",definition:"keeping your attention because it makes you want to understand, watch or think about it more",sentence:"I thought her idea was really <strong>interesting</strong>.",tip:"",emoji:"📖",roots:["interesting"]},
    {word:"hour",chinese:"",definition:"a unit of 60 minutes",sentence:"It takes two and a half <strong>hours</strong> to drive from here to Taipei.",tip:"",emoji:"📖",roots:["hour"]},
    {word:"hard",chinese:"",definition:"difficult to do or to deal with",sentence:"It's <strong>hard</strong> to remember all my passwords.",tip:"",emoji:"📖",roots:["hard"]},
    {word:"guess",chinese:"",definition:"to say or decide what you think is right or true when you are not completely sure about the facts",sentence:"We don't know how many people will come. We need to <strong>guess</strong>.",tip:"",emoji:"📖",roots:["guess"]},
    {word:"glass",chinese:"",definition:"a hard and clear material used to make windows, bottles, etc.",sentence:"Can I get you a <strong>glass</strong> of juice?",tip:"",emoji:"📖",roots:["glass"]},
    {word:"key",chinese:"",definition:"something you use to open a lock or start or turn off a machine",sentence:"I left my office <strong>keys</strong> at home.",tip:"",emoji:"📖",roots:["key"]},
    {word:"job",chinese:"",definition:"the work you do regularly to make money",sentence:"I'm looking for a new <strong>job</strong>.",tip:"",emoji:"📖",roots:["job"]},
    {word:"help",chinese:"",definition:"to give someone support so that it makes what they are doing easier or quicker",sentence:"I'll <strong>help</strong> you clean up.",tip:"",emoji:"📖",roots:["help"]},
    {word:"half",chinese:"",definition:"50% of something",sentence:"We waited for <strong>half</strong> an hour.",tip:"",emoji:"📖",roots:["half"]},
    {word:"glasses",chinese:"",definition:"something you wear over your eyes to help you see more clearly",sentence:"Wait. I need to put on my <strong>glasses</strong>.",tip:"",emoji:"📖",roots:["glasses"]},
    {word:"kind",chinese:"",definition:"a type of thing or person",sentence:"What <strong>kind</strong> of food do you like?",tip:"",emoji:"📖",roots:["kind"]},
    {word:"hear",chinese:"",definition:"to notice a sound",sentence:"Can you please speak louder? I can't <strong>hear</strong> you.",tip:"",emoji:"📖",roots:["hear"]},
    {word:"ID",chinese:"",definition:"an official document with your personal details that shows who you are",sentence:"Please show your <strong>ID</strong> when you enter the building.",tip:"",emoji:"📖",roots:["ID"]},
    {word:"hotel",chinese:"",definition:"a business that has a building with rooms you can pay to sleep in",sentence:"We can get a <strong>hotel</strong> close to the factory.",tip:"",emoji:"📖",roots:["hotel"]},
    {word:"head",chinese:"",definition:"the top part of your body with your face and brain",sentence:"The hat is too big for my <strong>head</strong>.",tip:"",emoji:"📖",roots:["head"]},
    {word:"guy",chinese:"",definition:"an informal word to describe a man or person (especially in plural)",sentence:"Who is the <strong>guy</strong> over there?",tip:"",emoji:"📖",roots:["guy"]},
    {word:"group",chinese:"",definition:"a number of people or things in an area or connected together",sentence:"We'll put them into two <strong>groups</strong>. So, please put the new ones here and the old ones there.",tip:"",emoji:"📖",roots:["group"]},
    {word:"have",chinese:"",definition:"to own or possess",sentence:"We <strong>have</strong> wireless internet in all our rooms.",tip:"",emoji:"📖",roots:["have"]},
    {word:"important",chinese:"",definition:"necessary or having a big effect on someone or something",sentence:"It is <strong>important</strong> to be on time.",tip:"",emoji:"📖",roots:["important"]},
    {word:"just",chinese:"",definition:"very recently; only",sentence:"I <strong>just</strong> arrived at the company.",tip:"",emoji:"📖",roots:["just"]},
    {word:"feel",chinese:"",definition:"to experience an emotion or sense something with your body",sentence:"I <strong>feel</strong> happy living in this area.",tip:"",emoji:"📖",roots:["feel"]},
    {word:"fly",chinese:"",definition:"to travel by airplane",sentence:"I'll <strong>fly</strong> from Singapore to Sydney next Monday.",tip:"",emoji:"📖",roots:["fly"]},
    {word:"funny",chinese:"",definition:"to describe something that makes you laugh",sentence:"My workmates are really <strong>funny</strong>, so we often laugh a lot in the office.",tip:"",emoji:"📖",roots:["funny"]},
    {word:"give",chinese:"",definition:"provide something or offer it to somebody",sentence:"I'll <strong>give</strong> you an answer tomorrow.",tip:"",emoji:"📖",roots:["give"]},
    {word:"factory",chinese:"",definition:"a large building or group of buildings where machines are used to produce products or goods",sentence:"In our <strong>factory</strong>, we make batteries for cell phones.",tip:"",emoji:"📖",roots:["factory"]},
    {word:"evening",chinese:"",definition:"the part of the day between afternoon and night",sentence:"I take a language class in the <strong>evening</strong>.",tip:"",emoji:"📖",roots:["evening"]},
    {word:"enjoy",chinese:"",definition:"to get pleasure and happiness from something",sentence:"I <strong>enjoy</strong> doing exercise in my free time.",tip:"",emoji:"📖",roots:["enjoy"]},
    {word:"fast",chinese:"",definition:"moving or being able to move very quickly",sentence:"If we take the <strong>fast</strong> train, we will be there before lunchtime.",tip:"",emoji:"📖",roots:["fast"]},
    {word:"finish",chinese:"",definition:"to complete something or do the last part of it",sentence:"I usually <strong>finish</strong> work at 6:30 pm.",tip:"",emoji:"📖",roots:["finish"]},
    {word:"friendly",chinese:"",definition:"nice, kind, and helpful to other people",sentence:"Our staff is <strong>friendly</strong> and helpful.",tip:"",emoji:"📖",roots:["friendly"]},
    {word:"exciting",chinese:"",definition:"making you feel interested and enthusiastic",sentence:"Some people think being a flight attendant is an <strong>exciting</strong> job.",tip:"",emoji:"📖",roots:["exciting"]},
    {word:"far",chinese:"",definition:"at a great distance",sentence:"The airport is quite <strong>far</strong> from the city center.",tip:"",emoji:"📖",roots:["far"]},
    {word:"free",chinese:"",definition:"not needing to be paid for",sentence:"The software is <strong>free</strong>, but you need to leave your name and email address.",tip:"",emoji:"📖",roots:["free"]},
    {word:"example",chinese:"",definition:"something is done or shown to help someone understand how to do, use or produce something",sentence:"My job is quite difficult. For <strong>example</strong>, I have to visit a lot of customers every week.",tip:"",emoji:"📖",roots:["example"]},
    {word:"end",chinese:"",definition:"the last part or point of something",sentence:"We will pay you at the <strong>end</strong> of the month.",tip:"",emoji:"📖",roots:["end"]},
    {word:"enough",chinese:"",definition:"as much as needed or required",sentence:"Don't worry. We have <strong>enough</strong> time to finish it.",tip:"",emoji:"📖",roots:["enough"]},
    {word:"favorite",chinese:"",definition:"the one you like best or most",sentence:"Kyoto is my <strong>favorite</strong> city.",tip:"",emoji:"📖",roots:["favorite"]},
    {word:"find",chinese:"",definition:"to discover something or to locate it",sentence:"I hope you <strong>find</strong> a good job.",tip:"",emoji:"📖",roots:["find"]},
    {word:"flower",chinese:"",definition:"the colorful part of a plant, often has a pleasant smell",sentence:"I always give my mother <strong>flowers</strong> on her birthday.",tip:"",emoji:"📖",roots:["flower"]},
    {word:"expensive",chinese:"",definition:"costing a lot of money or resources",sentence:"Living in London is very <strong>expensive</strong>.",tip:"",emoji:"📖",roots:["expensive"]},
    {word:"could",chinese:"",definition:"a more polite form of can when making a request or asking if something is okay",sentence:"<strong>Could</strong> you help me with my suitcase, please?",tip:"",emoji:"📖",roots:["could"]},
    {word:"different",chinese:"",definition:"unlike something or not the same as it",sentence:"<strong>Different</strong> products have <strong>different</strong> prices.",tip:"",emoji:"📖",roots:["different"]},
    {word:"dream",chinese:"",definition:"something you imagine and you want to do, get, or achieve in the future",sentence:"It's my <strong>dream</strong> to start my own company.",tip:"",emoji:"📖",roots:["dream"]},
    {word:"early",chinese:"",definition:"in or near the beginning of a period of time, or in the first part of a process or situation",sentence:"I get to the office <strong>early</strong>, so I can leave <strong>early</strong>.",tip:"",emoji:"📖",roots:["early"]},
    {word:"convenient",chinese:"",definition:"easy to use or do; causing fewer problems or needing less time",sentence:"It's a busy city, but it's also very <strong>convenient</strong>.",tip:"",emoji:"📖",roots:["convenient"]},
    {word:"cost",chinese:"",definition:"to estimate the amount of money you need to pay to buy something",sentence:"The shirt <strong>costs</strong> US$55.",tip:"",emoji:"📖",roots:["cost"]},
    {word:"computer",chinese:"",definition:"a machine that stores information and runs apps and programs",sentence:"I do all my homework on my <strong>computer</strong>.",tip:"",emoji:"📖",roots:["computer"]},
    {word:"company",chinese:"",definition:"an organization that does business",sentence:"I work for a <strong>company</strong> that makes laptop computers.",tip:"",emoji:"📖",roots:["company"]},
    {word:"customer",chinese:"",definition:"a person who buys a product or service",sentence:"Every <strong>customer</strong> is important to us.",tip:"",emoji:"📖",roots:["customer"]},
    {word:"difficult",chinese:"",definition:"not easy to do, achieve, or deal with",sentence:"It is <strong>difficult</strong> to remember everyone's name.",tip:"",emoji:"📖",roots:["difficult"]},
    {word:"credit card",chinese:"",definition:"a card that lets you buy something and pay later",sentence:"You can pay by your <strong>credit card</strong> online.",tip:"",emoji:"📖",roots:["credit","card"]},
    {word:"conversation",chinese:"",definition:"an informal talk or chat between two or more people face-to-face, on the phone, or online",sentence:"We had an interesting <strong>conversation</strong> after the meeting.",tip:"",emoji:"📖",roots:["conversation"]},
    {word:"dear",chinese:"",definition:"used in a letter or more formal email before the name of the person you are writing to",sentence:"<strong>Dear</strong> Ms. Tseng, thank you for your reply.",tip:"",emoji:"📖",roots:["dear"]},
    {word:"date",chinese:"",definition:"a particular day in a month and often given with the year",sentence:"What's the <strong>date</strong> today?",tip:"",emoji:"📖",roots:["date"]},
    {word:"country",chinese:"",definition:"an area of land with its own borders and own government",sentence:"Last year, I went to eight different <strong>countries</strong>.",tip:"",emoji:"📖",roots:["country"]},
    {word:"of course",chinese:"",definition:"certainly, definitely, or indeed",sentence:"Can I come with you? <strong>Of course</strong>.",tip:"",emoji:"📖",roots:["of","course"]},
    {word:"contact",chinese:"",definition:"get in touch with someone",sentence:"Please <strong>contact</strong> us for more information.",tip:"",emoji:"📖",roots:["contact"]},
    {word:"dollar",chinese:"",definition:"the main unit of money in several countries",sentence:"The train ticket to Manilla will cost me fifty <strong>dollars</strong>.",tip:"",emoji:"📖",roots:["dollar"]},
    {word:"each",chinese:"",definition:"every individual thing in a group of two or more",sentence:"Give one brochure and one catalog to <strong>each</strong> person.",tip:"",emoji:"📖",roots:["each"]},
    {word:"down",chinese:"",definition:"to or towards a lower place",sentence:"You need to go <strong>down</strong> to the first floor.",tip:"",emoji:"📖",roots:["down"]},
    {word:"like",chinese:"",definition:"to enjoy something or think that it is attractive",sentence:"I <strong>like</strong> my new cell phone. It's very easy to use.",tip:"",emoji:"📖",roots:["like"]},
    {word:"look for",chinese:"",definition:"to search for, try to find, seek",sentence:"I'm <strong>looking for</strong> a new apartment.",tip:"",emoji:"📖",roots:["look","for"]},
    {word:"maybe",chinese:"",definition:"to show you think something is possibly true but you are not sure",sentence:"<strong>Maybe</strong> we need to get some more people to help us.",tip:"",emoji:"📖",roots:["maybe"]},
    {word:"meeting",chinese:"",definition:"an activity where people get together to discuss things",sentence:"I had <strong>meetings</strong> all day.",tip:"",emoji:"📖",roots:["meeting"]},
    {word:"month",chinese:"",definition:"one of twelve periods of 28 to 31 days that a year is divided into",sentence:"She traveled to Thailand for two <strong>months</strong>.",tip:"",emoji:"📖",roots:["month"]},
    {word:"left",chinese:"",definition:"opposite to the right",sentence:"The bathroom is on the <strong>left</strong>. It's next to the elevator.",tip:"",emoji:"📖",roots:["left"]},
    {word:"learn",chinese:"",definition:"to get knowledge or a skill by studying it or being taught",sentence:"It's important to <strong>learn</strong> a second language.",tip:"",emoji:"📖",roots:["learn"]},
    {word:"long",chinese:"",definition:"happening for a large amount of time",sentence:"She's very tired after a <strong>long</strong> flight.",tip:"",emoji:"📖",roots:["long"]},
    {word:"light",chinese:"",definition:"brightness; a piece of equipment that produces brightness",sentence:"Please turn off the <strong>lights</strong> when you leave.",tip:"",emoji:"📖",roots:["light"]},
    {word:"make",chinese:"",definition:"to produce or create something",sentence:"I like to <strong>make</strong> soap and other things for my family.",tip:"",emoji:"📖",roots:["make"]},
    {word:"minute",chinese:"",definition:"a period of 60 seconds",sentence:"Please wait. It will take about three <strong>minutes</strong>.",tip:"",emoji:"📖",roots:["minute"]},
    {word:"late",chinese:"",definition:"after the usual, planned, or necessary time",sentence:"He's <strong>late</strong> to work every morning.",tip:"",emoji:"📖",roots:["late"]},
    {word:"leave",chinese:"",definition:"to go away from a place or person",sentence:"The train <strong>leaves</strong> in fifteen minutes.",tip:"",emoji:"📖",roots:["leave"]},
    {word:"manager",chinese:"",definition:"the person who leads a team or company and tells other staff what to do",sentence:"I want to be a <strong>manager</strong> in this company one day.",tip:"",emoji:"📖",roots:["manager"]},
    {word:"message",chinese:"",definition:"a piece of information you write or send to someone",sentence:"Can I leave him a <strong>message</strong>?",tip:"",emoji:"📖",roots:["message"]},
    {word:"life",chinese:"",definition:"the period of time you are alive, your experiences, and your way of living",sentence:"Work is an important part of <strong>life</strong>.",tip:"",emoji:"📖",roots:["life"]},
    {word:"meal",chinese:"",definition:"a time when you eat breakfast, lunch, or dinner; the food you eat at these times",sentence:"If we work late, the company gives us a free <strong>meal</strong>.",tip:"",emoji:"📖",roots:["meal"]},
    {word:"little",chinese:"",definition:"small in size or amount",sentence:"I have a <strong>little</strong> office on the second floor.",tip:"",emoji:"📖",roots:["little"]},
    {word:"lot",chinese:"",definition:"a large number or amount of something",sentence:"I have to write a <strong>lot</strong> of emails every day.",tip:"",emoji:"📖",roots:["lot"]},
    {word:"live",chinese:"",definition:"to have your home in a place",sentence:"I <strong>live</strong> with my family.",tip:"",emoji:"📖",roots:["live"]}
  ]
};
