WORD_DATA["gept_elementary"] = {
  name: "GEPT初級",
  color: "#7c3aed",
  words: [
    {word:"discount",chinese:"折扣",sentence:"There is a 20% <strong>discount</strong> on all shoes.",tip:"DIS(去掉)+COUNT(算)=不算那麼多=打折",emoji:"🏷️",roots:["dis","count"]},
    {word:"cashier",chinese:"收銀員",sentence:"Pay the <strong>cashier</strong> at the counter.",tip:"CASH(現金)+IER=管現金的人",emoji:"💵",roots:["cash","ier"]},
    {word:"change",chinese:"零錢/改變",sentence:"Here is your <strong>change</strong>.",tip:"CHANGE 有兩個意思：改變和零錢",emoji:"🪙",roots:["change"]},
    {word:"credit",chinese:"信用/學分",sentence:"She paid with a <strong>credit</strong> card.",tip:"CRED(相信)+IT=相信你會還錢",emoji:"💳",roots:["cred","it"]},
    {word:"receipt",chinese:"收據",sentence:"Keep the <strong>receipt</strong> for the refund.",tip:"RECEIPT 的 P 不發音！RE+CEIPT",emoji:"🧾",roots:["re","ceipt"]},
    {word:"budget",chinese:"預算",sentence:"We have a limited <strong>budget</strong> for the trip.",tip:"BUDGET 原意是皮袋裝錢=有限的錢",emoji:"💰",roots:["budg","et"]},
    {word:"bargain",chinese:"便宜貨/討價還價",sentence:"This jacket was a real <strong>bargain</strong>!",tip:"BARGAIN=BAR(酒吧)+GAIN(得到)=在酒吧談生意",emoji:"🤝",roots:["bar","gain"]},
    {word:"expense",chinese:"費用/開銷",sentence:"Food is our biggest <strong>expense</strong>.",tip:"EX(外)+PENSE(花)=花出去的錢",emoji:"💸",roots:["ex","pense"]},
    {word:"afford",chinese:"負擔得起",sentence:"I can't <strong>afford</strong> that expensive bag.",tip:"AF(向)+FORD(前進)=能走到那裡=負擔得起",emoji:"💰",roots:["af","ford"]},
    {word:"wallet",chinese:"皮夾",sentence:"Dad's <strong>wallet</strong> is made of leather.",tip:"WALLET 像牆一樣折的小東西",emoji:"👝",roots:["wall","et"]},
    {word:"pharmacy",chinese:"藥局",sentence:"Buy the medicine at the <strong>pharmacy</strong>.",tip:"PHARM(藥)+ACY=和藥有關的地方",emoji:"💊",roots:["pharm","acy"]},
    {word:"clinic",chinese:"診所",sentence:"Go to the <strong>clinic</strong> if you feel sick.",tip:"CLINIC 來自希臘語「床」=病床邊的醫療",emoji:"🏥",roots:["clin","ic"]},
    {word:"cure",chinese:"治療/治癒",sentence:"There is no <strong>cure</strong> for the common cold.",tip:"CURE 和 CARE 只差一個字母",emoji:"💊",roots:["cure"]},
    {word:"recover",chinese:"康復",sentence:"He <strong>recover</strong>ed quickly from the flu.",tip:"RE(再)+COVER(蓋)=再次蓋好=恢復健康",emoji:"😊",roots:["re","cover"]},
    {word:"dizzy",chinese:"頭暈的",sentence:"I feel <strong>dizzy</strong> when I spin around.",tip:"DIZZY 想到頭暈目眩轉圈圈",emoji:"😵",roots:["diz","zy"]},
    {word:"swollen",chinese:"腫脹的",sentence:"His ankle is red and <strong>swollen</strong>.",tip:"SWELL(膨脹)的過去分詞=腫起來的",emoji:"🦶",roots:["swoll","en"]},
    {word:"ointment",chinese:"藥膏",sentence:"Apply this <strong>ointment</strong> to the rash.",tip:"OINT(油)+MENT=塗油的東西=藥膏",emoji:"🧴",roots:["oint","ment"]},
    {word:"semester",chinese:"學期",sentence:"The new <strong>semester</strong> starts in September.",tip:"SEMESTER 來自拉丁語「六個月」",emoji:"📅",roots:["sem","ester"]},
    {word:"assignment",chinese:"作業/任務",sentence:"The <strong>assignment</strong> is due next Monday.",tip:"AS(向)+SIGN(標記)+MENT=被指派的任務",emoji:"📝",roots:["as","sign","ment"]},
    {word:"grade",chinese:"成績/年級",sentence:"She got a good <strong>grade</strong> on the test.",tip:"GRADE 來自拉丁語「階梯」=一級一級",emoji:"📊",roots:["grade"]},
    {word:"tutor",chinese:"家教/輔導",sentence:"I have a math <strong>tutor</strong> on Wednesdays.",tip:"TUTOR 來自拉丁語「守護者」",emoji:"👨‍🏫",roots:["tut","or"]},
    {word:"scholarship",chinese:"獎學金",sentence:"She won a <strong>scholarship</strong> to the university.",tip:"SCHOLAR(學者)+SHIP=學者的身份=獎學金",emoji:"🎓",roots:["scholar","ship"]},
    {word:"diploma",chinese:"文憑/畢業證書",sentence:"He received his <strong>diploma</strong> at graduation.",tip:"DIPLOMA 來自希臘語「折疊的文件」",emoji:"📜",roots:["diplo","ma"]},
    {word:"absent",chinese:"缺席的",sentence:"She was <strong>absent</strong> from school yesterday.",tip:"AB(離開)+SENT(存在)=不在那裡=缺席",emoji:"🚫",roots:["ab","sent"]},
    {word:"social",chinese:"社交的/社會的",sentence:"<strong>Social</strong> media is very popular.",tip:"SOCI(同伴)+AL=和同伴有關的=社交的",emoji:"📱",roots:["soci","al"]},
    {word:"app",chinese:"應用程式",sentence:"Download the <strong>app</strong> on your phone.",tip:"APP 是 APPLICATION 的縮寫",emoji:"📱",roots:["app"]},
    {word:"charge",chinese:"充電/收費",sentence:"I need to <strong>charge</strong> my phone.",tip:"CHARGE 有充電和收費兩個意思",emoji:"🔋",roots:["charge"]},
    {word:"password",chinese:"密碼",sentence:"Don't share your <strong>password</strong> with others.",tip:"PASS(通過)+WORD(字)=通關用的字",emoji:"🔒",roots:["pass","word"]},
    {word:"update",chinese:"更新",sentence:"Please <strong>update</strong> the software.",tip:"UP(向上)+DATE(日期)=跟上最新的",emoji:"🔄",roots:["up","date"]},
    {word:"online",chinese:"線上的",sentence:"I took an <strong>online</strong> course.",tip:"ON(在上)+LINE(線)=在網路線上",emoji:"🌐",roots:["on","line"]},
    {word:"menu",chinese:"菜單",sentence:"Can I see the <strong>menu</strong>, please?",tip:"MENU 來自法語「詳細的清單」",emoji:"📋",roots:["menu"]},
    {word:"appetizer",chinese:"開胃菜",sentence:"We ordered soup as an <strong>appetizer</strong>.",tip:"APPETIT(食慾)+ZER=刺激食慾的東西",emoji:"🥗",roots:["appetit","zer"]},
    {word:"dessert",chinese:"甜點",sentence:"I'll have ice cream for <strong>dessert</strong>.",tip:"DESSERT 有兩個 S=想吃兩次的甜點！",emoji:"🍰",roots:["des","sert"]},
    {word:"spicy",chinese:"辣的",sentence:"This curry is too <strong>spicy</strong> for me.",tip:"SPICE(香料)+Y=有很多香料的=辣的",emoji:"🌶️",roots:["spic","y"]},
    {word:"raw",chinese:"生的/未煮的",sentence:"I don't like eating <strong>raw</strong> fish.",tip:"RAW 想到生肉生魚的感覺",emoji:"🍣",roots:["raw"]},
    {word:"portion",chinese:"份量",sentence:"The <strong>portion</strong> was too big to finish.",tip:"PORTION=PORT(部分)+ION=一部分",emoji:"🍽️",roots:["port","ion"]},
    {word:"flavor",chinese:"口味/味道",sentence:"What <strong>flavor</strong> of ice cream do you want?",tip:"FLAVOR 想到各種味道在嘴裡",emoji:"🍦",roots:["flav","or"]},
    {word:"takeout",chinese:"外帶",sentence:"Let's order <strong>takeout</strong> tonight.",tip:"TAKE(拿)+OUT(外)=拿出去吃",emoji:"🥡",roots:["take","out"]},
    {word:"reservation",chinese:"預訂",sentence:"I made a <strong>reservation</strong> for 7 PM.",tip:"RE(回)+SERVE(保留)+ATION=保留好的位子",emoji:"📝",roots:["re","serv","ation"]},
    {word:"platform",chinese:"月台/平台",sentence:"The train arrives at <strong>platform</strong> 2.",tip:"PLAT(平)+FORM(形狀)=平的地方",emoji:"🚉",roots:["plat","form"]},
    {word:"terminal",chinese:"航站/終點站",sentence:"Go to <strong>terminal</strong> 1 for your flight.",tip:"TERMIN(終點)+AL=終點的地方",emoji:"🛫",roots:["termin","al"]},
    {word:"delay",chinese:"延誤/耽擱",sentence:"The flight has a two-hour <strong>delay</strong>.",tip:"DE(離開)+LAY(放)=放到一邊=延遲",emoji:"⏰",roots:["de","lay"]},
    {word:"passenger",chinese:"乘客",sentence:"All <strong>passenger</strong>s please board now.",tip:"PASS(通過)+ENGER=經過旅程的人",emoji:"✈️",roots:["pass","enger"]},
    {word:"fare",chinese:"車費/票價",sentence:"How much is the bus <strong>fare</strong>?",tip:"FARE 和 FAIR(公平)發音一樣",emoji:"🎫",roots:["fare"]},
    {word:"commute",chinese:"通勤",sentence:"I <strong>commute</strong> to work by train every day.",tip:"COM(一起)+MUTE(改變)=每天來回改變地點",emoji:"🚆",roots:["com","mute"]},
    {word:"transfer",chinese:"轉乘/轉帳",sentence:"You need to <strong>transfer</strong> at the next station.",tip:"TRANS(跨越)+FER(攜帶)=帶到另一邊",emoji:"🔄",roots:["trans","fer"]},
    {word:"performance",chinese:"表演/表現",sentence:"The dance <strong>performance</strong> was wonderful.",tip:"PERFORM(表演)+ANCE=表演的結果",emoji:"🎭",roots:["perform","ance"]},
    {word:"audience",chinese:"觀眾",sentence:"The <strong>audience</strong> clapped loudly.",tip:"AUDI(聽)+ENCE=來聽的人們",emoji:"👏",roots:["audi","ence"]},
    {word:"stage",chinese:"舞台/階段",sentence:"The actor walked onto the <strong>stage</strong>.",tip:"STAGE 也有「階段」的意思",emoji:"🎭",roots:["stage"]},
    {word:"series",chinese:"系列/連續劇",sentence:"I'm watching a new TV <strong>series</strong>.",tip:"SERIES 想到一集接一集",emoji:"📺",roots:["ser","ies"]},
    {word:"episode",chinese:"集/一段經歷",sentence:"Did you watch the latest <strong>episode</strong>?",tip:"EPI(在上面)+SODE(路)=旅程的一段",emoji:"📺",roots:["epi","sode"]},
    {word:"subtitle",chinese:"字幕",sentence:"I watch movies with English <strong>subtitle</strong>s.",tip:"SUB(下面)+TITLE(標題)=畫面下的文字",emoji:"📺",roots:["sub","title"]},
    {word:"landslide",chinese:"山崩/土石流",sentence:"The heavy rain caused a <strong>landslide</strong>.",tip:"LAND(土地)+SLIDE(滑)=土地滑動=山崩",emoji:"⛰️",roots:["land","slide"]},
    {word:"evacuation",chinese:"疏散/撤離",sentence:"The <strong>evacuation</strong> was quick and safe.",tip:"E(外)+VACU(空)+ATION=把人移到外面=疏散",emoji:"🚨",roots:["e","vacu","ation"]},
    {word:"shelter",chinese:"避難所/庇護",sentence:"People went to the <strong>shelter</strong> during the storm.",tip:"SHELTER 想到遮風避雨的地方",emoji:"🏠",roots:["shelt","er"]},
    {word:"rescue",chinese:"救援",sentence:"The team <strong>rescue</strong>d the trapped people.",tip:"RE(回)+SCUE(搖)=搖回來=拉回來=救援",emoji:"🚨",roots:["res","cue"]},
    {word:"victim",chinese:"受害者",sentence:"The <strong>victim</strong>s received food and water.",tip:"VICTIM 來自拉丁語「祭品」",emoji:"🙏",roots:["vict","im"]},
    {word:"emergency",chinese:"緊急情況",sentence:"Call 119 in an <strong>emergency</strong>.",tip:"E(外)+MERGE(出現)+ENCY=突然出現的狀況",emoji:"🚨",roots:["e","merg","ency"]},
    {word:"humorous",chinese:"幽默的",sentence:"He's a very <strong>humorous</strong> person.",tip:"HUMOR(幽默)+OUS=充滿幽默的",emoji:"😄",roots:["humor","ous"]},
    {word:"generous",chinese:"慷慨的",sentence:"She is <strong>generous</strong> with her time.",tip:"GENER(產生)+OUS=產生很多=慷慨",emoji:"🎁",roots:["gener","ous"]},
    {word:"stubborn",chinese:"固執的",sentence:"He's too <strong>stubborn</strong> to change his mind.",tip:"STUB(樹樁)+BORN=像樹樁一樣不動=固執",emoji:"🪵",roots:["stub","born"]},
    {word:"modest",chinese:"謙虛的",sentence:"She is very <strong>modest</strong> about her success.",tip:"MOD(適度)+EST=保持適度的=謙虛的",emoji:"🙏",roots:["mod","est"]},
    {word:"mature",chinese:"成熟的",sentence:"He is very <strong>mature</strong> for his age.",tip:"MATURE 來自拉丁語「到了時候」",emoji:"🌳",roots:["ma","ture"]},
    {word:"patient",chinese:"有耐心的/病人",sentence:"Be <strong>patient</strong>; your turn will come.",tip:"PATI(忍受)+ENT=能忍受等待的",emoji:"⏳",roots:["pati","ent"]},
    {word:"sincere",chinese:"真誠的",sentence:"She gave a <strong>sincere</strong> apology.",tip:"SINCERE 來自拉丁語「純淨的」",emoji:"❤️",roots:["sin","cere"]},
    {word:"selfish",chinese:"自私的",sentence:"Don't be so <strong>selfish</strong>; share with others.",tip:"SELF(自己)+ISH=只想自己的",emoji:"😤",roots:["self","ish"]},
    {word:"loyal",chinese:"忠誠的",sentence:"A dog is a <strong>loyal</strong> friend.",tip:"LOYAL 來自法語「法律」=守法=忠誠",emoji:"🐕",roots:["loy","al"]},
    {word:"acquaintance",chinese:"認識的人/相識",sentence:"He's just an <strong>acquaintance</strong>, not a close friend.",tip:"AC(向)+QUAINT(認識)+ANCE=認識但不熟的人",emoji:"🤝",roots:["ac","quaint","ance"]},
    {word:"neighbor",chinese:"鄰居",sentence:"Our <strong>neighbor</strong> is very friendly.",tip:"NEIGH(靠近)+BOR(住)=住在附近的人",emoji:"🏘️",roots:["neigh","bor"]},
    {word:"classmate",chinese:"同學",sentence:"She has been my <strong>classmate</strong> for three years.",tip:"CLASS(班級)+MATE(夥伴)=班上的夥伴",emoji:"👫",roots:["class","mate"]},
    {word:"stranger",chinese:"陌生人",sentence:"Never accept gifts from a <strong>stranger</strong>.",tip:"STRANGE(奇怪)+R=不認識的奇怪人",emoji:"🚫",roots:["strang","er"]},
    {word:"relative",chinese:"親戚",sentence:"We visit our <strong>relative</strong>s during Chinese New Year.",tip:"RELAT(聯繫)+IVE=有血緣聯繫的人",emoji:"👨‍👩‍👧",roots:["relat","ive"]},
    {word:"schedule",chinese:"時間表/行程",sentence:"Check the bus <strong>schedule</strong> online.",tip:"SCHEDULE 美式發音 /skedʒul/",emoji:"📅",roots:["sched","ule"]},
    {word:"appointment",chinese:"預約",sentence:"I have a dentist <strong>appointment</strong> at 3 PM.",tip:"AP(向)+POINT(指定)+MENT=指定好的時間",emoji:"📅",roots:["ap","point","ment"]},
    {word:"routine",chinese:"例行公事/日常",sentence:"Exercise is part of my daily <strong>routine</strong>.",tip:"ROUTINE=ROUTE(路線)+INE=每天走的固定路線",emoji:"🔄",roots:["rout","ine"]},
    {word:"errand",chinese:"差事/跑腿",sentence:"I need to run some <strong>errand</strong>s today.",tip:"ERRAND 想到出門辦事跑來跑去",emoji:"🏃",roots:["err","and"]},
    {word:"chore",chinese:"家事/雜務",sentence:"Washing dishes is my least favourite <strong>chore</strong>.",tip:"CHORE 想到每天必須做的無聊事",emoji:"🧹",roots:["chore"]},
    {word:"opportunity",chinese:"機會",sentence:"This is a great <strong>opportunity</strong> to learn.",tip:"OP(向)+PORT(門)+UNITY=門向你打開=機會",emoji:"🚪",roots:["op","port","unity"]},
    {word:"purpose",chinese:"目的/用途",sentence:"What is the <strong>purpose</strong> of this meeting?",tip:"PUR(向前)+POSE(放)=放在前面的目標",emoji:"🎯",roots:["pur","pose"]},
    {word:"advantage",chinese:"優勢/好處",sentence:"Speaking two languages is an <strong>advantage</strong>.",tip:"AD(向)+VANT(前)+AGE=走在前面=優勢",emoji:"💪",roots:["ad","vant","age"]},
    {word:"effort",chinese:"努力",sentence:"Put more <strong>effort</strong> into your studies.",tip:"EF(外)+FORT(力)=使出力量",emoji:"💪",roots:["ef","fort"]},
    {word:"progress",chinese:"進步/進展",sentence:"You've made great <strong>progress</strong> this year.",tip:"PRO(向前)+GRESS(走)=向前走=進步",emoji:"📈",roots:["pro","gress"]},
    {word:"succeed",chinese:"成功",sentence:"If you work hard, you will <strong>succeed</strong>.",tip:"SUC(在下面)+CEED(走)=跟隨目標走=成功",emoji:"🏆",roots:["suc","ceed"]},
    {word:"failure",chinese:"失敗",sentence:"Don't be afraid of <strong>failure</strong>.",tip:"FAIL(失敗)+URE=失敗的結果",emoji:"😔",roots:["fail","ure"]},
    {word:"achieve",chinese:"達成/實現",sentence:"She <strong>achieve</strong>d her dream of becoming a doctor.",tip:"A(向)+CHIEVE(首領)=到達首位=達成",emoji:"🌟",roots:["a","chieve"]},
    {word:"experience",chinese:"經驗/體驗",sentence:"Traveling is a wonderful <strong>experience</strong>.",tip:"EX(外)+PERI(嘗試)+ENCE=向外嘗試=經驗",emoji:"✨",roots:["ex","peri","ence"]},
    {word:"complain",chinese:"抱怨",sentence:"Don't <strong>complain</strong>; just try your best.",tip:"COM(一起)+PLAIN(哭)=一直哭哭=抱怨",emoji:"😤",roots:["com","plain"]},
    {word:"appreciate",chinese:"感激/欣賞",sentence:"I really <strong>appreciate</strong> your help.",tip:"AP(向)+PRECI(價值)+ATE=認為有價值=感激",emoji:"🙏",roots:["ap","preci","ate"]},
    {word:"recommend",chinese:"推薦",sentence:"I <strong>recommend</strong> this restaurant.",tip:"RE(再)+COM(一起)+MEND(託付)=再次託付=推薦",emoji:"👍",roots:["re","com","mend"]},
    {word:"confirm",chinese:"確認",sentence:"Please <strong>confirm</strong> your reservation.",tip:"CON(一起)+FIRM(堅固)=使堅固=確認",emoji:"✅",roots:["con","firm"]},
    {word:"cancel",chinese:"取消",sentence:"I need to <strong>cancel</strong> my appointment.",tip:"CANCEL 來自拉丁語「劃格子」=把字劃掉=取消",emoji:"❌",roots:["canc","el"]},
    {word:"reserve",chinese:"預訂/保留",sentence:"I'd like to <strong>reserve</strong> a table for two.",tip:"RE(回)+SERVE(保存)=保存回來=預訂",emoji:"📝",roots:["re","serve"]},
    {word:"deliver",chinese:"遞送",sentence:"They <strong>deliver</strong> pizza to your house.",tip:"DE(離)+LIVER(交出)=送出去=遞送",emoji:"📦",roots:["de","liver"]},
    {word:"exchange",chinese:"交換/兌換",sentence:"Can I <strong>exchange</strong> this shirt for a bigger size?",tip:"EX(外)+CHANGE(改變)=向外改變=交換",emoji:"🔄",roots:["ex","change"]},
    {word:"refund",chinese:"退款",sentence:"Can I get a <strong>refund</strong> for this?",tip:"RE(回)+FUND(資金)=把錢退回來",emoji:"💰",roots:["re","fund"]},
    {word:"register",chinese:"登記/註冊",sentence:"You need to <strong>register</strong> for the class.",tip:"RE(回)+GIST(記錄)+ER=記錄下來=登記",emoji:"📝",roots:["re","gist","er"]},
    {word:"display",chinese:"展示/陳列",sentence:"The paintings are on <strong>display</strong> in the gallery.",tip:"DIS(分開)+PLAY(展開)=展開給人看",emoji:"🖼️",roots:["dis","play"]},
    {word:"annual",chinese:"每年的",sentence:"The school has an <strong>annual</strong> sports day.",tip:"ANNU(年)+AL=每年的",emoji:"📅",roots:["annu","al"]},
    {word:"graduation",chinese:"畢業",sentence:"<strong>Graduation</strong> is in June.",tip:"GRADU(步驟)+ATION=完成一個階段",emoji:"🎓",roots:["gradu","ation"]},
    {word:"reunion",chinese:"團聚/重逢",sentence:"We have a family <strong>reunion</strong> every year.",tip:"RE(再)+UNION(聯合)=再次聯合=團聚",emoji:"👨‍👩‍👧‍👦",roots:["re","union"]},
    {word:"tradition",chinese:"傳統",sentence:"Eating mooncakes is a Chinese <strong>tradition</strong>.",tip:"TRADIT(傳遞)+ION=傳遞下來的東西",emoji:"🥮",roots:["tradit","ion"]},
    {word:"opinion",chinese:"意見/看法",sentence:"What's your <strong>opinion</strong> on this?",tip:"OPINION 來自拉丁語「想法」",emoji:"💭",roots:["opin","ion"]},
    {word:"describe",chinese:"描述",sentence:"Can you <strong>describe</strong> what happened?",tip:"DE(下)+SCRIBE(寫)=寫下來=描述",emoji:"📝",roots:["de","scribe"]},
    {word:"compare",chinese:"比較",sentence:"<strong>Compare</strong> these two prices.",tip:"COM(一起)+PARE(相等)=放在一起看相不相等",emoji:"⚖️",roots:["com","pare"]},
    {word:"consider",chinese:"考慮",sentence:"I'll <strong>consider</strong> your suggestion.",tip:"CON(一起)+SIDER(星星)=看星星想事情=考慮",emoji:"🤔",roots:["con","sider"]},
    {word:"imagine",chinese:"想像",sentence:"<strong>Imagine</strong> you are on a tropical island.",tip:"IMAGE(影像)+INE=在腦中形成影像",emoji:"💭",roots:["imagin","e"]},
    {word:"mention",chinese:"提到/提及",sentence:"She <strong>mention</strong>ed your name in the meeting.",tip:"MENT(心/記住)+ION=記住並說出來=提到",emoji:"🗣️",roots:["ment","ion"]},
    {word:"promise",chinese:"承諾/保證",sentence:"I <strong>promise</strong> I will be on time.",tip:"PRO(向前)+MISE(送)=向前送出去的話=承諾",emoji:"🤝",roots:["pro","mise"]},
    {word:"deny",chinese:"否認",sentence:"He <strong>denied</strong> breaking the window.",tip:"DENY=DE(向下)+NY(不)=向下說不=否認",emoji:"🙅",roots:["de","ny"]},
    {word:"request",chinese:"要求/請求",sentence:"She made a special <strong>request</strong>.",tip:"RE(再)+QUEST(尋求)=再次尋求=請求",emoji:"🙏",roots:["re","quest"]},
    {word:"refuse",chinese:"拒絕",sentence:"She <strong>refuse</strong>d to eat the vegetables.",tip:"RE(回)+FUSE(倒)=倒回去=拒絕接受",emoji:"🙅‍♀️",roots:["re","fuse"]},
    {word:"accept",chinese:"接受",sentence:"I'm happy to <strong>accept</strong> your invitation.",tip:"AC(向)+CEPT(拿)=拿過來=接受",emoji:"🤝",roots:["ac","cept"]},
    {word:"decision",chinese:"決定",sentence:"It was a difficult <strong>decision</strong>.",tip:"DE(下)+CIS(切)+ION=切下去=做決定",emoji:"⚡",roots:["de","cis","ion"]},
    {word:"confident",chinese:"有信心的",sentence:"She is <strong>confident</strong> about passing the test.",tip:"CON(完全)+FID(信任)+ENT=完全相信=有信心",emoji:"😎",roots:["con","fid","ent"]},
    {word:"creative",chinese:"有創意的",sentence:"She's very <strong>creative</strong> and loves drawing.",tip:"CREATE(創造)+IVE=能創造的",emoji:"🎨",roots:["creat","ive"]},
    {word:"curious",chinese:"好奇的",sentence:"Children are naturally <strong>curious</strong>.",tip:"CUR(關心)+IOUS=很想關心的=好奇的",emoji:"🔍",roots:["cur","ious"]},
    {word:"convenient",chinese:"方便的",sentence:"Living near school is very <strong>convenient</strong>.",tip:"CON(一起)+VEN(來)+IENT=一起來=方便",emoji:"👍",roots:["con","ven","ient"]},
    {word:"transportation",chinese:"交通/運輸",sentence:"Public <strong>transportation</strong> is cheap here.",tip:"TRANS(跨越)+PORT(帶)+ATION=帶到對面=運輸",emoji:"🚌",roots:["trans","port","ation"]},
    {word:"crowded",chinese:"擁擠的",sentence:"The bus is very <strong>crowded</strong> during rush hour.",tip:"CROWD(人群)+ED=充滿人群的",emoji:"🚌",roots:["crowd","ed"]},
    {word:"sustainable",chinese:"永續的",sentence:"We need <strong>sustainable</strong> energy sources.",tip:"SUS(下面)+TAIN(持有)+ABLE=能持續保持的",emoji:"🌱",roots:["sus","tain","able"]},
    {word:"aware",chinese:"意識到的/察覺的",sentence:"Are you <strong>aware</strong> of the rules?",tip:"A(在)+WARE(看)=在看著=有意識的",emoji:"👁️",roots:["a","ware"]},
    {word:"global",chinese:"全球的",sentence:"<strong>Global</strong> warming affects everyone.",tip:"GLOBE(地球)+AL=和全地球有關的",emoji:"🌍",roots:["glob","al"]},
    {word:"donate",chinese:"捐贈",sentence:"They <strong>donate</strong>d money to the charity.",tip:"DON(給)+ATE=給出去=捐贈",emoji:"💝",roots:["don","ate"]},
    {word:"welfare",chinese:"福利/福祉",sentence:"The government cares about public <strong>welfare</strong>.",tip:"WELL(好)+FARE(過)=過得好=福利",emoji:"🏥",roots:["wel","fare"]},
    {word:"stress",chinese:"壓力",sentence:"Too much <strong>stress</strong> is bad for your health.",tip:"STRESS 想到壓力壓在身上",emoji:"😓",roots:["stress"]},
    {word:"pressure",chinese:"壓力/壓迫",sentence:"Don't put too much <strong>pressure</strong> on yourself.",tip:"PRESS(壓)+URE=壓的力量",emoji:"😰",roots:["press","ure"]},
    {word:"emotion",chinese:"情緒/情感",sentence:"Music can express many <strong>emotion</strong>s.",tip:"E(外)+MOT(動)+ION=心被觸動=情緒",emoji:"😊",roots:["e","mot","ion"]},
    {word:"bored",chinese:"無聊的",sentence:"I'm so <strong>bored</strong> with nothing to do.",tip:"BORE(鑽孔/使無聊)+D=感到無趣的",emoji:"😴",roots:["bore","d"]},
    {word:"impression",chinese:"印象",sentence:"She made a good <strong>impression</strong> on everyone.",tip:"IM(裡面)+PRESS(壓)+ION=壓進心裡=印象",emoji:"💡",roots:["im","press","ion"]},
    {word:"attitude",chinese:"態度",sentence:"A positive <strong>attitude</strong> is important.",tip:"ATTITUDE=APT(適合)+ITUDE=適合的姿態=態度",emoji:"💪",roots:["att","itude"]},
    {word:"personality",chinese:"人格/性格",sentence:"He has a cheerful <strong>personality</strong>.",tip:"PERSON(人)+ALITY=人的特質=性格",emoji:"🧑",roots:["person","ality"]},
    {word:"talent",chinese:"才能/天賦",sentence:"She has a <strong>talent</strong> for music.",tip:"TALENT 古時是重量單位=有份量的能力",emoji:"⭐",roots:["tal","ent"]},
    {word:"challenge",chinese:"挑戰",sentence:"This math problem is a real <strong>challenge</strong>.",tip:"CHALLENGE 想到向你發起的挑戰",emoji:"🏋️",roots:["chall","enge"]},
    {word:"competition",chinese:"比賽/競爭",sentence:"She entered a writing <strong>competition</strong>.",tip:"COM(一起)+PET(追)+ITION=一起追=競爭",emoji:"🏆",roots:["com","pet","ition"]},
    {word:"cooperation",chinese:"合作",sentence:"<strong>Cooperation</strong> is the key to success.",tip:"CO(一起)+OPER(工作)+ATION=一起工作",emoji:"🤝",roots:["co","oper","ation"]},
    {word:"participate",chinese:"參加/參與",sentence:"Everyone should <strong>participate</strong> in the activity.",tip:"PART(部分)+ICIP+ATE=成為一部分=參與",emoji:"🙋",roots:["part","icip","ate"]},
    {word:"organize",chinese:"組織/安排",sentence:"Who will <strong>organize</strong> the school trip?",tip:"ORGAN(器官/組織)+IZE=使成為有組織的",emoji:"📋",roots:["organ","ize"]},
    {word:"arrange",chinese:"安排/排列",sentence:"Let me <strong>arrange</strong> a meeting for us.",tip:"AR(向)+RANGE(排列)=排列好=安排",emoji:"📅",roots:["ar","range"]},
    {word:"influence",chinese:"影響",sentence:"Parents have a big <strong>influence</strong> on children.",tip:"IN(裡面)+FLU(流)+ENCE=流進去的力量=影響",emoji:"🌊",roots:["in","flu","ence"]},
    {word:"document",chinese:"文件",sentence:"Sign the <strong>document</strong> here, please.",tip:"DOC(教)+UMENT=教人的東西=記錄文件",emoji:"📄",roots:["docu","ment"]},
    {word:"announcement",chinese:"公告/宣布",sentence:"There will be an important <strong>announcement</strong>.",tip:"AN(向)+NOUNCE(報告)+MENT=向大家報告",emoji:"📢",roots:["an","nounce","ment"]},
    {word:"celebrate",chinese:"慶祝",sentence:"Let's <strong>celebrate</strong> your birthday!",tip:"CELEBR(聚集/慶祝)+ATE=一起慶祝",emoji:"🎉",roots:["celebr","ate"]},
    {word:"prepare",chinese:"準備",sentence:"I need to <strong>prepare</strong> for the exam.",tip:"PRE(之前)+PARE(準備)=事先準備好",emoji:"📚",roots:["pre","pare"]},
    {word:"publish",chinese:"出版/發表",sentence:"She wants to <strong>publish</strong> a novel.",tip:"PUB(公開)+LISH=使公開=出版",emoji:"📖",roots:["pub","lish"]},
    {word:"bilingual",chinese:"雙語的",sentence:"She is <strong>bilingual</strong> in Chinese and English.",tip:"BI(兩)+LINGUAL(語言)=兩種語言的",emoji:"🗣️",roots:["bi","lingual"]},
    {word:"communicate",chinese:"溝通",sentence:"It's important to <strong>communicate</strong> clearly.",tip:"COM(一起)+MUNIC(分享)+ATE=一起分享=溝通",emoji:"🗣️",roots:["com","munic","ate"]},
    {word:"abroad",chinese:"在國外",sentence:"She wants to study <strong>abroad</strong>.",tip:"A(在)+BROAD(寬廣的)=在寬廣的外面=國外",emoji:"✈️",roots:["a","broad"]},
    {word:"region",chinese:"地區/區域",sentence:"This <strong>region</strong> is famous for its tea.",tip:"REG(統治)+ION=被統治的範圍=地區",emoji:"🗺️",roots:["reg","ion"]},
    {word:"citizen",chinese:"市民/公民",sentence:"Every <strong>citizen</strong> should vote.",tip:"CIT(城市)+IZEN=城市的人=公民",emoji:"🏙️",roots:["cit","izen"]},
    {word:"population",chinese:"人口",sentence:"The <strong>population</strong> of Taiwan is about 23 million.",tip:"POPUL(人民)+ATION=人民的總數=人口",emoji:"👥",roots:["popul","ation"]},
    {word:"historic",chinese:"歷史上有名的",sentence:"This is a <strong>historic</strong> building.",tip:"HISTOR(歷史)+IC=在歷史中重要的",emoji:"🏛️",roots:["histor","ic"]},
    {word:"modern",chinese:"現代的",sentence:"This is a very <strong>modern</strong> building.",tip:"MODERN=MODE(方式)+RN=現在的方式",emoji:"🏙️",roots:["mod","ern"]},
    {word:"technology",chinese:"科技",sentence:"<strong>Technology</strong> is changing the world fast.",tip:"TECHNO(技術)+LOGY(學問)=技術的學問",emoji:"💻",roots:["techno","logy"]},
    {word:"ordinary",chinese:"普通的/平凡的",sentence:"It was just an <strong>ordinary</strong> day.",tip:"ORDIN(順序)+ARY=照順序排的=普通的",emoji:"🙂",roots:["ordin","ary"]},
    {word:"typical",chinese:"典型的",sentence:"This is a <strong>typical</strong> Taiwanese breakfast.",tip:"TYP(類型)+ICAL=代表這種類型的",emoji:"📌",roots:["typ","ical"]},
    {word:"probably",chinese:"大概/可能",sentence:"It will <strong>probably</strong> rain tomorrow.",tip:"PROB(證明)+ABLY=能被證明的=可能",emoji:"🤔",roots:["prob","ably"]},
    {word:"especially",chinese:"特別是/尤其",sentence:"I love fruit, <strong>especially</strong> mangoes.",tip:"E(外)+SPECIAL(特別)+LY=特別地",emoji:"⭐",roots:["e","special","ly"]},
    {word:"recently",chinese:"最近",sentence:"I <strong>recently</strong> started learning guitar.",tip:"RECENT(最近的)+LY=在最近",emoji:"🕐",roots:["recent","ly"]},
    {word:"eventually",chinese:"最終/終於",sentence:"He <strong>eventually</strong> found his lost keys.",tip:"E(外)+VENT(來)+UALLY=出來了=最終",emoji:"🏁",roots:["e","vent","ually"]},
    {word:"immediately",chinese:"立即/馬上",sentence:"Come here <strong>immediately</strong>!",tip:"IM(不)+MEDI(中間)+ATELY=不需要中間過程=立即",emoji:"⚡",roots:["im","medi","ately"]},
    {word:"furniture",chinese:"家具",sentence:"We bought new <strong>furniture</strong> for the living room.",tip:"FURN(提供)+ITURE=提供使用的東西=家具",emoji:"🛋️",roots:["furn","iture"]},
    {word:"satisfaction",chinese:"滿足/滿意",sentence:"Customer <strong>satisfaction</strong> is our priority.",tip:"SATIS(足夠)+FACTION(做)=做到足夠=滿意",emoji:"😊",roots:["satis","fact","ion"]},
    {word:"solution",chinese:"解決方法/溶液",sentence:"We need to find a <strong>solution</strong> to this problem.",tip:"SOLUT(鬆開)+ION=把問題鬆開=解決",emoji:"💡",roots:["solut","ion"]},
    {word:"method",chinese:"方法",sentence:"This is the best <strong>method</strong> for studying.",tip:"METH(跟隨)+OD(路)=跟著走的路=方法",emoji:"📊",roots:["meth","od"]},
    {word:"instruction",chinese:"指示/說明",sentence:"Follow the <strong>instruction</strong>s carefully.",tip:"IN(裡面)+STRUCT(建造)+ION=建造的步驟=指示",emoji:"📋",roots:["in","struct","ion"]},
    {word:"survey",chinese:"調查/問卷",sentence:"Please fill out this <strong>survey</strong>.",tip:"SUR(上面)+VEY(看)=從上面看全貌=調查",emoji:"📊",roots:["sur","vey"]},
    {word:"percentage",chinese:"百分比",sentence:"A large <strong>percentage</strong> of students passed.",tip:"PER(每)+CENT(百)+AGE=每一百中佔多少",emoji:"📊",roots:["per","cent","age"]},
    {word:"temperature",chinese:"溫度/體溫",sentence:"The <strong>temperature</strong> today is 32 degrees.",tip:"TEMPER(調節)+ATURE=調節的程度=溫度",emoji:"🌡️",roots:["temper","ature"]},
    {word:"occupation",chinese:"職業",sentence:"What is your <strong>occupation</strong>?",tip:"OC(向)+CUP(拿)+ATION=拿來做的事=職業",emoji:"💼",roots:["oc","cup","ation"]},
    {word:"salary",chinese:"薪水",sentence:"He earns a good <strong>salary</strong>.",tip:"SALARY 來自拉丁語「鹽」(古代用鹽當薪水)",emoji:"💰",roots:["sal","ary"]},
    {word:"colleague",chinese:"同事",sentence:"She had lunch with her <strong>colleague</strong>s.",tip:"COL(一起)+LEAGUE(選擇)=一起被選的人=同事",emoji:"👥",roots:["col","league"]},
    {word:"interview",chinese:"面試/訪問",sentence:"I have a job <strong>interview</strong> tomorrow.",tip:"INTER(之間)+VIEW(看)=互相看=面試",emoji:"🤝",roots:["inter","view"]},
    {word:"resume",chinese:"履歷",sentence:"Send your <strong>resume</strong> to apply for the job.",tip:"RESUME 來自法語「總結」=人生總結",emoji:"📄",roots:["re","sume"]},
    {word:"economy",chinese:"經濟",sentence:"The <strong>economy</strong> is growing this year.",tip:"ECO(家)+NOMY(管理)=管理家務=經濟",emoji:"📈",roots:["eco","nomy"]},
    {word:"industry",chinese:"工業/產業",sentence:"The tech <strong>industry</strong> is booming.",tip:"INDUSTR(勤勞)+Y=勤勞地工作=工業",emoji:"🏭",roots:["industr","y"]},
    {word:"supply",chinese:"供應/補給",sentence:"The store has a good <strong>supply</strong> of fresh fruit.",tip:"SUP(下面)+PLY(填)=從下面填滿=供應",emoji:"📦",roots:["sup","ply"]},
    {word:"demand",chinese:"需求/要求",sentence:"There is high <strong>demand</strong> for this product.",tip:"DE(完全)+MAND(命令)=強烈要求=需求",emoji:"📈",roots:["de","mand"]},
    {word:"product",chinese:"產品",sentence:"This is our best-selling <strong>product</strong>.",tip:"PRO(向前)+DUCT(帶)=帶出來的東西=產品",emoji:"📦",roots:["pro","duct"]},
    {word:"quality",chinese:"品質",sentence:"This brand is known for its high <strong>quality</strong>.",tip:"QUAL(什麼樣)+ITY=是什麼樣子的=品質",emoji:"⭐",roots:["qual","ity"]},
    {word:"consumer",chinese:"消費者",sentence:"<strong>Consumer</strong>s want lower prices.",tip:"CON(完全)+SUM(拿)+ER=把東西拿來用的人",emoji:"🛍️",roots:["con","sum","er"]},
    {word:"previous",chinese:"先前的/以前的",sentence:"I met him at a <strong>previous</strong> meeting.",tip:"PRE(之前)+VI(路)+OUS=走在前面的=先前的",emoji:"⏪",roots:["pre","vi","ous"]},
    {word:"current",chinese:"目前的/水流",sentence:"What is your <strong>current</strong> address?",tip:"CURR(跑)+ENT=正在跑的=目前的",emoji:"🔄",roots:["curr","ent"]},
    {word:"various",chinese:"各種各樣的",sentence:"There are <strong>various</strong> options to choose from.",tip:"VARI(變化)+OUS=有很多變化的=各種的",emoji:"🌈",roots:["vari","ous"]},
    {word:"specific",chinese:"特定的/具體的",sentence:"Can you give a <strong>specific</strong> example?",tip:"SPEC(看)+IFIC=看得清楚的=具體的",emoji:"🔍",roots:["spec","ific"]},
    {word:"obvious",chinese:"明顯的",sentence:"The answer is <strong>obvious</strong>.",tip:"OB(對面)+VI(路)+OUS=擋在路前面的=明顯的",emoji:"👀",roots:["ob","vi","ous"]},
    {word:"necessary",chinese:"必要的",sentence:"Sleep is <strong>necessary</strong> for good health.",tip:"NE(不)+CESS(走開)+ARY=不能走開的=必要的",emoji:"❗",roots:["ne","cess","ary"]},
    {word:"worth",chinese:"值得的",sentence:"This book is <strong>worth</strong> reading.",tip:"WORTH 想到東西的價值",emoji:"💎",roots:["worth"]},
    {word:"accurate",chinese:"精確的/準確的",sentence:"Make sure your answer is <strong>accurate</strong>.",tip:"AC(向)+CUR(關心)+ATE=仔細關心的=精確的",emoji:"🎯",roots:["ac","cur","ate"]},
    {word:"efficient",chinese:"有效率的",sentence:"This machine is very <strong>efficient</strong>.",tip:"EF(外)+FICI(做)+ENT=做出成果的=有效率的",emoji:"⚡",roots:["ef","fici","ent"]},
    {word:"available",chinese:"可得到的/有空的",sentence:"Is this book <strong>available</strong> in the library?",tip:"A(向)+VAIL(有價值)+ABLE=能得到的",emoji:"✅",roots:["a","vail","able"]},
    {word:"flexible",chinese:"有彈性的/靈活的",sentence:"I have a <strong>flexible</strong> schedule.",tip:"FLEX(彎曲)+IBLE(能)=能彎曲的=靈活的",emoji:"🤸",roots:["flex","ible"]},
    {word:"significant",chinese:"重要的/顯著的",sentence:"This is a <strong>significant</strong> improvement.",tip:"SIGN(記號)+IFIC+ANT=做了記號的=重要的",emoji:"⭐",roots:["sign","ific","ant"]},
    {word:"duty-free",chinese:"免稅的",sentence:"She bought perfume at the <strong>duty-free</strong> shop.",tip:"DUTY(稅)+FREE(免)=免稅的",emoji:"🛍️",roots:["duty","free"]},
    {word:"currency",chinese:"貨幣",sentence:"The local <strong>currency</strong> is New Taiwan Dollar.",tip:"CURR(流通)+ENCY=流通的東西=錢",emoji:"💴",roots:["curr","ency"]},
    {word:"visa",chinese:"簽證",sentence:"You need a <strong>visa</strong> to enter some countries.",tip:"VISA 來自拉丁語「看過了」=已經檢查過",emoji:"📃",roots:["visa"]},
    {word:"sightseeing",chinese:"觀光",sentence:"We went <strong>sightseeing</strong> in the old town.",tip:"SIGHT(景色)+SEEING(看)=看景色=觀光",emoji:"📸",roots:["sight","seeing"]},
    {word:"accommodation",chinese:"住宿",sentence:"The <strong>accommodation</strong> is included in the price.",tip:"AC(向)+COM(一起)+MOD(模式)+ATION=安排住的模式",emoji:"🏨",roots:["ac","com","mod","ation"]},
    {word:"itinerary",chinese:"行程表",sentence:"Here is our travel <strong>itinerary</strong>.",tip:"ITINER(旅行)+ARY=旅行的計畫",emoji:"🗺️",roots:["itiner","ary"]},
    {word:"brochure",chinese:"宣傳冊",sentence:"Pick up a <strong>brochure</strong> at the tourist office.",tip:"BROCHURE=用釘子裝訂的小冊子",emoji:"📄",roots:["broch","ure"]},
    {word:"immigrant",chinese:"移民",sentence:"Many <strong>immigrant</strong>s came to this country.",tip:"IM(裡面)+MIGR(移動)+ANT=移動進來的人",emoji:"🧳",roots:["im","migr","ant"]},
    {word:"heatwave",chinese:"熱浪",sentence:"The <strong>heatwave</strong> lasted for two weeks.",tip:"HEAT(熱)+WAVE(浪)=一波熱浪",emoji:"🥵",roots:["heat","wave"]},
    {word:"monsoon",chinese:"季風/雨季",sentence:"The <strong>monsoon</strong> season brings heavy rain.",tip:"MONSOON 來自阿拉伯語「季節」",emoji:"🌧️",roots:["mon","soon"]},
    {word:"shortage",chinese:"短缺",sentence:"There is a water <strong>shortage</strong> this summer.",tip:"SHORT(短)+AGE=缺少的狀態",emoji:"🚰",roots:["short","age"]}
  ]
};
