WORD_DATA["toeic"] = {
  name: "TOEIC",
  color: "#d97706",
  words: [
    {word:"appointment",chinese:"約會/預約",sentence:"I have an <strong>appointment</strong> with the dentist at 3 PM.",tip:"APPOINT(指定)+MENT=指定的時間",emoji:"📅",roots:["ap","point","ment"]},
    {word:"accommodate",chinese:"容納/提供住宿",sentence:"The hotel can <strong>accommodate</strong> up to 500 guests.",tip:"AC(向)+COM(一起)+MOD(方式)+ATE=用適當方式接待",emoji:"🏨",roots:["ac","com","mod","ate"]},
    {word:"acquisition",chinese:"收購/獲得",sentence:"The company announced the <strong>acquisition</strong> of a competitor.",tip:"AC(向)+QUIS(尋求)+ITION=尋求獲得=收購",emoji:"🤝",roots:["ac","quis","ition"]},
    {word:"agenda",chinese:"議程/日程",sentence:"The meeting <strong>agenda</strong> includes three main topics.",tip:"AGENDA=要做的事情的清單=議程",emoji:"📋",roots:["agenda"]},
    {word:"allocate",chinese:"分配/撥出",sentence:"The manager will <strong>allocate</strong> resources to each team.",tip:"AL(向)+LOC(地方)+ATE=放到各個地方=分配",emoji:"📊",roots:["al","loc","ate"]},
    {word:"amendment",chinese:"修正/修改",sentence:"The contract requires a minor <strong>amendment</strong>.",tip:"A+MEND(修正)+MENT=修正的結果=修改",emoji:"📝",roots:["a","mend","ment"]},
    {word:"applicant",chinese:"申請人/應聘者",sentence:"Over 200 <strong>applicants</strong> applied for the position.",tip:"APPLIC(申請)+ANT=申請的人=申請人",emoji:"📄",roots:["applic","ant"]},
    {word:"appraisal",chinese:"評估/鑑定",sentence:"The annual performance <strong>appraisal</strong> is next week.",tip:"AP(向)+PRAIS(價格)+AL=給出價格=評估",emoji:"📊",roots:["ap","prais","al"]},
    {word:"apprentice",chinese:"學徒/實習生",sentence:"She started as an <strong>apprentice</strong> at the firm.",tip:"AP(向)+PRENT(學習)+ICE=向前學習的人=學徒",emoji:"👨‍🎓",roots:["ap","prent","ice"]},
    {word:"authorize",chinese:"授權/批准",sentence:"Only the director can <strong>authorize</strong> this expenditure.",tip:"AUTHOR(作者/權威)+IZE=給予權威=授權",emoji:"✅",roots:["author","ize"]},
    {word:"bankruptcy",chinese:"破產/倒閉",sentence:"The company filed for <strong>bankruptcy</strong> last month.",tip:"BANK(銀行)+RUPT(破壞)+CY=銀行被破壞=破產",emoji:"💔",roots:["bank","rupt","cy"]},
    {word:"benchmark",chinese:"基準/標準",sentence:"This report sets the <strong>benchmark</strong> for quality.",tip:"BENCH(台)+MARK(記號)=台上的標記=基準",emoji:"📏",roots:["bench","mark"]},
    {word:"brochure",chinese:"小冊子/宣傳冊",sentence:"Please take a <strong>brochure</strong> about our services.",tip:"BROCHURE=用釘子裝訂的小冊子=宣傳冊",emoji:"📰",roots:["brochure"]},
    {word:"budget",chinese:"預算/經費",sentence:"We need to stay within <strong>budget</strong> this quarter.",tip:"BUDGET=皮袋裝錢=預算",emoji:"💰",roots:["budget"]},
    {word:"candidate",chinese:"候選人/應試者",sentence:"Three <strong>candidates</strong> are shortlisted for the role.",tip:"CANDID(白色)+ATE=穿白袍的羅馬競選者=候選人",emoji:"🧑‍💼",roots:["candid","ate"]},
    {word:"capacity",chinese:"能力/容量",sentence:"The factory is operating at full <strong>capacity</strong>.",tip:"CAPAC(容納)+ITY=容納的量=容量",emoji:"🏭",roots:["capac","ity"]},
    {word:"cashier",chinese:"收銀員/出納",sentence:"Please pay the <strong>cashier</strong> at the front desk.",tip:"CASH(現金)+IER=管理現金的人=收銀員",emoji:"💵",roots:["cash","ier"]},
    {word:"certificate",chinese:"證書/執照",sentence:"She earned a professional <strong>certificate</strong> in accounting.",tip:"CERTIF(確認)+ICATE=確認合格的文件=證書",emoji:"📜",roots:["certif","icate"]},
    {word:"chairman",chinese:"主席/董事長",sentence:"The <strong>chairman</strong> opened the annual meeting.",tip:"CHAIR(椅子)+MAN=坐主位的人=主席",emoji:"🪑",roots:["chair","man"]},
    {word:"clearance",chinese:"清除/許可",sentence:"You need security <strong>clearance</strong> to enter this area.",tip:"CLEAR(清楚)+ANCE=清除障礙=許可",emoji:"🔓",roots:["clear","ance"]},
    {word:"client",chinese:"客戶/委託人",sentence:"We have a meeting with the <strong>client</strong> tomorrow.",tip:"CLIENT=靠著你的人=客戶",emoji:"🤝",roots:["client"]},
    {word:"collateral",chinese:"擔保品/抵押物",sentence:"The bank requires <strong>collateral</strong> for the loan.",tip:"COL(一起)+LATER(旁邊)+AL=放在旁邊的保證=擔保品",emoji:"🏠",roots:["col","later","al"]},
    {word:"commission",chinese:"佣金/委員會",sentence:"Sales staff earn a 10% <strong>commission</strong>.",tip:"COM(一起)+MISS(派送)+ION=派送出去做事=佣金",emoji:"💲",roots:["com","miss","ion"]},
    {word:"commodity",chinese:"商品/日用品",sentence:"Oil is a valuable <strong>commodity</strong>.",tip:"COM(一起)+MOD(方便)+ITY=方便交易的東西=商品",emoji:"📦",roots:["com","mod","ity"]},
    {word:"compensation",chinese:"補償/薪酬",sentence:"The company offers competitive <strong>compensation</strong> packages.",tip:"COM(一起)+PENS(衡量)+ATION=衡量後給予=補償",emoji:"💰",roots:["com","pens","ation"]},
    {word:"competitor",chinese:"競爭者/對手",sentence:"Our main <strong>competitor</strong> launched a new product.",tip:"COM(一起)+PET(追求)+ITOR=一起追求的人=競爭者",emoji:"🏃",roots:["com","pet","itor"]},
    {word:"compliance",chinese:"遵守/合規",sentence:"All employees must ensure <strong>compliance</strong> with the policy.",tip:"COM(完全)+PLI(滿)+ANCE=完全滿足要求=合規",emoji:"✅",roots:["com","pli","ance"]},
    {word:"conference",chinese:"會議/研討會",sentence:"The annual <strong>conference</strong> attracts thousands of attendees.",tip:"CON(一起)+FER(帶)+ENCE=帶到一起=會議",emoji:"🎤",roots:["con","fer","ence"]},
    {word:"confidential",chinese:"機密的/保密的",sentence:"This document is <strong>confidential</strong> and for internal use only.",tip:"CON(完全)+FID(信任)+ENTIAL=完全信任才能看=機密的",emoji:"🔒",roots:["con","fid","ential"]},
    {word:"confirmation",chinese:"確認/證實",sentence:"Please send a <strong>confirmation</strong> email after booking.",tip:"CON(完全)+FIRM(堅固)+ATION=使完全堅固=確認",emoji:"📧",roots:["con","firm","ation"]},
    {word:"consecutive",chinese:"連續的/接連的",sentence:"Sales grew for five <strong>consecutive</strong> quarters.",tip:"CON(一起)+SECUT(跟隨)+IVE=一個接一個=連續的",emoji:"📈",roots:["con","secut","ive"]},
    {word:"consultation",chinese:"諮詢/商議",sentence:"Free legal <strong>consultation</strong> is available to members.",tip:"CON(一起)+SULT(商量)+ATION=一起商量=諮詢",emoji:"💬",roots:["con","sult","ation"]},
    {word:"contractor",chinese:"承包商/合同工",sentence:"We hired a <strong>contractor</strong> to renovate the office.",tip:"CON(一起)+TRACT(拉)+OR=拉到一起合作的人=承包商",emoji:"👷",roots:["con","tract","or"]},
    {word:"controversy",chinese:"爭議/論戰",sentence:"The decision sparked <strong>controversy</strong> among stakeholders.",tip:"CONTRO(反對)+VERS(轉)+Y=轉向反對=爭議",emoji:"⚡",roots:["contro","vers","y"]},
    {word:"conversion",chinese:"轉換/改建",sentence:"The <strong>conversion</strong> rate from visitors to buyers is 3%.",tip:"CON(完全)+VERS(轉)+ION=完全轉變=轉換",emoji:"🔄",roots:["con","vers","ion"]},
    {word:"corporate",chinese:"企業的/公司的",sentence:"The <strong>corporate</strong> headquarters is in New York.",tip:"CORPOR(身體/團體)+ATE=組成團體的=公司的",emoji:"🏢",roots:["corpor","ate"]},
    {word:"correspondence",chinese:"通信/信函",sentence:"All <strong>correspondence</strong> should be addressed to the manager.",tip:"COR(一起)+RE(回)+SPOND(回應)+ENCE=互相回應=通信",emoji:"✉️",roots:["cor","re","spond","ence"]},
    {word:"credentials",chinese:"資格/證書",sentence:"Please present your <strong>credentials</strong> at the registration desk.",tip:"CRED(相信)+ENTIALS=讓人相信你的東西=資格證明",emoji:"🪪",roots:["cred","entials"]},
    {word:"customs",chinese:"海關/關稅",sentence:"You must declare goods at <strong>customs</strong>.",tip:"CUSTOM(習慣/稅)=按習慣收稅的地方=海關",emoji:"🛃",roots:["customs"]},
    {word:"deadline",chinese:"截止日期/期限",sentence:"The <strong>deadline</strong> for submissions is Friday.",tip:"DEAD(死)+LINE(線)=超過就死的線=截止日期",emoji:"⏰",roots:["dead","line"]},
    {word:"deduction",chinese:"扣除/推論",sentence:"Tax <strong>deductions</strong> reduce your taxable income.",tip:"DE(向下)+DUCT(引導)+ION=引導下去=扣除",emoji:"➖",roots:["de","duct","ion"]},
    {word:"deficit",chinese:"赤字/虧損",sentence:"The government is running a budget <strong>deficit</strong>.",tip:"DE(離開)+FIC(做)+IT=做不夠=赤字",emoji:"📉",roots:["de","fic","it"]},
    {word:"delegate",chinese:"代表/委派",sentence:"She <strong>delegated</strong> the task to her assistant.",tip:"DE(離開)+LEG(派)+ATE=派出去代表=委派",emoji:"👤",roots:["de","leg","ate"]},
    {word:"delivery",chinese:"交付/遞送",sentence:"Free <strong>delivery</strong> is available for orders over $50.",tip:"DE(向下)+LIVER(釋放)+Y=釋放交出=遞送",emoji:"📦",roots:["de","liver","y"]},
    {word:"deposit",chinese:"存款/押金",sentence:"A <strong>deposit</strong> of $500 is required to reserve the room.",tip:"DE(向下)+POSIT(放)=放下去=存款/押金",emoji:"🏦",roots:["de","posit"]},
    {word:"depreciation",chinese:"折舊/貶值",sentence:"We account for equipment <strong>depreciation</strong> annually.",tip:"DE(向下)+PRECI(價格)+ATION=價格下降=折舊",emoji:"📉",roots:["de","preci","ation"]},
    {word:"detour",chinese:"繞道/迂迴路線",sentence:"Road construction required a <strong>detour</strong> through the neighborhood.",tip:"DE(離開)+TOUR(轉)=轉離原路=繞道",emoji:"🔀",roots:["de","tour"]},
    {word:"directory",chinese:"目錄/通訊錄",sentence:"Check the employee <strong>directory</strong> for contact information.",tip:"DIRECT(指引)+ORY=指引你找到人的=通訊錄",emoji:"📒",roots:["direct","ory"]},
    {word:"disbursement",chinese:"支出/付款",sentence:"All <strong>disbursements</strong> must be approved by accounting.",tip:"DIS(離開)+BURSE(錢包)+MENT=從錢包出去=支出",emoji:"💸",roots:["dis","burse","ment"]},
    {word:"disclaimer",chinese:"免責聲明/否認",sentence:"The product comes with a legal <strong>disclaimer</strong>.",tip:"DIS(不)+CLAIM(聲稱)+ER=不聲稱負責=免責聲明",emoji:"⚠️",roots:["dis","claim","er"]},
    {word:"disclosure",chinese:"披露/公開",sentence:"Full <strong>disclosure</strong> of financial data is required.",tip:"DIS(打開)+CLOS(關)+URE=打開關著的=披露",emoji:"📢",roots:["dis","clos","ure"]},
    {word:"discount",chinese:"折扣/打折",sentence:"Members get a 20% <strong>discount</strong> on all purchases.",tip:"DIS(離開)+COUNT(計算)=從總數中去掉=折扣",emoji:"🏷️",roots:["dis","count"]},
    {word:"discrimination",chinese:"歧視/辨別",sentence:"Workplace <strong>discrimination</strong> is strictly prohibited.",tip:"DIS(分開)+CRIMIN(區分)+ATION=區別對待=歧視",emoji:"⚖️",roots:["dis","crimin","ation"]},
    {word:"dismissal",chinese:"解僱/駁回",sentence:"Wrongful <strong>dismissal</strong> can lead to lawsuits.",tip:"DIS(離開)+MISS(送)+AL=送走=解僱",emoji:"🚪",roots:["dis","miss","al"]},
    {word:"dispatch",chinese:"派遣/發送",sentence:"The order was <strong>dispatched</strong> within 24 hours.",tip:"DIS(離開)+PATCH(快速)=快速送出=派遣",emoji:"🚚",roots:["dis","patch"]},
    {word:"dispute",chinese:"爭議/糾紛",sentence:"The two parties are in a legal <strong>dispute</strong>.",tip:"DIS(分開)+PUTE(想)=想法分開=爭議",emoji:"⚖️",roots:["dis","pute"]},
    {word:"disruption",chinese:"中斷/擾亂",sentence:"The strike caused major <strong>disruption</strong> to services.",tip:"DIS(分開)+RUPT(打破)+ION=打破分開=中斷",emoji:"💥",roots:["dis","rupt","ion"]},
    {word:"dividend",chinese:"股息/紅利",sentence:"Shareholders receive quarterly <strong>dividends</strong>.",tip:"DIVID(分)+END=分出來的=股息",emoji:"💰",roots:["divid","end"]},
    {word:"documentation",chinese:"文件/文檔",sentence:"Please submit all required <strong>documentation</strong>.",tip:"DOCUMENT(文件)+ATION=做成文件=文檔",emoji:"📁",roots:["document","ation"]},
    {word:"domestic",chinese:"國內的/家庭的",sentence:"<strong>Domestic</strong> flights depart from Terminal 1.",tip:"DOMEST(家)+IC=和家有關的=國內的",emoji:"🏠",roots:["domest","ic"]},
    {word:"donation",chinese:"捐贈/捐款",sentence:"The charity received a generous <strong>donation</strong>.",tip:"DON(給)+ATION=給出去=捐贈",emoji:"🎁",roots:["don","ation"]},
    {word:"downturn",chinese:"衰退/下滑",sentence:"The economic <strong>downturn</strong> affected many businesses.",tip:"DOWN(下)+TURN(轉)=向下轉=衰退",emoji:"📉",roots:["down","turn"]},
    {word:"draft",chinese:"草稿/草案",sentence:"Please review the <strong>draft</strong> report by Friday.",tip:"DRAFT=拉出來的初步版本=草稿",emoji:"📝",roots:["draft"]},
    {word:"duration",chinese:"持續時間/期間",sentence:"The contract has a <strong>duration</strong> of two years.",tip:"DUR(持續)+ATION=持續的時間=期間",emoji:"⏱️",roots:["dur","ation"]},
    {word:"efficiency",chinese:"效率/效能",sentence:"We need to improve the <strong>efficiency</strong> of our workflow.",tip:"EF(出)+FIC(做)+IENCY=做出來的能力=效率",emoji:"⚡",roots:["ef","fic","iency"]},
    {word:"eligible",chinese:"有資格的/合格的",sentence:"Employees with 5 years of service are <strong>eligible</strong> for promotion.",tip:"E(出)+LIG(選)+IBLE=可以被選出的=合格的",emoji:"✅",roots:["e","lig","ible"]},
    {word:"embargo",chinese:"禁運/禁令",sentence:"The government imposed an <strong>embargo</strong> on oil exports.",tip:"EM(在內)+BARGO(船)=把船關在裡面=禁運",emoji:"🚫",roots:["em","bargo"]},
    {word:"emergency",chinese:"緊急情況/急診",sentence:"In case of <strong>emergency</strong>, call 911 immediately.",tip:"E(出)+MERG(浮現)+ENCY=突然浮現=緊急情況",emoji:"🚨",roots:["e","merg","ency"]},
    {word:"employment",chinese:"就業/僱用",sentence:"The <strong>employment</strong> rate has risen this year.",tip:"EM(在內)+PLOY(使用)+MENT=把人用在裡面=僱用",emoji:"💼",roots:["em","ploy","ment"]},
    {word:"endorsement",chinese:"背書/認可",sentence:"The product received <strong>endorsement</strong> from celebrities.",tip:"EN(在)+DORSE(背)+MENT=在背面簽名=背書",emoji:"✍️",roots:["en","dorse","ment"]},
    {word:"enforcement",chinese:"執行/強制",sentence:"Strict <strong>enforcement</strong> of the rules is expected.",tip:"EN(使)+FORCE(力量)+MENT=使有力量=執行",emoji:"👮",roots:["en","force","ment"]},
    {word:"enterprise",chinese:"企業/事業",sentence:"She runs a successful small <strong>enterprise</strong>.",tip:"ENTER(之間)+PRISE(拿)=敢去拿的事業=企業",emoji:"🏢",roots:["enter","prise"]},
    {word:"entrepreneur",chinese:"企業家/創業者",sentence:"The young <strong>entrepreneur</strong> founded three startups.",tip:"ENTRE(之間)+PREN(拿)+EUR=在中間拿機會的人=創業者",emoji:"💡",roots:["entre","pren","eur"]},
    {word:"equity",chinese:"公平/股權",sentence:"The founders hold 60% <strong>equity</strong> in the company.",tip:"EQU(平等)+ITY=平等的份額=股權",emoji:"📊",roots:["equ","ity"]},
    {word:"escalate",chinese:"升級/加劇",sentence:"If unresolved, the issue will <strong>escalate</strong> to management.",tip:"ESCAL(梯子)+ATE=爬梯子上去=升級",emoji:"⬆️",roots:["escal","ate"]},
    {word:"estimate",chinese:"估計/估算",sentence:"The project <strong>estimate</strong> is $2 million.",tip:"ESTIM(評價)+ATE=給出評價=估計",emoji:"🔢",roots:["estim","ate"]},
    {word:"evaluation",chinese:"評估/評價",sentence:"The employee <strong>evaluation</strong> will take place quarterly.",tip:"E(出)+VALU(價值)+ATION=給出價值=評估",emoji:"📊",roots:["e","valu","ation"]},
    {word:"exceed",chinese:"超過/超越",sentence:"Sales <strong>exceeded</strong> expectations this month.",tip:"EX(超過)+CEED(走)=走超過=超越",emoji:"🚀",roots:["ex","ceed"]},
    {word:"exclusive",chinese:"獨家的/排斥的",sentence:"We have an <strong>exclusive</strong> deal with the supplier.",tip:"EX(出)+CLUS(關)+IVE=把別人關在外面=獨家的",emoji:"⭐",roots:["ex","clus","ive"]},
    {word:"executive",chinese:"行政人員/高管",sentence:"The <strong>executive</strong> team approved the strategy.",tip:"EX(出)+ECUT(跟隨)+IVE=執行出來的人=高管",emoji:"👔",roots:["ex","ecut","ive"]},
    {word:"exemption",chinese:"免除/豁免",sentence:"Certain goods are granted tax <strong>exemption</strong>.",tip:"EX(出)+EMPT(拿)+ION=被拿出免除=豁免",emoji:"🆓",roots:["ex","empt","ion"]},
    {word:"exhibition",chinese:"展覽/展示",sentence:"The trade <strong>exhibition</strong> attracted many buyers.",tip:"EX(出)+HIBIT(持有)+ION=拿出來展示=展覽",emoji:"🎪",roots:["ex","hibit","ion"]},
    {word:"expansion",chinese:"擴展/擴張",sentence:"The company is planning overseas <strong>expansion</strong>.",tip:"EX(出)+PANS(展開)+ION=向外展開=擴展",emoji:"🌐",roots:["ex","pans","ion"]},
    {word:"expenditure",chinese:"支出/花費",sentence:"Capital <strong>expenditure</strong> increased by 15%.",tip:"EX(出)+PEND(花費)+ITURE=花出去的=支出",emoji:"💸",roots:["ex","pend","iture"]},
    {word:"expertise",chinese:"專業知識/專長",sentence:"Her <strong>expertise</strong> in marketing is well recognized.",tip:"EXPERT(專家)+ISE=專家的能力=專業知識",emoji:"🧠",roots:["expert","ise"]},
    {word:"export",chinese:"出口/輸出",sentence:"The country's main <strong>export</strong> is electronics.",tip:"EX(出)+PORT(港口)=從港口出去=出口",emoji:"🚢",roots:["ex","port"]},
    {word:"extension",chinese:"延期/分機",sentence:"He requested a one-week <strong>extension</strong> on the deadline.",tip:"EX(出)+TENS(伸展)+ION=向外伸展=延期",emoji:"📞",roots:["ex","tens","ion"]},
    {word:"facility",chinese:"設施/場所",sentence:"The new <strong>facility</strong> includes a gym and cafeteria.",tip:"FACIL(容易)+ITY=使事情容易的地方=設施",emoji:"🏗️",roots:["facil","ity"]},
    {word:"feasibility",chinese:"可行性/可能性",sentence:"We conducted a <strong>feasibility</strong> study before investing.",tip:"FEAS(做)+IBILITY=能做到的程度=可行性",emoji:"📋",roots:["feas","ibility"]},
    {word:"fiduciary",chinese:"信託的/受託人",sentence:"A lawyer has a <strong>fiduciary</strong> duty to their client.",tip:"FIDUC(信任)+IARY=基於信任的=信託的",emoji:"⚖️",roots:["fiduc","iary"]},
    {word:"fiscal",chinese:"財政的/會計的",sentence:"The <strong>fiscal</strong> year ends in March.",tip:"FISC(國庫)+AL=和國庫有關=財政的",emoji:"💰",roots:["fisc","al"]},
    {word:"forecast",chinese:"預測/預報",sentence:"The weather <strong>forecast</strong> predicts rain tomorrow.",tip:"FORE(前)+CAST(投射)=往前投射=預測",emoji:"🔮",roots:["fore","cast"]},
    {word:"forfeiture",chinese:"沒收/喪失",sentence:"Late payment may result in <strong>forfeiture</strong> of the deposit.",tip:"FOR(外)+FEIT(做)+URE=做超出範圍=喪失",emoji:"⚠️",roots:["for","feit","ure"]},
    {word:"franchise",chinese:"特許經營/加盟",sentence:"She opened a <strong>franchise</strong> of the popular restaurant.",tip:"FRANCH(自由)+ISE=給予自由經營權=加盟",emoji:"🏪",roots:["franch","ise"]},
    {word:"freight",chinese:"貨物/運費",sentence:"<strong>Freight</strong> costs have increased due to fuel prices.",tip:"FREIGHT=裝載運送的貨物=運費",emoji:"🚛",roots:["freight"]},
    {word:"fulfillment",chinese:"履行/完成",sentence:"Order <strong>fulfillment</strong> takes 3-5 business days.",tip:"FUL(完全)+FILL(填滿)+MENT=完全填滿=履行",emoji:"✅",roots:["ful","fill","ment"]},
    {word:"fundraise",chinese:"募款/籌資",sentence:"The charity event helped <strong>fundraise</strong> for the hospital.",tip:"FUND(資金)+RAISE(提升)=提升資金=募款",emoji:"💰",roots:["fund","raise"]},
    {word:"furnish",chinese:"提供/佈置",sentence:"The landlord agreed to <strong>furnish</strong> the apartment.",tip:"FURN(提供)+ISH=提供家具=佈置",emoji:"🛋️",roots:["furn","ish"]},
    {word:"guarantee",chinese:"保證/擔保",sentence:"The product comes with a two-year <strong>guarantee</strong>.",tip:"GUARANT(保護)+EE=被保護的=保證",emoji:"🛡️",roots:["guarant","ee"]},
    {word:"guideline",chinese:"指導方針/準則",sentence:"Please follow the company <strong>guidelines</strong> for travel expenses.",tip:"GUIDE(指引)+LINE(線)=引導的線=準則",emoji:"📏",roots:["guide","line"]},
    {word:"harassment",chinese:"騷擾/困擾",sentence:"Zero tolerance for workplace <strong>harassment</strong> is enforced.",tip:"HARASS(困擾)+MENT=持續困擾=騷擾",emoji:"🚫",roots:["harass","ment"]},
    {word:"headquarters",chinese:"總部/總公司",sentence:"The company <strong>headquarters</strong> is located in Tokyo.",tip:"HEAD(頭)+QUARTERS(營地)=主要營地=總部",emoji:"🏢",roots:["head","quarters"]},
    {word:"hospitality",chinese:"款待/好客",sentence:"The <strong>hospitality</strong> industry was hit hard by the pandemic.",tip:"HOSPIT(客人)+ALITY=對客人好=款待",emoji:"🏨",roots:["hospit","ality"]},
    {word:"humanitarian",chinese:"人道主義的/慈善的",sentence:"The organization provides <strong>humanitarian</strong> aid worldwide.",tip:"HUMAN(人)+ITARIAN=為了人類的=人道主義的",emoji:"❤️",roots:["human","itar","ian"]},
    {word:"immigration",chinese:"移民/入境",sentence:"<strong>Immigration</strong> control is located on the second floor.",tip:"IM(進入)+MIGR(遷移)+ATION=遷入=移民",emoji:"🛂",roots:["im","migr","ation"]},
    {word:"implement",chinese:"實施/執行",sentence:"The team will <strong>implement</strong> the new system next month.",tip:"IM(在內)+PLE(填)+MENT=填入使完成=實施",emoji:"⚙️",roots:["im","ple","ment"]},
    {word:"implication",chinese:"含義/影響",sentence:"The policy has serious <strong>implications</strong> for small businesses.",tip:"IM(在內)+PLIC(折)+ATION=折在裡面的意思=含義",emoji:"💡",roots:["im","plic","ation"]},
    {word:"import",chinese:"進口/輸入",sentence:"The country depends on <strong>imports</strong> for raw materials.",tip:"IM(進入)+PORT(港口)=從港口進來=進口",emoji:"🚢",roots:["im","port"]},
    {word:"incentive",chinese:"激勵/獎勵",sentence:"The bonus is an <strong>incentive</strong> for high performance.",tip:"IN(在內)+CENT(唱)+IVE=內在激發的=激勵",emoji:"🏆",roots:["in","cent","ive"]},
    {word:"incorporate",chinese:"合併/納入",sentence:"We plan to <strong>incorporate</strong> feedback into the design.",tip:"IN(在內)+CORPOR(身體)+ATE=納入整體=合併",emoji:"🔗",roots:["in","corpor","ate"]},
    {word:"incur",chinese:"招致/產生",sentence:"Late payments will <strong>incur</strong> additional fees.",tip:"IN(進入)+CUR(跑)=跑進來=招致",emoji:"💸",roots:["in","cur"]},
    {word:"indemnity",chinese:"賠償/保障",sentence:"The insurance provides <strong>indemnity</strong> against fire damage.",tip:"IN(不)+DEMN(損害)+ITY=使不受損害=賠償保障",emoji:"🛡️",roots:["in","demn","ity"]},
    {word:"indicator",chinese:"指標/指示器",sentence:"GDP is a key economic <strong>indicator</strong>.",tip:"IN(向)+DIC(指)+ATOR=指向某處的=指標",emoji:"📊",roots:["in","dic","ator"]},
    {word:"inflation",chinese:"通貨膨脹/膨脹",sentence:"<strong>Inflation</strong> has risen to 5% this year.",tip:"IN(在內)+FLAT(吹)+ION=吹大了=通貨膨脹",emoji:"📈",roots:["in","flat","ion"]},
    {word:"infrastructure",chinese:"基礎設施",sentence:"The government invested in transportation <strong>infrastructure</strong>.",tip:"INFRA(下面)+STRUCT(建造)+URE=在下面建造的=基礎設施",emoji:"🏗️",roots:["infra","struct","ure"]},
    {word:"initiative",chinese:"主動/倡議",sentence:"The company launched a green <strong>initiative</strong>.",tip:"INIT(開始)+IATIVE=開始行動的=主動/倡議",emoji:"🌱",roots:["init","iative"]},
    {word:"innovation",chinese:"創新/革新",sentence:"The award recognizes <strong>innovation</strong> in technology.",tip:"IN(在內)+NOV(新)+ATION=帶入新的=創新",emoji:"💡",roots:["in","nov","ation"]},
    {word:"inspection",chinese:"檢查/視察",sentence:"A safety <strong>inspection</strong> is conducted monthly.",tip:"IN(在內)+SPECT(看)+ION=往裡面看=檢查",emoji:"🔍",roots:["in","spect","ion"]},
    {word:"installment",chinese:"分期付款/期刊",sentence:"You can pay in six monthly <strong>installments</strong>.",tip:"IN(在)+STALL(放)+MENT=分批放入=分期付款",emoji:"💳",roots:["in","stall","ment"]},
    {word:"insurance",chinese:"保險/保障",sentence:"Health <strong>insurance</strong> is provided by the company.",tip:"IN(在內)+SUR(確定)+ANCE=確保在保護中=保險",emoji:"🏥",roots:["in","sur","ance"]},
    {word:"integrate",chinese:"整合/使融入",sentence:"We need to <strong>integrate</strong> the new software with existing systems.",tip:"INTEGR(完整)+ATE=使完整=整合",emoji:"🧩",roots:["integr","ate"]},
    {word:"integrity",chinese:"誠信/完整性",sentence:"Data <strong>integrity</strong> is essential for accurate reporting.",tip:"INTEGR(完整)+ITY=完整的品質=誠信",emoji:"💎",roots:["integr","ity"]},
    {word:"intellectual",chinese:"智力的/知識分子",sentence:"<strong>Intellectual</strong> property must be protected.",tip:"INTELLECT(智力)+UAL=和智力有關=智力的",emoji:"🧠",roots:["intellect","ual"]},
    {word:"inventory",chinese:"庫存/清單",sentence:"We need to update the warehouse <strong>inventory</strong>.",tip:"IN(在內)+VENT(來)+ORY=進來的東西清單=庫存",emoji:"📦",roots:["in","vent","ory"]},
    {word:"investment",chinese:"投資/投入",sentence:"Real estate is a good long-term <strong>investment</strong>.",tip:"IN(在內)+VEST(衣服/投入)+MENT=把資金穿上=投資",emoji:"💹",roots:["in","vest","ment"]},
    {word:"invoice",chinese:"發票/帳單",sentence:"Please send the <strong>invoice</strong> to our billing department.",tip:"IN(在內)+VOICE(聲音)=送出聲明的帳單=發票",emoji:"🧾",roots:["in","voice"]},
    {word:"itinerary",chinese:"行程/路線",sentence:"The travel <strong>itinerary</strong> includes stops in three cities.",tip:"ITINER(旅行)+ARY=旅行的計畫=行程",emoji:"🗺️",roots:["itiner","ary"]},
    {word:"jurisdiction",chinese:"管轄權/司法權",sentence:"This matter falls outside our <strong>jurisdiction</strong>.",tip:"JURIS(法律)+DICT(說)+ION=有權說法的=管轄權",emoji:"⚖️",roots:["juris","dict","ion"]},
    {word:"justification",chinese:"正當理由/辯解",sentence:"There is no <strong>justification</strong> for such behavior.",tip:"JUST(正義)+IFIC+ATION=使正義=正當理由",emoji:"📋",roots:["just","ific","ation"]},
    {word:"labor",chinese:"勞動/勞工",sentence:"<strong>Labor</strong> costs account for 40% of total expenses.",tip:"LABOR=工作/勞動",emoji:"👷",roots:["labor"]},
    {word:"landlord",chinese:"房東/地主",sentence:"The <strong>landlord</strong> raised the rent by 10%.",tip:"LAND(土地)+LORD(主人)=土地的主人=房東",emoji:"🏠",roots:["land","lord"]},
    {word:"lawsuit",chinese:"訴訟/官司",sentence:"The company faces a class-action <strong>lawsuit</strong>.",tip:"LAW(法律)+SUIT(追求)=用法律追求=訴訟",emoji:"⚖️",roots:["law","suit"]},
    {word:"lease",chinese:"租約/租賃",sentence:"The office <strong>lease</strong> expires next year.",tip:"LEASE=租用的合約=租約",emoji:"📄",roots:["lease"]},
    {word:"ledger",chinese:"帳簿/分類帳",sentence:"All transactions are recorded in the <strong>ledger</strong>.",tip:"LEDGER=放在一處的記錄=帳簿",emoji:"📒",roots:["ledger"]},
    {word:"legislation",chinese:"立法/法規",sentence:"New <strong>legislation</strong> requires companies to reduce emissions.",tip:"LEGIS(法律)+LATION=制定法律=立法",emoji:"📜",roots:["legis","lation"]},
    {word:"legitimate",chinese:"合法的/正當的",sentence:"They have a <strong>legitimate</strong> claim to the property.",tip:"LEGIT(法律)+IMATE=符合法律的=合法的",emoji:"✅",roots:["legit","imate"]},
    {word:"leverage",chinese:"槓桿/利用",sentence:"We can <strong>leverage</strong> our brand to enter new markets.",tip:"LEVER(槓桿)+AGE=使用槓桿原理=利用",emoji:"⚙️",roots:["lever","age"]},
    {word:"liability",chinese:"責任/負債",sentence:"The company's total <strong>liabilities</strong> exceed its assets.",tip:"LI(綁)+ABIL(能力)+ITY=被綁住的義務=負債",emoji:"⚖️",roots:["li","abil","ity"]},
    {word:"license",chinese:"執照/許可證",sentence:"You need a valid <strong>license</strong> to operate this equipment.",tip:"LIC(許可)+ENSE=給予許可=執照",emoji:"🪪",roots:["lic","ense"]},
    {word:"liquidate",chinese:"清算/變現",sentence:"The firm was forced to <strong>liquidate</strong> its assets.",tip:"LIQUID(液體)+ATE=使變成流動的現金=清算",emoji:"💧",roots:["liquid","ate"]},
    {word:"litigation",chinese:"訴訟/打官司",sentence:"The <strong>litigation</strong> process can take years.",tip:"LITIG(爭訟)+ATION=進行爭訟=訴訟",emoji:"⚖️",roots:["litig","ation"]},
    {word:"logistics",chinese:"物流/後勤",sentence:"The <strong>logistics</strong> of shipping to 50 countries are complex.",tip:"LOG(邏輯)+ISTICS=有邏輯的安排=物流",emoji:"🚛",roots:["log","istics"]},
    {word:"maintenance",chinese:"維護/保養",sentence:"Regular <strong>maintenance</strong> extends equipment life.",tip:"MAIN(手)+TEN(保持)+ANCE=用手保持=維護",emoji:"🔧",roots:["main","ten","ance"]},
    {word:"mandate",chinese:"授權/命令",sentence:"The new <strong>mandate</strong> requires all staff to complete training.",tip:"MAND(命令)+ATE=發出命令=授權",emoji:"📋",roots:["mand","ate"]},
    {word:"manufacture",chinese:"製造/生產",sentence:"The company <strong>manufactures</strong> electronic components.",tip:"MANU(手)+FACT(做)+URE=用手做出=製造",emoji:"🏭",roots:["manu","fact","ure"]},
    {word:"margin",chinese:"利潤/邊距",sentence:"The profit <strong>margin</strong> improved to 15%.",tip:"MARGIN=邊緣/多出來的部分=利潤",emoji:"📊",roots:["margin"]},
    {word:"marketing",chinese:"行銷/市場營銷",sentence:"The <strong>marketing</strong> team launched a new campaign.",tip:"MARKET(市場)+ING=在市場活動=行銷",emoji:"📣",roots:["market","ing"]},
    {word:"maturity",chinese:"到期/成熟",sentence:"The bond reaches <strong>maturity</strong> in five years.",tip:"MATUR(成熟)+ITY=成熟的狀態=到期",emoji:"📅",roots:["matur","ity"]},
    {word:"mediate",chinese:"調解/調停",sentence:"A neutral party was asked to <strong>mediate</strong> the dispute.",tip:"MEDI(中間)+ATE=站在中間=調解",emoji:"🤝",roots:["medi","ate"]},
    {word:"merchandise",chinese:"商品/貨物",sentence:"All <strong>merchandise</strong> is on sale this weekend.",tip:"MERCH(商業)+ANDISE=商業的東西=商品",emoji:"🛍️",roots:["merch","andise"]},
    {word:"merger",chinese:"合併/兼併",sentence:"The <strong>merger</strong> created the largest bank in the country.",tip:"MERG(融合)+ER=融合在一起=合併",emoji:"🤝",roots:["merg","er"]},
    {word:"methodology",chinese:"方法論/方法",sentence:"Our research <strong>methodology</strong> follows best practices.",tip:"METHOD(方法)+OLOGY(學)=方法的學問=方法論",emoji:"📐",roots:["method","ology"]},
    {word:"milestone",chinese:"里程碑/重要事件",sentence:"Reaching 1 million users was a major <strong>milestone</strong>.",tip:"MILE(英里)+STONE(石頭)=路邊標記的石頭=里程碑",emoji:"🏆",roots:["mile","stone"]},
    {word:"monetary",chinese:"貨幣的/金融的",sentence:"The central bank sets <strong>monetary</strong> policy.",tip:"MONET(錢幣)+ARY=和錢幣有關=貨幣的",emoji:"💰",roots:["monet","ary"]},
    {word:"monopoly",chinese:"壟斷/獨占",sentence:"The company has a <strong>monopoly</strong> on the local market.",tip:"MONO(單)+POLY(賣)=只有一家賣=壟斷",emoji:"🏢",roots:["mono","poly"]},
    {word:"mortgage",chinese:"抵押貸款/房貸",sentence:"They took out a 30-year <strong>mortgage</strong> to buy the house.",tip:"MORT(死)+GAGE(質押)=至死的質押=抵押貸款",emoji:"🏠",roots:["mort","gage"]},
    {word:"municipal",chinese:"市政的/地方的",sentence:"<strong>Municipal</strong> elections will be held next month.",tip:"MUNIC(城市)+IPAL=城市的=市政的",emoji:"🏛️",roots:["munic","ipal"]},
    {word:"negligence",chinese:"疏忽/過失",sentence:"The accident was caused by <strong>negligence</strong>.",tip:"NEG(不)+LIG(選擇)+ENCE=不去注意選擇=疏忽",emoji:"⚠️",roots:["neg","lig","ence"]},
    {word:"negotiate",chinese:"談判/協商",sentence:"We need to <strong>negotiate</strong> better terms with the supplier.",tip:"NEG(不)+OTI(休閒)+ATE=不休閒地忙著=談判",emoji:"🤝",roots:["neg","oti","ate"]},
    {word:"nominal",chinese:"名義上的/極小的",sentence:"There is only a <strong>nominal</strong> fee for the service.",tip:"NOMIN(名字)+AL=只是名義的=極小的",emoji:"💲",roots:["nomin","al"]},
    {word:"notification",chinese:"通知/通告",sentence:"You will receive a <strong>notification</strong> when your order ships.",tip:"NOT(知道)+IFIC+ATION=使知道=通知",emoji:"🔔",roots:["not","ific","ation"]},
    {word:"obligation",chinese:"義務/責任",sentence:"You have a legal <strong>obligation</strong> to report income.",tip:"OB(向)+LIG(綁)+ATION=被綁住的=義務",emoji:"📋",roots:["ob","lig","ation"]},
    {word:"occupancy",chinese:"使用/入住率",sentence:"Hotel <strong>occupancy</strong> rates are at 90%.",tip:"OCCUP(占據)+ANCY=占據的狀態=入住率",emoji:"🏨",roots:["occup","ancy"]},
    {word:"offset",chinese:"抵消/補償",sentence:"Savings in one area <strong>offset</strong> costs in another.",tip:"OFF(離開)+SET(設定)=設定離開平衡=抵消",emoji:"⚖️",roots:["off","set"]},
    {word:"omission",chinese:"遺漏/省略",sentence:"The <strong>omission</strong> of key data affected the results.",tip:"O+MISS(送)+ION=沒有送出=遺漏",emoji:"❌",roots:["o","miss","ion"]},
    {word:"operative",chinese:"有效的/操作人員",sentence:"The new rules become <strong>operative</strong> next month.",tip:"OPER(工作)+ATIVE=在工作的=有效的",emoji:"⚙️",roots:["oper","ative"]},
    {word:"optimize",chinese:"優化/最佳化",sentence:"We need to <strong>optimize</strong> our supply chain.",tip:"OPTIM(最好)+IZE=使成為最好=優化",emoji:"📈",roots:["optim","ize"]},
    {word:"ordinance",chinese:"法令/條例",sentence:"The city passed an <strong>ordinance</strong> banning plastic bags.",tip:"ORDIN(命令)+ANCE=發出命令=法令",emoji:"📜",roots:["ordin","ance"]},
    {word:"outsource",chinese:"外包/委外",sentence:"Many companies <strong>outsource</strong> their IT support.",tip:"OUT(外)+SOURCE(來源)=從外部找來源=外包",emoji:"🌐",roots:["out","source"]},
    {word:"overdue",chinese:"過期的/逾期的",sentence:"The payment is two weeks <strong>overdue</strong>.",tip:"OVER(超過)+DUE(到期)=超過到期日=逾期的",emoji:"⏰",roots:["over","due"]},
    {word:"overhead",chinese:"經常開支/管理費",sentence:"<strong>Overhead</strong> costs include rent and utilities.",tip:"OVER(上面)+HEAD(頭)=頭上的壓力=經常開支",emoji:"💰",roots:["over","head"]},
    {word:"oversight",chinese:"監督/疏忽",sentence:"The error was an unfortunate <strong>oversight</strong>.",tip:"OVER(在上)+SIGHT(看)=從上面看/看漏了=監督/疏忽",emoji:"👁️",roots:["over","sight"]},
    {word:"participant",chinese:"參與者/參加者",sentence:"All <strong>participants</strong> will receive a certificate.",tip:"PARTI(參加)+CIP(拿)+ANT=拿到參加權的人=參與者",emoji:"🙋",roots:["parti","cip","ant"]},
    {word:"patent",chinese:"專利/專利權",sentence:"The company holds several <strong>patents</strong> for its technology.",tip:"PATENT=公開的發明保護=專利",emoji:"📋",roots:["patent"]},
    {word:"payroll",chinese:"薪資名冊/工資總額",sentence:"The company has 500 employees on <strong>payroll</strong>.",tip:"PAY(付)+ROLL(名冊)=付款名冊=薪資名冊",emoji:"💰",roots:["pay","roll"]},
    {word:"penalty",chinese:"罰款/處罰",sentence:"There is a <strong>penalty</strong> for early contract termination.",tip:"PEN(懲罰)+ALTY=懲罰性的=罰款",emoji:"⚠️",roots:["pen","alty"]},
    {word:"pension",chinese:"退休金/養老金",sentence:"Employees contribute 5% of their salary to the <strong>pension</strong> fund.",tip:"PENS(支付)+ION=定期支付的=退休金",emoji:"👴",roots:["pens","ion"]},
    {word:"percentage",chinese:"百分比/比例",sentence:"What <strong>percentage</strong> of revenue goes to marketing?",tip:"PER(每)+CENT(百)+AGE=每百的=百分比",emoji:"📊",roots:["per","cent","age"]},
    {word:"personnel",chinese:"人事/員工",sentence:"The <strong>personnel</strong> department handles recruitment.",tip:"PERSON(人)+NEL=和人有關=人事",emoji:"👥",roots:["person","nel"]},
    {word:"petition",chinese:"請願/請求",sentence:"Employees signed a <strong>petition</strong> for better working conditions.",tip:"PET(追求)+ITION=追求某事的文件=請願",emoji:"📝",roots:["pet","ition"]},
    {word:"pharmaceutical",chinese:"製藥的/藥品",sentence:"The <strong>pharmaceutical</strong> company developed a new vaccine.",tip:"PHARMAC(藥)+EUTICAL=和藥物有關=製藥的",emoji:"💊",roots:["pharmac","eutical"]},
    {word:"portfolio",chinese:"投資組合/作品集",sentence:"She diversified her investment <strong>portfolio</strong>.",tip:"PORT(攜帶)+FOLIO(紙張)=攜帶的文件=投資組合",emoji:"📂",roots:["port","folio"]},
    {word:"postpone",chinese:"推遲/延期",sentence:"The meeting has been <strong>postponed</strong> until next week.",tip:"POST(之後)+PONE(放)=放到之後=推遲",emoji:"📅",roots:["post","pone"]},
    {word:"premises",chinese:"房屋/經營場所",sentence:"No smoking is allowed on the <strong>premises</strong>.",tip:"PRE(前面)+MISE(放)=前面提到的財產=場所",emoji:"🏢",roots:["pre","mise","s"]},
    {word:"premium",chinese:"保險費/額外費用",sentence:"Insurance <strong>premiums</strong> have gone up this year.",tip:"PREMI(第一/獎)+UM=最好的價格=保險費",emoji:"💲",roots:["premi","um"]},
    {word:"prerequisite",chinese:"先決條件/前提",sentence:"A degree is a <strong>prerequisite</strong> for this position.",tip:"PRE(前)+REQUISITE(必需的)=事前必需的=先決條件",emoji:"✅",roots:["pre","requisite"]},
    {word:"procurement",chinese:"採購/獲取",sentence:"The <strong>procurement</strong> team sources materials globally.",tip:"PRO(向前)+CURE(關心)+MENT=向前關心取得=採購",emoji:"🛒",roots:["pro","cure","ment"]},
    {word:"productivity",chinese:"生產力/產量",sentence:"New tools increased team <strong>productivity</strong> by 30%.",tip:"PRODUCT(產品)+IVITY=產出的能力=生產力",emoji:"📈",roots:["product","ivity"]},
    {word:"proficiency",chinese:"精通/熟練",sentence:"<strong>Proficiency</strong> in English is required for the role.",tip:"PRO(前)+FIC(做)+IENCY=做得好=精通",emoji:"🏅",roots:["pro","fic","iency"]},
    {word:"prohibition",chinese:"禁止/禁令",sentence:"There is a <strong>prohibition</strong> on smoking in public spaces.",tip:"PRO(向前)+HIBIT(保持)+ION=保持不讓做=禁止",emoji:"🚫",roots:["pro","hibit","ion"]},
    {word:"projection",chinese:"預測/預計",sentence:"Revenue <strong>projections</strong> for next year look positive.",tip:"PRO(向前)+JECT(扔)+ION=往前扔出去看=預測",emoji:"📊",roots:["pro","ject","ion"]},
    {word:"promotion",chinese:"晉升/促銷",sentence:"She earned a <strong>promotion</strong> to senior manager.",tip:"PRO(向前)+MOT(移動)+ION=向前移動=晉升",emoji:"⬆️",roots:["pro","mot","ion"]},
    {word:"prospectus",chinese:"招股說明書/簡介",sentence:"Read the <strong>prospectus</strong> before investing.",tip:"PRO(向前)+SPECT(看)+US=往前看的文件=招股書",emoji:"📄",roots:["pro","spect","us"]},
    {word:"protocol",chinese:"協議/禮儀規範",sentence:"Please follow the safety <strong>protocol</strong>.",tip:"PROTO(第一)+COL(膠)=第一張黏在文件上的=協議",emoji:"📋",roots:["proto","col"]},
    {word:"provision",chinese:"條款/供應",sentence:"The contract includes a <strong>provision</strong> for early termination.",tip:"PRO(向前)+VIS(看)+ION=向前看準備的=條款",emoji:"📜",roots:["pro","vis","ion"]},
    {word:"proxy",chinese:"代理/委託書",sentence:"She voted by <strong>proxy</strong> since she couldn't attend.",tip:"PROXY=代替行事的人=代理",emoji:"👤",roots:["proxy"]},
    {word:"qualification",chinese:"資格/條件",sentence:"What <strong>qualifications</strong> do you need for this job?",tip:"QUAL(品質)+IFIC+ATION=達到品質=資格",emoji:"🎓",roots:["qual","ific","ation"]},
    {word:"quarterly",chinese:"每季的/季刊",sentence:"The company publishes <strong>quarterly</strong> earnings reports.",tip:"QUARTER(四分之一)+LY=每四分之一年=每季的",emoji:"📅",roots:["quarter","ly"]},
    {word:"quota",chinese:"配額/定額",sentence:"Each salesperson must meet their monthly <strong>quota</strong>.",tip:"QUOTA=分配到的份額=配額",emoji:"📊",roots:["quota"]},
    {word:"ratification",chinese:"批准/認可",sentence:"The treaty awaits <strong>ratification</strong> by parliament.",tip:"RAT(算)+IFIC+ATION=正式算數=批准",emoji:"✅",roots:["rat","ific","ation"]},
    {word:"rebate",chinese:"回扣/折扣",sentence:"Customers can claim a $50 <strong>rebate</strong> on this product.",tip:"RE(回)+BATE(減少)=減回來=回扣",emoji:"💰",roots:["re","bate"]},
    {word:"recession",chinese:"經濟衰退/蕭條",sentence:"The country entered a <strong>recession</strong> in 2020.",tip:"RE(回)+CESS(退)+ION=退回去=經濟衰退",emoji:"📉",roots:["re","cess","ion"]},
    {word:"recruitment",chinese:"招聘/徵兵",sentence:"The <strong>recruitment</strong> drive attracted many applicants.",tip:"RE(再)+CRUIT(增長)+MENT=再次增長人員=招聘",emoji:"👥",roots:["re","cruit","ment"]},
    {word:"redundancy",chinese:"裁員/多餘",sentence:"Staff faced <strong>redundancy</strong> due to automation.",tip:"RE(再)+DUND(波浪)+ANCY=多出來的波浪=多餘/裁員",emoji:"📉",roots:["re","dund","ancy"]},
    {word:"referendum",chinese:"公民投票/公投",sentence:"A <strong>referendum</strong> on the issue will be held next year.",tip:"RE(回)+FER(帶)+ENDUM=帶回給人民=公投",emoji:"🗳️",roots:["re","fer","endum"]},
    {word:"refurbish",chinese:"翻新/整修",sentence:"The hotel was completely <strong>refurbished</strong> last year.",tip:"RE(再)+FURBISH(裝飾)=重新裝飾=翻新",emoji:"🔨",roots:["re","furbish"]},
    {word:"regulation",chinese:"規章/管理",sentence:"Strict <strong>regulations</strong> govern the banking industry.",tip:"REG(統治)+UL+ATION=統治的規則=規章",emoji:"📏",roots:["reg","ul","ation"]},
    {word:"reimbursement",chinese:"報銷/償還",sentence:"Submit receipts for travel <strong>reimbursement</strong>.",tip:"RE(回)+IM(在)+BURSE(錢包)+MENT=把錢放回錢包=報銷",emoji:"💰",roots:["re","im","burse","ment"]},
    {word:"reinstate",chinese:"恢復/復職",sentence:"The employee was <strong>reinstated</strong> after the investigation.",tip:"RE(再)+IN(在)+STATE(狀態)=再次在原狀態=復職",emoji:"🔄",roots:["re","in","state"]},
    {word:"remittance",chinese:"匯款/匯寄的款項",sentence:"Overseas <strong>remittances</strong> support many families.",tip:"RE(回)+MITT(送)+ANCE=送回去的錢=匯款",emoji:"💸",roots:["re","mitt","ance"]},
    {word:"renovation",chinese:"翻新/修繕",sentence:"The building is closed for <strong>renovation</strong>.",tip:"RE(再)+NOV(新)+ATION=使重新變新=翻新",emoji:"🏗️",roots:["re","nov","ation"]},
    {word:"repeal",chinese:"廢除/撤銷",sentence:"Lawmakers voted to <strong>repeal</strong> the controversial law.",tip:"RE(回)+PEAL(呼叫)=召回法律=廢除",emoji:"📜",roots:["re","peal"]},
    {word:"replication",chinese:"複製/重複",sentence:"The experiment requires <strong>replication</strong> for validation.",tip:"RE(再)+PLIC(折)+ATION=再次折出一樣的=複製",emoji:"🔁",roots:["re","plic","ation"]},
    {word:"representation",chinese:"代表/表述",sentence:"Legal <strong>representation</strong> is advisable in court.",tip:"RE(再)+PRESENT(呈現)+ATION=代替呈現=代表",emoji:"👤",roots:["re","present","ation"]},
    {word:"requisition",chinese:"申請/徵用",sentence:"Submit a <strong>requisition</strong> form for office supplies.",tip:"RE(再)+QUIS(尋求)+ITION=正式尋求=申請",emoji:"📝",roots:["re","quis","ition"]},
    {word:"resignation",chinese:"辭職/辭呈",sentence:"She submitted her <strong>resignation</strong> effective immediately.",tip:"RE(回)+SIGN(簽名)+ATION=簽名退回=辭職",emoji:"✍️",roots:["re","sign","ation"]},
    {word:"resolution",chinese:"決議/解決",sentence:"The board passed a <strong>resolution</strong> to restructure.",tip:"RE(再)+SOLUT(解開)+ION=解開問題=決議",emoji:"✅",roots:["re","solut","ion"]},
    {word:"restitution",chinese:"歸還/賠償",sentence:"The court ordered <strong>restitution</strong> to the victims.",tip:"RE(回)+STITUT(放置)+ION=放回原處=歸還",emoji:"⚖️",roots:["re","stitut","ion"]},
    {word:"restructure",chinese:"重組/改組",sentence:"The company plans to <strong>restructure</strong> its operations.",tip:"RE(再)+STRUCT(建造)+URE=重新建造=重組",emoji:"🏗️",roots:["re","struct","ure"]},
    {word:"retail",chinese:"零售/零賣",sentence:"The <strong>retail</strong> price is higher than the wholesale price.",tip:"RE(再)+TAIL(切)=再切成小塊賣=零售",emoji:"🏪",roots:["re","tail"]},
    {word:"retention",chinese:"保留/留任",sentence:"Employee <strong>retention</strong> is a priority for HR.",tip:"RE(回)+TENT(持有)+ION=持有住=保留",emoji:"🔒",roots:["re","tent","ion"]},
    {word:"revenue",chinese:"收入/稅收",sentence:"Annual <strong>revenue</strong> grew by 20% this year.",tip:"RE(回)+VENUE(來)=回來的錢=收入",emoji:"💰",roots:["re","venue"]},
    {word:"revision",chinese:"修訂/修改",sentence:"The document is on its third <strong>revision</strong>.",tip:"RE(再)+VIS(看)+ION=再看一次修改=修訂",emoji:"📝",roots:["re","vis","ion"]},
    {word:"sanction",chinese:"制裁/批准",sentence:"Economic <strong>sanctions</strong> were imposed on the country.",tip:"SANCT(神聖)+ION=神聖的批准或懲罰=制裁",emoji:"🚫",roots:["sanct","ion"]},
    {word:"scrutiny",chinese:"仔細審查/監視",sentence:"The accounts are under close <strong>scrutiny</strong>.",tip:"SCRUT(檢查)+INY=仔細檢查=審查",emoji:"🔍",roots:["scrut","iny"]},
    {word:"securities",chinese:"有價證券/證券",sentence:"She invested in government <strong>securities</strong>.",tip:"SECUR(安全)+ITIES=有保障的投資=證券",emoji:"📈",roots:["secur","ities"]},
    {word:"severance",chinese:"遣散費/解僱補償",sentence:"He received a generous <strong>severance</strong> package.",tip:"SEVER(切斷)+ANCE=切斷關係時給的=遣散費",emoji:"💰",roots:["sever","ance"]},
    {word:"shareholder",chinese:"股東/持股人",sentence:"<strong>Shareholders</strong> voted to approve the merger.",tip:"SHARE(股份)+HOLD(持有)+ER=持有股份的人=股東",emoji:"📊",roots:["share","hold","er"]},
    {word:"specification",chinese:"規格/明細",sentence:"The product meets all technical <strong>specifications</strong>.",tip:"SPEC(看)+IFIC+ATION=看清楚的細節=規格",emoji:"📋",roots:["spec","ific","ation"]},
    {word:"stipulate",chinese:"規定/約定",sentence:"The contract <strong>stipulates</strong> a 30-day notice period.",tip:"STIPUL(條款)+ATE=寫入條款=規定",emoji:"📝",roots:["stipul","ate"]},
    {word:"subsidiary",chinese:"子公司/附屬的",sentence:"The firm has <strong>subsidiaries</strong> in ten countries.",tip:"SUB(下)+SID(坐)+IARY=坐在下面的=子公司",emoji:"🏢",roots:["sub","sid","iary"]},
    {word:"subsidy",chinese:"補貼/津貼",sentence:"The government provides <strong>subsidies</strong> to farmers.",tip:"SUB(下)+SID(坐)+Y=在下面支撐=補貼",emoji:"💰",roots:["sub","sid","y"]},
    {word:"succession",chinese:"繼承/連續",sentence:"The CEO's <strong>succession</strong> plan is still unclear.",tip:"SUC(在下)+CESS(走)+ION=一個接一個走=繼承",emoji:"📊",roots:["suc","cess","ion"]},
    {word:"superintendent",chinese:"主管/監督人",sentence:"The building <strong>superintendent</strong> handles repairs.",tip:"SUPER(在上)+INTEND(注意)+ENT=在上面注意的人=主管",emoji:"👷",roots:["super","intend","ent"]},
    {word:"supplement",chinese:"補充/增刊",sentence:"Vitamins are a useful dietary <strong>supplement</strong>.",tip:"SUP(下面)+PLE(填)+MENT=在下面填補=補充",emoji:"💊",roots:["sup","ple","ment"]},
    {word:"surplus",chinese:"剩餘/過剩",sentence:"The budget <strong>surplus</strong> will be reinvested.",tip:"SUR(超過)+PLUS(更多)=超過需要的更多=剩餘",emoji:"📈",roots:["sur","plus"]},
    {word:"surveillance",chinese:"監控/監視",sentence:"Security <strong>surveillance</strong> cameras are installed throughout.",tip:"SUR(在上)+VEILL(看)+ANCE=在上面看=監控",emoji:"📷",roots:["sur","veill","ance"]},
    {word:"suspension",chinese:"暫停/中止",sentence:"The <strong>suspension</strong> of services affected many users.",tip:"SUS(在下)+PENS(懸掛)+ION=懸掛起來=暫停",emoji:"⏸️",roots:["sus","pens","ion"]},
    {word:"tariff",chinese:"關稅/稅率表",sentence:"New <strong>tariffs</strong> on imports increased product costs.",tip:"TARIFF=進口稅率=關稅",emoji:"🏛️",roots:["tariff"]},
    {word:"taxation",chinese:"稅收/課稅",sentence:"<strong>Taxation</strong> policies vary by country.",tip:"TAX(稅)+ATION=收稅的行為=課稅",emoji:"💰",roots:["tax","ation"]},
    {word:"tenure",chinese:"任期/終身職",sentence:"Her <strong>tenure</strong> as CEO lasted eight years.",tip:"TEN(持有)+URE=持有職位的期間=任期",emoji:"📅",roots:["ten","ure"]},
    {word:"termination",chinese:"終止/解僱",sentence:"Early <strong>termination</strong> of the contract incurs a fee.",tip:"TERMIN(結束)+ATION=結束=終止",emoji:"🛑",roots:["termin","ation"]},
    {word:"testimony",chinese:"證詞/證據",sentence:"The witness gave <strong>testimony</strong> before the court.",tip:"TESTI(見證)+MONY=做見證=證詞",emoji:"⚖️",roots:["testi","mony"]},
    {word:"transaction",chinese:"交易/業務",sentence:"Please keep records of all financial <strong>transactions</strong>.",tip:"TRANS(跨越)+ACT(做)+ION=跨越做的事=交易",emoji:"💳",roots:["trans","act","ion"]},
    {word:"transparency",chinese:"透明度/公開",sentence:"The company is committed to financial <strong>transparency</strong>.",tip:"TRANS(通過)+PAR(出現)+ENCY=能看穿的=透明度",emoji:"🔍",roots:["trans","par","ency"]},
    {word:"treasury",chinese:"國庫/財政部",sentence:"The <strong>Treasury</strong> Department manages government funds.",tip:"TREASUR(寶藏)+Y=存放寶藏的地方=國庫",emoji:"🏦",roots:["treasur","y"]},
    {word:"tribunal",chinese:"法庭/仲裁庭",sentence:"The case was referred to an international <strong>tribunal</strong>.",tip:"TRIBUN(法官)+AL=法官的地方=法庭",emoji:"⚖️",roots:["tribun","al"]},
    {word:"turnover",chinese:"營業額/人員流動",sentence:"Annual <strong>turnover</strong> reached $10 million.",tip:"TURN(轉)+OVER(結束)=轉過一輪的金額=營業額",emoji:"💹",roots:["turn","over"]},
    {word:"underwrite",chinese:"承保/承銷",sentence:"The bank agreed to <strong>underwrite</strong> the bond issue.",tip:"UNDER(下面)+WRITE(寫)=在下面簽名擔保=承保",emoji:"✍️",roots:["under","write"]},
    {word:"unemployment",chinese:"失業/失業率",sentence:"<strong>Unemployment</strong> fell to a record low.",tip:"UN(不)+EMPLOY(僱用)+MENT=沒有被僱用=失業",emoji:"📉",roots:["un","employ","ment"]},
    {word:"utility",chinese:"公用事業/效用",sentence:"<strong>Utility</strong> bills include water, gas, and electricity.",tip:"UTIL(有用)+ITY=有用的東西=公用事業",emoji:"💡",roots:["util","ity"]},
    {word:"vacancy",chinese:"空缺/職位空缺",sentence:"There is a <strong>vacancy</strong> for a senior analyst.",tip:"VAC(空)+ANCY=空的位置=空缺",emoji:"🪑",roots:["vac","ancy"]},
    {word:"validate",chinese:"驗證/使生效",sentence:"Please <strong>validate</strong> your parking ticket at the front desk.",tip:"VALID(有效)+ATE=使有效=驗證",emoji:"✅",roots:["valid","ate"]},
    {word:"vendor",chinese:"供應商/攤販",sentence:"We selected three <strong>vendors</strong> for the project.",tip:"VEND(賣)+OR=賣東西的人=供應商",emoji:"🏪",roots:["vend","or"]},
    {word:"venture",chinese:"風險投資/冒險",sentence:"The joint <strong>venture</strong> proved highly profitable.",tip:"VENT(來)+URE=來冒險=風險投資",emoji:"🚀",roots:["vent","ure"]},
    {word:"verification",chinese:"驗證/核實",sentence:"Identity <strong>verification</strong> is required for all users.",tip:"VERI(真)+FIC(做)+ATION=做到真實=驗證",emoji:"🔐",roots:["veri","fic","ation"]},
    {word:"violation",chinese:"違反/侵犯",sentence:"This is a clear <strong>violation</strong> of the agreement.",tip:"VIOL(暴力)+ATION=使用暴力對待規則=違反",emoji:"🚫",roots:["viol","ation"]},
    {word:"volatility",chinese:"波動性/不穩定性",sentence:"Market <strong>volatility</strong> increased during the crisis.",tip:"VOLAT(飛)+ILITY=像飛走般不穩定=波動性",emoji:"📊",roots:["volat","il","ity"]},
    {word:"voluntary",chinese:"自願的/志願的",sentence:"Participation in the survey is <strong>voluntary</strong>.",tip:"VOLUNT(意願)+ARY=出於意願的=自願的",emoji:"🙋",roots:["volunt","ary"]},
    {word:"voucher",chinese:"代金券/憑證",sentence:"Use this <strong>voucher</strong> for a 10% discount.",tip:"VOUCH(保證)+ER=保證可用的券=代金券",emoji:"🎫",roots:["vouch","er"]},
    {word:"waiver",chinese:"棄權/放棄聲明",sentence:"Sign the <strong>waiver</strong> before participating.",tip:"WAIVE(放棄)+R=放棄權利的文件=棄權聲明",emoji:"📄",roots:["waiv","er"]},
    {word:"warranty",chinese:"保修/保證書",sentence:"The device comes with a one-year <strong>warranty</strong>.",tip:"WARRANT(保證)+Y=保證的承諾=保修",emoji:"🛡️",roots:["warrant","y"]},
    {word:"wholesale",chinese:"批發/大宗交易",sentence:"We offer <strong>wholesale</strong> pricing for bulk orders.",tip:"WHOLE(全部)+SALE(賣)=整批賣=批發",emoji:"📦",roots:["whole","sale"]},
    {word:"withdrawal",chinese:"提款/撤回",sentence:"There is a daily limit on ATM <strong>withdrawals</strong>.",tip:"WITH(向後)+DRAW(拉)+AL=拉回來=提款",emoji:"🏧",roots:["with","draw","al"]},
    {word:"workforce",chinese:"勞動力/員工",sentence:"The company has a <strong>workforce</strong> of 10,000 people.",tip:"WORK(工作)+FORCE(力量)=工作的力量=勞動力",emoji:"👥",roots:["work","force"]},
    {word:"yield",chinese:"收益/產出",sentence:"The investment produced a 7% annual <strong>yield</strong>.",tip:"YIELD=產出的結果=收益",emoji:"📈",roots:["yield"]},
    {word:"zoning",chinese:"分區規劃/區劃",sentence:"<strong>Zoning</strong> laws restrict building heights in this area.",tip:"ZONE(區域)+ING=劃分區域=分區規劃",emoji:"🗺️",roots:["zon","ing"]},
    {word:"absenteeism",chinese:"缺勤/曠工",sentence:"High <strong>absenteeism</strong> affects team productivity.",tip:"ABSENT(缺席)+EE+ISM=缺席的現象=缺勤",emoji:"🚫",roots:["absent","ee","ism"]},
    {word:"accrue",chinese:"累積/產生",sentence:"Interest will <strong>accrue</strong> on the outstanding balance.",tip:"AC(向)+CRUE(增長)=逐漸增長=累積",emoji:"📈",roots:["ac","crue"]},
    {word:"adjourn",chinese:"休會/延期",sentence:"The meeting was <strong>adjourned</strong> until next Tuesday.",tip:"AD(向)+JOURN(日)=改到另一天=延期",emoji:"📅",roots:["ad","journ"]},
    {word:"amortize",chinese:"攤銷/分期償還",sentence:"The cost will be <strong>amortized</strong> over five years.",tip:"A+MORT(死)+IZE=慢慢使債務死去=分期償還",emoji:"💰",roots:["a","mort","ize"]},
    {word:"annuity",chinese:"年金/養老金",sentence:"She invested in an <strong>annuity</strong> for retirement income.",tip:"ANNU(年)+ITY=每年的支付=年金",emoji:"📅",roots:["annu","ity"]},
    {word:"arbitration",chinese:"仲裁/調解",sentence:"The dispute was settled through <strong>arbitration</strong>.",tip:"ARBITR(裁判)+ATION=做裁判=仲裁",emoji:"⚖️",roots:["arbitr","ation"]},
    {word:"audit",chinese:"審計/稽核",sentence:"The company undergoes an annual financial <strong>audit</strong>.",tip:"AUDIT=聽取帳目報告=審計",emoji:"📋",roots:["audit"]},
    {word:"austerity",chinese:"緊縮/樸素",sentence:"The government implemented <strong>austerity</strong> measures.",tip:"AUSTER(嚴格)+ITY=嚴格節省=緊縮",emoji:"📉",roots:["auster","ity"]},
    {word:"backlog",chinese:"積壓/待辦事項",sentence:"There is a large <strong>backlog</strong> of orders to fulfill.",tip:"BACK(後面)+LOG(記錄)=積在後面的=積壓",emoji:"📦",roots:["back","log"]},
    {word:"bailout",chinese:"紓困/救助",sentence:"The bank received a government <strong>bailout</strong>.",tip:"BAIL(保釋)+OUT(出)=保出來=紓困",emoji:"💰",roots:["bail","out"]},
    {word:"brokerage",chinese:"經紀業務/佣金",sentence:"The <strong>brokerage</strong> firm handles stock trades.",tip:"BROKER(經紀人)+AGE=經紀人的業務=經紀業務",emoji:"📊",roots:["broker","age"]},
    {word:"cartel",chinese:"壟斷聯盟/卡特爾",sentence:"The oil <strong>cartel</strong> controls global prices.",tip:"CARTEL=聯合壟斷的組織=卡特爾",emoji:"🤝",roots:["cartel"]},
    {word:"clause",chinese:"條款/子句",sentence:"Read every <strong>clause</strong> of the contract carefully.",tip:"CLAUSE=關閉一段話的=條款",emoji:"📜",roots:["clause"]},
    {word:"consortium",chinese:"聯合企業/財團",sentence:"A <strong>consortium</strong> of banks funded the project.",tip:"CON(一起)+SORT(命運)+IUM=命運在一起=聯合企業",emoji:"🏦",roots:["con","sort","ium"]},
    {word:"contingency",chinese:"意外事件/應急",sentence:"We need a <strong>contingency</strong> plan for emergencies.",tip:"CON(一起)+TING(觸)+ENCY=可能觸發的事=意外事件",emoji:"🚨",roots:["con","ting","ency"]},
    {word:"convene",chinese:"召集/召開",sentence:"The board will <strong>convene</strong> an emergency meeting.",tip:"CON(一起)+VENE(來)=一起來=召集",emoji:"🤝",roots:["con","vene"]},
    {word:"deprecate",chinese:"反對/不贊成",sentence:"Management <strong>deprecated</strong> the use of personal devices.",tip:"DE(向下)+PREC(價值)+ATE=降低價值=反對",emoji:"👎",roots:["de","prec","ate"]},
    {word:"designate",chinese:"指定/委派",sentence:"She was <strong>designated</strong> as the project lead.",tip:"DE(完全)+SIGN(標記)+ATE=標記出來=指定",emoji:"👆",roots:["de","sign","ate"]},
    {word:"disburse",chinese:"支付/付出",sentence:"Funds will be <strong>disbursed</strong> after approval.",tip:"DIS(離開)+BURSE(錢包)=從錢包出去=支付",emoji:"💸",roots:["dis","burse"]},
    {word:"divest",chinese:"剝奪/撤資",sentence:"The company decided to <strong>divest</strong> its retail division.",tip:"DI(離開)+VEST(投資)=去掉投資=撤資",emoji:"📉",roots:["di","vest"]},
    {word:"emolument",chinese:"薪酬/報酬",sentence:"The position includes generous <strong>emoluments</strong>.",tip:"E(出)+MOL(磨)+UMENT=磨出成果的報酬=薪酬",emoji:"💰",roots:["e","mol","ument"]},
    {word:"escrow",chinese:"第三方託管/代管",sentence:"The funds are held in <strong>escrow</strong> until closing.",tip:"ES(出)+CROW(滾動)=暫時滾到第三方=託管",emoji:"🔒",roots:["es","crow"]},
    {word:"expedite",chinese:"加速/促進",sentence:"Please <strong>expedite</strong> the processing of this order.",tip:"EX(出)+PED(腳)+ITE=把腳解放出來加速=加速",emoji:"⚡",roots:["ex","ped","ite"]},
    {word:"fiduciary",chinese:"信託的/受信人",sentence:"Directors have a <strong>fiduciary</strong> responsibility to shareholders.",tip:"FIDUC(信任)+IARY=基於信任的=信託的",emoji:"⚖️",roots:["fiduc","iary"]},
    {word:"garnish",chinese:"扣押工資/裝飾",sentence:"The court ordered to <strong>garnish</strong> his wages.",tip:"GARNISH=扣住裝飾=扣押",emoji:"⚖️",roots:["garnish"]},
    {word:"indemnify",chinese:"賠償/保障",sentence:"The policy will <strong>indemnify</strong> you against losses.",tip:"IN(不)+DEMN(損害)+IFY=使不受損害=賠償",emoji:"🛡️",roots:["in","demn","ify"]},
    {word:"insolvency",chinese:"破產/無力償債",sentence:"The firm faces <strong>insolvency</strong> unless it raises capital.",tip:"IN(不)+SOLV(解決/付)+ENCY=付不了=破產",emoji:"💔",roots:["in","solv","ency"]},
    {word:"interim",chinese:"臨時的/過渡期",sentence:"An <strong>interim</strong> manager was appointed.",tip:"INTER(之間)+IM=在兩者之間的=臨時的",emoji:"⏳",roots:["inter","im"]},
    {word:"lien",chinese:"留置權/扣押權",sentence:"The bank placed a <strong>lien</strong> on the property.",tip:"LIEN=綁住的權利=留置權",emoji:"🔗",roots:["lien"]},
    {word:"liquidation",chinese:"清算/清盤",sentence:"The company went into <strong>liquidation</strong>.",tip:"LIQUID(液體)+ATION=變成現金流=清算",emoji:"💧",roots:["liquid","ation"]},
    {word:"moratorium",chinese:"暫停/延期",sentence:"The government declared a <strong>moratorium</strong> on new construction.",tip:"MORATOR(延遲)+IUM=延遲的狀態=暫停",emoji:"⏸️",roots:["morator","ium"]},
    {word:"notarize",chinese:"公證/認證",sentence:"You need to <strong>notarize</strong> this document.",tip:"NOTAR(公證人)+IZE=請公證人認證=公證",emoji:"📋",roots:["notar","ize"]},
    {word:"solvent",chinese:"有償付能力的/溶劑",sentence:"The company remains <strong>solvent</strong> despite the downturn.",tip:"SOLV(解決/付)+ENT=能付得了的=有償付能力的",emoji:"✅",roots:["solv","ent"]}
  ]
};
