WORD_DATA["yle_movers"] = {
  name: "YLE Movers",
  color: "#059669",
  words: [
    {word:"scissors",chinese:"剪刀",sentence:"Please pass me the <strong>scissors</strong>.",tip:"SCISSORS 有兩個 S 像剪刀的兩片刀片！",emoji:"✂️",roots:["scis","sors"]},
    {word:"glue",chinese:"膠水",sentence:"Use <strong>glue</strong> to stick the paper together.",tip:"GLUE 和 BLUE 押韻",emoji:"🧴",roots:["glue"]},
    {word:"chalk",chinese:"粉筆",sentence:"The teacher writes with <strong>chalk</strong> on the board.",tip:"CHALK 的 L 不發音！",emoji:"🖍️",roots:["chalk"]},
    {word:"crayon",chinese:"蠟筆",sentence:"She colored the picture with a red <strong>crayon</strong>.",tip:"CRAY(蠟)+ON=蠟做的筆",emoji:"🖍️",roots:["cray","on"]},
    {word:"notebook",chinese:"筆記本",sentence:"Write the answer in your <strong>notebook</strong>.",tip:"NOTE(筆記)+BOOK(書)=筆記本",emoji:"📓",roots:["note","book"]},
    {word:"ruler",chinese:"尺",sentence:"Use a <strong>ruler</strong> to draw a straight line.",tip:"RULER 也有「統治者」的意思",emoji:"📏",roots:["rul","er"]},
    {word:"rubber",chinese:"橡皮擦",sentence:"Can I borrow your <strong>rubber</strong>? I made a mistake.",tip:"RUBBER 有兩個 B！擦擦擦",emoji:"🧽",roots:["rub","ber"]},
    {word:"envelope",chinese:"信封",sentence:"Put the letter in the <strong>envelope</strong>.",tip:"EN(裡面)+VELOPE(包裹)=把信包起來",emoji:"✉️",roots:["en","vel","ope"]},
    {word:"diary",chinese:"日記",sentence:"She writes in her <strong>diary</strong> every night.",tip:"DI(日)+ARY=每天寫的東西",emoji:"📔",roots:["di","ary"]},
    {word:"pupil",chinese:"學生",sentence:"Every <strong>pupil</strong> must wear a uniform.",tip:"PUPIL 也有「瞳孔」的意思",emoji:"👨‍🎓",roots:["pu","pil"]},
    {word:"brush",chinese:"刷/刷子",sentence:"<strong>Brush</strong> your teeth before bed.",tip:"BRUSH 想到刷刷刷的聲音",emoji:"🪥",roots:["brush"]},
    {word:"toothbrush",chinese:"牙刷",sentence:"I need a new <strong>toothbrush</strong>.",tip:"TOOTH(牙)+BRUSH(刷)=刷牙的工具",emoji:"🪥",roots:["tooth","brush"]},
    {word:"toothpaste",chinese:"牙膏",sentence:"Put some <strong>toothpaste</strong> on your brush.",tip:"TOOTH(牙)+PASTE(糊)=擠在牙刷上的糊",emoji:"🦷",roots:["tooth","paste"]},
    {word:"towel",chinese:"毛巾",sentence:"Dry your hands with a <strong>towel</strong>.",tip:"TOWEL 和 VOWEL 押韻",emoji:"🧖",roots:["tow","el"]},
    {word:"soap",chinese:"肥皂",sentence:"Wash your hands with <strong>soap</strong>.",tip:"SOAP 聽起來像滑滑的感覺",emoji:"🧼",roots:["soap"]},
    {word:"shampoo",chinese:"洗髮精",sentence:"I use <strong>shampoo</strong> to wash my hair.",tip:"SHAMPOO 來自印度語「按摩」",emoji:"🧴",roots:["sham","poo"]},
    {word:"shower",chinese:"淋浴",sentence:"I take a <strong>shower</strong> every morning.",tip:"SHOWER 也有「陣雨」的意思",emoji:"🚿",roots:["show","er"]},
    {word:"comb",chinese:"梳子/梳頭",sentence:"<strong>Comb</strong> your hair before school.",tip:"COMB 的 B 不發音！",emoji:"💇",roots:["comb"]},
    {word:"mirror",chinese:"鏡子",sentence:"She looked at herself in the <strong>mirror</strong>.",tip:"MIRROR 有兩個 R 像照鏡子看到兩個自己",emoji:"🪞",roots:["mir","ror"]},
    {word:"skateboard",chinese:"滑板",sentence:"He rides his <strong>skateboard</strong> to the park.",tip:"SKATE(溜冰)+BOARD(板)=溜冰的板子",emoji:"🛹",roots:["skate","board"]},
    {word:"rollerblade",chinese:"直排輪",sentence:"She loves to <strong>rollerblade</strong> on weekends.",tip:"ROLLER(滾輪)+BLADE(刀片)=有刀片般滾輪的鞋",emoji:"🛼",roots:["roller","blade"]},
    {word:"stamp",chinese:"郵票/蓋章",sentence:"Put a <strong>stamp</strong> on the letter.",tip:"STAMP 想到用力蓋章「碰！」",emoji:"📮",roots:["stamp"]},
    {word:"sticker",chinese:"貼紙",sentence:"She collects <strong>sticker</strong>s of animals.",tip:"STICK(黏)+ER=黏上去的東西",emoji:"🏷️",roots:["stick","er"]},
    {word:"puzzle",chinese:"拼圖/謎題",sentence:"Let's do a jigsaw <strong>puzzle</strong> together.",tip:"PUZZLE 讓你困惑 PUZZLED！",emoji:"🧩",roots:["puz","zle"]},
    {word:"kite",chinese:"風箏",sentence:"We fly a <strong>kite</strong> on windy days.",tip:"KITE 和 BITE 押韻",emoji:"🪁",roots:["kite"]},
    {word:"bank",chinese:"銀行/河岸",sentence:"My mom went to the <strong>bank</strong> to get money.",tip:"BANK 有兩個意思：銀行和河岸",emoji:"🏦",roots:["bank"]},
    {word:"cinema",chinese:"電影院",sentence:"Let's go to the <strong>cinema</strong> tonight.",tip:"CINEMA 來自希臘語「動」的意思",emoji:"🎬",roots:["cin","ema"]},
    {word:"chemist",chinese:"藥局/化學家",sentence:"Go to the <strong>chemist</strong> to buy medicine.",tip:"CHEMIST=研究化學的人，英式指藥局",emoji:"💊",roots:["chem","ist"]},
    {word:"petrol",chinese:"汽油",sentence:"Dad stopped to get <strong>petrol</strong> for the car.",tip:"PETROL = PETR(石頭)+OL(油)=石油",emoji:"⛽",roots:["petr","ol"]},
    {word:"bookshop",chinese:"書店",sentence:"I bought a new book at the <strong>bookshop</strong>.",tip:"BOOK(書)+SHOP(商店)=賣書的店",emoji:"📚",roots:["book","shop"]},
    {word:"whale",chinese:"鯨魚",sentence:"A blue <strong>whale</strong> is the biggest animal.",tip:"WHALE 的 WH 開頭像噴水的聲音",emoji:"🐋",roots:["whale"]},
    {word:"shark",chinese:"鯊魚",sentence:"The <strong>shark</strong> has very sharp teeth.",tip:"SHARK 和 SHARP 都有 SHAR-！",emoji:"🦈",roots:["shark"]},
    {word:"penguin",chinese:"企鵝",sentence:"<strong>Penguin</strong>s live in very cold places.",tip:"PENGUIN 走路搖搖擺擺很可愛",emoji:"🐧",roots:["pen","guin"]},
    {word:"parrot",chinese:"鸚鵡",sentence:"The <strong>parrot</strong> can say hello.",tip:"PARROT 會學人說話，PAR-ROT",emoji:"🦜",roots:["par","rot"]},
    {word:"kitten",chinese:"小貓",sentence:"The <strong>kitten</strong> is playing with a ball.",tip:"KITTEN = KIT(小)+TEN → 小小的貓",emoji:"🐱",roots:["kit","ten"]},
    {word:"puppy",chinese:"小狗",sentence:"We got a new <strong>puppy</strong> for Christmas.",tip:"PUPPY 發音像小狗叫 PUP PUP！",emoji:"🐶",roots:["pup","py"]},
    {word:"cage",chinese:"籠子",sentence:"The bird is in a <strong>cage</strong>.",tip:"CAGE 和 AGE 押韻",emoji:"🦜",roots:["cage"]},
    {word:"wing",chinese:"翅膀",sentence:"The bird opened its <strong>wing</strong>s and flew away.",tip:"WING 想到翅膀揮動 W 的形狀",emoji:"🦅",roots:["wing"]},
    {word:"feather",chinese:"羽毛",sentence:"The <strong>feather</strong> is very soft and light.",tip:"FEATHER 和 WEATHER 押韻",emoji:"🪶",roots:["feath","er"]},
    {word:"paw",chinese:"爪子/腳掌",sentence:"The dog gave me its <strong>paw</strong>.",tip:"PAW 想到動物的肉墊掌",emoji:"🐾",roots:["paw"]},
    {word:"tail",chinese:"尾巴",sentence:"The dog wags its <strong>tail</strong> when happy.",tip:"TAIL 和 TALE(故事)發音一樣！",emoji:"🐕",roots:["tail"]},
    {word:"mango",chinese:"芒果",sentence:"I love eating ripe <strong>mango</strong>.",tip:"MANGO 來自馬來語",emoji:"🥭",roots:["man","go"]},
    {word:"lemonade",chinese:"檸檬水",sentence:"Would you like some cold <strong>lemonade</strong>?",tip:"LEMON(檸檬)+ADE(飲料)=檸檬飲料",emoji:"🍋",roots:["lemon","ade"]},
    {word:"flour",chinese:"麵粉",sentence:"We need <strong>flour</strong> to make a cake.",tip:"FLOUR 和 FLOWER 發音一樣！",emoji:"🌾",roots:["flour"]},
    {word:"cereal",chinese:"穀片/麥片",sentence:"I eat <strong>cereal</strong> with milk for breakfast.",tip:"CEREAL 來自穀物女神 CERES",emoji:"🥣",roots:["cere","al"]},
    {word:"yogurt",chinese:"優格",sentence:"I like strawberry <strong>yogurt</strong>.",tip:"YOGURT 來自土耳其語",emoji:"🥛",roots:["yo","gurt"]},
    {word:"pancake",chinese:"鬆餅/薄餅",sentence:"Mom makes <strong>pancake</strong>s on Sunday.",tip:"PAN(平底鍋)+CAKE(蛋糕)=平底鍋煎的蛋糕",emoji:"🥞",roots:["pan","cake"]},
    {word:"biscuit",chinese:"餅乾",sentence:"Would you like a <strong>biscuit</strong> with your tea?",tip:"BIS(兩次)+CUIT(烤)=烤兩次的東西",emoji:"🍪",roots:["bis","cuit"]},
    {word:"jam",chinese:"果醬",sentence:"Put some <strong>jam</strong> on your toast.",tip:"JAM 也有「塞車」的意思",emoji:"🫙",roots:["jam"]},
    {word:"sausage",chinese:"香腸",sentence:"I like <strong>sausage</strong> for breakfast.",tip:"SAUSAGE 來自拉丁語「鹽醃的」",emoji:"🌭",roots:["saus","age"]},
    {word:"pepper",chinese:"胡椒/辣椒",sentence:"Add some <strong>pepper</strong> to the soup.",tip:"PEPPER 有兩個 P",emoji:"🌶️",roots:["pep","per"]},
    {word:"waterfall",chinese:"瀑布",sentence:"The <strong>waterfall</strong> is very tall and beautiful.",tip:"WATER(水)+FALL(落下)=水落下來",emoji:"💦",roots:["water","fall"]},
    {word:"lake",chinese:"湖",sentence:"We swim in the <strong>lake</strong> in summer.",tip:"LAKE 和 CAKE 押韻",emoji:"🏞️",roots:["lake"]},
    {word:"field",chinese:"田野/場地",sentence:"The cows are eating grass in the <strong>field</strong>.",tip:"FIELD 的 IE 發 /iː/ 的音",emoji:"🌾",roots:["field"]},
    {word:"cave",chinese:"洞穴",sentence:"The bear sleeps in a dark <strong>cave</strong>.",tip:"CAVE 和 BRAVE 押韻",emoji:"🕳️",roots:["cave"]},
    {word:"pond",chinese:"池塘",sentence:"There are frogs in the <strong>pond</strong>.",tip:"POND 和 WAND 押韻",emoji:"🐸",roots:["pond"]},
    {word:"stream",chinese:"小溪",sentence:"We crossed the <strong>stream</strong> on stepping stones.",tip:"STREAM 有流動的感覺",emoji:"🏞️",roots:["stream"]},
    {word:"bush",chinese:"灌木叢",sentence:"The rabbit hid behind the <strong>bush</strong>.",tip:"BUSH 和 PUSH 押韻",emoji:"🌳",roots:["bush"]},
    {word:"badminton",chinese:"羽毛球",sentence:"Let's play <strong>badminton</strong> after school.",tip:"BADMINTON 來自英國一個地名",emoji:"🏸",roots:["bad","min","ton"]},
    {word:"volleyball",chinese:"排球",sentence:"We play <strong>volleyball</strong> on the beach.",tip:"VOLLEY(截擊)+BALL(球)=不讓球落地",emoji:"🏐",roots:["volley","ball"]},
    {word:"hockey",chinese:"曲棍球",sentence:"He plays ice <strong>hockey</strong> every winter.",tip:"HOCKEY 想到用棍子打冰上的圓餅",emoji:"🏒",roots:["hock","ey"]},
    {word:"surfing",chinese:"衝浪",sentence:"<strong>Surfing</strong> is popular in Australia.",tip:"SURF(浪花)+ING=在浪花上的運動",emoji:"🏄",roots:["surf","ing"]},
    {word:"score",chinese:"得分/分數",sentence:"The final <strong>score</strong> was 3 to 1.",tip:"SCORE 原意是「刻痕」來記分",emoji:"🏆",roots:["score"]},
    {word:"racket",chinese:"球拍",sentence:"I bought a new tennis <strong>racket</strong>.",tip:"RACKET 也有「噪音」的意思",emoji:"🎾",roots:["rack","et"]},
    {word:"scarf",chinese:"圍巾",sentence:"Wear a <strong>scarf</strong> when it's cold.",tip:"SCARF 想到冬天脖子上的溫暖",emoji:"🧣",roots:["scarf"]},
    {word:"belt",chinese:"皮帶",sentence:"He wears a brown <strong>belt</strong>.",tip:"BELT 和 MELT 押韻",emoji:"👔",roots:["belt"]},
    {word:"pocket",chinese:"口袋",sentence:"Put the coin in your <strong>pocket</strong>.",tip:"POCKET = POCK(小袋)+ET",emoji:"👖",roots:["pock","et"]},
    {word:"sleeve",chinese:"袖子",sentence:"He rolled up his <strong>sleeve</strong>s.",tip:"SLEEVE 想到手臂滑進去的管子",emoji:"👕",roots:["sleeve"]},
    {word:"collar",chinese:"衣領/項圈",sentence:"The dog wears a red <strong>collar</strong>.",tip:"COLLAR 圍在脖子上的圈",emoji:"👔",roots:["col","lar"]},
    {word:"spotted",chinese:"有斑點的",sentence:"She has a <strong>spotted</strong> dress.",tip:"SPOT(點)+TED=有點點的",emoji:"🐄",roots:["spot","ted"]},
    {word:"headache",chinese:"頭痛",sentence:"I have a terrible <strong>headache</strong>.",tip:"HEAD(頭)+ACHE(痛)=頭痛",emoji:"🤕",roots:["head","ache"]},
    {word:"stomachache",chinese:"肚子痛",sentence:"He has a <strong>stomachache</strong> from eating too much.",tip:"STOMACH(胃)+ACHE(痛)=胃痛",emoji:"🤢",roots:["stomach","ache"]},
    {word:"cough",chinese:"咳嗽",sentence:"Cover your mouth when you <strong>cough</strong>.",tip:"COUGH 的 GH 發 /f/ 的音！",emoji:"😷",roots:["cough"]},
    {word:"sneeze",chinese:"打噴嚏",sentence:"I always <strong>sneeze</strong> in spring.",tip:"SNEEZE 想到「哈啾！」的聲音",emoji:"🤧",roots:["sneeze"]},
    {word:"fever",chinese:"發燒",sentence:"She stayed home because of a <strong>fever</strong>.",tip:"FEVER 想到身體發熱",emoji:"🤒",roots:["fev","er"]},
    {word:"plaster",chinese:"OK繃/石膏",sentence:"Put a <strong>plaster</strong> on the cut.",tip:"PLASTER=貼上去保護傷口的東西",emoji:"🩹",roots:["plast","er"]},
    {word:"medicine",chinese:"藥",sentence:"Take your <strong>medicine</strong> after lunch.",tip:"MEDI(醫治)+CINE=醫治用的東西",emoji:"💊",roots:["medi","cine"]},
    {word:"fog",chinese:"霧",sentence:"Be careful driving in the <strong>fog</strong>.",tip:"FOG 和 DOG 押韻，霧中看到狗",emoji:"🌫️",roots:["fog"]},
    {word:"storm",chinese:"暴風雨",sentence:"The <strong>storm</strong> blew down many trees.",tip:"STORM 想到風暴呼呼吹",emoji:"⛈️",roots:["storm"]},
    {word:"thunder",chinese:"打雷",sentence:"The <strong>thunder</strong> was very loud last night.",tip:"THUNDER 想到天上的轟隆聲",emoji:"⚡",roots:["thun","der"]},
    {word:"lightning",chinese:"閃電",sentence:"<strong>Lightning</strong> lit up the dark sky.",tip:"LIGHT(光)+NING=天空突然的光",emoji:"⚡",roots:["light","ning"]},
    {word:"rainbow",chinese:"彩虹",sentence:"Look! There's a <strong>rainbow</strong> in the sky!",tip:"RAIN(雨)+BOW(弓)=雨後的弓形彩光",emoji:"🌈",roots:["rain","bow"]},
    {word:"ferry",chinese:"渡船",sentence:"We took the <strong>ferry</strong> across the river.",tip:"FERRY 想到載你過河的船",emoji:"⛴️",roots:["fer","ry"]},
    {word:"helicopter",chinese:"直升機",sentence:"The <strong>helicopter</strong> flew over the city.",tip:"HELI(螺旋)+COPTER(翅膀)=螺旋翅膀",emoji:"🚁",roots:["heli","copter"]},
    {word:"ambulance",chinese:"救護車",sentence:"Call an <strong>ambulance</strong> quickly!",tip:"AMBUL(走動)+ANCE=走動的醫院",emoji:"🚑",roots:["ambul","ance"]},
    {word:"lorry",chinese:"卡車",sentence:"The <strong>lorry</strong> carried many boxes.",tip:"LORRY 是英式英文的卡車",emoji:"🚛",roots:["lor","ry"]},
    {word:"curly",chinese:"捲曲的",sentence:"She has beautiful <strong>curly</strong> hair.",tip:"CURL(捲)+Y=捲捲的",emoji:"👩‍🦱",roots:["curl","y"]},
    {word:"straight",chinese:"直的",sentence:"Draw a <strong>straight</strong> line.",tip:"STRAIGHT 有很多字母但只有一個音節！",emoji:"📏",roots:["straight"]},
    {word:"striped",chinese:"有條紋的",sentence:"He wore a <strong>striped</strong> shirt.",tip:"STRIPE(條紋)+D=有條紋的",emoji:"👔",roots:["stripe","d"]},
    {word:"wooden",chinese:"木製的",sentence:"We sat on a <strong>wooden</strong> bench.",tip:"WOOD(木)+EN=木頭做的",emoji:"🪵",roots:["wood","en"]},
    {word:"plastic",chinese:"塑膠的",sentence:"Don't use too many <strong>plastic</strong> bags.",tip:"PLASTIC 來自希臘語「可塑造的」",emoji:"🥤",roots:["plast","ic"]},
    {word:"kick",chinese:"踢",sentence:"<strong>Kick</strong> the ball into the goal!",tip:"KICK 想到腳用力踢出去",emoji:"⚽",roots:["kick"]},
    {word:"bounce",chinese:"彈跳",sentence:"The ball <strong>bounce</strong>d on the floor.",tip:"BOUNCE 想到球碰地板彈起來",emoji:"🏀",roots:["bounce"]},
    {word:"slide",chinese:"溜滑梯/滑動",sentence:"The children love the <strong>slide</strong> in the park.",tip:"SLIDE 想到滑下去的感覺",emoji:"🛝",roots:["slide"]},
    {word:"swing",chinese:"鞦韆/搖擺",sentence:"Push me on the <strong>swing</strong>, please!",tip:"SWING 想到前後搖擺",emoji:"🎠",roots:["swing"]},
    {word:"skip",chinese:"跳繩/跳過",sentence:"The girls like to <strong>skip</strong> rope.",tip:"SKIP 想到輕快地跳跳跳",emoji:"🤸",roots:["skip"]},
    {word:"pour",chinese:"倒/傾倒",sentence:"<strong>Pour</strong> some water into the glass.",tip:"POUR 和 FOUR 押韻",emoji:"🫗",roots:["pour"]},
    {word:"stir",chinese:"攪拌",sentence:"<strong>Stir</strong> the soup with a spoon.",tip:"STIR 想到湯匙轉圈圈",emoji:"🥄",roots:["stir"]},
    {word:"roast",chinese:"烤",sentence:"We <strong>roast</strong> a chicken for dinner.",tip:"ROAST 和 TOAST 押韻",emoji:"🍗",roots:["roast"]},
    {word:"slice",chinese:"切片",sentence:"Cut the bread into <strong>slice</strong>s.",tip:"SLICE 想到薄薄的一片",emoji:"🍞",roots:["slice"]},
    {word:"peel",chinese:"剝皮",sentence:"<strong>Peel</strong> the banana before eating it.",tip:"PEEL 和 FEEL 押韻",emoji:"🍌",roots:["peel"]},
    {word:"fridge",chinese:"冰箱",sentence:"Put the milk back in the <strong>fridge</strong>.",tip:"FRIDGE 是 REFRIGERATOR 的縮寫",emoji:"🧊",roots:["fridge"]},
    {word:"oven",chinese:"烤箱",sentence:"Bake the cake in the <strong>oven</strong> for 30 minutes.",tip:"OVEN 想到裡面很熱",emoji:"🔥",roots:["ov","en"]},
    {word:"bin",chinese:"垃圾桶",sentence:"Throw the wrapper in the <strong>bin</strong>.",tip:"BIN 和 IN 押韻",emoji:"🗑️",roots:["bin"]},
    {word:"shelf",chinese:"架子",sentence:"Put the book back on the <strong>shelf</strong>.",tip:"SHELF 複數是 SHELVES，F 變 VES",emoji:"📚",roots:["shelf"]},
    {word:"cupboard",chinese:"碗櫥/櫃子",sentence:"The plates are in the <strong>cupboard</strong>.",tip:"CUP(杯)+BOARD(板)=放杯子的板=碗櫥",emoji:"🗄️",roots:["cup","board"]},
    {word:"blanket",chinese:"毯子",sentence:"Cover yourself with a <strong>blanket</strong>.",tip:"BLANKET 想到溫暖包覆的感覺",emoji:"🛏️",roots:["blank","et"]},
    {word:"pillow",chinese:"枕頭",sentence:"My <strong>pillow</strong> is very soft.",tip:"PILLOW 想到軟綿綿的",emoji:"🛌",roots:["pil","low"]},
    {word:"fence",chinese:"圍籬",sentence:"The dog jumped over the <strong>fence</strong>.",tip:"FENCE 也有「擊劍」的意思",emoji:"🏡",roots:["fence"]},
    {word:"lawn",chinese:"草坪",sentence:"Dad mows the <strong>lawn</strong> every week.",tip:"LAWN 和 DAWN 押韻",emoji:"🌿",roots:["lawn"]},
    {word:"tidy",chinese:"整齊的/整理",sentence:"Please <strong>tidy</strong> your room.",tip:"TIDY 和 MESSY 是反義詞",emoji:"🧹",roots:["ti","dy"]},
    {word:"entrance",chinese:"入口",sentence:"The <strong>entrance</strong> is on the left.",tip:"ENTER(進入)+ANCE=進入的地方",emoji:"🚪",roots:["entr","ance"]},
    {word:"fountain",chinese:"噴泉",sentence:"There is a beautiful <strong>fountain</strong> in the park.",tip:"FOUNT(泉源)+AIN=泉水噴出來",emoji:"⛲",roots:["fount","ain"]},
    {word:"crossroads",chinese:"十字路口",sentence:"Turn left at the <strong>crossroads</strong>.",tip:"CROSS(交叉)+ROADS(路)=交叉的路",emoji:"🚦",roots:["cross","roads"]},
    {word:"pavement",chinese:"人行道",sentence:"Walk on the <strong>pavement</strong>, not the road.",tip:"PAVE(鋪路)+MENT=鋪好的路",emoji:"🚶",roots:["pave","ment"]},
    {word:"mechanic",chinese:"技工/機械師",sentence:"The <strong>mechanic</strong> fixed our car.",tip:"MECHAN(機械)+IC=修機械的人",emoji:"🔧",roots:["mechan","ic"]},
    {word:"dentist",chinese:"牙醫",sentence:"I visit the <strong>dentist</strong> twice a year.",tip:"DENT(牙)+IST(人)=看牙的人",emoji:"🦷",roots:["dent","ist"]},
    {word:"firefighter",chinese:"消防員",sentence:"The brave <strong>firefighter</strong> saved the cat.",tip:"FIRE(火)+FIGHTER(戰鬥者)=和火戰鬥的人",emoji:"🚒",roots:["fire","fighter"]},
    {word:"octopus",chinese:"章魚",sentence:"The <strong>octopus</strong> has eight arms.",tip:"OCTO(八)+PUS(腳)=八隻腳",emoji:"🐙",roots:["octo","pus"]},
    {word:"dolphin",chinese:"海豚",sentence:"We saw a <strong>dolphin</strong> jumping in the sea.",tip:"DOLPHIN 想到海裡跳躍的朋友",emoji:"🐬",roots:["dol","phin"]},
    {word:"tortoise",chinese:"烏龜(陸龜)",sentence:"The <strong>tortoise</strong> moves very slowly.",tip:"TORTOISE 是住在陸地上的龜",emoji:"🐢",roots:["tor","toise"]},
    {word:"butterfly",chinese:"蝴蝶",sentence:"A colorful <strong>butterfly</strong> landed on the flower.",tip:"BUTTER(奶油)+FLY(飛)=像奶油色般飛",emoji:"🦋",roots:["butter","fly"]},
    {word:"spider",chinese:"蜘蛛",sentence:"The <strong>spider</strong> made a web in the corner.",tip:"SPIDER 想到蜘蛛人 SPIDERMAN",emoji:"🕷️",roots:["spi","der"]},
    {word:"insect",chinese:"昆蟲",sentence:"An ant is a tiny <strong>insect</strong>.",tip:"IN(裡面)+SECT(切)=身體切成段的=昆蟲",emoji:"🐜",roots:["in","sect"]},
    {word:"kangaroo",chinese:"袋鼠",sentence:"The <strong>kangaroo</strong> can jump very far.",tip:"KANGAROO 來自澳洲原住民語言",emoji:"🦘",roots:["kan","ga","roo"]},
    {word:"giraffe",chinese:"長頸鹿",sentence:"The <strong>giraffe</strong> is the tallest animal.",tip:"GIRAFFE 有兩個 F",emoji:"🦒",roots:["gi","raffe"]},
    {word:"hippo",chinese:"河馬",sentence:"The <strong>hippo</strong> swims in the river.",tip:"HIPPO 是 HIPPOPOTAMUS 的縮寫=河馬",emoji:"🦛",roots:["hippo"]},
    {word:"claw",chinese:"爪子",sentence:"The eagle has sharp <strong>claw</strong>s.",tip:"CLAW 想到尖銳的彎鉤",emoji:"🦅",roots:["claw"]},
    {word:"trunk",chinese:"象鼻/樹幹",sentence:"The elephant uses its <strong>trunk</strong> to drink water.",tip:"TRUNK 有三個意思！象鼻、樹幹、行李箱",emoji:"🐘",roots:["trunk"]},
    {word:"foggy",chinese:"有霧的",sentence:"It's too <strong>foggy</strong> to see the road.",tip:"FOG(霧)+GY=霧茫茫的",emoji:"🌫️",roots:["fog","gy"]},
    {word:"degree",chinese:"度/學位",sentence:"It's 30 <strong>degree</strong>s today, very hot!",tip:"DEGREE 表示溫度的度數或學位",emoji:"🌡️",roots:["de","gree"]},
    {word:"thermometer",chinese:"溫度計",sentence:"The nurse used a <strong>thermometer</strong> to check my temperature.",tip:"THERMO(熱)+METER(測量)=測量熱度",emoji:"🌡️",roots:["thermo","meter"]},
    {word:"sunburn",chinese:"曬傷",sentence:"I got a <strong>sunburn</strong> at the beach.",tip:"SUN(太陽)+BURN(燒)=太陽燒傷",emoji:"☀️",roots:["sun","burn"]},
    {word:"umbrella",chinese:"雨傘",sentence:"Take an <strong>umbrella</strong>, it might rain.",tip:"UMBR(陰影)+ELLA=製造陰影的東西",emoji:"☂️",roots:["umbr","ella"]},
    {word:"astronaut",chinese:"太空人",sentence:"The <strong>astronaut</strong> floated in space.",tip:"ASTRO(星)+NAUT(水手)=星際水手",emoji:"👨‍🚀",roots:["astro","naut"]},
    {word:"planet",chinese:"行星",sentence:"Mars is the red <strong>planet</strong>.",tip:"PLANET 來自希臘語「漫遊者」",emoji:"🪐",roots:["plan","et"]},
    {word:"uniform",chinese:"制服",sentence:"We wear a <strong>uniform</strong> to school.",tip:"UNI(一)+FORM(形式)=統一的穿著",emoji:"👔",roots:["uni","form"]},
    {word:"quiz",chinese:"小考/測驗",sentence:"We have a spelling <strong>quiz</strong> today.",tip:"QUIZ 只有四個字母的小測驗",emoji:"📝",roots:["quiz"]},
    {word:"backpack",chinese:"背包",sentence:"Put your books in your <strong>backpack</strong>.",tip:"BACK(背)+PACK(包)=背上的包",emoji:"🎒",roots:["back","pack"]},
    {word:"locker",chinese:"置物櫃",sentence:"Keep your bag in the <strong>locker</strong>.",tip:"LOCK(鎖)+ER=可以上鎖的櫃子",emoji:"🔐",roots:["lock","er"]},
    {word:"playground",chinese:"遊樂場",sentence:"Children play on the <strong>playground</strong> at break time.",tip:"PLAY(玩)+GROUND(地面)=玩的地方",emoji:"🎢",roots:["play","ground"]},
    {word:"canteen",chinese:"食堂/餐廳",sentence:"We eat lunch in the school <strong>canteen</strong>.",tip:"CANTEEN 學校裡吃飯的地方",emoji:"🍽️",roots:["can","teen"]},
    {word:"corridor",chinese:"走廊",sentence:"Don't run in the <strong>corridor</strong>!",tip:"CORRIDOR 想到長長的通道",emoji:"🏫",roots:["cor","ri","dor"]},
    {word:"recipe",chinese:"食譜",sentence:"Follow the <strong>recipe</strong> to make cookies.",tip:"RECIPE 的 E 在結尾發音！",emoji:"📖",roots:["re","ci","pe"]},
    {word:"ingredient",chinese:"食材/成分",sentence:"What <strong>ingredient</strong>s do we need for the cake?",tip:"IN(裡面)+GREDI(走進)+ENT=走進去的東西=成分",emoji:"🥘",roots:["in","gredi","ent"]},
    {word:"lid",chinese:"蓋子",sentence:"Put the <strong>lid</strong> on the pot.",tip:"LID 只有三個字母，蓋住！",emoji:"🍲",roots:["lid"]},
    {word:"spoon",chinese:"湯匙",sentence:"Eat the soup with a <strong>spoon</strong>.",tip:"SPOON 有兩個 O",emoji:"🥄",roots:["spoon"]},
    {word:"fork",chinese:"叉子",sentence:"Use a <strong>fork</strong> to eat the pasta.",tip:"FORK 想到叉子的形狀",emoji:"🍴",roots:["fork"]},
    {word:"napkin",chinese:"餐巾",sentence:"Wipe your mouth with a <strong>napkin</strong>.",tip:"NAPKIN=NAP(布)+KIN(小)=小布",emoji:"🧻",roots:["nap","kin"]},
    {word:"tray",chinese:"托盤",sentence:"Carry your food on a <strong>tray</strong>.",tip:"TRAY 和 DAY 押韻",emoji:"🍽️",roots:["tray"]},
    {word:"barbecue",chinese:"烤肉",sentence:"We have a <strong>barbecue</strong> in the garden.",tip:"BBQ 是 BARBECUE 的縮寫",emoji:"🍖",roots:["bar","be","cue"]},
    {word:"picnic",chinese:"野餐",sentence:"Let's have a <strong>picnic</strong> in the park.",tip:"PIC(挑選)+NIC=挑個好地方吃東西",emoji:"🧺",roots:["pic","nic"]},
    {word:"hamster",chinese:"倉鼠",sentence:"My <strong>hamster</strong> runs on a wheel all night.",tip:"HAMSTER 想到胖胖的倉鼠",emoji:"🐹",roots:["ham","ster"]},
    {word:"goldfish",chinese:"金魚",sentence:"I have a <strong>goldfish</strong> in a bowl.",tip:"GOLD(金)+FISH(魚)=金色的魚",emoji:"🐠",roots:["gold","fish"]},
    {word:"leash",chinese:"牽繩",sentence:"Keep your dog on a <strong>leash</strong>.",tip:"LEASH 想到繩子牽住狗",emoji:"🐕‍🦺",roots:["leash"]},
    {word:"circus",chinese:"馬戲團",sentence:"The <strong>circus</strong> is coming to town!",tip:"CIRCUS 來自拉丁語「圓圈」",emoji:"🎪",roots:["circ","us"]},
    {word:"clown",chinese:"小丑",sentence:"The <strong>clown</strong> made everyone laugh.",tip:"CLOWN 想到紅鼻子和大鞋子",emoji:"🤡",roots:["clown"]},
    {word:"magic",chinese:"魔術/魔法",sentence:"The <strong>magic</strong> show was amazing!",tip:"MAGIC 想到變魔術",emoji:"🎩",roots:["mag","ic"]},
    {word:"trick",chinese:"把戲/技巧",sentence:"The dog can do many <strong>trick</strong>s.",tip:"TRICK 和 TREAT 一起出現在萬聖節",emoji:"🎭",roots:["trick"]},
    {word:"concert",chinese:"音樂會",sentence:"We went to a rock <strong>concert</strong>.",tip:"CON(一起)+CERT(確定)=一起確定節目=音樂會",emoji:"🎶",roots:["con","cert"]},
    {word:"drum",chinese:"鼓",sentence:"He plays the <strong>drum</strong> in the band.",tip:"DRUM 想到咚咚咚的聲音",emoji:"🥁",roots:["drum"]},
    {word:"trumpet",chinese:"小號/喇叭",sentence:"She plays the <strong>trumpet</strong> very well.",tip:"TRUMP(吹號)+ET=吹的樂器",emoji:"🎺",roots:["trump","et"]},
    {word:"violin",chinese:"小提琴",sentence:"She practises the <strong>violin</strong> every day.",tip:"VIOLIN 想到優美的弦樂聲",emoji:"🎻",roots:["vio","lin"]},
    {word:"flute",chinese:"長笛",sentence:"The <strong>flute</strong> makes a beautiful sound.",tip:"FLUTE 想到輕柔的吹奏聲",emoji:"🪈",roots:["flute"]},
    {word:"museum",chinese:"博物館",sentence:"We visited the dinosaur <strong>museum</strong>.",tip:"MUSE(繆斯女神)+UM=繆斯的殿堂",emoji:"🏛️",roots:["muse","um"]},
    {word:"castle",chinese:"城堡",sentence:"The princess lives in a big <strong>castle</strong>.",tip:"CASTLE 的 T 不發音！",emoji:"🏰",roots:["cas","tle"]},
    {word:"tower",chinese:"塔",sentence:"We climbed to the top of the <strong>tower</strong>.",tip:"TOWER 想到高高的建築",emoji:"🗼",roots:["tow","er"]},
    {word:"statue",chinese:"雕像",sentence:"There is a <strong>statue</strong> in the park.",tip:"STATUE 是靜止不動的人形",emoji:"🗽",roots:["stat","ue"]},
    {word:"palace",chinese:"宮殿",sentence:"The king lives in a grand <strong>palace</strong>.",tip:"PALACE 想到金碧輝煌的宮殿",emoji:"👑",roots:["pal","ace"]},
    {word:"treasure",chinese:"寶藏",sentence:"Pirates look for hidden <strong>treasure</strong>.",tip:"TREASURE 想到金幣和寶石",emoji:"💎",roots:["treas","ure"]},
    {word:"pirate",chinese:"海盜",sentence:"The <strong>pirate</strong> sailed across the ocean.",tip:"PIRATE 想到眼罩和寶藏地圖",emoji:"🏴‍☠️",roots:["pir","ate"]},
    {word:"dragon",chinese:"龍",sentence:"The <strong>dragon</strong> breathes fire.",tip:"DRAGON 來自希臘語「大蛇」",emoji:"🐉",roots:["drag","on"]},
    {word:"fairy",chinese:"仙女/精靈",sentence:"The <strong>fairy</strong> granted three wishes.",tip:"FAIRY 想到小翅膀和魔法棒",emoji:"🧚",roots:["fair","y"]},
    {word:"knight",chinese:"騎士",sentence:"The brave <strong>knight</strong> fought the dragon.",tip:"KNIGHT 的 K 和 GH 都不發音！",emoji:"⚔️",roots:["knight"]},
    {word:"wand",chinese:"魔杖",sentence:"The wizard waved his <strong>wand</strong>.",tip:"WAND 和 POND 押韻",emoji:"🪄",roots:["wand"]},
    {word:"witch",chinese:"女巫",sentence:"The <strong>witch</strong> flew on a broomstick.",tip:"WITCH 和 WHICH 發音一樣！",emoji:"🧙‍♀️",roots:["witch"]},
    {word:"ghost",chinese:"鬼/幽靈",sentence:"Is there a <strong>ghost</strong> in that old house?",tip:"GHOST 的 H 不發音",emoji:"👻",roots:["ghost"]},
    {word:"frightened",chinese:"害怕的",sentence:"The cat was <strong>frightened</strong> by the thunder.",tip:"FRIGHT(恐懼)+ENED=被嚇到的",emoji:"😱",roots:["fright","ened"]},
    {word:"horrible",chinese:"可怕的/糟糕的",sentence:"The weather was <strong>horrible</strong> yesterday.",tip:"HORR(恐懼)+IBLE=令人恐懼的",emoji:"😨",roots:["horr","ible"]},
    {word:"excellent",chinese:"極好的",sentence:"You did an <strong>excellent</strong> job!",tip:"EXCEL(超越)+LENT=超越一切的好",emoji:"⭐",roots:["ex","cel","lent"]},
    {word:"enormous",chinese:"巨大的",sentence:"The elephant is <strong>enormous</strong>!",tip:"E(出)+NORM(正常)+OUS=超出正常的大",emoji:"🐘",roots:["e","norm","ous"]},
    {word:"tiny",chinese:"極小的",sentence:"An ant is a <strong>tiny</strong> insect.",tip:"TINY 又小又可愛",emoji:"🐜",roots:["ti","ny"]},
    {word:"midnight",chinese:"午夜",sentence:"The clock struck <strong>midnight</strong>.",tip:"MID(中間)+NIGHT(夜)=夜的正中間",emoji:"🌙",roots:["mid","night"]},
    {word:"noon",chinese:"中午",sentence:"We have lunch at <strong>noon</strong>.",tip:"NOON 有兩個 O 在正中間",emoji:"☀️",roots:["noon"]},
    {word:"postcard",chinese:"明信片",sentence:"I sent a <strong>postcard</strong> from Paris.",tip:"POST(郵寄)+CARD(卡)=寄出去的卡片",emoji:"📬",roots:["post","card"]},
    {word:"address",chinese:"地址",sentence:"Write your <strong>address</strong> on the envelope.",tip:"ADDRESS 有兩個 D",emoji:"🏠",roots:["ad","dress"]},
    {word:"magazine",chinese:"雜誌",sentence:"She reads a fashion <strong>magazine</strong>.",tip:"MAGAZINE 原意是「倉庫」存放知識",emoji:"📰",roots:["mag","a","zine"]},
    {word:"cartoon",chinese:"卡通",sentence:"My favourite <strong>cartoon</strong> is on TV now.",tip:"CARTOON 來自義大利語「大紙」",emoji:"📺",roots:["car","toon"]},
    {word:"comic",chinese:"漫畫",sentence:"I love reading <strong>comic</strong> books.",tip:"COMIC 也有「喜劇的」意思",emoji:"📖",roots:["com","ic"]},
    {word:"channel",chinese:"頻道",sentence:"Change the <strong>channel</strong>, please.",tip:"CHANNEL 也有「水道」的意思",emoji:"📺",roots:["chan","nel"]},
    {word:"sore",chinese:"痠痛的",sentence:"My legs are <strong>sore</strong> after running.",tip:"SORE 和 MORE 押韻",emoji:"🦵",roots:["sore"]},
    {word:"bandage",chinese:"繃帶",sentence:"The nurse put a <strong>bandage</strong> on my arm.",tip:"BAND(綁)+AGE=綁住傷口的東西",emoji:"🩹",roots:["band","age"]},
    {word:"compass",chinese:"指南針",sentence:"Use a <strong>compass</strong> to find north.",tip:"COM(一起)+PASS(步)=一起走對方向的工具",emoji:"🧭",roots:["com","pass"]},
    {word:"tent",chinese:"帳篷",sentence:"We slept in a <strong>tent</strong> at the campsite.",tip:"TENT 想到三角形的帳篷",emoji:"⛺",roots:["tent"]},
    {word:"campfire",chinese:"營火",sentence:"We sang songs around the <strong>campfire</strong>.",tip:"CAMP(營地)+FIRE(火)=營地的火",emoji:"🔥",roots:["camp","fire"]},
    {word:"torch",chinese:"手電筒",sentence:"Use a <strong>torch</strong> to see in the dark.",tip:"TORCH 英式指手電筒",emoji:"🔦",roots:["torch"]},
    {word:"rope",chinese:"繩子",sentence:"Hold the <strong>rope</strong> tight!",tip:"ROPE 和 HOPE 押韻",emoji:"🪢",roots:["rope"]},
    {word:"sunset",chinese:"日落",sentence:"The <strong>sunset</strong> was beautiful tonight.",tip:"SUN(太陽)+SET(落下)=太陽落下",emoji:"🌅",roots:["sun","set"]},
    {word:"sunrise",chinese:"日出",sentence:"We woke up early to see the <strong>sunrise</strong>.",tip:"SUN(太陽)+RISE(升起)=太陽升起",emoji:"🌄",roots:["sun","rise"]},
    {word:"shadow",chinese:"影子",sentence:"My <strong>shadow</strong> follows me everywhere.",tip:"SHADOW 想到跟在身後的黑影",emoji:"👤",roots:["shad","ow"]},
    {word:"squirrel",chinese:"松鼠",sentence:"The <strong>squirrel</strong> climbs up the tree.",tip:"SQUIRREL 很難拼！SQUIR+REL",emoji:"🐿️",roots:["squir","rel"]},
    {word:"caterpillar",chinese:"毛毛蟲",sentence:"The <strong>caterpillar</strong> will become a butterfly.",tip:"CATERPILLAR 想到好餓好餓的毛毛蟲",emoji:"🐛",roots:["cater","pillar"]},
    {word:"nest",chinese:"巢",sentence:"The bird built a <strong>nest</strong> in the tree.",tip:"NEST 和 BEST 押韻",emoji:"🪹",roots:["nest"]},
    {word:"beak",chinese:"鳥喙",sentence:"The bird holds a worm in its <strong>beak</strong>.",tip:"BEAK 和 PEAK 押韻",emoji:"🐦",roots:["beak"]},
    {word:"drizzle",chinese:"毛毛雨",sentence:"It's just a light <strong>drizzle</strong> outside.",tip:"DRIZZLE 想到細細小小的雨滴",emoji:"🌦️",roots:["driz","zle"]},
    {word:"freeze",chinese:"結冰/凍住",sentence:"Water will <strong>freeze</strong> at zero degrees.",tip:"FREEZE 想到冷到凍住",emoji:"🥶",roots:["freeze"]},
    {word:"melt",chinese:"融化",sentence:"The ice cream started to <strong>melt</strong>.",tip:"MELT 和 BELT 押韻",emoji:"🍦",roots:["melt"]},
    {word:"tractor",chinese:"拖拉機",sentence:"The farmer drives a <strong>tractor</strong>.",tip:"TRACT(拉)+OR=拉東西的機器",emoji:"🚜",roots:["tract","or"]},
    {word:"motorcycle",chinese:"摩托車",sentence:"He rides a <strong>motorcycle</strong> to work.",tip:"MOTOR(馬達)+CYCLE(輪子)=有馬達的輪子",emoji:"🏍️",roots:["motor","cycle"]},
    {word:"sailing",chinese:"帆船運動",sentence:"We go <strong>sailing</strong> on the lake.",tip:"SAIL(帆)+ING=揚帆的活動",emoji:"⛵",roots:["sail","ing"]},
    {word:"athlete",chinese:"運動員",sentence:"The <strong>athlete</strong> runs very fast.",tip:"ATHLETE 想到奧運選手",emoji:"🏃",roots:["ath","lete"]},
    {word:"medal",chinese:"獎牌",sentence:"She won a gold <strong>medal</strong>.",tip:"MEDAL 和 METAL 只差一個字母",emoji:"🏅",roots:["med","al"]},
    {word:"coach",chinese:"教練",sentence:"The <strong>coach</strong> taught us new moves.",tip:"COACH 也有「長途巴士」的意思",emoji:"🏋️",roots:["coach"]},
    {word:"gymnasium",chinese:"體育館",sentence:"We play basketball in the <strong>gymnasium</strong>.",tip:"GYMNAS(訓練)+IUM=訓練的地方",emoji:"🏀",roots:["gym","nas","ium"]},
    {word:"pitch",chinese:"球場/投球",sentence:"The football <strong>pitch</strong> is very big.",tip:"PITCH 有很多意思：球場、音高、投",emoji:"⚽",roots:["pitch"]},
    {word:"net",chinese:"網",sentence:"The ball went into the <strong>net</strong>.",tip:"NET 也有「網路」的意思",emoji:"🥅",roots:["net"]},
    {word:"whistle",chinese:"哨子/吹哨",sentence:"The referee blew the <strong>whistle</strong>.",tip:"WHISTLE 的 T 不發音！",emoji:"📯",roots:["whist","le"]},
    {word:"seal",chinese:"海豹",sentence:"The <strong>seal</strong> clapped its flippers.",tip:"SEAL 也有「印章/密封」的意思",emoji:"🦭",roots:["seal"]},
    {word:"polar",chinese:"極地的",sentence:"<strong>Polar</strong> bears live in the Arctic.",tip:"POLAR 來自 POLE(極點)",emoji:"🐻‍❄️",roots:["pol","ar"]},
    {word:"jungle",chinese:"叢林",sentence:"Tigers live in the <strong>jungle</strong>.",tip:"JUNGLE 想到茂密的熱帶森林",emoji:"🌴",roots:["jun","gle"]},
    {word:"branch",chinese:"樹枝/分支",sentence:"The bird sat on a <strong>branch</strong>.",tip:"BRANCH 也有「分店」的意思",emoji:"🌿",roots:["branch"]},
    {word:"root",chinese:"根",sentence:"The tree has deep <strong>root</strong>s.",tip:"ROOT 想到深入土壤的根",emoji:"🌱",roots:["root"]},
    {word:"petal",chinese:"花瓣",sentence:"The flower has pink <strong>petal</strong>s.",tip:"PETAL 想到花瓣一片一片",emoji:"🌸",roots:["pet","al"]},
    {word:"seed",chinese:"種子",sentence:"Plant a <strong>seed</strong> and watch it grow.",tip:"SEED 想到小小的種子長成大樹",emoji:"🌱",roots:["seed"]},
    {word:"mud",chinese:"泥巴",sentence:"Don't step in the <strong>mud</strong>!",tip:"MUD 和 BUD 押韻",emoji:"💩",roots:["mud"]},
    {word:"sand",chinese:"沙子",sentence:"We build castles with <strong>sand</strong>.",tip:"SAND 想到海邊的沙灘",emoji:"🏖️",roots:["sand"]},
    {word:"wool",chinese:"羊毛",sentence:"This sweater is made of <strong>wool</strong>.",tip:"WOOL 有兩個 O 像綿羊的兩隻眼睛",emoji:"🧶",roots:["wool"]},
    {word:"fur",chinese:"毛皮",sentence:"The cat has soft <strong>fur</strong>.",tip:"FUR 想到動物柔軟的毛",emoji:"🐈",roots:["fur"]},
    {word:"diamond",chinese:"鑽石",sentence:"A <strong>diamond</strong> is very hard and shiny.",tip:"DIA(穿過)+MOND=穿透一切的石頭",emoji:"💎",roots:["dia","mond"]},
    {word:"calendar",chinese:"日曆",sentence:"Mark the date on the <strong>calendar</strong>.",tip:"CALENDAR 想到一格一格的日期",emoji:"📅",roots:["cal","en","dar"]},
    {word:"decoration",chinese:"裝飾",sentence:"We put up Christmas <strong>decoration</strong>s.",tip:"DECOR(裝飾)+ATION=裝飾品",emoji:"🎄",roots:["decor","ation"]},
    {word:"balloon",chinese:"氣球",sentence:"The child held a red <strong>balloon</strong>.",tip:"BALLOON 有兩個 L 和兩個 O",emoji:"🎈",roots:["bal","loon"]},
    {word:"candle",chinese:"蠟燭",sentence:"Blow out the <strong>candle</strong>s on the cake.",tip:"CANDLE 想到搖曳的火光",emoji:"🕯️",roots:["cand","le"]},
    {word:"wrap",chinese:"包裝",sentence:"Please <strong>wrap</strong> the present nicely.",tip:"WRAP 的 W 不發音！",emoji:"🎁",roots:["wrap"]},
    {word:"handsome",chinese:"英俊的",sentence:"The prince was very <strong>handsome</strong>.",tip:"HAND(手)+SOME=好拿的=好看的",emoji:"🤴",roots:["hand","some"]},
    {word:"beard",chinese:"鬍子",sentence:"Santa has a long white <strong>beard</strong>.",tip:"BEARD 想到聖誕老人的大鬍子",emoji:"🧔",roots:["beard"]},
    {word:"moustache",chinese:"八字鬍",sentence:"My uncle has a big <strong>moustache</strong>.",tip:"MOUSTACHE 嘴上面的鬍子",emoji:"🥸",roots:["moust","ache"]},
    {word:"fringe",chinese:"瀏海",sentence:"She has a short <strong>fringe</strong>.",tip:"FRINGE 也有「邊緣」的意思",emoji:"💇‍♀️",roots:["fringe"]},
    {word:"bald",chinese:"禿頭的",sentence:"My grandpa is <strong>bald</strong>.",tip:"BALD 和 BALL 只差一個字母",emoji:"👨‍🦲",roots:["bald"]},
    {word:"freckle",chinese:"雀斑",sentence:"She has cute <strong>freckle</strong>s on her nose.",tip:"FRECKLE 想到臉上的小點點",emoji:"👧",roots:["freck","le"]},
    {word:"escalator",chinese:"手扶梯",sentence:"Take the <strong>escalator</strong> to the second floor.",tip:"ESCALAT(攀升)+OR=向上升的東西",emoji:"🛗",roots:["es","cal","ator"]},
    {word:"suitcase",chinese:"手提箱",sentence:"Pack your clothes in the <strong>suitcase</strong>.",tip:"SUIT(套裝)+CASE(箱)=裝套裝的箱子",emoji:"🧳",roots:["suit","case"]},
    {word:"aquarium",chinese:"水族館",sentence:"We saw beautiful fish at the <strong>aquarium</strong>.",tip:"AQUA(水)+RIUM(地方)=水的地方",emoji:"🐠",roots:["aqua","rium"]},
    {word:"souvenir",chinese:"紀念品",sentence:"I bought a <strong>souvenir</strong> for my friend.",tip:"SOUVENIR 法語「記得」=幫你記得的東西",emoji:"🎁",roots:["sou","ve","nir"]},
    {word:"scenery",chinese:"風景",sentence:"The mountain <strong>scenery</strong> was beautiful.",tip:"SCENE(場景)+RY=美麗的場景",emoji:"🏔️",roots:["scen","ery"]},
    {word:"guide",chinese:"導遊/指南",sentence:"The <strong>guide</strong> showed us around the museum.",tip:"GUIDE 的 UI 發 /aɪ/ 的音",emoji:"🗺️",roots:["guide"]},
    {word:"purse",chinese:"錢包",sentence:"She keeps coins in her <strong>purse</strong>.",tip:"PURSE 和 NURSE 押韻",emoji:"👛",roots:["purse"]},
    {word:"coin",chinese:"硬幣",sentence:"I found a gold <strong>coin</strong> on the ground.",tip:"COIN 也有「創造新詞」的意思",emoji:"🪙",roots:["coin"]},
    {word:"alarm",chinese:"鬧鐘/警報",sentence:"Set the <strong>alarm</strong> for 7 o'clock.",tip:"ALARM 來自義大利語「拿起武器！」",emoji:"⏰",roots:["a","larm"]},
    {word:"adventure",chinese:"冒險",sentence:"Going camping is a great <strong>adventure</strong>.",tip:"AD(去)+VENTURE(來)=去經歷=冒險",emoji:"🗺️",roots:["ad","vent","ure"]},
    {word:"ladybird",chinese:"瓢蟲",sentence:"A <strong>ladybird</strong> landed on my hand.",tip:"LADY(女士)+BIRD(鳥)=聖母的蟲",emoji:"🐞",roots:["lady","bird"]},
    {word:"cobweb",chinese:"蜘蛛網",sentence:"There was a dusty <strong>cobweb</strong> in the corner.",tip:"COB(蜘蛛)+WEB(網)=蜘蛛的網",emoji:"🕸️",roots:["cob","web"]},
    {word:"hedgehog",chinese:"刺蝟",sentence:"The <strong>hedgehog</strong> curled into a ball.",tip:"HEDGE(樹籬)+HOG(豬)=住在樹籬裡的小豬",emoji:"🦔",roots:["hedge","hog"]},
    {word:"swan",chinese:"天鵝",sentence:"The white <strong>swan</strong> swam across the lake.",tip:"SWAN 想到優雅的白色大鳥",emoji:"🦢",roots:["swan"]},
    {word:"beetle",chinese:"甲蟲",sentence:"The shiny <strong>beetle</strong> flew away.",tip:"BEETLE 和 BEATLE(披頭四)一樣",emoji:"🪲",roots:["beet","le"]},
    {word:"tadpole",chinese:"蝌蚪",sentence:"The <strong>tadpole</strong> will become a frog.",tip:"TAD(小)+POLE(頭)=有小頭的東西",emoji:"🐸",roots:["tad","pole"]},
    {word:"wasp",chinese:"黃蜂",sentence:"Be careful! There's a <strong>wasp</strong> near your drink.",tip:"WASP 比 BEE 更會叮人",emoji:"🐝",roots:["wasp"]},
    {word:"snail",chinese:"蝸牛",sentence:"The <strong>snail</strong> moved slowly across the path.",tip:"SNAIL 想到慢慢爬的蝸牛",emoji:"🐌",roots:["snail"]},
    {word:"camel",chinese:"駱駝",sentence:"A <strong>camel</strong> can survive without water for days.",tip:"CAMEL 想到沙漠裡的駝峰",emoji:"🐪",roots:["cam","el"]},
    {word:"peacock",chinese:"孔雀",sentence:"The <strong>peacock</strong> spread its beautiful feathers.",tip:"PEA(孔雀)+COCK(公雞)=漂亮的公雞",emoji:"🦚",roots:["pea","cock"]},
    {word:"donkey",chinese:"驢子",sentence:"The <strong>donkey</strong> carried heavy bags.",tip:"DONKEY 想到又固執又可愛的動物",emoji:"🫏",roots:["don","key"]},
    {word:"eagle",chinese:"老鷹",sentence:"The <strong>eagle</strong> flew high in the sky.",tip:"EAGLE 想到展翅高飛",emoji:"🦅",roots:["ea","gle"]},
    {word:"pigeon",chinese:"鴿子",sentence:"<strong>Pigeon</strong>s are common in the city.",tip:"PIGEON 想到公園裡的鴿子",emoji:"🐦",roots:["pig","eon"]},
    {word:"flamingo",chinese:"紅鶴",sentence:"The pink <strong>flamingo</strong> stood on one leg.",tip:"FLAMINGO 來自「火焰」=火焰色的鳥",emoji:"🦩",roots:["flam","ingo"]},
    {word:"hoof",chinese:"蹄",sentence:"The horse's <strong>hoof</strong> made a loud sound.",tip:"HOOF 複數是 HOOVES",emoji:"🐴",roots:["hoof"]},
    {word:"stable",chinese:"馬廄",sentence:"The horses sleep in the <strong>stable</strong>.",tip:"STABLE 也有「穩定的」意思",emoji:"🐴",roots:["sta","ble"]},
    {word:"hay",chinese:"乾草",sentence:"The farmer feeds <strong>hay</strong> to the cows.",tip:"HAY 想到金黃色的乾草堆",emoji:"🌾",roots:["hay"]},
    {word:"scarecrow",chinese:"稻草人",sentence:"The <strong>scarecrow</strong> kept birds away from the crops.",tip:"SCARE(嚇)+CROW(烏鴉)=嚇烏鴉的東西",emoji:"🎃",roots:["scare","crow"]},
    {word:"wheelbarrow",chinese:"獨輪手推車",sentence:"He pushed the <strong>wheelbarrow</strong> full of soil.",tip:"WHEEL(輪)+BARROW(推車)=有輪子的推車",emoji:"🧑‍🌾",roots:["wheel","barrow"]},
    {word:"watering",chinese:"澆水",sentence:"She is <strong>watering</strong> the flowers in the garden.",tip:"WATER(水)+ING=給植物水",emoji:"🌻",roots:["water","ing"]},
    {word:"compost",chinese:"堆肥",sentence:"Put the leaves in the <strong>compost</strong> bin.",tip:"COM(一起)+POST(放)=放在一起分解=堆肥",emoji:"🌿",roots:["com","post"]},
    {word:"orchard",chinese:"果園",sentence:"We picked apples in the <strong>orchard</strong>.",tip:"ORCHARD 想到一排排的果樹",emoji:"🍎",roots:["orch","ard"]},
    {word:"plough",chinese:"犁/耕田",sentence:"The farmer used a <strong>plough</strong> to prepare the soil.",tip:"PLOUGH 英式拼法，美式是 PLOW",emoji:"🚜",roots:["plough"]},
    {word:"porridge",chinese:"粥/燕麥粥",sentence:"I eat <strong>porridge</strong> for breakfast.",tip:"PORRIDGE 想到溫暖的早餐粥",emoji:"🥣",roots:["porr","idge"]},
    {word:"doughnut",chinese:"甜甜圈",sentence:"She bought a chocolate <strong>doughnut</strong>.",tip:"DOUGH(麵糰)+NUT=像堅果形狀的麵糰",emoji:"🍩",roots:["dough","nut"]},
    {word:"syrup",chinese:"糖漿",sentence:"Pour some <strong>syrup</strong> on the pancakes.",tip:"SYRUP 想到甜甜黏黏的糖漿",emoji:"🍯",roots:["syr","up"]},
    {word:"vinegar",chinese:"醋",sentence:"Add a little <strong>vinegar</strong> to the salad.",tip:"VIN(酒)+EGAR(酸)=酸掉的酒=醋",emoji:"🫙",roots:["vin","egar"]},
    {word:"custard",chinese:"卡士達/蛋奶醬",sentence:"I love apple pie with <strong>custard</strong>.",tip:"CUSTARD 想到黃色滑滑的蛋奶醬",emoji:"🥧",roots:["cust","ard"]},
    {word:"grater",chinese:"磨碎器",sentence:"Use a <strong>grater</strong> to grate the cheese.",tip:"GRATE(磨碎)+R=磨碎東西的工具",emoji:"🧀",roots:["grat","er"]},
    {word:"chopstick",chinese:"筷子",sentence:"Can you eat with <strong>chopstick</strong>s?",tip:"CHOP(切)+STICK(棍)=切食物的棍子",emoji:"🥢",roots:["chop","stick"]},
    {word:"microwave",chinese:"微波爐",sentence:"Heat the food in the <strong>microwave</strong>.",tip:"MICRO(微小)+WAVE(波)=用微小的波加熱",emoji:"📻",roots:["micro","wave"]},
    {word:"kettle",chinese:"水壺",sentence:"Boil water in the <strong>kettle</strong>.",tip:"KETTLE 想到咻咻叫的水壺",emoji:"🫖",roots:["ket","tle"]},
    {word:"saucepan",chinese:"平底鍋",sentence:"Heat the soup in a <strong>saucepan</strong>.",tip:"SAUCE(醬)+PAN(鍋)=煮醬汁的鍋",emoji:"🍳",roots:["sauce","pan"]},
    {word:"wardrobe",chinese:"衣櫥",sentence:"Hang your coat in the <strong>wardrobe</strong>.",tip:"WARD(守護)+ROBE(衣服)=守護衣服的地方",emoji:"🚪",roots:["ward","robe"]},
    {word:"radiator",chinese:"暖氣機",sentence:"Sit near the <strong>radiator</strong> to stay warm.",tip:"RADIAT(放射)+OR=放射熱量的東西",emoji:"🔥",roots:["radi","ator"]},
    {word:"doorbell",chinese:"門鈴",sentence:"Ring the <strong>doorbell</strong> and wait.",tip:"DOOR(門)+BELL(鈴)=門口的鈴",emoji:"🔔",roots:["door","bell"]},
    {word:"letterbox",chinese:"信箱",sentence:"Check the <strong>letterbox</strong> for mail.",tip:"LETTER(信)+BOX(箱)=放信的箱子",emoji:"📬",roots:["letter","box"]},
    {word:"dustbin",chinese:"垃圾桶",sentence:"Put the rubbish in the <strong>dustbin</strong>.",tip:"DUST(灰塵)+BIN(桶)=放灰塵垃圾的桶",emoji:"🗑️",roots:["dust","bin"]},
    {word:"hedge",chinese:"樹籬",sentence:"We planted a <strong>hedge</strong> around the garden.",tip:"HEDGE 想到矮矮整齊的圍牆樹",emoji:"🌿",roots:["hedge"]},
    {word:"flowerpot",chinese:"花盆",sentence:"She planted seeds in the <strong>flowerpot</strong>.",tip:"FLOWER(花)+POT(盆)=種花的盆子",emoji:"🪴",roots:["flower","pot"]},
    {word:"pebble",chinese:"小石子/鵝卵石",sentence:"We threw <strong>pebble</strong>s into the lake.",tip:"PEBBLE 想到光滑圓圓的小石頭",emoji:"🪨",roots:["peb","ble"]},
    {word:"seashell",chinese:"貝殼",sentence:"She collected <strong>seashell</strong>s on the beach.",tip:"SEA(海)+SHELL(殼)=海邊的殼",emoji:"🐚",roots:["sea","shell"]},
    {word:"haystack",chinese:"乾草堆",sentence:"The cat hid behind the <strong>haystack</strong>.",tip:"HAY(乾草)+STACK(堆)=堆起來的乾草",emoji:"🌾",roots:["hay","stack"]},
    {word:"crew",chinese:"全體人員/隊員",sentence:"The ship's <strong>crew</strong> worked hard.",tip:"CREW 想到一起工作的夥伴",emoji:"🚢",roots:["crew"]},
    {word:"captain",chinese:"船長/隊長",sentence:"The <strong>captain</strong> steered the ship.",tip:"CAPTAIN 來自拉丁語「頭」=頭頭",emoji:"🧑‍✈️",roots:["capt","ain"]},
    {word:"runway",chinese:"跑道",sentence:"The plane took off from the <strong>runway</strong>.",tip:"RUN(跑)+WAY(路)=飛機跑的路",emoji:"🛫",roots:["run","way"]},
    {word:"harbor",chinese:"港口",sentence:"Boats are parked in the <strong>harbor</strong>.",tip:"HARBOR=船的避風港",emoji:"⚓",roots:["harb","or"]},
    {word:"anchor",chinese:"錨",sentence:"The ship dropped its <strong>anchor</strong>.",tip:"ANCHOR 想到讓船停下來的重物",emoji:"⚓",roots:["anch","or"]},
    {word:"lifeboat",chinese:"救生艇",sentence:"Every ship has a <strong>lifeboat</strong>.",tip:"LIFE(生命)+BOAT(船)=救命的船",emoji:"🚤",roots:["life","boat"]}
  ]
};
