WORD_DATA["competition_mid"] = {

    name: "公館基礎",
    color: "#7c3aed",
    words: [
      {word:"boy",definition:"a young male child who grows up to be a man",chinese:"男孩",sentence:"The <strong>boy</strong> is playing in the park.",tip:"BOY 只有三個字母，很好記！",emoji:"👦",roots:["boy"]},
      {word:"girl",definition:"a young female child who grows up to be a woman",chinese:"女孩",sentence:"The <strong>girl</strong> has a red dress.",tip:"GIRL 和 CURL、PEARL 押韻，注意中間是 IR",emoji:"👧",roots:["girl"]},
      {word:"dad",definition:"your father, the man who is your parent",chinese:"爸爸",sentence:"My <strong>dad</strong> cooks dinner.",tip:"DAD 正著讀反著讀都一樣！",emoji:"👨",roots:["dad"]},
      {word:"mom",definition:"your mother, the woman who is your parent",chinese:"媽媽",sentence:"My <strong>mom</strong> gives me a hug.",tip:"MOM 正著讀反著讀都一樣！",emoji:"👩",roots:["mom"]},
      {word:"apple",definition:"a round red or green fruit that is sweet and crunchy",chinese:"蘋果",sentence:"I eat an <strong>apple</strong> every day.",tip:"APPLE 有兩個 P！它是一個完整的字，不能拆成有意義的字根",emoji:"🍎",roots:["apple"]},
      {word:"cake",definition:"a sweet soft food you bake and eat at parties and birthdays",chinese:"蛋糕",sentence:"We have <strong>cake</strong> for my birthday.",tip:"CAKE 結尾的 E 不發音",emoji:"🎂",roots:["cake"]},
      {word:"egg",definition:"an oval food with a shell that a hen lays",chinese:"蛋",sentence:"I eat one <strong>egg</strong> for breakfast.",tip:"EGG 有兩個 G",emoji:"🥚",roots:["egg"]},
      {word:"zoo",definition:"a place where you go to see many wild animals",chinese:"動物園",sentence:"We go to the <strong>zoo</strong> on Sunday.",tip:"ZOO 有兩個 O",emoji:"🦁",roots:["zoo"]},
      {word:"blue",definition:"the color of the clear sky and the deep sea",chinese:"藍色",sentence:"The sky is <strong>blue</strong> today.",tip:"BLUE 想到天空和大海",emoji:"🔵",roots:["blue"]},
      {word:"green",definition:"the color of grass and tree leaves",chinese:"綠色",sentence:"The <strong>green</strong> leaves are beautiful.",tip:"GREEN 有兩個 E",emoji:"🟢",roots:["green"]},
      {word:"red",definition:"the color of blood, fire, and ripe strawberries",chinese:"紅色",sentence:"I have a <strong>red</strong> ball.",tip:"RED 只有三個字母",emoji:"🔴",roots:["red"]},
      {word:"yellow",definition:"the color of the sun, lemons, and egg yolks",chinese:"黃色",sentence:"The sun is <strong>yellow</strong>.",tip:"YELLOW 有兩個 L；它是一個完整的字，不能拆成有意義的字根",emoji:"🟡",roots:["yellow"]},
      {word:"color",definition:"how something looks, like red, blue, or yellow",chinese:"顏色",sentence:"What <strong>color</strong> do you like?",tip:"COLOR 美式拼法，英式是 colour；它源自拉丁文 color，是一個完整的字，不能拆成有意義的字根",emoji:"🎨",roots:["color"]},
      {word:"ball",definition:"a round toy you throw, kick, or bounce",chinese:"球",sentence:"Let's play with the <strong>ball</strong>.",tip:"BALL 有兩個 L",emoji:"⚽",roots:["ball"]},
      {word:"bag",definition:"a soft holder you carry your things in",chinese:"袋子/書包",sentence:"Put the book in your <strong>bag</strong>.",tip:"BAG 和 BIG 只差一個字母",emoji:"🎒",roots:["bag"]},
      {word:"book",definition:"pages with words and pictures that you read",chinese:"書",sentence:"I read a <strong>book</strong> every night.",tip:"BOOK 有兩個 O",emoji:"📖",roots:["book"]},
      {word:"box",definition:"a container with flat sides that holds things",chinese:"箱子",sentence:"The toy is in the <strong>box</strong>.",tip:"BOX 結尾的 X 發 /ks/ 的音",emoji:"📦",roots:["box"]},
      {word:"pencil",definition:"a thin wooden stick you use to write and draw",chinese:"鉛筆",sentence:"Write your name with a <strong>pencil</strong>.",tip:"用聯想記：PENCIL 開頭剛好長得像 PEN（筆）；它其實源自拉丁文 penicillus（小刷子），-cil 不是有意思的字根喔",emoji:"✏️",roots:["pencil"]},
      {word:"bird",definition:"an animal with feathers and wings that can fly",chinese:"鳥",sentence:"The <strong>bird</strong> sings in the tree.",tip:"BIRD 和 BIRTHDAY 開頭一樣",emoji:"🐦",roots:["bird"]},
      {word:"cat",definition:"a small furry pet that says meow and chases mice",chinese:"貓",sentence:"My <strong>cat</strong> sleeps all day.",tip:"CAT 只有三個字母",emoji:"🐱",roots:["cat"]},
      {word:"cow",definition:"a big farm animal that gives us milk",chinese:"牛",sentence:"The <strong>cow</strong> gives us milk.",tip:"COW 和 HOW 押韻",emoji:"🐄",roots:["cow"]},
      {word:"dog",definition:"a furry animal that barks and is a pet",chinese:"狗",sentence:"I walk my <strong>dog</strong> after school.",tip:"DOG 反過來是 GOD",emoji:"🐕",roots:["dog"]},
      {word:"fish",definition:"an animal with fins that swims and lives in water",chinese:"魚",sentence:"There are many <strong>fish</strong> in the sea.",tip:"FISH 的複數也是 FISH",emoji:"🐟",roots:["fish"]},
      {word:"pig",definition:"a fat pink farm animal with a curly tail",chinese:"豬",sentence:"The <strong>pig</strong> is pink and cute.",tip:"PIG 和 BIG 押韻",emoji:"🐷",roots:["pig"]},
      {word:"cup",definition:"a small round container you drink from",chinese:"杯子",sentence:"I drink water from a <strong>cup</strong>.",tip:"CUP 和 UP 押韻",emoji:"☕",roots:["cup"]},
      {word:"yo-yo",definition:"a round toy on a string that rolls down and back up",chinese:"溜溜球",sentence:"I can play with my <strong>yo-yo</strong>.",tip:"YO-YO 上上下下的玩具；它是重複同一個音節的完整字名，YO 本身不是有意義的字根",emoji:"🪀",roots:["yo-yo"]},
      {word:"kid",definition:"a child or young person",chinese:"小孩",sentence:"Every <strong>kid</strong> loves ice cream.",tip:"KID 和 LID（蓋子）押韻",emoji:"🧒",roots:["kid"]},
      {word:"student",definition:"a person who goes to school to learn",chinese:"學生",sentence:"I am a good <strong>student</strong>.",tip:"STUDENT 源自拉丁文 studēre（學習／熱衷）＋字尾 -ent（做某事的人）；stud- 和 -ent 是真正的構詞語素",emoji:"🧑‍🎓",roots:["stud","ent"]},
      {word:"teacher",definition:"a person whose job is to teach children at school",chinese:"老師",sentence:"Our <strong>teacher</strong> is very kind.",tip:"TEACHER = TEACH + ER（教的人）",emoji:"👩‍🏫",roots:["teach","er"]},
      {word:"doctor",definition:"a person who helps sick people get better",chinese:"醫生",sentence:"The <strong>doctor</strong> helps sick people.",tip:"DOCTOR 的歷史來源是拉丁文 docēre（教導）；在英文裡它是一個完整的字，不用拆成有意義的字根",emoji:"👨‍⚕️",roots:["doctor"]},
      {word:"friend",definition:"a person you like and enjoy spending time with",chinese:"朋友",sentence:"She is my best <strong>friend</strong>.",tip:"FRIEND 結尾剛好看得到 END 這幾個字母，可幫你記拼字（只是記憶法，不是字根）；friend 源自古英語 frēond，是一個完整的字",emoji:"🤝",roots:["friend"]},
      {word:"father",definition:"a man who is your parent, your dad",chinese:"父親",sentence:"My <strong>father</strong> works hard.",tip:"用聯想記：FATHER 裡剛好藏著 FAT、HER 這些字母（只是記憶法，不是字根）；father 比 dad 正式",emoji:"👨",roots:["father"]},
      {word:"mother",definition:"a woman who is your parent, your mom",chinese:"母親",sentence:"My <strong>mother</strong> loves me.",tip:"用聯想記：MOTHER 結尾剛好藏著 HER 這些字母（只是記憶法，不是字根）；mother 比 mom 正式",emoji:"👩",roots:["mother"]},
      {word:"brother",definition:"a boy who has the same parents as you",chinese:"兄弟",sentence:"My <strong>brother</strong> is older than me.",tip:"用聯想記：BROTHER 開頭剛好是 BRO（兄弟的暱稱）；只是幫助記拼字，不是字根",emoji:"👦",roots:["brother"]},
      {word:"sister",definition:"a girl who has the same parents as you",chinese:"姊妹",sentence:"My <strong>sister</strong> helps me study.",tip:"用聯想記：SISTER 開頭剛好是 SIS（姊妹的暱稱）；只是幫助記拼字，不是字根",emoji:"👧",roots:["sister"]},
      {word:"grandpa",definition:"your father's dad or your mother's dad",chinese:"爺爺/外公",sentence:"My <strong>grandpa</strong> tells me stories.",tip:"GRANDPA = GRAND + PA",emoji:"👴",roots:["grandpa"]},
      {word:"grandma",definition:"your father's mom or your mother's mom",chinese:"奶奶/外婆",sentence:"My <strong>grandma</strong> makes cookies.",tip:"GRANDMA = GRAND + MA",emoji:"👵",roots:["grandma"]},
      {word:"banana",definition:"a long yellow fruit that is soft and sweet",chinese:"香蕉",sentence:"The monkey eats a <strong>banana</strong>.",tip:"BANANA 有三個 A！它是一個完整的字，不能拆成有意義的字根",emoji:"🍌",roots:["banana"]},
      {word:"milk",definition:"a white drink that comes from cows",chinese:"牛奶",sentence:"I drink <strong>milk</strong> every morning.",tip:"MILK 想到白色的液體",emoji:"🥛",roots:["milk"]},
      {word:"rice",definition:"small white grains we cook and eat, often with meals",chinese:"米飯",sentence:"We eat <strong>rice</strong> for lunch.",tip:"RICE 和 NICE 押韻",emoji:"🍚",roots:["rice"]},
      {word:"tea",definition:"a warm brown drink made from leaves soaked in hot water",chinese:"茶",sentence:"Mom drinks hot <strong>tea</strong>.",tip:"TEA 只有三個字母",emoji:"🍵",roots:["tea"]},
      {word:"water",definition:"the clear liquid we drink and that fills rivers, lakes, and seas",chinese:"水",sentence:"Please drink more <strong>water</strong>.",tip:"WATER 想到河流、海洋裡的水；它是一個完整的字，不能拆成 WAT＋ER 這種有意義的字根",emoji:"💧",roots:["water"]},
      {word:"cook",definition:"to make food ready to eat by heating it",chinese:"煮/廚師",sentence:"Dad can <strong>cook</strong> very well.",tip:"COOK 有兩個 O；當名詞時是「廚師」",emoji:"👨‍🍳",roots:["cook"]},
      {word:"orange",definition:"a round juicy fruit with a thick orange skin",chinese:"橘子/橘色",sentence:"I like <strong>orange</strong> juice.",tip:"ORANGE 又是水果又是顏色",emoji:"🍊",roots:["orange"]},
      {word:"juice",definition:"the sweet liquid squeezed out of fruit",chinese:"果汁",sentence:"I want apple <strong>juice</strong>.",tip:"JUICE 的 UI 發 /u:/ 的音",emoji:"🧃",roots:["juice"]},
      {word:"hamburger",definition:"a cooked beef patty inside a round bun",chinese:"漢堡",sentence:"I eat a <strong>hamburger</strong> for lunch.",tip:"HAMBURGER 其實源自德國城市漢堡（Hamburg），跟火腿（ham）沒關係！拼字時可拆成 HAM + BURGER 幫忙記",emoji:"🍔",roots:["hamburger"]},
      {word:"ice cream",definition:"a sweet, cold, creamy treat that is frozen",chinese:"冰淇淋",sentence:"I love chocolate <strong>ice cream</strong>.",tip:"ICE CREAM = ICE（冰）+ CREAM（奶油），是兩個真的字組成的複合詞",emoji:"🍦",roots:["ice cream"]},
      {word:"pizza",definition:"a flat round bread baked with cheese and toppings",chinese:"披薩",sentence:"We order <strong>pizza</strong> on Friday.",tip:"PIZZA 有兩個 Z！它源自義大利文，是一個完整的字，不能拆成有意義的字根",emoji:"🍕",roots:["pizza"]},
      {word:"black",definition:"the darkest color, like the night sky",chinese:"黑色",sentence:"My shoes are <strong>black</strong>.",tip:"BLACK 和 BACK 只差一個 L",emoji:"⚫",roots:["black"]},
      {word:"white",definition:"the color of milk and fresh snow",chinese:"白色",sentence:"Snow is <strong>white</strong>.",tip:"WHITE 的 WH 發 /w/ 的音",emoji:"⚪",roots:["white"]},
      {word:"desk",definition:"a table where you read, write, or do work",chinese:"書桌",sentence:"Put your book on the <strong>desk</strong>.",tip:"DESK 和 DISK 很像",emoji:"📝",roots:["desk"]},
      {word:"door",definition:"the flat piece you open to go in or out of a room",chinese:"門",sentence:"Please close the <strong>door</strong>.",tip:"DOOR 有兩個 O",emoji:"🚪",roots:["door"]},
      {word:"marker",definition:"a colored pen with a soft tip for drawing",chinese:"麥克筆",sentence:"I draw with a <strong>marker</strong>.",tip:"MARKER = MARK（做記號）+ -ER（名詞字尾，表「做…的工具或人」）→ 用來做記號的筆",emoji:"🖊️",roots:["mark","er"]},
      {word:"pen",definition:"a thin tool you write with using ink",chinese:"筆",sentence:"Write with a <strong>pen</strong>, please.",tip:"PEN 只有三個字母",emoji:"🖊️",roots:["pen"]},
      {word:"table",definition:"a flat top on legs where you eat or work",chinese:"桌子",sentence:"We eat at the <strong>table</strong>.",tip:"TABLE 和 ABLE 押韻；它源自拉丁文 tabula，是一個完整的字，不能拆成有意義的字根",emoji:"🍽️",roots:["table"]},
      {word:"chair",definition:"a seat with a back for one person",chinese:"椅子",sentence:"Sit on the <strong>chair</strong>.",tip:"CHAIR 裡有 AIR（空氣）",emoji:"💺",roots:["chair"]},
      {word:"eraser",definition:"a soft piece of rubber that rubs out pencil marks",chinese:"橡皮擦",sentence:"I need an <strong>eraser</strong> for my mistake.",tip:"ERASER = ERAS（來自 ERASE 擦掉，拼寫時去掉字尾 e）+ -ER（名詞字尾，表工具）→ 用來擦掉字跡的工具",emoji:"🧽",roots:["eras","er"]},
      {word:"ruler",definition:"a flat straight stick used to measure and draw lines",chinese:"尺",sentence:"Use a <strong>ruler</strong> to draw a line.",tip:"RULER = RUL（來自 RULE 畫直線，也有統治之意）+ -ER（名詞字尾，表人或工具）→ 畫直線的工具「尺」，也指統治者",emoji:"📏",roots:["ruler"]},
      {word:"window",definition:"a glass opening in a wall that lets in light and air",chinese:"窗戶",sentence:"Open the <strong>window</strong>, please.",tip:"WINDOW 源自古北歐語 vindauga『風之眼』：WIND（風）+ auga（眼睛、開口），所以窗戶能透風又採光！現代英語裡它已是一個完整的字",emoji:"🪟",roots:["window"]},
      {word:"bear",definition:"a big furry animal that lives in the forest",chinese:"熊",sentence:"The <strong>bear</strong> lives in the forest.",tip:"BEAR 和 PEAR（梨子）押韻",emoji:"🐻",roots:["bear"]},
      {word:"monkey",definition:"a furry animal with a long tail that climbs trees",chinese:"猴子",sentence:"The <strong>monkey</strong> climbs the tree.",tip:"MONKEY 結尾剛好看得到 KEY 這幾個字母，可幫你記拼字（只是記憶法，不是字根）；它本身是一個完整的字",emoji:"🐒",roots:["monkey"]},
      {word:"lion",definition:"a big wild cat with a furry mane, the king of animals",chinese:"獅子",sentence:"The <strong>lion</strong> is the king of animals.",tip:"LION 聽起來像「賴恩」；它源自拉丁文 leo，是一個完整的字，不能拆成有意義的字根",emoji:"🦁",roots:["lion"]},
      {word:"rabbit",definition:"a small furry animal with long ears that hops",chinese:"兔子",sentence:"The <strong>rabbit</strong> eats carrots.",tip:"RABBIT 有兩個 B；它是一個完整的字，不能拆成有意義的字根",emoji:"🐰",roots:["rabbit"]},
      {word:"tiger",definition:"a big wild cat with orange fur and black stripes",chinese:"老虎",sentence:"The <strong>tiger</strong> has orange stripes.",tip:"TIGER 源自希臘文 tigris，是一個完整的字，不能拆成有意義的字根；可聯想高爾夫球手 Tiger Woods 幫忙記",emoji:"🐯",roots:["tiger"]},
      {word:"home",definition:"the place where you live with your family",chinese:"家",sentence:"I go <strong>home</strong> after school.",tip:"HOME 和 COME 都有 OME",emoji:"🏠",roots:["home"]},
      {word:"park",definition:"a grassy place outside where you play and have fun",chinese:"公園",sentence:"We play in the <strong>park</strong>.",tip:"PARK 也有停車的意思",emoji:"🏞️",roots:["park"]},
      {word:"school",definition:"a place where children go to learn",chinese:"學校",sentence:"I go to <strong>school</strong> by bus.",tip:"SCHOOL 的 SCH 發 /sk/ 的音",emoji:"🏫",roots:["school"]},
      {word:"bookstore",definition:"a store where you buy books",chinese:"書店",sentence:"I buy books at the <strong>bookstore</strong>.",tip:"BOOKSTORE = BOOK（書）+ STORE（商店）→ 賣書的店",emoji:"📚",roots:["book","store"]},
      {word:"fan",definition:"a machine that blows air to cool you down",chinese:"風扇/粉絲",sentence:"Turn on the <strong>fan</strong>. It is hot.",tip:"FAN 也有粉絲的意思",emoji:"🪭",roots:["fan"]},
      {word:"key",definition:"a small metal piece that you use to open or lock a door",chinese:"鑰匙",sentence:"I lost my <strong>key</strong>.",tip:"KEY 和 FREE 押韻",emoji:"🔑",roots:["key"]},
      {word:"head",definition:"the top part of your body, where your face is",chinese:"頭",sentence:"I wear a hat on my <strong>head</strong>.",tip:"HEAD 裡的 EA 發短音 /e/",emoji:"🗣️",roots:["head"]},
      {word:"eye",definition:"the part of your face you see with",chinese:"眼睛",sentence:"She has big <strong>eye</strong>s.",tip:"EYE 正著反著都一樣",emoji:"👁️",roots:["eye"]},
      {word:"nose",definition:"the part of your face you use to smell and breathe",chinese:"鼻子",sentence:"My <strong>nose</strong> is cold.",tip:"NOSE 和 ROSE 押韻",emoji:"👃",roots:["nose"]},
      {word:"hand",definition:"the body part at the end of your arm, with fingers",chinese:"手",sentence:"Raise your <strong>hand</strong>, please.",tip:"HAND 和 SAND 押韻",emoji:"✋",roots:["hand"]},
      {word:"arm",definition:"the long body part from your shoulder to your hand",chinese:"手臂",sentence:"I hurt my <strong>arm</strong>.",tip:"ARM 和 FARM 押韻",emoji:"💪",roots:["arm"]},
      {word:"leg",definition:"the long body part you use to stand and walk",chinese:"腿",sentence:"My <strong>leg</strong> is tired from running.",tip:"LEG 和 EGG 押韻",emoji:"🦵",roots:["leg"]},
      {word:"foot",definition:"the body part at the bottom of your leg that you stand on",chinese:"腳",sentence:"I step on the ball with my <strong>foot</strong>.",tip:"FOOT 的複數是 FEET（不規則）",emoji:"🦶",roots:["foot"]},
      {word:"face",definition:"the front of your head, with your eyes, nose, and mouth",chinese:"臉",sentence:"Wash your <strong>face</strong> every morning.",tip:"FACE 和 PLACE 押韻",emoji:"😊",roots:["face"]},
      {word:"mouth",definition:"the part of your face you use to eat and talk",chinese:"嘴巴",sentence:"Open your <strong>mouth</strong> wide.",tip:"MOUTH 裡有 OUT",emoji:"👄",roots:["mouth"]},
      {word:"one",definition:"the number 1, the very first number",chinese:"一",sentence:"I have <strong>one</strong> sister.",tip:"ONE 的發音很特別 /wʌn/",emoji:"1️⃣",roots:["one"]},
      {word:"two",definition:"the number 2, one more than one",chinese:"二",sentence:"I have <strong>two</strong> eyes.",tip:"TWO 的 W 不發音",emoji:"2️⃣",roots:["two"]},
      {word:"three",definition:"the number 3, one more than two",chinese:"三",sentence:"There are <strong>three</strong> cats.",tip:"THREE 的 TH 要咬舌頭",emoji:"3️⃣",roots:["three"]},
      {word:"four",definition:"the number 4, one more than three",chinese:"四",sentence:"A table has <strong>four</strong> legs.",tip:"FOUR 和 DOOR 押韻",emoji:"4️⃣",roots:["four"]},
      {word:"five",definition:"the number 5, one more than four",chinese:"五",sentence:"I have <strong>five</strong> fingers on one hand.",tip:"FIVE 和 DIVE 押韻",emoji:"5️⃣",roots:["five"]},
      {word:"six",definition:"the number 6, one more than five",chinese:"六",sentence:"There are <strong>six</strong> eggs in the box.",tip:"SIX 和 MIX 押韻",emoji:"6️⃣",roots:["six"]},
      {word:"seven",definition:"the number 7, one more than six",chinese:"七",sentence:"There are <strong>seven</strong> days in a week.",tip:"SEVEN 是一個完整的字，不能拆成有意義的字根；記中間是 V：s-e-v-e-n",emoji:"7️⃣",roots:["seven"]},
      {word:"eight",definition:"the number 8, one more than seven",chinese:"八",sentence:"I go to bed at <strong>eight</strong>.",tip:"EIGHT 有很多不發音的字母",emoji:"8️⃣",roots:["eight"]},
      {word:"nine",definition:"the number 9, one more than eight",chinese:"九",sentence:"My cat has <strong>nine</strong> lives.",tip:"NINE 和 FINE 押韻",emoji:"9️⃣",roots:["nine"]},
      {word:"ten",definition:"the number 10, one more than nine",chinese:"十",sentence:"I can count to <strong>ten</strong>.",tip:"TEN 和 PEN 押韻",emoji:"🔟",roots:["ten"]},
      {word:"eleven",definition:"the number 11, one more than ten",chinese:"十一",sentence:"There are <strong>eleven</strong> players on a soccer team.",tip:"ELEVEN 有三個 E；它是一個完整的字，不能拆成有意義的字根",emoji:"⚽",roots:["eleven"]},
      {word:"twelve",definition:"the number 12, one more than eleven",chinese:"十二",sentence:"There are <strong>twelve</strong> months in a year.",tip:"TWELVE 和 SHELF 有點像",emoji:"📆",roots:["twelve"]},
      {word:"old",definition:"having lived for many years; not young anymore",chinese:"老的/舊的",sentence:"My grandpa is very <strong>old</strong>.",tip:"OLD 和 GOLD 押韻",emoji:"👴",roots:["old"]},
      {word:"short",definition:"not tall; low from head to foot; also not long from end to end",chinese:"矮的/短的",sentence:"The pencil is very <strong>short</strong>.",tip:"SHORT 裡有 ORT",emoji:"📏",roots:["short"]},
      {word:"tall",definition:"very high from the ground to the top",chinese:"高的",sentence:"The tree is very <strong>tall</strong>.",tip:"TALL 有兩個 L",emoji:"🌲",roots:["tall"]},
      {word:"thin",definition:"not fat; very slim and skinny",chinese:"瘦的",sentence:"The cat is very <strong>thin</strong>.",tip:"THIN 的 TH 要咬舌頭",emoji:"🧍",roots:["thin"]},
      {word:"cold",definition:"not warm at all; having a very low temperature",chinese:"冷的",sentence:"It is very <strong>cold</strong> in winter.",tip:"COLD 和 OLD 押韻",emoji:"🥶",roots:["cold"]},
      {word:"cool",definition:"a little cold, but not too cold",chinese:"涼爽的/酷",sentence:"The weather is <strong>cool</strong> today.",tip:"COOL 有兩個 O，也有「酷」的意思",emoji:"😎",roots:["cool"]},
      {word:"hat",definition:"something you wear on top of your head",chinese:"帽子",sentence:"I wear a <strong>hat</strong> in summer.",tip:"HAT 和 CAT 押韻",emoji:"🎩",roots:["hat"]},
      {word:"warm",definition:"a little hot in a nice way; not cold",chinese:"溫暖的",sentence:"Spring is <strong>warm</strong>.",tip:"WARM 裡剛好藏著 ARM 這幾個字母，可幫你記拼字（只是記憶法，不是字根）",emoji:"🌤️",roots:["warm"]},
      {word:"cloudy",definition:"when the sky is full of gray clouds",chinese:"多雲的",sentence:"It is <strong>cloudy</strong> today.",tip:"CLOUDY = CLOUD（雲）+ -Y（形容詞字尾，表示「多…的」），所以是「多雲的」",emoji:"☁️",roots:["cloud","y"]},
      {word:"rainy",definition:"when lots of rain falls from the sky",chinese:"下雨的",sentence:"It is <strong>rainy</strong> today. Bring an umbrella.",tip:"RAINY = RAIN（雨）+ -Y（形容詞字尾，表示「多…的」），所以是「多雨的、下雨的」",emoji:"🌧️",roots:["rain","y"]},
      {word:"sunny",definition:"when the sun shines bright in the sky",chinese:"晴朗的",sentence:"It is <strong>sunny</strong> today. Let's go outside.",tip:"SUNNY = SUN（太陽）+ 字尾 -y；加 -y 前要把 N 雙寫，所以有兩個 N",emoji:"☀️",roots:["sunny"]},
      {word:"windy",definition:"when lots of air blows hard outside",chinese:"有風的",sentence:"It is <strong>windy</strong>. Hold your hat!",tip:"WINDY = WIND（風）+ -Y（形容詞字尾，表示「多…的」），所以是「多風的、有風的」",emoji:"💨",roots:["wind","y"]},
      {word:"Sunday",definition:"a weekend day when many people rest",chinese:"星期日",sentence:"We rest on <strong>Sunday</strong>.",tip:"SUNDAY = SUN + DAY（太陽日）",emoji:"☀️",roots:["sun","day"]},
      {word:"Monday",definition:"the first weekday, when school starts again",chinese:"星期一",sentence:"School starts on <strong>Monday</strong>.",tip:"MONDAY = MON + DAY；MON 來自 MOON（月亮），拼寫時少了一個 O，所以是「月亮日」",emoji:"🌙",roots:["mon","day"]},
      {word:"Tuesday",definition:"the day of the week that comes after Monday",chinese:"星期二",sentence:"We have art on <strong>Tuesday</strong>.",tip:"TUESDAY = TUES + DAY（日）；TUE 讀作 /tju:/",emoji:"📅",roots:["Tuesday"]},
      {word:"Wednesday",definition:"the day in the middle of the school week",chinese:"星期三",sentence:"<strong>Wednesday</strong> is the middle of the week.",tip:"WEDNESDAY = WEDNES + DAY（日）；注意 D 不發音！",emoji:"📅",roots:["Wednesday"]},
      {word:"Thursday",definition:"the day of the week that comes after Wednesday",chinese:"星期四",sentence:"We have PE on <strong>Thursday</strong>.",tip:"THURSDAY = THURS + DAY",emoji:"📅",roots:["thurs","day"]},
      {word:"Friday",definition:"the last school day before the weekend",chinese:"星期五",sentence:"<strong>Friday</strong> is my favorite day!",tip:"FRIDAY 源自女神 Frigg 之日（古英語 Frīgedæg）；記 FRI + DAY，週五快到週末了！",emoji:"🎉",roots:["Friday"]},
      {word:"Saturday",definition:"a weekend day when many people play and rest",chinese:"星期六",sentence:"I play games on <strong>Saturday</strong>.",tip:"SATURDAY = SATUR + DAY",emoji:"🎮",roots:["Saturday"]},
      {word:"time",definition:"the hours and minutes a clock shows",chinese:"時間",sentence:"What <strong>time</strong> is it?",tip:"TIME 和 DIME 押韻",emoji:"⏰",roots:["time"]},
      {word:"day",definition:"a time of 24 hours, from one morning to the next",chinese:"天/日子",sentence:"Today is a beautiful <strong>day</strong>.",tip:"DAY 和 PLAY 押韻",emoji:"🌅",roots:["day"]},
      {word:"week",definition:"seven days in a row, like Sunday to Saturday",chinese:"週",sentence:"There are seven days in a <strong>week</strong>.",tip:"WEEK 有兩個 E",emoji:"📅",roots:["week"]},
      {word:"year",definition:"twelve months, or about 365 days",chinese:"年",sentence:"There are twelve months in a <strong>year</strong>.",tip:"YEAR 和 EAR（耳朵）押韻",emoji:"📆",roots:["year"]},
      {word:"now",definition:"at this very moment; the present time",chinese:"現在",sentence:"I am hungry <strong>now</strong>.",tip:"NOW 和 COW 押韻",emoji:"⏱️",roots:["now"]},
      {word:"today",definition:"this day, the one happening right now",chinese:"今天",sentence:"<strong>Today</strong> is Monday.",tip:"TODAY = TO + DAY",emoji:"📅",roots:["today"]},
      {word:"cry",definition:"to have tears fall from your eyes when sad",chinese:"哭",sentence:"Don't <strong>cry</strong>. It's okay.",tip:"CRY 和 FLY 押韻",emoji:"😢",roots:["cry"]},
      {word:"dance",definition:"to move your body to music",chinese:"跳舞",sentence:"I love to <strong>dance</strong>.",tip:"DANCE 和 CHANCE 押韻",emoji:"💃",roots:["dance"]},
      {word:"jump",definition:"to push off the ground up into the air",chinese:"跳",sentence:"The frog can <strong>jump</strong> high.",tip:"JUMP 和 BUMP 押韻",emoji:"🦘",roots:["jump"]},
      {word:"like",definition:"to enjoy something or think it is nice",chinese:"喜歡",sentence:"I <strong>like</strong> ice cream.",tip:"LIKE 和 BIKE 押韻",emoji:"❤️",roots:["like"]},
      {word:"read",definition:"to look at words and understand what they say",chinese:"閱讀",sentence:"I <strong>read</strong> a book before bed.",tip:"READ 現在式和過去式拼法一樣！",emoji:"📖",roots:["read"]},
      {word:"sing",definition:"to make music with your voice",chinese:"唱歌",sentence:"Birds <strong>sing</strong> in the morning.",tip:"SING 和 RING 押韻",emoji:"🎤",roots:["sing"]},
      {word:"draw",definition:"to make a picture using a pen or pencil",chinese:"畫畫",sentence:"I <strong>draw</strong> a picture of my family.",tip:"DRAW 過去式是 DREW",emoji:"🎨",roots:["draw"]},
      {word:"sleep",definition:"to close your eyes and rest, like you do at night",chinese:"睡覺",sentence:"I <strong>sleep</strong> at nine o'clock.",tip:"SLEEP 有兩個 E",emoji:"😴",roots:["sleep"]},
      {word:"swim",definition:"to move through the water using your arms and legs",chinese:"游泳",sentence:"I can <strong>swim</strong> in the pool.",tip:"SWIM 和 HIM 押韻",emoji:"🏊",roots:["swim"]},
      {word:"want",definition:"to wish you could have something",chinese:"想要",sentence:"I <strong>want</strong> a new toy.",tip:"WANT 的 A 發 /ɒ/ 的音",emoji:"🙏",roots:["want"]},
      {word:"write",definition:"to make letters or words with a pen or pencil",chinese:"寫",sentence:"I <strong>write</strong> my name on the paper.",tip:"WRITE 的 W 不發音",emoji:"✍️",roots:["write"]},
      {word:"kite",definition:"a light toy on a string that flies in the wind",chinese:"風箏",sentence:"I fly a <strong>kite</strong> in the park.",tip:"KITE 和 BITE 押韻",emoji:"🪁",roots:["kite"]},
      {word:"name",definition:"the word people call you by",chinese:"名字",sentence:"My <strong>name</strong> is Tom.",tip:"NAME 和 GAME 押韻",emoji:"📛",roots:["name"]},
      {word:"o'clock",definition:"used to tell the hour, like on a clock",chinese:"...點鐘",sentence:"It is three <strong>o'clock</strong>.",tip:"O'CLOCK = OF THE CLOCK 的縮寫",emoji:"🕐",roots:["o'clock"]},
      {word:"weather",definition:"how hot, cold, sunny, or rainy it is outside",chinese:"天氣",sentence:"The <strong>weather</strong> is nice today.",tip:"WEATHER 和 WHETHER 發音一樣；它源自古英語 weder，是一個完整的字，不能拆成有意義的字根",emoji:"🌤️",roots:["weather"]},
      {word:"big",definition:"very large in size, not small",chinese:"大的",sentence:"The elephant is very <strong>big</strong>.",tip:"BIG 和 PIG 押韻",emoji:"🐘",roots:["big"]},
      {word:"small",definition:"little in size, not big",chinese:"小的",sentence:"The ant is very <strong>small</strong>.",tip:"SMALL 有兩個 L",emoji:"🐜",roots:["small"]},
      {word:"long",definition:"measuring a lot from one end to the other",chinese:"長的",sentence:"The snake is very <strong>long</strong>.",tip:"LONG 和 SONG 押韻",emoji:"📏",roots:["long"]},
      {word:"many",definition:"a large number of things you can count",chinese:"很多（可數）",sentence:"There are <strong>many</strong> stars in the sky.",tip:"MANY 用在可以數的東西",emoji:"✨",roots:["many"]},
      {word:"much",definition:"a large amount of something",chinese:"很多（不可數）",sentence:"I don't have <strong>much</strong> time.",tip:"MUCH 用在不能數的東西",emoji:"📊",roots:["much"]}
    ]
};
