WORD_DATA["coca_l8"] = {
  name: "COCA L8",
  color: "#8b5cf6",
  words: [
    {word:"albeit",chinese:"雖然/儘管",sentence:"The plan worked, <strong>albeit</strong> slowly.",tip:"ALL+BE+IT=雖然全部都是它=儘管如此",emoji:"🤔",roots:["al","be","it"]},
    {word:"hitherto",chinese:"到目前為止",sentence:"<strong>Hitherto</strong> unknown species were discovered.",tip:"HITHER(到這裡)+TO=到這裡為止=至今",emoji:"⏳",roots:["hither","to"]},
    {word:"notwithstanding",chinese:"儘管/雖然",sentence:"<strong>Notwithstanding</strong> the risks, she proceeded.",tip:"NOT+WITH+STANDING=不管站在那裡的障礙=儘管",emoji:"💪",roots:["not","with","standing"]},
    {word:"whereby",chinese:"藉此/由此",sentence:"A system <strong>whereby</strong> students can apply online.",tip:"WHERE(哪裡)+BY(通過)=通過哪個方式=藉此",emoji:"🔗",roots:["where","by"]},
    {word:"henceforth",chinese:"從今以後",sentence:"<strong>Henceforth</strong>, all meetings will be recorded.",tip:"HENCE(因此)+FORTH(向前)=從此向前=從今以後",emoji:"➡️",roots:["hence","forth"]},
    {word:"hegemony",chinese:"霸權/霸主地位",sentence:"The empire maintained its <strong>hegemony</strong> for centuries.",tip:"HEGE(領導)+MONY(統治)=領導者的統治=霸權",emoji:"👑",roots:["hege","mony"]},
    {word:"stratification",chinese:"分層/階層化",sentence:"Social <strong>stratification</strong> creates inequality.",tip:"STRAT(層)+IFIC+ATION=形成層次的過程=分層",emoji:"📊",roots:["strat","ific","ation"]},
    {word:"photosynthesis",chinese:"光合作用",sentence:"Plants use <strong>photosynthesis</strong> to make food.",tip:"PHOTO(光)+SYNTHESIS(合成)=用光合成食物",emoji:"🌿",roots:["photo","syn","thesis"]},
    {word:"erosion",chinese:"侵蝕/腐蝕",sentence:"Soil <strong>erosion</strong> threatens farmland.",tip:"E(出)+ROS(咬)+ION=被咬出去的=侵蝕",emoji:"🏜️",roots:["e","ros","ion"]},
    {word:"allegory",chinese:"寓言/比喻",sentence:"The novel is an <strong>allegory</strong> for political corruption.",tip:"ALLE(其他)+GORY(說)=說的是另一個意思=寓言",emoji:"📖",roots:["alle","gory"]},
    {word:"metaphor",chinese:"隱喻/比喻",sentence:"Life is a journey is a common <strong>metaphor</strong>.",tip:"META(超越)+PHOR(搬運)=搬到另一個意義=隱喻",emoji:"🌉",roots:["meta","phor"]},
    {word:"juxtaposition",chinese:"並置/對照",sentence:"The <strong>juxtaposition</strong> of old and new creates contrast.",tip:"JUXTA(旁邊)+POSITION(位置)=放在旁邊的位置=並置",emoji:"↔️",roots:["juxta","posit","ion"]},
    {word:"abscond",chinese:"潛逃/逃跑",sentence:"The thief <strong>abscond</strong>ed with the jewels.",tip:"AB(離開)+SCOND(隱藏)=隱藏著離開=潛逃",emoji:"🏃",roots:["ab","scond"]},
    {word:"abrogate",chinese:"廢除/取消",sentence:"The new law <strong>abrogate</strong>d the old regulation.",tip:"AB(離開)+ROG(要求)+ATE=不再要求=廢除",emoji:"❌",roots:["ab","rog","ate"]},
    {word:"abstemious",chinese:"有節制的/節約的",sentence:"He leads an <strong>abstemious</strong> lifestyle.",tip:"ABS(離開)+TEM(酒)+IOUS=離開酒的=有節制的",emoji:"🧘",roots:["abs","tem","ious"]},
    {word:"acrimonious",chinese:"尖刻的/充滿敵意的",sentence:"The divorce was <strong>acrimonious</strong>.",tip:"ACRI(尖銳)+MON(警告)+IOUS=尖銳地警告=尖刻的",emoji:"😠",roots:["acri","mon","ious"]},
    {word:"adulterate",chinese:"摻假/使不純",sentence:"The milk was <strong>adulterate</strong>d with water.",tip:"ADULT(成熟/改變)+ERATE=使改變品質=摻假",emoji:"🥛",roots:["ad","ulter","ate"]},
    {word:"aggrandize",chinese:"擴大/美化",sentence:"He tried to <strong>aggrandize</strong> his own importance.",tip:"AG(向)+GRAND(大)+IZE=使變大=擴大/美化",emoji:"📈",roots:["ag","grand","ize"]},
    {word:"anachronism",chinese:"時代錯誤",sentence:"A knight in modern times would be an <strong>anachronism</strong>.",tip:"ANA(反)+CHRON(時間)+ISM=反時間的=時代錯誤",emoji:"⏰",roots:["ana","chron","ism"]},
    {word:"anathema",chinese:"詛咒/令人厭惡之事",sentence:"Violence is <strong>anathema</strong> to her beliefs.",tip:"ANA(向上)+THEMA(放置)=被放上去詛咒的東西",emoji:"🚫",roots:["ana","thema"]},
    {word:"antipathy",chinese:"反感/厭惡",sentence:"She felt deep <strong>antipathy</strong> toward injustice.",tip:"ANTI(反對)+PATH(感覺)+Y=相反的感覺=反感",emoji:"😒",roots:["anti","path","y"]},
    {word:"apotheosis",chinese:"神化/典範",sentence:"The work represents the <strong>apotheosis</strong> of his career.",tip:"APO(離開)+THEO(神)+SIS=變成神=神化/巔峰",emoji:"⭐",roots:["apo","theo","sis"]},
    {word:"approbation",chinese:"認可/讚許",sentence:"The plan received official <strong>approbation</strong>.",tip:"AP(向)+PROB(好)+ATION=向著好的方向=認可",emoji:"👍",roots:["ap","prob","ation"]},
    {word:"archaic",chinese:"古老的/過時的",sentence:"The law is <strong>archaic</strong> and needs updating.",tip:"ARCHA(古老)+IC=來自古老時代的=過時的",emoji:"🏛️",roots:["arch","aic"]},
    {word:"ascetic",chinese:"苦行的/禁慾的",sentence:"The monk lived an <strong>ascetic</strong> life.",tip:"A+SCET(修煉)+IC=修煉自己的=苦行的",emoji:"🧘",roots:["a","scet","ic"]},
    {word:"assuage",chinese:"緩和/減輕",sentence:"Nothing could <strong>assuage</strong> her grief.",tip:"AS(向)+SUAGE(甜)=使變甜=緩和痛苦",emoji:"🍯",roots:["as","suage"]},
    {word:"atavism",chinese:"返祖現象/隔代遺傳",sentence:"The trait is an example of <strong>atavism</strong>.",tip:"ATAV(祖先)+ISM=回到祖先的=返祖現象",emoji:"🧬",roots:["atav","ism"]},
    {word:"attenuate",chinese:"減弱/使稀薄",sentence:"The drug <strong>attenuate</strong>s the virus.",tip:"AT(向)+TENU(薄)+ATE=使變薄=減弱",emoji:"📉",roots:["at","tenu","ate"]},
    {word:"avarice",chinese:"貪婪/貪財",sentence:"His <strong>avarice</strong> knew no bounds.",tip:"AVAR(渴望)+ICE=過度渴望=貪婪",emoji:"💰",roots:["avar","ice"]},
    {word:"beleaguer",chinese:"圍攻/困擾",sentence:"The <strong>beleaguer</strong>ed company struggled to survive.",tip:"BE(完全)+LEAGUER(圍營)=完全圍住=困擾",emoji:"🏰",roots:["be","leaguer"]},
    {word:"bellicose",chinese:"好戰的/好鬥的",sentence:"The <strong>bellicose</strong> leader threatened war.",tip:"BELL(戰爭)+ICOSE=像要打仗的=好戰的",emoji:"⚔️",roots:["bell","icose"]},
    {word:"bifurcate",chinese:"分叉/分成兩支",sentence:"The road <strong>bifurcate</strong>s at the bridge.",tip:"BI(兩)+FURC(叉)+ATE=分成兩叉=分叉",emoji:"🔀",roots:["bi","furc","ate"]},
    {word:"calumny",chinese:"誹謗/中傷",sentence:"He was a victim of <strong>calumny</strong>.",tip:"CALUMN(欺騙)+Y=用欺騙傷害人=誹謗",emoji:"😤",roots:["calumn","y"]},
    {word:"capacious",chinese:"寬敞的/容量大的",sentence:"She carried a <strong>capacious</strong> bag.",tip:"CAPAC(容量)+IOUS=容量大的=寬敞的",emoji:"👜",roots:["capac","ious"]},
    {word:"capitulation",chinese:"投降/屈服",sentence:"The <strong>capitulation</strong> ended the siege.",tip:"CAPIT(頭)+UL+ATION=低頭的動作=投降",emoji:"🏳️",roots:["capit","ul","ation"]},
    {word:"cavernous",chinese:"洞穴般的/巨大空曠的",sentence:"The <strong>cavernous</strong> warehouse echoed with footsteps.",tip:"CAVERN(洞穴)+OUS=像洞穴一樣的=巨大空曠",emoji:"🕳️",roots:["cavern","ous"]},
    {word:"chicanery",chinese:"詭計/欺騙手段",sentence:"Political <strong>chicanery</strong> undermines democracy.",tip:"CHICAN(詭計)+ERY=使用詭計=欺騙手段",emoji:"🎭",roots:["chican","ery"]},
    {word:"circumlocution",chinese:"迂迴說法/繞圈子",sentence:"Avoid <strong>circumlocution</strong> and speak directly.",tip:"CIRCUM(繞圈)+LOCUT(說)+ION=繞著圈說=迂迴",emoji:"🔄",roots:["circum","locut","ion"]},
    {word:"clemency",chinese:"寬恕/仁慈",sentence:"The prisoner begged for <strong>clemency</strong>.",tip:"CLEM(溫和)+ENCY=溫和的態度=寬恕",emoji:"🕊️",roots:["clem","ency"]},
    {word:"coalesce",chinese:"合併/聯合",sentence:"Small groups <strong>coalesce</strong>d into a movement.",tip:"CO(一起)+ALESCE(生長)=一起生長=合併",emoji:"🤝",roots:["co","alesce"]},
    {word:"cognoscenti",chinese:"內行/鑑賞家",sentence:"The wine is popular among <strong>cognoscenti</strong>.",tip:"COGN(知道)+OSCENTI=知道的人們=內行",emoji:"🍷",roots:["cogn","oscenti"]},
    {word:"colloquial",chinese:"口語的/通俗的",sentence:"The essay uses too many <strong>colloquial</strong> expressions.",tip:"COL(一起)+LOQ(說)+IAL=平常一起說的=口語的",emoji:"🗣️",roots:["col","loqu","ial"]},
    {word:"conflagration",chinese:"大火/衝突",sentence:"The <strong>conflagration</strong> destroyed the entire block.",tip:"CON(一起)+FLAGR(燃燒)+ATION=一起燃燒=大火",emoji:"🔥",roots:["con","flagr","ation"]},
    {word:"concomitant",chinese:"伴隨的/相伴的",sentence:"Stress and its <strong>concomitant</strong> health problems.",tip:"CON(一起)+COMIT(陪伴)+ANT=一起陪伴的=伴隨的",emoji:"🔗",roots:["con","comit","ant"]},
    {word:"confound",chinese:"使困惑/使混淆",sentence:"The results <strong>confound</strong>ed the researchers.",tip:"CON(一起)+FOUND(倒)=一起倒下=使困惑",emoji:"😵",roots:["con","found"]},
    {word:"connivance",chinese:"縱容/默許",sentence:"The fraud happened with the <strong>connivance</strong> of officials.",tip:"CON(一起)+NIV(眨眼)+ANCE=一起眨眼假裝沒看到=縱容",emoji:"🙈",roots:["con","niv","ance"]},
    {word:"consecrate",chinese:"奉獻/使神聖",sentence:"The church was <strong>consecrate</strong>d in 1850.",tip:"CON(完全)+SECR(神聖)+ATE=使完全神聖=奉獻",emoji:"⛪",roots:["con","secr","ate"]},
    {word:"contravene",chinese:"違反/抵觸",sentence:"This action <strong>contravene</strong>s the law.",tip:"CONTRA(反)+VENE(來)=反著來=違反",emoji:"🚫",roots:["contra","vene"]},
    {word:"contrition",chinese:"悔恨/懊悔",sentence:"He showed genuine <strong>contrition</strong> for his actions.",tip:"CON(完全)+TRIT(磨)+ION=完全磨碎心的=悔恨",emoji:"😔",roots:["con","trit","ion"]},
    {word:"convalescence",chinese:"康復期/恢復",sentence:"She spent weeks in <strong>convalescence</strong>.",tip:"CON(完全)+VAL(強壯)+ESCENCE=完全變強壯=康復",emoji:"🏥",roots:["con","val","escence"]},
    {word:"coruscate",chinese:"閃爍/光芒四射",sentence:"The diamonds <strong>coruscate</strong>d in the light.",tip:"CORUSC(閃爍)+ATE=發出閃光=閃爍",emoji:"✨",roots:["corusc","ate"]},
    {word:"countermand",chinese:"撤銷命令/取消",sentence:"The general <strong>countermand</strong>ed the order.",tip:"COUNTER(反)+MAND(命令)=反命令=撤銷",emoji:"🔄",roots:["counter","mand"]},
    {word:"crepuscular",chinese:"黃昏的/朦朧的",sentence:"Many animals are <strong>crepuscular</strong>, active at dusk.",tip:"CREPUSC(黃昏)+ULAR=黃昏時候的=朦朧的",emoji:"🌅",roots:["crepusc","ular"]},
    {word:"cupidity",chinese:"貪婪/貪心",sentence:"<strong>Cupidity</strong> drove him to embezzle funds.",tip:"CUP(渴望)+IDITY=過度渴望=貪婪",emoji:"💰",roots:["cup","id","ity"]},
    {word:"dearth",chinese:"缺乏/匱乏",sentence:"There is a <strong>dearth</strong> of qualified teachers.",tip:"DEARTH=DEAR(珍貴)+TH=因為缺少所以珍貴=缺乏",emoji:"📉",roots:["dear","th"]},
    {word:"decadence",chinese:"頹廢/墮落",sentence:"The empire fell into <strong>decadence</strong>.",tip:"DE(向下)+CAD(落)+ENCE=向下掉落=頹廢",emoji:"🍷",roots:["de","cad","ence"]},
    {word:"defalcation",chinese:"挪用公款/虧空",sentence:"The accountant was charged with <strong>defalcation</strong>.",tip:"DE(離開)+FALC(鐮刀)+ATION=用鐮刀割走=挪用公款",emoji:"💸",roots:["de","falc","ation"]},
    {word:"deleterious",chinese:"有害的/有毒的",sentence:"Pollution has <strong>deleterious</strong> effects on the environment.",tip:"DELETE(刪除)+RIOUS=像刪除生命力一樣=有害的",emoji:"☠️",roots:["delete","rious"]},
    {word:"demagogery",chinese:"煽動民心/蠱惑",sentence:"His speech was pure <strong>demagogery</strong>.",tip:"DEMO(人民)+AGOG(引導)+ERY=引導人民情緒=煽動",emoji:"📢",roots:["dem","agog","ery"]},
    {word:"denigrate",chinese:"詆毀/貶低",sentence:"She refuses to <strong>denigrate</strong> her competitors.",tip:"DE(向下)+NIGR(黑)+ATE=把人說黑=詆毀",emoji:"👎",roots:["de","nigr","ate"]},
    {word:"denouement",chinese:"結局/收場",sentence:"The <strong>denouement</strong> of the novel was unexpected.",tip:"DE(解開)+NOU(結)+EMENT=解開結=結局",emoji:"📖",roots:["de","noue","ment"]},
    {word:"depravity",chinese:"墮落/邪惡",sentence:"The war revealed human <strong>depravity</strong>.",tip:"DE(向下)+PRAV(歪)+ITY=歪到底=墮落",emoji:"😈",roots:["de","prav","ity"]},
    {word:"deprecate",chinese:"反對/貶低",sentence:"He <strong>deprecate</strong>d the use of violence.",tip:"DE(向下)+PREC(祈禱)+ATE=祈禱去除=反對",emoji:"👎",roots:["de","prec","ate"]},
    {word:"derelict",chinese:"被遺棄的/玩忽職守的",sentence:"The <strong>derelict</strong> building will be demolished.",tip:"DE(完全)+RE(回)+LICT(留)=被完全留下不管=遺棄的",emoji:"🏚️",roots:["de","re","lict"]},
    {word:"desultory",chinese:"漫無目的的/雜亂的",sentence:"They made <strong>desultory</strong> conversation.",tip:"DE(向下)+SULT(跳)+ORY=跳來跳去的=漫無目的",emoji:"🔀",roots:["de","sult","ory"]},
    {word:"diatribe",chinese:"猛烈抨擊",sentence:"She launched a <strong>diatribe</strong> against the policy.",tip:"DIA(穿過)+TRIBE=穿透對方的攻擊=猛烈抨擊",emoji:"🗡️",roots:["dia","tribe"]},
    {word:"didactic",chinese:"教誨的/說教式的",sentence:"The film is too <strong>didactic</strong> to be entertaining.",tip:"DIDACT(教)+IC=一直在教你的=說教式的",emoji:"👨‍🏫",roots:["didact","ic"]},
    {word:"diffident",chinese:"缺乏自信的/羞怯的",sentence:"The <strong>diffident</strong> speaker struggled with eye contact.",tip:"DIF(不)+FID(信任)+ENT=不信任自己的=缺乏自信",emoji:"😊",roots:["dif","fid","ent"]},
    {word:"dilatory",chinese:"拖延的/遲緩的",sentence:"His <strong>dilatory</strong> tactics frustrated everyone.",tip:"DILAT(推遲)+ORY=不斷推遲的=拖延的",emoji:"🐌",roots:["dilat","ory"]},
    {word:"diminution",chinese:"減少/縮小",sentence:"There has been no <strong>diminution</strong> in quality.",tip:"DI+MINUT(小)+ION=變小的過程=減少",emoji:"📉",roots:["di","minut","ion"]},
    {word:"disaffected",chinese:"不滿的/叛離的",sentence:"<strong>Disaffected</strong> workers went on strike.",tip:"DIS(不)+AFFECT(影響)+ED=不再被正面影響=不滿",emoji:"😤",roots:["dis","affect","ed"]},
    {word:"discomfit",chinese:"使困窘/使挫敗",sentence:"The question <strong>discomfit</strong>ed the speaker.",tip:"DIS(不)+COMFIT(舒適)=使不舒適=使困窘",emoji:"😰",roots:["dis","comfit"]},
    {word:"disingenuous",chinese:"不真誠的/虛偽的",sentence:"His apology seemed <strong>disingenuous</strong>.",tip:"DIS(不)+INGENU(天真)+OUS=不天真的=虛偽的",emoji:"🎭",roots:["dis","in","genu","ous"]},
    {word:"disparagement",chinese:"貶低/輕蔑",sentence:"The constant <strong>disparagement</strong> hurt morale.",tip:"DIS(不)+PAR(相等)+AGEMENT=說不相等=貶低",emoji:"👎",roots:["dis","par","age","ment"]},
    {word:"dissolution",chinese:"解散/瓦解",sentence:"The <strong>dissolution</strong> of the partnership was amicable.",tip:"DIS(分開)+SOLUT(鬆)+ION=鬆開分開=解散",emoji:"💔",roots:["dis","solut","ion"]},
    {word:"draconian",chinese:"嚴酷的/苛刻的",sentence:"The <strong>draconian</strong> measures provoked protests.",tip:"DRACO(古希臘嚴厲立法者)+NIAN=像德拉古一樣嚴厲",emoji:"⚖️",roots:["dracon","ian"]},
    {word:"edification",chinese:"啟迪/教化",sentence:"For your <strong>edification</strong>, here are the facts.",tip:"EDIFIC(建造)+ATION=建造知識的過程=啟迪",emoji:"📚",roots:["edific","ation"]},
    {word:"effete",chinese:"衰弱的/頹廢的",sentence:"The <strong>effete</strong> aristocracy lost touch with reality.",tip:"EF(出)+FETE(生育)=生不出來的=衰弱的",emoji:"😩",roots:["ef","fete"]},
    {word:"effrontery",chinese:"厚顏無恥/放肆",sentence:"He had the <strong>effrontery</strong> to demand a raise.",tip:"EF(出)+FRONT(臉面)+ERY=把臉伸出去=厚臉皮",emoji:"😤",roots:["ef","front","ery"]},
    {word:"egalitarian",chinese:"平等主義的",sentence:"The society promotes <strong>egalitarian</strong> values.",tip:"EGAL(平等)+ITARIAN=追求平等的=平等主義的",emoji:"⚖️",roots:["egal","itar","ian"]},
    {word:"eleemosynary",chinese:"慈善的/救濟的",sentence:"The foundation serves <strong>eleemosynary</strong> purposes.",tip:"ELEEM(慈悲)+OSYN+ARY=出於慈悲的=慈善的",emoji:"❤️",roots:["eleem","osyn","ary"]},
    {word:"emaciate",chinese:"使消瘦/使憔悴",sentence:"The disease <strong>emaciate</strong>d him rapidly.",tip:"E(出)+MACI(瘦)+ATE=使變瘦=使消瘦",emoji:"😫",roots:["e","maci","ate"]},
    {word:"encomium",chinese:"頌詞/讚美",sentence:"The professor received an <strong>encomium</strong> at retirement.",tip:"EN(在裡面)+COM(歌唱)+IUM=在裡面歌唱=頌詞",emoji:"🎵",roots:["en","com","ium"]},
    {word:"enervate",chinese:"使衰弱/使無力",sentence:"The heat <strong>enervate</strong>d the travelers.",tip:"E(出)+NERV(神經)+ATE=抽走神經力量=使衰弱",emoji:"😫",roots:["e","nerv","ate"]},
    {word:"ennui",chinese:"倦怠/厭煩",sentence:"She suffered from <strong>ennui</strong> during the long vacation.",tip:"EN(在裡面)+NUI(煩)=心裡面的煩=倦怠",emoji:"😑",roots:["en","nui"]},
    {word:"ephemeral",chinese:"短暫的/轉瞬即逝的",sentence:"Social media fame is often <strong>ephemeral</strong>.",tip:"EPI(在上)+HEMER(一天)+AL=只存在一天的=短暫",emoji:"🌸",roots:["epi","hemer","al"]},
    {word:"epistemic",chinese:"認識論的/知識的",sentence:"The paper explores <strong>epistemic</strong> uncertainty.",tip:"EPIST(知識)+EMIC=關於知識的=認識論的",emoji:"🧠",roots:["epist","emic"]},
    {word:"equanimity",chinese:"鎮定/沉著",sentence:"He accepted the news with <strong>equanimity</strong>.",tip:"EQU(平等)+ANIM(心)+ITY=心情平等=鎮定",emoji:"🧘",roots:["equ","anim","ity"]},
    {word:"equitable",chinese:"公平的/公正的",sentence:"We need a more <strong>equitable</strong> distribution of wealth.",tip:"EQUIT(公平)+ABLE=能做到公平的=公正的",emoji:"⚖️",roots:["equit","able"]},
    {word:"erudite",chinese:"博學的/有學問的",sentence:"The <strong>erudite</strong> professor published many papers.",tip:"E(出)+RUD(粗糙)+ITE=從粗糙中走出=有學問的",emoji:"📚",roots:["e","rud","ite"]},
    {word:"escarpment",chinese:"懸崖/陡坡",sentence:"The castle sits atop a steep <strong>escarpment</strong>.",tip:"ES(出)+CARP(陡壁)+MENT=陡峭的地形=懸崖",emoji:"🏔️",roots:["es","carp","ment"]},
    {word:"excoriate",chinese:"嚴厲批評/剝皮",sentence:"Critics <strong>excoriate</strong>d the new policy.",tip:"EX(出)+CORI(皮)+ATE=把皮剝掉=嚴厲批評",emoji:"😤",roots:["ex","cori","ate"]},
    {word:"execrable",chinese:"極壞的/可憎的",sentence:"The food was <strong>execrable</strong>.",tip:"EX(出)+SECR(詛咒)+ABLE=值得被詛咒的=極壞的",emoji:"🤮",roots:["ex","ecr","able"]},
    {word:"exegesis",chinese:"詮釋/解經",sentence:"Biblical <strong>exegesis</strong> requires deep knowledge.",tip:"EX(出)+EGE(引導)+SIS=引導出意義=詮釋",emoji:"📖",roots:["ex","ege","sis"]},
    {word:"exigent",chinese:"緊急的/急迫的",sentence:"<strong>Exigent</strong> circumstances demanded immediate action.",tip:"EX(出)+IG(做)+ENT=需要立刻做出的=緊急的",emoji:"🚨",roots:["ex","ig","ent"]},
    {word:"expatiate",chinese:"詳述/細說",sentence:"She <strong>expatiate</strong>d on the benefits of the plan.",tip:"EX(出)+PATI(走)+ATE=走出去展開說=詳述",emoji:"📝",roots:["ex","pati","ate"]},
    {word:"expiate",chinese:"贖罪/補償",sentence:"He tried to <strong>expiate</strong> his guilt through charity.",tip:"EX(出)+PI(虔誠)+ATE=通過虔誠走出罪=贖罪",emoji:"🙏",roots:["ex","pi","ate"]},
    {word:"expunge",chinese:"刪除/抹去",sentence:"The record was <strong>expunge</strong>d from the database.",tip:"EX(出)+PUNGE(刺)=用刺刮出去=刪除",emoji:"🗑️",roots:["ex","punge"]},
    {word:"extemporaneous",chinese:"即興的/無準備的",sentence:"She gave an <strong>extemporaneous</strong> speech.",tip:"EX(出)+TEMPOR(時間)+ANEOUS=超出時間準備的=即興",emoji:"🎤",roots:["ex","tempor","aneous"]},
    {word:"extirpate",chinese:"根除/消滅",sentence:"Efforts to <strong>extirpate</strong> the disease continue.",tip:"EX(出)+TIRP(根)+ATE=把根拔出來=根除",emoji:"🌿",roots:["ex","tirp","ate"]},
    {word:"facile",chinese:"輕率的/膚淺的",sentence:"His <strong>facile</strong> explanation ignored the complexity.",tip:"FACIL(容易)+E=太容易的=輕率的/膚淺的",emoji:"🤷",roots:["facil","e"]},
    {word:"fastidious",chinese:"挑剔的/一絲不苟的",sentence:"She is <strong>fastidious</strong> about cleanliness.",tip:"FASTID(厭惡)+IOUS=對不完美感到厭惡=挑剔的",emoji:"🔬",roots:["fastid","ious"]},
    {word:"fecund",chinese:"肥沃的/多產的",sentence:"The <strong>fecund</strong> soil produced abundant crops.",tip:"FEC(做/生)+UND=能生產很多的=肥沃的",emoji:"🌾",roots:["fec","und"]},
    {word:"felicitous",chinese:"恰當的/巧妙的",sentence:"That was a <strong>felicitous</strong> choice of words.",tip:"FELIC(幸福)+ITOUS=帶來幸福感的=恰當的",emoji:"✨",roots:["felic","it","ous"]},
    {word:"filibuster",chinese:"阻撓議事/拖延戰術",sentence:"The senator used a <strong>filibuster</strong> to block the vote.",tip:"像海盜(freebooter)一樣劫持議程=阻撓議事",emoji:"🏴‍☠️",roots:["fili","buster"]},
    {word:"filigree",chinese:"金銀絲細工/精巧裝飾",sentence:"The jewelry featured delicate <strong>filigree</strong> work.",tip:"FIL(線)+I+GREE(顆粒)=用細線和顆粒做的=精巧細工",emoji:"💍",roots:["fili","gree"]},
    {word:"flagellate",chinese:"鞭打/嚴厲批評",sentence:"He <strong>flagellate</strong>d himself for his mistakes.",tip:"FLAGELL(鞭子)+ATE=用鞭子打=嚴厲自責",emoji:"🔨",roots:["flagell","ate"]},
    {word:"flagrant",chinese:"公然的/明目張膽的",sentence:"It was a <strong>flagrant</strong> violation of the rules.",tip:"FLAGR(燃燒)+ANT=像燃燒一樣明顯的=公然的",emoji:"🔥",roots:["flagr","ant"]},
    {word:"forbearance",chinese:"克制/忍耐",sentence:"She showed great <strong>forbearance</strong> in the face of provocation.",tip:"FOR(前)+BEAR(承受)+ANCE=向前承受=忍耐",emoji:"🧘",roots:["for","bear","ance"]},
    {word:"foreboding",chinese:"預感/不祥預兆",sentence:"She had a sense of <strong>foreboding</strong> about the trip.",tip:"FORE(前面)+BODING(預兆)=提前的不好預兆",emoji:"⛈️",roots:["fore","boding"]},
    {word:"fulminate",chinese:"猛烈抨擊/爆發",sentence:"He <strong>fulminate</strong>d against the new regulations.",tip:"FULMIN(閃電)+ATE=像閃電一樣爆發=猛烈抨擊",emoji:"⚡",roots:["fulmin","ate"]},
    {word:"gainsay",chinese:"否認/反駁",sentence:"No one could <strong>gainsay</strong> her achievements.",tip:"GAIN(反對)+SAY(說)=說反對的話=否認",emoji:"🚫",roots:["gain","say"]},
    {word:"grandiloquent",chinese:"誇大的/浮誇的",sentence:"His <strong>grandiloquent</strong> speech impressed no one.",tip:"GRAND(大)+LOQU(說)+ENT=說大話的=浮誇的",emoji:"🎭",roots:["grand","i","loqu","ent"]},
    {word:"gratuitous",chinese:"無緣無故的/不必要的",sentence:"The movie contains <strong>gratuitous</strong> violence.",tip:"GRAT(恩惠/免費)+UIT+OUS=白白給的=不必要的",emoji:"🚫",roots:["grat","uit","ous"]},
    {word:"hagiography",chinese:"聖徒傳/溢美之詞",sentence:"The biography reads like <strong>hagiography</strong>.",tip:"HAGIO(聖人)+GRAPH(寫)+Y=寫聖人的=溢美之詞",emoji:"😇",roots:["hagio","graph","y"]},
    {word:"halcyon",chinese:"平靜的/黃金時代的",sentence:"She recalled the <strong>halcyon</strong> days of her youth.",tip:"HALCYON=翠鳥(傳說能使海平靜的鳥)=平靜的",emoji:"🕊️",roots:["halcy","on"]},
    {word:"harbinger",chinese:"先驅/預兆",sentence:"Robins are a <strong>harbinger</strong> of spring.",tip:"HARBOR(港口)+INGER=先到港口準備的人=先驅",emoji:"🌸",roots:["harb","inger"]},
    {word:"hermetic",chinese:"密封的/隱秘的",sentence:"The jar has a <strong>hermetic</strong> seal.",tip:"HERMET(赫爾墨斯/密封)+IC=像魔法密封的=密封的",emoji:"🔒",roots:["hermet","ic"]},
    {word:"histrionic",chinese:"戲劇性的/做作的",sentence:"Her <strong>histrionic</strong> reaction was unnecessary.",tip:"HISTRION(演員)+IC=像演員一樣的=做作的",emoji:"🎭",roots:["histrion","ic"]},
    {word:"hubris",chinese:"傲慢/自大",sentence:"His <strong>hubris</strong> led to his downfall.",tip:"HUBRIS=古希臘悲劇中的致命傲慢=自大",emoji:"👑",roots:["hubr","is"]},
    {word:"iconoclastic",chinese:"打破傳統的",sentence:"Her <strong>iconoclastic</strong> views challenged the establishment.",tip:"ICONO(偶像)+CLAST(打破)+IC=打破偶像的=反傳統",emoji:"🔨",roots:["icono","clast","ic"]},
    {word:"idolatry",chinese:"偶像崇拜/盲目崇拜",sentence:"Consumer <strong>idolatry</strong> drives overconsumption.",tip:"IDOL(偶像)+ATRY(崇拜)=崇拜偶像=盲目崇拜",emoji:"🙇",roots:["idol","atry"]},
    {word:"ignominy",chinese:"恥辱/不名譽",sentence:"He suffered the <strong>ignominy</strong> of public failure.",tip:"IG(不)+NOMIN(名字)+Y=沒有好名聲=恥辱",emoji:"😔",roots:["ig","nomin","y"]},
    {word:"immutable",chinese:"不可改變的",sentence:"The laws of physics are <strong>immutable</strong>.",tip:"IM(不)+MUT(改變)+ABLE=不能改變的",emoji:"🔒",roots:["im","mut","able"]},
    {word:"impecunious",chinese:"貧窮的/沒錢的",sentence:"The <strong>impecunious</strong> artist could barely afford rent.",tip:"IM(不)+PECUN(錢)+IOUS=沒有錢的=貧窮的",emoji:"💸",roots:["im","pecun","ious"]},
    {word:"implacable",chinese:"不能安撫的/無情的",sentence:"She faced an <strong>implacable</strong> enemy.",tip:"IM(不)+PLAC(平靜)+ABLE=不能平靜的=無情的",emoji:"😤",roots:["im","plac","able"]},
    {word:"imprecation",chinese:"詛咒/咒罵",sentence:"He hurled <strong>imprecation</strong>s at his rival.",tip:"IM(向)+PREC(祈禱)+ATION=向人祈禱壞事=詛咒",emoji:"🤬",roots:["im","prec","ation"]},
    {word:"impugn",chinese:"質疑/抨擊",sentence:"She <strong>impugn</strong>ed the integrity of the report.",tip:"IM(向)+PUGN(打)=向人打去=質疑/抨擊",emoji:"🥊",roots:["im","pugn"]},
    {word:"impunity",chinese:"免受懲罰",sentence:"He acted with <strong>impunity</strong>.",tip:"IM(不)+PUN(懲罰)+ITY=不受懲罰=免罰",emoji:"🛡️",roots:["im","pun","ity"]},
    {word:"inchoate",chinese:"剛開始的/未成形的",sentence:"The plan is still <strong>inchoate</strong>.",tip:"IN(進入)+CHO(開始)+ATE=剛開始進入=未成形的",emoji:"🌱",roots:["in","cho","ate"]},
    {word:"incipient",chinese:"初期的/剛萌芽的",sentence:"Doctors detected <strong>incipient</strong> signs of disease.",tip:"IN(進入)+CIP(拿/開始)+IENT=剛開始拿到=初期的",emoji:"🌱",roots:["in","cip","ient"]},
    {word:"incontrovertible",chinese:"無可爭辯的",sentence:"The evidence is <strong>incontrovertible</strong>.",tip:"IN(不)+CONTRO(反對)+VERT(轉)+IBLE=不能翻轉反對的",emoji:"✅",roots:["in","contro","vert","ible"]},
    {word:"incorrigible",chinese:"無可救藥的/積習難改的",sentence:"He is an <strong>incorrigible</strong> optimist.",tip:"IN(不)+CORRIG(改正)+IBLE=不能改正的",emoji:"🤷",roots:["in","corrig","ible"]},
    {word:"incredulity",chinese:"懷疑/不信",sentence:"She stared in <strong>incredulity</strong> at the news.",tip:"IN(不)+CRED(相信)+ILITY=不相信的狀態=懷疑",emoji:"😲",roots:["in","cred","ul","ity"]},
    {word:"inculcate",chinese:"灌輸/諄諄教導",sentence:"Parents <strong>inculcate</strong> values in their children.",tip:"IN(進入)+CULC(踩)+ATE=踩進去=灌輸",emoji:"📚",roots:["in","culc","ate"]},
    {word:"indemnify",chinese:"賠償/保障",sentence:"The insurance will <strong>indemnify</strong> you for losses.",tip:"IN(不)+DEMN(損害)+IFY=使不受損害=賠償保障",emoji:"🛡️",roots:["in","demn","ify"]},
    {word:"indigent",chinese:"貧困的/赤貧的",sentence:"The charity helps <strong>indigent</strong> families.",tip:"IN(不)+DIG(需要)+ENT=有需要卻得不到=貧困的",emoji:"🏚️",roots:["in","dig","ent"]},
    {word:"ineffable",chinese:"不可言喻的/妙不可言的",sentence:"The beauty of the sunset was <strong>ineffable</strong>.",tip:"IN(不)+EF(出)+FABLE(說)=說不出來的=不可言喻",emoji:"🌅",roots:["in","ef","fable"]},
    {word:"infelicitous",chinese:"不恰當的/不幸的",sentence:"His <strong>infelicitous</strong> choice of words offended many.",tip:"IN(不)+FELIC(幸福)+ITOUS=不帶來幸福的=不恰當",emoji:"😬",roots:["in","felic","itous"]},
    {word:"insouciant",chinese:"漫不經心的/無憂無慮的",sentence:"She walked in with an <strong>insouciant</strong> air.",tip:"IN(不)+SOUCI(擔心)+ANT=不擔心的=無憂無慮",emoji:"😎",roots:["in","souci","ant"]},
    {word:"intemperance",chinese:"無節制/過度",sentence:"His <strong>intemperance</strong> in drinking ruined his career.",tip:"IN(不)+TEMPER(節制)+ANCE=不節制=過度",emoji:"🍺",roots:["in","temper","ance"]},
    {word:"intransigent",chinese:"不妥協的/固執的",sentence:"The <strong>intransigent</strong> negotiator refused all offers.",tip:"IN(不)+TRANS(越過)+IG(做)+ENT=不越過底線的=不妥協",emoji:"🗿",roots:["in","trans","ig","ent"]},
    {word:"invective",chinese:"謾罵/痛罵",sentence:"He hurled <strong>invective</strong> at his opponents.",tip:"IN(向)+VECT(攻擊)+IVE=向人攻擊的話=謾罵",emoji:"🤬",roots:["in","vect","ive"]},
    {word:"inveterate",chinese:"根深蒂固的/積習的",sentence:"He is an <strong>inveterate</strong> liar.",tip:"IN(在裡面)+VETER(老)+ATE=在裡面老了=根深蒂固",emoji:"🌳",roots:["in","veter","ate"]},
    {word:"invidious",chinese:"招人反感的/不公平的",sentence:"Making <strong>invidious</strong> comparisons is unfair.",tip:"IN(向)+VID(看)+IOUS=看了讓人不爽的=招人反感",emoji:"😒",roots:["in","vid","ious"]},
    {word:"irascible",chinese:"易怒的/暴躁的",sentence:"The <strong>irascible</strong> old man shouted at everyone.",tip:"IR(向)+ASC(怒)+IBLE=容易發怒的=易怒的",emoji:"😡",roots:["ir","asc","ible"]},
    {word:"irresolute",chinese:"猶豫不決的/優柔寡斷的",sentence:"His <strong>irresolute</strong> manner frustrated his team.",tip:"IR(不)+RESOLUTE(堅定)=不堅定的=猶豫的",emoji:"🤷",roots:["ir","resolut","e"]},
    {word:"jettison",chinese:"拋棄/丟棄",sentence:"The airline <strong>jettison</strong>ed unnecessary costs.",tip:"JET(扔)+TISON=把東西扔出去=拋棄",emoji:"🗑️",roots:["jet","tison"]},
    {word:"jurisprudence",chinese:"法學/法律體系",sentence:"She studied <strong>jurisprudence</strong> at Oxford.",tip:"JURIS(法律)+PRUDENCE(謹慎)=對法律的謹慎研究=法學",emoji:"⚖️",roots:["juris","prud","ence"]},
    {word:"lachrymose",chinese:"愛哭的/催人淚下的",sentence:"The movie was rather <strong>lachrymose</strong>.",tip:"LACHRYM(淚)+OSE=充滿淚水的=催人淚下",emoji:"😢",roots:["lachrym","ose"]},
    {word:"languor",chinese:"倦怠/慵懶",sentence:"The tropical heat induced a pleasant <strong>languor</strong>.",tip:"LANGU(疲倦)+OR=疲倦的狀態=倦怠",emoji:"😴",roots:["langu","or"]},
    {word:"largesse",chinese:"慷慨/大方",sentence:"The billionaire's <strong>largesse</strong> funded many projects.",tip:"LARGE(大)+SSE=大方給予=慷慨",emoji:"💰",roots:["large","sse"]},
    {word:"legerdemain",chinese:"戲法/花招",sentence:"The politician used financial <strong>legerdemain</strong>.",tip:"LEGER(輕)+DE(的)+MAIN(手)=手很輕巧=戲法",emoji:"🎩",roots:["leger","de","main"]},
    {word:"loquacious",chinese:"話多的/健談的",sentence:"The <strong>loquacious</strong> guide talked nonstop.",tip:"LOQ(說)+UACIOUS=一直說的=話多的",emoji:"🗣️",roots:["loqu","acious"]},
    {word:"magniloquent",chinese:"誇大的/言辭華麗的",sentence:"His <strong>magniloquent</strong> rhetoric impressed few.",tip:"MAGNI(大)+LOQ(說)+UENT=說大話的=誇大的",emoji:"🎭",roots:["magni","loqu","ent"]},
    {word:"malfeasance",chinese:"不法行為/瀆職",sentence:"The mayor was accused of <strong>malfeasance</strong>.",tip:"MAL(壞)+FEAS(做)+ANCE=做壞事=不法行為",emoji:"⚖️",roots:["mal","feas","ance"]},
    {word:"malinger",chinese:"裝病/偽裝生病",sentence:"He was <strong>malinger</strong>ing to avoid work.",tip:"MAL(壞)+LINGER(逗留)=用壞方式逗留不走=裝病",emoji:"🤒",roots:["mal","inger"]},
    {word:"mendacious",chinese:"虛假的/說謊的",sentence:"His <strong>mendacious</strong> testimony was exposed.",tip:"MEND(錯誤)+ACIOUS=充滿錯誤的=說謊的",emoji:"🤥",roots:["mend","acious"]},
    {word:"meretricious",chinese:"華而不實的/俗豔的",sentence:"The <strong>meretricious</strong> decorations cheapened the room.",tip:"MERETRIC(娼妓)+IOUS=像妓女裝扮的=華而不實",emoji:"✨",roots:["meretric","ious"]},
    {word:"metamorphosis",chinese:"變形/蛻變",sentence:"The caterpillar undergoes <strong>metamorphosis</strong>.",tip:"META(超越)+MORPH(形狀)+OSIS=超越原來的形狀=蛻變",emoji:"🦋",roots:["meta","morph","osis"]},
    {word:"militate",chinese:"影響/起作用(反對)",sentence:"Several factors <strong>militate</strong> against success.",tip:"MILIT(軍事)+ATE=像軍隊一樣對抗=起反作用",emoji:"⚔️",roots:["milit","ate"]},
    {word:"misanthrope",chinese:"厭世者/憤世嫉俗者",sentence:"The old <strong>misanthrope</strong> avoided all social contact.",tip:"MIS(恨)+ANTHROP(人)+E=恨人的人=厭世者",emoji:"😑",roots:["mis","anthrop","e"]},
    {word:"mollify",chinese:"安撫/緩和",sentence:"She tried to <strong>mollify</strong> the upset customer.",tip:"MOLL(軟)+IFY(使)=使變軟=安撫",emoji:"🕊️",roots:["moll","ify"]},
    {word:"moribund",chinese:"垂死的/即將結束的",sentence:"The <strong>moribund</strong> industry needs reinvention.",tip:"MORI(死)+BUND(界)=在死亡邊界的=垂死的",emoji:"💀",roots:["mori","bund"]},
    {word:"munificent",chinese:"慷慨的/豐厚的",sentence:"The <strong>munificent</strong> donation funded the library.",tip:"MUNI(贈予)+FIC(做)+ENT=做出贈予的=慷慨的",emoji:"💰",roots:["muni","fic","ent"]},
    {word:"nadir",chinese:"最低點/谷底",sentence:"The stock market reached its <strong>nadir</strong> in March.",tip:"NADIR=阿拉伯語天底=最低點",emoji:"📉",roots:["nad","ir"]},
    {word:"neophyte",chinese:"新手/初學者",sentence:"As a <strong>neophyte</strong> in politics, she had much to learn.",tip:"NEO(新)+PHYTE(生長)=新生長的=新手",emoji:"🌱",roots:["neo","phyte"]},
    {word:"nonchalance",chinese:"冷淡/漫不經心",sentence:"He accepted the award with studied <strong>nonchalance</strong>.",tip:"NON(不)+CHAL(在意)+ANCE=不在意的態度=冷淡",emoji:"😎",roots:["non","chal","ance"]},
    {word:"obdurate",chinese:"頑固的/冷酷的",sentence:"The <strong>obdurate</strong> negotiator refused to budge.",tip:"OB(對著)+DUR(硬)+ATE=硬對著的=頑固的",emoji:"🗿",roots:["ob","dur","ate"]},
    {word:"obsequious",chinese:"諂媚的/卑躬屈膝的",sentence:"The <strong>obsequious</strong> assistant agreed with everything.",tip:"OB(向)+SEQU(跟隨)+IOUS=一直跟隨的=諂媚的",emoji:"🙇",roots:["ob","sequ","ious"]},
    {word:"obstreperous",chinese:"喧鬧的/難控制的",sentence:"The <strong>obstreperous</strong> crowd refused to quiet down.",tip:"OB(對)+STREP(噪音)+EROUS=對著製造噪音=喧鬧的",emoji:"📢",roots:["ob","strep","erous"]},
    {word:"obviate",chinese:"消除/排除",sentence:"The new design <strong>obviate</strong>s the need for repairs.",tip:"OB(對著)+VI(路)+ATE=擋在路前面消除=排除",emoji:"🚫",roots:["ob","vi","ate"]},
    {word:"officious",chinese:"多管閒事的/好干涉的",sentence:"The <strong>officious</strong> neighbor reported every noise.",tip:"OFFIC(職責)+IOUS=過度履行職責的=多管閒事",emoji:"😤",roots:["offic","ious"]},
    {word:"opprobrium",chinese:"譴責/恥辱",sentence:"The scandal brought <strong>opprobrium</strong> on the family.",tip:"OP(對)+PROBR(恥辱)+IUM=對著施加恥辱=譴責",emoji:"😔",roots:["op","probr","ium"]},
    {word:"ossify",chinese:"骨化/僵化",sentence:"The bureaucracy has <strong>ossifie</strong>d over decades.",tip:"OS(骨)+SIFY(使)=使變成骨頭=僵化",emoji:"🦴",roots:["os","sify"]},
    {word:"palliative",chinese:"緩和的/治標的",sentence:"The treatment is merely <strong>palliative</strong>, not curative.",tip:"PALL(遮蓋)+IATIVE=把症狀遮蓋的=緩和的",emoji:"💊",roots:["pall","iat","ive"]},
    {word:"panegyric",chinese:"頌詞/頌辭",sentence:"The eulogy was a <strong>panegyric</strong> to her achievements.",tip:"PAN(全部)+EGYR(集會)+IC=全體集會讚美=頌詞",emoji:"🎵",roots:["pan","egyr","ic"]},
    {word:"paragon",chinese:"典範/模範",sentence:"She is a <strong>paragon</strong> of virtue.",tip:"PARA(旁邊)+GON(磨石)=在磨石旁磨出來的完美=典範",emoji:"⭐",roots:["para","gon"]},
    {word:"pariah",chinese:"賤民/被排斥者",sentence:"After the scandal, he became a social <strong>pariah</strong>.",tip:"PARIAH=印度種姓制度中被排斥的人=賤民",emoji:"🚪",roots:["par","iah"]},
    {word:"parsimonious",chinese:"吝嗇的/小氣的",sentence:"The <strong>parsimonious</strong> landlord refused all repairs.",tip:"PARSI(節省)+MON(警告)+IOUS=過度節省的=吝嗇的",emoji:"💰",roots:["parsi","mon","ious"]},
    {word:"pathos",chinese:"感染力/悲愴",sentence:"The story is full of <strong>pathos</strong>.",tip:"PATH(感覺/痛苦)+OS=引起痛苦感覺的=悲愴",emoji:"😢",roots:["path","os"]},
    {word:"pecuniary",chinese:"金錢的/財務的",sentence:"He had no <strong>pecuniary</strong> interest in the deal.",tip:"PECUN(錢)+IARY=關於錢的=金錢的",emoji:"💰",roots:["pecun","iary"]},
    {word:"pellucid",chinese:"清澈的/明晰的",sentence:"Her writing is remarkably <strong>pellucid</strong>.",tip:"PEL(穿過)+LUCID(光)=光能穿過的=清澈的",emoji:"💎",roots:["pel","lucid"]},
    {word:"penurious",chinese:"極度貧困的/吝嗇的",sentence:"The <strong>penurious</strong> old man hoarded every penny.",tip:"PENUR(貧困)+IOUS=極度貧困的/因窮而吝嗇",emoji:"💸",roots:["penur","ious"]},
    {word:"perdition",chinese:"永久毀滅/地獄",sentence:"The preacher warned of eternal <strong>perdition</strong>.",tip:"PERD(毀滅)+ITION=完全毀滅=地獄",emoji:"🔥",roots:["perd","ition"]},
    {word:"perfidious",chinese:"背信棄義的/不忠的",sentence:"The <strong>perfidious</strong> ally betrayed their trust.",tip:"PER(通過)+FID(信任)+IOUS=破壞信任的=背信的",emoji:"🗡️",roots:["per","fid","ious"]},
    {word:"peripatetic",chinese:"巡迴的/流動的",sentence:"She led a <strong>peripatetic</strong> life, never staying long.",tip:"PERI(周圍)+PATET(走)+IC=到處走的=巡迴的",emoji:"🚶",roots:["peri","patet","ic"]},
    {word:"perspicacious",chinese:"有洞察力的/敏銳的",sentence:"A <strong>perspicacious</strong> analyst predicted the crash.",tip:"PER(穿過)+SPIC(看)+ACIOUS=能看穿的=有洞察力",emoji:"🦅",roots:["per","spic","acious"]},
    {word:"pertinacious",chinese:"頑強的/堅持的",sentence:"Her <strong>pertinacious</strong> efforts finally paid off.",tip:"PER(持續)+TIN(握)+ACIOUS=持續握住的=頑強的",emoji:"💪",roots:["per","tin","acious"]},
    {word:"phlegmatic",chinese:"冷靜的/不動感情的",sentence:"His <strong>phlegmatic</strong> nature kept him calm in crises.",tip:"PHLEGM(痰/冷靜)+ATIC=像痰一樣冷的=冷靜的",emoji:"🧊",roots:["phlegm","atic"]},
    {word:"plaintive",chinese:"悲傷的/哀怨的",sentence:"The <strong>plaintive</strong> cry of the bird echoed in the valley.",tip:"PLAINT(哀嘆)+IVE=充滿哀嘆的=悲傷的",emoji:"😢",roots:["plaint","ive"]},
    {word:"platitude",chinese:"陳腐之言/老生常談",sentence:"The speech was full of meaningless <strong>platitude</strong>s.",tip:"PLAT(平坦)+ITUDE=平淡無奇的話=陳腐之言",emoji:"😴",roots:["plat","itude"]},
    {word:"plethora",chinese:"過多/過剩",sentence:"There is a <strong>plethora</strong> of options available.",tip:"PLETH(滿)+ORA=滿出來的=過多",emoji:"📦",roots:["pleth","ora"]},
    {word:"polemic",chinese:"論戰/爭論",sentence:"The book is a <strong>polemic</strong> against capitalism.",tip:"POLEM(戰爭)+IC=文字上的戰爭=論戰",emoji:"⚔️",roots:["polem","ic"]},
    {word:"ponderous",chinese:"笨重的/沉悶的",sentence:"His <strong>ponderous</strong> writing style bores readers.",tip:"PONDER(重量)+OUS=很重的=笨重的/沉悶的",emoji:"🐘",roots:["ponder","ous"]},
    {word:"portentous",chinese:"不祥的/自命不凡的",sentence:"The dark clouds looked <strong>portentous</strong>.",tip:"PORT(預兆)+ENTOUS=帶有預兆的=不祥的",emoji:"⛈️",roots:["port","ent","ous"]},
    {word:"pragmatism",chinese:"務實主義/實用主義",sentence:"Political <strong>pragmatism</strong> often trumps ideology.",tip:"PRAGMA(行動)+TISM=注重行動的主義=務實主義",emoji:"🎯",roots:["pragma","tism"]},
    {word:"precipitous",chinese:"陡峭的/倉促的",sentence:"The <strong>precipitous</strong> decline alarmed investors.",tip:"PRE(前)+CIPIT(頭)+OUS=頭朝前衝的=陡峭的",emoji:"📉",roots:["pre","cipit","ous"]},
    {word:"predilection",chinese:"偏好/偏愛",sentence:"She has a <strong>predilection</strong> for classical music.",tip:"PRE(提前)+DI+LECT(選擇)+ION=提前選好的=偏好",emoji:"❤️",roots:["pre","di","lect","ion"]},
    {word:"preponderance",chinese:"優勢/多數",sentence:"The <strong>preponderance</strong> of evidence supports the theory.",tip:"PRE(前)+PONDER(重)+ANCE=在前面更重的=優勢",emoji:"⚖️",roots:["pre","ponder","ance"]},
    {word:"prescient",chinese:"有先見之明的",sentence:"Her <strong>prescient</strong> warning saved many lives.",tip:"PRE(前)+SCI(知道)+ENT=提前知道的=有先見之明",emoji:"🔮",roots:["pre","sci","ent"]},
    {word:"prevaricate",chinese:"支吾/閃爍其辭",sentence:"The witness tried to <strong>prevaricate</strong>.",tip:"PRE(前)+VARIC(偏斜)+ATE=走在歪路上=支吾",emoji:"🤥",roots:["pre","varic","ate"]},
    {word:"probity",chinese:"正直/誠實",sentence:"His <strong>probity</strong> made him an excellent judge.",tip:"PROB(好/正直)+ITY=好的品性=正直",emoji:"💎",roots:["prob","ity"]},
    {word:"proclivity",chinese:"傾向/癖性",sentence:"She has a <strong>proclivity</strong> for adventure.",tip:"PRO(向前)+CLIV(傾斜)+ITY=向前傾斜=傾向",emoji:"⬆️",roots:["pro","cliv","ity"]},
    {word:"prodigal",chinese:"揮霍的/浪子",sentence:"The <strong>prodigal</strong> son returned home penniless.",tip:"PRO(向前)+DIG(驅趕)+AL=把錢趕出去=揮霍的",emoji:"💸",roots:["pro","dig","al"]},
    {word:"prodigious",chinese:"巨大的/驚人的",sentence:"She has a <strong>prodigious</strong> talent for music.",tip:"PRODIG(奇蹟)+IOUS=像奇蹟一樣的=驚人的",emoji:"🤯",roots:["prodig","ious"]},
    {word:"prognosticate",chinese:"預測/預言",sentence:"Economists <strong>prognosticate</strong> a recession.",tip:"PRO(提前)+GNOST(知道)+ICATE=提前知道=預測",emoji:"🔮",roots:["pro","gnost","icate"]},
    {word:"prolixity",chinese:"冗長/囉嗦",sentence:"The report suffers from <strong>prolixity</strong>.",tip:"PRO(向前)+LIX(流)+ITY=一直向前流=冗長",emoji:"📜",roots:["pro","lix","ity"]},
    {word:"promontory",chinese:"海角/岬",sentence:"The lighthouse stands on a rocky <strong>promontory</strong>.",tip:"PRO(向前)+MONT(山)+ORY=向前突出的山=海角",emoji:"🏖️",roots:["pro","mont","ory"]},
    {word:"propinquity",chinese:"接近/鄰近",sentence:"Their <strong>propinquity</strong> led to friendship.",tip:"PRO(接近)+PINQU(接近)+ITY=接近的狀態=鄰近",emoji:"🏘️",roots:["pro","pinqu","ity"]},
    {word:"propitiate",chinese:"安撫/討好",sentence:"They offered sacrifices to <strong>propitiate</strong> the gods.",tip:"PRO(向前)+PITI(善意)+ATE=向前展示善意=安撫",emoji:"🙏",roots:["pro","piti","ate"]},
    {word:"proscribe",chinese:"禁止/排斥",sentence:"The government <strong>proscribe</strong>d the organization.",tip:"PRO(公開)+SCRIBE(寫)=公開寫出禁令=禁止",emoji:"🚫",roots:["pro","scribe"]},
    {word:"provenance",chinese:"起源/出處",sentence:"The painting's <strong>provenance</strong> was verified.",tip:"PRO(向前)+VEN(來)+ANCE=從哪裡來的=起源",emoji:"🏛️",roots:["pro","ven","ance"]},
    {word:"prurient",chinese:"色情的/好色的",sentence:"The movie appeals to <strong>prurient</strong> interests.",tip:"PRUR(癢)+IENT=使人發癢的=色情的",emoji:"🙈",roots:["prur","ient"]},
    {word:"pugilism",chinese:"拳擊/搏鬥",sentence:"He studied the art of <strong>pugilism</strong>.",tip:"PUGIL(拳頭)+ISM=用拳頭的=拳擊",emoji:"🥊",roots:["pugil","ism"]},
    {word:"pugnacious",chinese:"好鬥的/好爭辯的",sentence:"His <strong>pugnacious</strong> attitude creates conflicts.",tip:"PUGN(打)+ACIOUS=喜歡打的=好鬥的",emoji:"👊",roots:["pugn","acious"]},
    {word:"punctilious",chinese:"一絲不苟的/拘泥的",sentence:"She is <strong>punctilious</strong> about grammar rules.",tip:"PUNCT(點)+IL+IOUS=注意每個小點的=一絲不苟",emoji:"📌",roots:["punct","il","ious"]},
    {word:"pusillanimous",chinese:"膽小的/懦弱的",sentence:"The <strong>pusillanimous</strong> leader avoided all risks.",tip:"PUSILL(小)+ANIM(心靈)+OUS=心很小的=膽小的",emoji:"🐁",roots:["pusill","anim","ous"]},
    {word:"quagmire",chinese:"泥沼/困境",sentence:"The project became a financial <strong>quagmire</strong>.",tip:"QUAG(沼澤)+MIRE(泥)=泥沼地=困境",emoji:"🏚️",roots:["quag","mire"]},
    {word:"querulous",chinese:"愛抱怨的/牢騷的",sentence:"The <strong>querulous</strong> customer demanded a refund.",tip:"QUER(抱怨)+UL+OUS=不停抱怨的",emoji:"😤",roots:["quer","ul","ous"]},
    {word:"quiescent",chinese:"靜止的/沉寂的",sentence:"The volcano has been <strong>quiescent</strong> for decades.",tip:"QUI(安靜)+ESCENT(變成)=變得安靜的=靜止的",emoji:"🌋",roots:["qui","escent"]},
    {word:"raconteur",chinese:"善於講故事的人",sentence:"She is a gifted <strong>raconteur</strong>.",tip:"RACONT(講述)+EUR(人)=講述的人=說故事的人",emoji:"📖",roots:["racont","eur"]},
    {word:"rapacious",chinese:"貪婪的/掠奪的",sentence:"The <strong>rapacious</strong> company exploited workers.",tip:"RAP(抓)+ACIOUS=一直抓取的=貪婪的",emoji:"🦅",roots:["rap","acious"]},
    {word:"recondite",chinese:"深奧的/難懂的",sentence:"The book deals with <strong>recondite</strong> topics.",tip:"RE(回)+COND(隱藏)+ITE=藏回去的=深奧的",emoji:"📚",roots:["re","cond","ite"]},
    {word:"recrimination",chinese:"反控/反唇相譏",sentence:"The meeting dissolved into mutual <strong>recrimination</strong>s.",tip:"RE(回)+CRIMIN(控告)+ATION=回頭控告=反控",emoji:"😤",roots:["re","crimin","ation"]},
    {word:"redoubtable",chinese:"令人敬畏的/可怕的",sentence:"She is a <strong>redoubtable</strong> opponent in debate.",tip:"RE(強調)+DOUBT(畏懼)+ABLE=讓人畏懼的=令人敬畏",emoji:"💪",roots:["re","doubt","able"]},
    {word:"refulgent",chinese:"燦爛的/光輝的",sentence:"The <strong>refulgent</strong> sunrise painted the sky gold.",tip:"RE(回)+FULG(閃耀)+ENT=閃耀回來的=燦爛的",emoji:"✨",roots:["re","fulg","ent"]},
    {word:"remonstrate",chinese:"抗議/規勸",sentence:"She <strong>remonstrate</strong>d with him about his behavior.",tip:"RE(回)+MONSTR(展示)+ATE=展示回去=抗議/規勸",emoji:"☝️",roots:["re","monstr","ate"]},
    {word:"renege",chinese:"食言/背信",sentence:"He <strong>renege</strong>d on his promise.",tip:"RE(回)+NEGE(否認)=否認回去=食言",emoji:"🤥",roots:["re","nege"]},
    {word:"replete",chinese:"充滿的/飽的",sentence:"The book is <strong>replete</strong> with examples.",tip:"RE(再)+PLETE(填滿)=再次填滿=充滿的",emoji:"📦",roots:["re","plete"]},
    {word:"reproach",chinese:"責備/批評",sentence:"His behavior is beyond <strong>reproach</strong>.",tip:"RE(回)+PROACH(靠近)=靠回來指責=責備",emoji:"😠",roots:["re","proach"]},
    {word:"reprobate",chinese:"墮落者/道德敗壞的",sentence:"The <strong>reprobate</strong> showed no remorse.",tip:"RE(回)+PROB(試驗)+ATE=試驗後被退回的=墮落者",emoji:"😈",roots:["re","prob","ate"]},
    {word:"requiem",chinese:"安魂曲/輓歌",sentence:"Mozart composed a famous <strong>requiem</strong>.",tip:"REQUI(安息)+EM=為安息而作=安魂曲",emoji:"🎵",roots:["requi","em"]},
    {word:"rescind",chinese:"撤銷/廢除",sentence:"The policy was <strong>rescind</strong>ed after protests.",tip:"RE(回)+SCIND(切)=切回去=撤銷",emoji:"✂️",roots:["re","scind"]},
    {word:"sagacious",chinese:"睿智的/有遠見的",sentence:"The <strong>sagacious</strong> leader anticipated problems.",tip:"SAG(感知)+ACIOUS=感知力強的=睿智的",emoji:"🦉",roots:["sag","acious"]},
    {word:"salacious",chinese:"猥褻的/好色的",sentence:"The tabloid published <strong>salacious</strong> rumors.",tip:"SAL(跳)+ACIOUS=像動物求偶跳躍的=猥褻的",emoji:"🙈",roots:["sal","acious"]},
    {word:"salubrious",chinese:"有益健康的",sentence:"The mountain air is very <strong>salubrious</strong>.",tip:"SALUBR(健康)+IOUS=帶來健康的=有益健康的",emoji:"🏔️",roots:["salubr","ious"]},
    {word:"sanctimonious",chinese:"假裝虔誠的/偽善的",sentence:"His <strong>sanctimonious</strong> attitude annoyed everyone.",tip:"SANCTI(神聖)+MON+IOUS=假裝神聖的=偽善的",emoji:"😇",roots:["sancti","mon","ious"]},
    {word:"saturnine",chinese:"陰沉的/憂鬱的",sentence:"His <strong>saturnine</strong> expression scared the children.",tip:"SATURN(土星)+INE=像土星一樣陰暗的=陰沉的",emoji:"🌑",roots:["saturn","ine"]},
    {word:"scrupulous",chinese:"一絲不苟的/有良心的",sentence:"She is <strong>scrupulous</strong> in her work.",tip:"SCRUP(小石頭)+ULOUS=像被小石子硌著一樣謹慎",emoji:"📏",roots:["scrup","ul","ous"]},
    {word:"sedulous",chinese:"勤勉的/不懈的",sentence:"Through <strong>sedulous</strong> effort, she mastered the language.",tip:"SED(沒有)+UL(欺騙)+OUS=沒有欺騙地努力=勤勉",emoji:"📚",roots:["sed","ul","ous"]},
    {word:"sententious",chinese:"說教的/簡潔的",sentence:"His <strong>sententious</strong> remarks annoyed the audience.",tip:"SENTENT(格言)+IOUS=充滿格言的=說教的",emoji:"📜",roots:["sentent","ious"]},
    {word:"sequester",chinese:"隔離/扣押",sentence:"The jury was <strong>sequester</strong>ed during the trial.",tip:"SE(離開)+QUEST(尋找)+ER=把人帶離去找=隔離",emoji:"🔒",roots:["se","quest","er"]},
    {word:"sinecure",chinese:"閒差/掛名職位",sentence:"The position was a well-paid <strong>sinecure</strong>.",tip:"SINE(沒有)+CURE(照料)=不用照料的工作=閒差",emoji:"💤",roots:["sine","cure"]},
    {word:"solicitous",chinese:"關心的/焦慮的",sentence:"She was <strong>solicitous</strong> about his health.",tip:"SOLICIT(請求)+OUS=不斷請求關心的=關心的",emoji:"🤗",roots:["solicit","ous"]},
    {word:"soporific",chinese:"催眠的/令人昏昏欲睡的",sentence:"The professor's <strong>soporific</strong> lecture put us to sleep.",tip:"SOPOR(睡眠)+IFIC(使)=使人睡覺的=催眠的",emoji:"😴",roots:["sopor","ific"]},
    {word:"specious",chinese:"似是而非的/貌似有理的",sentence:"His <strong>specious</strong> argument fooled many people.",tip:"SPEC(看)+IOUS=看起來好看的(但不是)=似是而非",emoji:"🎭",roots:["spec","ious"]},
    {word:"stolid",chinese:"遲鈍的/無動於衷的",sentence:"The guard remained <strong>stolid</strong> throughout.",tip:"STOL(忍受)+ID=能忍受一切的=無動於衷的",emoji:"🗿",roots:["stol","id"]},
    {word:"strident",chinese:"刺耳的/強硬的",sentence:"Her <strong>strident</strong> voice filled the room.",tip:"STRID(刺耳)+ENT=發出刺耳聲的=刺耳的",emoji:"📢",roots:["strid","ent"]},
    {word:"subjugate",chinese:"征服/使屈從",sentence:"The empire <strong>subjugate</strong>d many peoples.",tip:"SUB(下面)+JUG(枷鎖)+ATE=放在枷鎖下面=征服",emoji:"⛓️",roots:["sub","jug","ate"]},
    {word:"subterfuge",chinese:"詭計/遁辭",sentence:"He obtained the information through <strong>subterfuge</strong>.",tip:"SUBTER(下面)+FUGE(逃)=在下面偷偷逃走=詭計",emoji:"🕵️",roots:["subter","fuge"]},
    {word:"supercilious",chinese:"傲慢的/目中無人的",sentence:"Her <strong>supercilious</strong> attitude alienated colleagues.",tip:"SUPER(上面)+CIL(眉毛)+IOUS=抬起眉毛的=傲慢的",emoji:"😤",roots:["super","cil","ious"]},
    {word:"sycophantic",chinese:"諂媚的/拍馬屁的",sentence:"The <strong>sycophantic</strong> press praised everything.",tip:"SYCO(無花果)+PHANT(展示)+IC=展示無花果討好=諂媚",emoji:"🙇",roots:["syco","phant","ic"]},
    {word:"tendentious",chinese:"有偏見的/帶傾向性的",sentence:"The article was criticized as <strong>tendentious</strong>.",tip:"TEND(傾向)+ENTIOUS=帶有傾向的=有偏見的",emoji:"↗️",roots:["tend","ent","ious"]},
    {word:"timorous",chinese:"膽怯的/畏縮的",sentence:"The <strong>timorous</strong> boy hid behind his mother.",tip:"TIMOR(恐懼)+OUS=充滿恐懼的=膽怯的",emoji:"😨",roots:["timor","ous"]},
    {word:"torpid",chinese:"遲鈍的/懶散的",sentence:"The <strong>torpid</strong> economy showed no signs of recovery.",tip:"TORP(麻木)+ID=麻木的=遲鈍的",emoji:"🐢",roots:["torp","id"]},
    {word:"tractable",chinese:"溫順的/易駕馭的",sentence:"The <strong>tractable</strong> horse was perfect for beginners.",tip:"TRACT(拉)+ABLE=容易拉動的=溫順的",emoji:"🐴",roots:["tract","able"]},
    {word:"transgression",chinese:"違反/過錯",sentence:"His <strong>transgression</strong>s were eventually discovered.",tip:"TRANS(越過)+GRESS(走)+ION=走過界的=違反",emoji:"🚫",roots:["trans","gress","ion"]},
    {word:"trenchant",chinese:"犀利的/一針見血的",sentence:"She is known for her <strong>trenchant</strong> criticism.",tip:"TRENCH(切)+ANT=切中要害的=犀利的",emoji:"🗡️",roots:["trench","ant"]},
    {word:"truculent",chinese:"好鬥的/兇猛的",sentence:"The <strong>truculent</strong> bully intimidated everyone.",tip:"TRUC(兇猛)+UL+ENT=很兇猛的=好鬥的",emoji:"😠",roots:["truc","ul","ent"]},
    {word:"turgid",chinese:"浮誇的/腫脹的",sentence:"His <strong>turgid</strong> prose is difficult to read.",tip:"TURG(腫)+ID=腫脹的文字=浮誇的",emoji:"📜",roots:["turg","id"]},
    {word:"turpitude",chinese:"邪惡/卑鄙",sentence:"Moral <strong>turpitude</strong> disqualifies candidates.",tip:"TURP(醜陋)+ITUDE=醜陋的品行=邪惡",emoji:"😈",roots:["turp","itude"]},
    {word:"ubiquity",chinese:"無所不在/遍布",sentence:"The <strong>ubiquity</strong> of social media affects culture.",tip:"UBI(哪裡)+QUIT(到處)+Y=到處都是的狀態=遍布",emoji:"🌐",roots:["ubi","quit","y"]},
    {word:"unctuous",chinese:"虛情假意的/油腔滑調的",sentence:"His <strong>unctuous</strong> charm made people uncomfortable.",tip:"UNCT(油)+UOUS=像油一樣滑的=油腔滑調的",emoji:"🛢️",roots:["unct","uous"]},
    {word:"unimpeachable",chinese:"無可置疑的/無懈可擊的",sentence:"Her integrity is <strong>unimpeachable</strong>.",tip:"UN(不)+IMPEACH(彈劾)+ABLE=不能彈劾的=無可置疑",emoji:"💎",roots:["un","im","peach","able"]},
    {word:"uxorious",chinese:"怕老婆的/溺愛妻子的",sentence:"The <strong>uxorious</strong> husband obeyed her every wish.",tip:"UXOR(妻子)+IOUS=對妻子過度的=怕老婆的",emoji:"💑",roots:["uxor","ious"]},
    {word:"vacillate",chinese:"猶豫不決/搖擺",sentence:"She <strong>vacillate</strong>d between the two options.",tip:"VACILL(搖擺)+ATE=來回搖擺=猶豫不決",emoji:"⚖️",roots:["vacill","ate"]},
    {word:"valediction",chinese:"告別/告別辭",sentence:"She gave a touching <strong>valediction</strong> at graduation.",tip:"VALE(再見)+DICT(說)+ION=說再見=告別辭",emoji:"👋",roots:["vale","dict","ion"]},
    {word:"vapid",chinese:"乏味的/無聊的",sentence:"The conversation was entirely <strong>vapid</strong>.",tip:"VAP(蒸氣)+ID=像蒸氣一樣空的=乏味的",emoji:"😑",roots:["vap","id"]},
    {word:"vehement",chinese:"激烈的/猛烈的",sentence:"She made a <strong>vehement</strong> protest against the decision.",tip:"VEH(攜帶)+EMENT=攜帶強烈情緒的=激烈的",emoji:"🔥",roots:["veh","ement"]},
    {word:"venal",chinese:"貪污的/唯利是圖的",sentence:"The <strong>venal</strong> official accepted bribes.",tip:"VEN(賣)+AL=什麼都能賣的=貪污的",emoji:"💰",roots:["ven","al"]},
    {word:"venial",chinese:"可原諒的/輕微的",sentence:"It was a <strong>venial</strong> offense, not a serious one.",tip:"VENI(原諒)+AL=可以原諒的=輕微的",emoji:"😌",roots:["veni","al"]},
    {word:"verisimilitude",chinese:"逼真/似真性",sentence:"The film achieves great <strong>verisimilitude</strong>.",tip:"VERI(真)+SIMIL(相似)+ITUDE=和真的相似=逼真",emoji:"🎬",roots:["veri","simil","itude"]},
    {word:"vitiate",chinese:"損害/使無效",sentence:"Fraud <strong>vitiate</strong>s the contract.",tip:"VITI(缺陷)+ATE=使有缺陷=損害/使無效",emoji:"❌",roots:["viti","ate"]},
    {word:"vituperate",chinese:"痛罵/辱罵",sentence:"He <strong>vituperate</strong>d his opponents mercilessly.",tip:"VITU(缺陷)+PER(完全)+ATE=完全用缺陷罵人=痛罵",emoji:"🤬",roots:["vitu","per","ate"]},
    {word:"vociferous",chinese:"大聲疾呼的/吵鬧的",sentence:"The protesters were <strong>vociferous</strong> in their demands.",tip:"VOCI(聲音)+FER(帶)+OUS=帶來大聲音的=大聲的",emoji:"📢",roots:["voci","fer","ous"]},
    {word:"voluble",chinese:"健談的/口若懸河的",sentence:"The <strong>voluble</strong> salesman talked without pause.",tip:"VOLU(轉)+BLE=嘴巴不停轉的=健談的",emoji:"🗣️",roots:["volu","ble"]},
    {word:"wanton",chinese:"肆意的/放蕩的",sentence:"The <strong>wanton</strong> destruction angered the community.",tip:"WANT(缺乏)+ON=缺乏約束的=肆意的",emoji:"💥",roots:["want","on"]},
    {word:"zephyr",chinese:"微風/和風",sentence:"A gentle <strong>zephyr</strong> rustled the leaves.",tip:"ZEPHYR=希臘西風之神=溫柔的微風",emoji:"🍃",roots:["zeph","yr"]},
    {word:"abnegate",chinese:"放棄/自我克制",sentence:"He <strong>abnegate</strong>d his personal desires for the team.",tip:"AB(離開)+NEG(否認)+ATE=否認自己的需要=放棄",emoji:"🚫",roots:["ab","neg","ate"]},
    {word:"accrue",chinese:"累積/自然增長",sentence:"Interest will <strong>accrue</strong> on the savings account.",tip:"AC(向)+CRUE(成長)=向某處成長=累積",emoji:"📈",roots:["ac","crue"]},
    {word:"acumen",chinese:"敏銳/精明",sentence:"Her business <strong>acumen</strong> led to great success.",tip:"ACU(尖銳)+MEN=頭腦尖銳=敏銳",emoji:"🧠",roots:["acu","men"]},
    {word:"adroit",chinese:"靈巧的/機敏的",sentence:"An <strong>adroit</strong> politician navigates complex situations.",tip:"A(向)+DROIT(右/正確)=向正確方向走=靈巧的",emoji:"🤹",roots:["a","droit"]},
    {word:"adventitious",chinese:"偶然的/外來的",sentence:"The plant developed <strong>adventitious</strong> roots.",tip:"AD(向)+VENT(來)+ITIOUS=偶然來到的=偶然的",emoji:"🍀",roots:["ad","vent","itious"]},
    {word:"affable",chinese:"和藹的/友善的",sentence:"The <strong>affable</strong> host welcomed all guests warmly.",tip:"AF(向)+FABLE(說)=容易對話的=和藹的",emoji:"😊",roots:["af","fable"]},
    {word:"aggrandizement",chinese:"擴大/自我吹捧",sentence:"His pursuit of self-<strong>aggrandizement</strong> was obvious.",tip:"AG(向)+GRAND(大)+MENT=使自己變大=自我吹捧",emoji:"📈",roots:["ag","grand","ize","ment"]},
    {word:"alacrity",chinese:"敏捷/樂意",sentence:"She accepted the offer with <strong>alacrity</strong>.",tip:"ALACR(活潑)+ITY=活潑迅速的態度=敏捷/樂意",emoji:"🏃",roots:["alacr","ity"]},
    {word:"amalgam",chinese:"混合物/汞合金",sentence:"The culture is an <strong>amalgam</strong> of many traditions.",tip:"AMALGAM=汞和其他金屬的混合物=混合",emoji:"🧪",roots:["amalg","am"]},
    {word:"amenable",chinese:"順從的/可接受的",sentence:"She is <strong>amenable</strong> to the new proposal.",tip:"A(向)+MEN(帶)+ABLE=能被帶著走的=順從的",emoji:"👍",roots:["a","men","able"]},
    {word:"anachronistic",chinese:"時代錯誤的",sentence:"The monarchy seems <strong>anachronistic</strong> in modern times.",tip:"ANA(反)+CHRON(時間)+ISTIC=反時間的=時代錯誤",emoji:"⏰",roots:["ana","chron","istic"]},
    {word:"anodyne",chinese:"止痛的/無刺激的",sentence:"The statement was deliberately <strong>anodyne</strong>.",tip:"AN(無)+ODYNE(痛)=無痛的=不刺激的",emoji:"😌",roots:["an","odyne"]},
    {word:"apocryphal",chinese:"偽經的/不可信的",sentence:"The story about the origin is probably <strong>apocryphal</strong>.",tip:"APO(遠離)+CRYPH(隱藏)+AL=隱藏起來的=可疑的",emoji:"🤔",roots:["apo","cryph","al"]},
    {word:"apposite",chinese:"恰當的/貼切的",sentence:"Her remarks were perfectly <strong>apposite</strong>.",tip:"AP(向)+POSIT(放置)=放到正確位置=恰當的",emoji:"🎯",roots:["ap","posit","e"]},
    {word:"arrogate",chinese:"僭越/冒稱",sentence:"He <strong>arrogate</strong>d authority that was not his.",tip:"AR(向)+ROG(要求)+ATE=無理要求=僭越",emoji:"👑",roots:["ar","rog","ate"]},
    {word:"asperity",chinese:"嚴厲/粗暴",sentence:"She spoke with unexpected <strong>asperity</strong>.",tip:"ASPER(粗糙)+ITY=粗糙的態度=嚴厲",emoji:"😠",roots:["asper","ity"]},
    {word:"assiduous",chinese:"勤勉的/刻苦的",sentence:"Through <strong>assiduous</strong> study, she passed the exam.",tip:"AS(向)+SID(坐)+UOUS=坐下來不走的=勤勉的",emoji:"📚",roots:["as","sid","uous"]},
    {word:"atavistic",chinese:"返祖的/原始本能的",sentence:"Violence is an <strong>atavistic</strong> impulse.",tip:"ATAV(祖先)+ISTIC=回到祖先的=返祖的",emoji:"🧬",roots:["atav","istic"]},
    {word:"auspice",chinese:"贊助/預兆",sentence:"The event was held under the <strong>auspice</strong>s of the UN.",tip:"AU(鳥)+SPICE(看)=看鳥占卜=預兆/贊助",emoji:"🦅",roots:["au","spice"]},
    {word:"autocratic",chinese:"專制的/獨裁的",sentence:"The <strong>autocratic</strong> ruler silenced all opposition.",tip:"AUTO(自己)+CRAT(統治)+IC=自己統治的=專制的",emoji:"👑",roots:["auto","crat","ic"]},
    {word:"baleful",chinese:"邪惡的/有害的",sentence:"He gave her a <strong>baleful</strong> look.",tip:"BALE(災禍)+FUL=充滿災禍的=邪惡的",emoji:"😠",roots:["bale","ful"]},
    {word:"bane",chinese:"禍根/毒害",sentence:"Corruption is the <strong>bane</strong> of good governance.",tip:"BANE=古英語毒藥=禍根",emoji:"☠️",roots:["bane"]},
    {word:"bastardize",chinese:"使變質/使墮落",sentence:"Commercialization has <strong>bastardize</strong>d the tradition.",tip:"BASTARD(私生子)+IZE=使變成不純的=使變質",emoji:"📉",roots:["bastard","ize"]},
    {word:"beatific",chinese:"幸福的/極樂的",sentence:"She had a <strong>beatific</strong> smile on her face.",tip:"BEAT(幸福)+IFIC(使)=帶來幸福的=極樂的",emoji:"😇",roots:["beat","ific"]},
    {word:"beneficent",chinese:"慈善的/行善的",sentence:"The <strong>beneficent</strong> organization fed thousands.",tip:"BENE(好)+FIC(做)+ENT=做好事的=慈善的",emoji:"❤️",roots:["bene","fic","ent"]},
    {word:"bereft",chinese:"被剝奪的/喪失的",sentence:"She was <strong>bereft</strong> of hope after the loss.",tip:"BE(完全)+REFT(被搶走)=被完全搶走=喪失的",emoji:"😢",roots:["be","reft"]},
    {word:"blandishment",chinese:"奉承/花言巧語",sentence:"She resisted all <strong>blandishment</strong>s.",tip:"BLAND(溫和)+ISH+MENT=用溫和話語討好=奉承",emoji:"🍯",roots:["bland","ish","ment"]},
    {word:"blight",chinese:"枯萎病/損害",sentence:"Urban <strong>blight</strong> affects many neighborhoods.",tip:"BLIGHT=植物的枯萎病=比喻損害",emoji:"🥀",roots:["blight"]},
    {word:"bourgeois",chinese:"中產階級的/庸俗的",sentence:"They criticized his <strong>bourgeois</strong> values.",tip:"BOURGEOIS=法語市民=中產階級的（貶義）",emoji:"🏠",roots:["bourg","eois"]},
    {word:"bucolic",chinese:"田園的/鄉村的",sentence:"The <strong>bucolic</strong> landscape inspired many painters.",tip:"BUC(牧牛)+OLIC=像牧牛的生活=田園的",emoji:"🐄",roots:["buc","olic"]},
    {word:"calumniate",chinese:"誹謗/中傷",sentence:"He <strong>calumniate</strong>d his former business partner.",tip:"CALUMN(欺騙)+IATE=用欺騙傷害=誹謗",emoji:"🗣️",roots:["calumni","ate"]},
    {word:"capricious",chinese:"反覆無常的/善變的",sentence:"The <strong>capricious</strong> boss changed plans daily.",tip:"CAPRI(山羊)+CIOUS=像山羊跳來跳去=善變的",emoji:"🐐",roots:["capri","cious"]},
    {word:"castigate",chinese:"嚴懲/嚴厲批評",sentence:"The report <strong>castigate</strong>d the government.",tip:"CASTIG(純淨)+ATE=通過懲罰使純淨=嚴懲",emoji:"😠",roots:["castig","ate"]},
    {word:"cataclysm",chinese:"大災難/劇變",sentence:"The war was a <strong>cataclysm</strong> for the region.",tip:"CATA(向下)+CLYSM(洪水)=洪水向下衝=大災難",emoji:"🌊",roots:["cata","clysm"]},
    {word:"chagrin",chinese:"懊惱/失望",sentence:"Much to his <strong>chagrin</strong>, he lost the game.",tip:"CHAGRIN=法語悲傷=因失敗而懊惱",emoji:"😤",roots:["cha","grin"]},
    {word:"charlatan",chinese:"騙子/江湖郎中",sentence:"The doctor turned out to be a <strong>charlatan</strong>.",tip:"CHARLATAN=義大利語喋喋不休的人=騙子",emoji:"🎭",roots:["charl","atan"]},
    {word:"churlish",chinese:"粗魯的/無禮的",sentence:"It would be <strong>churlish</strong> to refuse the invitation.",tip:"CHURL(農夫)+ISH=像粗魯農夫的=無禮的",emoji:"😠",roots:["churl","ish"]},
    {word:"circumscribe",chinese:"限制/在周圍畫線",sentence:"The constitution <strong>circumscribe</strong>s executive power.",tip:"CIRCUM(周圍)+SCRIBE(寫)=在周圍畫線=限制",emoji:"⭕",roots:["circum","scribe"]},
    {word:"coda",chinese:"尾聲/結尾部分",sentence:"The final chapter serves as a <strong>coda</strong> to the story.",tip:"CODA=音樂術語=樂曲尾聲",emoji:"🎵",roots:["cod","a"]},
    {word:"cogitate",chinese:"深思/仔細考慮",sentence:"She <strong>cogitate</strong>d on the problem for hours.",tip:"COG(思考)+IT+ATE=反覆思考=深思",emoji:"🤔",roots:["cogit","ate"]},
    {word:"comity",chinese:"禮讓/友好",sentence:"International <strong>comity</strong> requires mutual respect.",tip:"COM(一起)+ITY=在一起和睦的=禮讓",emoji:"🤝",roots:["com","ity"]},
    {word:"compunction",chinese:"良心不安/內疚",sentence:"He felt no <strong>compunction</strong> about lying.",tip:"COM(完全)+PUNCT(刺)+ION=良心完全被刺=內疚",emoji:"😔",roots:["com","punct","ion"]},
    {word:"concatenation",chinese:"連串/連鎖",sentence:"A <strong>concatenation</strong> of errors led to the disaster.",tip:"CON(一起)+CATEN(鏈)+ATION=連鏈在一起=連串",emoji:"🔗",roots:["con","caten","ation"]},
    {word:"conduit",chinese:"管道/通道",sentence:"The diplomat served as a <strong>conduit</strong> for information.",tip:"CON(一起)+DUIT(引導)=引導流通的=管道",emoji:"🔌",roots:["con","duit"]},
    {word:"congruent",chinese:"一致的/全等的",sentence:"The results are <strong>congruent</strong> with our hypothesis.",tip:"CON(一起)+GRU(一致)+ENT=一起一致的=相符的",emoji:"🟰",roots:["con","gru","ent"]},
    {word:"consecration",chinese:"奉獻/神聖化",sentence:"The <strong>consecration</strong> of the new church drew crowds.",tip:"CON(完全)+SECR(神聖)+ATION=使完全神聖=奉獻",emoji:"⛪",roots:["con","secr","ation"]},
    {word:"conterminous",chinese:"相鄰的/同界的",sentence:"The two parks are <strong>conterminous</strong>.",tip:"CON(一起)+TERMIN(邊界)+OUS=邊界在一起的=相鄰",emoji:"🗺️",roots:["con","termin","ous"]},
    {word:"contumacious",chinese:"違抗的/不服從的",sentence:"The <strong>contumacious</strong> witness refused to testify.",tip:"CON(一起)+TUM(膨脹)+ACIOUS=膨脹抗拒的=違抗的",emoji:"😤",roots:["con","tum","acious"]},
    {word:"conundrum",chinese:"難題/謎語",sentence:"The budget is a political <strong>conundrum</strong>.",tip:"CON(一起)+UNDRUM=讓大家一起困惑的=難題",emoji:"🧩",roots:["con","undrum"]},
    {word:"corrigendum",chinese:"勘誤表/應更正之處",sentence:"The publisher issued a <strong>corrigendum</strong>.",tip:"CORRIG(改正)+ENDUM=需要改正的=勘誤",emoji:"📝",roots:["corrig","endum"]},
    {word:"coterie",chinese:"小圈子/同人",sentence:"She belongs to an exclusive <strong>coterie</strong> of artists.",tip:"COTERIE=法語佃農團體=小圈子",emoji:"👥",roots:["coter","ie"]},
    {word:"craven",chinese:"怯懦的/膽小的",sentence:"His <strong>craven</strong> surrender disappointed everyone.",tip:"CRAVEN=像被擊敗(cravant)的=怯懦的",emoji:"🐁",roots:["crav","en"]},
    {word:"crescendo",chinese:"漸強/高潮",sentence:"The music built to a powerful <strong>crescendo</strong>.",tip:"CRESC(成長)+ENDO=不斷成長增大=漸強",emoji:"🎵",roots:["cresc","endo"]},
    {word:"curtailment",chinese:"縮減/削減",sentence:"The <strong>curtailment</strong> of freedoms was protested.",tip:"CURT(短)+AIL+MENT=使變短的動作=縮減",emoji:"✂️",roots:["curt","ail","ment"]},
    {word:"delectation",chinese:"享受/愉悅",sentence:"The concert was arranged for the <strong>delectation</strong> of the guests.",tip:"DE+LECT(吸引/享樂)+ATION=帶來享樂=愉悅",emoji:"😊",roots:["de","lect","ation"]},
    {word:"debunk",chinese:"揭穿/拆穿",sentence:"Scientists <strong>debunk</strong>ed the myth.",tip:"DE(去除)+BUNK(胡說)=去除胡說=揭穿",emoji:"🔍",roots:["de","bunk"]},
    {word:"decorous",chinese:"得體的/端莊的",sentence:"She maintained <strong>decorous</strong> behavior throughout.",tip:"DECOR(裝飾/禮節)+OUS=有禮節的=得體的",emoji:"🎩",roots:["decor","ous"]},
    {word:"deign",chinese:"屈尊/俯就",sentence:"She didn't <strong>deign</strong> to reply.",tip:"DEIGN=DIGN(尊嚴)=放下尊嚴=屈尊",emoji:"👸",roots:["deign"]},
    {word:"demur",chinese:"反對/提出異議",sentence:"She <strong>demur</strong>red at the suggestion.",tip:"DE(延遲)+MUR(拖延)=拖延不同意=反對",emoji:"🤔",roots:["de","mur"]},
    {word:"denizen",chinese:"居民/常客",sentence:"The forest is home to many wild <strong>denizen</strong>s.",tip:"DEN(裡面)+IZEN=住在裡面的=居民",emoji:"🏡",roots:["den","izen"]},
    {word:"desuetude",chinese:"廢棄/不用",sentence:"Many old laws have fallen into <strong>desuetude</strong>.",tip:"DE(離開)+SUET(習慣)+UDE=離開習慣=廢棄不用",emoji:"📜",roots:["de","suet","ude"]},
    {word:"dialectic",chinese:"辯證法/辯證的",sentence:"Hegelian <strong>dialectic</strong> involves thesis and antithesis.",tip:"DIA(穿過)+LECT(說)+IC=互相對說=辯證法",emoji:"🔄",roots:["dia","lect","ic"]},
    {word:"dilettantism",chinese:"一知半解/淺嘗輒止",sentence:"His <strong>dilettantism</strong> prevented deep expertise.",tip:"DILETT(享樂)+ANT+ISM=只為享樂的態度=淺嘗輒止",emoji:"🎨",roots:["dilett","ant","ism"]},
    {word:"disabuse",chinese:"糾正/消除錯誤觀念",sentence:"Let me <strong>disabuse</strong> you of that notion.",tip:"DIS(去除)+ABUSE(濫用/誤用)=去除誤用=糾正",emoji:"💡",roots:["dis","abuse"]},
    {word:"discursive",chinese:"離題的/散漫的",sentence:"His <strong>discursive</strong> essay jumped between topics.",tip:"DIS(分開)+CURS(跑)+IVE=跑來跑去的=離題的",emoji:"🔀",roots:["dis","curs","ive"]},
    {word:"dissemble",chinese:"掩飾/假裝",sentence:"She <strong>dissemble</strong>d her true feelings.",tip:"DIS(分開)+SEMBLE(似乎)=看似另一個樣子=掩飾",emoji:"🎭",roots:["dis","semble"]},
    {word:"dolorous",chinese:"悲傷的/憂鬱的",sentence:"She let out a <strong>dolorous</strong> cry.",tip:"DOLOR(痛苦)+OUS=充滿痛苦的=悲傷的",emoji:"😢",roots:["dolor","ous"]},
    {word:"doctrinaire",chinese:"教條主義的/空想的",sentence:"His <strong>doctrinaire</strong> approach ignored reality.",tip:"DOCTRINE(教條)+AIRE=堅持教條的人=教條主義的",emoji:"📕",roots:["doctrin","aire"]},
    {word:"duplicity",chinese:"口是心非/兩面派",sentence:"His <strong>duplicity</strong> was eventually exposed.",tip:"DUPLIC(雙重)+ITY=雙重面孔=口是心非",emoji:"🎭",roots:["duplic","ity"]},
    {word:"ebullience",chinese:"熱情奔放/活力",sentence:"Her <strong>ebullience</strong> is contagious.",tip:"E(出)+BULL(沸騰)+IENCE=沸騰出來的=熱情奔放",emoji:"🫧",roots:["e","bull","ience"]},
    {word:"ecumenical",chinese:"普世的/全基督教的",sentence:"The <strong>ecumenical</strong> movement promotes unity.",tip:"ECU(住)+MEN(全世界)+ICAL=全世界居住的=普世的",emoji:"🌍",roots:["ecu","men","ical"]},
    {word:"edifice",chinese:"大廈/宏偉建築",sentence:"The legal <strong>edifice</strong> took centuries to build.",tip:"EDIFIC(建造)+E=建造起來的=大廈",emoji:"🏛️",roots:["edif","ice"]},
    {word:"efface",chinese:"抹去/使不顯眼",sentence:"Time has <strong>efface</strong>d the inscription.",tip:"EF(出)+FACE(表面)=從表面除去=抹去",emoji:"🧹",roots:["ef","face"]},
    {word:"egoist",chinese:"自我主義者/利己者",sentence:"The <strong>egoist</strong> thinks only of himself.",tip:"EGO(自我)+IST(人)=以自我為中心的人",emoji:"🪞",roots:["ego","ist"]},
    {word:"emollient",chinese:"柔軟劑/安撫的",sentence:"Her <strong>emollient</strong> words calmed the situation.",tip:"E(出)+MOLL(軟)+IENT=使軟出來的=安撫的",emoji:"🧴",roots:["e","moll","ient"]},
    {word:"empiricism",chinese:"經驗主義",sentence:"Scientific <strong>empiricism</strong> relies on observation.",tip:"EMPIR(經驗)+ICISM=基於經驗的主義=經驗主義",emoji:"🔬",roots:["empir","ic","ism"]},
    {word:"endemic",chinese:"地方特有的/流行的",sentence:"The disease is <strong>endemic</strong> to this region.",tip:"EN(在裡面)+DEM(人民)+IC=在人群中的=地方流行的",emoji:"🦠",roots:["en","dem","ic"]},
    {word:"enfranchise",chinese:"給予選舉權/解放",sentence:"The amendment <strong>enfranchise</strong>d women voters.",tip:"EN(使)+FRANCHISE(自由/權利)=使有權利=給予選舉權",emoji:"🗳️",roots:["en","franch","ise"]},
    {word:"epigram",chinese:"警句/格言",sentence:"Oscar Wilde was famous for his <strong>epigram</strong>s.",tip:"EPI(在上面)+GRAM(寫)=寫在上面的短語=警句",emoji:"📝",roots:["epi","gram"]},
    {word:"epithet",chinese:"綽號/稱號",sentence:"The <strong>epithet</strong> \"the Great\" was given to Alexander.",tip:"EPI(在上面)+THET(放)=放在名字上面的=稱號",emoji:"🏷️",roots:["epi","thet"]},
    {word:"equivocate",chinese:"含糊其辭/模稜兩可",sentence:"The politician <strong>equivocate</strong>d when asked directly.",tip:"EQUI(相等)+VOC(聲音)+ATE=發出兩種聲音=含糊其辭",emoji:"🌫️",roots:["equi","voc","ate"]},
    {word:"ethos",chinese:"精神/風氣",sentence:"The company's <strong>ethos</strong> emphasizes innovation.",tip:"ETHOS=希臘語品格/精神=文化精神",emoji:"🏛️",roots:["eth","os"]},
    {word:"exculpatory",chinese:"開脫的/辯解的",sentence:"The <strong>exculpatory</strong> evidence cleared the defendant.",tip:"EX(出)+CULP(罪)+ATORY=從罪中出來的=開脫的",emoji:"⚖️",roots:["ex","culp","atory"]},
    {word:"exemplar",chinese:"典範/模範",sentence:"She is an <strong>exemplar</strong> of dedication.",tip:"EXEMPL(例子)+AR=作為例子的=典範",emoji:"⭐",roots:["exempl","ar"]},
    {word:"exhume",chinese:"掘出/發掘",sentence:"The body was <strong>exhume</strong>d for further examination.",tip:"EX(出)+HUME(土)=從土裡挖出來=掘出",emoji:"⛏️",roots:["ex","hume"]},
    {word:"expatriate",chinese:"移居國外者/放逐",sentence:"Many <strong>expatriate</strong>s live in the city.",tip:"EX(出)+PATRI(祖國)+ATE=離開祖國的=移居國外者",emoji:"🌍",roots:["ex","patri","ate"]},
    {word:"expediency",chinese:"權宜/方便",sentence:"He acted out of political <strong>expediency</strong>.",tip:"EX(出)+PED(腳)+IENCY=把腳伸出方便走=權宜",emoji:"🏃",roots:["ex","ped","iency"]},
    {word:"expostulate",chinese:"規勸/告誡",sentence:"She <strong>expostulate</strong>d with him about his spending.",tip:"EX(出)+POSTUL(要求)+ATE=向外要求改正=規勸",emoji:"☝️",roots:["ex","postul","ate"]},
    {word:"expurgate",chinese:"刪除/審查",sentence:"The publisher <strong>expurgate</strong>d offensive passages.",tip:"EX(出)+PURG(清潔)+ATE=清除出去=刪除",emoji:"✂️",roots:["ex","purg","ate"]},
    {word:"extemporize",chinese:"即興表演/即興發言",sentence:"The speaker had to <strong>extemporize</strong> when her notes were lost.",tip:"EX(出)+TEMPOR(時間)+IZE=超出準備時間=即興",emoji:"🎤",roots:["ex","tempor","ize"]},
    {word:"extrapolation",chinese:"推斷/外推",sentence:"The <strong>extrapolation</strong> suggests rapid growth.",tip:"EXTRA(外)+POL(推)+ATION=從已知推向外面=推斷",emoji:"📈",roots:["extra","pol","ation"]},
    {word:"fealty",chinese:"忠誠/效忠",sentence:"Knights swore <strong>fealty</strong> to the king.",tip:"FEAL(忠誠)+TY=忠誠的狀態=效忠",emoji:"⚔️",roots:["feal","ty"]},
    {word:"fecundity",chinese:"肥沃/多產",sentence:"The <strong>fecundity</strong> of the soil amazed farmers.",tip:"FEC(生產)+UND+ITY=不斷生產的能力=多產",emoji:"🌾",roots:["fec","und","ity"]},
    {word:"feign",chinese:"假裝/佯裝",sentence:"She <strong>feign</strong>ed surprise at the news.",tip:"FEIGN=假裝（和FAINT有關）=佯裝",emoji:"🎭",roots:["feign"]},
    {word:"firebrand",chinese:"煽動者/火把",sentence:"The political <strong>firebrand</strong> stirred up controversy.",tip:"FIRE(火)+BRAND(木頭)=點火的人=煽動者",emoji:"🔥",roots:["fire","brand"]},
    {word:"fissure",chinese:"裂縫/分裂",sentence:"A <strong>fissure</strong> appeared in the relationship.",tip:"FISS(裂開)+URE=裂開的=裂縫",emoji:"🔨",roots:["fiss","ure"]},
    {word:"flout",chinese:"蔑視/公然違反",sentence:"He <strong>flout</strong>ed the school rules openly.",tip:"FLOUT=FLOAT(漂浮)+OUT=飄在規則外面=蔑視",emoji:"🚫",roots:["flout"]},
    {word:"fracas",chinese:"喧鬧/爭吵",sentence:"A <strong>fracas</strong> broke out in the bar.",tip:"FRACAS=法語打破=喧鬧爭吵",emoji:"💥",roots:["frac","as"]},
    {word:"gambit",chinese:"策略/開局棄兵",sentence:"His opening <strong>gambit</strong> was a bold one.",tip:"GAMBIT=棋局中犧牲棋子的策略=策略",emoji:"♟️",roots:["gamb","it"]},
    {word:"glib",chinese:"油嘴滑舌的/膚淺的",sentence:"His <strong>glib</strong> answers didn't satisfy the committee.",tip:"GLIB=滑溜的嘴=油嘴滑舌的",emoji:"🗣️",roots:["glib"]},
    {word:"grandiose",chinese:"宏偉的/浮誇的",sentence:"His <strong>grandiose</strong> plans never materialized.",tip:"GRAND(大)+IOSE=過度大的=浮誇的",emoji:"🏰",roots:["grand","iose"]},
    {word:"heuristic",chinese:"啟發式的/探索的",sentence:"<strong>Heuristic</strong> methods help solve complex problems.",tip:"HEUR(發現)+ISTIC=用於發現的=啟發式的",emoji:"💡",roots:["heur","istic"]},
    {word:"hedonism",chinese:"享樂主義",sentence:"<strong>Hedonism</strong> prioritizes pleasure above all.",tip:"HEDON(快樂)+ISM=追求快樂的主義=享樂主義",emoji:"🎉",roots:["hedon","ism"]},
    {word:"homily",chinese:"訓誡/說教",sentence:"The priest delivered a brief <strong>homily</strong>.",tip:"HOMIL(群眾)+Y=對群眾說的話=訓誡",emoji:"📖",roots:["homil","y"]},
    {word:"hiatus",chinese:"間斷/空白期",sentence:"The band took a two-year <strong>hiatus</strong>.",tip:"HIATUS=拉丁語裂口=時間上的斷裂=間斷",emoji:"⏸️",roots:["hiat","us"]},
    {word:"iconography",chinese:"圖像學/象徵符號",sentence:"The <strong>iconography</strong> of the painting reveals hidden meaning.",tip:"ICONO(圖像)+GRAPH(寫/畫)+Y=研究圖像的=圖像學",emoji:"🖼️",roots:["icono","graph","y"]},
    {word:"idiomatic",chinese:"慣用的/地道的",sentence:"Her English is fluent and <strong>idiomatic</strong>.",tip:"IDIO(獨特)+MAT+IC=獨特的表達方式=慣用的",emoji:"🗣️",roots:["idio","mat","ic"]},
    {word:"ignominious",chinese:"可恥的/丟臉的",sentence:"The team suffered an <strong>ignominious</strong> defeat.",tip:"IG(不)+NOMIN(名)+IOUS=沒有好名聲的=可恥的",emoji:"😔",roots:["ig","nomin","ious"]},
    {word:"impervious",chinese:"不受影響的/不能滲透的",sentence:"The material is <strong>impervious</strong> to water.",tip:"IM(不)+PERV(穿過)+IOUS=穿不過的=不可滲透的",emoji:"🛡️",roots:["im","perv","ious"]},
    {word:"importune",chinese:"糾纏/再三請求",sentence:"Beggars <strong>importune</strong>d tourists for money.",tip:"IM(不)+PORT(港口/方便)+UNE=讓人不方便=糾纏",emoji:"🙏",roots:["im","port","une"]},
    {word:"imprimatur",chinese:"認可/許可",sentence:"The project received the director's <strong>imprimatur</strong>.",tip:"IM(讓)+PRIM(印)+ATUR=讓它印出來=許可",emoji:"✅",roots:["im","prim","atur"]},
    {word:"incendiary",chinese:"煽動性的/縱火的",sentence:"The <strong>incendiary</strong> remarks sparked protests.",tip:"IN(向)+CEND(燃燒)+IARY=向裡面點火的=煽動性的",emoji:"🔥",roots:["in","cend","iary"]},
    {word:"incognito",chinese:"隱姓埋名的",sentence:"The celebrity traveled <strong>incognito</strong>.",tip:"IN(不)+COGNIT(知道)+O=不被認出的=隱姓埋名",emoji:"🕶️",roots:["in","cognit","o"]},
    {word:"indefatigable",chinese:"不知疲倦的/堅持不懈的",sentence:"Her <strong>indefatigable</strong> efforts won admiration.",tip:"IN(不)+DE(完全)+FATIG(疲倦)+ABLE=不會疲倦的",emoji:"💪",roots:["in","de","fatig","able"]},
    {word:"indictment",chinese:"起訴/控告",sentence:"The <strong>indictment</strong> listed multiple charges.",tip:"IN(向)+DICT(說/宣布)+MENT=向某人宣布罪狀=起訴",emoji:"⚖️",roots:["in","dict","ment"]},
    {word:"indomitable",chinese:"不屈不撓的/堅強的",sentence:"Her <strong>indomitable</strong> spirit overcame all obstacles.",tip:"IN(不)+DOMIT(馴服)+ABLE=不能被馴服的=不屈的",emoji:"💪",roots:["in","domit","able"]},
    {word:"insipid",chinese:"平淡無味的/乏味的",sentence:"The food was bland and <strong>insipid</strong>.",tip:"IN(不)+SIPID(味道)=沒有味道的=乏味的",emoji:"😐",roots:["in","sipid"]},
    {word:"internecine",chinese:"兩敗俱傷的/內鬥的",sentence:"<strong>Internecine</strong> conflicts weakened the organization.",tip:"INTER(互相)+NEC(殺)+INE=互相殘殺的=兩敗俱傷",emoji:"⚔️",roots:["inter","nec","ine"]},
    {word:"interpolation",chinese:"插入/內插",sentence:"The <strong>interpolation</strong> of new data improved the model.",tip:"INTER(之間)+POL(光滑)+ATION=在之間使光滑=插入",emoji:"📊",roots:["inter","pol","ation"]},
    {word:"inure",chinese:"使習慣/使適應",sentence:"Years of hardship <strong>inure</strong>d her to suffering.",tip:"IN(進入)+URE(使用)=使進入習慣使用=使適應",emoji:"💪",roots:["in","ure"]},
    {word:"inveigh",chinese:"猛烈抨擊/痛罵",sentence:"He <strong>inveigh</strong>ed against corruption.",tip:"IN(向)+VEIGH(攻擊)=向著攻擊=猛烈抨擊",emoji:"😤",roots:["in","veigh"]},
    {word:"jejune",chinese:"枯燥的/幼稚的",sentence:"His <strong>jejune</strong> remarks added nothing to the debate.",tip:"JEJUN(空腹)+E=空腹般空虛的=枯燥的",emoji:"😐",roots:["jejun","e"]},
    {word:"laud",chinese:"讚美/稱讚",sentence:"Critics <strong>laud</strong>ed the film for its originality.",tip:"LAUD=讚美（和APPLAUD鼓掌有關）",emoji:"👏",roots:["laud"]},
    {word:"limpid",chinese:"清澈的/簡明的",sentence:"The lake has <strong>limpid</strong> blue water.",tip:"LIMP(清澈)+ID=清清澈澈的=清澈的",emoji:"💎",roots:["limp","id"]},
    {word:"machination",chinese:"陰謀/詭計",sentence:"His <strong>machination</strong>s were finally exposed.",tip:"MACHIN(機器/詭計)+ATION=像機器運轉的陰謀",emoji:"⚙️",roots:["machin","ation"]},
    {word:"maelstrom",chinese:"大漩渦/混亂局面",sentence:"The country was caught in a political <strong>maelstrom</strong>.",tip:"MAEL(磨)+STROM(水流)=磨碎一切的水流=大漩渦",emoji:"🌀",roots:["mael","strom"]},
    {word:"martinet",chinese:"嚴格紀律者/死板的人",sentence:"The new manager is a real <strong>martinet</strong>.",tip:"以法國軍官Martinet命名=嚴格執行紀律的人",emoji:"👮",roots:["martin","et"]},
    {word:"mawkish",chinese:"多愁善感的/令人作嘔的",sentence:"The film was criticized for its <strong>mawkish</strong> sentimentality.",tip:"MAWK(蛆)+ISH=像蛆一樣令人不適=過度感傷的",emoji:"🤢",roots:["mawk","ish"]},
    {word:"mercurial",chinese:"善變的/活潑的",sentence:"Her <strong>mercurial</strong> temperament made her unpredictable.",tip:"MERCUR(水銀/墨丘利)+IAL=像水銀一樣變化的=善變的",emoji:"💨",roots:["mercur","ial"]},
    {word:"misnomer",chinese:"用詞不當/名不副實",sentence:"Calling it a \"lake\" is a <strong>misnomer</strong>; it is more of a pond.",tip:"MIS(錯)+NOMER(名字)=錯誤的名字=名不副實",emoji:"❌",roots:["mis","nomer"]},
    {word:"moratorium",chinese:"暫停/延期",sentence:"The government declared a <strong>moratorium</strong> on nuclear testing.",tip:"MORAT(延遲)+ORIUM(地方)=延遲的狀態=暫停",emoji:"⏸️",roots:["morat","orium"]},
    {word:"necromancy",chinese:"巫術/通靈術",sentence:"Medieval tales often involve <strong>necromancy</strong>.",tip:"NECRO(死)+MANCY(占卜)=用死者占卜=巫術",emoji:"💀",roots:["necro","mancy"]},
    {word:"nihilism",chinese:"虛無主義",sentence:"<strong>Nihilism</strong> rejects all moral and religious principles.",tip:"NIHIL(虛無)+ISM=認為一切虛無的主義",emoji:"⚫",roots:["nihil","ism"]},
    {word:"nomenclature",chinese:"命名法/術語體系",sentence:"The <strong>nomenclature</strong> of chemistry follows specific rules.",tip:"NOMEN(名字)+CLAT(叫)+URE=叫名字的系統=命名法",emoji:"🏷️",roots:["nomen","clat","ure"]},
    {word:"non sequitur",chinese:"不合邏輯的推論",sentence:"His argument is a <strong>non sequitur</strong>.",tip:"NON(不)+SEQUITUR(跟隨)=不跟隨前提的=不合邏輯",emoji:"🤔",roots:["non","sequitur"]},
    {word:"obeisance",chinese:"鞠躬/敬意",sentence:"The courtiers paid <strong>obeisance</strong> to the king.",tip:"OBEI(服從)+SANCE=表示服從的動作=鞠躬",emoji:"🙇",roots:["obei","sance"]},
    {word:"oblique",chinese:"斜的/間接的",sentence:"He made an <strong>oblique</strong> reference to the scandal.",tip:"OB(對)+LIQUE(傾斜)=傾斜的=間接的",emoji:"↗️",roots:["ob","lique"]},
    {word:"onus",chinese:"責任/義務",sentence:"The <strong>onus</strong> is on you to prove your claims.",tip:"ONUS=拉丁語負擔=責任",emoji:"💼",roots:["on","us"]},
    {word:"ontological",chinese:"本體論的",sentence:"The philosopher raised <strong>ontological</strong> questions about existence.",tip:"ONTO(存在)+LOG(學)+ICAL=關於存在的學問=本體論的",emoji:"🧠",roots:["onto","log","ical"]},
    {word:"opprobrious",chinese:"辱罵的/可恥的",sentence:"He used <strong>opprobrious</strong> language against his critic.",tip:"OP(對)+PROBR(恥辱)+IOUS=對人施加恥辱的=辱罵的",emoji:"😤",roots:["op","probr","ious"]},
    {word:"overture",chinese:"序曲/提議",sentence:"The company made <strong>overture</strong>s toward a merger.",tip:"OVERT(打開)+URE=打開序幕=序曲/初步提議",emoji:"🎵",roots:["over","ture"]},
    {word:"paradigmatic",chinese:"範式的/典範的",sentence:"This case is <strong>paradigmatic</strong> of the problem.",tip:"PARADIGM(典範)+ATIC=作為典範的=範式的",emoji:"📐",roots:["para","digm","atic"]},
    {word:"parse",chinese:"解析/分析",sentence:"Let's <strong>parse</strong> this sentence grammatically.",tip:"PARSE=把句子分開解析=分析",emoji:"🔍",roots:["parse"]},
    {word:"pedagogical",chinese:"教學的/教育學的",sentence:"New <strong>pedagogical</strong> methods improve learning.",tip:"PED(兒童)+AGOG(引導)+ICAL=引導兒童的=教學的",emoji:"👨‍🏫",roots:["ped","agog","ical"]},
    {word:"pejorative",chinese:"貶義的/輕蔑的",sentence:"The term has <strong>pejorative</strong> connotations.",tip:"PEJOR(更壞)+ATIVE=使更壞的=貶義的",emoji:"👎",roots:["pejor","ative"]},
    {word:"penultimate",chinese:"倒數第二的",sentence:"We are on the <strong>penultimate</strong> chapter.",tip:"PEN(幾乎)+ULTIMATE(最後)=幾乎最後=倒數第二",emoji:"2️⃣",roots:["pen","ultim","ate"]},
    {word:"perquisite",chinese:"額外收入/津貼",sentence:"Free travel is a <strong>perquisite</strong> of the job.",tip:"PER(完全)+QUIS(尋求)+ITE=額外尋求到的=津貼",emoji:"💰",roots:["per","quis","ite"]},
    {word:"philistine",chinese:"庸俗之人/不懂藝術者",sentence:"He dismissed them as cultural <strong>philistine</strong>s.",tip:"PHILISTINE=聖經中非利士人=不懂文化的人",emoji:"😤",roots:["philist","ine"]},
    {word:"polity",chinese:"政體/政治組織",sentence:"A democratic <strong>polity</strong> requires informed citizens.",tip:"POLIT(城邦)+Y=城邦的組織=政體",emoji:"🏛️",roots:["polit","y"]},
    {word:"pontificate",chinese:"說教/自以為是地講話",sentence:"He loves to <strong>pontificate</strong> on politics.",tip:"PONTIFIC(教皇)+ATE=像教皇一樣說話=說教",emoji:"🎤",roots:["pontific","ate"]},
    {word:"portend",chinese:"預示/預兆",sentence:"Dark clouds <strong>portend</strong> a storm.",tip:"PORT(前)+END(伸展)=向前伸展預示=預兆",emoji:"⛈️",roots:["port","end"]},
    {word:"postmortem",chinese:"事後分析/驗屍",sentence:"The team conducted a <strong>postmortem</strong> on the failed project.",tip:"POST(之後)+MORTEM(死亡)=死後的分析=事後檢討",emoji:"🔍",roots:["post","mortem"]},
    {word:"precursor",chinese:"先驅/前兆",sentence:"This technology is a <strong>precursor</strong> to AI.",tip:"PRE(前)+CURS(跑)+OR=跑在前面的=先驅",emoji:"🏃",roots:["pre","curs","or"]},
    {word:"prig",chinese:"一本正經的人/假正經",sentence:"Don't be such a <strong>prig</strong> about table manners.",tip:"PRIG=自以為道德高尚的人=假正經",emoji:"🤓",roots:["prig"]},
    {word:"primordial",chinese:"原始的/最初的",sentence:"<strong>Primordial</strong> soup may have given rise to life.",tip:"PRIM(第一)+ORD(開始)+IAL=最初開始的=原始的",emoji:"🌍",roots:["prim","ord","ial"]},
    {word:"puerile",chinese:"幼稚的/孩子氣的",sentence:"His <strong>puerile</strong> behavior embarrassed his colleagues.",tip:"PUER(男孩)+ILE=像小男孩一樣的=幼稚的",emoji:"👶",roots:["puer","ile"]},
    {word:"pulchritude",chinese:"美麗/美貌",sentence:"The <strong>pulchritude</strong> of the landscape amazed visitors.",tip:"PULCHR(美)+ITUDE=美麗的狀態=美貌",emoji:"🌹",roots:["pulchr","itude"]},
    {word:"putative",chinese:"公認的/假定的",sentence:"The <strong>putative</strong> father denied paternity.",tip:"PUT(認為)+ATIVE=被認為的=假定的",emoji:"🤔",roots:["put","ative"]},
    {word:"quotidian",chinese:"日常的/平凡的",sentence:"The novel captures the <strong>quotidian</strong> details of life.",tip:"QUOTID(每天)+IAN=每天的=日常的",emoji:"📅",roots:["quotid","ian"]},
    {word:"rapprochement",chinese:"和解/恢復友好關係",sentence:"The two nations achieved <strong>rapprochement</strong>.",tip:"RE(再)+AP(向)+PROCH(接近)+MENT=再次靠近=和解",emoji:"🤝",roots:["rap","proche","ment"]},
    {word:"recidivism",chinese:"累犯/再犯",sentence:"Programs aim to reduce <strong>recidivism</strong>.",tip:"RE(回)+CID(落)+IVISM=再次落回犯罪=累犯",emoji:"🔄",roots:["re","cidiv","ism"]},
    {word:"remiss",chinese:"疏忽的/不負責的",sentence:"It would be <strong>remiss</strong> of me not to mention this.",tip:"RE(回)+MISS(放)=放回去不管=疏忽的",emoji:"🤷",roots:["re","miss"]},
    {word:"repartee",chinese:"機智的回答/妙語",sentence:"Her quick <strong>repartee</strong> delighted the audience.",tip:"RE(回)+PART(出發)+EE=迅速回擊出去=機智回答",emoji:"⚡",roots:["re","part","ee"]},
    {word:"reprise",chinese:"重演/重複",sentence:"The orchestra played a <strong>reprise</strong> of the opening theme.",tip:"RE(再)+PRISE(拿)=再拿出來演=重演",emoji:"🎵",roots:["re","prise"]},
    {word:"sanguinary",chinese:"血腥的/嗜殺的",sentence:"The <strong>sanguinary</strong> battle left thousands dead.",tip:"SANGUIN(血)+ARY=充滿血的=血腥的",emoji:"🩸",roots:["sanguin","ary"]},
    {word:"sapient",chinese:"智慧的/有見識的",sentence:"The <strong>sapient</strong> elder offered wise counsel.",tip:"SAP(智慧)+IENT=有智慧的=睿智的",emoji:"🦉",roots:["sap","ient"]},
    {word:"simulacrum",chinese:"幻象/表象",sentence:"The theme park is a <strong>simulacrum</strong> of reality.",tip:"SIMUL(模擬)+ACRUM=模擬出來的東西=幻象",emoji:"🎭",roots:["simul","acrum"]},
    {word:"solecism",chinese:"語法錯誤/失禮",sentence:"Using \"ain't\" is considered a <strong>solecism</strong>.",tip:"SOLEC(索利城)+ISM=索利城人說的壞希臘語=語病",emoji:"❌",roots:["solec","ism"]},
    {word:"solipsism",chinese:"唯我論/自我中心",sentence:"His extreme <strong>solipsism</strong> blinded him to others' needs.",tip:"SOL(獨自)+IPS(自己)+ISM=只有自己的主義=唯我論",emoji:"🪞",roots:["sol","ips","ism"]},
    {word:"sophistry",chinese:"詭辯/似是而非的推理",sentence:"His argument is mere <strong>sophistry</strong>.",tip:"SOPH(智慧)+ISTRY=假裝智慧的=詭辯",emoji:"🎭",roots:["soph","istry"]},
    {word:"taciturn",chinese:"沉默寡言的",sentence:"The <strong>taciturn</strong> man rarely spoke at meetings.",tip:"TACIT(沉默)+URN=保持沉默的=沉默寡言的",emoji:"🤐",roots:["tacit","urn"]},
    {word:"temerity",chinese:"魯莽/膽大妄為",sentence:"He had the <strong>temerity</strong> to question the CEO.",tip:"TEMER(魯莽)+ITY=魯莽的性質=膽大妄為",emoji:"😱",roots:["temer","ity"]},
    {word:"tome",chinese:"大部頭著作/巨著",sentence:"She authored a scholarly <strong>tome</strong> on ancient history.",tip:"TOME=希臘語切片(知識的切片)=厚書",emoji:"📚",roots:["tome"]},
    {word:"trope",chinese:"修辭/比喻手法",sentence:"The chosen-one <strong>trope</strong> is common in fantasy.",tip:"TROPE=希臘語轉向=修辭中的轉義=比喻",emoji:"📝",roots:["trope"]},
    {word:"veracious",chinese:"誠實的/真實的",sentence:"A <strong>veracious</strong> account of events was published.",tip:"VER(真)+ACIOUS=充滿真實的=誠實的",emoji:"✅",roots:["ver","acious"]},
    {word:"vestige",chinese:"痕跡/遺跡",sentence:"Only <strong>vestige</strong>s of the ancient city remain.",tip:"VESTIG(足跡)+E=留下的足跡=痕跡",emoji:"👣",roots:["vestig","e"]},
    {word:"vicarious",chinese:"間接感受的/替代的",sentence:"She experienced <strong>vicarious</strong> thrill from the movie.",tip:"VICAR(代理)+IOUS=通過代理體驗的=間接感受的",emoji:"🎬",roots:["vicar","ious"]},
    {word:"virtuoso",chinese:"藝術大師/演奏大師",sentence:"The pianist is a true <strong>virtuoso</strong>.",tip:"VIRTU(精通)+OSO=精通藝術的人=大師",emoji:"🎹",roots:["virtu","oso"]},
    {word:"voluminous",chinese:"大量的/厚重的",sentence:"She compiled <strong>voluminous</strong> research notes.",tip:"VOLUM(卷)+INOUS=很多卷的=大量的",emoji:"📚",roots:["volum","inous"]},
    {word:"waif",chinese:"流浪兒/無家可歸者",sentence:"The <strong>waif</strong> wandered the streets alone.",tip:"WAIF=古法語被遺棄的人=流浪兒",emoji:"😢",roots:["waif"]},
    {word:"wraith",chinese:"幽靈/鬼魂",sentence:"A pale <strong>wraith</strong> appeared in the doorway.",tip:"WRAITH=蘇格蘭語幽靈=鬼魂",emoji:"👻",roots:["wraith"]},
    {word:"xenophobia",chinese:"仇外/排外",sentence:"<strong>Xenophobia</strong> leads to discrimination.",tip:"XENO(外國)+PHOBIA(恐懼)=對外國的恐懼=仇外",emoji:"🚫",roots:["xeno","phobia"]},
    {word:"zeitgeist",chinese:"時代精神",sentence:"The film captures the <strong>zeitgeist</strong> of the 1960s.",tip:"ZEIT(時間)+GEIST(精神)=時間的精神=時代精神",emoji:"🌍",roots:["zeit","geist"]},
    {word:"apostate",chinese:"叛教者/變節者",sentence:"The <strong>apostate</strong> was shunned by his former community.",tip:"APO(離開)+STATE(站)=站到外面去的=叛教者",emoji:"🚶",roots:["apo","state"]},
    {word:"truculence",chinese:"兇猛/好鬥",sentence:"His <strong>truculence</strong> made negotiations impossible.",tip:"TRUC(兇猛)+UL+ENCE=兇猛的狀態=好鬥",emoji:"😠",roots:["truc","ul","ence"]},
    {word:"bilious",chinese:"壞脾氣的/膽汁過多的",sentence:"He was in a <strong>bilious</strong> mood all morning.",tip:"BIL(膽汁)+IOUS=膽汁多的=脾氣壞的",emoji:"😤",roots:["bil","ious"]},
    {word:"boorish",chinese:"粗野的/不文明的",sentence:"His <strong>boorish</strong> behavior offended everyone.",tip:"BOOR(粗人)+ISH=像粗人一樣的=粗野的",emoji:"😤",roots:["boor","ish"]},
    {word:"callow",chinese:"不成熟的/乳臭未乾的",sentence:"The <strong>callow</strong> recruit had much to learn.",tip:"CALLOW=像剛出殼的雛鳥一樣沒經驗",emoji:"🐣",roots:["callow"]},
    {word:"canard",chinese:"謠言/假消息",sentence:"The story turned out to be a <strong>canard</strong>.",tip:"CANARD=法語鴨子=像鴨子叫一樣的謠言",emoji:"🦆",roots:["can","ard"]},
    {word:"cant",chinese:"偽善之言/行話",sentence:"His speech was full of political <strong>cant</strong>.",tip:"CANT=唱歌般的空洞話語=偽善之言",emoji:"🎭",roots:["cant"]},
    {word:"captious",chinese:"吹毛求疵的/挑剔的",sentence:"The <strong>captious</strong> critic found fault with everything.",tip:"CAPT(抓)+IOUS=總想抓住毛病的=吹毛求疵",emoji:"🔍",roots:["capt","ious"]},
    {word:"cogent",chinese:"有說服力的/令人信服的",sentence:"She presented a <strong>cogent</strong> argument for reform.",tip:"COG(思考)+ENT=經過深思的=有說服力的",emoji:"💡",roots:["cog","ent"]},
    {word:"compatriot",chinese:"同胞/同國人",sentence:"She greeted her <strong>compatriot</strong> warmly abroad.",tip:"COM(一起)+PATRI(祖國)+OT=同一祖國的人=同胞",emoji:"🤝",roots:["com","patri","ot"]},
    {word:"compliant",chinese:"順從的/遵守的",sentence:"The software is fully <strong>compliant</strong> with regulations.",tip:"COM(完全)+PLI(摺)+ANT=完全摺疊順從的=遵守的",emoji:"✅",roots:["com","pli","ant"]},
    {word:"confute",chinese:"駁斥/證明有誤",sentence:"The scientist <strong>confute</strong>d the old theory.",tip:"CON(完全)+FUTE(打敗)=完全打敗論點=駁斥",emoji:"🥊",roots:["con","fute"]},
    {word:"consanguinity",chinese:"血親關係/同族",sentence:"Laws prohibit marriage between those of close <strong>consanguinity</strong>.",tip:"CON(一起)+SANGUIN(血)+ITY=同血的=血親關係",emoji:"🩸",roots:["con","sanguin","ity"]},
    {word:"contumely",chinese:"傲慢的侮辱/蔑視",sentence:"He endured <strong>contumely</strong> from his rivals.",tip:"CON(完全)+TUMEL(膨脹)=膨脹的傲慢=侮辱",emoji:"😤",roots:["con","tumel","y"]},
    {word:"coquette",chinese:"賣弄風情的女人/調情者",sentence:"She played the <strong>coquette</strong> at the party.",tip:"COQ(公雞)+ETTE(小)=像小公雞賣弄=賣弄風情",emoji:"💃",roots:["coqu","ette"]},
    {word:"curmudgeon",chinese:"脾氣壞的人/吝嗇鬼",sentence:"The old <strong>curmudgeon</strong> chased kids off his lawn.",tip:"CUR(狗)+MUDGEON=像老狗一樣愛生氣=壞脾氣的人",emoji:"😠",roots:["cur","mudgeon"]},
    {word:"declivity",chinese:"下坡/傾斜",sentence:"The road runs down a steep <strong>declivity</strong>.",tip:"DE(向下)+CLIV(傾斜)+ITY=向下傾斜的=下坡",emoji:"⬇️",roots:["de","cliv","ity"]},
    {word:"demotic",chinese:"通俗的/民眾的",sentence:"The author writes in a <strong>demotic</strong> style.",tip:"DEMO(人民)+TIC=屬於人民的=通俗的",emoji:"🗣️",roots:["demo","tic"]},
    {word:"desiccate",chinese:"使乾燥/脫水",sentence:"The sun <strong>desiccate</strong>d the exposed soil.",tip:"DE(完全)+SICC(乾)+ATE=使完全乾燥=脫水",emoji:"☀️",roots:["de","sicc","ate"]},
    {word:"despotic",chinese:"專制的/暴虐的",sentence:"The <strong>despotic</strong> ruler crushed all opposition.",tip:"DESPOT(暴君)+IC=像暴君一樣的=專制的",emoji:"👑",roots:["despot","ic"]},
    {word:"embezzle",chinese:"挪用/盜用公款",sentence:"He <strong>embezzle</strong>d millions from the company.",tip:"EM(使)+BEZZLE(揮霍)=把別人的錢揮霍=盜用公款",emoji:"💸",roots:["em","bezzle"]},
    {word:"emissary",chinese:"使者/特使",sentence:"The king sent an <strong>emissary</strong> to negotiate peace.",tip:"E(出)+MISS(送)+ARY=被送出去的人=使者",emoji:"🕊️",roots:["e","miss","ary"]},
    {word:"empirical",chinese:"經驗主義的/實證的",sentence:"The claim lacks <strong>empirical</strong> evidence.",tip:"EMPIR(經驗)+ICAL=基於經驗的=實證的",emoji:"🔬",roots:["empir","ical"]},
    {word:"errant",chinese:"犯錯的/遊蕩的",sentence:"The <strong>errant</strong> knight wandered the countryside.",tip:"ERR(錯誤/遊走)+ANT=走錯路的/到處走的=遊蕩的",emoji:"🗡️",roots:["err","ant"]},
    {word:"exalt",chinese:"提升/讚揚",sentence:"The poem <strong>exalt</strong>s the beauty of nature.",tip:"EX(向上)+ALT(高)=往高處提=提升/讚揚",emoji:"⬆️",roots:["ex","alt"]},
    {word:"fiduciary",chinese:"信託的/受信任的",sentence:"The trustee has a <strong>fiduciary</strong> duty.",tip:"FIDUC(信任)+IARY=基於信任的=信託的",emoji:"🤝",roots:["fiduc","iary"]},
    {word:"flagitious",chinese:"極惡的/罪惡昭彰的",sentence:"The <strong>flagitious</strong> crime shocked the nation.",tip:"FLAGIT(恥辱)+IOUS=極度恥辱的=極惡的",emoji:"💀",roots:["flagit","ious"]},
    {word:"garrulity",chinese:"饒舌/話多",sentence:"His <strong>garrulity</strong> tested everyone's patience.",tip:"GARR(喋喋不休)+UL+ITY=喋喋不休的狀態=話多",emoji:"🗣️",roots:["garr","ul","ity"]},
    {word:"gestation",chinese:"懷孕期/醞釀",sentence:"The project had a long <strong>gestation</strong> period.",tip:"GEST(懷孕)+ATION=懷孕的過程=醞釀期",emoji:"🤰",roots:["gest","ation"]},
    {word:"gossamer",chinese:"薄紗般的/纖細的",sentence:"The <strong>gossamer</strong> wings of the dragonfly shimmered.",tip:"GOOSE+SUMMER=仲夏的蜘蛛絲=薄紗般纖細的",emoji:"🕸️",roots:["goss","amer"]},
    {word:"hagiographic",chinese:"聖徒傳式的/過分讚美的",sentence:"The biography is too <strong>hagiographic</strong>.",tip:"HAGIO(聖人)+GRAPH(寫)+IC=像寫聖人一樣=過分讚美",emoji:"😇",roots:["hagio","graph","ic"]},
    {word:"untoward",chinese:"不幸的/不利的",sentence:"Nothing <strong>untoward</strong> happened during the event.",tip:"UN(不)+TOWARD(朝向好的)=不朝向好的=不利的",emoji:"⚠️",roots:["un","toward"]},
    {word:"incandescent",chinese:"白熾的/光輝燦爛的",sentence:"The sunset was <strong>incandescent</strong>.",tip:"IN(向裡)+CAND(發光)+ESCENT=發出白光的=光輝的",emoji:"💡",roots:["in","cand","escent"]},
    {word:"insouciance",chinese:"漫不經心/無所謂",sentence:"She faced the challenge with characteristic <strong>insouciance</strong>.",tip:"IN(不)+SOUCI(擔心)+ANCE=不擔心的態度=漫不經心",emoji:"😎",roots:["in","souci","ance"]},
    {word:"lugubrious",chinese:"悲哀的/陰鬱的",sentence:"The <strong>lugubrious</strong> music matched the rainy day.",tip:"LUGUBR(哀悼)+IOUS=充滿哀悼的=悲哀的",emoji:"😢",roots:["lugubr","ious"]},
    {word:"machiavellian",chinese:"權術的/不擇手段的",sentence:"His <strong>machiavellian</strong> tactics alienated allies.",tip:"以馬基維利(Machiavelli)命名=不擇手段的",emoji:"🐍",roots:["machiavell","ian"]},
    {word:"magnate",chinese:"大亨/巨頭",sentence:"The media <strong>magnate</strong> owns several newspapers.",tip:"MAGN(大)+ATE=大人物=大亨",emoji:"💼",roots:["magn","ate"]},
    {word:"sycophancy",chinese:"諂媚/拍馬屁",sentence:"The court was rife with <strong>sycophancy</strong>.",tip:"SYCO(無花果)+PHANCY(展示)=展示無花果討好=諂媚",emoji:"🙇",roots:["syco","phan","cy"]}
  ]
};
