WORD_DATA["competition_upper"] = {

    name: "公館高年級",
    color: "#8b5cf6",
    words: [
      {word:"nurse",chinese:"護士",sentence:"The <strong>nurse</strong> takes care of me.",tip:"NURSE 和 PURSE 押韻",emoji:"👩‍⚕️",roots:["nurse"]},
      {word:"singer",chinese:"歌手",sentence:"She is a famous <strong>singer</strong>.",tip:"SINGER = SING + ER（唱歌的人）",emoji:"🎤",roots:["sing","er"]},
      {word:"police officer",chinese:"警察",sentence:"The <strong>police officer</strong> helps people.",tip:"比 policeman 更正式",emoji:"👮",roots:["po","lice"," ","off","i","cer"]},
      {word:"mailman",chinese:"郵差",sentence:"The <strong>mailman</strong> brings letters.",tip:"MAILMAN = MAIL + MAN",emoji:"📮",roots:["mail","man"]},
      {word:"uncle",chinese:"叔叔/伯伯",sentence:"My <strong>uncle</strong> lives in Taipei.",tip:"UNCLE 的 UN 發 /ʌŋ/ 的音",emoji:"👨",roots:["un","cle"]},
      {word:"aunt",chinese:"阿姨/姑姑",sentence:"My <strong>aunt</strong> gives me candy.",tip:"AUNT 美式發 /ænt/",emoji:"👩",roots:["aunt"]},
      {word:"pink",chinese:"粉紅色",sentence:"I like <strong>pink</strong> flowers.",tip:"PINK 和 THINK 押韻",emoji:"💗",roots:["pink"]},
      {word:"brown",chinese:"棕色",sentence:"The tree is <strong>brown</strong>.",tip:"BROWN 和 DOWN 押韻",emoji:"🟤",roots:["brown"]},
      {word:"gray",chinese:"灰色",sentence:"The sky is <strong>gray</strong> today.",tip:"GRAY（美式）= GREY（英式）",emoji:"🩶",roots:["gray"]},
      {word:"purple",chinese:"紫色",sentence:"I have a <strong>purple</strong> bag.",tip:"PURPLE 有兩個 P",emoji:"🟣",roots:["pur","ple"]},
      {word:"bread",chinese:"麵包",sentence:"I eat <strong>bread</strong> for breakfast.",tip:"BREAD 的 EA 發短音 /e/",emoji:"🍞",roots:["bread"]},
      {word:"breakfast",chinese:"早餐",sentence:"I eat eggs for <strong>breakfast</strong>.",tip:"BREAKFAST = BREAK + FAST（打破禁食）",emoji:"🥞",roots:["break","fast"]},
      {word:"coffee",chinese:"咖啡",sentence:"Dad drinks <strong>coffee</strong> every morning.",tip:"COFFEE 有兩個 F 和兩個 E",emoji:"☕",roots:["cof","fee"]},
      {word:"cookies",chinese:"餅乾",sentence:"Mom makes <strong>cookies</strong> for us.",tip:"COOKIES = COOK + IES",emoji:"🍪",roots:["cook","ies"]},
      {word:"dinner",chinese:"晚餐",sentence:"We have <strong>dinner</strong> at six.",tip:"DINNER 有兩個 N",emoji:"🍽️",roots:["din","ner"]},
      {word:"food",chinese:"食物",sentence:"I like Chinese <strong>food</strong>.",tip:"FOOD 有兩個 O",emoji:"🍲",roots:["food"]},
      {word:"fruit",chinese:"水果",sentence:"I eat <strong>fruit</strong> every day.",tip:"FRUIT 的 UI 發 /u:/ 的音",emoji:"🍇",roots:["fruit"]},
      {word:"lunch",chinese:"午餐",sentence:"We have <strong>lunch</strong> at noon.",tip:"LUNCH 和 BUNCH 押韻",emoji:"🥪",roots:["lunch"]},
      {word:"noodles",chinese:"麵條",sentence:"I like <strong>noodles</strong> with soup.",tip:"NOODLES 有兩個 O",emoji:"🍜",roots:["noo","dles"]},
      {word:"sandwich",chinese:"三明治",sentence:"I make a <strong>sandwich</strong> for lunch.",tip:"三明治是伯爵的名字！",emoji:"🥪",roots:["sand","wich"]},
      {word:"soup",chinese:"湯",sentence:"This <strong>soup</strong> is very hot.",tip:"SOUP 和 GROUP 押韻",emoji:"🍲",roots:["soup"]},
      {word:"candy",chinese:"糖果",sentence:"Don't eat too much <strong>candy</strong>.",tip:"CANDY 和 HANDY 押韻",emoji:"🍬",roots:["can","dy"]},
      {word:"pie",chinese:"派",sentence:"Mom makes apple <strong>pie</strong>.",tip:"PIE 和 FLY 押韻",emoji:"🥧",roots:["pie"]},
      {word:"moon",chinese:"月亮",sentence:"The <strong>moon</strong> is bright tonight.",tip:"MOON 有兩個 O",emoji:"🌙",roots:["moon"]},
      {word:"sky",chinese:"天空",sentence:"The <strong>sky</strong> is blue.",tip:"SKY 和 FLY 押韻",emoji:"🌌",roots:["sky"]},
      {word:"star",chinese:"星星",sentence:"I can see many <strong>star</strong>s at night.",tip:"STAR 和 CAR 押韻",emoji:"⭐",roots:["star"]},
      {word:"sun",chinese:"太陽",sentence:"The <strong>sun</strong> rises in the east.",tip:"SUN 和 FUN 押韻",emoji:"☀️",roots:["sun"]},
      {word:"tree",chinese:"樹",sentence:"The <strong>tree</strong> is very tall.",tip:"TREE 有兩個 E",emoji:"🌳",roots:["tree"]},
      {word:"flower",chinese:"花",sentence:"The <strong>flower</strong> smells nice.",tip:"FLOWER = FLOW + ER",emoji:"🌸",roots:["flow","er"]},
      {word:"spring",chinese:"春天",sentence:"Flowers bloom in <strong>spring</strong>.",tip:"SPRING 也有彈簧的意思",emoji:"🌷",roots:["spring"]},
      {word:"summer",chinese:"夏天",sentence:"I swim in <strong>summer</strong>.",tip:"SUMMER 有兩個 M",emoji:"🌞",roots:["sum","mer"]},
      {word:"fall",chinese:"秋天",sentence:"Leaves change color in <strong>fall</strong>.",tip:"FALL 也有跌倒的意思",emoji:"🍂",roots:["fall"]},
      {word:"winter",chinese:"冬天",sentence:"It snows in <strong>winter</strong>.",tip:"WINTER = WIN + TER",emoji:"❄️",roots:["win","ter"]},
      {word:"here",chinese:"這裡",sentence:"Come <strong>here</strong>, please.",tip:"HERE 和 THERE 是相反詞",emoji:"📍",roots:["here"]},
      {word:"there",chinese:"那裡",sentence:"The cat is over <strong>there</strong>.",tip:"THERE 和 HERE 是相反詞",emoji:"👉",roots:["there"]},
      {word:"shop",chinese:"商店",sentence:"I go to the <strong>shop</strong> with mom.",tip:"SHOP 和 STOP 押韻",emoji:"🏪",roots:["shop"]},
      {word:"hospital",chinese:"醫院",sentence:"The doctor works at the <strong>hospital</strong>.",tip:"HOSPITAL 裡有 HOST",emoji:"🏥",roots:["hos","pi","tal"]},
      {word:"library",chinese:"圖書館",sentence:"I read books at the <strong>library</strong>.",tip:"LIBRARY 有兩個 R",emoji:"📚",roots:["li","bra","ry"]},
      {word:"police station",chinese:"警察局",sentence:"Go to the <strong>police station</strong> for help.",tip:"POLICE STATION = 警察 + 站",emoji:"🚔",roots:["po","lice"," ","sta","tion"]},
      {word:"post office",chinese:"郵局",sentence:"I buy stamps at the <strong>post office</strong>.",tip:"POST OFFICE = 郵件 + 辦公室",emoji:"🏤",roots:["post"," ","off","ice"]},
      {word:"restaurant",chinese:"餐廳",sentence:"We eat at a <strong>restaurant</strong>.",tip:"RESTAURANT 拼法很長要小心",emoji:"🍽️",roots:["res","tau","rant"]},
      {word:"classroom",chinese:"教室",sentence:"Our <strong>classroom</strong> is big.",tip:"CLASSROOM = CLASS + ROOM",emoji:"🏫",roots:["class","room"]},
      {word:"sofa",chinese:"沙發",sentence:"I sit on the <strong>sofa</strong>.",tip:"SOFA 只有四個字母",emoji:"🛋️",roots:["so","fa"]},
      {word:"TV",chinese:"電視",sentence:"I watch <strong>TV</strong> after dinner.",tip:"TV = TELEVISION 的縮寫",emoji:"📺",roots:["TV"]},
      {word:"bathroom",chinese:"浴室",sentence:"I brush my teeth in the <strong>bathroom</strong>.",tip:"BATHROOM = BATH + ROOM",emoji:"🚿",roots:["bath","room"]},
      {word:"bedroom",chinese:"臥室",sentence:"I sleep in my <strong>bedroom</strong>.",tip:"BEDROOM = BED + ROOM",emoji:"🛏️",roots:["bed","room"]},
      {word:"kitchen",chinese:"廚房",sentence:"Mom cooks in the <strong>kitchen</strong>.",tip:"KITCHEN 裡有 KIT",emoji:"👨‍🍳",roots:["kit","chen"]},
      {word:"living room",chinese:"客廳",sentence:"We watch TV in the <strong>living room</strong>.",tip:"LIVING ROOM = 生活 + 房間",emoji:"🛋️",roots:["liv","ing"," ","room"]},
      {word:"telephone",chinese:"電話",sentence:"Answer the <strong>telephone</strong>, please.",tip:"TELEPHONE = TELE（遠）+ PHONE（聲音）",emoji:"📞",roots:["tele","phone"]},
      {word:"some",chinese:"一些",sentence:"I have <strong>some</strong> candies.",tip:"SOME 的 O 發 /ʌ/ 的音",emoji:"🔢",roots:["some"]},
      {word:"thirteen",chinese:"十三",sentence:"I am <strong>thirteen</strong> years old.",tip:"THIRTEEN = THIR + TEEN",emoji:"1️⃣",roots:["thir","teen"]},
      {word:"fourteen",chinese:"十四",sentence:"There are <strong>fourteen</strong> students.",tip:"FOURTEEN = FOUR + TEEN",emoji:"1️⃣",roots:["four","teen"]},
      {word:"fifteen",chinese:"十五",sentence:"I have <strong>fifteen</strong> books.",tip:"FIFTEEN = FIF + TEEN（注意不是 FIVE）",emoji:"1️⃣",roots:["fif","teen"]},
      {word:"sixteen",chinese:"十六",sentence:"She is <strong>sixteen</strong> years old.",tip:"SIXTEEN = SIX + TEEN",emoji:"1️⃣",roots:["six","teen"]},
      {word:"seventeen",chinese:"十七",sentence:"There are <strong>seventeen</strong> boys.",tip:"SEVENTEEN = SEVEN + TEEN",emoji:"1️⃣",roots:["seven","teen"]},
      {word:"eighteen",chinese:"十八",sentence:"He is <strong>eighteen</strong> years old.",tip:"EIGHTEEN = EIGHT + EEN（只有一個T）",emoji:"1️⃣",roots:["eigh","teen"]},
      {word:"nineteen",chinese:"十九",sentence:"I have <strong>nineteen</strong> toys.",tip:"NINETEEN = NINE + TEEN",emoji:"1️⃣",roots:["nine","teen"]},
      {word:"twenty",chinese:"二十",sentence:"There are <strong>twenty</strong> chairs.",tip:"TWENTY 來自 TWO",emoji:"2️⃣",roots:["twen","ty"]},
      {word:"thirty",chinese:"三十",sentence:"Dad is <strong>thirty</strong> years old.",tip:"THIRTY 來自 THREE",emoji:"3️⃣",roots:["thir","ty"]},
      {word:"forty",chinese:"四十",sentence:"There are <strong>forty</strong> students.",tip:"FORTY 沒有 U！（不是 FOURTY）",emoji:"4️⃣",roots:["for","ty"]},
      {word:"fifty",chinese:"五十",sentence:"Grandma is <strong>fifty</strong> years old.",tip:"FIFTY 來自 FIVE",emoji:"5️⃣",roots:["fif","ty"]},
      {word:"sixty",chinese:"六十",sentence:"There are <strong>sixty</strong> minutes in an hour.",tip:"SIXTY 來自 SIX",emoji:"6️⃣",roots:["six","ty"]},
      {word:"seventy",chinese:"七十",sentence:"Grandpa is <strong>seventy</strong> years old.",tip:"SEVENTY 來自 SEVEN",emoji:"7️⃣",roots:["seven","ty"]},
      {word:"eighty",chinese:"八十",sentence:"Great grandma is <strong>eighty</strong>.",tip:"EIGHTY 來自 EIGHT",emoji:"8️⃣",roots:["eigh","ty"]},
      {word:"ninety",chinese:"九十",sentence:"There are <strong>ninety</strong> pages.",tip:"NINETY 來自 NINE（保留E）",emoji:"9️⃣",roots:["nine","ty"]},
      {word:"hundred",chinese:"一百",sentence:"I have one <strong>hundred</strong> stickers.",tip:"HUNDRED = HUND + RED",emoji:"💯",roots:["hun","dred"]},
      {word:"bus",chinese:"公車",sentence:"I take the <strong>bus</strong> to school.",tip:"BUS 只有三個字母",emoji:"🚌",roots:["bus"]},
      {word:"bike",chinese:"腳踏車",sentence:"I ride my <strong>bike</strong> to the park.",tip:"BIKE 和 LIKE 押韻",emoji:"🚲",roots:["bike"]},
      {word:"car",chinese:"汽車",sentence:"Dad drives a <strong>car</strong>.",tip:"CAR 和 STAR 押韻",emoji:"🚗",roots:["car"]},
      {word:"MRT",chinese:"捷運",sentence:"I take the <strong>MRT</strong> to school.",tip:"MRT = Mass Rapid Transit",emoji:"🚇",roots:["MRT"]},
      {word:"plane",chinese:"飛機",sentence:"The <strong>plane</strong> flies in the sky.",tip:"PLANE 和 RAIN 有類似的音",emoji:"✈️",roots:["plane"]},
      {word:"ship",chinese:"船",sentence:"The <strong>ship</strong> sails on the sea.",tip:"SHIP 和 TIP 押韻",emoji:"🚢",roots:["ship"]},
      {word:"taxi",chinese:"計程車",sentence:"We take a <strong>taxi</strong> to the airport.",tip:"TAXI 是全世界通用的字",emoji:"🚕",roots:["tax","i"]},
      {word:"train",chinese:"火車",sentence:"The <strong>train</strong> is very fast.",tip:"TRAIN 和 RAIN 押韻",emoji:"🚂",roots:["train"]},
      {word:"bad",chinese:"壞的",sentence:"That is a <strong>bad</strong> idea.",tip:"BAD 和 SAD 押韻",emoji:"👎",roots:["bad"]},
      {word:"good",chinese:"好的",sentence:"You are a <strong>good</strong> student.",tip:"GOOD 有兩個 O",emoji:"👍",roots:["good"]},
      {word:"happy",chinese:"快樂的",sentence:"I am <strong>happy</strong> today.",tip:"HAPPY 有兩個 P",emoji:"😊",roots:["hap","py"]},
      {word:"mad",chinese:"生氣的",sentence:"Don't be <strong>mad</strong> at me.",tip:"MAD 和 BAD 押韻",emoji:"😠",roots:["mad"]},
      {word:"sad",chinese:"傷心的",sentence:"I feel <strong>sad</strong> when my friend leaves.",tip:"SAD 和 BAD 押韻",emoji:"😢",roots:["sad"]},
      {word:"sick",chinese:"生病的",sentence:"I am <strong>sick</strong> today.",tip:"SICK 和 KICK 押韻",emoji:"🤒",roots:["sick"]},
      {word:"angry",chinese:"生氣的",sentence:"The dog looks <strong>angry</strong>.",tip:"ANGRY = ANG + RY",emoji:"😤",roots:["ang","ry"]},
      {word:"excited",chinese:"興奮的",sentence:"I am <strong>excited</strong> about the trip.",tip:"EXCITED = EXCITE + D",emoji:"🤩",roots:["ex","cit","ed"]},
      {word:"hungry",chinese:"餓的",sentence:"I am very <strong>hungry</strong>.",tip:"HUNGRY 裡有 HUNG",emoji:"😋",roots:["hun","gry"]},
      {word:"tired",chinese:"累的",sentence:"I am <strong>tired</strong> after running.",tip:"TIRED = TIRE + D",emoji:"😫",roots:["tir","ed"]},
      {word:"coat",chinese:"外套",sentence:"Wear your <strong>coat</strong>. It's cold.",tip:"COAT 和 BOAT 押韻",emoji:"🧥",roots:["coat"]},
      {word:"glasses",chinese:"眼鏡",sentence:"I wear <strong>glasses</strong> to read.",tip:"GLASSES 永遠用複數",emoji:"👓",roots:["glass","es"]},
      {word:"pants",chinese:"褲子",sentence:"I wear blue <strong>pants</strong>.",tip:"PANTS 永遠用複數",emoji:"👖",roots:["pants"]},
      {word:"shoes",chinese:"鞋子",sentence:"Put on your <strong>shoes</strong>.",tip:"SHOES 永遠用複數",emoji:"👟",roots:["shoes"]},
      {word:"shorts",chinese:"短褲",sentence:"I wear <strong>shorts</strong> in summer.",tip:"SHORTS = SHORT + S",emoji:"🩳",roots:["shorts"]},
      {word:"socks",chinese:"襪子",sentence:"I wear white <strong>socks</strong>.",tip:"SOCKS 永遠用複數",emoji:"🧦",roots:["socks"]},
      {word:"T-shirt",chinese:"T恤",sentence:"I wear a <strong>T-shirt</strong> in summer.",tip:"因為形狀像字母T",emoji:"👕",roots:["T","-","shirt"]},
      {word:"jacket",chinese:"夾克",sentence:"Bring your <strong>jacket</strong>.",tip:"JACKET = JACK + ET",emoji:"🧥",roots:["jack","et"]},
      {word:"sweater",chinese:"毛衣",sentence:"I wear a <strong>sweater</strong> in winter.",tip:"SWEATER = SWEAT + ER（出汗的衣服）",emoji:"🧶",roots:["sweat","er"]},
      {word:"art",chinese:"美術",sentence:"I love <strong>art</strong> class.",tip:"ART 只有三個字母",emoji:"🎨",roots:["art"]},
      {word:"Chinese",chinese:"中文",sentence:"I study <strong>Chinese</strong> every day.",tip:"CHINESE = CHINA + ESE",emoji:"🇹🇼",roots:["Chi","nese"]},
      {word:"English",chinese:"英文",sentence:"I learn <strong>English</strong> at school.",tip:"ENGLISH = ENG + LISH",emoji:"🇬🇧",roots:["Eng","lish"]},
      {word:"math",chinese:"數學",sentence:"I like <strong>math</strong> class.",tip:"MATH = MATHEMATICS 的縮寫",emoji:"🔢",roots:["math"]},
      {word:"music",chinese:"音樂",sentence:"I play <strong>music</strong> on the piano.",tip:"MUSIC = MUS + IC",emoji:"🎵",roots:["mu","sic"]},
      {word:"PE",chinese:"體育",sentence:"We run in <strong>PE</strong> class.",tip:"PE = Physical Education",emoji:"🏃",roots:["PE"]},
      {word:"science",chinese:"科學/自然",sentence:"I love <strong>science</strong> experiments.",tip:"SCIENCE 的 SC 發 /s/ 的音",emoji:"🔬",roots:["sci","ence"]},
      {word:"close",chinese:"關閉",sentence:"Please <strong>close</strong> the door.",tip:"CLOSE 當動詞和形容詞發音不同",emoji:"🚪",roots:["close"]},
      {word:"clean",chinese:"打掃/乾淨",sentence:"Please <strong>clean</strong> your room.",tip:"CLEAN 既是動詞也是形容詞",emoji:"🧹",roots:["clean"]},
      {word:"come",chinese:"來",sentence:"<strong>Come</strong> here, please.",tip:"COME 的 O 發 /ʌ/ 的音",emoji:"🏃",roots:["come"]},
      {word:"drink",chinese:"喝",sentence:"I <strong>drink</strong> water every day.",tip:"DRINK 和 THINK 押韻",emoji:"🥤",roots:["drink"]},
      {word:"eat",chinese:"吃",sentence:"I <strong>eat</strong> lunch at school.",tip:"EAT 和 MEAT 押韻",emoji:"🍽️",roots:["eat"]},
      {word:"feel",chinese:"感覺",sentence:"I <strong>feel</strong> happy today.",tip:"FEEL 有兩個 E",emoji:"💭",roots:["feel"]},
      {word:"fly",chinese:"飛",sentence:"Birds can <strong>fly</strong>.",tip:"FLY 和 SKY 押韻",emoji:"🕊️",roots:["fly"]},
      {word:"get",chinese:"得到",sentence:"I <strong>get</strong> a gift from mom.",tip:"GET 有很多不同用法",emoji:"🎁",roots:["get"]},
      {word:"give",chinese:"給",sentence:"I <strong>give</strong> her a book.",tip:"GIVE 和 LIVE 押韻",emoji:"🤲",roots:["give"]},
      {word:"go",chinese:"去",sentence:"I <strong>go</strong> to school.",tip:"GO 只有兩個字母",emoji:"🚶",roots:["go"]},
      {word:"listen",chinese:"聽",sentence:"<strong>Listen</strong> to the teacher.",tip:"LISTEN 的 T 不發音！",emoji:"👂",roots:["lis","ten"]},
      {word:"live",chinese:"住/生活",sentence:"I <strong>live</strong> in Taipei.",tip:"LIVE 當動詞和形容詞發音不同",emoji:"🏠",roots:["live"]},
      {word:"ride",chinese:"騎",sentence:"I <strong>ride</strong> my bike to school.",tip:"RIDE 和 SIDE 押韻",emoji:"🚴",roots:["ride"]},
      {word:"open",chinese:"打開",sentence:"<strong>Open</strong> the window, please.",tip:"OPEN 和 CLOSE 是相反詞",emoji:"📂",roots:["o","pen"]},
      {word:"play",chinese:"玩",sentence:"Let's <strong>play</strong> together.",tip:"PLAY 和 DAY 押韻",emoji:"🎮",roots:["play"]},
      {word:"run",chinese:"跑",sentence:"I <strong>run</strong> to school.",tip:"RUN 和 FUN 押韻",emoji:"🏃",roots:["run"]},
      {word:"say",chinese:"說",sentence:"What did you <strong>say</strong>?",tip:"SAY 和 DAY 押韻",emoji:"🗣️",roots:["say"]},
      {word:"see",chinese:"看見",sentence:"I <strong>see</strong> a bird.",tip:"SEE 有兩個 E",emoji:"👀",roots:["see"]},
      {word:"sit",chinese:"坐",sentence:"Please <strong>sit</strong> down.",tip:"SIT 和 HIT 押韻",emoji:"💺",roots:["sit"]},
      {word:"drive",chinese:"開車",sentence:"Mom can <strong>drive</strong>.",tip:"DRIVE 和 FIVE 押韻",emoji:"🚗",roots:["drive"]},
      {word:"speak",chinese:"說（語言）",sentence:"I can <strong>speak</strong> English.",tip:"SPEAK 比 SAY 更正式",emoji:"🗣️",roots:["speak"]},
      {word:"study",chinese:"學習/讀書",sentence:"I <strong>study</strong> English every day.",tip:"STUDY 的複數要去 Y 加 IES",emoji:"📚",roots:["stu","dy"]},
      {word:"take",chinese:"拿/搭乘",sentence:"I <strong>take</strong> the bus to school.",tip:"TAKE 有很多不同用法",emoji:"🤲",roots:["take"]},
      {word:"talk",chinese:"說話/聊天",sentence:"I <strong>talk</strong> to my friend.",tip:"TALK 的 L 不發音！",emoji:"💬",roots:["talk"]},
      {word:"wear",chinese:"穿",sentence:"I <strong>wear</strong> a hat.",tip:"WEAR 和 BEAR 押韻",emoji:"👔",roots:["wear"]},
      {word:"walk",chinese:"走路",sentence:"I <strong>walk</strong> to school.",tip:"WALK 的 L 不發音！",emoji:"🚶",roots:["walk"]},
      {word:"wash",chinese:"洗",sentence:"<strong>Wash</strong> your hands.",tip:"WASH 的 A 發 /ɒ/ 的音",emoji:"🧼",roots:["wash"]},
      {word:"watch",chinese:"看（專注地）",sentence:"I <strong>watch</strong> TV after dinner.",tip:"WATCH 也有手錶的意思",emoji:"📺",roots:["watch"]},
      {word:"work",chinese:"工作",sentence:"Dad goes to <strong>work</strong> every day.",tip:"WORK 和 WORD 只差一個字母",emoji:"💼",roots:["work"]},
      {word:"Japan",chinese:"日本",sentence:"<strong>Japan</strong> is near Taiwan.",tip:"JAPAN 的重音在第二音節",emoji:"🇯🇵",roots:["Ja","pan"]},
      {word:"Taiwan",chinese:"台灣",sentence:"I live in <strong>Taiwan</strong>.",tip:"TAIWAN 是我們的家！",emoji:"🇹🇼",roots:["Tai","wan"]},
      {word:"UK",chinese:"英國",sentence:"The <strong>UK</strong> is in Europe.",tip:"UK = United Kingdom",emoji:"🇬🇧",roots:["UK"]},
      {word:"USA",chinese:"美國",sentence:"The <strong>USA</strong> is very big.",tip:"USA = United States of America",emoji:"🇺🇸",roots:["USA"]},
      {word:"card",chinese:"卡片",sentence:"I make a birthday <strong>card</strong>.",tip:"CARD 和 HARD 押韻",emoji:"💌",roots:["card"]},
      {word:"computer",chinese:"電腦",sentence:"I use a <strong>computer</strong> to study.",tip:"COMPUTER = COM + PUT + ER",emoji:"💻",roots:["com","put","er"]},
      {word:"e-mail",chinese:"電子郵件",sentence:"I send an <strong>e-mail</strong> to my friend.",tip:"E-MAIL = ELECTRONIC + MAIL",emoji:"📧",roots:["e","-","mail"]},
      {word:"bee",chinese:"蜜蜂",sentence:"The <strong>bee</strong> makes honey.",tip:"BEE 有兩個 E",emoji:"🐝",roots:["bee"]},
      {word:"duck",chinese:"鴨子",sentence:"The <strong>duck</strong> swims in the pond.",tip:"DUCK 和 LUCK 押韻",emoji:"🦆",roots:["duck"]},
      {word:"chicken",chinese:"雞/雞肉",sentence:"I eat <strong>chicken</strong> for dinner.",tip:"CHICKEN = CHICK + EN",emoji:"🐔",roots:["chick","en"]},
      {word:"elephant",chinese:"大象",sentence:"The <strong>elephant</strong> is very big.",tip:"ELEPHANT 的 PH 發 /f/ 的音",emoji:"🐘",roots:["ele","phant"]},
      {word:"dirty",chinese:"髒的",sentence:"Your hands are <strong>dirty</strong>.",tip:"DIRTY 和 CLEAN 是相反詞",emoji:"🤢",roots:["dir","ty"]}
    ]
};
