WORD_DATA["yle_flyers"] = {
  name: "YLE Flyers",
  color: "#0891b2",
  words: [
    {word:"journalist",chinese:"記者",sentence:"The <strong>journalist</strong> interviewed the mayor.",tip:"JOURNAL(日報)+IST(人)=寫日報的人",emoji:"📰",roots:["journal","ist"]},
    {word:"article",chinese:"文章",sentence:"She wrote an <strong>article</strong> for the school newspaper.",tip:"ARTICLE 也有「冠詞」的意思",emoji:"📝",roots:["art","icle"]},
    {word:"headline",chinese:"標題",sentence:"The <strong>headline</strong> says the team won!",tip:"HEAD(頭)+LINE(行)=最上面的一行字",emoji:"📰",roots:["head","line"]},
    {word:"advertisement",chinese:"廣告",sentence:"I saw an <strong>advertisement</strong> for a new phone.",tip:"AD(向)+VERT(轉)+ISE=把注意力轉過來",emoji:"📺",roots:["ad","vert","ise","ment"]},
    {word:"blog",chinese:"部落格",sentence:"She writes a <strong>blog</strong> about cooking.",tip:"BLOG = WEB + LOG 的縮寫",emoji:"💻",roots:["blog"]},
    {word:"broadcast",chinese:"廣播/播放",sentence:"The news is <strong>broadcast</strong> every evening.",tip:"BROAD(寬廣)+CAST(撒)=廣泛撒出去",emoji:"📡",roots:["broad","cast"]},
    {word:"screen",chinese:"螢幕",sentence:"Don't sit too close to the <strong>screen</strong>.",tip:"SCREEN 也有「屏風」的意思",emoji:"🖥️",roots:["screen"]},
    {word:"keyboard",chinese:"鍵盤",sentence:"Type your name on the <strong>keyboard</strong>.",tip:"KEY(鍵)+BOARD(板)=有按鍵的板子",emoji:"⌨️",roots:["key","board"]},
    {word:"printer",chinese:"印表機",sentence:"The <strong>printer</strong> is out of ink.",tip:"PRINT(印)+ER=印東西的機器",emoji:"🖨️",roots:["print","er"]},
    {word:"website",chinese:"網站",sentence:"Visit our <strong>website</strong> for more information.",tip:"WEB(網)+SITE(地方)=網路上的地方",emoji:"🌐",roots:["web","site"]},
    {word:"download",chinese:"下載",sentence:"<strong>Download</strong> the app from the store.",tip:"DOWN(下)+LOAD(裝載)=往下裝",emoji:"⬇️",roots:["down","load"]},
    {word:"upload",chinese:"上傳",sentence:"<strong>Upload</strong> your photo to the website.",tip:"UP(上)+LOAD(裝載)=往上傳",emoji:"⬆️",roots:["up","load"]},
    {word:"pollution",chinese:"污染",sentence:"Air <strong>pollution</strong> is bad for our health.",tip:"POLLUT(弄髒)+ION=弄髒環境",emoji:"🏭",roots:["pol","lut","ion"]},
    {word:"recycle",chinese:"回收/再利用",sentence:"We should <strong>recycle</strong> paper and plastic.",tip:"RE(再)+CYCLE(循環)=再次循環使用",emoji:"♻️",roots:["re","cycle"]},
    {word:"waste",chinese:"浪費/廢物",sentence:"Don't <strong>waste</strong> water.",tip:"WASTE 和 TASTE 押韻但意思相反",emoji:"🗑️",roots:["waste"]},
    {word:"endangered",chinese:"瀕危的",sentence:"Pandas are <strong>endangered</strong> animals.",tip:"EN(使)+DANGER(危險)+ED=處於危險中的",emoji:"🐼",roots:["en","danger","ed"]},
    {word:"fossil",chinese:"化石",sentence:"We found a dinosaur <strong>fossil</strong>.",tip:"FOSSIL 來自拉丁語「挖出來的東西」",emoji:"🦴",roots:["fos","sil"]},
    {word:"solar",chinese:"太陽的",sentence:"<strong>Solar</strong> energy comes from the sun.",tip:"SOL(太陽)+AR=和太陽有關的",emoji:"☀️",roots:["sol","ar"]},
    {word:"electricity",chinese:"電",sentence:"We use <strong>electricity</strong> to power our lights.",tip:"ELECTR(琥珀/電)+ICITY=電力",emoji:"⚡",roots:["electr","icity"]},
    {word:"embarrassed",chinese:"尷尬的",sentence:"He felt <strong>embarrassed</strong> when he tripped.",tip:"EM(使)+BARRASS(障礙)=使人受阻=尷尬",emoji:"😳",roots:["em","bar","rassed"]},
    {word:"jealous",chinese:"嫉妒的",sentence:"She was <strong>jealous</strong> of her friend's new toy.",tip:"JEALOUS 想到眼睛綠綠的嫉妒",emoji:"😒",roots:["jeal","ous"]},
    {word:"relieved",chinese:"鬆一口氣的",sentence:"I was <strong>relieved</strong> when I passed the test.",tip:"RE(再)+LIEVE(輕)=再次變輕鬆=解脫",emoji:"😌",roots:["re","liev","ed"]},
    {word:"disappointed",chinese:"失望的",sentence:"He was <strong>disappointed</strong> with his test score.",tip:"DIS(不)+APPOINT(指定)=不如所期望=失望",emoji:"😞",roots:["dis","appoint","ed"]},
    {word:"amazed",chinese:"驚嘆的",sentence:"We were <strong>amazed</strong> by the magic show.",tip:"A+MAZE(迷宮)=像進迷宮般驚奇",emoji:"😲",roots:["a","maze","d"]},
    {word:"anxious",chinese:"焦慮的",sentence:"She felt <strong>anxious</strong> before the exam.",tip:"ANXI(擔心)+OUS=充滿擔心的",emoji:"😰",roots:["anxi","ous"]},
    {word:"confused",chinese:"困惑的",sentence:"I'm <strong>confused</strong> by this maths problem.",tip:"CON(一起)+FUSE(倒)=全部倒在一起=混亂",emoji:"😕",roots:["con","fus","ed"]},
    {word:"grateful",chinese:"感激的",sentence:"I'm <strong>grateful</strong> for your help.",tip:"GRATE(感謝)+FUL=充滿感謝的",emoji:"🙏",roots:["grate","ful"]},
    {word:"furious",chinese:"狂怒的",sentence:"Dad was <strong>furious</strong> when I broke the window.",tip:"FURY(憤怒)+OUS=充滿憤怒的",emoji:"😡",roots:["fur","ious"]},
    {word:"terrified",chinese:"極度害怕的",sentence:"She was <strong>terrified</strong> of the spider.",tip:"TERR(嚇)+IFIED=被嚇壞了",emoji:"😱",roots:["terr","ified"]},
    {word:"pilot",chinese:"飛行員",sentence:"The <strong>pilot</strong> flew the plane safely.",tip:"PILOT 想到開飛機的英雄",emoji:"👨‍✈️",roots:["pil","ot"]},
    {word:"scientist",chinese:"科學家",sentence:"The <strong>scientist</strong> discovered a new species.",tip:"SCIENT(知識)+IST=有知識的人",emoji:"🔬",roots:["scient","ist"]},
    {word:"lawyer",chinese:"律師",sentence:"She wants to become a <strong>lawyer</strong>.",tip:"LAW(法律)+YER=做法律工作的人",emoji:"⚖️",roots:["law","yer"]},
    {word:"surgeon",chinese:"外科醫生",sentence:"The <strong>surgeon</strong> performed the operation.",tip:"SURG(升起)+EON=動手的醫生",emoji:"👨‍⚕️",roots:["surg","eon"]},
    {word:"electrician",chinese:"電工",sentence:"We called an <strong>electrician</strong> to fix the wiring.",tip:"ELECTRIC(電)+IAN=搞電的人",emoji:"🔌",roots:["electr","ician"]},
    {word:"plumber",chinese:"水管工",sentence:"The <strong>plumber</strong> fixed the leaking pipe.",tip:"PLUMB(鉛)+ER=用鉛管的人(古代水管是鉛做的)",emoji:"🔧",roots:["plumb","er"]},
    {word:"biology",chinese:"生物學",sentence:"We dissected a flower in <strong>biology</strong> class.",tip:"BIO(生命)+LOGY(學問)=研究生命的學問",emoji:"🧬",roots:["bio","logy"]},
    {word:"geography",chinese:"地理學",sentence:"In <strong>geography</strong>, we study maps and countries.",tip:"GEO(地球)+GRAPHY(描寫)=描寫地球",emoji:"🌍",roots:["geo","graphy"]},
    {word:"presentation",chinese:"簡報/報告",sentence:"She gave a <strong>presentation</strong> about dinosaurs.",tip:"PRESENT(呈現)+ATION=呈現出來",emoji:"📊",roots:["present","ation"]},
    {word:"laboratory",chinese:"實驗室",sentence:"We do experiments in the <strong>laboratory</strong>.",tip:"LABOR(工作)+ATORY=工作的地方",emoji:"🧪",roots:["labor","atory"]},
    {word:"microscope",chinese:"顯微鏡",sentence:"Look at the cell under the <strong>microscope</strong>.",tip:"MICRO(小)+SCOPE(看)=看小東西的工具",emoji:"🔬",roots:["micro","scope"]},
    {word:"passport",chinese:"護照",sentence:"Don't forget your <strong>passport</strong> at the airport.",tip:"PASS(通過)+PORT(港口)=通過關口的證件",emoji:"🛂",roots:["pass","port"]},
    {word:"luggage",chinese:"行李",sentence:"How many pieces of <strong>luggage</strong> do you have?",tip:"LUG(拖拉)+GAGE=拖著走的東西",emoji:"🧳",roots:["lug","gage"]},
    {word:"departure",chinese:"出發/離境",sentence:"The <strong>departure</strong> time is 9:30 AM.",tip:"DE(離開)+PART(部分)+URE=離開的動作",emoji:"🛫",roots:["de","part","ure"]},
    {word:"arrival",chinese:"到達",sentence:"Check the <strong>arrival</strong> board for your flight.",tip:"ARRIVE(到達)+AL=到達的動作",emoji:"🛬",roots:["arriv","al"]},
    {word:"destination",chinese:"目的地",sentence:"Our <strong>destination</strong> is Tokyo.",tip:"DESTIN(命定)+ATION=命定要去的地方",emoji:"📍",roots:["destin","ation"]},
    {word:"ceiling",chinese:"天花板",sentence:"There is a crack in the <strong>ceiling</strong>.",tip:"CEIL(遮蓋)+ING=蓋在上面的東西",emoji:"🏠",roots:["ceil","ing"]},
    {word:"fireplace",chinese:"壁爐",sentence:"We sat by the <strong>fireplace</strong> to keep warm.",tip:"FIRE(火)+PLACE(地方)=生火的地方",emoji:"🔥",roots:["fire","place"]},
    {word:"curtain",chinese:"窗簾",sentence:"Open the <strong>curtain</strong>s to let in sunlight.",tip:"CURTAIN 想到舞台的幕",emoji:"🪟",roots:["curt","ain"]},
    {word:"drawer",chinese:"抽屜",sentence:"Put your socks in the top <strong>drawer</strong>.",tip:"DRAW(拉)+ER=拉出來的東西",emoji:"🗄️",roots:["draw","er"]},
    {word:"chimney",chinese:"煙囪",sentence:"Smoke comes out of the <strong>chimney</strong>.",tip:"CHIMNEY 想到聖誕老人爬煙囪",emoji:"🏠",roots:["chim","ney"]},
    {word:"aisle",chinese:"走道",sentence:"Walk down the <strong>aisle</strong> to find your seat.",tip:"AISLE 的 S 不發音！發音像 I'LL",emoji:"🛒",roots:["aisle"]},
    {word:"trolley",chinese:"推車/手推車",sentence:"Put the groceries in the <strong>trolley</strong>.",tip:"TROLLEY 想到超市的推車",emoji:"🛒",roots:["trol","ley"]},
    {word:"checkout",chinese:"結帳處",sentence:"Pay at the <strong>checkout</strong> counter.",tip:"CHECK(核對)+OUT(出)=核對後離開",emoji:"🏪",roots:["check","out"]},
    {word:"celebration",chinese:"慶祝",sentence:"We had a big <strong>celebration</strong> for New Year.",tip:"CELEBR(慶祝)+ATION=慶祝的活動",emoji:"🎉",roots:["celebr","ation"]},
    {word:"custom",chinese:"習俗/風俗",sentence:"Eating turkey is a Thanksgiving <strong>custom</strong>.",tip:"CUSTOM=人們習慣做的事=風俗",emoji:"🎎",roots:["cust","om"]},
    {word:"ankle",chinese:"腳踝",sentence:"She twisted her <strong>ankle</strong> while running.",tip:"ANKLE 想到腳和腿連接的地方",emoji:"🦶",roots:["ank","le"]},
    {word:"wrist",chinese:"手腕",sentence:"She wears a watch on her <strong>wrist</strong>.",tip:"WRIST 的 W 不發音",emoji:"⌚",roots:["wrist"]},
    {word:"elbow",chinese:"手肘",sentence:"Don't put your <strong>elbow</strong>s on the table.",tip:"EL(手臂)+BOW(彎)=手臂彎曲的地方",emoji:"💪",roots:["el","bow"]},
    {word:"muscle",chinese:"肌肉",sentence:"Exercise makes your <strong>muscle</strong>s stronger.",tip:"MUSCLE 裡藏著 MUSC(老鼠)=肌肉像老鼠跑",emoji:"💪",roots:["musc","le"]},
    {word:"injection",chinese:"注射",sentence:"The nurse gave me an <strong>injection</strong>.",tip:"IN(裡面)+JECT(丟)+ION=丟進去=注射",emoji:"💉",roots:["in","ject","ion"]},
    {word:"cotton",chinese:"棉花/棉布",sentence:"This T-shirt is made of <strong>cotton</strong>.",tip:"COTTON 想到白白軟軟的棉花",emoji:"☁️",roots:["cot","ton"]},
    {word:"leather",chinese:"皮革",sentence:"He has a brown <strong>leather</strong> jacket.",tip:"LEATHER 和 WEATHER 拼法很像",emoji:"🧥",roots:["leath","er"]},
    {word:"silk",chinese:"絲綢",sentence:"Her dress is made of <strong>silk</strong>.",tip:"SILK 想到滑滑亮亮的絲綢",emoji:"👗",roots:["silk"]},
    {word:"concrete",chinese:"混凝土",sentence:"The floor is made of <strong>concrete</strong>.",tip:"CON(一起)+CRETE(生長)=長在一起變硬",emoji:"🏗️",roots:["con","crete"]},
    {word:"continent",chinese:"大洲/大陸",sentence:"Africa is the second largest <strong>continent</strong>.",tip:"CON(一起)+TINENT(持有)=連在一起的大片土地",emoji:"🌍",roots:["con","tin","ent"]},
    {word:"volcano",chinese:"火山",sentence:"The <strong>volcano</strong> erupted with hot lava.",tip:"VOLCANO 來自火神 VULCAN",emoji:"🌋",roots:["volcan","o"]},
    {word:"earthquake",chinese:"地震",sentence:"The <strong>earthquake</strong> shook the whole building.",tip:"EARTH(地球)+QUAKE(震動)=地球在搖",emoji:"🫨",roots:["earth","quake"]},
    {word:"coast",chinese:"海岸",sentence:"We drove along the <strong>coast</strong>.",tip:"COAST 想到海邊的風景",emoji:"🏖️",roots:["coast"]},
    {word:"harbour",chinese:"港口",sentence:"The boats are safe in the <strong>harbour</strong>.",tip:"HARBOUR=HARB(遮蔽)+OUR=船的避風港",emoji:"⚓",roots:["harb","our"]},
    {word:"fortnight",chinese:"兩週",sentence:"We went on holiday for a <strong>fortnight</strong>.",tip:"FOURTEEN(十四)+NIGHT(夜)=十四天=兩週",emoji:"📅",roots:["fort","night"]},
    {word:"decade",chinese:"十年",sentence:"They lived here for a <strong>decade</strong>.",tip:"DEC(十)+ADE=十年的時間",emoji:"📅",roots:["dec","ade"]},
    {word:"gradually",chinese:"逐漸地",sentence:"The weather is <strong>gradually</strong> getting warmer.",tip:"GRAD(步)+UALLY=一步一步地",emoji:"📈",roots:["gradu","ally"]},
    {word:"meanwhile",chinese:"同時",sentence:"<strong>Meanwhile</strong>, his sister was reading a book.",tip:"MEAN(中間)+WHILE(一段時間)=在此期間",emoji:"⏰",roots:["mean","while"]},
    {word:"fiction",chinese:"小說/虛構",sentence:"I prefer <strong>fiction</strong> to non-fiction books.",tip:"FICT(編造)+ION=編造的故事",emoji:"📚",roots:["fict","ion"]},
    {word:"novel",chinese:"小說",sentence:"She is reading a detective <strong>novel</strong>.",tip:"NOVEL 也有「新奇的」意思",emoji:"📖",roots:["nov","el"]},
    {word:"poetry",chinese:"詩歌",sentence:"We studied <strong>poetry</strong> in English class.",tip:"POET(詩人)+RY=詩人寫的東西",emoji:"📜",roots:["poet","ry"]},
    {word:"chapter",chinese:"章節",sentence:"Read <strong>chapter</strong> 3 for homework.",tip:"CHAPTER 來自拉丁語「頭」=每章的開頭",emoji:"📖",roots:["chapt","er"]},
    {word:"character",chinese:"角色/人物",sentence:"My favourite <strong>character</strong> is the wizard.",tip:"CHARACTER 也有「性格」的意思",emoji:"🧙",roots:["char","act","er"]},
    {word:"detective",chinese:"偵探",sentence:"The <strong>detective</strong> solved the mystery.",tip:"DETECT(發現)+IVE=發現真相的人",emoji:"🕵️",roots:["detect","ive"]},
    {word:"mystery",chinese:"謎/神秘事物",sentence:"The disappearance is still a <strong>mystery</strong>.",tip:"MYSTERY 來自希臘語「閉上眼睛」",emoji:"🔍",roots:["myst","ery"]},
    {word:"legend",chinese:"傳說/傳奇",sentence:"There is a <strong>legend</strong> about a dragon in the lake.",tip:"LEGEND 來自拉丁語「要被讀的東西」",emoji:"📜",roots:["leg","end"]},
    {word:"comedy",chinese:"喜劇",sentence:"We watched a funny <strong>comedy</strong> film.",tip:"COMEDY 來自希臘語「歌唱的村莊」",emoji:"😂",roots:["com","edy"]},
    {word:"tragedy",chinese:"悲劇",sentence:"Romeo and Juliet is a <strong>tragedy</strong>.",tip:"TRAGEDY 來自希臘語「山羊之歌」",emoji:"😢",roots:["trag","edy"]},
    {word:"referee",chinese:"裁判",sentence:"The <strong>referee</strong> blew the final whistle.",tip:"REFER(參考)+EE=被參考意見的人=裁判",emoji:"🧑‍⚖️",roots:["refer","ee"]},
    {word:"opponent",chinese:"對手",sentence:"She shook hands with her <strong>opponent</strong>.",tip:"OP(對面)+PON(放)+ENT=放在對面的人",emoji:"🤝",roots:["op","pon","ent"]},
    {word:"spectator",chinese:"觀眾",sentence:"Thousands of <strong>spectator</strong>s watched the game.",tip:"SPECT(看)+ATOR=看的人",emoji:"👀",roots:["spect","ator"]},
    {word:"gymnastics",chinese:"體操",sentence:"She practises <strong>gymnastics</strong> three times a week.",tip:"GYMN(訓練)+ASTICS=古希臘訓練項目",emoji:"🤸",roots:["gymn","astics"]},
    {word:"marathon",chinese:"馬拉松",sentence:"He finished the <strong>marathon</strong> in four hours.",tip:"MARATHON 來自希臘地名",emoji:"🏃",roots:["mara","thon"]},
    {word:"mixture",chinese:"混合物",sentence:"Pour the <strong>mixture</strong> into the pan.",tip:"MIX(混合)+TURE=混合後的東西",emoji:"🥣",roots:["mix","ture"]},
    {word:"appetite",chinese:"食慾",sentence:"I have a big <strong>appetite</strong> after swimming.",tip:"AP(朝向)+PETITE(追求)=朝向食物追求",emoji:"🍽️",roots:["ap","pet","ite"]},
    {word:"vegetarian",chinese:"素食者",sentence:"She's a <strong>vegetarian</strong>; she doesn't eat meat.",tip:"VEGET(蔬菜)+ARIAN=吃蔬菜的人",emoji:"🥦",roots:["veget","arian"]},
    {word:"accent",chinese:"口音/重音",sentence:"She speaks English with a French <strong>accent</strong>.",tip:"AC(向)+CENT(唱)=說話的調調=口音",emoji:"🗣️",roots:["ac","cent"]},
    {word:"pronounce",chinese:"發音",sentence:"How do you <strong>pronounce</strong> this word?",tip:"PRO(向前)+NOUNCE(宣布)=說出聲音來",emoji:"🔊",roots:["pro","nounce"]},
    {word:"translate",chinese:"翻譯",sentence:"Can you <strong>translate</strong> this into Chinese?",tip:"TRANS(跨越)+LATE(帶)=帶到另一種語言",emoji:"🌐",roots:["trans","late"]},
    {word:"vocabulary",chinese:"詞彙",sentence:"Reading helps you build your <strong>vocabulary</strong>.",tip:"VOC(聲音)+ABULARY=用聲音表達的字詞",emoji:"📚",roots:["voc","abul","ary"]},
    {word:"grammar",chinese:"文法",sentence:"English <strong>grammar</strong> can be tricky.",tip:"GRAM(寫)+MAR=寫作的規則",emoji:"📝",roots:["gram","mar"]},
    {word:"paragraph",chinese:"段落",sentence:"Write a <strong>paragraph</strong> about your hobby.",tip:"PARA(旁邊)+GRAPH(寫)=寫在旁邊的段落標記",emoji:"📄",roots:["para","graph"]},
    {word:"essay",chinese:"文章/散文",sentence:"Write an <strong>essay</strong> about your summer holiday.",tip:"ESSAY 來自法語「嘗試」=嘗試表達想法",emoji:"✍️",roots:["es","say"]},
    {word:"suburb",chinese:"郊區",sentence:"They live in a quiet <strong>suburb</strong>.",tip:"SUB(在下面/靠近)+URB(城市)=城市附近",emoji:"🏘️",roots:["sub","urb"]},
    {word:"cathedral",chinese:"大教堂",sentence:"The old <strong>cathedral</strong> has beautiful windows.",tip:"CATHEDRA(座位)+L=主教座位所在=大教堂",emoji:"⛪",roots:["cathedr","al"]},
    {word:"monument",chinese:"紀念碑",sentence:"We visited the war <strong>monument</strong>.",tip:"MONU(提醒)+MENT=提醒人們記住的東西",emoji:"🗿",roots:["monu","ment"]},
    {word:"drought",chinese:"乾旱",sentence:"The <strong>drought</strong> lasted for three months.",tip:"DROUGHT 想到土地乾裂",emoji:"🏜️",roots:["drought"]},
    {word:"typhoon",chinese:"颱風",sentence:"A big <strong>typhoon</strong> hit the island last week.",tip:"TYPHOON 來自中文「大風」的音譯",emoji:"🌀",roots:["ty","phoon"]},
    {word:"astronomy",chinese:"天文學",sentence:"She studies <strong>astronomy</strong> and loves stars.",tip:"ASTRO(星星)+NOMY(規律)=星星的規律",emoji:"🔭",roots:["astro","nomy"]},
    {word:"telescope",chinese:"望遠鏡",sentence:"We looked at the moon through a <strong>telescope</strong>.",tip:"TELE(遠)+SCOPE(看)=看遠處的工具",emoji:"🔭",roots:["tele","scope"]},
    {word:"orbit",chinese:"軌道",sentence:"The Earth <strong>orbit</strong>s the Sun.",tip:"ORBIT 來自拉丁語「圓圈」",emoji:"🪐",roots:["orb","it"]},
    {word:"gravity",chinese:"重力",sentence:"<strong>Gravity</strong> keeps us on the ground.",tip:"GRAV(重)+ITY=重的力量",emoji:"🍎",roots:["grav","ity"]},
    {word:"hypothesis",chinese:"假設",sentence:"Our <strong>hypothesis</strong> was correct.",tip:"HYPO(下面)+THESIS(放置)=放在下面的假定",emoji:"💡",roots:["hypo","thesis"]},
    {word:"species",chinese:"物種",sentence:"There are many <strong>species</strong> of birds.",tip:"SPECIES 來自拉丁語「外表/種類」",emoji:"🦜",roots:["spec","ies"]},
    {word:"habitat",chinese:"棲息地",sentence:"The forest is the bear's natural <strong>habitat</strong>.",tip:"HABIT(居住)+AT=居住的地方",emoji:"🌲",roots:["habit","at"]},
    {word:"mammal",chinese:"哺乳動物",sentence:"A whale is a <strong>mammal</strong>, not a fish.",tip:"MAMMAL 來自 MAMMA(媽媽的乳房)=喝奶的動物",emoji:"🐋",roots:["mamm","al"]},
    {word:"reptile",chinese:"爬蟲類",sentence:"A snake is a <strong>reptile</strong>.",tip:"REPT(爬)+ILE=爬行的動物",emoji:"🐍",roots:["rept","ile"]},
    {word:"predator",chinese:"掠食者",sentence:"The lion is a fierce <strong>predator</strong>.",tip:"PRED(抓取)+ATOR=抓別的動物的",emoji:"🦁",roots:["pred","ator"]},
    {word:"prey",chinese:"獵物",sentence:"The eagle caught its <strong>prey</strong>.",tip:"PREY 想到被追捕的小動物",emoji:"🐰",roots:["prey"]},
    {word:"adopt",chinese:"領養/採用",sentence:"They decided to <strong>adopt</strong> a puppy.",tip:"AD(向)+OPT(選擇)=選擇接受=領養",emoji:"🐕",roots:["ad","opt"]},
    {word:"charity",chinese:"慈善/慈善機構",sentence:"She raised money for <strong>charity</strong>.",tip:"CHARITY 來自拉丁語「愛/慷慨」",emoji:"❤️",roots:["char","ity"]},
    {word:"volunteer",chinese:"志願者",sentence:"She works as a <strong>volunteer</strong> at the hospital.",tip:"VOLUNT(意願)+EER=有意願的人",emoji:"🙋",roots:["volunt","eer"]},
    {word:"invisible",chinese:"看不見的",sentence:"The glass door was almost <strong>invisible</strong>.",tip:"IN(不)+VIS(看)+IBLE(能)=不能看見的",emoji:"👻",roots:["in","vis","ible"]},
    {word:"transparent",chinese:"透明的",sentence:"Glass is <strong>transparent</strong>.",tip:"TRANS(穿過)+PAR(出現)+ENT=可以看穿的",emoji:"🔍",roots:["trans","par","ent"]},
    {word:"identical",chinese:"完全相同的",sentence:"The twins look <strong>identical</strong>.",tip:"IDENT(相同)+ICAL=完全一樣的",emoji:"👯",roots:["ident","ical"]},
    {word:"artificial",chinese:"人工的/人造的",sentence:"These flowers are <strong>artificial</strong>, not real.",tip:"ART(技術)+IFICIAL=用技術做的=人工的",emoji:"🌺",roots:["art","ificial"]},
    {word:"ancient",chinese:"古老的",sentence:"We studied <strong>ancient</strong> Egyptian history.",tip:"ANCIENT 來自拉丁語「在前面的」",emoji:"🏺",roots:["anc","ient"]},
    {word:"civilization",chinese:"文明",sentence:"The Roman <strong>civilization</strong> was very advanced.",tip:"CIVIL(公民)+IZATION=公民社會的發展",emoji:"🏛️",roots:["civil","ization"]},
    {word:"emperor",chinese:"皇帝",sentence:"The <strong>emperor</strong> ruled a vast empire.",tip:"EMPEROR 來自拉丁語「命令者」",emoji:"👑",roots:["emper","or"]},
    {word:"invade",chinese:"入侵",sentence:"The enemy tried to <strong>invade</strong> the castle.",tip:"IN(裡面)+VADE(走)=走進去=入侵",emoji:"⚔️",roots:["in","vade"]},
    {word:"conquer",chinese:"征服",sentence:"The army <strong>conquer</strong>ed the territory.",tip:"CON(完全)+QUER(尋求)=完全取得=征服",emoji:"🏴",roots:["con","quer"]},
    {word:"sculpture",chinese:"雕塑",sentence:"There is a marble <strong>sculpture</strong> in the gallery.",tip:"SCULPT(雕刻)+URE=雕刻出來的東西",emoji:"🗿",roots:["sculpt","ure"]},
    {word:"gallery",chinese:"畫廊/美術館",sentence:"We visited an art <strong>gallery</strong> on Sunday.",tip:"GALLERY 想到掛滿畫的長廊",emoji:"🖼️",roots:["gall","ery"]},
    {word:"exhibition",chinese:"展覽",sentence:"There is a dinosaur <strong>exhibition</strong> at the museum.",tip:"EX(外)+HIBIT(持有)+ION=拿出來展示",emoji:"🏛️",roots:["ex","hibit","ion"]},
    {word:"portrait",chinese:"肖像",sentence:"She painted a <strong>portrait</strong> of her grandmother.",tip:"POR(向前)+TRAIT(畫)=畫出面前的人",emoji:"🖼️",roots:["por","trait"]},
    {word:"literature",chinese:"文學",sentence:"We study English <strong>literature</strong> at school.",tip:"LITER(文字)+ATURE=和文字有關的藝術",emoji:"📚",roots:["liter","ature"]},
    {word:"satellite",chinese:"衛星",sentence:"The <strong>satellite</strong> orbits the Earth.",tip:"SATELLITE 原意是「隨從/跟隨者」",emoji:"🛰️",roots:["satell","ite"]},
    {word:"comet",chinese:"彗星",sentence:"We saw a <strong>comet</strong> in the night sky.",tip:"COMET 來自希臘語「長頭髮的星」",emoji:"☄️",roots:["com","et"]},
    {word:"galaxy",chinese:"銀河/星系",sentence:"Our solar system is in the Milky Way <strong>galaxy</strong>.",tip:"GALAXY 來自希臘語「牛奶」=乳白色的星河",emoji:"🌌",roots:["galax","y"]},
    {word:"universe",chinese:"宇宙",sentence:"The <strong>universe</strong> is incredibly vast.",tip:"UNI(一)+VERSE(轉)=轉動的整體=宇宙",emoji:"🌌",roots:["uni","verse"]},
    {word:"oxygen",chinese:"氧氣",sentence:"Plants produce <strong>oxygen</strong>.",tip:"OXY(酸)+GEN(產生)=產生酸的元素(早期命名)",emoji:"💨",roots:["oxy","gen"]},
    {word:"magnify",chinese:"放大",sentence:"The lens can <strong>magnify</strong> tiny objects.",tip:"MAGN(大)+IFY(使)=使東西變大",emoji:"🔍",roots:["magn","ify"]},
    {word:"evaporate",chinese:"蒸發",sentence:"The water will <strong>evaporate</strong> in the sun.",tip:"E(出)+VAPOR(蒸氣)+ATE=變成蒸氣出去",emoji:"💨",roots:["e","vapor","ate"]},
    {word:"dissolve",chinese:"溶解",sentence:"Sugar <strong>dissolve</strong>s in hot water.",tip:"DIS(分開)+SOLVE(鬆開)=分散開來=溶解",emoji:"🧪",roots:["dis","solve"]},
    {word:"diagram",chinese:"圖表",sentence:"Draw a <strong>diagram</strong> to explain the process.",tip:"DIA(通過)+GRAM(寫)=用圖寫出來",emoji:"📊",roots:["dia","gram"]},
    {word:"formula",chinese:"公式",sentence:"Use the <strong>formula</strong> to solve the problem.",tip:"FORMULA 來自拉丁語「小形式」",emoji:"📐",roots:["form","ula"]},
    {word:"calculate",chinese:"計算",sentence:"<strong>Calculate</strong> the total cost.",tip:"CALCUL(小石子)+ATE=用石子計數(古代方法)",emoji:"🧮",roots:["calcul","ate"]},
    {word:"symptom",chinese:"症狀",sentence:"A cough is a common <strong>symptom</strong> of a cold.",tip:"SYM(一起)+PTOM(倒下)=一起倒下的徵兆",emoji:"🤒",roots:["sym","ptom"]},
    {word:"vaccine",chinese:"疫苗",sentence:"The <strong>vaccine</strong> protects us from the disease.",tip:"VACCINE 來自拉丁語「牛」(最早用牛痘)",emoji:"💉",roots:["vacc","ine"]},
    {word:"allergy",chinese:"過敏",sentence:"He has an <strong>allergy</strong> to peanuts.",tip:"ALL(其他)+ERGY(能量)=對其他東西的反應",emoji:"🤧",roots:["all","ergy"]},
    {word:"prescription",chinese:"處方",sentence:"The doctor wrote a <strong>prescription</strong> for medicine.",tip:"PRE(之前)+SCRIPT(寫)+ION=提前寫好的指示",emoji:"📋",roots:["pre","script","ion"]},
    {word:"documentary",chinese:"紀錄片",sentence:"We watched a <strong>documentary</strong> about whales.",tip:"DOCUMENT(紀錄)+ARY=紀錄的影片",emoji:"🎬",roots:["document","ary"]},
    {word:"autobiography",chinese:"自傳",sentence:"She wrote her <strong>autobiography</strong> at age 80.",tip:"AUTO(自己)+BIO(生命)+GRAPHY(寫)=寫自己的人生",emoji:"📖",roots:["auto","bio","graphy"]},
    {word:"rehearsal",chinese:"排練/彩排",sentence:"We have a play <strong>rehearsal</strong> after school.",tip:"RE(再)+HEARSE(耙)=再次耙過=反覆練習",emoji:"🎭",roots:["re","hears","al"]},
    {word:"costume",chinese:"戲服/服裝",sentence:"She wore a pirate <strong>costume</strong> for the play.",tip:"COSTUME 來自拉丁語「習慣/穿著」",emoji:"👗",roots:["cost","ume"]},
    {word:"orchestra",chinese:"管弦樂團",sentence:"The <strong>orchestra</strong> played beautifully.",tip:"ORCHESTRA 原意是希臘劇場的舞台",emoji:"🎵",roots:["orch","estra"]},
    {word:"choir",chinese:"合唱團",sentence:"She sings in the school <strong>choir</strong>.",tip:"CHOIR 發音是 /kwaɪr/，很特別！",emoji:"🎶",roots:["choir"]},
    {word:"rhythm",chinese:"節奏",sentence:"Clap your hands to the <strong>rhythm</strong>.",tip:"RHYTHM 沒有正常的母音字母！",emoji:"🥁",roots:["rhy","thm"]},
    {word:"melody",chinese:"旋律",sentence:"That song has a beautiful <strong>melody</strong>.",tip:"MELO(歌)+DY=歌曲的調子",emoji:"🎵",roots:["mel","ody"]},
    {word:"permission",chinese:"許可/允許",sentence:"Ask <strong>permission</strong> before you leave.",tip:"PER(通過)+MISS(送)+ION=讓你通過=許可",emoji:"✅",roots:["per","miss","ion"]},
    {word:"responsible",chinese:"負責任的",sentence:"You are <strong>responsible</strong> for your own things.",tip:"RE(回)+SPONS(回應)+IBLE=能回應的=負責的",emoji:"💼",roots:["re","spons","ible"]},
    {word:"independent",chinese:"獨立的",sentence:"She is very <strong>independent</strong> for her age.",tip:"IN(不)+DEPEND(依靠)+ENT=不依靠別人的",emoji:"💪",roots:["in","depend","ent"]},
    {word:"concentrate",chinese:"集中/專注",sentence:"Please <strong>concentrate</strong> on your work.",tip:"CON(一起)+CENTR(中心)+ATE=集中到中心",emoji:"🎯",roots:["con","centr","ate"]},
    {word:"interrupt",chinese:"打斷",sentence:"Don't <strong>interrupt</strong> when someone is talking.",tip:"INTER(之間)+RUPT(破)=在中間打破=打斷",emoji:"🙊",roots:["inter","rupt"]},
    {word:"hesitate",chinese:"猶豫",sentence:"Don't <strong>hesitate</strong> to ask for help.",tip:"HESITATE 想到站在那裡猶豫不決",emoji:"🤔",roots:["hesit","ate"]},
    {word:"persuade",chinese:"說服",sentence:"She <strong>persuade</strong>d me to try the new food.",tip:"PER(完全)+SUADE(勸)=完全說服",emoji:"🗣️",roots:["per","suade"]},
    {word:"apologize",chinese:"道歉",sentence:"I want to <strong>apologize</strong> for being late.",tip:"APO(離開)+LOG(說)+IZE=說些話讓問題離開",emoji:"🙇",roots:["apo","log","ize"]},
    {word:"guarantee",chinese:"保證",sentence:"We <strong>guarantee</strong> the quality of our products.",tip:"GUARANTEE=GARANT(保護)+EE=保護的承諾",emoji:"✅",roots:["guar","ant","ee"]},
    {word:"peninsula",chinese:"半島",sentence:"Italy is a <strong>peninsula</strong>.",tip:"PEN(幾乎)+INSULA(島)=幾乎是島=半島",emoji:"🗺️",roots:["pen","insula"]},
    {word:"hemisphere",chinese:"半球",sentence:"Australia is in the southern <strong>hemisphere</strong>.",tip:"HEMI(半)+SPHERE(球)=半個球",emoji:"🌍",roots:["hemi","sphere"]},
    {word:"equator",chinese:"赤道",sentence:"The <strong>equator</strong> divides the Earth in half.",tip:"EQUAT(相等)+OR=使兩半相等的線",emoji:"🌐",roots:["equat","or"]},
    {word:"valley",chinese:"山谷",sentence:"A river flows through the <strong>valley</strong>.",tip:"VALLEY 想到兩山之間的低地",emoji:"🏞️",roots:["val","ley"]},
    {word:"glacier",chinese:"冰河",sentence:"The <strong>glacier</strong> moves very slowly.",tip:"GLAC(冰)+IER=巨大的冰",emoji:"🧊",roots:["glac","ier"]},
    {word:"tropical",chinese:"熱帶的",sentence:"Bananas grow in <strong>tropical</strong> countries.",tip:"TROPIC(回歸線)+AL=回歸線附近的",emoji:"🌴",roots:["tropic","al"]},
    {word:"avalanche",chinese:"雪崩",sentence:"The <strong>avalanche</strong> buried the road in snow.",tip:"AVAL(下)+ANCHE=大量往下衝=雪崩",emoji:"🏔️",roots:["aval","anche"]},
    {word:"tsunami",chinese:"海嘯",sentence:"The <strong>tsunami</strong> caused terrible damage.",tip:"TSUNAMI 來自日語「港口的波浪」",emoji:"🌊",roots:["tsu","nami"]},
    {word:"agriculture",chinese:"農業",sentence:"<strong>Agriculture</strong> is important in this country.",tip:"AGRI(田)+CULTURE(耕種)=耕種田地",emoji:"🌾",roots:["agri","culture"]},
    {word:"harvest",chinese:"收穫",sentence:"Farmers <strong>harvest</strong> rice in autumn.",tip:"HARVEST 想到金黃色的稻田",emoji:"🌾",roots:["harv","est"]},
    {word:"renewable",chinese:"可再生的",sentence:"Solar power is a <strong>renewable</strong> energy source.",tip:"RE(再)+NEW(新)+ABLE(能)=能再次變新的",emoji:"♻️",roots:["re","new","able"]},
    {word:"ecosystem",chinese:"生態系統",sentence:"The coral reef is a delicate <strong>ecosystem</strong>.",tip:"ECO(家/環境)+SYSTEM(系統)=環境系統",emoji:"🌿",roots:["eco","system"]},
    {word:"extinct",chinese:"滅絕的",sentence:"Dinosaurs are <strong>extinct</strong>.",tip:"EX(出)+TINCT(消滅)=消滅光了",emoji:"🦕",roots:["ex","tinct"]},
    {word:"conservation",chinese:"保育/保存",sentence:"Wildlife <strong>conservation</strong> is very important.",tip:"CON(一起)+SERVE(保持)+ATION=保持住",emoji:"🌱",roots:["con","serv","ation"]},
    {word:"atmosphere",chinese:"大氣層/氣氛",sentence:"The Earth's <strong>atmosphere</strong> protects us from the sun.",tip:"ATMO(蒸氣)+SPHERE(球)=圍繞地球的氣體層",emoji:"🌍",roots:["atmo","sphere"]},
    {word:"bronze",chinese:"青銅/銅牌",sentence:"She won a <strong>bronze</strong> medal in swimming.",tip:"BRONZE 想到古老的青銅器",emoji:"🥉",roots:["bronze"]},
    {word:"tournament",chinese:"錦標賽",sentence:"Our team entered the tennis <strong>tournament</strong>.",tip:"TOURN(轉)+AMENT=騎士比武=錦標賽",emoji:"🏆",roots:["tourn","ament"]},
    {word:"tackle",chinese:"處理/攔截",sentence:"He <strong>tackle</strong>d the player with the ball.",tip:"TACKLE 想到橄欖球攔截",emoji:"🏈",roots:["tack","le"]},
    {word:"stadium",chinese:"體育場",sentence:"The <strong>stadium</strong> was full of cheering fans.",tip:"STADIUM 來自希臘語的長度單位",emoji:"🏟️",roots:["stadi","um"]},
    {word:"trophy",chinese:"獎盃",sentence:"The team lifted the <strong>trophy</strong> proudly.",tip:"TROPHY 來自希臘語「轉敗為勝」",emoji:"🏆",roots:["tro","phy"]},
    {word:"archaeology",chinese:"考古學",sentence:"She studied <strong>archaeology</strong> at university.",tip:"ARCHAE(古老)+OLOGY(學)=研究古老事物的學問",emoji:"⛏️",roots:["archae","ology"]},
    {word:"hieroglyphics",chinese:"象形文字",sentence:"The Egyptians wrote in <strong>hieroglyphics</strong>.",tip:"HIERO(神聖)+GLYPHICS(雕刻)=神聖的雕刻文字",emoji:"🏺",roots:["hiero","glyphics"]},
    {word:"mummy",chinese:"木乃伊",sentence:"They found a <strong>mummy</strong> in the pyramid.",tip:"MUMMY 來自阿拉伯語「蠟」=蠟封的屍體",emoji:"🧟",roots:["mum","my"]},
    {word:"pyramid",chinese:"金字塔",sentence:"The <strong>pyramid</strong>s of Egypt are very old.",tip:"PYRAMID 可能來自希臘語「火焰形」",emoji:"🔺",roots:["pyra","mid"]},
    {word:"biography",chinese:"傳記",sentence:"I read a <strong>biography</strong> of Marie Curie.",tip:"BIO(生命)+GRAPHY(寫)=寫別人的人生故事",emoji:"📖",roots:["bio","graphy"]},
    {word:"encyclopedia",chinese:"百科全書",sentence:"Look it up in the <strong>encyclopedia</strong>.",tip:"EN(在裡面)+CYCLO(圓/全)+PEDIA(教育)=全部知識",emoji:"📚",roots:["en","cyclo","pedia"]},
    {word:"expedition",chinese:"探險/遠征",sentence:"They went on an <strong>expedition</strong> to the Arctic.",tip:"EX(外)+PED(腳)+ITION=走出去遠行",emoji:"🧭",roots:["ex","ped","ition"]},
    {word:"specimen",chinese:"標本/樣本",sentence:"The scientist examined the <strong>specimen</strong>.",tip:"SPEC(看)+IMEN=拿來看的東西=標本",emoji:"🧫",roots:["spec","imen"]},
    {word:"greenhouse",chinese:"溫室",sentence:"The <strong>greenhouse</strong> effect warms our planet.",tip:"GREEN(綠)+HOUSE(房)=種綠色植物的房子",emoji:"🌱",roots:["green","house"]},
    {word:"deforestation",chinese:"砍伐森林",sentence:"<strong>Deforestation</strong> destroys animal habitats.",tip:"DE(去除)+FOREST(森林)+ATION=去掉森林",emoji:"🪓",roots:["de","forest","ation"]},
    {word:"migration",chinese:"遷徙",sentence:"Bird <strong>migration</strong> happens every autumn.",tip:"MIGR(移動)+ATION=移動的行為",emoji:"🦆",roots:["migr","ation"]},
    {word:"hibernation",chinese:"冬眠",sentence:"Bears go into <strong>hibernation</strong> in winter.",tip:"HIBERN(冬天)+ATION=冬天的活動=冬眠",emoji:"🐻",roots:["hibern","ation"]},
    {word:"camouflage",chinese:"偽裝",sentence:"The lizard uses <strong>camouflage</strong> to hide.",tip:"CAMOUFLAGE 法語「偽裝」=藏起來",emoji:"🦎",roots:["camou","flage"]},
    {word:"photosynthesis",chinese:"光合作用",sentence:"Plants use <strong>photosynthesis</strong> to make food.",tip:"PHOTO(光)+SYNTHESIS(合成)=用光合成食物",emoji:"🌿",roots:["photo","synthesis"]},
    {word:"nocturnal",chinese:"夜行性的",sentence:"Owls are <strong>nocturnal</strong> animals.",tip:"NOCT(夜)+URNAL=和夜晚有關的",emoji:"🦉",roots:["noct","urnal"]},
    {word:"herbivore",chinese:"草食動物",sentence:"A rabbit is a <strong>herbivore</strong>.",tip:"HERBI(草)+VORE(吃)=吃草的動物",emoji:"🐰",roots:["herbi","vore"]},
    {word:"carnivore",chinese:"肉食動物",sentence:"A wolf is a <strong>carnivore</strong>.",tip:"CARNI(肉)+VORE(吃)=吃肉的動物",emoji:"🐺",roots:["carni","vore"]},
    {word:"omnivore",chinese:"雜食動物",sentence:"Humans are <strong>omnivore</strong>s.",tip:"OMNI(全部)+VORE(吃)=什麼都吃的動物",emoji:"🧑",roots:["omni","vore"]},
    {word:"humidity",chinese:"濕度",sentence:"The <strong>humidity</strong> is very high today.",tip:"HUMID(潮濕)+ITY=潮濕的程度",emoji:"💧",roots:["humid","ity"]},
    {word:"forecast",chinese:"預報",sentence:"The weather <strong>forecast</strong> says rain tomorrow.",tip:"FORE(之前)+CAST(投射)=提前投射=預報",emoji:"🌤️",roots:["fore","cast"]}
  ]
};
