WORD_DATA["coca_l1"] = {
  name: "COCA L1",
  color: "#22c55e",
  words: [
    {word:"the",chinese:"這個/那個（定冠詞）",sentence:"<strong>The</strong> cat is on the table.",tip:"THE 是英文最常見的字！",emoji:"👆",roots:["the"]},
    {word:"a",chinese:"一個（不定冠詞）",sentence:"I have <strong>a</strong> new toy.",tip:"A 用在子音開頭的字前面",emoji:"1️⃣",roots:["a"]},
    {word:"an",chinese:"一個（不定冠詞）",sentence:"She eats <strong>an</strong> egg every morning.",tip:"AN 用在母音開頭的字前面",emoji:"1️⃣",roots:["an"]},
    {word:"is",chinese:"是（第三人稱單數）",sentence:"He <strong>is</strong> my best friend.",tip:"IS 搭配 he/she/it 使用",emoji:"✅",roots:["is"]},
    {word:"are",chinese:"是（複數/第二人稱）",sentence:"They <strong>are</strong> very happy.",tip:"ARE 搭配 you/we/they 使用",emoji:"✅",roots:["are"]},
    {word:"was",chinese:"是（過去式單數）",sentence:"She <strong>was</strong> at the store yesterday.",tip:"WAS 是 is 的過去式",emoji:"⏪",roots:["was"]},
    {word:"were",chinese:"是（過去式複數）",sentence:"We <strong>were</strong> at the park.",tip:"WERE 是 are 的過去式",emoji:"⏪",roots:["were"]},
    {word:"be",chinese:"是/存在",sentence:"I want to <strong>be</strong> a pilot.",tip:"BE 是所有「是」的原形",emoji:"✨",roots:["be"]},
    {word:"been",chinese:"已經是（過去分詞）",sentence:"I have <strong>been</strong> to Japan.",tip:"BEEN 用在 have 後面",emoji:"✈️",roots:["been"]},
    {word:"have",chinese:"有/已經",sentence:"I <strong>have</strong> two cats at home.",tip:"HAVE 表示擁有或完成",emoji:"🤲",roots:["have"]},
    {word:"has",chinese:"有（第三人稱）",sentence:"She <strong>has</strong> a beautiful smile.",tip:"HAS 是 have 的第三人稱",emoji:"🤲",roots:["has"]},
    {word:"had",chinese:"有（過去式）",sentence:"He <strong>had</strong> a great idea.",tip:"HAD 是 have 的過去式",emoji:"⏪",roots:["had"]},
    {word:"do",chinese:"做/助動詞",sentence:"What do you <strong>do</strong> after school?",tip:"DO 也用來問問題",emoji:"💪",roots:["do"]},
    {word:"does",chinese:"做（第三人稱）",sentence:"She <strong>does</strong> her homework first.",tip:"DOES 搭配 he/she/it",emoji:"💪",roots:["does"]},
    {word:"did",chinese:"做了（過去式）",sentence:"I <strong>did</strong> my best on the test.",tip:"DID 是 do 的過去式",emoji:"⏪",roots:["did"]},
    {word:"will",chinese:"將要",sentence:"I <strong>will</strong> help you tomorrow.",tip:"WILL 表示未來要做的事",emoji:"🔮",roots:["will"]},
    {word:"would",chinese:"會/將會",sentence:"I <strong>would</strong> like some juice.",tip:"WOULD 是比較有禮貌的說法",emoji:"🎩",roots:["would"]},
    {word:"can",chinese:"能夠/會",sentence:"I <strong>can</strong> ride my bike fast.",tip:"CAN 表示有能力做某事",emoji:"💪",roots:["can"]},
    {word:"could",chinese:"能夠（過去式/禮貌）",sentence:"<strong>Could</strong> you help me, please?",tip:"COULD 比 CAN 更有禮貌",emoji:"🙏",roots:["could"]},
    {word:"should",chinese:"應該",sentence:"You <strong>should</strong> eat your vegetables.",tip:"SHOULD 表示建議",emoji:"👍",roots:["should"]},
    {word:"may",chinese:"可以/可能",sentence:"<strong>May</strong> I go outside?",tip:"MAY 用來請求許可",emoji:"🙋",roots:["may"]},
    {word:"might",chinese:"可能",sentence:"It <strong>might</strong> rain later.",tip:"MIGHT 表示不太確定",emoji:"🤔",roots:["might"]},
    {word:"must",chinese:"必須",sentence:"You <strong>must</strong> brush your teeth.",tip:"MUST 表示一定要做",emoji:"❗",roots:["must"]},
    {word:"shall",chinese:"將要/要不要",sentence:"<strong>Shall</strong> we go now?",tip:"SHALL 常用來提議",emoji:"🤝",roots:["shall"]},
    {word:"not",chinese:"不/沒有",sentence:"I am <strong>not</strong> afraid.",tip:"NOT 放在動詞後面表示否定",emoji:"🚫",roots:["not"]},
    {word:"no",chinese:"不/沒有",sentence:"<strong>No</strong>, thank you.",tip:"NO 是最直接的拒絕",emoji:"🙅",roots:["no"]},
    {word:"yes",chinese:"是/好",sentence:"<strong>Yes</strong>, I can do it!",tip:"YES 是最開心的回答",emoji:"👍",roots:["yes"]},
    {word:"and",chinese:"和/而且",sentence:"I love cats <strong>and</strong> dogs.",tip:"AND 把兩個東西連在一起",emoji:"🤝",roots:["and"]},
    {word:"or",chinese:"或者",sentence:"Do you want cake <strong>or</strong> pie?",tip:"OR 表示二選一",emoji:"🔀",roots:["or"]},
    {word:"but",chinese:"但是",sentence:"I want to go, <strong>but</strong> I am busy.",tip:"BUT 表示轉折",emoji:"↩️",roots:["but"]},
    {word:"if",chinese:"如果",sentence:"<strong>If</strong> it rains, we stay inside.",tip:"IF 表示條件",emoji:"❓",roots:["if"]},
    {word:"then",chinese:"然後/那麼",sentence:"First think, <strong>then</strong> speak.",tip:"THEN 表示接下來",emoji:"➡️",roots:["then"]},
    {word:"when",chinese:"什麼時候/當",sentence:"<strong>When</strong> is your birthday?",tip:"WHEN 問時間",emoji:"⏰",roots:["when"]},
    {word:"where",chinese:"哪裡",sentence:"<strong>Where</strong> do you live?",tip:"WHERE 問地點",emoji:"📍",roots:["where"]},
    {word:"what",chinese:"什麼",sentence:"<strong>What</strong> is your favorite color?",tip:"WHAT 問事物",emoji:"❓",roots:["what"]},
    {word:"who",chinese:"誰",sentence:"<strong>Who</strong> is your best friend?",tip:"WHO 問人",emoji:"🧑",roots:["who"]},
    {word:"how",chinese:"如何/怎麼",sentence:"<strong>How</strong> are you today?",tip:"HOW 問方式或程度",emoji:"🤷",roots:["how"]},
    {word:"why",chinese:"為什麼",sentence:"<strong>Why</strong> are you laughing?",tip:"WHY 問原因",emoji:"🤔",roots:["why"]},
    {word:"which",chinese:"哪一個",sentence:"<strong>Which</strong> one do you prefer?",tip:"WHICH 要從幾個中選一個",emoji:"👈",roots:["which"]},
    {word:"this",chinese:"這個",sentence:"<strong>This</strong> is my favorite song.",tip:"THIS 指近的東西",emoji:"👇",roots:["this"]},
    {word:"that",chinese:"那個",sentence:"<strong>That</strong> mountain is very tall.",tip:"THAT 指遠的東西",emoji:"👉",roots:["that"]},
    {word:"these",chinese:"這些",sentence:"<strong>These</strong> flowers are beautiful.",tip:"THESE 是 this 的複數",emoji:"👇",roots:["these"]},
    {word:"those",chinese:"那些",sentence:"<strong>Those</strong> birds are singing.",tip:"THOSE 是 that 的複數",emoji:"👉",roots:["those"]},
    {word:"it",chinese:"它",sentence:"<strong>It</strong> is a sunny day.",tip:"IT 代替事物或動物",emoji:"👆",roots:["it"]},
    {word:"he",chinese:"他",sentence:"<strong>He</strong> is very smart.",tip:"HE 指男生",emoji:"👦",roots:["he"]},
    {word:"she",chinese:"她",sentence:"<strong>She</strong> is very kind.",tip:"SHE 指女生",emoji:"👧",roots:["she"]},
    {word:"we",chinese:"我們",sentence:"<strong>We</strong> are a great team.",tip:"WE 包括說話的人",emoji:"👫",roots:["we"]},
    {word:"they",chinese:"他們/她們/它們",sentence:"<strong>They</strong> are playing outside.",tip:"THEY 指兩個以上的人或物",emoji:"👥",roots:["they"]},
    {word:"me",chinese:"我（受格）",sentence:"Please help <strong>me</strong>.",tip:"ME 在動詞後面用",emoji:"🙋",roots:["me"]},
    {word:"him",chinese:"他（受格）",sentence:"I gave <strong>him</strong> a cookie.",tip:"HIM 是 he 的受格",emoji:"👦",roots:["him"]},
    {word:"her",chinese:"她（受格）/她的",sentence:"I see <strong>her</strong> every day.",tip:"HER 可以是受格也可以是所有格",emoji:"👧",roots:["her"]},
    {word:"us",chinese:"我們（受格）",sentence:"Come with <strong>us</strong>!",tip:"US 是 we 的受格",emoji:"👫",roots:["us"]},
    {word:"them",chinese:"他們（受格）",sentence:"I helped <strong>them</strong> clean up.",tip:"THEM 是 they 的受格",emoji:"👥",roots:["them"]},
    {word:"my",chinese:"我的",sentence:"<strong>My</strong> dog is very cute.",tip:"MY 表示屬於我的",emoji:"🙋",roots:["my"]},
    {word:"your",chinese:"你的/你們的",sentence:"What is <strong>your</strong> name?",tip:"YOUR 表示屬於你的",emoji:"👉",roots:["your"]},
    {word:"his",chinese:"他的",sentence:"<strong>His</strong> room is very neat.",tip:"HIS 表示屬於他的",emoji:"👦",roots:["his"]},
    {word:"its",chinese:"它的",sentence:"The dog wags <strong>its</strong> tail.",tip:"ITS 沒有撇號！it's = it is",emoji:"🐕",roots:["its"]},
    {word:"our",chinese:"我們的",sentence:"This is <strong>our</strong> school.",tip:"OUR 表示屬於我們的",emoji:"👫",roots:["our"]},
    {word:"their",chinese:"他們的",sentence:"<strong>Their</strong> house is very big.",tip:"THEIR 不要和 there 搞混",emoji:"👥",roots:["their"]},
    {word:"mine",chinese:"我的（名詞性）",sentence:"This pencil is <strong>mine</strong>.",tip:"MINE 後面不加名詞",emoji:"🙋",roots:["mine"]},
    {word:"yours",chinese:"你的（名詞性）",sentence:"Is this bag <strong>yours</strong>?",tip:"YOURS 後面不加名詞",emoji:"👉",roots:["yours"]},
    {word:"I",chinese:"我",sentence:"<strong>I</strong> love my family.",tip:"I 永遠大寫！",emoji:"🙋",roots:["I"]},
    {word:"you",chinese:"你/你們",sentence:"<strong>You</strong> are amazing!",tip:"YOU 可以指一個人或多人",emoji:"👉",roots:["you"]},
    {word:"all",chinese:"全部/所有",sentence:"<strong>All</strong> the children are here.",tip:"ALL 表示全部都算在內",emoji:"💯",roots:["all"]},
    {word:"each",chinese:"每一個",sentence:"<strong>Each</strong> student got a prize.",tip:"EACH 強調一個一個",emoji:"☝️",roots:["each"]},
    {word:"every",chinese:"每一個",sentence:"I exercise <strong>every</strong> morning.",tip:"EVERY 強調全部無例外",emoji:"📅",roots:["ev","ery"]},
    {word:"both",chinese:"兩個都",sentence:"<strong>Both</strong> answers are correct.",tip:"BOTH 只能用在兩個",emoji:"✌️",roots:["both"]},
    {word:"few",chinese:"少數/幾個",sentence:"I have a <strong>few</strong> questions.",tip:"A FEW 表示有一些",emoji:"🤏",roots:["few"]},
    {word:"more",chinese:"更多",sentence:"I want <strong>more</strong> time to finish.",tip:"MORE 是 many/much 的比較級",emoji:"➕",roots:["more"]},
    {word:"most",chinese:"最多/大部分",sentence:"<strong>Most</strong> people love music.",tip:"MOST 表示最高程度",emoji:"🏆",roots:["most"]},
    {word:"other",chinese:"其他的",sentence:"The <strong>other</strong> kids went home.",tip:"OTHER 表示剩下的",emoji:"👈",roots:["oth","er"]},
    {word:"another",chinese:"另一個",sentence:"Can I have <strong>another</strong> chance?",tip:"ANOTHER = AN + OTHER",emoji:"➕",roots:["an","other"]},
    {word:"such",chinese:"如此/這樣的",sentence:"It is <strong>such</strong> a nice day!",tip:"SUCH 加強語氣",emoji:"😮",roots:["such"]},
    {word:"any",chinese:"任何/一些",sentence:"Do you have <strong>any</strong> questions?",tip:"ANY 用在問句和否定句",emoji:"❓",roots:["any"]},
    {word:"same",chinese:"相同的",sentence:"We wear the <strong>same</strong> shirt.",tip:"SAME 前面常加 the",emoji:"👯",roots:["same"]},
    {word:"different",chinese:"不同的",sentence:"We have <strong>different</strong> ideas.",tip:"DIFFERENT = DIFFER + ENT",emoji:"🔀",roots:["dif","fer","ent"]},
    {word:"new",chinese:"新的",sentence:"I got a <strong>new</strong> backpack!",tip:"NEW 和 KNEW 發音一樣",emoji:"✨",roots:["new"]},
    {word:"first",chinese:"第一/首先",sentence:"I am <strong>first</strong> in line.",tip:"FIRST 有 fir（杉樹）在裡面",emoji:"🥇",roots:["first"]},
    {word:"last",chinese:"最後的/上一個",sentence:"This is the <strong>last</strong> question.",tip:"LAST 可以指最後或上次",emoji:"🔚",roots:["last"]},
    {word:"next",chinese:"下一個",sentence:"See you <strong>next</strong> time!",tip:"NEXT 表示接下來的",emoji:"⏭️",roots:["next"]},
    {word:"own",chinese:"自己的/擁有",sentence:"I clean my <strong>own</strong> room.",tip:"OWN 強調是自己的",emoji:"🏠",roots:["own"]},
    {word:"only",chinese:"只有/唯一的",sentence:"She is the <strong>only</strong> one here.",tip:"ONLY = ON + LY",emoji:"☝️",roots:["on","ly"]},
    {word:"just",chinese:"只是/剛剛",sentence:"I <strong>just</strong> finished eating.",tip:"JUST 有「剛好」的意思",emoji:"👌",roots:["just"]},
    {word:"also",chinese:"也/還",sentence:"I <strong>also</strong> enjoy painting.",tip:"ALSO 放在動詞前面",emoji:"➕",roots:["al","so"]},
    {word:"very",chinese:"非常",sentence:"The movie is <strong>very</strong> funny.",tip:"VERY 加強形容詞",emoji:"💪",roots:["very"]},
    {word:"too",chinese:"也/太",sentence:"I like ice cream <strong>too</strong>!",tip:"TOO 放句尾表示「也」",emoji:"➕",roots:["too"]},
    {word:"so",chinese:"所以/這麼",sentence:"I am <strong>so</strong> happy today!",tip:"SO 加強語氣或表示因果",emoji:"😊",roots:["so"]},
    {word:"really",chinese:"真的/非常",sentence:"I <strong>really</strong> love pizza.",tip:"REALLY = REAL + LY",emoji:"❗",roots:["real","ly"]},
    {word:"still",chinese:"仍然/還是",sentence:"Are you <strong>still</strong> hungry?",tip:"STILL 表示狀態持續",emoji:"⏳",roots:["still"]},
    {word:"even",chinese:"甚至/即使",sentence:"<strong>Even</strong> the teacher laughed!",tip:"EVEN 加強意外的感覺",emoji:"😲",roots:["even"]},
    {word:"again",chinese:"再一次",sentence:"Can we do it <strong>again</strong>?",tip:"AGAIN 的 AI 發 /ɛ/ 的音",emoji:"🔄",roots:["a","gain"]},
    {word:"already",chinese:"已經",sentence:"I <strong>already</strong> ate dinner.",tip:"ALREADY = ALL + READY",emoji:"✅",roots:["al","ready"]},
    {word:"always",chinese:"總是/一直",sentence:"She <strong>always</strong> smiles at me.",tip:"ALWAYS = ALL + WAYS",emoji:"♾️",roots:["al","ways"]},
    {word:"never",chinese:"從不",sentence:"I <strong>never</strong> give up.",tip:"NEVER = NOT + EVER",emoji:"🙅",roots:["nev","er"]},
    {word:"often",chinese:"經常",sentence:"We <strong>often</strong> play after school.",tip:"OFTEN 的 T 可以不發音",emoji:"🔁",roots:["of","ten"]},
    {word:"sometimes",chinese:"有時候",sentence:"I <strong>sometimes</strong> stay up late.",tip:"SOMETIMES = SOME + TIMES",emoji:"🎲",roots:["some","times"]},
    {word:"usually",chinese:"通常",sentence:"I <strong>usually</strong> wake up at seven.",tip:"USUALLY = USUAL + LY",emoji:"📅",roots:["usu","al","ly"]},
    {word:"about",chinese:"關於/大約",sentence:"Tell me <strong>about</strong> your weekend.",tip:"ABOUT 有兩個意思要記",emoji:"💬",roots:["a","bout"]},
    {word:"after",chinese:"在...之後",sentence:"We rest <strong>after</strong> lunch.",tip:"AFTER 和 BEFORE 相反",emoji:"⏩",roots:["af","ter"]},
    {word:"before",chinese:"在...之前",sentence:"Wash hands <strong>before</strong> eating.",tip:"BEFORE = BE + FORE",emoji:"⏪",roots:["be","fore"]},
    {word:"between",chinese:"在...之間",sentence:"The park is <strong>between</strong> two buildings.",tip:"BETWEEN 用在兩者之間",emoji:"↔️",roots:["be","tween"]},
    {word:"from",chinese:"從/來自",sentence:"I am <strong>from</strong> Taipei.",tip:"FROM 表示起點",emoji:"📍",roots:["from"]},
    {word:"into",chinese:"進入",sentence:"The frog jumped <strong>into</strong> the pond.",tip:"INTO = IN + TO",emoji:"➡️",roots:["in","to"]},
    {word:"over",chinese:"在...上方/超過",sentence:"The rainbow is <strong>over</strong> the hill.",tip:"OVER 表示上方經過",emoji:"🌈",roots:["over"]},
    {word:"under",chinese:"在...下面",sentence:"The cat hid <strong>under</strong> the bed.",tip:"UNDER 和 OVER 相反",emoji:"⬇️",roots:["un","der"]},
    {word:"up",chinese:"向上",sentence:"Look <strong>up</strong> at the sky!",tip:"UP 只有兩個字母",emoji:"⬆️",roots:["up"]},
    {word:"down",chinese:"向下",sentence:"The ball rolled <strong>down</strong> the hill.",tip:"DOWN 和 UP 相反",emoji:"⬇️",roots:["down"]},
    {word:"out",chinese:"出去/外面",sentence:"Let's go <strong>out</strong> and play.",tip:"OUT 和 IN 相反",emoji:"🚪",roots:["out"]},
    {word:"off",chinese:"離開/關掉",sentence:"Turn <strong>off</strong> the TV.",tip:"OFF 和 ON 相反",emoji:"📴",roots:["off"]},
    {word:"away",chinese:"離開/遠處",sentence:"The bird flew <strong>away</strong>.",tip:"AWAY = A + WAY",emoji:"🐦",roots:["a","way"]},
    {word:"back",chinese:"回來/背部",sentence:"Come <strong>back</strong> soon!",tip:"BACK 表示回到原處",emoji:"↩️",roots:["back"]},
    {word:"through",chinese:"穿過/通過",sentence:"We walked <strong>through</strong> the forest.",tip:"THROUGH 的 OUGH 不發音",emoji:"🌲",roots:["through"]},
    {word:"around",chinese:"周圍/到處",sentence:"Look <strong>around</strong> you.",tip:"AROUND = A + ROUND",emoji:"🔄",roots:["a","round"]},
    {word:"along",chinese:"沿著",sentence:"Walk <strong>along</strong> the river.",tip:"ALONG = A + LONG",emoji:"🏞️",roots:["a","long"]},
    {word:"across",chinese:"橫過/對面",sentence:"The store is <strong>across</strong> the street.",tip:"ACROSS = A + CROSS",emoji:"↔️",roots:["a","cross"]},
    {word:"against",chinese:"反對/靠著",sentence:"Don't lean <strong>against</strong> the wall.",tip:"AGAINST 有「對抗」的意思",emoji:"🤼",roots:["a","gainst"]},
    {word:"until",chinese:"直到",sentence:"Wait <strong>until</strong> I come back.",tip:"UNTIL = UN + TIL",emoji:"⏳",roots:["un","til"]},
    {word:"since",chinese:"自從/因為",sentence:"I have been here <strong>since</strong> morning.",tip:"SINCE 後面接時間點",emoji:"📅",roots:["since"]},
    {word:"during",chinese:"在...期間",sentence:"Be quiet <strong>during</strong> class.",tip:"DURING = DUR(持續) + ING",emoji:"⏱️",roots:["dur","ing"]},
    {word:"while",chinese:"當...的時候/一會兒",sentence:"I listen to music <strong>while</strong> I study.",tip:"WHILE 表示同時進行",emoji:"⏱️",roots:["while"]},
    {word:"because",chinese:"因為",sentence:"I am happy <strong>because</strong> you came.",tip:"BECAUSE = BE + CAUSE（原因）",emoji:"💡",roots:["be","cause"]},
    {word:"although",chinese:"雖然",sentence:"<strong>Although</strong> it rained, we had fun.",tip:"ALTHOUGH = ALL + THOUGH",emoji:"🌧️",roots:["al","though"]},
    {word:"though",chinese:"雖然/不過",sentence:"The test was hard, <strong>though</strong> I passed.",tip:"THOUGH 可放句尾",emoji:"💪",roots:["though"]},
    {word:"however",chinese:"然而/不過",sentence:"I tried hard; <strong>however</strong>, I lost.",tip:"HOWEVER = HOW + EVER",emoji:"↩️",roots:["how","ever"]},
    {word:"therefore",chinese:"因此/所以",sentence:"He was sick, <strong>therefore</strong> he stayed home.",tip:"THEREFORE = THERE + FORE",emoji:"➡️",roots:["there","fore"]},
    {word:"instead",chinese:"代替/反而",sentence:"I had fruit <strong>instead</strong> of candy.",tip:"INSTEAD = IN + STEAD（地方）",emoji:"🔀",roots:["in","stead"]},
    {word:"without",chinese:"沒有/不帶",sentence:"Don't leave <strong>without</strong> me!",tip:"WITHOUT = WITH + OUT",emoji:"🚫",roots:["with","out"]},
    {word:"within",chinese:"在...之內",sentence:"Stay <strong>within</strong> the lines.",tip:"WITHIN = WITH + IN",emoji:"⭕",roots:["with","in"]},
    {word:"toward",chinese:"朝向",sentence:"He walked <strong>toward</strong> the door.",tip:"TOWARD = TO + WARD（方向）",emoji:"➡️",roots:["to","ward"]},
    {word:"among",chinese:"在...之中",sentence:"She sat <strong>among</strong> her friends.",tip:"AMONG 用在三個以上",emoji:"👥",roots:["a","mong"]},
    {word:"above",chinese:"在...上方",sentence:"The plane flew <strong>above</strong> the clouds.",tip:"ABOVE = A + BOVE",emoji:"⬆️",roots:["a","bove"]},
    {word:"below",chinese:"在...下方",sentence:"Fish swim <strong>below</strong> the surface.",tip:"BELOW = BE + LOW",emoji:"⬇️",roots:["be","low"]},
    {word:"behind",chinese:"在...後面",sentence:"The cat hid <strong>behind</strong> the sofa.",tip:"BEHIND = BE + HIND（後面）",emoji:"🔙",roots:["be","hind"]},
    {word:"beside",chinese:"在...旁邊",sentence:"Sit <strong>beside</strong> me.",tip:"BESIDE = BE + SIDE",emoji:"↔️",roots:["be","side"]},
    {word:"beyond",chinese:"超越/在...之外",sentence:"The view <strong>beyond</strong> the hill is amazing.",tip:"BEYOND = BE + YOND",emoji:"🌄",roots:["be","yond"]},
    {word:"near",chinese:"靠近",sentence:"The store is <strong>near</strong> my house.",tip:"NEAR 和 FAR 相反",emoji:"📍",roots:["near"]},
    {word:"far",chinese:"遠的",sentence:"The airport is very <strong>far</strong>.",tip:"FAR 和 NEAR 相反",emoji:"🌙",roots:["far"]},
    {word:"well",chinese:"好地/健康的",sentence:"She sings very <strong>well</strong>.",tip:"WELL 是 good 的副詞形式",emoji:"👏",roots:["well"]},
    {word:"better",chinese:"更好的",sentence:"Today is <strong>better</strong> than yesterday.",tip:"BETTER 是 good 的比較級",emoji:"📈",roots:["bet","ter"]},
    {word:"best",chinese:"最好的",sentence:"You are the <strong>best</strong>!",tip:"BEST 是 good 的最高級",emoji:"🏆",roots:["best"]},
    {word:"less",chinese:"更少的",sentence:"I eat <strong>less</strong> sugar now.",tip:"LESS 和 MORE 相反",emoji:"➖",roots:["less"]},
    {word:"least",chinese:"最少的",sentence:"This costs the <strong>least</strong>.",tip:"LEAST 是 little 的最高級",emoji:"🤏",roots:["least"]},
    {word:"enough",chinese:"足夠的",sentence:"Do you have <strong>enough</strong> time?",tip:"ENOUGH 的 GH 不發音",emoji:"👌",roots:["e","nough"]},
    {word:"quite",chinese:"相當/蠻",sentence:"It is <strong>quite</strong> cold today.",tip:"QUITE 和 QUIET 很像但不同",emoji:"😮",roots:["quite"]},
    {word:"rather",chinese:"相當/寧可",sentence:"I would <strong>rather</strong> stay home.",tip:"RATHER 表示偏好",emoji:"🤔",roots:["rath","er"]},
    {word:"pretty",chinese:"漂亮的/相當",sentence:"She is <strong>pretty</strong> smart.",tip:"PRETTY 當副詞表示「相當」",emoji:"🌸",roots:["pret","ty"]},
    {word:"almost",chinese:"幾乎",sentence:"I <strong>almost</strong> forgot!",tip:"ALMOST = AL + MOST",emoji:"😅",roots:["al","most"]},
    {word:"together",chinese:"一起",sentence:"Let's work <strong>together</strong>.",tip:"TOGETHER = TO + GET + HER",emoji:"🤝",roots:["to","geth","er"]},
    {word:"alone",chinese:"獨自/孤單的",sentence:"I don't want to be <strong>alone</strong>.",tip:"ALONE = A + LONE（孤獨的）",emoji:"🧍",roots:["a","lone"]},
    {word:"else",chinese:"其他的/另外",sentence:"What <strong>else</strong> do you need?",tip:"ELSE 常跟疑問詞一起用",emoji:"❓",roots:["else"]},
    {word:"ago",chinese:"...之前",sentence:"Two years <strong>ago</strong>, I moved here.",tip:"AGO 放在時間後面",emoji:"⏪",roots:["ago"]},
    {word:"yet",chinese:"還/尚未",sentence:"I have not finished <strong>yet</strong>.",tip:"YET 用在否定句和問句",emoji:"⏳",roots:["yet"]},
    {word:"soon",chinese:"很快/不久",sentence:"I will be there <strong>soon</strong>.",tip:"SOON 有兩個 O",emoji:"⏰",roots:["soon"]},
    {word:"later",chinese:"稍後/之後",sentence:"See you <strong>later</strong>!",tip:"LATER = LATE + R",emoji:"👋",roots:["lat","er"]},
    {word:"early",chinese:"早的/提早",sentence:"I wake up <strong>early</strong>.",tip:"EARLY 的 EAR 像耳朵",emoji:"🌅",roots:["ear","ly"]},
    {word:"late",chinese:"晚的/遲到",sentence:"Don't be <strong>late</strong> for class.",tip:"LATE 和 EARLY 相反",emoji:"⏰",roots:["late"]},
    {word:"high",chinese:"高的",sentence:"The mountain is very <strong>high</strong>.",tip:"HIGH 的 GH 不發音",emoji:"🏔️",roots:["high"]},
    {word:"low",chinese:"低的",sentence:"Speak in a <strong>low</strong> voice.",tip:"LOW 和 HIGH 相反",emoji:"⬇️",roots:["low"]},
    {word:"large",chinese:"大的",sentence:"We need a <strong>large</strong> box.",tip:"LARGE 比 BIG 正式",emoji:"📦",roots:["large"]},
    {word:"great",chinese:"很棒的/偉大的",sentence:"You did a <strong>great</strong> job!",tip:"GREAT 的 EA 發 /eɪ/",emoji:"🌟",roots:["great"]},
    {word:"little",chinese:"小的/一點點",sentence:"The <strong>little</strong> puppy is so cute.",tip:"LITTLE 有兩個 T",emoji:"🤏",roots:["lit","tle"]},
    {word:"whole",chinese:"整個的/全部",sentence:"I read the <strong>whole</strong> story.",tip:"WHOLE 的 W 不發音",emoji:"⭕",roots:["whole"]},
    {word:"real",chinese:"真實的",sentence:"Is that a <strong>real</strong> dinosaur?",tip:"REAL 和 REALLY 是一家人",emoji:"💎",roots:["real"]},
    {word:"true",chinese:"真的/正確的",sentence:"Is the story <strong>true</strong>?",tip:"TRUE 和 REAL 意思接近",emoji:"✅",roots:["true"]},
    {word:"clear",chinese:"清楚的/晴朗的",sentence:"The sky is <strong>clear</strong> tonight.",tip:"CLEAR 想到透明乾淨",emoji:"💧",roots:["clear"]},
    {word:"dark",chinese:"黑暗的",sentence:"It gets <strong>dark</strong> at night.",tip:"DARK 和 LIGHT 相反",emoji:"🌑",roots:["dark"]},
    {word:"light",chinese:"光/輕的/亮的",sentence:"Turn on the <strong>light</strong>, please.",tip:"LIGHT 有三個意思",emoji:"💡",roots:["light"]},
    {word:"hot",chinese:"熱的",sentence:"Be careful, the soup is <strong>hot</strong>!",tip:"HOT 和 COLD 相反",emoji:"🔥",roots:["hot"]},
    {word:"nice",chinese:"好的/友善的",sentence:"Have a <strong>nice</strong> day!",tip:"NICE 和 ICE 押韻",emoji:"😊",roots:["nice"]},
    {word:"fine",chinese:"好的/很好",sentence:"I feel <strong>fine</strong>, thanks.",tip:"FINE 的意思很多",emoji:"👌",roots:["fine"]},
    {word:"beautiful",chinese:"美麗的",sentence:"The sunset is <strong>beautiful</strong>.",tip:"BEAUTIFUL = BEAUTI + FUL",emoji:"🌅",roots:["beauti","ful"]},
    {word:"wonderful",chinese:"很棒的/美妙的",sentence:"We had a <strong>wonderful</strong> vacation.",tip:"WONDERFUL = WONDER + FUL",emoji:"🎉",roots:["wonder","ful"]},
    {word:"terrible",chinese:"糟糕的/可怕的",sentence:"I had a <strong>terrible</strong> dream.",tip:"TERRIBLE = TERR(恐懼) + IBLE",emoji:"😱",roots:["terr","ible"]},
    {word:"sorry",chinese:"抱歉的",sentence:"I am <strong>sorry</strong> I broke it.",tip:"SORRY 有兩個 R",emoji:"🙏",roots:["sor","ry"]},
    {word:"afraid",chinese:"害怕的",sentence:"Don't be <strong>afraid</strong> of the dark.",tip:"AFRAID = A + FRAID",emoji:"😨",roots:["a","fraid"]},
    {word:"certain",chinese:"確定的/某些",sentence:"I am <strong>certain</strong> he will come.",tip:"CERTAIN = CERT(確定) + AIN",emoji:"✅",roots:["cer","tain"]},
    {word:"simple",chinese:"簡單的",sentence:"The recipe is very <strong>simple</strong>.",tip:"SIMPLE 和 EASY 意思相近",emoji:"👌",roots:["sim","ple"]},
    {word:"special",chinese:"特別的",sentence:"Today is a <strong>special</strong> day.",tip:"SPECIAL = SPEC(看) + IAL",emoji:"⭐",roots:["spec","ial"]},
    {word:"poor",chinese:"貧窮的/可憐的",sentence:"The <strong>poor</strong> puppy is lost.",tip:"POOR 和 RICH 相反",emoji:"😢",roots:["poor"]},
    {word:"rich",chinese:"富有的",sentence:"The soil here is very <strong>rich</strong>.",tip:"RICH 和 POOR 相反",emoji:"💰",roots:["rich"]},
    {word:"strong",chinese:"強壯的",sentence:"The wind is very <strong>strong</strong>.",tip:"STRONG 和 WEAK 相反",emoji:"💪",roots:["strong"]},
    {word:"weak",chinese:"弱的",sentence:"I feel <strong>weak</strong> when I am sick.",tip:"WEAK 和 STRONG 相反",emoji:"🤒",roots:["weak"]},
    {word:"deep",chinese:"深的",sentence:"The ocean is very <strong>deep</strong>.",tip:"DEEP 有兩個 E",emoji:"🌊",roots:["deep"]},
    {word:"wide",chinese:"寬的",sentence:"Open your eyes <strong>wide</strong>.",tip:"WIDE 和 NARROW 相反",emoji:"↔️",roots:["wide"]},
    {word:"heavy",chinese:"重的",sentence:"This box is too <strong>heavy</strong> for me.",tip:"HEAVY 和 LIGHT 相反",emoji:"🏋️",roots:["heav","y"]},
    {word:"kind",chinese:"善良的/種類",sentence:"Be <strong>kind</strong> to others.",tip:"KIND 有兩個意思",emoji:"💖",roots:["kind"]},
    {word:"dear",chinese:"親愛的/昂貴的",sentence:"<strong>Dear</strong> Mom, I love you.",tip:"DEAR 寫信時用",emoji:"💌",roots:["dear"]},
    {word:"in",chinese:"在...裡面",sentence:"The toy is <strong>in</strong> the box.",tip:"IN 和 OUT 相反",emoji:"📦",roots:["in"]},
    {word:"on",chinese:"在...上面",sentence:"The cup is <strong>on</strong> the shelf.",tip:"ON 表示接觸在上面",emoji:"📚",roots:["on"]},
    {word:"at",chinese:"在（地點/時間）",sentence:"I wake up <strong>at</strong> seven.",tip:"AT 用在具體地點和時間",emoji:"📍",roots:["at"]},
    {word:"to",chinese:"到/向",sentence:"I walk <strong>to</strong> the park.",tip:"TO 表示方向或目的",emoji:"➡️",roots:["to"]},
    {word:"for",chinese:"為了/給",sentence:"This gift is <strong>for</strong> you.",tip:"FOR 表示目的或對象",emoji:"🎁",roots:["for"]},
    {word:"with",chinese:"和/跟/帶著",sentence:"I play <strong>with</strong> my friends.",tip:"WITH 表示一起或使用",emoji:"🤝",roots:["with"]},
    {word:"of",chinese:"...的/屬於",sentence:"A glass <strong>of</strong> milk, please.",tip:"OF 是英文第二常見的字",emoji:"📎",roots:["of"]},
    {word:"by",chinese:"被/在旁邊/搭乘",sentence:"The story was written <strong>by</strong> him.",tip:"BY 有很多意思",emoji:"📖",roots:["by"]},
    {word:"as",chinese:"作為/像...一樣",sentence:"She works <strong>as</strong> a teacher.",tip:"AS 用來比較或表身份",emoji:"🔄",roots:["as"]},
    {word:"thing",chinese:"東西/事情",sentence:"What is that <strong>thing</strong>?",tip:"THING 可以指任何東西",emoji:"🔮",roots:["thing"]},
    {word:"people",chinese:"人們",sentence:"Many <strong>people</strong> love this park.",tip:"PEOPLE 的複數不加 S",emoji:"👥",roots:["peo","ple"]},
    {word:"man",chinese:"男人",sentence:"That <strong>man</strong> is very tall.",tip:"MAN 的複數是 MEN",emoji:"👨",roots:["man"]},
    {word:"woman",chinese:"女人",sentence:"The <strong>woman</strong> is a pilot.",tip:"WOMAN 的複數是 WOMEN",emoji:"👩",roots:["wom","an"]},
    {word:"child",chinese:"小孩",sentence:"Every <strong>child</strong> needs love.",tip:"CHILD 的複數是 CHILDREN",emoji:"🧒",roots:["child"]},
    {word:"children",chinese:"小孩們",sentence:"The <strong>children</strong> are laughing.",tip:"CHILDREN 是 CHILD 的複數",emoji:"👦👧",roots:["child","ren"]},
    {word:"world",chinese:"世界",sentence:"The <strong>world</strong> is full of wonder.",tip:"WORLD 裡面有 OR",emoji:"🌍",roots:["world"]},
    {word:"life",chinese:"生活/生命",sentence:"I love my <strong>life</strong>!",tip:"LIFE 的複數是 LIVES",emoji:"❤️",roots:["life"]},
    {word:"house",chinese:"房子",sentence:"We painted our <strong>house</strong> blue.",tip:"HOUSE 裡面有 MOUSE",emoji:"🏠",roots:["house"]},
    {word:"place",chinese:"地方",sentence:"This is a nice <strong>place</strong> to rest.",tip:"PLACE 和 SPACE 押韻",emoji:"📍",roots:["place"]},
    {word:"room",chinese:"房間",sentence:"My <strong>room</strong> is very tidy.",tip:"ROOM 有兩個 O",emoji:"🛏️",roots:["room"]},
    {word:"night",chinese:"夜晚",sentence:"Good <strong>night</strong>! Sweet dreams.",tip:"NIGHT 的 GH 不發音",emoji:"🌙",roots:["night"]},
    {word:"morning",chinese:"早上",sentence:"Good <strong>morning</strong>, everyone!",tip:"MORNING = MORN + ING",emoji:"🌅",roots:["morn","ing"]},
    {word:"way",chinese:"路/方式",sentence:"This is the best <strong>way</strong> to learn.",tip:"WAY 可以指路或方法",emoji:"🛤️",roots:["way"]},
    {word:"end",chinese:"結束/結尾",sentence:"The <strong>end</strong> of the movie was great.",tip:"END 只有三個字母",emoji:"🔚",roots:["end"]},
    {word:"part",chinese:"部分",sentence:"This is the fun <strong>part</strong>.",tip:"PART 和 WHOLE 相反",emoji:"🧩",roots:["part"]},
    {word:"number",chinese:"數字/號碼",sentence:"Pick a <strong>number</strong> from one to ten.",tip:"NUMBER = NUMB + ER",emoji:"🔢",roots:["num","ber"]},
    {word:"word",chinese:"字/單字",sentence:"Can you spell this <strong>word</strong>?",tip:"WORD 和 WORLD 很像",emoji:"📝",roots:["word"]},
    {word:"story",chinese:"故事",sentence:"Read me a <strong>story</strong>, please.",tip:"STORY 的複數是 STORIES",emoji:"📖",roots:["stor","y"]},
    {word:"nothing",chinese:"什麼都沒有",sentence:"There is <strong>nothing</strong> to worry about.",tip:"NOTHING = NO + THING",emoji:"0️⃣",roots:["no","thing"]},
    {word:"something",chinese:"某個東西",sentence:"I want <strong>something</strong> to drink.",tip:"SOMETHING = SOME + THING",emoji:"🤔",roots:["some","thing"]},
    {word:"everything",chinese:"每樣東西",sentence:"<strong>Everything</strong> will be okay.",tip:"EVERYTHING = EVERY + THING",emoji:"💯",roots:["every","thing"]},
    {word:"everyone",chinese:"每個人",sentence:"<strong>Everyone</strong> likes her.",tip:"EVERYONE = EVERY + ONE",emoji:"👥",roots:["every","one"]},
    {word:"someone",chinese:"某個人",sentence:"<strong>Someone</strong> left a message.",tip:"SOMEONE = SOME + ONE",emoji:"🧑",roots:["some","one"]},
    {word:"anyone",chinese:"任何人",sentence:"Does <strong>anyone</strong> know the answer?",tip:"ANYONE = ANY + ONE",emoji:"❓",roots:["any","one"]},
    {word:"nobody",chinese:"沒有人",sentence:"<strong>Nobody</strong> is perfect.",tip:"NOBODY = NO + BODY",emoji:"🚫",roots:["no","body"]},
    {word:"anything",chinese:"任何東西",sentence:"Is there <strong>anything</strong> I can help with?",tip:"ANYTHING = ANY + THING",emoji:"❓",roots:["any","thing"]},
    {word:"right",chinese:"對的/右邊",sentence:"Turn <strong>right</strong> at the corner.",tip:"RIGHT 有兩個意思：對的和右邊",emoji:"✅",roots:["right"]},
    {word:"wrong",chinese:"錯的",sentence:"That answer is <strong>wrong</strong>.",tip:"WRONG 的 W 不發音",emoji:"❌",roots:["wrong"]},
    {word:"sure",chinese:"確定的/當然",sentence:"Are you <strong>sure</strong> about that?",tip:"SURE 聽起來像 SHORE",emoji:"👍",roots:["sure"]},
    {word:"able",chinese:"能夠的",sentence:"I am <strong>able</strong> to finish on time.",tip:"ABLE 常加在字後面變形容詞",emoji:"💪",roots:["able"]},
    {word:"ready",chinese:"準備好的",sentence:"Are you <strong>ready</strong> for the test?",tip:"READY = READ + Y",emoji:"✅",roots:["read","y"]},
    {word:"free",chinese:"自由的/免費的",sentence:"This app is <strong>free</strong> to download.",tip:"FREE 有「自由」和「免費」兩個意思",emoji:"🆓",roots:["free"]},
    {word:"full",chinese:"滿的/飽的",sentence:"My stomach is <strong>full</strong>.",tip:"FULL 和 EMPTY 相反",emoji:"🫃",roots:["full"]},
    {word:"empty",chinese:"空的",sentence:"The bottle is <strong>empty</strong>.",tip:"EMPTY 和 FULL 相反",emoji:"🥛",roots:["emp","ty"]},
    {word:"young",chinese:"年輕的",sentence:"She looks very <strong>young</strong>.",tip:"YOUNG 和 OLD 相反",emoji:"👶",roots:["young"]},
    {word:"fast",chinese:"快的",sentence:"Cheetahs are very <strong>fast</strong>.",tip:"FAST 和 SLOW 相反",emoji:"🏎️",roots:["fast"]},
    {word:"slow",chinese:"慢的",sentence:"The turtle is very <strong>slow</strong>.",tip:"SLOW 和 FAST 相反",emoji:"🐢",roots:["slow"]},
    {word:"hard",chinese:"困難的/硬的/努力",sentence:"I study <strong>hard</strong> for the exam.",tip:"HARD 有多個意思",emoji:"💎",roots:["hard"]},
    {word:"easy",chinese:"容易的",sentence:"This puzzle is <strong>easy</strong>.",tip:"EASY 和 HARD 相反",emoji:"😎",roots:["eas","y"]},
    {word:"possible",chinese:"可能的",sentence:"Anything is <strong>possible</strong>!",tip:"POSSIBLE = POSS + IBLE",emoji:"🌟",roots:["poss","ible"]},
    {word:"important",chinese:"重要的",sentence:"Exercise is <strong>important</strong>.",tip:"IMPORTANT = IM + PORT + ANT",emoji:"⭐",roots:["im","port","ant"]},
    {word:"make",chinese:"製作/使得",sentence:"Let's <strong>make</strong> a paper airplane.",tip:"MAKE 的過去式是 MADE",emoji:"🎨",roots:["make"]},
    {word:"think",chinese:"想/認為",sentence:"I <strong>think</strong> you are right.",tip:"THINK 的過去式是 THOUGHT",emoji:"🤔",roots:["think"]},
    {word:"know",chinese:"知道",sentence:"I <strong>know</strong> the answer!",tip:"KNOW 的 K 不發音",emoji:"💡",roots:["know"]},
    {word:"look",chinese:"看",sentence:"<strong>Look</strong> at the stars!",tip:"LOOK 有兩個 O",emoji:"👀",roots:["look"]},
    {word:"find",chinese:"找到",sentence:"Can you <strong>find</strong> your shoes?",tip:"FIND 的過去式是 FOUND",emoji:"🔍",roots:["find"]},
    {word:"put",chinese:"放",sentence:"<strong>Put</strong> your toys away.",tip:"PUT 三態同形：put-put-put",emoji:"👇",roots:["put"]},
    {word:"try",chinese:"嘗試",sentence:"<strong>Try</strong> your best!",tip:"TRY 的過去式是 TRIED",emoji:"💪",roots:["try"]},
    {word:"ask",chinese:"問/要求",sentence:"Can I <strong>ask</strong> a question?",tip:"ASK 只有三個字母",emoji:"❓",roots:["ask"]},
    {word:"need",chinese:"需要",sentence:"I <strong>need</strong> a glass of water.",tip:"NEED 有兩個 E",emoji:"🆘",roots:["need"]},
    {word:"turn",chinese:"轉/輪到",sentence:"It is your <strong>turn</strong> now.",tip:"TURN 可以是轉或輪流",emoji:"↩️",roots:["turn"]},
    {word:"call",chinese:"叫/打電話",sentence:"I will <strong>call</strong> you tonight.",tip:"CALL 有兩個 L",emoji:"📞",roots:["call"]},
    {word:"keep",chinese:"保持/繼續",sentence:"<strong>Keep</strong> going! You are doing great.",tip:"KEEP 有兩個 E",emoji:"💪",roots:["keep"]},
    {word:"let",chinese:"讓/允許",sentence:"<strong>Let</strong> me try again.",tip:"LET 只有三個字母",emoji:"👍",roots:["let"]},
    {word:"begin",chinese:"開始",sentence:"Let's <strong>begin</strong> our adventure!",tip:"BEGIN 的過去式是 BEGAN",emoji:"▶️",roots:["be","gin"]},
    {word:"seem",chinese:"似乎/看起來",sentence:"You <strong>seem</strong> happy today!",tip:"SEEM 有兩個 E",emoji:"🤔",roots:["seem"]},
    {word:"help",chinese:"幫助",sentence:"Can you <strong>help</strong> me carry this?",tip:"HELP 是很常用的求助語",emoji:"🆘",roots:["help"]},
    {word:"show",chinese:"展示/表演",sentence:"<strong>Show</strong> me your painting.",tip:"SHOW 的過去式是 SHOWED",emoji:"👀",roots:["show"]},
    {word:"hear",chinese:"聽到",sentence:"I can <strong>hear</strong> birds singing.",tip:"HEAR 裡面有 EAR（耳朵）",emoji:"👂",roots:["hear"]},
    {word:"move",chinese:"移動/搬家",sentence:"Please don't <strong>move</strong>.",tip:"MOVE 和 MOVIE 是一家人",emoji:"🏃",roots:["move"]},
    {word:"change",chinese:"改變/零錢",sentence:"People can <strong>change</strong> for the better.",tip:"CHANGE 裡面有 HANG",emoji:"🔄",roots:["change"]},
    {word:"bring",chinese:"帶來",sentence:"Please <strong>bring</strong> your homework.",tip:"BRING 的過去式是 BROUGHT",emoji:"🤲",roots:["bring"]},
    {word:"pay",chinese:"付錢",sentence:"I will <strong>pay</strong> for the ticket.",tip:"PAY 的過去式是 PAID",emoji:"💵",roots:["pay"]},
    {word:"meet",chinese:"遇見/認識",sentence:"Nice to <strong>meet</strong> you!",tip:"MEET 有兩個 E",emoji:"🤝",roots:["meet"]},
    {word:"mean",chinese:"意思是/吝嗇的",sentence:"What does this <strong>mean</strong>?",tip:"MEAN 有「意思是」和「壞心的」兩個意思",emoji:"🤔",roots:["mean"]},
    {word:"become",chinese:"變成",sentence:"I want to <strong>become</strong> a scientist.",tip:"BECOME = BE + COME",emoji:"🦋",roots:["be","come"]},
    {word:"leave",chinese:"離開/留下",sentence:"I <strong>leave</strong> for school at eight.",tip:"LEAVE 的過去式是 LEFT",emoji:"🚪",roots:["leave"]},
    {word:"happen",chinese:"發生",sentence:"What <strong>happen</strong>ed here?",tip:"HAPPEN = HAP(運氣) + PEN",emoji:"❗",roots:["hap","pen"]},
    {word:"love",chinese:"愛/喜愛",sentence:"I <strong>love</strong> reading stories.",tip:"LOVE 裡面藏著一顆心",emoji:"❤️",roots:["love"]},
    {word:"country",chinese:"國家/鄉下",sentence:"Japan is a beautiful <strong>country</strong>.",tip:"COUNTRY = COUN + TRY",emoji:"🌏",roots:["coun","try"]},
    {word:"city",chinese:"城市",sentence:"This <strong>city</strong> has many tall buildings.",tip:"CITY 的複數是 CITIES",emoji:"🏙️",roots:["ci","ty"]},
    {word:"family",chinese:"家庭/家人",sentence:"I enjoy spending time with my <strong>family</strong>.",tip:"FAMILY = FAM + I + LY",emoji:"👨‍👩‍👧‍👦",roots:["fam","ily"]},
    {word:"body",chinese:"身體",sentence:"Stretching is good for your <strong>body</strong>.",tip:"BODY 的複數是 BODIES",emoji:"🧍",roots:["bod","y"]},
    {word:"side",chinese:"邊/旁邊",sentence:"Walk on the right <strong>side</strong>.",tip:"SIDE 和 HIDE 押韻",emoji:"↔️",roots:["side"]},
    {word:"point",chinese:"點/分數/指",sentence:"You got the highest <strong>point</strong>s!",tip:"POINT = POIN + T",emoji:"👉",roots:["point"]},
    {word:"fact",chinese:"事實",sentence:"That is a known <strong>fact</strong>.",tip:"FACT = F + ACT",emoji:"📋",roots:["fact"]},
    {word:"power",chinese:"力量/電力",sentence:"Knowledge is <strong>power</strong>.",tip:"POWER = POW + ER",emoji:"⚡",roots:["pow","er"]},
    {word:"lot",chinese:"很多",sentence:"I have a <strong>lot</strong> of homework.",tip:"A LOT OF 表示很多",emoji:"📚",roots:["lot"]},
    {word:"believe",chinese:"相信",sentence:"I <strong>believe</strong> in you!",tip:"BELIEVE 裡面有 LIE（謊言）但要相信！",emoji:"🙏",roots:["be","lieve"]},
    {word:"remember",chinese:"記得",sentence:"<strong>Remember</strong> to lock the door.",tip:"REMEMBER = RE + MEMBER",emoji:"🧠",roots:["re","mem","ber"]},
    {word:"use",chinese:"使用",sentence:"Can I <strong>use</strong> your eraser?",tip:"USE 當動詞 S 發 /z/",emoji:"✍️",roots:["use"]},
    {word:"tell",chinese:"告訴",sentence:"<strong>Tell</strong> me what happened.",tip:"TELL 有兩個 L",emoji:"🗣️",roots:["tell"]},
    {word:"wait",chinese:"等待",sentence:"Please <strong>wait</strong> for me.",tip:"WAIT 的 AI 發長音",emoji:"⏳",roots:["wait"]},
    {word:"follow",chinese:"跟隨",sentence:"<strong>Follow</strong> the leader!",tip:"FOLLOW = FOL + LOW",emoji:"🚶",roots:["fol","low"]},
    {word:"stop",chinese:"停止",sentence:"<strong>Stop</strong> at the red light.",tip:"STOP 是八角形紅色標誌",emoji:"🛑",roots:["stop"]},
    {word:"start",chinese:"開始",sentence:"Let's <strong>start</strong> the game!",tip:"START 和 STOP 相反",emoji:"▶️",roots:["start"]},
    {word:"hour",chinese:"小時",sentence:"The movie is two <strong>hour</strong>s long.",tip:"HOUR 的 H 不發音",emoji:"🕐",roots:["hour"]},
    {word:"minute",chinese:"分鐘",sentence:"Wait one <strong>minute</strong>, please.",tip:"MINUTE 當「微小」時重音不同",emoji:"⏱️",roots:["min","ute"]},
    {word:"second",chinese:"第二/秒",sentence:"I will be back in a <strong>second</strong>.",tip:"SECOND 有「第二」和「秒」兩個意思",emoji:"⏱️",roots:["sec","ond"]},
    {word:"half",chinese:"一半",sentence:"I ate <strong>half</strong> of the pie.",tip:"HALF 的 L 不發音",emoji:"🍕",roots:["half"]},
    {word:"problem",chinese:"問題/麻煩",sentence:"No <strong>problem</strong>! I can do it.",tip:"PROBLEM = PROB + LEM",emoji:"🤔",roots:["prob","lem"]},
    {word:"question",chinese:"問題（提問）",sentence:"I have a <strong>question</strong> for you.",tip:"QUESTION = QUEST(尋找) + ION",emoji:"❓",roots:["quest","ion"]},
    {word:"answer",chinese:"答案/回答",sentence:"Do you know the <strong>answer</strong>?",tip:"ANSWER 的 W 不發音",emoji:"💡",roots:["an","swer"]},
    {word:"idea",chinese:"主意/想法",sentence:"I have a great <strong>idea</strong>!",tip:"IDEA 有三個音節",emoji:"💡",roots:["i","dea"]},
    {word:"reason",chinese:"原因/理由",sentence:"There is a good <strong>reason</strong> for it.",tip:"REASON = REA + SON",emoji:"🤔",roots:["rea","son"]},
    {word:"example",chinese:"例子",sentence:"Can you give me an <strong>example</strong>?",tip:"EXAMPLE = EX + AMPLE",emoji:"📋",roots:["ex","am","ple"]},
    {word:"understand",chinese:"了解/明白",sentence:"I <strong>understand</strong> now!",tip:"UNDERSTAND = UNDER + STAND",emoji:"💡",roots:["under","stand"]},
    {word:"game",chinese:"遊戲/比賽",sentence:"Let's play a board <strong>game</strong>.",tip:"GAME 和 NAME 押韻",emoji:"🎮",roots:["game"]},
    {word:"picture",chinese:"圖片/照片",sentence:"I took a <strong>picture</strong> of the sunset.",tip:"PICTURE = PICT(畫) + URE",emoji:"🖼️",roots:["pic","ture"]},
    {word:"movie",chinese:"電影",sentence:"We watched a funny <strong>movie</strong>.",tip:"MOVIE 和 MOVE 是一家人",emoji:"🎬",roots:["mov","ie"]},
    {word:"letter",chinese:"信/字母",sentence:"I wrote a <strong>letter</strong> to my friend.",tip:"LETTER 有兩個 T",emoji:"✉️",roots:["let","ter"]},
    {word:"age",chinese:"年齡",sentence:"What <strong>age</strong> did you start school?",tip:"AGE 只有三個字母",emoji:"🎂",roots:["age"]},
    {word:"air",chinese:"空氣",sentence:"Fresh <strong>air</strong> feels wonderful.",tip:"AIR 只有三個字母",emoji:"💨",roots:["air"]},
    {word:"line",chinese:"線/排隊",sentence:"Stand in <strong>line</strong>, please.",tip:"LINE 和 FINE 押韻",emoji:"➖",roots:["line"]},
    {word:"class",chinese:"課/班級",sentence:"We have art <strong>class</strong> today.",tip:"CLASS 有兩個 S",emoji:"🏫",roots:["class"]},
    {word:"heart",chinese:"心/心臟",sentence:"I love you with all my <strong>heart</strong>.",tip:"HEART 裡面有 EAR 和 ART",emoji:"❤️",roots:["heart"]},
    {word:"river",chinese:"河流",sentence:"We played by the <strong>river</strong>.",tip:"RIVER = RIV + ER",emoji:"🏞️",roots:["riv","er"]},
    {word:"sea",chinese:"海",sentence:"The <strong>sea</strong> is so blue and calm.",tip:"SEA 和 SEE 發音一樣",emoji:"🌊",roots:["sea"]},
    {word:"land",chinese:"陸地/土地",sentence:"The bird landed on <strong>land</strong>.",tip:"LAND 和 SAND 押韻",emoji:"🏝️",roots:["land"]},
    {word:"mountain",chinese:"山",sentence:"We climbed a <strong>mountain</strong>.",tip:"MOUNTAIN = MOUNT + AIN",emoji:"🏔️",roots:["moun","tain"]},
    {word:"town",chinese:"小鎮",sentence:"Our <strong>town</strong> is very quiet.",tip:"TOWN 和 DOWN 押韻",emoji:"🏘️",roots:["town"]},
    {word:"street",chinese:"街道",sentence:"Look both ways before crossing the <strong>street</strong>.",tip:"STREET 有兩個 E",emoji:"🛣️",roots:["street"]},
    {word:"road",chinese:"路/道路",sentence:"The <strong>road</strong> goes through the forest.",tip:"ROAD 和 TOAD（蟾蜍）押韻",emoji:"🛤️",roots:["road"]},
    {word:"garden",chinese:"花園",sentence:"We grow tomatoes in our <strong>garden</strong>.",tip:"GARDEN = GARD + EN",emoji:"🌷",roots:["gar","den"]},
    {word:"snow",chinese:"雪",sentence:"Let's play in the <strong>snow</strong>!",tip:"SNOW 和 KNOW 押韻",emoji:"❄️",roots:["snow"]},
    {word:"rain",chinese:"雨/下雨",sentence:"I love the sound of <strong>rain</strong>.",tip:"RAIN 和 TRAIN 押韻",emoji:"🌧️",roots:["rain"]},
    {word:"wind",chinese:"風",sentence:"The <strong>wind</strong> blows leaves around.",tip:"WIND 也可以是「繞」(發音不同)",emoji:"🌬️",roots:["wind"]},
    {word:"animal",chinese:"動物",sentence:"What <strong>animal</strong> do you like best?",tip:"ANIMAL = ANI + MAL",emoji:"🐾",roots:["ani","mal"]},
    {word:"horse",chinese:"馬",sentence:"The <strong>horse</strong> galloped across the field.",tip:"HORSE 裡面有 OR",emoji:"🐴",roots:["horse"]},
    {word:"paper",chinese:"紙",sentence:"Write your name on the <strong>paper</strong>.",tip:"PAPER = PA + PER",emoji:"📄",roots:["pa","per"]},
    {word:"son",chinese:"兒子",sentence:"He is a kind <strong>son</strong>.",tip:"SON 和 SUN 發音一樣",emoji:"👦",roots:["son"]},
    {word:"daughter",chinese:"女兒",sentence:"His <strong>daughter</strong> loves to paint.",tip:"DAUGHTER 的 GH 不發音",emoji:"👧",roots:["daugh","ter"]},
    {word:"baby",chinese:"嬰兒",sentence:"The <strong>baby</strong> is smiling.",tip:"BABY 的複數是 BABIES",emoji:"👶",roots:["ba","by"]},
    {word:"king",chinese:"國王",sentence:"The <strong>king</strong> sits on a golden throne.",tip:"KING 和 SING 押韻",emoji:"👑",roots:["king"]},
    {word:"voice",chinese:"聲音/嗓音",sentence:"She has a lovely <strong>voice</strong>.",tip:"VOICE 裡面有 ICE",emoji:"🗣️",roots:["voice"]},
    {word:"sense",chinese:"感覺/意義",sentence:"That makes <strong>sense</strong>!",tip:"SENSE 有五種：視聽嗅味觸",emoji:"🧠",roots:["sense"]},
    {word:"matter",chinese:"事情/物質/重要",sentence:"It doesn't <strong>matter</strong>.",tip:"MATTER 有兩個 T",emoji:"❗",roots:["mat","ter"]},
    {word:"care",chinese:"關心/照顧",sentence:"I <strong>care</strong> about my friends.",tip:"CARE 和 SHARE 押韻",emoji:"💕",roots:["care"]},
    {word:"stand",chinese:"站立",sentence:"Please <strong>stand</strong> up.",tip:"STAND 裡面有 AND",emoji:"🧍",roots:["stand"]},
    {word:"catch",chinese:"抓住/接住",sentence:"<strong>Catch</strong> the ball!",tip:"CATCH 的 TCH 發 /tʃ/",emoji:"🤾",roots:["catch"]},
    {word:"carry",chinese:"攜帶/搬運",sentence:"I <strong>carry</strong> my lunch to school.",tip:"CARRY 有兩個 R",emoji:"🎒",roots:["car","ry"]},
    {word:"cut",chinese:"切/剪",sentence:"<strong>Cut</strong> the paper along the line.",tip:"CUT 三態同形：cut-cut-cut",emoji:"✂️",roots:["cut"]},
    {word:"pick",chinese:"挑選/撿起",sentence:"<strong>Pick</strong> your favorite color.",tip:"PICK 和 KICK 押韻",emoji:"👆",roots:["pick"]},
    {word:"break",chinese:"打破/休息",sentence:"Be careful not to <strong>break</strong> it!",tip:"BREAK 的 EA 發 /eɪ/",emoji:"💔",roots:["break"]},
    {word:"grow",chinese:"成長/種植",sentence:"Plants <strong>grow</strong> toward the sun.",tip:"GROW 的過去式是 GREW",emoji:"🌱",roots:["grow"]},
    {word:"hold",chinese:"握住/抱著",sentence:"<strong>Hold</strong> my hand when crossing.",tip:"HOLD 的過去式是 HELD",emoji:"🤝",roots:["hold"]},
    {word:"spend",chinese:"花費（時間/金錢）",sentence:"I <strong>spend</strong> time reading every day.",tip:"SPEND 的過去式是 SPENT",emoji:"⏰",roots:["spend"]},
    {word:"win",chinese:"贏",sentence:"I hope our team will <strong>win</strong>!",tip:"WIN 的過去式是 WON",emoji:"🏆",roots:["win"]},
    {word:"lose",chinese:"輸/丟失",sentence:"Don't <strong>lose</strong> your ticket!",tip:"LOSE 和 CHOOSE 押韻",emoji:"😢",roots:["lose"]},
    {word:"send",chinese:"寄/送",sentence:"I will <strong>send</strong> you an email.",tip:"SEND 的過去式是 SENT",emoji:"📨",roots:["send"]},
    {word:"build",chinese:"建造",sentence:"Let's <strong>build</strong> a sandcastle!",tip:"BUILD 的 UI 發 /ɪ/",emoji:"🏗️",roots:["build"]},
    {word:"set",chinese:"設定/放置",sentence:"<strong>Set</strong> the table for dinner.",tip:"SET 三態同形：set-set-set",emoji:"⚙️",roots:["set"]},
    {word:"miss",chinese:"想念/錯過",sentence:"I <strong>miss</strong> my grandparents.",tip:"MISS 有「想念」和「錯過」兩個意思",emoji:"😢",roots:["miss"]},
    {word:"enjoy",chinese:"享受",sentence:"I <strong>enjoy</strong> playing with my friends.",tip:"ENJOY = EN + JOY",emoji:"😊",roots:["en","joy"]},
    {word:"wish",chinese:"希望/祝福",sentence:"I <strong>wish</strong> upon a star.",tip:"WISH 和 FISH 押韻",emoji:"🌠",roots:["wish"]},
    {word:"wonder",chinese:"想知道/驚嘆",sentence:"I <strong>wonder</strong> what is inside.",tip:"WONDER = WON + DER",emoji:"🤔",roots:["won","der"]},
    {word:"hope",chinese:"希望",sentence:"I <strong>hope</strong> you feel better.",tip:"HOPE 和 ROPE 押韻",emoji:"🙏",roots:["hope"]},
    {word:"thank",chinese:"感謝",sentence:"<strong>Thank</strong> you for the gift!",tip:"THANK 和 THINK 很像",emoji:"🙏",roots:["thank"]},
    {word:"add",chinese:"加/增加",sentence:"<strong>Add</strong> two plus three.",tip:"ADD 有兩個 D",emoji:"➕",roots:["add"]},
    {word:"smile",chinese:"微笑",sentence:"Her <strong>smile</strong> lights up the room.",tip:"SMILE 讓人開心",emoji:"😊",roots:["smile"]},
    {word:"laugh",chinese:"笑",sentence:"That joke makes me <strong>laugh</strong>.",tip:"LAUGH 的 GH 發 /f/",emoji:"😂",roots:["laugh"]},
    {word:"wake",chinese:"醒來",sentence:"I <strong>wake</strong> up when the sun rises.",tip:"WAKE 和 CAKE 押韻",emoji:"⏰",roots:["wake"]},
    {word:"die",chinese:"死/去世",sentence:"The plant will <strong>die</strong> without water.",tip:"DIE 的現在分詞是 DYING",emoji:"🥀",roots:["die"]},
    {word:"stay",chinese:"停留/待",sentence:"Can I <strong>stay</strong> up late tonight?",tip:"STAY 和 DAY 押韻",emoji:"🏠",roots:["stay"]},
    {word:"bit",chinese:"一點點",sentence:"I am a <strong>bit</strong> nervous.",tip:"A BIT 表示一點點",emoji:"🤏",roots:["bit"]},
    {word:"piece",chinese:"片/塊",sentence:"May I have a <strong>piece</strong> of cake?",tip:"PIECE 和 PEACE 發音一樣",emoji:"🍰",roots:["piece"]},
    {word:"top",chinese:"頂端/上面",sentence:"The cat sat on <strong>top</strong> of the roof.",tip:"TOP 和 BOTTOM 相反",emoji:"🔝",roots:["top"]},
    {word:"bottom",chinese:"底部/下面",sentence:"Look at the <strong>bottom</strong> of the page.",tip:"BOTTOM 有兩個 T",emoji:"⬇️",roots:["bot","tom"]},
    {word:"middle",chinese:"中間",sentence:"Sit in the <strong>middle</strong> of the row.",tip:"MIDDLE 有兩個 D",emoji:"⏺️",roots:["mid","dle"]},
    {word:"sound",chinese:"聲音/聽起來",sentence:"What is that <strong>sound</strong>?",tip:"SOUND 和 ROUND 押韻",emoji:"🔊",roots:["sound"]},
    {word:"war",chinese:"戰爭",sentence:"We want peace, not <strong>war</strong>.",tip:"WAR 和 PEACE 相反",emoji:"⚔️",roots:["war"]},
    {word:"peace",chinese:"和平",sentence:"Let there be <strong>peace</strong> on Earth.",tip:"PEACE 和 PIECE 發音一樣",emoji:"☮️",roots:["peace"]},
    {word:"group",chinese:"群/組",sentence:"Our <strong>group</strong> won the contest.",tip:"GROUP 的 OU 發 /u:/",emoji:"👥",roots:["group"]},
    {word:"teach",chinese:"教",sentence:"She loves to <strong>teach</strong> kids.",tip:"TEACH 的過去式是 TAUGHT",emoji:"👩‍🏫",roots:["teach"]},
    {word:"type",chinese:"種類/打字",sentence:"What <strong>type</strong> of music do you like?",tip:"TYPE 有「種類」和「打字」兩個意思",emoji:"⌨️",roots:["type"]},
    {word:"song",chinese:"歌曲",sentence:"That is my favorite <strong>song</strong>.",tip:"SONG 和 LONG 押韻",emoji:"🎵",roots:["song"]},
    {word:"language",chinese:"語言",sentence:"I want to learn a new <strong>language</strong>.",tip:"LANGUAGE = LANGU + AGE",emoji:"🗣️",roots:["lang","uage"]},
    {word:"maybe",chinese:"也許/可能",sentence:"<strong>Maybe</strong> we can go swimming.",tip:"MAYBE = MAY + BE",emoji:"🤔",roots:["may","be"]},
    {word:"plan",chinese:"計劃",sentence:"What is your <strong>plan</strong> for today?",tip:"PLAN 和 CAN 押韻",emoji:"📋",roots:["plan"]},
    {word:"finish",chinese:"完成",sentence:"I need to <strong>finish</strong> my project.",tip:"FINISH = FIN(結束) + ISH",emoji:"🏁",roots:["fin","ish"]},
    {word:"pass",chinese:"通過/傳遞",sentence:"Please <strong>pass</strong> me the salt.",tip:"PASS 有兩個 S",emoji:"🤲",roots:["pass"]},
    {word:"decide",chinese:"決定",sentence:"I can't <strong>decide</strong> which book to read.",tip:"DECIDE = DE + CIDE(切)",emoji:"🤔",roots:["de","cide"]},
    {word:"once",chinese:"一次/曾經",sentence:"I brush my teeth <strong>once</strong> in the morning.",tip:"ONCE 的發音特殊：/wʌns/",emoji:"1️⃣",roots:["once"]},
    {word:"ever",chinese:"曾經/到底",sentence:"Have you <strong>ever</strong> seen a whale?",tip:"EVER 常和 HAVE 一起用",emoji:"🐋",roots:["ev","er"]},
    {word:"upon",chinese:"在...上面",sentence:"Once <strong>upon</strong> a time, there was a princess.",tip:"UPON = UP + ON",emoji:"📖",roots:["up","on"]},
    {word:"either",chinese:"也（否定）/兩者之一",sentence:"I don't like it <strong>either</strong>.",tip:"EITHER 可唸 /iːðər/ 或 /aɪðər/",emoji:"🔀",roots:["ei","ther"]},
    {word:"neither",chinese:"兩者都不",sentence:"<strong>Neither</strong> answer is correct.",tip:"NEITHER = N + EITHER",emoji:"🚫",roots:["nei","ther"]},
    {word:"perhaps",chinese:"也許/可能",sentence:"<strong>Perhaps</strong> it will be sunny tomorrow.",tip:"PERHAPS = PER + HAPS",emoji:"🤔",roots:["per","haps"]},
    {word:"several",chinese:"幾個/一些",sentence:"I have <strong>several</strong> pets.",tip:"SEVERAL = SEV + ER + AL",emoji:"👥",roots:["sev","er","al"]},
    {word:"whether",chinese:"是否",sentence:"I don't know <strong>whether</strong> to go or stay.",tip:"WHETHER 和 WEATHER 發音一樣",emoji:"🤔",roots:["whe","ther"]},
    {word:"nor",chinese:"也不",sentence:"I have neither time <strong>nor</strong> energy.",tip:"NOR 和 NEITHER 搭配",emoji:"🚫",roots:["nor"]},
    {word:"thus",chinese:"因此/如此",sentence:"He practiced hard, <strong>thus</strong> he improved.",tip:"THUS 比較正式",emoji:"➡️",roots:["thus"]},
    {word:"okay",chinese:"好的/沒問題",sentence:"Are you <strong>okay</strong>?",tip:"OKAY 也寫成 OK",emoji:"👌",roots:["o","kay"]},
    {word:"please",chinese:"請",sentence:"<strong>Please</strong> pass me the butter.",tip:"PLEASE 是禮貌用語",emoji:"🙏",roots:["please"]},
    {word:"welcome",chinese:"歡迎/不客氣",sentence:"You are <strong>welcome</strong>!",tip:"WELCOME = WEL + COME",emoji:"🤗",roots:["wel","come"]},
    {word:"hello",chinese:"你好",sentence:"<strong>Hello</strong>, nice to meet you!",tip:"HELLO 是最基本的打招呼",emoji:"👋",roots:["hel","lo"]},
    {word:"bye",chinese:"再見",sentence:"<strong>Bye</strong>! See you tomorrow!",tip:"BYE 是 GOODBYE 的縮寫",emoji:"👋",roots:["bye"]},
    {word:"myself",chinese:"我自己",sentence:"I made it <strong>myself</strong>!",tip:"MYSELF = MY + SELF",emoji:"🙋",roots:["my","self"]},
    {word:"yourself",chinese:"你自己",sentence:"Believe in <strong>yourself</strong>!",tip:"YOURSELF = YOUR + SELF",emoji:"👉",roots:["your","self"]},
    {word:"himself",chinese:"他自己",sentence:"He cooked dinner <strong>himself</strong>.",tip:"HIMSELF = HIM + SELF",emoji:"👦",roots:["him","self"]},
    {word:"herself",chinese:"她自己",sentence:"She did the project <strong>herself</strong>.",tip:"HERSELF = HER + SELF",emoji:"👧",roots:["her","self"]},
    {word:"itself",chinese:"它自己",sentence:"The door opened by <strong>itself</strong>.",tip:"ITSELF = IT + SELF",emoji:"🚪",roots:["it","self"]},
    {word:"themselves",chinese:"他們自己",sentence:"They cleaned the room <strong>themselves</strong>.",tip:"THEMSELVES = THEM + SELVES",emoji:"👥",roots:["them","selves"]},
    {word:"common",chinese:"常見的/共同的",sentence:"Cats are <strong>common</strong> pets.",tip:"COMMON 有兩個 M",emoji:"🐱",roots:["com","mon"]},
    {word:"public",chinese:"公共的/公眾",sentence:"This is a <strong>public</strong> library.",tip:"PUBLIC = PUB + LIC",emoji:"🏛️",roots:["pub","lic"]},
    {word:"natural",chinese:"自然的",sentence:"This soap is all <strong>natural</strong>.",tip:"NATURAL = NATUR(自然) + AL",emoji:"🌿",roots:["nat","ur","al"]},
    {word:"private",chinese:"私人的",sentence:"That is my <strong>private</strong> diary.",tip:"PRIVATE = PRIV + ATE",emoji:"🔒",roots:["pri","vate"]},
    {word:"market",chinese:"市場",sentence:"We buy fruit at the <strong>market</strong>.",tip:"MARKET = MARK + ET",emoji:"🏪",roots:["mark","et"]},
    {word:"parent",chinese:"父母",sentence:"My <strong>parent</strong>s support me.",tip:"PARENT = PAR + ENT",emoji:"👨‍👩‍👧",roots:["par","ent"]},
    {word:"present",chinese:"禮物/現在/出席",sentence:"I got a <strong>present</strong> for my birthday!",tip:"PRESENT 有三個意思！",emoji:"🎁",roots:["pre","sent"]},
    {word:"practice",chinese:"練習",sentence:"<strong>Practice</strong> makes perfect!",tip:"PRACTICE = PRACT + ICE",emoji:"🎯",roots:["pract","ice"]},
    {word:"page",chinese:"頁",sentence:"Turn to <strong>page</strong> five.",tip:"PAGE 和 AGE 押韻",emoji:"📄",roots:["page"]},
    {word:"glass",chinese:"玻璃/杯子",sentence:"Handle the <strong>glass</strong> carefully.",tip:"GLASS 有兩個 S",emoji:"🥛",roots:["glass"]},
    {word:"difficult",chinese:"困難的",sentence:"The math test was <strong>difficult</strong>.",tip:"DIFFICULT = DIF + FI + CULT",emoji:"😰",roots:["dif","fi","cult"]},
    {word:"perfect",chinese:"完美的",sentence:"Your drawing is <strong>perfect</strong>!",tip:"PERFECT = PER + FECT",emoji:"💯",roots:["per","fect"]},
    {word:"subject",chinese:"科目/主題",sentence:"What is your favorite <strong>subject</strong>?",tip:"SUBJECT = SUB + JECT",emoji:"📚",roots:["sub","ject"]},
    {word:"effort",chinese:"努力",sentence:"Good <strong>effort</strong>, keep trying!",tip:"EFFORT = EF + FORT",emoji:"💪",roots:["ef","fort"]},
    {word:"news",chinese:"新聞",sentence:"Did you hear the <strong>news</strong>?",tip:"NEWS 用單數動詞",emoji:"📰",roots:["news"]},
    {word:"test",chinese:"測驗/考試",sentence:"We have a spelling <strong>test</strong> Friday.",tip:"TEST 和 BEST 押韻",emoji:"📝",roots:["test"]},
    {word:"mind",chinese:"心智/介意",sentence:"I don't <strong>mind</strong> waiting.",tip:"MIND 有「心」和「介意」的意思",emoji:"🧠",roots:["mind"]},
    {word:"cause",chinese:"原因/引起",sentence:"What <strong>cause</strong>d the noise?",tip:"CAUSE = 原因，BECAUSE = 因為",emoji:"💡",roots:["cause"]},
    {word:"serve",chinese:"服務/上菜",sentence:"May I <strong>serve</strong> you some tea?",tip:"SERVE = SERV(服務) + E",emoji:"🍽️",roots:["serve"]},
    {word:"human",chinese:"人類/人的",sentence:"Every <strong>human</strong> being is unique.",tip:"HUMAN = HU + MAN",emoji:"🧑",roots:["hu","man"]},
    {word:"interest",chinese:"興趣/利息",sentence:"I have great <strong>interest</strong> in space.",tip:"INTEREST = INTER + EST",emoji:"🔍",roots:["in","ter","est"]},
    {word:"form",chinese:"形式/表格",sentence:"Please fill out this <strong>form</strong>.",tip:"FORM 和 STORM 押韻",emoji:"📋",roots:["form"]},
    {word:"system",chinese:"系統",sentence:"The solar <strong>system</strong> has eight planets.",tip:"SYSTEM = SYS + TEM",emoji:"⚙️",roots:["sys","tem"]},
    {word:"area",chinese:"地區/面積",sentence:"This <strong>area</strong> has many parks.",tip:"AREA 有三個音節",emoji:"🗺️",roots:["ar","e","a"]},
    {word:"result",chinese:"結果",sentence:"The <strong>result</strong> was amazing!",tip:"RESULT = RE + SULT",emoji:"📊",roots:["re","sult"]},
    {word:"note",chinese:"筆記/備註",sentence:"I wrote a <strong>note</strong> to remind myself.",tip:"NOTE 和 VOTE 押韻",emoji:"📝",roots:["note"]},
    {word:"report",chinese:"報告",sentence:"I gave a <strong>report</strong> on dolphins.",tip:"REPORT = RE + PORT",emoji:"📄",roots:["re","port"]},
    {word:"level",chinese:"等級/水平",sentence:"I reached the next <strong>level</strong>!",tip:"LEVEL 正著反著都一樣！",emoji:"📶",roots:["lev","el"]},
    {word:"order",chinese:"順序/點菜/命令",sentence:"Put these numbers in <strong>order</strong>.",tip:"ORDER = OR + DER",emoji:"📋",roots:["or","der"]},
    {word:"chance",chinese:"機會",sentence:"Give me one more <strong>chance</strong>!",tip:"CHANCE 和 DANCE 押韻",emoji:"🎲",roots:["chance"]},
    {word:"act",chinese:"行為/演戲",sentence:"Think before you <strong>act</strong>.",tip:"ACT 只有三個字母",emoji:"🎭",roots:["act"]},
    {word:"ground",chinese:"地面/地上",sentence:"The ball rolled on the <strong>ground</strong>.",tip:"GROUND 和 ROUND 押韻",emoji:"🌍",roots:["ground"]},
    {word:"experience",chinese:"經驗/體驗",sentence:"It was an amazing <strong>experience</strong>!",tip:"EXPERIENCE = EX + PERI + ENCE",emoji:"🌟",roots:["ex","peri","ence"]},
    {word:"share",chinese:"分享",sentence:"Let's <strong>share</strong> these snacks.",tip:"SHARE 和 CARE 押韻",emoji:"🤝",roots:["share"]},
    {word:"surprise",chinese:"驚喜/驚訝",sentence:"What a wonderful <strong>surprise</strong>!",tip:"SURPRISE = SUR + PRISE",emoji:"🎉",roots:["sur","prise"]},
    {word:"agree",chinese:"同意",sentence:"I <strong>agree</strong> with your idea.",tip:"AGREE = A + GREE",emoji:"🤝",roots:["a","gree"]},
    {word:"receive",chinese:"收到",sentence:"I <strong>receive</strong>d a letter today.",tip:"I before E except after C!",emoji:"📬",roots:["re","ceive"]},
    {word:"suppose",chinese:"假設/認為",sentence:"I <strong>suppose</strong> that is fair.",tip:"SUPPOSE = SUP + POSE",emoji:"🤔",roots:["sup","pose"]},
    {word:"include",chinese:"包括",sentence:"Does the price <strong>include</strong> tax?",tip:"INCLUDE = IN + CLUDE(關)",emoji:"📦",roots:["in","clude"]},
    {word:"continue",chinese:"繼續",sentence:"Please <strong>continue</strong> reading aloud.",tip:"CONTINUE = CON + TINUE",emoji:"▶️",roots:["con","tin","ue"]},
    {word:"appear",chinese:"出現/看起來",sentence:"A rainbow <strong>appear</strong>ed in the sky!",tip:"APPEAR = AP + PEAR",emoji:"🌈",roots:["ap","pear"]},
    {word:"create",chinese:"創造",sentence:"Let's <strong>create</strong> a new game!",tip:"CREATE = CRE + ATE",emoji:"🎨",roots:["cre","ate"]},
    {word:"record",chinese:"記錄/唱片",sentence:"She broke the school <strong>record</strong>.",tip:"RECORD 當名詞和動詞重音不同",emoji:"📊",roots:["re","cord"]},
    {word:"consider",chinese:"考慮",sentence:"Let me <strong>consider</strong> your offer.",tip:"CONSIDER = CON + SIDER",emoji:"🤔",roots:["con","sid","er"]},
    {word:"expect",chinese:"期望/預期",sentence:"I <strong>expect</strong> it will be fun!",tip:"EXPECT = EX + PECT",emoji:"🤞",roots:["ex","pect"]},
    {word:"suggest",chinese:"建議",sentence:"I <strong>suggest</strong> we leave early.",tip:"SUGGEST = SUG + GEST",emoji:"💡",roots:["sug","gest"]},
    {word:"raise",chinese:"舉起/提高/養育",sentence:"<strong>Raise</strong> your hand if you know.",tip:"RAISE 有受詞，RISE 沒有",emoji:"🙋",roots:["raise"]},
    {word:"develop",chinese:"發展/開發",sentence:"Children <strong>develop</strong> quickly.",tip:"DEVELOP = DE + VELOP",emoji:"📈",roots:["de","vel","op"]},
    {word:"reach",chinese:"到達/伸手拿",sentence:"I can <strong>reach</strong> the top shelf now!",tip:"REACH 和 TEACH 押韻",emoji:"🤚",roots:["reach"]},
    {word:"remain",chinese:"保持/剩餘",sentence:"Please <strong>remain</strong> seated.",tip:"REMAIN = RE + MAIN",emoji:"🪑",roots:["re","main"]},
    {word:"offer",chinese:"提供/提議",sentence:"She <strong>offer</strong>ed to help me.",tip:"OFFER 有兩個 F",emoji:"🤲",roots:["of","fer"]},
    {word:"force",chinese:"力量/強迫",sentence:"The <strong>force</strong> of the wind is strong.",tip:"FORCE 想到星際大戰",emoji:"💪",roots:["force"]},
    {word:"information",chinese:"資訊",sentence:"I need more <strong>information</strong>.",tip:"INFORMATION = INFORM + ATION",emoji:"ℹ️",roots:["in","form","ation"]},
    {word:"produce",chinese:"生產/農產品",sentence:"Trees <strong>produce</strong> oxygen for us.",tip:"PRODUCE 當名詞和動詞重音不同",emoji:"🌳",roots:["pro","duce"]},
    {word:"company",chinese:"公司/陪伴",sentence:"My mom works at a big <strong>company</strong>.",tip:"COMPANY = COM + PANY",emoji:"🏢",roots:["com","pa","ny"]},
    {word:"money",chinese:"錢",sentence:"I save my <strong>money</strong> in a piggy bank.",tip:"MONEY = MON + EY",emoji:"💰",roots:["mon","ey"]},
    {word:"further",chinese:"更遠/進一步",sentence:"Let's look <strong>further</strong> into this.",tip:"FURTHER = FURTH + ER",emoji:"➡️",roots:["fur","ther"]},
    {word:"per",chinese:"每/每一",sentence:"It costs ten dollars <strong>per</strong> ticket.",tip:"PER 表示「每一個」",emoji:"👤",roots:["per"]},
    {word:"job",chinese:"工作/職業",sentence:"He has a great <strong>job</strong>.",tip:"JOB 只有三個字母",emoji:"💼",roots:["job"]},
    {word:"head",chinese:"頭/領導",sentence:"She is the <strong>head</strong> of the group.",tip:"HEAD 的 EA 發短音",emoji:"🗣️",roots:["head"]},
    {word:"door",chinese:"門",sentence:"Please close the <strong>door</strong> quietly.",tip:"DOOR 有兩個 O",emoji:"🚪",roots:["door"]},
    {word:"face",chinese:"臉/面對",sentence:"Wash your <strong>face</strong> before bed.",tip:"FACE 也是動詞「面對」",emoji:"😊",roots:["face"]},
    {word:"eye",chinese:"眼睛",sentence:"Close your <strong>eye</strong>s and make a wish.",tip:"EYE 正著看反著看都一樣",emoji:"👁️",roots:["eye"]},
    {word:"hand",chinese:"手/遞給",sentence:"Raise your <strong>hand</strong> to answer.",tip:"HAND 和 SAND 押韻",emoji:"✋",roots:["hand"]},
    {word:"book",chinese:"書/預訂",sentence:"I finished reading this <strong>book</strong>.",tip:"BOOK 也可以當動詞「預訂」",emoji:"📖",roots:["book"]},
    {word:"home",chinese:"家",sentence:"There is no place like <strong>home</strong>.",tip:"HOME SWEET HOME!",emoji:"🏠",roots:["home"]},
    {word:"school",chinese:"學校",sentence:"I love going to <strong>school</strong>.",tip:"SCHOOL 的 CH 發 /k/ 的音",emoji:"🏫",roots:["school"]},
    {word:"food",chinese:"食物",sentence:"Healthy <strong>food</strong> gives you energy.",tip:"FOOD 有兩個 O",emoji:"🍽️",roots:["food"]},
    {word:"water",chinese:"水/澆水",sentence:"Plants need <strong>water</strong> to grow.",tip:"WATER 是生命之源",emoji:"💧",roots:["wa","ter"]},
    {word:"car",chinese:"汽車",sentence:"We drove the <strong>car</strong> to the beach.",tip:"CAR 只有三個字母",emoji:"🚗",roots:["car"]},
    {word:"table",chinese:"桌子/表格",sentence:"Set the plates on the <strong>table</strong>.",tip:"TABLE 的 A 發長音",emoji:"🪑",roots:["ta","ble"]},
    {word:"today",chinese:"今天",sentence:"<strong>Today</strong> is going to be great!",tip:"TODAY = TO + DAY",emoji:"📅",roots:["to","day"]},
    {word:"year",chinese:"年/歲",sentence:"I am eight <strong>year</strong>s old.",tip:"YEAR 和 EAR 押韻",emoji:"📅",roots:["year"]},
    {word:"day",chinese:"天/白天",sentence:"What a beautiful <strong>day</strong>!",tip:"DAY 和 PLAY 押韻",emoji:"☀️",roots:["day"]},
    {word:"name",chinese:"名字/命名",sentence:"What is your puppy's <strong>name</strong>?",tip:"NAME 的 A 發長音",emoji:"📛",roots:["name"]},
    {word:"friend",chinese:"朋友",sentence:"You are my best <strong>friend</strong>.",tip:"FRIEND 裡面藏著 END",emoji:"🤝",roots:["fri","end"]},
    {word:"work",chinese:"工作/運作",sentence:"Hard <strong>work</strong> pays off.",tip:"WORK 和 WORD 很像",emoji:"💼",roots:["work"]},
    {word:"play",chinese:"玩/演奏",sentence:"Let's go <strong>play</strong> in the yard!",tip:"PLAY 可以是玩或演奏",emoji:"🎮",roots:["play"]},
    {word:"run",chinese:"跑",sentence:"I love to <strong>run</strong> in the park.",tip:"RUN 的過去式是 RAN",emoji:"🏃",roots:["run"]},
    {word:"read",chinese:"讀/閱讀",sentence:"I <strong>read</strong> before bedtime.",tip:"READ 現在式和過去式拼法相同但發音不同",emoji:"📖",roots:["read"]},
    {word:"walk",chinese:"走路/散步",sentence:"Let's <strong>walk</strong> to the store.",tip:"WALK 的 L 不發音",emoji:"🚶",roots:["walk"]},
    {word:"eat",chinese:"吃",sentence:"Let's <strong>eat</strong> lunch together.",tip:"EAT 的過去式是 ATE",emoji:"🍽️",roots:["eat"]},
    {word:"drink",chinese:"喝/飲料",sentence:"I <strong>drink</strong> juice every morning.",tip:"DRINK 的過去式是 DRANK",emoji:"🥤",roots:["drink"]},
    {word:"sleep",chinese:"睡覺",sentence:"I <strong>sleep</strong> eight hours every night.",tip:"SLEEP 有兩個 E",emoji:"😴",roots:["sleep"]},
    {word:"speak",chinese:"說/講話",sentence:"She can <strong>speak</strong> three languages.",tip:"SPEAK 的過去式是 SPOKE",emoji:"🗣️",roots:["speak"]},
    {word:"write",chinese:"寫",sentence:"I <strong>write</strong> in my journal daily.",tip:"WRITE 的 W 不發音",emoji:"✍️",roots:["write"]},
    {word:"give",chinese:"給",sentence:"I will <strong>give</strong> you my extra pencil.",tip:"GIVE 的過去式是 GAVE",emoji:"🎁",roots:["give"]},
    {word:"take",chinese:"拿/帶走",sentence:"<strong>Take</strong> an umbrella with you.",tip:"TAKE 的過去式是 TOOK",emoji:"🤲",roots:["take"]},
    {word:"come",chinese:"來",sentence:"<strong>Come</strong> here, please!",tip:"COME 的過去式是 CAME",emoji:"🏃",roots:["come"]},
    {word:"go",chinese:"去",sentence:"Let's <strong>go</strong> to the playground!",tip:"GO 的過去式是 WENT",emoji:"🚶",roots:["go"]},
    {word:"see",chinese:"看見",sentence:"I can <strong>see</strong> the ocean from here.",tip:"SEE 和 SEA 發音一樣",emoji:"👀",roots:["see"]},
    {word:"say",chinese:"說",sentence:"What did you <strong>say</strong>?",tip:"SAY 的過去式是 SAID",emoji:"💬",roots:["say"]},
    {word:"get",chinese:"得到/變得",sentence:"I <strong>get</strong> up early every morning.",tip:"GET 有很多用法",emoji:"🤲",roots:["get"]},
    {word:"like",chinese:"喜歡/像",sentence:"I <strong>like</strong> chocolate ice cream.",tip:"LIKE 有「喜歡」和「像」兩個意思",emoji:"👍",roots:["like"]},
    {word:"time",chinese:"時間/次",sentence:"What <strong>time</strong> is it?",tip:"TIME 和 DIME 押韻",emoji:"⏰",roots:["time"]},
    {word:"long",chinese:"長的/長久",sentence:"The snake is very <strong>long</strong>.",tip:"LONG 和 SHORT 相反",emoji:"📏",roots:["long"]},
    {word:"big",chinese:"大的",sentence:"That is a <strong>big</strong> elephant!",tip:"BIG 只有三個字母",emoji:"🐘",roots:["big"]},
    {word:"good",chinese:"好的",sentence:"You are a <strong>good</strong> student.",tip:"GOOD 的比較級是 BETTER",emoji:"👍",roots:["good"]},
    {word:"bad",chinese:"壞的/糟糕的",sentence:"That was a <strong>bad</strong> idea.",tip:"BAD 的比較級是 WORSE",emoji:"👎",roots:["bad"]},
    {word:"happy",chinese:"開心的",sentence:"I am so <strong>happy</strong> to see you!",tip:"HAPPY 有兩個 P",emoji:"😊",roots:["hap","py"]},
    {word:"sad",chinese:"難過的",sentence:"Don't be <strong>sad</strong>, things will get better.",tip:"SAD 只有三個字母",emoji:"😢",roots:["sad"]},
    {word:"old",chinese:"老的/舊的",sentence:"That is an <strong>old</strong> castle.",tip:"OLD 和 GOLD 押韻",emoji:"🏰",roots:["old"]},
    {word:"learn",chinese:"學習",sentence:"I want to <strong>learn</strong> to cook.",tip:"LEARN 和 EARN 押韻",emoji:"🎓",roots:["learn"]},
    {word:"live",chinese:"住/活/現場的",sentence:"I <strong>live</strong> near the river.",tip:"LIVE 當動詞和形容詞發音不同",emoji:"🏠",roots:["live"]},
    {word:"feel",chinese:"感覺",sentence:"I <strong>feel</strong> great after exercising.",tip:"FEEL 有兩個 E",emoji:"😊",roots:["feel"]},
    {word:"fly",chinese:"飛",sentence:"Birds <strong>fly</strong> south in winter.",tip:"FLY 的過去式是 FLEW",emoji:"🦅",roots:["fly"]},
    {word:"open",chinese:"打開/開放的",sentence:"<strong>Open</strong> the window for fresh air.",tip:"OPEN 和 CLOSE 相反",emoji:"📖",roots:["o","pen"]},
    {word:"close",chinese:"關閉/靠近",sentence:"Please <strong>close</strong> your textbook.",tip:"CLOSE 當動詞和形容詞發音不同",emoji:"📕",roots:["close"]},
    {word:"listen",chinese:"聽",sentence:"<strong>Listen</strong> to the teacher carefully.",tip:"LISTEN 的 T 不發音",emoji:"👂",roots:["lis","ten"]},
    {word:"sit",chinese:"坐",sentence:"Please <strong>sit</strong> down and relax.",tip:"SIT 的過去式是 SAT",emoji:"🪑",roots:["sit"]}
  ]
};
