WORD_DATA["coca_l9"] = {
  name: "COCA L9",
  color: "#14b8a6",
  words: [
    {word:"abate",chinese:"減弱/減輕",sentence:"The storm began to <strong>abate</strong> after midnight.",tip:"A+BATE(打)=把力量打下去=減弱",emoji:"📉",roots:["a","bate"]},
    {word:"abdicate",chinese:"退位/放棄",sentence:"The king decided to <strong>abdicate</strong> his throne.",tip:"AB(離開)+DIC(說)+ATE=宣布離開=退位",emoji:"👑",roots:["ab","dic","ate"]},
    {word:"aberrant",chinese:"異常的/偏離的",sentence:"His <strong>aberrant</strong> behavior alarmed his colleagues.",tip:"AB(離開)+ERR(錯誤)+ANT=走偏的",emoji:"⚠️",roots:["ab","err","ant"]},
    {word:"aberration",chinese:"偏差/異常",sentence:"The test result was an <strong>aberration</strong>, not the norm.",tip:"AB(離開)+ERR(錯誤)+ATION=走偏了",emoji:"📐",roots:["ab","err","ation"]},
    {word:"abhor",chinese:"憎惡/痛恨",sentence:"Most people <strong>abhor</strong> violence against children.",tip:"AB(離開)+HOR(顫抖)=嚇得發抖想逃=痛恨",emoji:"😤",roots:["ab","hor"]},
    {word:"abject",chinese:"悲慘的/卑微的",sentence:"They lived in <strong>abject</strong> poverty for years.",tip:"AB(離開)+JECT(扔)=被扔掉的=悲慘的",emoji:"😢",roots:["ab","ject"]},
    {word:"ablaze",chinese:"著火的/熱情的",sentence:"The building was <strong>ablaze</strong> when firefighters arrived.",tip:"A(在)+BLAZE(火焰)=在火焰中",emoji:"🔥",roots:["a","blaze"]},
    {word:"abolition",chinese:"廢除/廢止",sentence:"The <strong>abolition</strong> of slavery was a landmark event.",tip:"AB(離開)+OL(生長)+ITION=使不再生長=廢除",emoji:"⛓️",roots:["ab","ol","ition"]},
    {word:"abrasive",chinese:"粗糙的/傷人的",sentence:"His <strong>abrasive</strong> tone offended everyone in the room.",tip:"AB(離開)+RAS(刮)+IVE=刮傷人的",emoji:"🪨",roots:["ab","ras","ive"]},
    {word:"abridge",chinese:"刪節/縮短",sentence:"The editor had to <strong>abridge</strong> the novel for young readers.",tip:"A+BRIDGE(橋)=搭橋跳過中間=縮短",emoji:"✂️",roots:["a","bridge"]},
    {word:"absolve",chinese:"赦免/免除",sentence:"The jury <strong>absolved</strong> him of all charges.",tip:"AB(離開)+SOLVE(解)=解除罪責=赦免",emoji:"⚖️",roots:["ab","solve"]},
    {word:"abstinence",chinese:"節制/禁慾",sentence:"The doctor recommended <strong>abstinence</strong> from alcohol.",tip:"ABS(離開)+TIN(持有)+ENCE=遠離持有=節制",emoji:"🚫",roots:["abs","tin","ence"]},
    {word:"abysmal",chinese:"極糟的/深不可測的",sentence:"The team's performance was <strong>abysmal</strong> this season.",tip:"ABYSS(深淵)+MAL=深淵般糟糕",emoji:"⬇️",roots:["abyss","mal"]},
    {word:"accolade",chinese:"榮譽/讚揚",sentence:"She received many <strong>accolades</strong> for her research.",tip:"AC(向)+COL(脖子)+ADE=擁抱脖子=表彰",emoji:"🏆",roots:["ac","col","ade"]},
    {word:"acquiesce",chinese:"默許/順從",sentence:"He reluctantly <strong>acquiesced</strong> to their demands.",tip:"AC(向)+QUIESCE(安靜)=安靜接受=默許",emoji:"🤫",roots:["ac","qui","esce"]},
    {word:"acrimonious",chinese:"尖刻的/激烈的",sentence:"The divorce was long and <strong>acrimonious</strong>.",tip:"ACRI(尖銳)+MON(警告)+IOUS=尖銳地警告=尖刻的",emoji:"😠",roots:["acri","mon","ious"]},
    {word:"acumen",chinese:"敏銳/精明",sentence:"Her business <strong>acumen</strong> made her a successful entrepreneur.",tip:"ACU(尖銳)+MEN=心智尖銳=敏銳",emoji:"🧠",roots:["acu","men"]},
    {word:"adamant",chinese:"堅決的/固執的",sentence:"She was <strong>adamant</strong> about not changing her decision.",tip:"ADAM(鑽石般堅硬)+ANT=像鑽石般堅定",emoji:"💎",roots:["adam","ant"]},
    {word:"adept",chinese:"熟練的/精通的",sentence:"She is <strong>adept</strong> at solving complex problems.",tip:"AD(向)+EPT(適合)=很適合做=精通的",emoji:"🎯",roots:["ad","ept"]},
    {word:"admonish",chinese:"告誡/警告",sentence:"The teacher <strong>admonished</strong> the students for cheating.",tip:"AD(向)+MON(警告)+ISH=向人警告=告誡",emoji:"☝️",roots:["ad","mon","ish"]},
    {word:"adorn",chinese:"裝飾/點綴",sentence:"Flowers <strong>adorned</strong> every table at the wedding.",tip:"AD(向)+ORN(裝飾)=加上裝飾",emoji:"💐",roots:["ad","orn"]},
    {word:"adulate",chinese:"奉承/諂媚",sentence:"Fans <strong>adulated</strong> the pop star wherever she went.",tip:"AD(向)+UL(尾巴)+ATE=搖尾巴=諂媚",emoji:"🙇",roots:["ad","ul","ate"]},
    {word:"advent",chinese:"到來/出現",sentence:"The <strong>advent</strong> of the internet changed everything.",tip:"AD(向)+VENT(來)=來到=出現",emoji:"🌅",roots:["ad","vent"]},
    {word:"adversity",chinese:"逆境/困難",sentence:"She showed great courage in the face of <strong>adversity</strong>.",tip:"AD(向)+VERS(轉)+ITY=轉向你的壞事=逆境",emoji:"🌊",roots:["ad","vers","ity"]},
    {word:"affable",chinese:"和藹的/友善的",sentence:"The <strong>affable</strong> host made everyone feel welcome.",tip:"AF(向)+FABLE(說)=容易交談的=友善的",emoji:"😊",roots:["af","fa","ble"]},
    {word:"affluent",chinese:"富裕的/富足的",sentence:"They moved to an <strong>affluent</strong> neighborhood.",tip:"AF(向)+FLU(流)+ENT=財富流向=富裕的",emoji:"💰",roots:["af","flu","ent"]},
    {word:"aggrandize",chinese:"增大/誇大",sentence:"He tried to <strong>aggrandize</strong> his role in the project.",tip:"AG(向)+GRAND(大)+IZE=使變大=誇大",emoji:"📢",roots:["ag","grand","ize"]},
    {word:"aghast",chinese:"驚駭的/嚇呆的",sentence:"She stood <strong>aghast</strong> at the destruction.",tip:"A+GHAST(鬼)=像見鬼一樣=驚駭",emoji:"😱",roots:["a","ghast"]},
    {word:"albeit",chinese:"雖然/儘管",sentence:"He accepted the job, <strong>albeit</strong> reluctantly.",tip:"ALL+BE+IT=即使全都是這樣=雖然",emoji:"🔄",roots:["al","be","it"]},
    {word:"alchemy",chinese:"煉金術/魔法",sentence:"The chef's <strong>alchemy</strong> turned simple ingredients into gourmet dishes.",tip:"AL(阿拉伯)+CHEMY(化學)=古代化學=煉金術",emoji:"⚗️",roots:["al","chem","y"]},
    {word:"alleviate",chinese:"減輕/緩和",sentence:"The medicine helped <strong>alleviate</strong> her pain.",tip:"AL(向)+LEVI(輕)+ATE=使變輕=減輕",emoji:"💊",roots:["al","levi","ate"]},
    {word:"aloof",chinese:"冷漠的/疏遠的",sentence:"He remained <strong>aloof</strong> from his classmates.",tip:"A+LOOF(上風處)=站在上風處=冷漠疏遠",emoji:"🧊",roots:["a","loof"]},
    {word:"altercation",chinese:"爭吵/口角",sentence:"A loud <strong>altercation</strong> broke out in the parking lot.",tip:"ALTER(其他)+CATION=和別人起衝突=爭吵",emoji:"🗣️",roots:["alter","cat","ion"]},
    {word:"amalgamate",chinese:"合併/混合",sentence:"The two companies decided to <strong>amalgamate</strong>.",tip:"A+MALG(混合)+AMATE=混在一起=合併",emoji:"🤝",roots:["a","malg","amate"]},
    {word:"ambivalence",chinese:"矛盾心理/猶豫",sentence:"She felt <strong>ambivalence</strong> about leaving her hometown.",tip:"AMBI(兩邊)+VAL(力量)+ENCE=兩邊都有力=矛盾",emoji:"⚖️",roots:["ambi","val","ence"]},
    {word:"amenable",chinese:"順從的/願意的",sentence:"He was <strong>amenable</strong> to changing the schedule.",tip:"A+MEN(帶領)+ABLE=可以被帶領的=順從的",emoji:"👍",roots:["a","men","able"]},
    {word:"amiable",chinese:"友好的/親切的",sentence:"Her <strong>amiable</strong> personality won her many friends.",tip:"AMI(朋友)+ABLE=像朋友般的=友好的",emoji:"🤗",roots:["ami","able"]},
    {word:"amorphous",chinese:"無定形的/模糊的",sentence:"The plan was still <strong>amorphous</strong> and lacked details.",tip:"A(無)+MORPH(形狀)+OUS=沒有形狀的",emoji:"☁️",roots:["a","morph","ous"]},
    {word:"anachronism",chinese:"時代錯誤/過時的事物",sentence:"A typewriter in a modern office is an <strong>anachronism</strong>.",tip:"ANA(逆)+CHRON(時間)+ISM=逆時間=時代錯誤",emoji:"⏰",roots:["ana","chron","ism"]},
    {word:"analogous",chinese:"類似的/可比較的",sentence:"The human heart is <strong>analogous</strong> to a pump.",tip:"ANA(相似)+LOG(比例)+OUS=比例相似的=類似的",emoji:"🔄",roots:["ana","log","ous"]},
    {word:"anarchy",chinese:"無政府/混亂",sentence:"The country descended into <strong>anarchy</strong> after the coup.",tip:"AN(無)+ARCHY(統治)=沒有統治=無政府",emoji:"🏴",roots:["an","arch","y"]},
    {word:"anecdotal",chinese:"軼事的/趣聞的",sentence:"The evidence was purely <strong>anecdotal</strong>, not scientific.",tip:"ANEC(未發表)+DOT+AL=未發表的小故事=軼事的",emoji:"📖",roots:["anec","dot","al"]},
    {word:"anguish",chinese:"極度痛苦/苦悶",sentence:"She cried out in <strong>anguish</strong> when she heard the news.",tip:"ANG(窄)+UISH=心被壓得很窄=極度痛苦",emoji:"💔",roots:["ang","uish"]},
    {word:"animosity",chinese:"敵意/仇恨",sentence:"There was deep <strong>animosity</strong> between the two rivals.",tip:"ANIM(心靈)+OSITY=心中的惡意=敵意",emoji:"😡",roots:["anim","os","ity"]},
    {word:"annihilate",chinese:"殲滅/徹底摧毀",sentence:"The army planned to <strong>annihilate</strong> the enemy forces.",tip:"AN(向)+NIHIL(無)+ATE=使變成無=殲滅",emoji:"💥",roots:["an","nihil","ate"]},
    {word:"anomalous",chinese:"異常的/不規則的",sentence:"The <strong>anomalous</strong> data point skewed the results.",tip:"AN(不)+OMAL(正常)+OUS=不正常的=異常的",emoji:"📊",roots:["an","omal","ous"]},
    {word:"anthology",chinese:"文選/選集",sentence:"She published an <strong>anthology</strong> of modern poetry.",tip:"ANTHO(花)+LOGY(收集)=收集花朵=選集",emoji:"📚",roots:["antho","log","y"]},
    {word:"antiquated",chinese:"過時的/陳舊的",sentence:"The factory used <strong>antiquated</strong> machinery.",tip:"ANTIQU(古老)+ATED=變古老的=過時的",emoji:"🏚️",roots:["antiqu","ated"]},
    {word:"apathetic",chinese:"冷漠的/無動於衷的",sentence:"Young voters are often <strong>apathetic</strong> about politics.",tip:"A(無)+PATH(感情)+ETIC=沒有感情的=冷漠的",emoji:"😐",roots:["a","path","etic"]},
    {word:"apex",chinese:"頂點/巔峰",sentence:"She reached the <strong>apex</strong> of her career at forty.",tip:"AP(向上)+EX=最上面=頂點",emoji:"🔺",roots:["ap","ex"]},
    {word:"appease",chinese:"安撫/平息",sentence:"He tried to <strong>appease</strong> her anger with flowers.",tip:"AP(向)+PEASE(和平)=使和平=安撫",emoji:"🕊️",roots:["ap","pease"]},
    {word:"apprehension",chinese:"憂慮/理解",sentence:"She felt a sense of <strong>apprehension</strong> before the exam.",tip:"AP(向)+PRE(前)+HENS(抓)+ION=提前抓住心=憂慮",emoji:"😰",roots:["ap","pre","hens","ion"]},
    {word:"arbitrary",chinese:"任意的/武斷的",sentence:"The decision seemed completely <strong>arbitrary</strong>.",tip:"ARBIT(仲裁)+RARY=像仲裁者隨意決定=武斷的",emoji:"🎲",roots:["arbit","rary"]},
    {word:"arcane",chinese:"神秘的/晦澀的",sentence:"The book was full of <strong>arcane</strong> knowledge.",tip:"ARC(箱子)+ANE=鎖在箱子裡的=神秘的",emoji:"🔮",roots:["arc","ane"]},
    {word:"arduous",chinese:"艱巨的/費力的",sentence:"The climb was <strong>arduous</strong> but rewarding.",tip:"ARD(燃燒)+UOUS=燃燒體力的=艱巨的",emoji:"⛰️",roots:["ard","uous"]},
    {word:"articulate",chinese:"表達清晰的/發音",sentence:"She is very <strong>articulate</strong> in expressing her ideas.",tip:"ARTIC(連接)+ULATE=把詞連接好=表達清晰",emoji:"🎙️",roots:["artic","ul","ate"]},
    {word:"ascetic",chinese:"苦行的/禁慾的",sentence:"The monk lived an <strong>ascetic</strong> life in the mountains.",tip:"A+SCET(鍛鍊)+IC=苦練的=苦行的",emoji:"🧘",roots:["a","scet","ic"]},
    {word:"assiduous",chinese:"刻苦的/勤奮的",sentence:"Her <strong>assiduous</strong> efforts finally paid off.",tip:"AS(向)+SID(坐)+UOUS=一直坐著做=勤奮的",emoji:"📝",roots:["as","sid","uous"]},
    {word:"astute",chinese:"精明的/敏銳的",sentence:"An <strong>astute</strong> investor knows when to sell.",tip:"AS+TUTE(聰明)=非常聰明=精明的",emoji:"🦊",roots:["as","tute"]},
    {word:"attrition",chinese:"消耗/磨損",sentence:"Staff <strong>attrition</strong> was high due to low morale.",tip:"AT(向)+TRIT(磨)+ION=不斷磨損=消耗",emoji:"⏳",roots:["at","trit","ion"]},
    {word:"audacity",chinese:"大膽/魯莽",sentence:"He had the <strong>audacity</strong> to challenge the boss.",tip:"AUD(敢)+ACITY=敢的程度=大膽",emoji:"🦁",roots:["aud","ac","ity"]},
    {word:"augment",chinese:"增加/擴大",sentence:"She took a second job to <strong>augment</strong> her income.",tip:"AUG(增加)+MENT=使增加",emoji:"📈",roots:["aug","ment"]},
    {word:"auspicious",chinese:"吉祥的/有利的",sentence:"The wedding day started with <strong>auspicious</strong> weather.",tip:"AU(鳥)+SPIC(看)+IOUS=看鳥占卜吉利=吉祥的",emoji:"🍀",roots:["au","spic","ious"]},
    {word:"austere",chinese:"嚴肅的/樸素的",sentence:"The room had an <strong>austere</strong> beauty with minimal furniture.",tip:"AUSTER(嚴厲)=嚴格樸素的",emoji:"🏛️",roots:["auster","e"]},
    {word:"avarice",chinese:"貪婪/貪財",sentence:"His <strong>avarice</strong> led him to cheat his partners.",tip:"AV(渴望)+ARICE=渴望錢財=貪婪",emoji:"🤑",roots:["av","ar","ice"]},
    {word:"avert",chinese:"避免/轉移",sentence:"Quick action <strong>averted</strong> a major disaster.",tip:"A(離開)+VERT(轉)=轉開=避免",emoji:"🛡️",roots:["a","vert"]},
    {word:"avid",chinese:"熱切的/渴望的",sentence:"She is an <strong>avid</strong> reader of mystery novels.",tip:"AV(渴望)+ID=渴望的=熱切的",emoji:"📖",roots:["av","id"]},
    {word:"axiom",chinese:"公理/格言",sentence:"It is an <strong>axiom</strong> that practice makes perfect.",tip:"AXI(值得)+OM=值得相信的話=公理",emoji:"📜",roots:["axi","om"]},
    {word:"banal",chinese:"平庸的/陳腐的",sentence:"The movie had a <strong>banal</strong> plot with no surprises.",tip:"BAN(禁止)+AL=被禁止新意的=陳腐的",emoji:"🥱",roots:["ban","al"]},
    {word:"bane",chinese:"禍根/災星",sentence:"Mosquitoes are the <strong>bane</strong> of summer evenings.",tip:"BANE=帶來痛苦的事物=禍根",emoji:"☠️",roots:["bane"]},
    {word:"baroque",chinese:"巴洛克的/華麗的",sentence:"The church featured <strong>baroque</strong> architecture.",tip:"BAROQUE=不規則珍珠=華麗繁複的",emoji:"🏰",roots:["baroque"]},
    {word:"bastion",chinese:"堡壘/據點",sentence:"The university is a <strong>bastion</strong> of free speech.",tip:"BAST(建造)+ION=建造的防禦=堡壘",emoji:"🏰",roots:["bast","ion"]},
    {word:"bedlam",chinese:"混亂/喧鬧",sentence:"The classroom was in <strong>bedlam</strong> when the teacher left.",tip:"BEDLAM=瘋人院的名字=混亂",emoji:"🤯",roots:["bed","lam"]},
    {word:"befuddle",chinese:"使困惑/使迷糊",sentence:"The complex instructions <strong>befuddled</strong> everyone.",tip:"BE(使)+FUDDLE(迷糊)=使迷糊",emoji:"😵",roots:["be","fuddle"]},
    {word:"belligerent",chinese:"好戰的/挑釁的",sentence:"His <strong>belligerent</strong> attitude started many fights.",tip:"BELL(戰爭)+IGER(帶來)+ENT=帶來戰爭的=好戰的",emoji:"👊",roots:["bell","iger","ent"]},
    {word:"bemoan",chinese:"哀嘆/惋惜",sentence:"He <strong>bemoaned</strong> the loss of the old traditions.",tip:"BE(加強)+MOAN(呻吟)=大聲呻吟=哀嘆",emoji:"😩",roots:["be","moan"]},
    {word:"benign",chinese:"和善的/良性的",sentence:"The tumor turned out to be <strong>benign</strong>.",tip:"BEN(好)+IGN=好的=良性的",emoji:"😌",roots:["ben","ign"]},
    {word:"bequeath",chinese:"遺贈/傳給",sentence:"She <strong>bequeathed</strong> her estate to her grandchildren.",tip:"BE(加強)+QUEATH(說)=在遺囑中說=遺贈",emoji:"📜",roots:["be","queath"]},
    {word:"berate",chinese:"嚴厲斥責",sentence:"The coach <strong>berated</strong> the player for the error.",tip:"BE(加強)+RATE(責罵)=狠狠責罵=嚴厲斥責",emoji:"😤",roots:["be","rate"]},
    {word:"bereave",chinese:"喪親/失去親人",sentence:"The <strong>bereaved</strong> family received many condolences.",tip:"BE(加強)+REAVE(搶走)=被搶走親人=喪親",emoji:"🖤",roots:["be","reave"]},
    {word:"besiege",chinese:"圍攻/困擾",sentence:"Reporters <strong>besieged</strong> the celebrity for comments.",tip:"BE(加強)+SIEGE(圍攻)=圍攻",emoji:"🏰",roots:["be","siege"]},
    {word:"bilateral",chinese:"雙邊的/雙方的",sentence:"The two countries signed a <strong>bilateral</strong> trade agreement.",tip:"BI(二)+LATER(邊)+AL=兩邊的=雙邊的",emoji:"🤝",roots:["bi","later","al"]},
    {word:"blasphemy",chinese:"褻瀆/不敬",sentence:"In some countries, <strong>blasphemy</strong> is a criminal offense.",tip:"BLAS(傷害)+PHEM(說)=說傷害神的話=褻瀆",emoji:"⚡",roots:["blas","phem","y"]},
    {word:"blatant",chinese:"公然的/明目張膽的",sentence:"It was a <strong>blatant</strong> lie that everyone saw through.",tip:"BLAT(叫喊)+ANT=大聲叫嚷的=公然的",emoji:"📣",roots:["blat","ant"]},
    {word:"blight",chinese:"枯萎病/損害",sentence:"Poverty is a <strong>blight</strong> on our society.",tip:"BLIGHT=使枯萎的疾病=損害",emoji:"🥀",roots:["blight"]},
    {word:"bolster",chinese:"支持/加強",sentence:"New evidence <strong>bolstered</strong> his argument.",tip:"BOLSTER=枕頭=支撐=加強",emoji:"💪",roots:["bolster"]},
    {word:"bombastic",chinese:"誇誇其談的/浮誇的",sentence:"His <strong>bombastic</strong> speeches impressed no one.",tip:"BOMB(爆炸)+ASTIC=像炸彈般誇張=浮誇的",emoji:"💨",roots:["bomb","ast","ic"]},
    {word:"bourgeois",chinese:"中產階級的/資產階級的",sentence:"They lived a comfortable <strong>bourgeois</strong> lifestyle.",tip:"BOURG(城鎮)+EOIS=城鎮居民=中產階級的",emoji:"🏡",roots:["bourg","eois"]},
    {word:"brevity",chinese:"簡潔/短暫",sentence:"<strong>Brevity</strong> is the soul of wit.",tip:"BREV(短)+ITY=短的特質=簡潔",emoji:"✏️",roots:["brev","ity"]},
    {word:"broach",chinese:"提出/開啟話題",sentence:"She didn't know how to <strong>broach</strong> the subject.",tip:"BROACH=用尖物打開=開啟話題",emoji:"🗣️",roots:["broach"]},
    {word:"bucolic",chinese:"田園的/鄉村的",sentence:"They enjoyed the <strong>bucolic</strong> scenery of the countryside.",tip:"BU(牛)+COL(耕種)+IC=牛耕田=田園的",emoji:"🌾",roots:["bu","col","ic"]},
    {word:"buoyant",chinese:"有浮力的/樂觀的",sentence:"The market remained <strong>buoyant</strong> despite the crisis.",tip:"BUOY(浮標)+ANT=像浮標般=有浮力的/樂觀的",emoji:"🎈",roots:["buoy","ant"]},
    {word:"bureaucracy",chinese:"官僚制度/繁文縟節",sentence:"The project was delayed by <strong>bureaucracy</strong>.",tip:"BUREAU(辦公桌)+CRACY(統治)=坐辦公桌統治=官僚",emoji:"📋",roots:["bureau","cracy"]},
    {word:"burgeon",chinese:"迅速成長/萌芽",sentence:"The tech industry continued to <strong>burgeon</strong>.",tip:"BURG(芽)+EON=發芽=迅速成長",emoji:"🌱",roots:["burg","eon"]},
    {word:"burnish",chinese:"擦亮/磨光",sentence:"She worked to <strong>burnish</strong> her professional reputation.",tip:"BURN(燒)+ISH=燒到發亮=擦亮",emoji:"✨",roots:["burn","ish"]},
    {word:"cacophony",chinese:"刺耳的聲音/不和諧",sentence:"A <strong>cacophony</strong> of car horns filled the street.",tip:"CACO(壞)+PHON(聲音)+Y=難聽的聲音",emoji:"🔊",roots:["caco","phon","y"]},
    {word:"cajole",chinese:"哄騙/甜言蜜語勸",sentence:"She <strong>cajoled</strong> him into lending her money.",tip:"CA+JOLE(快樂)=用甜言蜜語使人開心=哄騙",emoji:"🍬",roots:["ca","jole"]},
    {word:"calamity",chinese:"災難/大禍",sentence:"The earthquake was a terrible <strong>calamity</strong>.",tip:"CALAM(損害)+ITY=帶來損害的事=災難",emoji:"🌋",roots:["calam","ity"]},
    {word:"callous",chinese:"無情的/冷酷的",sentence:"His <strong>callous</strong> disregard for others shocked everyone.",tip:"CALL(硬皮)+OUS=心長繭了=無情的",emoji:"🧊",roots:["call","ous"]},
    {word:"candor",chinese:"坦率/直言不諱",sentence:"I appreciate your <strong>candor</strong> about the situation.",tip:"CAND(白/光)+OR=光明正大=坦率",emoji:"💡",roots:["cand","or"]},
    {word:"capacious",chinese:"寬敞的/容量大的",sentence:"The <strong>capacious</strong> trunk held all their luggage.",tip:"CAPAC(容納)+IOUS=能容納很多的=寬敞的",emoji:"🏠",roots:["capac","ious"]},
    {word:"capitulate",chinese:"投降/屈服",sentence:"The army was forced to <strong>capitulate</strong> after the siege.",tip:"CAPIT(頭)+ULATE=低頭=投降",emoji:"🏳️",roots:["capit","ul","ate"]},
    {word:"capricious",chinese:"善變的/任性的",sentence:"The <strong>capricious</strong> weather ruined their plans.",tip:"CAPRI(山羊)+CIOUS=像山羊般跳來跳去=善變的",emoji:"🐐",roots:["capri","cious"]},
    {word:"cardinal",chinese:"主要的/基本的",sentence:"Honesty is a <strong>cardinal</strong> virtue.",tip:"CARD(心)+INAL=心中最重要的=主要的",emoji:"❤️",roots:["card","inal"]},
    {word:"cascade",chinese:"瀑布/傾瀉",sentence:"A <strong>cascade</strong> of water fell from the cliff.",tip:"CASC(落)+ADE=落下的=瀑布",emoji:"🌊",roots:["casc","ade"]},
    {word:"castigate",chinese:"嚴厲批評/懲罰",sentence:"The press <strong>castigated</strong> the politician for lying.",tip:"CAST(純潔)+IGATE=使純潔=嚴厲糾正",emoji:"📰",roots:["cast","ig","ate"]},
    {word:"catalyst",chinese:"催化劑/促進因素",sentence:"The incident was a <strong>catalyst</strong> for change.",tip:"CATA(下)+LYST(鬆開)=使反應鬆開加速=催化劑",emoji:"⚡",roots:["cata","lyst"]},
    {word:"catharsis",chinese:"宣洩/淨化",sentence:"Writing in her journal was a form of <strong>catharsis</strong>.",tip:"CATHAR(淨化)+SIS=淨化心靈=宣洩",emoji:"🧹",roots:["cathar","sis"]},
    {word:"caustic",chinese:"腐蝕性的/刻薄的",sentence:"Her <strong>caustic</strong> remarks hurt his feelings.",tip:"CAUST(燒)+IC=像燒灼般=刻薄的",emoji:"🧪",roots:["caust","ic"]},
    {word:"cavalier",chinese:"漫不經心的/輕率的",sentence:"His <strong>cavalier</strong> attitude toward safety was dangerous.",tip:"CAVALIER=騎士般自大=漫不經心的",emoji:"🤷",roots:["caval","ier"]},
    {word:"censure",chinese:"譴責/非難",sentence:"The committee voted to <strong>censure</strong> the senator.",tip:"CENS(評判)+URE=做出評判=譴責",emoji:"👎",roots:["cens","ure"]},
    {word:"cerebral",chinese:"大腦的/理智的",sentence:"He preferred <strong>cerebral</strong> pursuits like chess.",tip:"CEREBR(腦)+AL=和腦有關的=理智的",emoji:"🧠",roots:["cerebr","al"]},
    {word:"chagrin",chinese:"懊惱/失望",sentence:"Much to her <strong>chagrin</strong>, she was not invited.",tip:"CHAGRIN=刺痛心的感覺=懊惱",emoji:"😣",roots:["chagrin"]},
    {word:"charlatan",chinese:"騙子/江湖郎中",sentence:"The healer turned out to be a <strong>charlatan</strong>.",tip:"CHARL(說話)+ATAN=說空話的人=騙子",emoji:"🎭",roots:["charl","atan"]},
    {word:"chronicle",chinese:"編年史/記錄",sentence:"The book <strong>chronicles</strong> the history of the city.",tip:"CHRON(時間)+ICLE=按時間記錄=編年史",emoji:"📜",roots:["chron","icle"]},
    {word:"circumspect",chinese:"謹慎的/周密的",sentence:"Be <strong>circumspect</strong> in your dealings with strangers.",tip:"CIRCUM(周圍)+SPECT(看)=四周都看=謹慎的",emoji:"👀",roots:["circum","spect"]},
    {word:"clandestine",chinese:"秘密的/暗中的",sentence:"They held <strong>clandestine</strong> meetings in the basement.",tip:"CLAN(秘密)+DESTIN+E=秘密進行的",emoji:"🕵️",roots:["clan","dest","ine"]},
    {word:"clemency",chinese:"仁慈/寬恕",sentence:"The prisoner begged for <strong>clemency</strong>.",tip:"CLEM(溫和)+ENCY=溫和對待=仁慈",emoji:"🙏",roots:["clem","ency"]},
    {word:"coalesce",chinese:"合併/聯合",sentence:"Several small groups <strong>coalesced</strong> into one party.",tip:"CO(一起)+AL+ESCE(生長)=一起生長=合併",emoji:"🔗",roots:["co","al","esce"]},
    {word:"coerce",chinese:"強迫/脅迫",sentence:"He was <strong>coerced</strong> into signing the document.",tip:"CO(一起)+ERCE(關閉)=把人關起來逼=強迫",emoji:"⛓️",roots:["co","erce"]},
    {word:"cogent",chinese:"有說服力的/令人信服的",sentence:"She presented a <strong>cogent</strong> argument for the change.",tip:"COG(思考)+ENT=經過深思的=有說服力的",emoji:"💡",roots:["cog","ent"]},
    {word:"cognizant",chinese:"認識到的/了解的",sentence:"She was <strong>cognizant</strong> of the risks involved.",tip:"COGN(知道)+IZ+ANT=知道的=了解的",emoji:"🧐",roots:["cogn","iz","ant"]},
    {word:"collaborate",chinese:"合作/協作",sentence:"Scientists from both countries <strong>collaborated</strong> on the study.",tip:"COL(一起)+LABOR(工作)+ATE=一起工作=合作",emoji:"🤝",roots:["col","labor","ate"]},
    {word:"colloquial",chinese:"口語的/通俗的",sentence:"The essay used too much <strong>colloquial</strong> language.",tip:"COL(一起)+LOQU(說)+IAL=人們一起說的=口語的",emoji:"💬",roots:["col","loqu","ial"]},
    {word:"combustion",chinese:"燃燒/氧化",sentence:"The engine works by internal <strong>combustion</strong>.",tip:"COM(完全)+BUST(燃燒)+ION=完全燒起來=燃燒",emoji:"🔥",roots:["com","bust","ion"]},
    {word:"commemorative",chinese:"紀念的/慶祝的",sentence:"They issued a <strong>commemorative</strong> stamp for the event.",tip:"COM(一起)+MEMOR(記憶)+ATIVE=一起記住=紀念的",emoji:"🎖️",roots:["com","memor","ative"]},
    {word:"commiserate",chinese:"同情/憐憫",sentence:"Friends <strong>commiserated</strong> with her after the loss.",tip:"COM(一起)+MISER(痛苦)+ATE=一起感受痛苦=同情",emoji:"🫂",roots:["com","miser","ate"]},
    {word:"compendium",chinese:"概要/彙編",sentence:"The book is a <strong>compendium</strong> of modern art.",tip:"COM(一起)+PEND(稱重)+IUM=放在一起衡量=概要",emoji:"📘",roots:["com","pend","ium"]},
    {word:"complacent",chinese:"自滿的/沾沾自喜的",sentence:"Don't become <strong>complacent</strong> after early success.",tip:"COM(完全)+PLAC(喜歡)+ENT=完全滿意=自滿的",emoji:"😏",roots:["com","plac","ent"]},
    {word:"complicit",chinese:"共謀的/同謀的",sentence:"He was <strong>complicit</strong> in the fraud scheme.",tip:"COM(一起)+PLIC(折疊)+IT=摺在一起=共謀的",emoji:"🤫",roots:["com","plic","it"]},
    {word:"composure",chinese:"鎮定/沉著",sentence:"She maintained her <strong>composure</strong> under pressure.",tip:"COM(一起)+POS(放)+URE=把自己放好=鎮定",emoji:"🧘",roots:["com","pos","ure"]},
    {word:"conciliatory",chinese:"和解的/調停的",sentence:"He took a <strong>conciliatory</strong> approach to the dispute.",tip:"CON(一起)+CIL(召集)+IATORY=把人召集在一起=和解的",emoji:"🕊️",roots:["con","cili","atory"]},
    {word:"concoct",chinese:"調製/捏造",sentence:"She <strong>concocted</strong> a story to explain her absence.",tip:"CON(一起)+COCT(煮)=煮在一起=調製/捏造",emoji:"🧪",roots:["con","coct"]},
    {word:"concurrent",chinese:"同時的/並發的",sentence:"The two events were <strong>concurrent</strong>.",tip:"CON(一起)+CURR(跑)+ENT=一起跑=同時的",emoji:"⏱️",roots:["con","curr","ent"]},
    {word:"condescend",chinese:"屈尊/俯就",sentence:"She <strong>condescended</strong> to speak with the junior staff.",tip:"CON(向下)+DE+SCEND(爬)=往下爬=屈尊",emoji:"👃",roots:["con","de","scend"]},
    {word:"conducive",chinese:"有助於的/有益的",sentence:"A quiet room is <strong>conducive</strong> to studying.",tip:"CON(一起)+DUC(引導)+IVE=引導朝向=有助於的",emoji:"✅",roots:["con","duc","ive"]},
    {word:"confiscate",chinese:"沒收/充公",sentence:"The teacher <strong>confiscated</strong> the student's phone.",tip:"CON(完全)+FISC(國庫)+ATE=收入國庫=沒收",emoji:"🚫",roots:["con","fisc","ate"]},
    {word:"confluence",chinese:"匯合/匯流",sentence:"The <strong>confluence</strong> of the two rivers creates rapids.",tip:"CON(一起)+FLU(流)+ENCE=流到一起=匯合",emoji:"🌊",roots:["con","flu","ence"]},
    {word:"congenial",chinese:"意氣相投的/適宜的",sentence:"The office had a <strong>congenial</strong> atmosphere.",tip:"CON(一起)+GEN(出生)+IAL=一起出生的=意氣相投的",emoji:"😄",roots:["con","gen","ial"]},
    {word:"conjecture",chinese:"推測/猜想",sentence:"His theory is based on <strong>conjecture</strong>, not facts.",tip:"CON(一起)+JECT(扔)+URE=把想法扔在一起=推測",emoji:"🤔",roots:["con","ject","ure"]},
    {word:"connoisseur",chinese:"鑑賞家/內行",sentence:"He is a <strong>connoisseur</strong> of fine wines.",tip:"CON(完全)+NOISS(知道)+EUR=完全懂的人=鑑賞家",emoji:"🍷",roots:["con","noiss","eur"]},
    {word:"consecrate",chinese:"奉獻/使神聖",sentence:"The church was <strong>consecrated</strong> in a special ceremony.",tip:"CON(完全)+SECR(神聖)+ATE=使完全神聖=奉獻",emoji:"⛪",roots:["con","secr","ate"]},
    {word:"consensus",chinese:"共識/一致",sentence:"The committee reached a <strong>consensus</strong> on the budget.",tip:"CON(一起)+SENS(感覺)+US=一起感覺=共識",emoji:"🤝",roots:["con","sens","us"]},
    {word:"conspicuous",chinese:"顯眼的/引人注目的",sentence:"His absence was <strong>conspicuous</strong> at the meeting.",tip:"CON(完全)+SPIC(看)+UOUS=完全被看到=顯眼的",emoji:"👁️",roots:["con","spic","uous"]},
    {word:"constituency",chinese:"選區/支持者",sentence:"The politician appealed to her <strong>constituency</strong>.",tip:"CON(一起)+STITU(站)+ENCY=站在一起的人=選區",emoji:"🗳️",roots:["con","stitu","ency"]},
    {word:"contemptuous",chinese:"輕蔑的/鄙視的",sentence:"He gave a <strong>contemptuous</strong> sneer.",tip:"CON(完全)+TEMPT(蔑視)+UOUS=完全蔑視的",emoji:"😒",roots:["con","tempt","uous"]},
    {word:"contiguous",chinese:"相鄰的/連續的",sentence:"The two properties are <strong>contiguous</strong>.",tip:"CON(一起)+TIG(觸)+UOUS=互相觸碰的=相鄰的",emoji:"🧩",roots:["con","tig","uous"]},
    {word:"contingent",chinese:"取決於的/偶然的",sentence:"Success is <strong>contingent</strong> upon hard work.",tip:"CON(一起)+TING(觸)+ENT=接觸到條件=取決於的",emoji:"🎯",roots:["con","ting","ent"]},
    {word:"contrition",chinese:"悔恨/懺悔",sentence:"He expressed sincere <strong>contrition</strong> for his mistakes.",tip:"CON(完全)+TRIT(磨)+ION=心被磨碎=悔恨",emoji:"😔",roots:["con","trit","ion"]},
    {word:"convivial",chinese:"歡樂的/友好的",sentence:"The party had a <strong>convivial</strong> atmosphere.",tip:"CON(一起)+VIV(活)+IAL=一起活得開心=歡樂的",emoji:"🎉",roots:["con","viv","ial"]},
    {word:"copious",chinese:"大量的/豐富的",sentence:"She took <strong>copious</strong> notes during the lecture.",tip:"COPI(豐富)+OUS=很豐富的=大量的",emoji:"📝",roots:["copi","ous"]},
    {word:"cordial",chinese:"熱誠的/友好的",sentence:"They received a <strong>cordial</strong> welcome.",tip:"CORD(心)+IAL=發自內心的=熱誠的",emoji:"🤗",roots:["cord","ial"]},
    {word:"cornerstone",chinese:"基石/基礎",sentence:"Trust is the <strong>cornerstone</strong> of any relationship.",tip:"CORNER(角落)+STONE(石頭)=建築的角落石=基石",emoji:"🧱",roots:["corner","stone"]},
    {word:"coronation",chinese:"加冕典禮",sentence:"The <strong>coronation</strong> was watched by millions.",tip:"CORON(皇冠)+ATION=戴上皇冠=加冕",emoji:"👑",roots:["coron","ation"]},
    {word:"corpulent",chinese:"肥胖的/臃腫的",sentence:"The <strong>corpulent</strong> man struggled to climb the stairs.",tip:"CORP(身體)+ULENT=身體太多=肥胖的",emoji:"🫃",roots:["corp","ul","ent"]},
    {word:"corroborate",chinese:"證實/佐證",sentence:"Witnesses <strong>corroborated</strong> her story.",tip:"COR(一起)+ROBOR(力量)+ATE=一起加強=證實",emoji:"✓",roots:["cor","robor","ate"]},
    {word:"cosmopolitan",chinese:"世界性的/國際化的",sentence:"London is a truly <strong>cosmopolitan</strong> city.",tip:"COSMO(世界)+POLIT(城市)+AN=世界城市的=國際化的",emoji:"🌍",roots:["cosmo","polit","an"]},
    {word:"counterfeit",chinese:"偽造的/仿冒品",sentence:"The police seized <strong>counterfeit</strong> banknotes.",tip:"COUNTER(相反)+FEIT(做)=做出相反的=偽造的",emoji:"💵",roots:["counter","feit"]},
    {word:"coup",chinese:"政變/大成功",sentence:"The military staged a <strong>coup</strong> against the government.",tip:"COUP=一擊=政變",emoji:"⚔️",roots:["coup"]},
    {word:"covert",chinese:"秘密的/隱蔽的",sentence:"The agency conducted <strong>covert</strong> operations.",tip:"CO+VERT(覆蓋)=被覆蓋的=秘密的",emoji:"🕶️",roots:["co","vert"]},
    {word:"credulous",chinese:"輕信的/易受騙的",sentence:"The <strong>credulous</strong> investors lost their money.",tip:"CRED(相信)+ULOUS=太容易相信的=輕信的",emoji:"🙈",roots:["cred","ul","ous"]},
    {word:"crescendo",chinese:"漸強/高潮",sentence:"The music built to a powerful <strong>crescendo</strong>.",tip:"CRESC(生長)+ENDO=聲音越來越大=漸強",emoji:"🎵",roots:["cresc","endo"]},
    {word:"criterion",chinese:"標準/準則",sentence:"What <strong>criteria</strong> did you use to select candidates?",tip:"CRIT(判斷)+ERION=用來判斷的=標準",emoji:"📏",roots:["crit","erion"]},
    {word:"cryptic",chinese:"神秘的/隱晦的",sentence:"She left a <strong>cryptic</strong> message on his desk.",tip:"CRYPT(隱藏)+IC=隱藏意思的=神秘的",emoji:"🔐",roots:["crypt","ic"]},
    {word:"culminate",chinese:"達到頂點/告終",sentence:"Years of work <strong>culminated</strong> in a breakthrough.",tip:"CULM(頂)+IN+ATE=到達頂點",emoji:"🏔️",roots:["culm","in","ate"]},
    {word:"culpable",chinese:"有罪的/該受責備的",sentence:"He was found <strong>culpable</strong> for the accident.",tip:"CULP(罪)+ABLE=有罪的",emoji:"⚖️",roots:["culp","able"]},
    {word:"cumbersome",chinese:"笨重的/累贅的",sentence:"The <strong>cumbersome</strong> equipment slowed them down.",tip:"CUMBER(阻礙)+SOME=有阻礙的=笨重的",emoji:"🪨",roots:["cumber","some"]},
    {word:"curtail",chinese:"削減/縮短",sentence:"Budget cuts <strong>curtailed</strong> the research program.",tip:"CURT(短)+AIL=使變短=削減",emoji:"✂️",roots:["curt","ail"]},
    {word:"cynical",chinese:"憤世嫉俗的/懷疑的",sentence:"He became <strong>cynical</strong> about politics after the scandal.",tip:"CYN(狗)+ICAL=像狗般嘲笑人=憤世嫉俗的",emoji:"🐕",roots:["cyn","ical"]},
    {word:"dearth",chinese:"缺乏/不足",sentence:"There is a <strong>dearth</strong> of affordable housing.",tip:"DEAR(貴)+TH=太貴所以缺=缺乏",emoji:"🏜️",roots:["dear","th"]},
    {word:"debacle",chinese:"慘敗/崩潰",sentence:"The product launch was a complete <strong>debacle</strong>.",tip:"DE(向下)+BACLE(阻擋)=崩塌下來=慘敗",emoji:"💥",roots:["de","bacle"]},
    {word:"debilitate",chinese:"使衰弱/使虛弱",sentence:"The disease <strong>debilitated</strong> him for months.",tip:"DE(向下)+BILIS(力量)+TATE=力量往下=使衰弱",emoji:"🤒",roots:["de","bilit","ate"]},
    {word:"decorum",chinese:"禮節/得體",sentence:"Please maintain <strong>decorum</strong> during the ceremony.",tip:"DECOR(裝飾/適當)+UM=適當的行為=禮節",emoji:"🎩",roots:["decor","um"]},
    {word:"decree",chinese:"法令/頒布",sentence:"The government issued a <strong>decree</strong> banning protests.",tip:"DE(向下)+CREE(判決)=從上往下的判決=法令",emoji:"📋",roots:["de","cree"]},
    {word:"defamation",chinese:"誹謗/中傷",sentence:"He sued the newspaper for <strong>defamation</strong>.",tip:"DE(向下)+FAM(名聲)+ATION=把名聲拉低=誹謗",emoji:"📰",roots:["de","fam","ation"]},
    {word:"deference",chinese:"尊敬/順從",sentence:"She treated her elders with great <strong>deference</strong>.",tip:"DE(向下)+FER(帶)+ENCE=把自己帶低=尊敬",emoji:"🙇",roots:["de","fer","ence"]},
    {word:"deft",chinese:"靈巧的/熟練的",sentence:"With <strong>deft</strong> fingers, she repaired the watch.",tip:"DEFT=手指靈活的=靈巧的",emoji:"🤹",roots:["deft"]},
    {word:"defunct",chinese:"已廢除的/不存在的",sentence:"The company has been <strong>defunct</strong> since 2010.",tip:"DE(離開)+FUNCT(功能)=沒有功能了=已廢除的",emoji:"🪦",roots:["de","funct"]},
    {word:"deleterious",chinese:"有害的/有毒的",sentence:"Smoking has <strong>deleterious</strong> effects on health.",tip:"DELETE(刪除)+RIOUS=像被刪除般有害=有害的",emoji:"☠️",roots:["delet","er","ious"]},
    {word:"delineate",chinese:"描繪/勾勒",sentence:"The report <strong>delineates</strong> the plan clearly.",tip:"DE(完全)+LINE(線)+ATE=用線畫出=描繪",emoji:"🖊️",roots:["de","line","ate"]},
    {word:"deluge",chinese:"洪水/大量",sentence:"A <strong>deluge</strong> of complaints followed the announcement.",tip:"DE(向下)+LUGE(洗)=大量沖刷下來=洪水",emoji:"🌊",roots:["de","luge"]},
    {word:"demagogue",chinese:"煽動者/民粹領袖",sentence:"The <strong>demagogue</strong> exploited people's fears.",tip:"DEMO(人民)+AGOGUE(領導)=帶領人民的人=煽動者",emoji:"📢",roots:["dem","agogue"]},
    {word:"demeanor",chinese:"舉止/態度",sentence:"His calm <strong>demeanor</strong> reassured everyone.",tip:"DE+MEAN(行為)+OR=行為表現=舉止",emoji:"🧑‍💼",roots:["de","mean","or"]},
    {word:"denounce",chinese:"譴責/告發",sentence:"Human rights groups <strong>denounced</strong> the policy.",tip:"DE(向下)+NOUNCE(宣布)=公開宣布反對=譴責",emoji:"📣",roots:["de","nounce"]},
    {word:"depict",chinese:"描繪/描述",sentence:"The painting <strong>depicts</strong> a rural landscape.",tip:"DE(完全)+PICT(畫)=完全畫出=描繪",emoji:"🎨",roots:["de","pict"]},
    {word:"deplorable",chinese:"糟糕的/令人遺憾的",sentence:"Living conditions in the area were <strong>deplorable</strong>.",tip:"DE(加強)+PLOR(哭)+ABLE=令人哭泣的=糟糕的",emoji:"😢",roots:["de","plor","able"]},
    {word:"deprecate",chinese:"反對/輕視",sentence:"She <strong>deprecated</strong> the use of outdated methods.",tip:"DE(向下)+PREC(價值)+ATE=降低價值=輕視",emoji:"👎",roots:["de","prec","ate"]},
    {word:"derelict",chinese:"荒廢的/玩忽職守的",sentence:"The <strong>derelict</strong> building was an eyesore.",tip:"DE(完全)+RELICT(留下)=被留下不管=荒廢的",emoji:"🏚️",roots:["de","relict"]},
    {word:"deride",chinese:"嘲笑/嘲弄",sentence:"Critics <strong>derided</strong> the film as unoriginal.",tip:"DE(向下)+RIDE(笑)=向下嘲笑=嘲弄",emoji:"🤣",roots:["de","ride"]},
    {word:"despondent",chinese:"沮喪的/失望的",sentence:"She felt <strong>despondent</strong> after failing the exam.",tip:"DE(離開)+SPOND(承諾)+ENT=失去希望=沮喪的",emoji:"😞",roots:["de","spond","ent"]},
    {word:"despot",chinese:"暴君/專制者",sentence:"The <strong>despot</strong> ruled with an iron fist.",tip:"DESPOT=主人=暴君",emoji:"👿",roots:["des","pot"]},
    {word:"destitute",chinese:"赤貧的/缺乏的",sentence:"War left many families <strong>destitute</strong>.",tip:"DE(離開)+STITUTE(站立)=站不住腳=赤貧的",emoji:"🧑‍🦯",roots:["de","stitute"]},
    {word:"deter",chinese:"阻止/威懾",sentence:"High fines <strong>deter</strong> people from littering.",tip:"DE(離開)+TER(恐嚇)=嚇得離開=阻止",emoji:"🚧",roots:["de","ter"]},
    {word:"detrimental",chinese:"有害的/不利的",sentence:"Lack of sleep is <strong>detrimental</strong> to health.",tip:"DE(向下)+TRI(磨)+MENTAL=磨損心智的=有害的",emoji:"⚠️",roots:["de","tri","mental"]},
    {word:"devout",chinese:"虔誠的/衷心的",sentence:"She was a <strong>devout</strong> follower of the faith.",tip:"DE(完全)+VOUT(發誓)=完全發誓=虔誠的",emoji:"🙏",roots:["de","vout"]},
    {word:"diatribe",chinese:"抨擊/長篇大論",sentence:"He launched into a <strong>diatribe</strong> against corruption.",tip:"DIA(通過)+TRIBE(部落)=穿過部落般猛烈=抨擊",emoji:"🗯️",roots:["dia","tribe"]},
    {word:"dichotomy",chinese:"二分法/對立",sentence:"There is a <strong>dichotomy</strong> between theory and practice.",tip:"DICHO(二)+TOMY(切)=切成兩半=二分法",emoji:"✂️",roots:["dicho","tomy"]},
    {word:"didactic",chinese:"教誨的/說教的",sentence:"The novel has a <strong>didactic</strong> tone that annoys readers.",tip:"DIDACT(教)+IC=愛教人的=說教的",emoji:"👨‍🏫",roots:["didact","ic"]},
    {word:"diffident",chinese:"缺乏自信的/羞怯的",sentence:"The <strong>diffident</strong> boy rarely spoke in class.",tip:"DIF(不)+FID(信任)+ENT=不信任自己=缺乏自信的",emoji:"😶",roots:["dif","fid","ent"]},
    {word:"digress",chinese:"離題/跑題",sentence:"The speaker tended to <strong>digress</strong> from the topic.",tip:"DI(離開)+GRESS(走)=走離主題=離題",emoji:"🔀",roots:["di","gress"]},
    {word:"dilapidated",chinese:"破舊的/倒塌的",sentence:"The <strong>dilapidated</strong> house needed major repairs.",tip:"DI(分開)+LAPID(石頭)+ATED=石頭散落=破舊的",emoji:"🏚️",roots:["di","lapid","ated"]},
    {word:"diligent",chinese:"勤奮的/勤勉的",sentence:"A <strong>diligent</strong> student always does homework on time.",tip:"DILI(珍惜)+GENT=珍惜時間的=勤奮的",emoji:"📚",roots:["dili","gent"]},
    {word:"diminish",chinese:"減少/縮小",sentence:"His influence has <strong>diminished</strong> over the years.",tip:"DI+MINI(小)+SH=變小=減少",emoji:"📉",roots:["di","mini","sh"]},
    {word:"dire",chinese:"可怕的/極嚴重的",sentence:"The refugees are in <strong>dire</strong> need of food.",tip:"DIRE=令人恐懼的=可怕的",emoji:"🚨",roots:["dire"]},
    {word:"discern",chinese:"辨別/識別",sentence:"It was hard to <strong>discern</strong> the truth from lies.",tip:"DIS(分開)+CERN(篩選)=篩選分開=辨別",emoji:"🔍",roots:["dis","cern"]},
    {word:"discourse",chinese:"論述/話語",sentence:"Academic <strong>discourse</strong> requires formal language.",tip:"DIS(分開)+COURSE(跑)=話題跑開來=論述",emoji:"📖",roots:["dis","course"]},
    {word:"discreet",chinese:"謹慎的/低調的",sentence:"Please be <strong>discreet</strong> about this information.",tip:"DIS(分開)+CREET(辨別)=能分辨場合=謹慎的",emoji:"🤐",roots:["dis","creet"]},
    {word:"disdain",chinese:"蔑視/鄙視",sentence:"She looked at him with <strong>disdain</strong>.",tip:"DIS(不)+DAIN(值得)=不值得看=蔑視",emoji:"😤",roots:["dis","dain"]},
    {word:"disparage",chinese:"貶低/輕視",sentence:"Don't <strong>disparage</strong> others to make yourself look better.",tip:"DIS(不)+PAR(平等)+AGE=不把人當平等=貶低",emoji:"👎",roots:["dis","par","age"]},
    {word:"disparity",chinese:"差異/不等",sentence:"There is a huge <strong>disparity</strong> in wealth distribution.",tip:"DIS(不)+PAR(平等)+ITY=不平等=差異",emoji:"⚖️",roots:["dis","par","ity"]},
    {word:"dissident",chinese:"持不同政見者",sentence:"The <strong>dissident</strong> was imprisoned for speaking out.",tip:"DIS(離開)+SID(坐)+ENT=坐到不同位置=持不同意見者",emoji:"✊",roots:["dis","sid","ent"]},
    {word:"divulge",chinese:"透露/洩露",sentence:"She refused to <strong>divulge</strong> the secret.",tip:"DI(分開)+VULGE(群眾)=散播到群眾=透露",emoji:"🤫",roots:["di","vulge"]},
    {word:"docile",chinese:"溫順的/聽話的",sentence:"The <strong>docile</strong> horse was perfect for beginners.",tip:"DOC(教)+ILE=容易教的=溫順的",emoji:"🐴",roots:["doc","ile"]},
    {word:"dogmatic",chinese:"教條的/武斷的",sentence:"His <strong>dogmatic</strong> approach left no room for discussion.",tip:"DOGMA(教條)+TIC=信教條的=武斷的",emoji:"📕",roots:["dogm","atic"]},
    {word:"dormant",chinese:"休眠的/靜止的",sentence:"The volcano has been <strong>dormant</strong> for centuries.",tip:"DORM(睡)+ANT=在睡覺的=休眠的",emoji:"🌋",roots:["dorm","ant"]},
    {word:"draconian",chinese:"嚴厲的/殘酷的",sentence:"The <strong>draconian</strong> laws shocked the public.",tip:"DRACO(古代暴君)+NIAN=像暴君般=嚴厲的",emoji:"⚔️",roots:["dracon","ian"]},
    {word:"dubious",chinese:"懷疑的/可疑的",sentence:"The claim seems <strong>dubious</strong> without evidence.",tip:"DUB(二)+IOUS=心裡有兩個想法=懷疑的",emoji:"🤨",roots:["dub","ious"]},
    {word:"duplicity",chinese:"欺騙/口是心非",sentence:"His <strong>duplicity</strong> was eventually exposed.",tip:"DU(二)+PLIC(折)+ITY=兩面=欺騙",emoji:"🎭",roots:["du","plic","ity"]},
    {word:"dwindle",chinese:"減少/萎縮",sentence:"The population has <strong>dwindled</strong> to just a few hundred.",tip:"DWINDLE=逐漸變少=萎縮",emoji:"📉",roots:["dwindle"]},
    {word:"ebullient",chinese:"熱情洋溢的/興奮的",sentence:"Her <strong>ebullient</strong> personality lit up the room.",tip:"E(出)+BULL(冒泡)+IENT=像水煮沸冒泡=熱情洋溢",emoji:"🎊",roots:["e","bull","ient"]},
    {word:"eclectic",chinese:"折衷的/多樣的",sentence:"She has <strong>eclectic</strong> taste in music.",tip:"EC(出)+LECT(選)+IC=從各處選出=折衷的",emoji:"🎨",roots:["ec","lect","ic"]},
    {word:"edify",chinese:"啟迪/教化",sentence:"The documentary was meant to <strong>edify</strong> viewers.",tip:"ED(建造)+IFY=建造心靈=啟迪",emoji:"💡",roots:["ed","ify"]},
    {word:"effervescent",chinese:"冒泡的/活潑的",sentence:"Her <strong>effervescent</strong> charm delighted everyone.",tip:"EF(出)+FERV(沸騰)+ESCENT=沸騰冒出=活潑的",emoji:"🫧",roots:["ef","ferv","escent"]},
    {word:"egregious",chinese:"極其惡劣的/驚人的",sentence:"The judge called it an <strong>egregious</strong> violation of law.",tip:"E(出)+GREG(群)+IOUS=出了群的壞=極其惡劣的",emoji:"😱",roots:["e","greg","ious"]},
    {word:"elicit",chinese:"引出/激起",sentence:"Her question <strong>elicited</strong> a surprising response.",tip:"E(出)+LICIT(引誘)=引出來=引出",emoji:"🎣",roots:["e","licit"]},
    {word:"eloquent",chinese:"雄辯的/有表現力的",sentence:"She gave an <strong>eloquent</strong> speech at the conference.",tip:"E(出)+LOQU(說)+ENT=說得出色=雄辯的",emoji:"🎤",roots:["e","loqu","ent"]},
    {word:"elucidate",chinese:"闡明/解釋",sentence:"Could you <strong>elucidate</strong> your point further?",tip:"E(出)+LUCID(清楚)+ATE=使清楚=闡明",emoji:"💡",roots:["e","lucid","ate"]},
    {word:"elusive",chinese:"難以捉摸的/逃避的",sentence:"Happiness can be <strong>elusive</strong>.",tip:"E(出)+LUS(玩)+IVE=玩著逃跑=難以捉摸的",emoji:"🦋",roots:["e","lus","ive"]},
    {word:"emancipate",chinese:"解放/釋放",sentence:"The law <strong>emancipated</strong> enslaved people.",tip:"E(出)+MAN(手)+CIP(拿)+ATE=從手中放出=解放",emoji:"🕊️",roots:["e","man","cip","ate"]},
    {word:"embellish",chinese:"裝飾/潤飾",sentence:"He tends to <strong>embellish</strong> his stories.",tip:"EM(使)+BELL(美)+ISH=使變美=裝飾",emoji:"✨",roots:["em","bell","ish"]},
    {word:"empathy",chinese:"同理心/共情",sentence:"A good leader shows <strong>empathy</strong> for their team.",tip:"EM(在內)+PATH(感受)+Y=感受別人內心=同理心",emoji:"💗",roots:["em","path","y"]},
    {word:"empirical",chinese:"經驗的/實證的",sentence:"The theory was supported by <strong>empirical</strong> evidence.",tip:"EM(在)+PIRIC(經驗)+AL=基於經驗的=實證的",emoji:"🔬",roots:["em","piric","al"]},
    {word:"emulate",chinese:"效仿/模仿",sentence:"Young athletes <strong>emulate</strong> their heroes.",tip:"EMUL(競爭)+ATE=競相模仿=效仿",emoji:"🪞",roots:["emul","ate"]},
    {word:"endemic",chinese:"地方性的/特有的",sentence:"Malaria is <strong>endemic</strong> in tropical regions.",tip:"EN(在內)+DEM(人民)+IC=在某地人民中=地方性的",emoji:"🗺️",roots:["en","dem","ic"]},
    {word:"enervate",chinese:"使衰弱/使無力",sentence:"The heat <strong>enervated</strong> everyone at the outdoor event.",tip:"E(出)+NERV(神經)+ATE=抽出神經=使衰弱",emoji:"😫",roots:["e","nerv","ate"]},
    {word:"engender",chinese:"產生/引起",sentence:"Trust <strong>engenders</strong> loyalty.",tip:"EN(使)+GENDER(產生)=使產生",emoji:"🌱",roots:["en","gender"]},
    {word:"enigma",chinese:"謎/神秘的人或事",sentence:"Her disappearance remains an <strong>enigma</strong>.",tip:"ENIGMA=難以理解的謎",emoji:"❓",roots:["enigma"]},
    {word:"ennui",chinese:"厭倦/無聊",sentence:"A sense of <strong>ennui</strong> settled over him.",tip:"ENNUI(法語)=深深的無聊感=厭倦",emoji:"😑",roots:["ennui"]},
    {word:"ephemeral",chinese:"短暫的/轉瞬即逝的",sentence:"Fame can be <strong>ephemeral</strong>.",tip:"EPH(在上)+HEMER(天)+AL=只存一天=短暫的",emoji:"🌸",roots:["epi","hemer","al"]},
    {word:"epitome",chinese:"典型/縮影",sentence:"She is the <strong>epitome</strong> of grace.",tip:"EPI(在上)+TOME(切)=在表面上看到的=典型",emoji:"⭐",roots:["epi","tome"]},
    {word:"equanimity",chinese:"平靜/鎮定",sentence:"He faced the crisis with <strong>equanimity</strong>.",tip:"EQU(平等)+ANIM(心)+ITY=心保持平穩=平靜",emoji:"🧘",roots:["equ","anim","ity"]},
    {word:"equivocal",chinese:"模棱兩可的/含糊的",sentence:"His response was <strong>equivocal</strong> and unhelpful.",tip:"EQUI(平等)+VOC(聲音)+AL=兩邊聲音一樣=含糊的",emoji:"🤷",roots:["equi","voc","al"]},
    {word:"eradicate",chinese:"根除/消滅",sentence:"The goal is to <strong>eradicate</strong> poverty.",tip:"E(出)+RADIC(根)+ATE=把根拔出=根除",emoji:"🌿",roots:["e","radic","ate"]},
    {word:"erratic",chinese:"不穩定的/古怪的",sentence:"His <strong>erratic</strong> driving made passengers nervous.",tip:"ERR(錯誤)+ATIC=到處出錯=不穩定的",emoji:"↔️",roots:["err","atic"]},
    {word:"erudite",chinese:"博學的/有學問的",sentence:"The <strong>erudite</strong> professor impressed his students.",tip:"E(出)+RUD(粗糙)+ITE=從粗糙中出來=博學的",emoji:"🎓",roots:["e","rud","ite"]},
    {word:"eschew",chinese:"避開/戒除",sentence:"She <strong>eschewed</strong> social media entirely.",tip:"ES(離開)+CHEW(咀嚼)=不去嚼=避開",emoji:"🚫",roots:["es","chew"]},
    {word:"esoteric",chinese:"深奧的/少數人懂的",sentence:"The book covers <strong>esoteric</strong> topics in physics.",tip:"ESO(內)+TERIC=內部的人才懂=深奧的",emoji:"🔮",roots:["eso","ter","ic"]},
    {word:"espouse",chinese:"擁護/支持",sentence:"She <strong>espoused</strong> the cause of environmental protection.",tip:"E(出)+SPOUSE(配偶)=像嫁給一樣投入=擁護",emoji:"💍",roots:["e","spouse"]},
    {word:"ethereal",chinese:"空靈的/超凡的",sentence:"The dancer had an <strong>ethereal</strong> quality.",tip:"ETHER(以太/天空)+EAL=天空般的=空靈的",emoji:"✨",roots:["ether","eal"]},
    {word:"euphemism",chinese:"委婉語",sentence:"'Passed away' is a <strong>euphemism</strong> for 'died'.",tip:"EU(好)+PHEM(說)+ISM=說好聽話=委婉語",emoji:"🌺",roots:["eu","phem","ism"]},
    {word:"exacerbate",chinese:"加劇/使惡化",sentence:"The drought <strong>exacerbated</strong> the food shortage.",tip:"EX(加強)+ACERB(酸苦)+ATE=使更苦=加劇",emoji:"📈",roots:["ex","acerb","ate"]},
    {word:"exalt",chinese:"提升/讚揚",sentence:"The poem <strong>exalts</strong> the beauty of nature.",tip:"EX(出)+ALT(高)=提到高處=提升/讚揚",emoji:"🙌",roots:["ex","alt"]},
    {word:"exemplary",chinese:"模範的/典型的",sentence:"Her conduct was <strong>exemplary</strong>.",tip:"EXEMPL(例子)+ARY=可做例子的=模範的",emoji:"🏅",roots:["exempl","ary"]},
    {word:"exhort",chinese:"勸告/敦促",sentence:"The coach <strong>exhorted</strong> the team to try harder.",tip:"EX(加強)+HORT(鼓勵)=強烈鼓勵=勸告",emoji:"📣",roots:["ex","hort"]},
    {word:"exonerate",chinese:"免除罪責/證明無罪",sentence:"DNA evidence <strong>exonerated</strong> the wrongly convicted man.",tip:"EX(離開)+ONER(負擔)+ATE=去掉負擔=免除罪責",emoji:"⚖️",roots:["ex","oner","ate"]},
    {word:"expedient",chinese:"權宜的/方便的",sentence:"It was <strong>expedient</strong> to agree rather than argue.",tip:"EX(出)+PED(腳)+IENT=把腳抽出=方便快速的",emoji:"⚡",roots:["ex","ped","ient"]},
    {word:"expunge",chinese:"刪除/抹去",sentence:"The court ordered the record to be <strong>expunged</strong>.",tip:"EX(出)+PUNGE(刺)=刺掉=刪除",emoji:"🗑️",roots:["ex","punge"]},
    {word:"extol",chinese:"讚美/頌揚",sentence:"Critics <strong>extolled</strong> the film for its originality.",tip:"EX(出)+TOL(舉起)=高高舉起讚美=頌揚",emoji:"🎉",roots:["ex","tol"]},
    {word:"extraneous",chinese:"無關的/外來的",sentence:"Remove all <strong>extraneous</strong> details from the report.",tip:"EXTRA(外面)+NEOUS=外面來的=無關的",emoji:"🚮",roots:["extra","neous"]},
    {word:"exuberant",chinese:"充滿活力的/繁茂的",sentence:"The children were <strong>exuberant</strong> on the last day of school.",tip:"EX(出)+UBER(豐富)+ANT=豐富溢出=充滿活力的",emoji:"🌳",roots:["ex","uber","ant"]},
    {word:"facetious",chinese:"滑稽的/不認真的",sentence:"He made a <strong>facetious</strong> remark that annoyed everyone.",tip:"FACET(面)+IOUS=多面的玩笑=滑稽的",emoji:"😜",roots:["facet","ious"]},
    {word:"fallacious",chinese:"謬誤的/不合邏輯的",sentence:"The argument was based on <strong>fallacious</strong> reasoning.",tip:"FALL(欺騙)+AC+IOUS=欺騙性的=謬誤的",emoji:"❌",roots:["fall","ac","ious"]},
    {word:"fastidious",chinese:"挑剔的/一絲不苟的",sentence:"She was <strong>fastidious</strong> about cleanliness.",tip:"FASTIDI(厭惡)+OUS=容易厭惡的=挑剔的",emoji:"🧐",roots:["fastidi","ous"]},
    {word:"fervent",chinese:"熱烈的/熱情的",sentence:"She is a <strong>fervent</strong> supporter of the cause.",tip:"FERV(沸騰)+ENT=沸騰般熱=熱烈的",emoji:"🔥",roots:["ferv","ent"]},
    {word:"fickle",chinese:"善變的/反覆無常的",sentence:"Public opinion is notoriously <strong>fickle</strong>.",tip:"FICKLE=容易改變的=善變的",emoji:"🌦️",roots:["fickle"]},
    {word:"flagrant",chinese:"公然的/惡名昭彰的",sentence:"It was a <strong>flagrant</strong> violation of human rights.",tip:"FLAGR(燃燒)+ANT=像火燒般明顯=公然的",emoji:"🔥",roots:["flagr","ant"]},
    {word:"fledgling",chinese:"初出茅廬的/新手",sentence:"The <strong>fledgling</strong> company struggled in its first year.",tip:"FLEDGE(長羽毛)+LING=剛長羽毛的小鳥=新手",emoji:"🐣",roots:["fledg","ling"]},
    {word:"flippant",chinese:"輕率的/不嚴肅的",sentence:"His <strong>flippant</strong> response angered the teacher.",tip:"FLIP(翻轉)+ANT=隨意翻轉態度=輕率的",emoji:"🙃",roots:["flip","ant"]},
    {word:"florid",chinese:"華麗的/紅潤的",sentence:"His <strong>florid</strong> writing style was hard to read.",tip:"FLOR(花)+ID=像花一樣華麗=華麗的",emoji:"🌹",roots:["flor","id"]},
    {word:"fluctuate",chinese:"波動/變動",sentence:"Prices <strong>fluctuate</strong> with supply and demand.",tip:"FLUCT(流動)+UATE=像波浪流動=波動",emoji:"📊",roots:["fluct","uate"]},
    {word:"foment",chinese:"煽動/激起",sentence:"The rebels tried to <strong>foment</strong> a revolution.",tip:"FO(加溫)+MENT=加熱激發=煽動",emoji:"🔥",roots:["fo","ment"]},
    {word:"forbearance",chinese:"忍耐/克制",sentence:"She showed great <strong>forbearance</strong> in dealing with him.",tip:"FOR(加強)+BEAR(承受)+ANCE=承受住=忍耐",emoji:"🧘",roots:["for","bear","ance"]},
    {word:"forensic",chinese:"法醫的/法庭的",sentence:"<strong>Forensic</strong> evidence linked him to the crime.",tip:"FORENS(法庭)+IC=法庭的",emoji:"🔬",roots:["forens","ic"]},
    {word:"formidable",chinese:"可怕的/令人敬畏的",sentence:"She faced a <strong>formidable</strong> opponent in the final.",tip:"FORMID(恐懼)+ABLE=令人恐懼的=可怕的",emoji:"💪",roots:["formid","able"]},
    {word:"fortuitous",chinese:"偶然的/幸運的",sentence:"Their meeting was entirely <strong>fortuitous</strong>.",tip:"FORTUIT(偶然)+OUS=偶然發生的=幸運的",emoji:"🍀",roots:["fortuit","ous"]},
    {word:"fractious",chinese:"易怒的/難管教的",sentence:"The <strong>fractious</strong> toddler refused to nap.",tip:"FRACT(打碎)+IOUS=容易碎裂的脾氣=易怒的",emoji:"😤",roots:["fract","ious"]},
    {word:"frivolous",chinese:"輕浮的/不重要的",sentence:"The lawsuit was dismissed as <strong>frivolous</strong>.",tip:"FRIVOL(輕浮)+OUS=輕浮的",emoji:"🎪",roots:["frivol","ous"]},
    {word:"frugal",chinese:"節儉的/樸素的",sentence:"His <strong>frugal</strong> habits helped him save money.",tip:"FRUG(果實)+AL=只吃果實就夠=節儉的",emoji:"💰",roots:["frug","al"]},
    {word:"furtive",chinese:"鬼鬼祟祟的/偷偷的",sentence:"He cast a <strong>furtive</strong> glance over his shoulder.",tip:"FURT(偷)+IVE=偷偷摸摸的=鬼祟的",emoji:"👀",roots:["furt","ive"]},
    {word:"futile",chinese:"無用的/徒勞的",sentence:"All attempts to save the building were <strong>futile</strong>.",tip:"FUT(流)+ILE=像水流走般無用=徒勞的",emoji:"🕳️",roots:["fut","ile"]},
    {word:"galvanize",chinese:"激勵/刺激",sentence:"The speech <strong>galvanized</strong> the crowd into action.",tip:"GALVAN(電)+IZE=像電擊般刺激=激勵",emoji:"⚡",roots:["galvan","ize"]},
    {word:"garner",chinese:"收集/獲得",sentence:"The film <strong>garnered</strong> positive reviews.",tip:"GARNER=穀倉=收集",emoji:"🧺",roots:["garner"]},
    {word:"garrulous",chinese:"嘮叨的/多話的",sentence:"The <strong>garrulous</strong> neighbor talked for hours.",tip:"GARR(聊天)+ULOUS=太多聊天=嘮叨的",emoji:"🗣️",roots:["garr","ul","ous"]},
    {word:"germane",chinese:"有關的/切題的",sentence:"His comments were not <strong>germane</strong> to the discussion.",tip:"GERM(種子)+ANE=同一顆種子=有關的",emoji:"🎯",roots:["germ","ane"]},
    {word:"glacial",chinese:"冰川的/冷漠的",sentence:"She received a <strong>glacial</strong> stare from her boss.",tip:"GLACI(冰)+AL=像冰一樣的=冷漠的",emoji:"🧊",roots:["glaci","al"]},
    {word:"grandiose",chinese:"宏偉的/浮誇的",sentence:"He had <strong>grandiose</strong> plans that never materialized.",tip:"GRAND(大)+IOSE=誇大的=浮誇的",emoji:"🏰",roots:["grand","iose"]},
    {word:"gratuitous",chinese:"無償的/無端的",sentence:"The movie had too much <strong>gratuitous</strong> violence.",tip:"GRATU(恩惠)+ITOUS=沒有必要給的=無端的",emoji:"🙄",roots:["gratu","it","ous"]},
    {word:"gregarious",chinese:"群居的/愛交際的",sentence:"She is very <strong>gregarious</strong> and loves parties.",tip:"GREG(群)+ARIOUS=喜歡群體的=愛交際的",emoji:"🎉",roots:["greg","ar","ious"]},
    {word:"guile",chinese:"狡詐/詭計",sentence:"He used <strong>guile</strong> rather than force to get what he wanted.",tip:"GUILE=狡猾的手段=詭計",emoji:"🦊",roots:["guile"]},
    {word:"hackneyed",chinese:"陳腐的/老套的",sentence:"The plot relied on <strong>hackneyed</strong> cliches.",tip:"HACKNEY(出租馬)=被騎太多次=老套的",emoji:"🐴",roots:["hackney","ed"]},
    {word:"hapless",chinese:"不幸的/倒楣的",sentence:"The <strong>hapless</strong> tourist lost his passport.",tip:"HAP(運氣)+LESS=沒有運氣的=不幸的",emoji:"😟",roots:["hap","less"]},
    {word:"harbinger",chinese:"先兆/預兆",sentence:"Crocuses are a <strong>harbinger</strong> of spring.",tip:"HARBOR(港口)+INGER=先到港口通報的人=先兆",emoji:"🌅",roots:["harb","inger"]},
    {word:"harrowing",chinese:"令人痛苦的/悲慘的",sentence:"The survivors shared <strong>harrowing</strong> tales of escape.",tip:"HARROW(耙地)=被耙子刮過般痛苦=令人痛苦的",emoji:"😰",roots:["harrow","ing"]},
    {word:"haughty",chinese:"傲慢的/自大的",sentence:"Her <strong>haughty</strong> manner put people off.",tip:"HAUGHT(高)+Y=自認為高高在上=傲慢的",emoji:"👃",roots:["haught","y"]},
    {word:"hedonism",chinese:"享樂主義",sentence:"A life of pure <strong>hedonism</strong> left him feeling empty.",tip:"HEDON(快樂)+ISM=追求快樂主義=享樂主義",emoji:"🍹",roots:["hedon","ism"]},
    {word:"hegemony",chinese:"霸權/支配地位",sentence:"The country sought <strong>hegemony</strong> over the region.",tip:"HEGEMON(領導)+Y=領導地位=霸權",emoji:"🏛️",roots:["hegemon","y"]},
    {word:"heinous",chinese:"極惡的/可憎的",sentence:"Murder is a <strong>heinous</strong> crime.",tip:"HEIN(仇恨)+OUS=令人仇恨的=極惡的",emoji:"😈",roots:["hein","ous"]},
    {word:"heresy",chinese:"異端/邪說",sentence:"His views were considered <strong>heresy</strong> by the church.",tip:"HERES(選擇)+Y=選擇不同信仰=異端",emoji:"🔥",roots:["heres","y"]},
    {word:"hiatus",chinese:"間斷/中斷",sentence:"The band went on a two-year <strong>hiatus</strong>.",tip:"HIATUS=裂開的缺口=中斷",emoji:"⏸️",roots:["hiatus"]},
    {word:"hierarchy",chinese:"等級制度/層級",sentence:"The company has a strict <strong>hierarchy</strong>.",tip:"HIER(神聖)+ARCH(統治)+Y=神聖的統治順序=等級制度",emoji:"📊",roots:["hier","arch","y"]},
    {word:"histrionic",chinese:"做作的/戲劇化的",sentence:"Her <strong>histrionic</strong> outburst embarrassed everyone.",tip:"HISTRION(演員)+IC=像演員般=做作的",emoji:"🎭",roots:["histrion","ic"]},
    {word:"homogeneous",chinese:"同質的/一致的",sentence:"The community was quite <strong>homogeneous</strong> in culture.",tip:"HOMO(相同)+GEN(種類)+EOUS=同種類的=同質的",emoji:"🔲",roots:["homo","gen","eous"]},
    {word:"hubris",chinese:"傲慢/自大",sentence:"His <strong>hubris</strong> led to his downfall.",tip:"HUBRIS=過度的自負=傲慢",emoji:"👑",roots:["hubris"]},
    {word:"hyperbole",chinese:"誇張法/誇大",sentence:"Saying 'I've told you a million times' is <strong>hyperbole</strong>.",tip:"HYPER(超過)+BOLE(扔)=扔得太遠=誇大",emoji:"🎭",roots:["hyper","bole"]},
    {word:"iconoclast",chinese:"打破傳統者/破壞偶像者",sentence:"The artist was an <strong>iconoclast</strong> who defied convention.",tip:"ICONO(偶像)+CLAST(打碎)=打碎偶像=打破傳統者",emoji:"🔨",roots:["icono","clast"]},
    {word:"idyllic",chinese:"田園的/寧靜的",sentence:"They spent an <strong>idyllic</strong> summer in the countryside.",tip:"IDYLL(田園詩)+IC=田園詩般的=寧靜的",emoji:"🏡",roots:["idyll","ic"]},
    {word:"ignominy",chinese:"恥辱/不名譽",sentence:"He suffered the <strong>ignominy</strong> of public defeat.",tip:"IG(不)+NOM(名聲)+INY=沒有好名聲=恥辱",emoji:"😥",roots:["ig","nom","iny"]},
    {word:"illicit",chinese:"非法的/不正當的",sentence:"The police cracked down on <strong>illicit</strong> trade.",tip:"IL(不)+LICIT(合法)=不合法的=非法的",emoji:"🚨",roots:["il","licit"]},
    {word:"imminent",chinese:"即將發生的/迫在眉睫的",sentence:"A storm is <strong>imminent</strong>.",tip:"IM(在上)+MIN(突出)+ENT=懸在頭上的=即將發生的",emoji:"⏰",roots:["im","min","ent"]},
    {word:"immutable",chinese:"不可改變的/永恆的",sentence:"The laws of physics are <strong>immutable</strong>.",tip:"IM(不)+MUT(改變)+ABLE=不能改變的",emoji:"🗿",roots:["im","mut","able"]},
    {word:"impasse",chinese:"僵局/絕路",sentence:"Negotiations reached an <strong>impasse</strong>.",tip:"IM(不)+PASSE(通過)=不能通過=僵局",emoji:"🚧",roots:["im","passe"]},
    {word:"impeccable",chinese:"無懈可擊的/完美的",sentence:"Her <strong>impeccable</strong> manners impressed everyone.",tip:"IM(不)+PECC(罪)+ABLE=不會犯錯的=完美的",emoji:"💯",roots:["im","pecc","able"]},
    {word:"impediment",chinese:"障礙/阻礙",sentence:"His stutter was an <strong>impediment</strong> to communication.",tip:"IM(在)+PED(腳)+IMENT=絆住腳的=障礙",emoji:"🚧",roots:["im","ped","iment"]},
    {word:"imperative",chinese:"必要的/命令的",sentence:"It is <strong>imperative</strong> that we act now.",tip:"IMPER(命令)+ATIVE=命令般必須的=必要的",emoji:"❗",roots:["imper","ative"]},
    {word:"imperious",chinese:"專橫的/傲慢的",sentence:"She spoke in an <strong>imperious</strong> tone.",tip:"IMPER(命令)+IOUS=愛命令人的=專橫的",emoji:"👸",roots:["imper","ious"]},
    {word:"impervious",chinese:"不受影響的/防水的",sentence:"He was <strong>impervious</strong> to criticism.",tip:"IM(不)+PERV(穿透)+IOUS=穿不透的=不受影響的",emoji:"🛡️",roots:["im","perv","ious"]},
    {word:"impetuous",chinese:"衝動的/魯莽的",sentence:"His <strong>impetuous</strong> decision caused problems.",tip:"IM(向)+PET(追求)+UOUS=猛烈追求=衝動的",emoji:"💨",roots:["im","pet","uous"]},
    {word:"implacable",chinese:"難以平息的/無情的",sentence:"She was his <strong>implacable</strong> enemy.",tip:"IM(不)+PLAC(平息)+ABLE=不能平息的",emoji:"😤",roots:["im","plac","able"]},
    {word:"implicit",chinese:"含蓄的/暗示的",sentence:"There was an <strong>implicit</strong> threat in his words.",tip:"IM(在內)+PLIC(折)+IT=折在裡面的=含蓄的",emoji:"🤫",roots:["im","plic","it"]},
    {word:"impromptu",chinese:"即興的/臨時的",sentence:"She gave an <strong>impromptu</strong> speech at the party.",tip:"IM(不)+PROMPT(準備)+U=沒有準備的=即興的",emoji:"🎤",roots:["im","prompt","u"]},
    {word:"impudent",chinese:"無禮的/厚顏的",sentence:"The <strong>impudent</strong> child talked back to the teacher.",tip:"IM(不)+PUD(羞恥)+ENT=不知恥的=無禮的",emoji:"😏",roots:["im","pud","ent"]},
    {word:"impunity",chinese:"免罰/不受懲罰",sentence:"They acted with <strong>impunity</strong>, knowing no one would stop them.",tip:"IM(不)+PUN(懲罰)+ITY=不受懲罰",emoji:"🏴‍☠️",roots:["im","pun","ity"]},
    {word:"inadvertent",chinese:"無意的/不注意的",sentence:"The error was <strong>inadvertent</strong>, not deliberate.",tip:"IN(不)+AD(向)+VERT(轉)+ENT=沒有注意轉向=無意的",emoji:"🤷",roots:["in","ad","vert","ent"]},
    {word:"inane",chinese:"愚蠢的/空洞的",sentence:"Stop asking <strong>inane</strong> questions.",tip:"IN(空)+ANE=空洞的=愚蠢的",emoji:"🙄",roots:["in","ane"]},
    {word:"incandescent",chinese:"白熱的/熱情的",sentence:"The filament glowed with <strong>incandescent</strong> light.",tip:"IN(在內)+CAND(白/亮)+ESCENT=發出白光=白熱的",emoji:"💡",roots:["in","cand","escent"]},
    {word:"incendiary",chinese:"煽動性的/縱火的",sentence:"His <strong>incendiary</strong> remarks sparked protests.",tip:"IN(在內)+CEND(燃燒)+IARY=引起燃燒的=煽動的",emoji:"🔥",roots:["in","cend","iary"]},
    {word:"incessant",chinese:"不停的/連續的",sentence:"The <strong>incessant</strong> noise kept her awake.",tip:"IN(不)+CESS(停止)+ANT=不停止的=不停的",emoji:"🔄",roots:["in","cess","ant"]},
    {word:"incipient",chinese:"初期的/萌芽的",sentence:"The doctor detected <strong>incipient</strong> signs of the disease.",tip:"IN(在內)+CIP(開始)+IENT=開始在內部=初期的",emoji:"🌱",roots:["in","cip","ient"]},
    {word:"incisive",chinese:"敏銳的/深刻的",sentence:"Her <strong>incisive</strong> analysis impressed the panel.",tip:"IN(在內)+CIS(切)+IVE=切入核心的=敏銳的",emoji:"🔪",roots:["in","cis","ive"]},
    {word:"incite",chinese:"煽動/激起",sentence:"The speech was designed to <strong>incite</strong> violence.",tip:"IN(在內)+CITE(激動)=使內心激動=煽動",emoji:"📢",roots:["in","cite"]},
    {word:"incongruous",chinese:"不協調的/不相稱的",sentence:"A castle in the desert looks <strong>incongruous</strong>.",tip:"IN(不)+CON(一起)+GRU(一致)+OUS=不一致的",emoji:"🧩",roots:["in","con","gru","ous"]},
    {word:"incontrovertible",chinese:"無可爭辯的/確鑿的",sentence:"The DNA evidence was <strong>incontrovertible</strong>.",tip:"IN(不)+CONTRO(反對)+VERT(轉)+IBLE=不能反轉的",emoji:"✅",roots:["in","contro","vert","ible"]},
    {word:"incorrigible",chinese:"不可救藥的/屢教不改的",sentence:"The <strong>incorrigible</strong> thief was sent to prison again.",tip:"IN(不)+CORRIG(糾正)+IBLE=不能糾正的=不可救藥的",emoji:"🔄",roots:["in","corrig","ible"]},
    {word:"incredulous",chinese:"不相信的/懷疑的",sentence:"She gave him an <strong>incredulous</strong> look.",tip:"IN(不)+CRED(相信)+ULOUS=不相信的",emoji:"😲",roots:["in","cred","ulous"]},
    {word:"inculcate",chinese:"灌輸/反覆教導",sentence:"Parents try to <strong>inculcate</strong> values in their children.",tip:"IN(在內)+CULC(踩)+ATE=踩進腦子裡=灌輸",emoji:"📖",roots:["in","culc","ate"]},
    {word:"incumbent",chinese:"現任的/義務的",sentence:"It is <strong>incumbent</strong> upon us to help.",tip:"IN(在上)+CUMB(躺)+ENT=躺在職位上的=現任的",emoji:"🪑",roots:["in","cumb","ent"]},
    {word:"indigenous",chinese:"本土的/土著的",sentence:"<strong>Indigenous</strong> cultures deserve respect and preservation.",tip:"INDI(在內)+GEN(出生)+OUS=在裡面出生的=本土的",emoji:"🌍",roots:["indi","gen","ous"]},
    {word:"indigent",chinese:"貧困的/窮困的",sentence:"The shelter provides food for <strong>indigent</strong> families.",tip:"INDI(在內)+GENT=內部缺乏的=貧困的",emoji:"🏚️",roots:["indi","gent"]},
    {word:"indignant",chinese:"憤慨的/義憤的",sentence:"She was <strong>indignant</strong> at the unfair treatment.",tip:"IN(不)+DIGN(值得)+ANT=不值得被這樣對待=憤慨的",emoji:"😠",roots:["in","dign","ant"]},
    {word:"indolent",chinese:"懶惰的/懈怠的",sentence:"The <strong>indolent</strong> cat slept all day.",tip:"IN(不)+DOL(痛苦)+ENT=不覺得痛苦=懶惰的",emoji:"🦥",roots:["in","dol","ent"]},
    {word:"indomitable",chinese:"不屈不撓的/堅強的",sentence:"Her <strong>indomitable</strong> spirit inspired everyone.",tip:"IN(不)+DOMIT(馴服)+ABLE=不能被馴服的=不屈的",emoji:"💪",roots:["in","domit","able"]},
    {word:"ineffable",chinese:"難以形容的/不可言喻的",sentence:"The beauty of the sunset was <strong>ineffable</strong>.",tip:"IN(不)+EF(出)+FABLE(說)=說不出的=難以形容的",emoji:"🌅",roots:["in","ef","fable"]},
    {word:"inexorable",chinese:"不可阻擋的/無情的",sentence:"The <strong>inexorable</strong> march of time changes everything.",tip:"IN(不)+EXOR(求)+ABLE=求也沒用的=不可阻擋的",emoji:"⏳",roots:["in","exor","able"]},
    {word:"infallible",chinese:"永不犯錯的/可靠的",sentence:"No system is <strong>infallible</strong>.",tip:"IN(不)+FALL(犯錯)+IBLE=不會犯錯的",emoji:"✓",roots:["in","fall","ible"]},
    {word:"inflammatory",chinese:"煽動性的/引起炎症的",sentence:"His <strong>inflammatory</strong> comments provoked outrage.",tip:"IN(在內)+FLAMM(火)+ATORY=點火的=煽動的",emoji:"🔥",roots:["in","flamm","atory"]},
    {word:"ingenious",chinese:"巧妙的/有創造力的",sentence:"She came up with an <strong>ingenious</strong> solution.",tip:"IN(在內)+GEN(產生)+IOUS=內在產生的聰明=巧妙的",emoji:"💡",roots:["in","gen","ious"]},
    {word:"inherent",chinese:"固有的/內在的",sentence:"There are <strong>inherent</strong> risks in any investment.",tip:"IN(在內)+HER(黏著)+ENT=黏在裡面的=固有的",emoji:"🧬",roots:["in","her","ent"]},
    {word:"innocuous",chinese:"無害的/無毒的",sentence:"The remark seemed <strong>innocuous</strong> but offended some.",tip:"IN(不)+NOC(傷害)+UOUS=不會傷害的=無害的",emoji:"🐑",roots:["in","noc","uous"]},
    {word:"innuendo",chinese:"暗示/影射",sentence:"The article was full of malicious <strong>innuendo</strong>.",tip:"IN(向)+NU(點頭)+ENDO=用點頭暗示=影射",emoji:"🤫",roots:["in","nu","endo"]},
    {word:"insatiable",chinese:"貪得無厭的/不知足的",sentence:"He had an <strong>insatiable</strong> appetite for knowledge.",tip:"IN(不)+SATI(滿足)+ABLE=不能滿足的=貪得無厭的",emoji:"🕳️",roots:["in","sati","able"]},
    {word:"inscrutable",chinese:"高深莫測的/難理解的",sentence:"His <strong>inscrutable</strong> expression revealed nothing.",tip:"IN(不)+SCRUT(檢查)+ABLE=不能檢查的=高深莫測的",emoji:"🎭",roots:["in","scrut","able"]},
    {word:"insidious",chinese:"暗中為害的/潛伏的",sentence:"The disease has an <strong>insidious</strong> onset.",tip:"IN(在內)+SID(坐)+IOUS=坐在裡面伺機=潛伏的",emoji:"🐍",roots:["in","sid","ious"]},
    {word:"insinuate",chinese:"暗示/含沙射影",sentence:"Are you <strong>insinuating</strong> that I lied?",tip:"IN(在內)+SINU(彎曲)+ATE=彎彎曲曲暗示=含沙射影",emoji:"🐍",roots:["in","sinu","ate"]},
    {word:"insipid",chinese:"無味的/乏味的",sentence:"The food was bland and <strong>insipid</strong>.",tip:"IN(不)+SIPID(味道)=沒有味道的=乏味的",emoji:"😶",roots:["in","sipid"]},
    {word:"insolent",chinese:"無禮的/傲慢的",sentence:"His <strong>insolent</strong> reply shocked the audience.",tip:"IN(不)+SOL(習慣)+ENT=不守規矩的=無禮的",emoji:"😤",roots:["in","sol","ent"]},
    {word:"instigate",chinese:"煽動/唆使",sentence:"He was accused of <strong>instigating</strong> the riot.",tip:"IN(在內)+STIG(刺)+ATE=從內部刺激=煽動",emoji:"📌",roots:["in","stig","ate"]},
    {word:"insular",chinese:"孤立的/狹隘的",sentence:"Their <strong>insular</strong> community resisted change.",tip:"INSUL(島)+AR=像島嶼般孤立=狹隘的",emoji:"🏝️",roots:["insul","ar"]},
    {word:"insurgent",chinese:"叛亂者/起義者",sentence:"The <strong>insurgents</strong> attacked the military base.",tip:"IN(向)+SURG(升起)+ENT=起來反抗的人=叛亂者",emoji:"⚔️",roots:["in","surg","ent"]},
    {word:"intangible",chinese:"無形的/難以觸摸的",sentence:"Trust is an <strong>intangible</strong> asset.",tip:"IN(不)+TANG(觸摸)+IBLE=不能觸摸的=無形的",emoji:"👻",roots:["in","tang","ible"]},
    {word:"integral",chinese:"不可或缺的/完整的",sentence:"Teamwork is <strong>integral</strong> to our success.",tip:"INTEGR(完整)+AL=使完整的=不可或缺的",emoji:"🧩",roots:["integr","al"]},
    {word:"intractable",chinese:"難以處理的/倔強的",sentence:"The conflict proved <strong>intractable</strong>.",tip:"IN(不)+TRACT(拉)+ABLE=拉不動的=難以處理的",emoji:"🪨",roots:["in","tract","able"]},
    {word:"intransigent",chinese:"不妥協的/固執的",sentence:"Both sides remained <strong>intransigent</strong> in negotiations.",tip:"IN(不)+TRANS(跨越)+IG+ENT=不肯跨越=不妥協的",emoji:"🧱",roots:["in","trans","ig","ent"]},
    {word:"intrinsic",chinese:"固有的/本質的",sentence:"Curiosity is <strong>intrinsic</strong> to human nature.",tip:"INTR(在內)+INSIC=在內部的=固有的",emoji:"💎",roots:["intr","insic"]},
    {word:"inundate",chinese:"淹沒/使應接不暇",sentence:"They were <strong>inundated</strong> with applications.",tip:"IN(在內)+UND(波浪)+ATE=波浪湧入=淹沒",emoji:"🌊",roots:["in","und","ate"]},
    {word:"invective",chinese:"謾罵/痛斥",sentence:"He hurled <strong>invective</strong> at his opponents.",tip:"IN(向)+VECT(攻擊)+IVE=向人攻擊=謾罵",emoji:"🗯️",roots:["in","vect","ive"]},
    {word:"inveterate",chinese:"根深蒂固的/積習的",sentence:"He is an <strong>inveterate</strong> liar.",tip:"IN(在內)+VETER(老)+ATE=老在裡面=根深蒂固的",emoji:"🌳",roots:["in","veter","ate"]},
    {word:"inviolable",chinese:"不可侵犯的/神聖的",sentence:"Freedom of speech should be <strong>inviolable</strong>.",tip:"IN(不)+VIOL(暴力)+ABLE=不能用暴力侵犯的",emoji:"🛡️",roots:["in","viol","able"]},
    {word:"irascible",chinese:"易怒的/暴躁的",sentence:"The <strong>irascible</strong> old man yelled at everyone.",tip:"IR(強調)+ASC(怒)+IBLE=容易發怒的=易怒的",emoji:"😡",roots:["ir","asc","ible"]},
    {word:"ironic",chinese:"諷刺的/出乎意料的",sentence:"It's <strong>ironic</strong> that a fire station burned down.",tip:"IRON(假裝不知道)+IC=假裝不知道的=諷刺的",emoji:"🙃",roots:["iron","ic"]},
    {word:"irreverent",chinese:"不敬的/無禮的",sentence:"His <strong>irreverent</strong> humor offended some people.",tip:"IR(不)+REVER(敬畏)+ENT=不敬畏的=不敬的",emoji:"😈",roots:["ir","rever","ent"]},
    {word:"itinerant",chinese:"巡迴的/流動的",sentence:"The <strong>itinerant</strong> musician traveled from town to town.",tip:"ITINER(旅行)+ANT=旅行的=巡迴的",emoji:"🚶",roots:["itiner","ant"]},
    {word:"jubilant",chinese:"歡欣的/喜悅的",sentence:"The team was <strong>jubilant</strong> after winning the championship.",tip:"JUBIL(歡呼)+ANT=歡呼的=歡欣的",emoji:"🎊",roots:["jubil","ant"]},
    {word:"judicious",chinese:"明智的/審慎的",sentence:"A <strong>judicious</strong> use of resources is essential.",tip:"JUDIC(判斷)+IOUS=善於判斷的=明智的",emoji:"⚖️",roots:["judic","ious"]},
    {word:"juxtapose",chinese:"並列/並置比較",sentence:"The exhibit <strong>juxtaposes</strong> old and new art.",tip:"JUXTA(旁邊)+POSE(放)=放在旁邊=並列",emoji:"↔️",roots:["juxta","pose"]},
    {word:"labyrinth",chinese:"迷宮/錯綜複雜",sentence:"The old city is a <strong>labyrinth</strong> of narrow streets.",tip:"LABYRINTH=希臘神話的迷宮=錯綜複雜",emoji:"🌀",roots:["labyrinth"]},
    {word:"laconic",chinese:"簡潔的/言簡意賅的",sentence:"His <strong>laconic</strong> reply gave nothing away.",tip:"LACON(斯巴達人)+IC=像斯巴達人般簡短=簡潔的",emoji:"🤐",roots:["lacon","ic"]},
    {word:"lament",chinese:"哀悼/悲嘆",sentence:"She <strong>lamented</strong> the loss of her childhood home.",tip:"LAMENT=悲傷的哭泣=哀悼",emoji:"😢",roots:["lament"]},
    {word:"languish",chinese:"衰弱/憔悴",sentence:"The prisoner <strong>languished</strong> in jail for years.",tip:"LANGU(疲倦)+ISH=變得疲倦=衰弱",emoji:"😩",roots:["langu","ish"]},
    {word:"laudable",chinese:"值得讚揚的/可嘉的",sentence:"Her efforts are <strong>laudable</strong>.",tip:"LAUD(讚美)+ABLE=值得讚美的",emoji:"👏",roots:["laud","able"]},
    {word:"lavish",chinese:"奢華的/慷慨的",sentence:"They held a <strong>lavish</strong> wedding reception.",tip:"LAVISH=像洗浴般傾瀉=奢華的",emoji:"💎",roots:["lavish"]},
    {word:"lethargic",chinese:"昏昏欲睡的/無精打采的",sentence:"The heat made everyone feel <strong>lethargic</strong>.",tip:"LETHAR(忘記)+GIC=忘記活力=無精打采的",emoji:"😴",roots:["lethar","gic"]},
    {word:"levity",chinese:"輕率/輕浮",sentence:"A little <strong>levity</strong> helped ease the tension.",tip:"LEV(輕)+ITY=輕的態度=輕率",emoji:"😄",roots:["lev","ity"]},
    {word:"litigate",chinese:"訴訟/打官司",sentence:"They decided to <strong>litigate</strong> the dispute in court.",tip:"LITIG(爭訟)+ATE=進行爭訟=訴訟",emoji:"⚖️",roots:["litig","ate"]},
    {word:"lofty",chinese:"崇高的/高聳的",sentence:"He had <strong>lofty</strong> ambitions for the future.",tip:"LOFT(閣樓/高處)+Y=在高處的=崇高的",emoji:"🏔️",roots:["loft","y"]},
    {word:"lucid",chinese:"清晰的/明確的",sentence:"She gave a <strong>lucid</strong> explanation of the theory.",tip:"LUC(光)+ID=有光的=清晰的",emoji:"💡",roots:["luc","id"]},
    {word:"ludicrous",chinese:"荒謬的/可笑的",sentence:"The idea was absolutely <strong>ludicrous</strong>.",tip:"LUD(玩)+ICROUS=像在玩笑=荒謬的",emoji:"🤡",roots:["lud","icrous"]},
    {word:"luminous",chinese:"發光的/明亮的",sentence:"The <strong>luminous</strong> stars lit up the sky.",tip:"LUMIN(光)+OUS=有光的=發光的",emoji:"✨",roots:["lumin","ous"]},
    {word:"magnanimous",chinese:"寬宏大量的/慷慨的",sentence:"He was <strong>magnanimous</strong> in victory.",tip:"MAGN(大)+ANIM(心)+OUS=大心的=寬宏大量的",emoji:"🫶",roots:["magn","anim","ous"]},
    {word:"malevolent",chinese:"惡意的/邪惡的",sentence:"The villain had a <strong>malevolent</strong> grin.",tip:"MAL(壞)+EVOL(願望)+ENT=壞願望的=惡意的",emoji:"😈",roots:["mal","evol","ent"]},
    {word:"malleable",chinese:"可塑的/易受影響的",sentence:"Gold is one of the most <strong>malleable</strong> metals.",tip:"MALL(錘打)+EABLE=可以錘打塑形的=可塑的",emoji:"🔨",roots:["mall","eable"]},
    {word:"mandate",chinese:"授權/命令",sentence:"The government received a <strong>mandate</strong> from voters.",tip:"MAND(命令)+ATE=給予命令=授權",emoji:"📋",roots:["mand","ate"]},
    {word:"manifest",chinese:"顯示/明顯的",sentence:"His frustration was <strong>manifest</strong> in his tone.",tip:"MANI(手)+FEST(打)=用手打出來=明顯的",emoji:"👁️",roots:["mani","fest"]},
    {word:"meander",chinese:"蜿蜒/漫步",sentence:"The river <strong>meanders</strong> through the valley.",tip:"MEANDER=彎曲的河流名=蜿蜒",emoji:"🌊",roots:["meander"]},
    {word:"melancholy",chinese:"憂鬱/悲傷",sentence:"A sense of <strong>melancholy</strong> filled the room.",tip:"MELAN(黑)+CHOLY(膽汁)=黑色膽汁=憂鬱",emoji:"🌧️",roots:["melan","chol","y"]},
    {word:"meticulous",chinese:"一絲不苟的/細緻的",sentence:"She was <strong>meticulous</strong> about every detail.",tip:"METIC(恐懼)+ULOUS=怕出錯的=一絲不苟的",emoji:"🔍",roots:["metic","ul","ous"]},
    {word:"mitigate",chinese:"減輕/緩和",sentence:"We must take steps to <strong>mitigate</strong> the risk.",tip:"MIT(溫和)+IG+ATE=使溫和=減輕",emoji:"🩹",roots:["mit","ig","ate"]},
    {word:"morose",chinese:"鬱悶的/陰沉的",sentence:"He became <strong>morose</strong> after losing his job.",tip:"MOR(脾氣)+OSE=壞脾氣的=鬱悶的",emoji:"😞",roots:["mor","ose"]},
    {word:"mundane",chinese:"平凡的/世俗的",sentence:"She longed to escape her <strong>mundane</strong> routine.",tip:"MUND(世界)+ANE=世界上普通的=平凡的",emoji:"📦",roots:["mund","ane"]},
    {word:"nefarious",chinese:"邪惡的/不法的",sentence:"The villain had <strong>nefarious</strong> plans.",tip:"NE(不)+FAR(正確)+IOUS=不正確的=邪惡的",emoji:"😈",roots:["ne","far","ious"]},
    {word:"negligible",chinese:"微不足道的/可忽略的",sentence:"The difference in cost was <strong>negligible</strong>.",tip:"NEG(不)+LIG(選擇)+IBLE=不值得選的=微不足道的",emoji:"🔬",roots:["neg","lig","ible"]},
    {word:"nonchalant",chinese:"漫不經心的/冷淡的",sentence:"He tried to appear <strong>nonchalant</strong> despite his nervousness.",tip:"NON(不)+CHAL(熱)+ANT=不熱心的=漫不經心的",emoji:"😎",roots:["non","chal","ant"]},
    {word:"nostalgia",chinese:"懷舊/思鄉",sentence:"The old photos filled her with <strong>nostalgia</strong>.",tip:"NOST(回家)+ALGIA(痛)=想回家的痛=懷舊",emoji:"📷",roots:["nost","algia"]},
    {word:"notoriety",chinese:"惡名/臭名昭著",sentence:"The criminal gained <strong>notoriety</strong> for his crimes.",tip:"NOTOR(知名)+IETY=因壞事出名=惡名",emoji:"📰",roots:["notor","iety"]},
    {word:"novice",chinese:"新手/初學者",sentence:"As a <strong>novice</strong>, she made many mistakes.",tip:"NOV(新)+ICE=新的人=新手",emoji:"🐣",roots:["nov","ice"]},
    {word:"noxious",chinese:"有毒的/有害的",sentence:"<strong>Noxious</strong> fumes filled the factory.",tip:"NOX(傷害)+IOUS=有傷害的=有毒的",emoji:"☠️",roots:["nox","ious"]},
    {word:"nuance",chinese:"細微差別/微妙",sentence:"The translator captured every <strong>nuance</strong> of the text.",tip:"NU(雲)+ANCE=像雲般微妙=細微差別",emoji:"🎨",roots:["nu","ance"]},
    {word:"oblivious",chinese:"不在意的/渾然不知的",sentence:"She was <strong>oblivious</strong> to the danger.",tip:"OB(向)+LIV(遺忘)+IOUS=忘記了一切=渾然不知的",emoji:"🙈",roots:["ob","liv","ious"]},
    {word:"obscure",chinese:"模糊的/不出名的",sentence:"The meaning of the poem is quite <strong>obscure</strong>.",tip:"OB(覆蓋)+SCURE(暗)=被覆蓋變暗=模糊的",emoji:"🌫️",roots:["ob","scure"]},
    {word:"obsolete",chinese:"過時的/廢棄的",sentence:"Typewriters are now <strong>obsolete</strong>.",tip:"OB(離開)+SOL(使用)+ETE=不再使用=過時的",emoji:"📟",roots:["ob","sol","ete"]},
    {word:"obstinate",chinese:"固執的/頑固的",sentence:"The <strong>obstinate</strong> child refused to eat vegetables.",tip:"OB(對著)+STIN(站)+ATE=站著不動=固執的",emoji:"🧱",roots:["ob","stin","ate"]},
    {word:"ominous",chinese:"不祥的/凶兆的",sentence:"Dark clouds gathered in an <strong>ominous</strong> sky.",tip:"OMIN(預兆)+OUS=有不好預兆的=不祥的",emoji:"⛈️",roots:["omin","ous"]},
    {word:"opaque",chinese:"不透明的/晦澀的",sentence:"The glass was <strong>opaque</strong> and blocked all light.",tip:"OP(對著)+AQUE=對著看不穿=不透明的",emoji:"⬛",roots:["op","aque"]},
    {word:"opprobrium",chinese:"恥辱/侮辱",sentence:"The scandal brought <strong>opprobrium</strong> upon the family.",tip:"OP(對著)+PROBR(羞恥)+IUM=對著臉的羞恥=恥辱",emoji:"😥",roots:["op","probr","ium"]},
    {word:"ostentatious",chinese:"炫耀的/招搖的",sentence:"His <strong>ostentatious</strong> display of wealth annoyed people.",tip:"OSTENT(展示)+ATIOUS=過度展示的=炫耀的",emoji:"💎",roots:["ostent","at","ious"]},
    {word:"palliate",chinese:"減輕/緩和",sentence:"The drug can <strong>palliate</strong> the symptoms.",tip:"PALL(覆蓋)+IATE=用外衣蓋住=減輕痛苦",emoji:"💊",roots:["pall","iate"]},
    {word:"palpable",chinese:"明顯的/可感知的",sentence:"The tension in the room was <strong>palpable</strong>.",tip:"PALP(觸摸)+ABLE=可以觸摸到的=明顯的",emoji:"✋",roots:["palp","able"]},
    {word:"paradox",chinese:"矛盾/悖論",sentence:"It's a <strong>paradox</strong> that less is more.",tip:"PARA(旁邊)+DOX(觀點)=旁邊的觀點=矛盾",emoji:"🔄",roots:["para","dox"]},
    {word:"paragon",chinese:"模範/典範",sentence:"She is a <strong>paragon</strong> of virtue.",tip:"PARA(旁邊)+GON(角)=鋒芒畢露=典範",emoji:"⭐",roots:["para","gon"]},
    {word:"paramount",chinese:"最重要的/至高的",sentence:"Safety is of <strong>paramount</strong> importance.",tip:"PARA(超過)+MOUNT(山)=超過山的=最高的",emoji:"🏔️",roots:["para","mount"]},
    {word:"parochial",chinese:"狹隘的/地方的",sentence:"His views are too <strong>parochial</strong> for a global company.",tip:"PAROCH(教區)+IAL=只看教區的=狹隘的",emoji:"🏘️",roots:["paroch","ial"]},
    {word:"partisan",chinese:"黨派的/偏袒的",sentence:"The report was clearly <strong>partisan</strong>.",tip:"PARTI(黨派)+SAN=屬於黨派的=偏袒的",emoji:"🏴",roots:["parti","san"]},
    {word:"pathos",chinese:"感染力/哀婉",sentence:"The speech was full of <strong>pathos</strong>.",tip:"PATH(感受)+OS=引起感受=感染力",emoji:"🎭",roots:["path","os"]},
    {word:"paucity",chinese:"少量/缺乏",sentence:"There is a <strong>paucity</strong> of evidence for the claim.",tip:"PAUC(少)+ITY=少的狀態=缺乏",emoji:"📉",roots:["pauc","ity"]},
    {word:"pedantic",chinese:"學究的/賣弄學問的",sentence:"His <strong>pedantic</strong> corrections irritated everyone.",tip:"PED(教)+ANTIC=過度教人的=學究的",emoji:"🤓",roots:["ped","antic"]},
    {word:"penchant",chinese:"嗜好/傾向",sentence:"She has a <strong>penchant</strong> for collecting vintage items.",tip:"PENCH(傾斜)+ANT=傾向於某事=嗜好",emoji:"❤️",roots:["pench","ant"]},
    {word:"penitent",chinese:"懺悔的/後悔的",sentence:"The <strong>penitent</strong> thief asked for forgiveness.",tip:"PEN(懲罰)+IT+ENT=接受懲罰的=懺悔的",emoji:"🙏",roots:["pen","it","ent"]},
    {word:"pensive",chinese:"沉思的/憂慮的",sentence:"She sat in <strong>pensive</strong> silence.",tip:"PENS(思考)+IVE=思考中的=沉思的",emoji:"🤔",roots:["pens","ive"]},
    {word:"perfunctory",chinese:"敷衍的/草率的",sentence:"He gave a <strong>perfunctory</strong> nod without looking up.",tip:"PER(完全)+FUNCT(功能)+ORY=只完成功能=敷衍的",emoji:"🥱",roots:["per","funct","ory"]},
    {word:"peripheral",chinese:"外圍的/次要的",sentence:"Don't focus on <strong>peripheral</strong> issues.",tip:"PERI(周圍)+PHER(帶)+AL=在周圍的=外圍的",emoji:"⭕",roots:["peri","pher","al"]},
    {word:"permeate",chinese:"滲透/瀰漫",sentence:"The smell of coffee <strong>permeated</strong> the house.",tip:"PER(通過)+MEATE(穿過)=穿過去=滲透",emoji:"💨",roots:["per","meate"]},
    {word:"pernicious",chinese:"有害的/惡性的",sentence:"Gossip can have <strong>pernicious</strong> effects.",tip:"PER(完全)+NIC(傷害)+IOUS=完全傷害的=有害的",emoji:"☠️",roots:["per","nic","ious"]},
    {word:"perpetuate",chinese:"使永久/延續",sentence:"The system <strong>perpetuates</strong> inequality.",tip:"PER(完全)+PETU(追求)+ATE=永遠追求=使永久",emoji:"♾️",roots:["per","petu","ate"]},
    {word:"pervasive",chinese:"普遍的/滲透的",sentence:"Corruption is <strong>pervasive</strong> in the system.",tip:"PER(通過)+VAS(走)+IVE=到處走的=普遍的",emoji:"🌐",roots:["per","vas","ive"]},
    {word:"petulant",chinese:"任性的/暴躁的",sentence:"The <strong>petulant</strong> child threw a tantrum.",tip:"PET(追求)+UL+ANT=急躁追求=任性的",emoji:"😤",roots:["pet","ul","ant"]},
    {word:"philanthropy",chinese:"慈善/博愛",sentence:"His <strong>philanthropy</strong> funded many hospitals.",tip:"PHIL(愛)+ANTHROP(人)+Y=愛人類=慈善",emoji:"💝",roots:["phil","anthrop","y"]},
    {word:"placate",chinese:"安撫/平息",sentence:"She tried to <strong>placate</strong> the angry customer.",tip:"PLAC(平靜)+ATE=使平靜=安撫",emoji:"🕊️",roots:["plac","ate"]},
    {word:"platitude",chinese:"陳詞濫調/老生常談",sentence:"His speech was full of empty <strong>platitudes</strong>.",tip:"PLAT(平)+ITUDE=平淡的話=陳詞濫調",emoji:"🗣️",roots:["plat","itude"]},
    {word:"plausible",chinese:"看似合理的/貌似可信的",sentence:"His excuse sounded <strong>plausible</strong>.",tip:"PLAUS(鼓掌)+IBLE=值得鼓掌的=合理的",emoji:"🤔",roots:["plaus","ible"]},
    {word:"plight",chinese:"困境/苦境",sentence:"The <strong>plight</strong> of refugees moved many to donate.",tip:"PLIGHT=危險的處境=困境",emoji:"😰",roots:["plight"]},
    {word:"poignant",chinese:"辛酸的/令人感動的",sentence:"The movie had a <strong>poignant</strong> ending.",tip:"POIGN(刺)+ANT=刺痛心的=辛酸的",emoji:"💔",roots:["poign","ant"]},
    {word:"polarize",chinese:"使兩極化/使對立",sentence:"The issue has <strong>polarized</strong> public opinion.",tip:"POLAR(極)+IZE=使分成兩極=使對立",emoji:"⚡",roots:["polar","ize"]},
    {word:"ponderous",chinese:"笨重的/沉悶的",sentence:"His <strong>ponderous</strong> speech put the audience to sleep.",tip:"PONDER(重)+OUS=太重的=笨重的",emoji:"🐘",roots:["ponder","ous"]},
    {word:"posthumous",chinese:"死後的/遺腹的",sentence:"He received a <strong>posthumous</strong> award for bravery.",tip:"POST(之後)+HUM(埋)+OUS=埋葬之後的=死後的",emoji:"🪦",roots:["post","hum","ous"]},
    {word:"pragmatic",chinese:"務實的/實用的",sentence:"We need a <strong>pragmatic</strong> approach to this problem.",tip:"PRAGMA(事實)+TIC=基於事實的=務實的",emoji:"⚙️",roots:["pragm","atic"]},
    {word:"precarious",chinese:"不穩定的/危險的",sentence:"The economy is in a <strong>precarious</strong> state.",tip:"PREC(祈禱)+ARIOUS=需要祈禱的=不穩定的",emoji:"⚠️",roots:["prec","ar","ious"]},
    {word:"precedent",chinese:"先例/慣例",sentence:"The case set a legal <strong>precedent</strong>.",tip:"PRE(前)+CED(走)+ENT=走在前面的=先例",emoji:"📜",roots:["pre","ced","ent"]},
    {word:"preclude",chinese:"排除/阻止",sentence:"Bad weather <strong>precluded</strong> outdoor activities.",tip:"PRE(前)+CLUDE(關閉)=提前關閉=排除",emoji:"🚫",roots:["pre","clude"]},
    {word:"precocious",chinese:"早熟的/過早發育的",sentence:"The <strong>precocious</strong> child could read at age three.",tip:"PRE(前)+COC(煮熟)+IOUS=提前煮熟=早熟的",emoji:"💒",roots:["pre","coc","ious"]},
    {word:"predatory",chinese:"掠奪的/食肉的",sentence:"<strong>Predatory</strong> lending practices harm the poor.",tip:"PRED(掠奪)+ATORY=掠奪性的",emoji:"🦅",roots:["pred","atory"]},
    {word:"presumptuous",chinese:"放肆的/冒昧的",sentence:"It was <strong>presumptuous</strong> of him to assume he'd be invited.",tip:"PRE(提前)+SUMPT(拿)+UOUS=提前就拿=放肆的",emoji:"😏",roots:["pre","sumpt","uous"]},
    {word:"prevalent",chinese:"普遍的/盛行的",sentence:"Obesity is increasingly <strong>prevalent</strong> worldwide.",tip:"PRE(前)+VAL(力量)+ENT=力量在前面=普遍的",emoji:"🌐",roots:["pre","val","ent"]},
    {word:"pristine",chinese:"原始的/嶄新的",sentence:"The beach was in <strong>pristine</strong> condition.",tip:"PRISTINE=最初的狀態=嶄新的",emoji:"✨",roots:["pristine"]},
    {word:"prodigal",chinese:"揮霍的/浪費的",sentence:"The <strong>prodigal</strong> son wasted his inheritance.",tip:"PRO(前)+DIG(驅趕)+AL=把財富趕走=揮霍的",emoji:"💸",roots:["pro","dig","al"]},
    {word:"prodigious",chinese:"巨大的/驚人的",sentence:"She showed <strong>prodigious</strong> talent from a young age.",tip:"PRO(前)+DIG(顯示)+IOUS=在眾人前顯示=驚人的",emoji:"🌟",roots:["pro","dig","ious"]},
    {word:"profane",chinese:"褻瀆的/世俗的",sentence:"He used <strong>profane</strong> language in public.",tip:"PRO(在外)+FANE(神殿)=在神殿外面=世俗的",emoji:"🤬",roots:["pro","fane"]},
    {word:"profuse",chinese:"大量的/充沛的",sentence:"She offered <strong>profuse</strong> apologies for the mistake.",tip:"PRO(前)+FUSE(流)=大量流出=大量的",emoji:"💦",roots:["pro","fuse"]},
    {word:"proliferate",chinese:"激增/繁殖",sentence:"Social media platforms have <strong>proliferated</strong> in recent years.",tip:"PRO(前)+LIFER(後代)+ATE=產生很多後代=激增",emoji:"📈",roots:["pro","lifer","ate"]},
    {word:"propensity",chinese:"傾向/癖好",sentence:"He has a <strong>propensity</strong> for exaggeration.",tip:"PRO(前)+PENS(傾斜)+ITY=往前傾斜=傾向",emoji:"↗️",roots:["pro","pens","ity"]},
    {word:"propriety",chinese:"禮儀/得體",sentence:"She always acted with strict <strong>propriety</strong>.",tip:"PROPRI(自己的)+ETY=符合自己身分=得體",emoji:"🎩",roots:["propri","ety"]},
    {word:"prosaic",chinese:"平淡的/乏味的",sentence:"The novel had a <strong>prosaic</strong> style.",tip:"PROS(散文)+AIC=像散文般平淡=乏味的",emoji:"📄",roots:["pros","aic"]},
    {word:"protagonist",chinese:"主角/主要人物",sentence:"The <strong>protagonist</strong> of the story faces many challenges.",tip:"PROTO(第一)+AGON(競賽)+IST=第一位競爭者=主角",emoji:"🎬",roots:["prot","agon","ist"]},
    {word:"provincial",chinese:"偏狹的/省的",sentence:"His <strong>provincial</strong> attitudes made him seem narrow-minded.",tip:"PROVINCE(省份)+IAL=小省份的=偏狹的",emoji:"🏘️",roots:["provinci","al"]},
    {word:"provocative",chinese:"挑釁的/引起反應的",sentence:"Her <strong>provocative</strong> remarks started a heated debate.",tip:"PRO(前)+VOC(叫)+ATIVE=在人前叫=挑釁的",emoji:"😤",roots:["pro","voc","ative"]},
    {word:"prudent",chinese:"謹慎的/精明的",sentence:"It would be <strong>prudent</strong> to save more money.",tip:"PRUD(有遠見)+ENT=有遠見的=謹慎的",emoji:"🧐",roots:["prud","ent"]},
    {word:"pungent",chinese:"刺鼻的/辛辣的",sentence:"The <strong>pungent</strong> smell of garlic filled the kitchen.",tip:"PUNG(刺)+ENT=刺鼻子的=刺鼻的",emoji:"🧄",roots:["pung","ent"]},
    {word:"quandary",chinese:"困境/進退兩難",sentence:"She was in a <strong>quandary</strong> about which job to take.",tip:"QUANDARY=不知該選哪邊=困境",emoji:"🤷",roots:["quandary"]},
    {word:"querulous",chinese:"愛抱怨的/牢騷的",sentence:"The <strong>querulous</strong> patient complained about everything.",tip:"QUER(抱怨)+ULOUS=很愛抱怨的",emoji:"😩",roots:["quer","ul","ous"]},
    {word:"quintessential",chinese:"典型的/精髓的",sentence:"She is the <strong>quintessential</strong> professional.",tip:"QUINT(第五)+ESSENT(本質)+IAL=第五元素=精髓的",emoji:"💫",roots:["quint","essent","ial"]},
    {word:"quixotic",chinese:"不切實際的/空想的",sentence:"His <strong>quixotic</strong> quest was doomed to fail.",tip:"QUIXOT(乘乘德)=像乘乘德般=不切實際的",emoji:"🏇",roots:["quixot","ic"]},
    {word:"rancor",chinese:"怨恨/仇恨",sentence:"She held no <strong>rancor</strong> toward her former rival.",tip:"RANC(惡臭)+OR=臭的感情=怨恨",emoji:"😠",roots:["ranc","or"]},
    {word:"raze",chinese:"夷為平地/拆毀",sentence:"The old factory was <strong>razed</strong> to make way for a park.",tip:"RAZE=刮到地面=夷為平地",emoji:"🏗️",roots:["raze"]},
    {word:"rebuke",chinese:"斥責/指責",sentence:"The manager <strong>rebuked</strong> him for being late.",tip:"RE(回)+BUKE(打)=打回去=斥責",emoji:"👊",roots:["re","buke"]},
    {word:"recalcitrant",chinese:"不服從的/頑抗的",sentence:"The <strong>recalcitrant</strong> prisoner refused to cooperate.",tip:"RE(回)+CALCIT(踢)+RANT=踢回去=不服從的",emoji:"🐎",roots:["re","calcit","rant"]},
    {word:"recant",chinese:"撤回/放棄信仰",sentence:"Under pressure, he <strong>recanted</strong> his earlier statements.",tip:"RE(回)+CANT(唱)=把唱過的收回=撤回",emoji:"🔙",roots:["re","cant"]},
    {word:"recluse",chinese:"隱居者/隱士",sentence:"The author became a <strong>recluse</strong> in his later years.",tip:"RE(回)+CLUSE(關)=把自己關起來=隱居者",emoji:"🏚️",roots:["re","cluse"]},
    {word:"reconcile",chinese:"和解/調和",sentence:"They finally <strong>reconciled</strong> after years of conflict.",tip:"RE(再)+CON(一起)+CILE(召集)=再召集在一起=和解",emoji:"🤝",roots:["re","con","cile"]},
    {word:"redeem",chinese:"贖回/彌補",sentence:"He tried to <strong>redeem</strong> himself with good deeds.",tip:"RE(回)+DEEM(買)=買回來=贖回",emoji:"💫",roots:["re","deem"]},
    {word:"relegate",chinese:"貶低/降級",sentence:"The team was <strong>relegated</strong> to the lower division.",tip:"RE(回)+LEG(派)+ATE=打發回去=降級",emoji:"⬇️",roots:["re","leg","ate"]},
    {word:"relinquish",chinese:"放棄/交出",sentence:"He was forced to <strong>relinquish</strong> control.",tip:"RE(回)+LINQU(留)+ISH=留下不要了=放棄",emoji:"✋",roots:["re","linqu","ish"]},
    {word:"reminiscent",chinese:"令人想起的/回憶的",sentence:"The style is <strong>reminiscent</strong> of classical art.",tip:"RE(再)+MINI(記憶)+SCENT=再次記起的=回憶的",emoji:"💭",roots:["re","mini","scent"]},
    {word:"remorse",chinese:"悔恨/自責",sentence:"He felt deep <strong>remorse</strong> for what he had done.",tip:"RE(再)+MORSE(咬)=良心再次咬=悔恨",emoji:"😔",roots:["re","morse"]},
    {word:"renounce",chinese:"宣布放棄/斷絕",sentence:"She <strong>renounced</strong> her claim to the property.",tip:"RE(回)+NOUNCE(宣布)=宣布退回=放棄",emoji:"🚫",roots:["re","nounce"]},
    {word:"repercussion",chinese:"後果/影響",sentence:"The decision had serious <strong>repercussions</strong>.",tip:"RE(回)+PER(通過)+CUSS(打)+ION=打擊回來=後果",emoji:"🔄",roots:["re","per","cuss","ion"]},
    {word:"replete",chinese:"充滿的/飽滿的",sentence:"The report was <strong>replete</strong> with errors.",tip:"RE(再)+PLETE(填滿)=再次填滿=充滿的",emoji:"🫙",roots:["re","plete"]},
    {word:"reprehensible",chinese:"應受譴責的/可恥的",sentence:"His behavior was utterly <strong>reprehensible</strong>.",tip:"RE(回)+PRE(前)+HENS(抓)+IBLE=該被抓回來的=可恥的",emoji:"👎",roots:["re","pre","hens","ible"]},
    {word:"repudiate",chinese:"拒絕/否認",sentence:"She <strong>repudiated</strong> the allegations.",tip:"RE(回)+PUD(腳)+IATE=用腳踢回去=拒絕",emoji:"✋",roots:["re","pud","iate"]},
    {word:"resilient",chinese:"有彈性的/能恢復的",sentence:"Children are remarkably <strong>resilient</strong>.",tip:"RE(回)+SIL(跳)+IENT=跳回來的=有彈性的",emoji:"🏀",roots:["re","sil","ient"]},
    {word:"resolute",chinese:"堅定的/果斷的",sentence:"She remained <strong>resolute</strong> in her decision.",tip:"RE(加強)+SOL(鬆開)+UTE=徹底解開猶豫=堅定的",emoji:"💪",roots:["re","sol","ute"]},
    {word:"resurgence",chinese:"復興/再起",sentence:"There has been a <strong>resurgence</strong> of interest in jazz.",tip:"RE(再)+SURG(升起)+ENCE=再次升起=復興",emoji:"🌅",roots:["re","surg","ence"]},
    {word:"reticent",chinese:"沉默的/不愛說話的",sentence:"He was <strong>reticent</strong> about his past.",tip:"RE(回)+TIC(沉默)+ENT=保持沉默=不愛說話的",emoji:"🤐",roots:["re","tic","ent"]},
    {word:"retribution",chinese:"報應/懲罰",sentence:"He feared <strong>retribution</strong> for his crimes.",tip:"RE(回)+TRIBUT(付)+ION=付回去=報應",emoji:"⚡",roots:["re","tribut","ion"]},
    {word:"revere",chinese:"尊敬/崇拜",sentence:"The students <strong>revered</strong> their wise professor.",tip:"RE(再)+VERE(敬畏)=再次敬畏=尊敬",emoji:"🙏",roots:["re","vere"]},
    {word:"rhetoric",chinese:"修辭/辯術",sentence:"His speech was more <strong>rhetoric</strong> than substance.",tip:"RHETOR(演說家)+IC=演說家的技巧=修辭",emoji:"🎙️",roots:["rhetor","ic"]},
    {word:"rudimentary",chinese:"基本的/初步的",sentence:"He has only a <strong>rudimentary</strong> knowledge of French.",tip:"RUDI(粗糙)+MENT+ARY=粗糙初步的=基本的",emoji:"📐",roots:["rudi","ment","ary"]},
    {word:"sacrilege",chinese:"褻瀆/冒瀆",sentence:"Destroying the ancient temple was considered <strong>sacrilege</strong>.",tip:"SACRI(神聖)+LEGE(偷)=偷竊神聖之物=褻瀆",emoji:"⛪",roots:["sacri","lege"]},
    {word:"sagacious",chinese:"睿智的/精明的",sentence:"The <strong>sagacious</strong> leader foresaw the crisis.",tip:"SAG(智慧)+ACIOUS=有智慧的=睿智的",emoji:"🦉",roots:["sag","acious"]},
    {word:"salient",chinese:"顯著的/突出的",sentence:"The <strong>salient</strong> features of the plan were discussed.",tip:"SAL(跳)+IENT=跳出來的=顯著的",emoji:"📌",roots:["sal","ient"]},
    {word:"sardonic",chinese:"嘲諷的/譏笑的",sentence:"He gave a <strong>sardonic</strong> smile.",tip:"SARDONIC=撒丁島的有毒植物讓人笑=嘲諷的",emoji:"😏",roots:["sardon","ic"]},
    {word:"scrupulous",chinese:"一絲不苟的/嚴謹的",sentence:"She was <strong>scrupulous</strong> about following the rules.",tip:"SCRUP(小石子)+ULOUS=連小石子都注意=一絲不苟的",emoji:"🔍",roots:["scrup","ul","ous"]},
    {word:"sedentary",chinese:"久坐的/靜態的",sentence:"A <strong>sedentary</strong> lifestyle increases health risks.",tip:"SED(坐)+ENT+ARY=坐著的=久坐的",emoji:"🪑",roots:["sed","ent","ary"]}
  ]
};
