WORD_DATA["competition_upper"] = {

    name: "公館進階",
    color: "#8b5cf6",
    words: [
      {word:"nurse",definition:"a person whose job is to help sick people get better",chinese:"護士",sentence:"The <strong>nurse</strong> takes care of me.",tip:"NURSE 和 PURSE 押韻",emoji:"👩‍⚕️",roots:["nurse"]},
      {word:"singer",definition:"a person whose job is to sing songs",chinese:"歌手",sentence:"She is a famous <strong>singer</strong>.",tip:"SINGER = SING + ER（唱歌的人）",emoji:"🎤",roots:["sing","er"]},
      {word:"police officer",definition:"a person whose job is to keep people safe and stop crime",chinese:"警察",sentence:"The <strong>police officer</strong> helps people.",tip:"比 policeman 更中性正式；officer 由 office（職務）＋ -er（做…的人）構成",emoji:"👮",roots:["police officer"]},
      {word:"mailman",definition:"a person whose job is to bring letters to your home",chinese:"郵差",sentence:"The <strong>mailman</strong> brings letters.",tip:"MAILMAN = MAIL + MAN",emoji:"📮",roots:["mail","man"]},
      {word:"uncle",definition:"the brother of your mother or father",chinese:"叔叔/伯伯",sentence:"My <strong>uncle</strong> lives in Taipei.",tip:"UNCLE 是單一語素，不可再拆；整個字唸 /ˈʌŋkəl/",emoji:"👨",roots:["uncle"]},
      {word:"aunt",definition:"the sister of your mother or father",chinese:"阿姨/姑姑",sentence:"My <strong>aunt</strong> gives me candy.",tip:"AUNT 美式發 /ænt/",emoji:"👩",roots:["aunt"]},
      {word:"pink",definition:"a light red color, like many flowers",chinese:"粉紅色",sentence:"I like <strong>pink</strong> flowers.",tip:"PINK 和 THINK 押韻",emoji:"💗",roots:["pink"]},
      {word:"brown",definition:"the color of dirt, wood, or chocolate",chinese:"棕色",sentence:"The tree is <strong>brown</strong>.",tip:"BROWN 和 DOWN 押韻",emoji:"🟤",roots:["brown"]},
      {word:"gray",definition:"a color between black and white, like a rainy sky",chinese:"灰色",sentence:"The sky is <strong>gray</strong> today.",tip:"GRAY（美式）= GREY（英式）",emoji:"🩶",roots:["gray"]},
      {word:"purple",definition:"a color made by mixing red and blue",chinese:"紫色",sentence:"I have a <strong>purple</strong> bag.",tip:"PURPLE 有兩個 P",emoji:"🟣",roots:["purple"]},
      {word:"bread",definition:"a soft food made from flour and baked in an oven",chinese:"麵包",sentence:"I eat <strong>bread</strong> for breakfast.",tip:"BREAD 的 EA 發短音 /e/",emoji:"🍞",roots:["bread"]},
      {word:"breakfast",definition:"the first meal you eat in the morning",chinese:"早餐",sentence:"I eat eggs for <strong>breakfast</strong>.",tip:"BREAKFAST = BREAK + FAST（打破禁食）",emoji:"🥞",roots:["break","fast"]},
      {word:"coffee",definition:"a hot brown drink that many grown-ups drink",chinese:"咖啡",sentence:"Dad drinks <strong>coffee</strong> every morning.",tip:"COFFEE 有兩個 F 和兩個 E",emoji:"☕",roots:["coffee"]},
      {word:"cookies",definition:"small, sweet, flat treats that are baked",chinese:"餅乾",sentence:"Mom makes <strong>cookies</strong> for us.",tip:"COOKIE 源自荷蘭語 koekje（小蛋糕），不是 COOK＋IES",emoji:"🍪",roots:["cookies"]},
      {word:"dinner",definition:"the big meal you eat in the evening",chinese:"晚餐",sentence:"We have <strong>dinner</strong> at six.",tip:"DINNER 有兩個 N",emoji:"🍽️",roots:["dinner"]},
      {word:"food",definition:"things you eat to live and grow",chinese:"食物",sentence:"I like Chinese <strong>food</strong>.",tip:"FOOD 有兩個 O",emoji:"🍲",roots:["food"]},
      {word:"fruit",definition:"the sweet part of a plant you eat, like apples or grapes",chinese:"水果",sentence:"I eat <strong>fruit</strong> every day.",tip:"FRUIT 的 UI 發 /u:/ 的音",emoji:"🍇",roots:["fruit"]},
      {word:"lunch",definition:"the meal you eat in the middle of the day",chinese:"午餐",sentence:"We have <strong>lunch</strong> at noon.",tip:"LUNCH 和 BUNCH 押韻",emoji:"🥪",roots:["lunch"]},
      {word:"noodles",definition:"long thin strips of dough often eaten in soup",chinese:"麵條",sentence:"I like <strong>noodles</strong> with soup.",tip:"NOODLES 有兩個 O",emoji:"🍜",roots:["noodles"]},
      {word:"sandwich",definition:"food made of two pieces of bread with filling inside",chinese:"三明治",sentence:"I make a <strong>sandwich</strong> for lunch.",tip:"三明治是伯爵的名字！",emoji:"🥪",roots:["sandwich"]},
      {word:"soup",definition:"a warm liquid food you eat with a spoon",chinese:"湯",sentence:"This <strong>soup</strong> is very hot.",tip:"SOUP 和 GROUP 押韻",emoji:"🍲",roots:["soup"]},
      {word:"candy",definition:"a sweet treat made mostly of sugar",chinese:"糖果",sentence:"Don't eat too much <strong>candy</strong>.",tip:"CANDY 和 HANDY 押韻",emoji:"🍬",roots:["candy"]},
      {word:"pie",definition:"a baked food with fruit inside a pastry crust",chinese:"派",sentence:"Mom makes apple <strong>pie</strong>.",tip:"PIE 和 FLY 押韻",emoji:"🥧",roots:["pie"]},
      {word:"moon",definition:"the big round thing that shines in the night sky",chinese:"月亮",sentence:"The <strong>moon</strong> is bright tonight.",tip:"MOON 有兩個 O",emoji:"🌙",roots:["moon"]},
      {word:"sky",definition:"the wide space above you where clouds and stars are",chinese:"天空",sentence:"The <strong>sky</strong> is blue.",tip:"SKY 和 FLY 押韻",emoji:"🌌",roots:["sky"]},
      {word:"star",definition:"a tiny bright light you see in the night sky",chinese:"星星",sentence:"I can see many <strong>star</strong>s at night.",tip:"STAR 和 CAR 押韻",emoji:"⭐",roots:["star"]},
      {word:"sun",definition:"the bright star that lights the day and warms us",chinese:"太陽",sentence:"The <strong>sun</strong> rises in the east.",tip:"SUN 和 FUN 押韻",emoji:"☀️",roots:["sun"]},
      {word:"tree",definition:"a tall plant with a wooden trunk and branches",chinese:"樹",sentence:"The <strong>tree</strong> is very tall.",tip:"TREE 有兩個 E",emoji:"🌳",roots:["tree"]},
      {word:"flower",definition:"the pretty, colorful part of a plant",chinese:"花",sentence:"The <strong>flower</strong> smells nice.",tip:"FLOWER 源自拉丁文 florem（花），不是 FLOW＋ER",emoji:"🌸",roots:["flower"]},
      {word:"spring",definition:"the warm season when flowers grow, after winter",chinese:"春天",sentence:"Flowers bloom in <strong>spring</strong>.",tip:"SPRING 也有彈簧的意思",emoji:"🌷",roots:["spring"]},
      {word:"summer",definition:"the hottest season of the year",chinese:"夏天",sentence:"I swim in <strong>summer</strong>.",tip:"SUMMER 有兩個 M",emoji:"🌞",roots:["summer"]},
      {word:"fall",definition:"the season after summer when leaves turn colors",chinese:"秋天",sentence:"Leaves change color in <strong>fall</strong>.",tip:"FALL 也有跌倒的意思",emoji:"🍂",roots:["fall"]},
      {word:"winter",definition:"the coldest season of the year, when it snows",chinese:"冬天",sentence:"It snows in <strong>winter</strong>.",tip:"用聯想記：WINTER 裡藏著 WIN，想成「冬天要贏過寒冷」（非真字根）",emoji:"❄️",roots:["winter"]},
      {word:"here",definition:"in or at this place, close to you",chinese:"這裡",sentence:"Come <strong>here</strong>, please.",tip:"HERE 和 THERE 是相反詞",emoji:"📍",roots:["here"]},
      {word:"there",definition:"in or at that place, away from you",chinese:"那裡",sentence:"The cat is over <strong>there</strong>.",tip:"THERE 和 HERE 是相反詞",emoji:"👉",roots:["there"]},
      {word:"shop",definition:"a place where you go to buy things",chinese:"商店",sentence:"I go to the <strong>shop</strong> with mom.",tip:"SHOP 和 STOP 押韻",emoji:"🏪",roots:["shop"]},
      {word:"hospital",definition:"a big place where doctors help sick or hurt people",chinese:"醫院",sentence:"The doctor works at the <strong>hospital</strong>.",tip:"源自拉丁文 hospes（客人／主人）＋ -al；與 hotel、hospitality 同源",emoji:"🏥",roots:["hospital"]},
      {word:"library",definition:"a place where you can read and borrow books",chinese:"圖書館",sentence:"I read books at the <strong>library</strong>.",tip:"源自拉丁文 liber（書）＋ -ary（場所）；注意有兩個 R",emoji:"📚",roots:["library"]},
      {word:"police station",definition:"the place where police officers work",chinese:"警察局",sentence:"Go to the <strong>police station</strong> for help.",tip:"複合詞：police（警察）＋ station（站／所）",emoji:"🚔",roots:["police station"]},
      {word:"post office",definition:"a place where you send letters and buy stamps",chinese:"郵局",sentence:"I buy stamps at the <strong>post office</strong>.",tip:"複合詞：post（郵件）＋ office（辦公處）",emoji:"🏤",roots:["post office"]},
      {word:"restaurant",definition:"a place where you go out to eat a meal",chinese:"餐廳",sentence:"We eat at a <strong>restaurant</strong>.",tip:"源自法文 restaurer（恢復體力）＋ -ant；拼法長要小心",emoji:"🍽️",roots:["restaurant"]},
      {word:"classroom",definition:"the room in school where you learn with your teacher",chinese:"教室",sentence:"Our <strong>classroom</strong> is big.",tip:"CLASSROOM = CLASS + ROOM",emoji:"🏫",roots:["class","room"]},
      {word:"sofa",definition:"a long soft seat where a few people can sit",chinese:"沙發",sentence:"I sit on the <strong>sofa</strong>.",tip:"SOFA 只有四個字母",emoji:"🛋️",roots:["sofa"]},
      {word:"TV",definition:"a screen that shows cartoons, movies, and other programs",chinese:"電視",sentence:"I watch <strong>TV</strong> after dinner.",tip:"TV = TELEVISION 的縮寫",emoji:"📺",roots:["TV"]},
      {word:"bathroom",definition:"the room with a toilet and sink where you wash up",chinese:"浴室",sentence:"I brush my teeth in the <strong>bathroom</strong>.",tip:"BATHROOM = BATH + ROOM",emoji:"🚿",roots:["bath","room"]},
      {word:"bedroom",definition:"the room where you sleep at night",chinese:"臥室",sentence:"I sleep in my <strong>bedroom</strong>.",tip:"BEDROOM = BED + ROOM",emoji:"🛏️",roots:["bed","room"]},
      {word:"kitchen",definition:"the room where you cook and make food",chinese:"廚房",sentence:"Mom cooks in the <strong>kitchen</strong>.",tip:"用聯想記：KITCHEN 裡藏著 KIT（工具組），廚房裡工具多（非真字根）",emoji:"👨‍🍳",roots:["kitchen"]},
      {word:"living room",definition:"the room where a family sits and relaxes together",chinese:"客廳",sentence:"We watch TV in the <strong>living room</strong>.",tip:"LIVING ROOM = 生活 + 房間",emoji:"🛋️",roots:["living room"]},
      {word:"telephone",definition:"a machine you use to talk to someone far away",chinese:"電話",sentence:"Answer the <strong>telephone</strong>, please.",tip:"TELEPHONE = TELE（遠）+ PHONE（聲音）",emoji:"📞",roots:["telephone"]},
      {word:"some",definition:"a few of something, but not all of it",chinese:"一些",sentence:"I have <strong>some</strong> candies.",tip:"SOME 的 O 發 /ʌ/ 的音",emoji:"🔢",roots:["some"]},
      {word:"thirteen",definition:"the number 13, which is ten plus three",chinese:"十三",sentence:"I am <strong>thirteen</strong> years old.",tip:"THIRTEEN(13) 拼字注意：開頭是 THIR-（和 THIRTY 一樣），不是 THREE",emoji:"1️⃣3️⃣",roots:["thirteen"]},
      {word:"fourteen",definition:"the number 14, which is ten plus four",chinese:"十四",sentence:"There are <strong>fourteen</strong> students.",tip:"FOURTEEN = FOUR + TEEN",emoji:"1️⃣4️⃣",roots:["four","teen"]},
      {word:"fifteen",definition:"the number 15, which is ten plus five",chinese:"十五",sentence:"I have <strong>fifteen</strong> books.",tip:"FIFTEEN(15) 拼字注意：開頭是 FIF-（和 FIFTY 一樣），不是 FIVE",emoji:"1️⃣5️⃣",roots:["fifteen"]},
      {word:"sixteen",definition:"the number 16, which is ten plus six",chinese:"十六",sentence:"She is <strong>sixteen</strong> years old.",tip:"SIXTEEN = SIX + TEEN",emoji:"1️⃣6️⃣",roots:["six","teen"]},
      {word:"seventeen",definition:"the number 17, which is ten plus seven",chinese:"十七",sentence:"There are <strong>seventeen</strong> boys.",tip:"SEVENTEEN = SEVEN + TEEN",emoji:"1️⃣7️⃣",roots:["seven","teen"]},
      {word:"eighteen",definition:"the number 18, which is ten plus eight",chinese:"十八",sentence:"He is <strong>eighteen</strong> years old.",tip:"EIGHTEEN = EIGHT + EEN：-teen(十幾) 的 T 和 EIGHT 尾巴的 T 合併，只留一個 T，所以拼成 -EEN",emoji:"1️⃣8️⃣",roots:["eighteen"]},
      {word:"nineteen",definition:"the number 19, which is ten plus nine",chinese:"十九",sentence:"I have <strong>nineteen</strong> toys.",tip:"NINETEEN = NINE + TEEN",emoji:"1️⃣9️⃣",roots:["nine","teen"]},
      {word:"twenty",definition:"the number 20, which is two tens",chinese:"二十",sentence:"There are <strong>twenty</strong> chairs.",tip:"TWENTY 來自 TWO",emoji:"2️⃣",roots:["twenty"]},
      {word:"thirty",definition:"the number 30, which is three tens",chinese:"三十",sentence:"Dad is <strong>thirty</strong> years old.",tip:"THIRTY 來自 THREE",emoji:"3️⃣",roots:["thirty"]},
      {word:"forty",definition:"the number 40, which is four tens",chinese:"四十",sentence:"There are <strong>forty</strong> students.",tip:"FORTY 沒有 U！（不是 FOURTY）",emoji:"4️⃣",roots:["forty"]},
      {word:"fifty",definition:"the number 50, which is five tens",chinese:"五十",sentence:"Grandma is <strong>fifty</strong> years old.",tip:"FIFTY(50) 來自 FIVE；拼字開頭是 FIF-（和 FIFTEEN 一樣），不是 FIVE",emoji:"5️⃣",roots:["fifty"]},
      {word:"sixty",definition:"the number 60, which is six tens",chinese:"六十",sentence:"There are <strong>sixty</strong> minutes in an hour.",tip:"SIXTY = SIX + -TY（-ty＝「幾十」的字尾）",emoji:"6️⃣",roots:["sixty"]},
      {word:"seventy",definition:"the number 70, which is seven tens",chinese:"七十",sentence:"Grandpa is <strong>seventy</strong> years old.",tip:"SEVENTY = SEVEN + -TY（-ty＝「幾十」的字尾）",emoji:"7️⃣",roots:["seventy"]},
      {word:"eighty",definition:"the number 80, which is eight tens",chinese:"八十",sentence:"Great grandma is <strong>eighty</strong>.",tip:"EIGHTY = EIGHT + Y：-ty(幾十) 的 T 和 EIGHT 尾巴的 T 合併，只留一個 T，所以拼成 -Y",emoji:"8️⃣",roots:["eighty"]},
      {word:"ninety",definition:"the number 90, which is nine tens",chinese:"九十",sentence:"There are <strong>ninety</strong> pages.",tip:"NINETY = NINE + -TY（保留 NINE 的 E；-ty＝「幾十」的字尾）",emoji:"9️⃣",roots:["ninety"]},
      {word:"hundred",definition:"the number 100, which is ten tens",chinese:"一百",sentence:"I have one <strong>hundred</strong> stickers.",tip:"用聯想記：HUNDRED 結尾是 RED，但和顏色 red 無關（非真字根）",emoji:"💯",roots:["hundred"]},
      {word:"bus",definition:"a big long vehicle that carries many people on roads",chinese:"公車",sentence:"I take the <strong>bus</strong> to school.",tip:"BUS 只有三個字母",emoji:"🚌",roots:["bus"]},
      {word:"bike",definition:"a vehicle with two wheels that you ride and pedal",chinese:"腳踏車",sentence:"I ride my <strong>bike</strong> to the park.",tip:"BIKE 和 LIKE 押韻",emoji:"🚲",roots:["bike"]},
      {word:"car",definition:"a vehicle with four wheels that carries a few people",chinese:"汽車",sentence:"Dad drives a <strong>car</strong>.",tip:"CAR 和 STAR 押韻",emoji:"🚗",roots:["car"]},
      {word:"MRT",definition:"the fast train that carries people around a city",chinese:"捷運",sentence:"I take the <strong>MRT</strong> to school.",tip:"MRT = Mass Rapid Transit",emoji:"🚇",roots:["MRT"]},
      {word:"plane",definition:"a machine with wings that flies people through the sky",chinese:"飛機",sentence:"The <strong>plane</strong> flies in the sky.",tip:"PLANE 和 RAIN 有類似的音",emoji:"✈️",roots:["plane"]},
      {word:"ship",definition:"a very big boat that carries people across the sea",chinese:"船",sentence:"The <strong>ship</strong> sails on the sea.",tip:"SHIP 和 TIP 押韻",emoji:"🚢",roots:["ship"]},
      {word:"taxi",definition:"a car you pay to drive you where you want to go",chinese:"計程車",sentence:"We take a <strong>taxi</strong> to the airport.",tip:"TAXI 是 TAXICAB 的縮寫（源自計費表 taximeter）",emoji:"🚕",roots:["taxi"]},
      {word:"train",definition:"a long line of cars that ride on tracks",chinese:"火車",sentence:"The <strong>train</strong> is very fast.",tip:"TRAIN 和 RAIN 押韻",emoji:"🚂",roots:["train"]},
      {word:"bad",definition:"not good, or not the way it should be",chinese:"壞的",sentence:"That is a <strong>bad</strong> idea.",tip:"BAD 和 SAD 押韻",emoji:"👎",roots:["bad"]},
      {word:"good",definition:"nice, or the way it should be",chinese:"好的",sentence:"You are a <strong>good</strong> student.",tip:"GOOD 有兩個 O",emoji:"👍",roots:["good"]},
      {word:"happy",definition:"feeling glad and full of joy",chinese:"快樂的",sentence:"I am <strong>happy</strong> today.",tip:"HAPPY = HAP（好運，如 happen、mishap）+ -Y；P 要雙寫",emoji:"😊",roots:["happy"]},
      {word:"mad",definition:"feeling very angry at someone or something",chinese:"生氣的",sentence:"Don't be <strong>mad</strong> at me.",tip:"MAD 和 BAD 押韻",emoji:"😠",roots:["mad"]},
      {word:"sad",definition:"feeling unhappy, like you want to cry",chinese:"傷心的",sentence:"I feel <strong>sad</strong> when my friend leaves.",tip:"SAD 和 BAD 押韻",emoji:"😢",roots:["sad"]},
      {word:"sick",definition:"not feeling well in your body",chinese:"生病的",sentence:"I am <strong>sick</strong> today.",tip:"SICK 和 KICK 押韻",emoji:"🤒",roots:["sick"]},
      {word:"angry",definition:"feeling mad and upset, wanting to shout or fight",chinese:"生氣的",sentence:"The dog looks <strong>angry</strong>.",tip:"ANGRY 來自 ANGER（怒氣）：去 E 加 Y",emoji:"😤",roots:["angry"]},
      {word:"excited",definition:"feeling very happy and can't wait for something fun",chinese:"興奮的",sentence:"I am <strong>excited</strong> about the trip.",tip:"EXCITED = EXCITE + D",emoji:"🤩",roots:["excited"]},
      {word:"hungry",definition:"feeling that you want or need to eat food",chinese:"餓的",sentence:"I am very <strong>hungry</strong>.",tip:"HUNGRY 來自 HUNGER（飢餓）：去 E 加 Y",emoji:"😋",roots:["hungry"]},
      {word:"tired",definition:"feeling that you need to rest or sleep",chinese:"累的",sentence:"I am <strong>tired</strong> after running.",tip:"TIRED = TIRE + D",emoji:"😫",roots:["tired"]},
      {word:"coat",definition:"a warm piece of clothing you put on over your shirt when it is cold",chinese:"外套",sentence:"Wear your <strong>coat</strong>. It's cold.",tip:"COAT 和 BOAT 押韻",emoji:"🧥",roots:["coat"]},
      {word:"glasses",definition:"things you wear over your eyes to help you see better",chinese:"眼鏡",sentence:"I wear <strong>glasses</strong> to read.",tip:"GLASSES 永遠用複數",emoji:"👓",roots:["glasses"]},
      {word:"pants",definition:"clothes that cover each leg from your waist to your feet",chinese:"褲子",sentence:"I wear blue <strong>pants</strong>.",tip:"PANTS 永遠用複數",emoji:"👖",roots:["pants"]},
      {word:"shoes",definition:"things you wear on your feet to walk outside",chinese:"鞋子",sentence:"Put on your <strong>shoes</strong>.",tip:"SHOES 永遠用複數",emoji:"👟",roots:["shoes"]},
      {word:"shorts",definition:"short pants that stop above your knees",chinese:"短褲",sentence:"I wear <strong>shorts</strong> in summer.",tip:"SHORTS = SHORT + S",emoji:"🩳",roots:["shorts"]},
      {word:"socks",definition:"soft clothes you wear on your feet inside your shoes",chinese:"襪子",sentence:"I wear white <strong>socks</strong>.",tip:"SOCKS 永遠用複數",emoji:"🧦",roots:["socks"]},
      {word:"T-shirt",definition:"a soft cotton top with short sleeves",chinese:"T恤",sentence:"I wear a <strong>T-shirt</strong> in summer.",tip:"因為形狀像字母T",emoji:"👕",roots:["T-shirt"]},
      {word:"jacket",definition:"a light, warm piece of clothing you wear over your shirt",chinese:"夾克",sentence:"Bring your <strong>jacket</strong>.",tip:"拼字記憶法(非字源):開頭像名字 JACK,幫助記拼字。真正字源：源自古法語 jaquet,是 jaque(平民短上衣)的指小形,-et 為指小後綴。",emoji:"🧥",roots:["jacket"]},
      {word:"sweater",definition:"a warm soft top with long sleeves for cold days",chinese:"毛衣",sentence:"I wear a <strong>sweater</strong> in winter.",tip:"SWEATER = SWEAT + ER（出汗的衣服）",emoji:"🧶",roots:["sweat","er"]},
      {word:"art",definition:"making pretty pictures and things by drawing or painting",chinese:"美術",sentence:"I love <strong>art</strong> class.",tip:"ART 只有三個字母",emoji:"🎨",roots:["art"]},
      {word:"Chinese",definition:"the language people speak in China and Taiwan",chinese:"中文",sentence:"I study <strong>Chinese</strong> every day.",tip:"CHINESE = CHINA + -ESE（-ese 是表「屬於某地方的人／語言」的字尾，如 Japanese、Taiwanese）",emoji:"🇹🇼",roots:["Chinese"]},
      {word:"English",definition:"the language people speak in America and Britain",chinese:"英文",sentence:"I learn <strong>English</strong> at school.",tip:"ENGLISH 源自 the Angles（盎格魯民族）這個古代部族",emoji:"🇬🇧",roots:["English"]},
      {word:"math",definition:"the school subject about numbers and shapes",chinese:"數學",sentence:"I like <strong>math</strong> class.",tip:"MATH = MATHEMATICS 的縮寫",emoji:"🔢",roots:["math"]},
      {word:"music",definition:"nice sounds made by singing or playing instruments",chinese:"音樂",sentence:"I play <strong>music</strong> on the piano.",tip:"MUSIC 源自希臘 Muse（繆思女神，掌管音樂藝術）",emoji:"🎵",roots:["music"]},
      {word:"PE",definition:"the school class where you run and play sports",chinese:"體育",sentence:"We run in <strong>PE</strong> class.",tip:"PE = Physical Education",emoji:"🏃",roots:["PE"]},
      {word:"science",definition:"the school subject about how nature and the world work",chinese:"科學/自然",sentence:"I love <strong>science</strong> experiments.",tip:"SCIENCE = SCI（拉丁 scire「知道、知識」）+ -ENCE（名詞字尾）：探究萬物的學問",emoji:"🔬",roots:["sci","ence"]},
      {word:"close",definition:"to shut something so it is not open",chinese:"關閉",sentence:"Please <strong>close</strong> the door.",tip:"CLOSE 當動詞和形容詞發音不同",emoji:"🚪",roots:["close"]},
      {word:"clean",definition:"to make something free from dirt and mess",chinese:"打掃/乾淨",sentence:"Please <strong>clean</strong> your room.",tip:"CLEAN 既是動詞也是形容詞",emoji:"🧹",roots:["clean"]},
      {word:"come",definition:"to move toward the person who is talking",chinese:"來",sentence:"<strong>Come</strong> here, please.",tip:"COME 的 O 發 /ʌ/ 的音",emoji:"🏃",roots:["come"]},
      {word:"drink",definition:"to take liquid into your mouth and swallow it",chinese:"喝",sentence:"I <strong>drink</strong> water every day.",tip:"DRINK 和 THINK 押韻",emoji:"🥤",roots:["drink"]},
      {word:"eat",definition:"to put food in your mouth, chew it, and swallow it",chinese:"吃",sentence:"I <strong>eat</strong> lunch at school.",tip:"EAT 和 MEAT 押韻",emoji:"🍽️",roots:["eat"]},
      {word:"feel",definition:"to have a feeling inside like happy, sad, or scared",chinese:"感覺",sentence:"I <strong>feel</strong> happy today.",tip:"FEEL 有兩個 E",emoji:"💭",roots:["feel"]},
      {word:"fly",definition:"to move through the air like a bird",chinese:"飛",sentence:"Birds can <strong>fly</strong>.",tip:"FLY 和 SKY 押韻",emoji:"🕊️",roots:["fly"]},
      {word:"get",definition:"to receive or be given something",chinese:"得到",sentence:"I <strong>get</strong> a gift from mom.",tip:"GET 有很多不同用法",emoji:"🎁",roots:["get"]},
      {word:"give",definition:"to hand something to someone to keep",chinese:"給",sentence:"I <strong>give</strong> her a book.",tip:"GIVE 和 LIVE 押韻",emoji:"🤲",roots:["give"]},
      {word:"go",definition:"to move from one place to another",chinese:"去",sentence:"I <strong>go</strong> to school.",tip:"GO 只有兩個字母",emoji:"🚶",roots:["go"]},
      {word:"listen",definition:"to pay attention to a sound with your ears",chinese:"聽",sentence:"<strong>Listen</strong> to the teacher.",tip:"LISTEN 是單一語素，不可再拆；拼字記憶法(非字源)：中間的 T 不發音",emoji:"👂",roots:["listen"]},
      {word:"live",definition:"to have your home in a certain place",chinese:"住/生活",sentence:"I <strong>live</strong> in Taipei.",tip:"LIVE 當動詞和形容詞發音不同",emoji:"🏠",roots:["live"]},
      {word:"ride",definition:"to sit on a bike or animal and make it go",chinese:"騎",sentence:"I <strong>ride</strong> my bike to school.",tip:"RIDE 和 SIDE 押韻",emoji:"🚴",roots:["ride"]},
      {word:"open",definition:"to move something so it is not shut",chinese:"打開",sentence:"<strong>Open</strong> the window, please.",tip:"OPEN 是單一語素，不可再拆；OPEN 和 CLOSE 是相反詞",emoji:"📂",roots:["open"]},
      {word:"play",definition:"to have fun with games or toys",chinese:"玩",sentence:"Let's <strong>play</strong> together.",tip:"PLAY 和 DAY 押韻",emoji:"🎮",roots:["play"]},
      {word:"run",definition:"to move fast on your feet, faster than walking",chinese:"跑",sentence:"I <strong>run</strong> to school.",tip:"RUN 和 FUN 押韻",emoji:"🏃",roots:["run"]},
      {word:"say",definition:"to speak words out loud",chinese:"說",sentence:"What did you <strong>say</strong>?",tip:"SAY 和 DAY 押韻",emoji:"🗣️",roots:["say"]},
      {word:"see",definition:"to notice something with your eyes",chinese:"看見",sentence:"I <strong>see</strong> a bird.",tip:"SEE 有兩個 E",emoji:"👀",roots:["see"]},
      {word:"sit",definition:"to rest your body on a chair with your bottom",chinese:"坐",sentence:"Please <strong>sit</strong> down.",tip:"SIT 和 HIT 押韻",emoji:"💺",roots:["sit"]},
      {word:"drive",definition:"to make a car go and steer it where you want",chinese:"開車",sentence:"Mom can <strong>drive</strong>.",tip:"DRIVE 和 FIVE 押韻",emoji:"🚗",roots:["drive"]},
      {word:"speak",definition:"to say words out loud with your voice",chinese:"說（語言）",sentence:"I can <strong>speak</strong> English.",tip:"SPEAK 比 SAY 更正式",emoji:"🗣️",roots:["speak"]},
      {word:"study",definition:"to read and learn about a subject",chinese:"學習/讀書",sentence:"I <strong>study</strong> English every day.",tip:"STUDY 可拆成 stud- + -y：字根 stud- 來自拉丁文，意為「鑽研、勤學」(同源詞 student、studio)；-y 為字尾。拼字提醒：第三人稱單數去 Y 加 IES → studies",emoji:"📚",roots:["study"]},
      {word:"take",definition:"to use a bus or car to go somewhere",chinese:"搭乘",sentence:"I <strong>take</strong> the bus to school.",tip:"TAKE 有很多不同用法",emoji:"🤲",roots:["take"]},
      {word:"talk",definition:"to say words to someone in a conversation",chinese:"說話/聊天",sentence:"I <strong>talk</strong> to my friend.",tip:"TALK 的 L 不發音！",emoji:"💬",roots:["talk"]},
      {word:"wear",definition:"to have clothes or a hat on your body",chinese:"穿",sentence:"I <strong>wear</strong> a hat.",tip:"WEAR 和 BEAR 押韻",emoji:"👔",roots:["wear"]},
      {word:"walk",definition:"to move forward by putting one foot in front of the other",chinese:"走路",sentence:"I <strong>walk</strong> to school.",tip:"WALK 的 L 不發音！",emoji:"🚶",roots:["walk"]},
      {word:"wash",definition:"to make something clean with water and soap",chinese:"洗",sentence:"<strong>Wash</strong> your hands.",tip:"WASH 的 A 發 /ɒ/ 的音",emoji:"🧼",roots:["wash"]},
      {word:"watch",definition:"to look at something for a while",chinese:"看（專注地）",sentence:"I <strong>watch</strong> TV after dinner.",tip:"WATCH 也有手錶的意思",emoji:"📺",roots:["watch"]},
      {word:"work",definition:"the job a person does to earn money",chinese:"工作",sentence:"Dad goes to <strong>work</strong> every day.",tip:"WORK 和 WORD 只差一個字母",emoji:"💼",roots:["work"]},
      {word:"Japan",definition:"a country in Asia near Taiwan",chinese:"日本",sentence:"<strong>Japan</strong> is near Taiwan.",tip:"JAPAN 是單一語素的專有名詞，不可再拆；發音時重音在第二音節",emoji:"🇯🇵",roots:["Japan"]},
      {word:"Taiwan",definition:"an island country in Asia, east of China",chinese:"台灣",sentence:"I live in <strong>Taiwan</strong>.",tip:"TAIWAN 是單一語素的專有名詞，不可再拆；TAIWAN 是我們的家！",emoji:"🇹🇼",roots:["Taiwan"]},
      {word:"UK",definition:"a country in Europe that includes England",chinese:"英國",sentence:"The <strong>UK</strong> is in Europe.",tip:"UK = United Kingdom",emoji:"🇬🇧",roots:["UK"]},
      {word:"USA",definition:"a big country in North America, also called America",chinese:"美國",sentence:"The <strong>USA</strong> is very big.",tip:"USA = United States of America",emoji:"🇺🇸",roots:["USA"]},
      {word:"card",definition:"a folded paper you write a nice message on",chinese:"卡片",sentence:"I make a birthday <strong>card</strong>.",tip:"CARD 和 HARD 押韻",emoji:"💌",roots:["card"]},
      {word:"computer",definition:"a machine that stores information and helps you work and play",chinese:"電腦",sentence:"I use a <strong>computer</strong> to study.",tip:"COMPUTER = COM（一起、共同）+ PUT（計算，源自拉丁文 putare）+ ER（做…的機器）",emoji:"💻",roots:["com","put","er"]},
      {word:"e-mail",definition:"a message you send to someone through a computer",chinese:"電子郵件",sentence:"I send an <strong>e-mail</strong> to my friend.",tip:"E-MAIL = ELECTRONIC + MAIL",emoji:"📧",roots:["e-mail"]},
      {word:"bee",definition:"a small flying insect that makes honey and can sting",chinese:"蜜蜂",sentence:"The <strong>bee</strong> makes honey.",tip:"BEE 有兩個 E",emoji:"🐝",roots:["bee"]},
      {word:"duck",definition:"a bird with a flat beak that swims on water",chinese:"鴨子",sentence:"The <strong>duck</strong> swims in the pond.",tip:"DUCK 和 LUCK 押韻",emoji:"🦆",roots:["duck"]},
      {word:"chicken",definition:"a farm bird kept for its eggs and meat",chinese:"雞/雞肉",sentence:"I eat <strong>chicken</strong> for dinner.",tip:"CHICKEN = CHICK + EN",emoji:"🐔",roots:["chick","en"]},
      {word:"elephant",definition:"a very big gray animal with a long nose and big ears",chinese:"大象",sentence:"The <strong>elephant</strong> is very big.",tip:"ELEPHANT 的 PH 發 /f/ 的音",emoji:"🐘",roots:["elephant"]},
      {word:"dirty",definition:"not clean, covered with dirt or mud",chinese:"髒的",sentence:"Your hands are <strong>dirty</strong>.",tip:"DIRTY = DIRT（泥土、污垢）+ Y（形容詞字尾，表「充滿…的」）",emoji:"🤢",roots:["dirt","y"]}
    ]
};
